### ISSUE TITLE
Module not installable through packagist.org

### ISSUE THREAD

**Issue by pivulic** [Adyen/adyen-magento2#10]
### Problem
We are trying to install Adyen through https://packagist.org/packages/adyen/module-payment but it's currently failing because it can't find the latest 1.1.0 tagged version.

```
$ composer require adyen/module-payment:1.1.0
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package adyen/module-payment could not be found in any version, there may be a typo in the package name.
  Problem 2
    - justinrainbow/json-schema 1.6.1 requires php >=5.3.29 -> no matching package found.
    - justinrainbow/json-schema 1.6.1 requires php >=5.3.29 -> no matching package found.
    - Installation request for justinrainbow/json-schema == 1.6.1.0 -> satisfiable by justinrainbow/json-schema[1.6.1].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

Read <http://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

Installation failed, reverting ./composer.json to its original content.
```

### Expected Result
Could you update https://packagist.org/packages/adyen/module-payment with the latest release, similar to https://packagist.org/packages/magestore/module-bannerslider where they have 0.1.5?

**Comment by rikterbeek** [comment]
Hi Pablo,

I see the issue the version in my composer.json is not the same as release version. I will do a new release soon with some bug fixes and this will be solved as well.

Regards,
Rik
Adyen

**Comment by pivulic** [comment]
Thanks Rik! I guess I'll see the new release once you close this issue :)

**Comment by rikterbeek** [comment]
Hi Pablo,

The new release is done best to use this one. In packagist see https://packagist.org/packages/adyen/module-payment it is as well now updated.

Regards,
Rik
Adyen

**Comment by pivulic** [comment]
It works, I can now install the module! Well done as usual, and thanks for the quick feedback :)
