### ISSUE TITLE
PIX

### ISSUE THREAD

**Issue by jonathanribas** [Adyen/adyen-magento2#1000]
**Describe the solution you'd like**
Hi Adyen team,

[PIX](https://docs.adyen.com/payment-methods/pix) is becoming a very popular payment method in Brazil, are you guys planning to implement it?

Thanks in advance!

**Comment by acampos1916** [comment]
Hey @jonathanribas, absolutely. It will be supported with the version 7.0.0. You can already test it with the release candidate https://github.com/Adyen/adyen-magento2/releases/tag/7.0.0-rc.2

**Comment by jonathanribas** [comment]
Great, thank you!
