### ISSUE TITLE
[PW-4535] CSP List in Adyen Module not updated

### ISSUE THREAD

**Issue by willbrammer** [Adyen/adyen-magento2#1010]
**Describe the bug**
The CSP whitelist in Adyen is not up to date with the domains that Adyen use for payment processing. This can cause issues with "restrict" mode enabled in Magento 2: https://devdocs.magento.com/guides/v2.4/extension-dev-guide/security/content-security-policies.html#configure-a-modules-csp-mode

https://github.com/Adyen/adyen-magento2/blob/develop/etc/csp_whitelist.xml

**Magento version**
2.4.2

**Plugin version**
7.0.0

**Expectations**
We would expect Adyen to have an up to date CSP whitelist similar to what Braintree have provided here https://github.com/braintree/braintree-web-drop-in/issues/442#issuecomment-429330829

Or some documentation on what domains are used for processing payments

As we can see in the logs that the following domains being 

- adyenpayments.com - MERCHANTPREFIX-MERCHANTDOMAIN-checkout-live.adyenpayments.com 

We also see several domains being used for 3DS. 

Are we able to get a list like braintree have provided?

Thanks
Will

**Comment by acampos1916** [comment]
Hello @willbrammer, please note that we are in no way dictating how your CSP policy should be, as it is entirely up to you with regards to the risk that comes with a more relaxed CSP, and the below are just recommendations.

For the CSP policy we in general give no direct suggestions, and it is a policy decided by the merchant. One of the things you could consider is setting the policy to Report Only.

If you would not want to relax the CSP, and decide to whitelist them one by one, we unfortunately can't provide you with a list of all the issuer URLs available. It is not practical as the list can change and there can be many issuers to keep track of, making your CSP unscalable if you were to add the issuer URLs into your CSP. Moreover we would be whitelisting third-party domains without the merchant's consent.

An example of URLs to whitelist (note that this list is non-exhaustive as there is a large number of providers):
	• 3ds-secure.cardcomplete.com
	• ecclients.btrl.ro
	• bofp.erstebank.hu
	• www.clicksafe.lloydstsb.com
	• pay.activa-card.com
	• 3dsecure-1.wirecard.com
	• 3dsecure-2.wirecard.com
	• acssv.otpbank.hu
	• acs.sia.eu
	• idcheck.acs.touchtechpayments.com
	• sicher-bezahlen.sparkasse.at
	• secure5.arcot.com
	• www.securesuite.co.uk
	• bred.wlp-acs.com
	• bnpp-3ds.wlp-acs.com

I hope the above information helps in making a final decision.
