### ISSUE TITLE
[PW-4537] Giftcards unusable in v6.6.9 - v7.0.0

### ISSUE THREAD

**Issue by simonjanguapa** [Adyen/adyen-magento2#1011]
**Describe the bug**
We have recently updated the Adyen extension (Magento 2) for one of our clients. Our client was using an older version: 4.2.1.

Using giftcards to pay for an order no longer works since the update. We have tried the following versions of this repository: 6.6.9, 6.7.0 and 7.0.0.

In 6.6.9 and 6.7.0: The user receives the following error: "Error with payment method please select different payment method.". Adyen API returns "Invalid card number".

In 7.0.0: There are some input fields for your giftcard code but none of them is functional. Opening one of the giftcard payment methods opens _all_ giftcard payment methods. None of the payment methods (also non-giftcard methods!) work anymore as soon as the user selected one of the giftcard payment method.

**To Reproduce**

_Versions 6.6.9, 6.7.0 and 6.7.0_
1. Go to the backoffice of Adyen and enable all of the following giftcard payment methods: "vvvcadeaubon", "genericgiftcard", "boekenbon".
2. Go to your Magento 2 checkout. Click on one of the giftcard payment methods you have just enabled and click "Place order".
3. An error is visible on the frontend: "Error with payment method please select different payment method."
4. The response from the Adyen API is "Invalid card number".

_Additional steps for version 7.0.0 only_
- Clicking on one of the giftcard payment methods (step 2) opens all of the giftcard payment methods instead of just the one that you have clicked. See screenshot attached.
- The visible input fields are not usable and you can not use the 'Place Order' button because jQuery could not validate the form.
- None of the payment methods (also non-gifcard methods!) work anymore as soon as you have opened one (which opens them all) of the giftcard payment methods.

**Expected behavior**

_For versions 6.6.9 and 6.7.0_
Being forwarded to a secure payment page.

_For version 7.0.0_
Functional input fields to pay with one of the giftcards. 

**Magento version**
Tested on both 2.3.5-p2 and 2.4.2.

**Plugin version**
6.6.9, 6.7.0 and 7.0.0.

**Screenshots**

_Version 6.6.9 and 6.7.0_
On Chrome Version 89.0.4389.82, Ubuntu 20.04.
![image](https://user-images.githubusercontent.com/23055714/114725246-a2ceea00-9d3c-11eb-9879-8f0ff5eb3937.png)

_Version 7.0.0_
On Chrome Version 89.0.4389.82, Ubuntu 20.04.
![screenshot-mag development-2021 04 14-16_21_05](https://user-images.githubusercontent.com/23055714/114726190-7071bc80-9d3d-11eb-8bcb-75fab2765053.png)

**Comment by acampos1916** [comment]
Hello @simonjanguapa, thank you for the detailed report.

I can confirm the following issues in 7.0.0:

- Clicking on one type of giftcard PM will expand all giftcard PMs.
- Orders can't be placed with giftcard PMs. But the error message I got in the adyen/info.log is different: `Required field 'brand' is not provided.`

For the previous major version, 6.7.0, I could not reproduce the order placement issue. Can you check which PHP library is being used? This will affect the Adyen Checkout API version and might be the reason for your `Invalid card number` error. If the plugin and its dependencies were upgraded through Composer then this should be fine. You can also see the Checkout API version in adyen/info.log: `Request url to Adyen: https://checkout-test.adyen.com/checkout/vXX/payments`

I'll create internal tickets for the two confirmed issues and upgrade here any progress made.
