### ISSUE TITLE
Add one more status ("Complete") for confirmed payments

### ISSUE THREAD

**Issue by Coderimus** [Adyen/adyen-magento2#102]
Hello @rikterbeek !
The admin setting "Order status: payment confirmed" (module-payment/etc/adminhtml/system/adyen_required_settings.xml) uses the  `Magento\Sales\Model\Config\Source\Order\Status\Processing` as source model. As a result, for orders with confirmed payment we always get status "Processing" and this is quite confused: your payment confirmed but the order has processing status. 

You can check this at `Adyen\Payment\Model\Cron::_setPaymentAuthorized`:
1. Line 1363 - we get status Processing from the admin settings
2. Next, if order is not virtual and boleto we go to line 1415 and set the "Processing" status to the order

I think that it would be a good idea to add one more status - Complete - to the "Order status: payment confirmed" setting from the box. It can be added as separate source class `Adyen\Payment\Model\Config\Source\AuthStatus` with 2 properties:
```    
protected $_stateStatuses = [
        \Magento\Sales\Model\Order::STATE_PROCESSING,
        \Magento\Sales\Model\Order::STATE_COMPLETE
    ];
```
What do you think about this idea?

Sincerely yours,
Alexander

**Comment by rikterbeek** [comment]
Hi @Coderimus,

Looks like a possibility we can look into. Normally you only want the completed status if the product is shipped. Why is this not the case in your situation ?

Regards,
Rik
Adyen

**Comment by Coderimus** [comment]
Hello @rikterbeek !
Thank you for your reply. We faced with this problem even if the product was shipped because the `Adyen\Payment\Model\Cron::_setPaymentAuthorized` method takes the status from the admin and then in this condition 
`$status = (!empty($status)) ? $status : $this->_order->getStatus();` - line 1415
set it because the payment method was not "adyen_boleto" and product was not virtual. 

Regards,
Alexander

**Comment by rikterbeek** [comment]
Hi @Coderimus,

Adding complete status will conflict if it is not in a complete status already. So therefore we can't add it. It looks though that your flow is a bit different then Magento would like it. See attached image for the best flow. The capture call is done on invoice creation so what you can do best is ship after the capture notification is received (if you are on manual capture for auto capture this is already on authorization)

![image](https://cloud.githubusercontent.com/assets/5948499/25168816/390391bc-24e5-11e7-826d-6a94966c9a2b.png)


Regards,

**Comment by Coderimus** [comment]
Thank you @rikterbeek  for your complete and detail reply. We fixed this issue by our customization for our order workflow.
