### ISSUE TITLE
Magento Query Consumer are not workung due to missing class Adyen\Payment\Model\AdyenRequestMerchantSession

### ISSUE THREAD

**Issue by frostblogNet** [Adyen/adyen-magento2#1020]
**Describe the bug**
By starting query consumer we are getting this error:

2021-04-28 05:25:55] report.ERROR: Class Adyen\Payment\Model\AdyenRequestMerchantSession does not exist
#0 /var/www/shop/releases/feature-magento-2.4-update-786425/vendor/magento/framework/Code/Reader/ClassReader.php(24): ReflectionClass->__construct()
#1 /var/www/shop/releases/feature-magento-2.4-update-786425/vendor/magento/framework/ObjectManager/Definition/Runtime.php(54): Magento\Framework\Code\Reader\ClassReader->getConstructor()
#2 /var/www/shop/releases/feature-magento-2.4-update-786425/vendor/magento/framework/ObjectManager/Factory/Compiled.php(100): Magento\Framework\ObjectManager\Definition\Runtime->getParameters()
#3 /var/www/shop/releases/feature-magento-2.4-update-786425/vendor/magento/framework/ObjectManager/ObjectManager.php(56): Magento\Framework\ObjectManager\Factory\Compiled->create()
#4 /var/www/shop/releases/feature-magento-2.4-update-786425/vendor/magento/framework-message-queue/ConsumerFactory.php(167): Magento\Framework\ObjectManager\ObjectManager->create()
#5 /var/www/shop/releases/feature-magento-2.4-update-786425/vendor/magento/framework-message-queue/ConsumerFactory.php(101): Magento\Framework\MessageQueue\ConsumerFactory->getHandlersFromCommunicationConfig()
#6 /var/www/shop/releases/feature-magento-2.4-update-786425/vendor/magento/framework-message-queue/ConsumerFactory.php(75): Magento\Framework\MessageQueue\ConsumerFactory->createConsumerConfiguration()
#7 /var/www/shop/releases/feature-magento-2.4-update-786425/vendor/magento/module-message-queue/Console/StartConsumerCommand.php(89): Magento\Framework\MessageQueue\ConsumerFactory->get()
#8 /var/www/shop/releases/feature-magento-2.4-update-786425/vendor/symfony/console/Command/Command.php(255): Magento\MessageQueue\Console\StartConsumerCommand->execute()
#9 /var/www/shop/releases/feature-magento-2.4-update-786425/vendor/magento/framework/Interception/Interceptor.php(58): Symfony\Component\Console\Command\Command->run()
#10 /var/www/shop/releases/feature-magento-2.4-update-786425/vendor/magento/framework/Interception/Interceptor.php(138): Magento\MessageQueue\Console\StartConsumerCommand\Interceptor->___callParent()
#11 /var/www/shop/releases/feature-magento-2.4-update-786425/vendor/magento/framework/Interception/Interceptor.php(153): Magento\MessageQueue\Console\StartConsumerCommand\Interceptor->Magento\Framework\Interception\{closure}()
#12 /var/www/shop/releases/feature-magento-2.4-update-786425/generated/code/Magento/MessageQueue/Console/StartConsumerCommand/Interceptor.php(23): Magento\MessageQueue\Console\StartConsumerCommand\Interceptor->___callPlugins()
#13 /var/www/shop/releases/feature-magento-2.4-update-786425/generated/code/Magento/MessageQueue/Console/StartConsumerCommand/Proxy.php(143): Magento\MessageQueue\Console\StartConsumerCommand\Interceptor->run()
#14 /var/www/shop/releases/feature-magento-2.4-update-786425/vendor/symfony/console/Application.php(1009): Magento\MessageQueue\Console\StartConsumerCommand\Proxy->run()
#15 /var/www/shop/releases/feature-magento-2.4-update-786425/vendor/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand()
#16 /var/www/shop/releases/feature-magento-2.4-update-786425/vendor/magento/framework/Console/Cli.php(115): Symfony\Component\Console\Application->doRun()
#17 /var/www/shop/releases/feature-magento-2.4-update-786425/vendor/symfony/console/Application.php(149): Magento\Framework\Console\Cli->doRun()
#18 /var/www/shop/releases/feature-magento-2.4-update-786425/bin/magento(23): Symfony\Component\Console\Application->run()
#19 {main} [] []
[2021-04-28 05:25:57] report.ERROR: Class Adyen\Payment\Model\AdyenRequestMerchantSession does not exist
#0 /var/www/shop/releases/feature-magento-2.4-update-786425/vendor/magento/framework/Code/Reader/ClassReader.php(24): ReflectionClass->__construct()
#1 /var/www/shop/releases/feature-magento-2.4-update-786425/vendor/magento/framework/ObjectManager/Definition/Runtime.php(54): Magento\Framework\Code\Reader\ClassReader->getConstructor()
#2 /var/www/shop/releases/feature-magento-2.4-update-786425/vendor/magento/framework/ObjectManager/Factory/Compiled.php(100): Magento\Framework\ObjectManager\Definition\Runtime->getParameters()
#3 /var/www/shop/releases/feature-magento-2.4-update-786425/vendor/magento/framework/ObjectManager/ObjectManager.php(56): Magento\Framework\ObjectManager\Factory\Compiled->create()
#4 /var/www/shop/releases/feature-magento-2.4-update-786425/vendor/magento/framework-message-queue/ConsumerFactory.php(167): Magento\Framework\ObjectManager\ObjectManager->create()
#5 /var/www/shop/releases/feature-magento-2.4-update-786425/vendor/magento/framework-message-queue/ConsumerFactory.php(101): Magento\Framework\MessageQueue\ConsumerFactory->getHandlersFromCommunicationConfig()
#6 /var/www/shop/releases/feature-magento-2.4-update-786425/vendor/magento/framework-message-queue/ConsumerFactory.php(75): Magento\Framework\MessageQueue\ConsumerFactory->createConsumerConfiguration()
#7 /var/www/shop/releases/feature-magento-2.4-update-786425/vendor/magento/module-message-queue/Console/StartConsumerCommand.php(89): Magento\Framework\MessageQueue\ConsumerFactory->get()
#8 /var/www/shop/releases/feature-magento-2.4-update-786425/vendor/symfony/console/Command/Command.php(255): Magento\MessageQueue\Console\StartConsumerCommand->execute()
#9 /var/www/shop/releases/feature-magento-2.4-update-786425/vendor/magento/framework/Interception/Interceptor.php(58): Symfony\Component\Console\Command\Command->run()
#10 /var/www/shop/releases/feature-magento-2.4-update-786425/vendor/magento/framework/Interception/Interceptor.php(138): Magento\MessageQueue\Console\StartConsumerCommand\Interceptor->___callParent()
#11 /var/www/shop/releases/feature-magento-2.4-update-786425/vendor/magento/framework/Interception/Interceptor.php(153): Magento\MessageQueue\Console\StartConsumerCommand\Interceptor->Magento\Framework\Interception\{closure}()
#12 /var/www/shop/releases/feature-magento-2.4-update-786425/generated/code/Magento/MessageQueue/Console/StartConsumerCommand/Interceptor.php(23): Magento\MessageQueue\Console\StartConsumerCommand\Interceptor->___callPlugins()
#13 /var/www/shop/releases/feature-magento-2.4-update-786425/generated/code/Magento/MessageQueue/Console/StartConsumerCommand/Proxy.php(143): Magento\MessageQueue\Console\StartConsumerCommand\Interceptor->run()
#14 /var/www/shop/releases/feature-magento-2.4-update-786425/vendor/symfony/console/Application.php(1009): Magento\MessageQueue\Console\StartConsumerCommand\Proxy->run()
#15 /var/www/shop/releases/feature-magento-2.4-update-786425/vendor/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand()
#16 /var/www/shop/releases/feature-magento-2.4-update-786425/vendor/magento/framework/Console/Cli.php(115): Symfony\Component\Console\Application->doRun()
#17 /var/www/shop/releases/feature-magento-2.4-update-786425/vendor/symfony/console/Application.php(149): Magento\Framework\Console\Cli->doRun()
#18 /var/www/shop/releases/feature-magento-2.4-update-786425/bin/magento(23): Symfony\Component\Console\Application->run( 

**To Reproduce**
1. Go to 'shell'
2.  Open system.log in a secound shell
3. Start all queue consumers
4. See error in system.log

**Magento version**
magento 2.4.2

**Plugin version**
adyen/module-payment                                              7.0.0 
adyen/php-api-library                                             10.0.0  

**Screenshots**
According to di.xml there is a preference
![grafik](https://user-images.githubusercontent.com/19548641/116353219-a95a6880-a7f6-11eb-9f44-4c57ec042659.png)
but the implementation is missing  see https://github.com/Adyen/adyen-magento2/tree/7.0.0/Model

**Comment by acampos1916** [comment]
Thanks for this feedback @frostblogNet. I've created a PR to remove the preference. The concrete implementation to that class is not being used in the plugin anymore.
