### ISSUE TITLE
Zero subtotal checkout infinite spinner

### ISSUE THREAD

**Issue by m-molla** [Adyen/adyen-magento2#1023]
**Describe the bug**
Shipping methods are not clickable if magento Zero Subtotal Checkout (magento ootb feature) is enable.

**To Reproduce**
1. Enable Zero Subtotal Checkout
2. Add a product with price 0
3. Add to cart product with zero price
4. Go to the checkout page

**Expected behavior**
Shipping method will be clickable.

**Magento version**
2.4.2

**Comment by acampos1916** [comment]
Thanks for reporting this issue @m-molla. Can you confirm if #1028 solves it for you?

**Comment by m-molla** [comment]
> Thanks for reporting this issue @m-molla. Can you confirm if #1028 solves it for you?
@acampos1916 thank you very much for your quick response. Yes I confirm that the issue is solved.
