### ISSUE TITLE
[PW-4739] v7.0.0 not combatabile with "phpunit/phpunit": "~6.5.0"

### ISSUE THREAD

**Issue by siergiej-zarkiewicz** [Adyen/adyen-magento2#1027]
**Describe the bug**
After run
`vendor/bin/phpunit --configuration dev/tests/unit/phpunit.xml.dist vendor/adyen/module-payment/
`
Error:
`
`There were 8 errors:

1) Adyen\Payment\Tests\Helper\ChargedCurrencyTest::testGetQuoteAmountCurrency with data set #2 ('base', Adyen\Payment\Model\AdyenAmountCurrency Object (...), false, 'base')
Error: Call to undefined method Adyen\Payment\Tests\Helper\ChargedCurrencyTest::expectNotToPerformAssertions()

/var/www/vendor/adyen/module-payment/Test/Unit/Helper/ChargedCurrencyTest.php:340

2) Adyen\Payment\Tests\Helper\ChargedCurrencyTest::testGetQuoteAmountCurrency with data set #3 ('base', Adyen\Payment\Model\AdyenAmountCurrency Object (...), false, 'display')
Error: Call to undefined method Adyen\Payment\Tests\Helper\ChargedCurrencyTest::expectNotToPerformAssertions()

/var/www/vendor/adyen/module-payment/Test/Unit/Helper/ChargedCurrencyTest.php:340

3) Adyen\Payment\Tests\Helper\ChargedCurrencyTest::testGetQuoteAmountCurrency with data set #4 ('display', Adyen\Payment\Model\AdyenAmountCurrency Object (...), false, 'base')
Error: Call to undefined method Adyen\Payment\Tests\Helper\ChargedCurrencyTest::expectNotToPerformAssertions()

/var/www/vendor/adyen/module-payment/Test/Unit/Helper/ChargedCurrencyTest.php:340

4) Adyen\Payment\Tests\Helper\ChargedCurrencyTest::testGetQuoteAmountCurrency with data set #5 ('display', Adyen\Payment\Model\AdyenAmountCurrency Object (...), false, 'display')
Error: Call to undefined method Adyen\Payment\Tests\Helper\ChargedCurrencyTest::expectNotToPerformAssertions()

/var/www/vendor/adyen/module-payment/Test/Unit/Helper/ChargedCurrencyTest.php:340

5) Adyen\Payment\Tests\Helper\ChargedCurrencyTest::testGetQuoteItemAmountCurrency with data set #2 ('base', Adyen\Payment\Model\AdyenAmountCurrency Object (...), false, 'base')
Error: Call to undefined method Adyen\Payment\Tests\Helper\ChargedCurrencyTest::expectNotToPerformAssertions()

/var/www/vendor/adyen/module-payment/Test/Unit/Helper/ChargedCurrencyTest.php:375

6) Adyen\Payment\Tests\Helper\ChargedCurrencyTest::testGetQuoteItemAmountCurrency with data set #3 ('base', Adyen\Payment\Model\AdyenAmountCurrency Object (...), false, 'display')
Error: Call to undefined method Adyen\Payment\Tests\Helper\ChargedCurrencyTest::expectNotToPerformAssertions()

/var/www/vendor/adyen/module-payment/Test/Unit/Helper/ChargedCurrencyTest.php:375

7) Adyen\Payment\Tests\Helper\ChargedCurrencyTest::testGetQuoteItemAmountCurrency with data set #4 ('display', Adyen\Payment\Model\AdyenAmountCurrency Object (...), false, 'base')
Error: Call to undefined method Adyen\Payment\Tests\Helper\ChargedCurrencyTest::expectNotToPerformAssertions()

/var/www/vendor/adyen/module-payment/Test/Unit/Helper/ChargedCurrencyTest.php:375

8) Adyen\Payment\Tests\Helper\ChargedCurrencyTest::testGetQuoteItemAmountCurrency with data set #5 ('display', Adyen\Payment\Model\AdyenAmountCurrency Object (...), false, 'display')
Error: Call to undefined method Adyen\Payment\Tests\Helper\ChargedCurrencyTest::expectNotToPerformAssertions()

/var/www/vendor/adyen/module-payment/Test/Unit/Helper/ChargedCurrencyTest.php:375

--

There was 1 failure:

1) Adyen\Payment\Model\AdyenInitiateTerminalApiTest::testAddSaleToAcquirerDataLoggedInCustomer
Failed asserting that two arrays are equal.

/var/www/vendor/adyen/module-payment/Test/Unit/Model/AdyenInitiateTerminalApiTest.php:176

ERRORS!
Tests: 80, Assertions: 83, Errors: 8, Failures: 1.
`
**To Reproduce**
1. Run `vendor/bin/phpunit --configuration dev/tests/unit/phpunit.xml.dist vendor/adyen/module-payment/`
2. See error

**Expected behavior**
PHPUnit test pass

**Magento version**
[e.g. 2.3.6]

**Plugin version**
[e.g. 7.0.0]

**PHPUnit version**
[e.g. 6.5.14]

**Comment by AlexandrosMor** [comment]
Hello @siergiej-zarkiewicz,

Thank you for raising this issue. We created an internal ticket and we are going to investigate it as soon as possible.

kind regards,
Alexandros
Adyen
