### ISSUE TITLE
Dublicated text block

### ISSUE THREAD

**Issue by Hakyna** [Adyen/adyen-magento2#103]
Hello @rikterbeek .

During the development I found duplicate text on frontend. This happens in `module-payment/view/frontend/templates/info/adyen_hpp.phtml` file. The same text block is outputed in lines 36 and 37.

In our case text is "Pay with credit card or Klarna invoice".
Here is the screenshot: http://prntscr.com/et7mzt

This text block comes from admin panel (System -> Configuration -> Sales -> Payment Methods -> Adyen Hosted Payment Page (HPP) integration -> Advanced Settings -> Title field).

What do you think, can we leave only one of this text blocks?

With best regards, 
Anton.

**Comment by rikterbeek** [comment]
Hi @Hakyna,

Thanks for letting us know this is now fixed see fix above.

Regards,
Rik
Adyen

**Comment by Hakyna** [comment]
Thank you very much @rikterbeek !
Waiting for release 2.0.4.
