### ISSUE TITLE
Prestashop module js error on checkout page

### ISSUE THREAD

**Issue by astrid2002** [Adyen/adyen-magento2#1039]
Hello

i have installed the adyen prestashop module version module 3.5.0

Prestashop verison  1.7.6.3 i am getting the following error on the front end part on the checkout page and of course i am not seeing the payment method. 

https://bagprive.com/modules/adyenofficial/views/js/bundle.js
![Screen Shot 2021-05-10 at 20 07 49](https://user-images.githubusercontent.com/13542427/117690028-70919a80-b1cb-11eb-9f10-9ba1ccb8f908.png)

**Comment by Morerice** [comment]
Hi @astrid2002 

Could you please close this issue and open it in our PrestaShop plugin [repository](https://github.com/Adyen/adyen-prestashop/issues)?
Also in that issue, could you provide us with the log files which you can obtain by following these [instructions](https://docs.adyen.com/plugins/prestashop#downloading-the-logs)?

Best regards,
Jean
Adyen

**Comment by acampos1916** [comment]
I see that the issue was already created in the right repo. I'm closing this one now.
