### ISSUE TITLE
[PW-4643] Critical error on create order by admin with Adyen 7.0.0

### ISSUE THREAD

**Issue by mirkocesaro** [Adyen/adyen-magento2#1040]
**Describe the bug**
When an admin tries to create an order for a customer, there is a critical error in the log:

`report.CRITICAL: Invalid method Adyen\Payment\Block\Form\Cc::allowRecurring`

On developer mode, on the product submit to the cart, your journey will end on the page
https://{{base_url}}/{{admin}}/sales/order_create/processData/key/{{KEY}}/

With the following message:
```
1 exception(s):
Exception #0 (Magento\Framework\Exception\LocalizedException): Invalid method Adyen\Payment\Block\Form\Cc::allowRecurring
```

**To Reproduce**
Steps to reproduce the behaviour:
1. Set Magento in developer mode
2. Go to the admin
2. Create a new order
3. Add a product to the order by SKU
4. Click on "Add to Order"

**Expected behaviour**
The item is added to the order

**Magento version**
2.4.1

**Plugin version**
7.0.0

**Comment by jlczapski** [comment]
We are also experiencing this issue on Magento 2.4.2, Adyen 7.0.0. Do you have any updates?

**Comment by acampos1916** [comment]
Hello @mirkocesaro @jlczapski. Indeed as commented in #1045 there is as known bug with admin orders in 7.0.0 and 7.0.1. A fix is currently being worked on and will be released ASAP.

**Comment by acampos1916** [comment]
@mirkocesaro are you able to test if #1048 fixes this issue for you for card payments?
