### ISSUE TITLE
Notification grids

### ISSUE THREAD

**Issue by othuress** [Adyen/adyen-magento2#1041]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by othuress** [comment]
Dear Sir/Mam,

Create new Menu item Called Notification at the blue mark bellow.

 
![bild](https://user-images.githubusercontent.com/57142707/117949714-b311bf00-b312-11eb-9582-ffe4f6303329.png)


Create a grid like the transaction grid but with adyen notification messages that can be filtered, i.e. table adyen_notification

 
![bild](https://user-images.githubusercontent.com/57142707/117949761-be64ea80-b312-11eb-9e66-3d8f6a897079.png)

 

Include the following columns
pspreference, merchant_reference, event_code, success, payment_method, amount_value, amount_currency, reason,a.additional_data, created_at

![bild](https://user-images.githubusercontent.com/57142707/117949807-cb81d980-b312-11eb-8712-dd5ef0833280.png)


Event_codes in the filter should be
https://docs.adyen.com/development-resources/webhooks/understand-notifications#event-codes
i.e. OFFER_CLOSED,AUTHORISATION,CAPTURE,REFUND,CANCELLATION,CAPTURE_FAILED,REFUND_FAILED etc etc

Success in the filter True or False

Amount_currency in the filter SEK,GBP,EUR,DKK,USD etc etc

Default filter event_code = capture_failed, success = true, sorted on created_at from newest to oldest.

Regards,
Ola

**Comment by acampos1916** [comment]
Hello @othuress, there's already a notifications grid in System > Adyen > Notifications Overview. Please check it out and feel free to suggest anything that you would like to have there.

Thanks!

**Comment by othuress** [comment]
Hello,

We were not aware it existed, move it or copy it to the Sales menu
***@***.***D74B14.CB7153F0]

And add a dropp down for filters, so that you can easily change event_code and success, for example.

We developed our own now but we will let it “die” and use adyen default.

Vänliga hälsningar / Mit freundlichen Grüßen / Best regards​
Ola Thuresson
Direct. +46-(0)42-3017460<tel:+46-(0)42-3017460>
/
Cell. +46-(0)708-336040<tel:+46-(0)708-336040>
E‑mail. ***@***.******@***.***>

Thuresson Trading
Görslövsvägen 20
263 71
Jonstorp
Sweden
Switch. +46‑(0)42‑36 75 20
[Thuresson News]<https://www.thuressontrading.com/news/juicer>
[Thuresson Web]<https://www.thuressontrading.com/>
[Thuresson Trading AB]<https://www.thuressontrading.com/>

Från: Ángel Campos ***@***.***>
Skickat: den 17 maj 2021 10:46
Till: Adyen/adyen-magento2 ***@***.***>
Kopia: Ola Thuresson ***@***.***>; Mention ***@***.***>
Ämne: Re: [Adyen/adyen-magento2] Notification grids (#1041)


Hello @othuress<https://github.com/othuress>, there's already a notifications grid in System > Adyen > Notifications Overview. Please check it out and feel free to suggest anything that you would like to have there.

Thanks!
