### ISSUE TITLE
[PW-4885] renderCheckoutComponent method throws error whle trying to join undefined value

### ISSUE THREAD

**Issue by lukaszlempicki-sii** [Adyen/adyen-magento2#1043]
**Describe the bug**
In adyen-hpp-method-js on line 259 "renderCheckoutComponent" method   throws error while trying to join street address which should be array but it's undefined.

**To Reproduce**
1. Use incognito mode in your browser
2. Go to the checkout page. It should have available Adyen HPP methods
3. In the console you will get:

```
VM5376:1 Uncaught TypeError: Cannot read property 'join' of undefined
    at eval (eval at renderCheckoutComponent (adyen-hpp-method.js:257), <anonymous>:1:31)
    at Object.renderCheckoutComponent (adyen-hpp-method.js:257)
    at afterRender (eval at createBindingsStringEvaluator (knockout.js:2982), <anonymous>:3:162)
    at init (after-render.js:17)
    at knockout.js:3358
    at Object.ignore (knockout.js:1470)
    at knockout.js:3357
    at Object.arrayForEach (knockout.js:159)
    at applyBindingsToNodeInternal (knockout.js:3343)
    at applyBindingsToNodeAndDescendantsInternal (knockout.js:3223)
```

**Expected behavior**
It would be great to add fix in the code which checks if given street value is array, join it if it's true, and leave as it is if it's not

adyen-hpp-method.js
```
street = Array.isArray(quote.shippingAddress().street) ? quote.shippingAddress().street.join(' ') : quote.shippingAddress().street
```

**Magento version**
2.3.5-p2

**Plugin version**
7.0.0

**Screenshots**
![Screenshot from 2021-05-13 13-22-14](https://user-images.githubusercontent.com/52414806/118119310-74e9cd80-b3ee-11eb-992d-f9879a1ea6be.png)

**Comment by acampos1916** [comment]
Hello @lukaszlempicki-sii, thanks for opening this issue.

I was not able to reproduce this, even setting the number of street lines to 1 in the Magento admin always returned an array. Would you be able to share the config that sets the street as a non-array so that we can reproduce and test your proposed solution?

**Comment by zakisaad** [comment]
We also encounter this (7.0.1); reloading the checkout page resolves the problem. We have implemented a similar fix as suggested in the OP.

We use the OneStepCheckout plugin, I assume this is throwing a spanner in the works. @lukaszlempicki-sii, is this case for you also?

**Comment by lukaszlempicki-sii** [comment]
@zakisaad Yes, sounds the same. And reloading also resolves the problem. 

@acampos1916 what config do you need?

**Comment by acampos1916** [comment]
@lukaszlempicki-sii no need, now we know that this is probably a compatibility issue with the checkout plugin that you and @zakisaad are using. I've opened #1066 with the suggested fix.

Thank you both.
