### ISSUE TITLE
[PW-4694] Storeviews not enabled getting errors

### ISSUE THREAD

**Issue by jpratt** [Adyen/adyen-magento2#1049]
**Describe the bug**
When a storeview is not using Adyen, all resources are still loaded on the page. Errors occur on sites with no API credentials setup

**To Reproduce**
1. Install/Enable Ayden module
2. Compile, build static assets, etc.
3. Load default checkout for storeview that does no use Adyen and does not have Adyen API keys set.
4. Observe errors

**Expected behavior**
I expect for stores that do not use the Adyen payment method(s), the assets for Adyen are no loaded and is disabled. Maybe have a enable/disable for the method like other modules.

**Magento version**
2.3.6

**Plugin version**
7.0.1

**Screenshots**
![Screen Shot 2021-05-14 at 2 27 09 PM](https://user-images.githubusercontent.com/139758/118684151-70d2fc80-b7ae-11eb-9812-89e81d21fbe0.png)

**Comment by acampos1916** [comment]
Thanks for the feedback @jpratt,

Sounds like a good idea to disable the assets from being loaded if the methods are not being used. We'll look into this enhancement.

**Comment by Suzell** [comment]
Described in  #1342 so i am closing this ticket.
