### ISSUE TITLE
Cannot checkout with credit card using mutations, paymentMethod node is not generated

### ISSUE THREAD

**Issue by diogoazziwebjump** [Adyen/adyen-magento2#1054]
**Describe the bug**
After upgrading from version 6.6.9 to 7.0.1, the mutation placeOrder call is no longer generating the "paymentMethod" node in the request for the /payment API method.

**To Reproduce**
The PWA interface is defined the card data in the cart according to the call below for the setPaymentMethodOnCart method:
{
   "operationName":"setPaymentMethodOnCart",
   "variables":{
      "cartId":"gUDqMsyEn4UxALJWQ8EaGJ8l3hxRvwvD",
      "ccType":"MC",
  "cvc":"adyenjs_0_1_25$r1V1OS5k5TA8bR0xWvs70SodiKCxb59W6JZvUSm8/IkRNCXeI6FC6J3daWVcypnU0atyvH+aEB8iPnhJSZwQm5F9AewpD1wVbtvm+LxpJpAjW3uC4spVf49OIth0OFbmDid0GrM4EihL9X2GIGPaaoexYH4/67vQum6T6StAMVYChcloO9zp6jk58WTaiksOZh/e2LuVoO6Td5K4iSGNHjIt6aK+PeM4oljeewRWWDz4N1kbiQcGHjmLmhfPrqBDhfZ8Ssxahbz79MPr+X26U2hsmd7Wz0lFwuwFxUbHROzlAIkkSHL4C6GHP43hMWXpZ4MtZCgMc8c3FzxTYMHjsA==$h8Qc3OqHSm2kT1pQDbGfu8zngcv001WLdnUCIXGTGgEiEbvGEmd4mdnj81Hg9KQTXRfhsb4sAz8DOPHA7l4BS4LBegFKTTeaGjHEaPO9PQDYmXI5Ru5FX1v758U7Sy98qMqecwZFdpvxtNi7choe4Pn4dnxpqJbValKejwKUnqBQwzieoNJOuwB9akfPPNq9cevo6PcFm7GP04hopgQi1un9IJo/Jeii1oJY8D3WWMzBW0Ogcpwbwm7KZwoQvewSU23dA4o9tLpxA3w/+dvqWHrluD/cgwCCmDTTZ5VMM/HNooEKqi+7sY6y6t1ffmBV/1lxmt/W7/73EFig0wnKiIoUNx+aRjozrLRFXK+pa2yx7mpNG0bk2PR5k8nDepqL6+g8Rckg3zY47DcwvTbaHo0vhxLBFLTMvA1G4vAyfuypKI/iFaOL886deojqcvvFbeuJ+yUNMjYrTiiEqFwK3siVRlfjVyVoV7XIJkpLI0CEm+4X/4o6JrQGQ8O8cz5hYOlIQ98aIkoKWdsxxV4LWjTF4VRge/h4eShQJCY03NqO4qvLHuDugOwjJXe01+dGMAAwCqV++WMyDGJ/Od5ev/Yi5PcB/YOLZoVQEJH28MIy5VgnegllYBd8GR1IILYJWKzQcryj93KBIXFw7W+ILdCe0P7fawDH2aWGc7DVbVOiFPXtFk0uduy0LBeaMdrb317CEViaVbXvoGjzrXJfJL584b8uvGRA9MmU7GSV9E/SXSR9QRczcm0nMQkRSw==",
 "expiryMonth":"adyenjs_0_1_25$wbemDJasrOAsEhI4hVchz3eYZdzhIlJNisgcSe20J5ojzZRNMGWrgMazzRkzcuTRFQXsuDgO4q87FNOgA6qg6nofo0kiE7Dgj70hm0M7CDE0KGGlee07S5ijHM3wVfRg6vL0sQEr+L6G+ZWs/8UhGZcrIAinXj853RRZ4FJyouE99f0XrPPgLm5ZvYtr3HNZqKqf3C1rUrwkaI91evoP2Hxq+l9VqSPgHryka48DmcFO0ogqP0+ABasgNLxEOVyDnY/MCBjiYGk8GLhOg8FHY8Z80NQSE1yYZZ5+LKGu5kHU58599exnd7281BMVkaixwTtP/SbvaKHol+yf/W8k7g==$kkIIRb2EjT7YrStaJXy4Q/7qy5T4Os2YBa6FGkbNRtRnAm3THcGMa8nadVLuAbNDn345bGjkftm8TdrAfQGiyalWjWjZ5VRkff8TJdDRFSLh9QHsGPrDbC5XWUU72VDVamV6bdWRd0IBdaumb9aR9LL9Ht5KbRqm++HPv8E1zdkgBmClR53JmEW0DV+rRlpTR+i1OgqKZO2RJ18MiXHuhtPF0OkbIoCVzvD4GCikFxXbZoMvaaEqCWK9EH8S+jdn2/3qBqb4ZekJZC9aYCO43d5EudR3tSvI9SrPFIFxu1sZeYqxZCrUEtvtQWxdqjqOdxzc4i7DmFMGEfSrZPD5oOyAU+NJjKK99K2GHjmqSwKX0k6M/TMXu/UdOT/yOZWaEFtQX+URTUrCUrFGipe3MxRtaSM7Ptu0PwCD5wWnH6NyVqJlD/0RyA+vGg==",
      "expiryYear":"adyenjs_0_1_25$JliRCuBMXl2WCTOuKrtkoDnEfUmQKLUCZ33EZaMeihgYEOdXghafppD/Pr2EAfNRP91+DUFoZ61QT0NFqgXrvL3N4ngZysFSepH+56YdGE+9/BoLJjZ5adlW0bB38he4t0HXwqRYx065mH9kE2UEovCiqFilaW0GMyGSr2a3phZEcc/3Fpwxg7J3qa60AxD+3+TEdYQpEdUZQlBue3hWTeJMD1/OlvMXrKnjYiwytOPTZZlal/QPSRHXvoQeAwGE+6W+UVvnQ13BjVF9lplmU7CITqZxInmu1+bAD4DJdya2nVKL68Ojy1NQTHuYfsoyuZUkKiELdtoOie61yZ661A==$xtDBXGR3P3TXTueaWniJ64IizH+zDMEhp4jaL6Uf5GrYBEILzahqSdgObAuSl4i3qckMj/ArqYZI6JQKiAx/1fd+53Vn49Ph8KZA8dvR3EsYsbFh12CP93lh4k+QWYUOQnnWzklBVfgKvMHacDRpcsjmC3nK4kUj4JlPZDwgPvz5WolggBGmtG9IrZnQ0S/MuDerH35/CW/TvVmFRHDiw+D7Uuw6VNMbkQy9D/Cm+yFT0wb10EzzojNJbcOezadBH8wkXJRjH/4rfiFVMU4rMiv4Y5Q/WQiqpCtBk5O9ZpDEYBqP7T69RsCFuyC4kCvIzM+l/DeeU8YSSQVApsUUpltboyeoiAyYrhhiuE3yIrVOdxDBN+LxBRrfOMs2cv77l2S3Q7Mx7Hh+wPbdYzQ6zketwvlTM3GcpLJNthNGmceG1gisTBUnqyp1TBA=",
      "holderName":"D",
      "number":"adyenjs_0_1_25$fsrLOVILQCcAHmEds051TEBiEQlpzkYIKl7EPeaS119j8mTnvzeP9iOci7vM4Itjdoj2gE6RXt8Tjk17GN0W72GD6fRu/VQsMAH+kUFEz9OWp6dxCehBvmD8NuaE4xi+jEXfqLlWi2GrjNkWigiSEItmmCZQWF/DOse6KsvmvknZJvPOECqo2nUrpi5YwcknlgLQ+W4CB2DsIWYrdIwoDkGyuetaVb7sL0tXdV1PR7GIRfpfpf/LkwWmD2fkxxfviYQheltfsSUOmsLhh/tQY1tp9MdW6Hz3k9XiE7v7itt/vMBBj2gkRubyBY252B7R4FS+QSKoGelz4wLnJyPqng==$jCfyP2qm4JCEu8blRxLAIC3mfXZvH0NPNqfBtZ0fYyPPhYZhAF7v4Yd8eh9a0kvW8RFslllPFekaJKqDRa/Mcn4cAIL/0bwVCvJwLF736lwh1rFebYHF9BLaJxkYtl7duG5cSaiSnEWNoE1bnnj1Y/obwUsMIPgc/16scwnRCwCp8txEOEPxPKpxryF/q4OOewUFs7ocBuxbHFp4UdQAEGiwyzgr0G8PG+0k0AzMxEKRsEXWmKYgjdAKuTIEcavQfljxMvlFu4AbuoCtx8iMneJMdd3wPmwDDb2yLOmjhPJktPXs1Q9CYx/Jms47oRdABqKVDO9TwRYa9QI5ezxW39ntwq/50t5CwqgUFDIQGlWylYWNESSCufPY417odV7QOgmywNpRHL0U/BRlNBjYTCergVVidNBKM/ZwzCuYIzYG/e2oNPO5ilrBnPhKf+wrc7XIFkkfCgzwzIyVL80bo4Qqv0/ia4zqE/u6+WpDmdHqV7aJjX8mves/0StUM8oPnMlHIreqreScyTJAKsD7OLBlurJyRkIJK7ou2JytV+GAWnhiB02bjh0G+wt5ebFGoTQhrLwT2M1QGogAuQag5SLfWZEUsyVPMc5IbBWYeZfd3PSj1a3PHUUvrwcOi6iUsFLJnTrDr8sq",
      "installments":"1"
   },
   "query":"mutation setPaymentMethodOnCart($cartId: String!, $ccType: String!, $cvc: String!, $expiryMonth: String!, $expiryYear: String!, $holderName: String!, $number: String!, $installments: String!) {
  setPaymentMethodOnCart(input: {
    cart_id: $cartId,
    payment_method: {
        code: \"adyen_cc\",
        adyen_cc: {
            cc_type: $ccType,
            cvc: $cvc,
            expiryMonth: $expiryMonth,
            expiryYear: $expiryYear,
            holderName: $holderName,
            number: $number,
            number_of_installments: $installments
            }
        }
    }) {
    cart {
      id
      selected_payment_method {
        code
        title
        __typename
      }
      __typename
    }
    __typename
  }
}"
}

We made a change to receive the card data in schema.graphql

input PaymentMethodInput {
    adyen_cc: AdyenCCInput @doc(description: "Defines the required attributes for Authorize.Net payments")
}

input AdyenCCInput {
    holderName: String! @doc(description: "Adyen's credit card holder name")
    number: String! @doc(description: "Adyen's description of the transaction request")
    cvc: String! @doc(description: "Adyen's description of the transaction request")
    expiryMonth: String! @doc(description: "Adyen's description of the transaction request")
    expiryYear: String! @doc(description: "Adyen's description of the transaction request")
    cc_type: String! @doc(description: "Adyen's description of the transaction request")
    number_of_installments: String! @doc(description: "Adyen's number of installments selected to transaction")
}

And we created a DataProvider to pass the data to the module:

DataProvider:
public function getData($data): array
{
    if (empty($data[self::PATH_ADDITIONAL_DATA])) {
        throw new GraphQlInputException(
            __('Required parameter "adyen_cc" for "payment_method" is missing.')
        );
    }

    return $this->arrayManager->get(self::PATH_ADDITIONAL_DATA, $data);
}

So, we call the mutation placeOrder:

mutation ($cart_id: String!){
  placeOrder(input: {cart_id: $cart_id}) {
    order {
      order_number
    }
  }
}

This works correctly in version 6.6.9. 

The method responsible for setting up the paymentMethod node is buildCCData in \Helper\Request.php but this method is not called anywhere in version 7.0.1.

/**
 * @param $request
 * @param $payment
 * @param $storeIdbuildCCData
 * @return mixed
 */
public function buildCCData($payload, $storeId, $areaCode, $request = [])
{
    // If ccType is set use this. For bcmc you need bcmc otherwise it will fail

    if (!empty($payload['method']) && $payload['method'] == 'adyen_oneclick' &&
        !empty($payload[PaymentInterface::KEY_ADDITIONAL_DATA]['variant'])
    ) {
        $request['paymentMethod']['type'] = $payload[PaymentInterface::KEY_ADDITIONAL_DATA]['variant'];
    } else {
        $request['paymentMethod']['type'] = 'scheme';
    }

    if (!empty($payload[PaymentInterface::KEY_ADDITIONAL_DATA]
        [AdyenCcDataAssignObserver::ENCRYPTED_CREDIT_CARD_NUMBER]) &&
        $cardNumber = $payload[PaymentInterface::KEY_ADDITIONAL_DATA]
        [AdyenCcDataAssignObserver::ENCRYPTED_CREDIT_CARD_NUMBER]) {
        $request['paymentMethod']['encryptedCardNumber'] = $cardNumber;
    }

    if (!empty($payload[PaymentInterface::KEY_ADDITIONAL_DATA]
        [AdyenCcDataAssignObserver::ENCRYPTED_EXPIRY_MONTH]) &&
        $expiryMonth = $payload[PaymentInterface::KEY_ADDITIONAL_DATA]
        [AdyenCcDataAssignObserver::ENCRYPTED_EXPIRY_MONTH]) {
        $request['paymentMethod']['encryptedExpiryMonth'] = $expiryMonth;
    }

    if (!empty($payload[PaymentInterface::KEY_ADDITIONAL_DATA]
        [AdyenCcDataAssignObserver::ENCRYPTED_EXPIRY_YEAR]) &&
        $expiryYear = $payload[PaymentInterface::KEY_ADDITIONAL_DATA]
        [AdyenCcDataAssignObserver::ENCRYPTED_EXPIRY_YEAR]) {
        $request['paymentMethod']['encryptedExpiryYear'] = $expiryYear;
    }

    if (!empty($payload[PaymentInterface::KEY_ADDITIONAL_DATA]
        [AdyenCcDataAssignObserver::HOLDER_NAME]) && $holderName =
            $payload[PaymentInterface::KEY_ADDITIONAL_DATA][AdyenCcDataAssignObserver::HOLDER_NAME]) {
        $request['paymentMethod']['holderName'] = $holderName;
    }

    if (!empty($payload[PaymentInterface::KEY_ADDITIONAL_DATA]
        [AdyenCcDataAssignObserver::ENCRYPTED_SECURITY_CODE]) &&
        $securityCode = $payload[PaymentInterface::KEY_ADDITIONAL_DATA]
        [AdyenCcDataAssignObserver::ENCRYPTED_SECURITY_CODE]) {
        $request['paymentMethod']['encryptedSecurityCode'] = $securityCode;
    }

    if (!empty($payload[PaymentInterface::KEY_ADDITIONAL_DATA]
        [AdyenOneclickDataAssignObserver::RECURRING_DETAIL_REFERENCE]) &&
        $recurringDetailReference = $payload[PaymentInterface::KEY_ADDITIONAL_DATA]
        [AdyenOneclickDataAssignObserver::RECURRING_DETAIL_REFERENCE]
    ) {
        $request['paymentMethod']['recurringDetailReference'] = $recurringDetailReference;
    }

    /**
     * if MOTO for backend is enabled use MOTO as shopper interaction type
     */
    $enableMoto = $this->adyenHelper->getAdyenCcConfigDataFlag('enable_moto', $storeId);
    if ($areaCode === \Magento\Backend\App\Area\FrontNameResolver::AREA_CODE &&
        $enableMoto
    ) {
        $request['shopperInteraction'] = "Moto";
    }

    // if installments is set add it into the request
    if (!empty($payload[PaymentInterface::KEY_ADDITIONAL_DATA]
    [AdyenCcDataAssignObserver::NUMBER_OF_INSTALLMENTS])) {
        if (($numberOfInstallment = $payload[PaymentInterface::KEY_ADDITIONAL_DATA]
            [AdyenCcDataAssignObserver::NUMBER_OF_INSTALLMENTS]) > 0) {
            $request['installments']['value'] = $numberOfInstallment;
        }
    }

    return $request;
} 

In version 6.6.9, there is the CcAuthorizationDataBuilder component in di.xml, but it has been removed in the current version. As a result, paymentMethod data is never sent. 

    <virtualType name="AdyenPaymentCcAuthorizeRequest" type="Magento\Payment\Gateway\Request\BuilderComposite">
        <arguments>
            <argument name="builders" xsi:type="array">
                <item name="merchantaccount" xsi:type="string">Adyen\Payment\Gateway\Request\MerchantAccountDataBuilder</item>
                <item name="customer" xsi:type="string">Adyen\Payment\Gateway\Request\CustomerDataBuilder</item>
                <item name="customerip" xsi:type="string">Adyen\Payment\Gateway\Request\CustomerIpDataBuilder</item>
                <item name="address" xsi:type="string">Adyen\Payment\Gateway\Request\AddressDataBuilder</item>
                <item name="payment" xsi:type="string">Adyen\Payment\Gateway\Request\PaymentDataBuilder</item>
                <item name="browserinfo" xsi:type="string">Adyen\Payment\Gateway\Request\BrowserInfoDataBuilder</item>
                <item name="recurring" xsi:type="string">Adyen\Payment\Gateway\Request\RecurringDataBuilder</item>
                <item name="transaction" xsi:type="string">Adyen\Payment\Gateway\Request\CcAuthorizationDataBuilder</item>
                <item name="vault" xsi:type="string">Adyen\Payment\Gateway\Request\VaultDataBuilder</item>
                <item name="threeds2" xsi:type="string">Adyen\Payment\Gateway\Request\ThreeDS2DataBuilder</item>
            </argument>
        </arguments>
    </virtualType>

It seems to me that this part is not implemented, can you help us to understand why this node is not being mounted? 
This is preventing the version from being updated.

**Expected behavior**
Capture credit card data in the PWA Studio frontend and send it to the module in order to generate the paymentMethod node. 

NODE NOT GENERATED IN JSON:
paymentMethod":{
      "type":"scheme",
      "encryptedCardNumber":"",
      "encryptedExpiryMonth":"",
      "encryptedExpiryYear":"",
      "holderName":"D",
      "encryptedSecurityCode":""
   },

JSON GENERATED:
{
   "merchantAccount":"#merchantAccount",
   "shopperReference":"74",
   "shopperEmail":"diogo.azzi@webjump.com.br",
   "telephoneNumber":"(11) 94533-433",
   "shopperName":{
      "firstName":"Diogo",
      "lastName":"Azzi Ferreira"
   },
   "countryCode":"BR",
   "shopperLocale":"pt_BR",
   "shopperIP":"201.81.8.134",
   "billingAddress":{
      "street":"N\/A",
      "postalCode":"03512020",
      "city":"Adolfo",
      "houseNumberOrName":"",
      "country":"BR",
      "stateOrProvince":"SP"
   },
   "deliveryAddress":{
      "street":"N\/A",
      "postalCode":"03512020",
      "city":"Adolfo",
      "houseNumberOrName":"",
      "country":"BR",
      "stateOrProvince":"SP"
   },
   "amount":{
      "currency":"BRL",
      "value":1000
   },
   "reference":"2000000010",
   "fraudOffset":"0",
   "browserInfo":{
      "userAgent":"Mozilla\/5.0 (X11; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/80.0.3987.132 Safari\/537.36",
      "acceptHeader":"*\/*",
      "javaEnabled":false
   },
   "enableOneClick":false,
   "enableRecurring":false,
   "installments":{
      "value":"1"
   },
   "additionalData":{
      "allow3DS2":true
   },
   "origin":"https:\/\/integration-5ojmyuq-dvvlhgaenfux4.us-5.magentosite.cloud\/checkout",
   "channel":"web",
   "applicationInfo":{
      "merchantApplication":{
         "name":"adyen-magento2",
         "version":"6.6.9"
      },
      "adyenLibrary":{
         "name":"adyen-php-api-library",
         "version":"7.1.0"
      },
      "adyenPaymentSource":{
         "version":"6.6.9",
         "name":"adyen-magento2"
      },
      "externalPlatform":{
         "version":"2.4.2-p1",
         "name":"Magento"
      }
   }

**Magento version**
2.4.2

**Plugin version**
7.0.1

**Desktop (please complete the following information):**
 - OS: Linux Mint
 - Browser chrome
- Versão 80.0.3987.132

**Comment by cyattilakiss** [comment]
Hi @diogoazziwebjump ,

Thank you for raising this issue. Indeed between version 6 and version 7 we introduced a lot of changes especially regarding PWA. Please read those changes in our detailed release notes [here](https://github.com/Adyen/adyen-magento2/releases/tag/7.0.0)

Furthermore please see our new [PWA integration documentation](https://docs.adyen.com/plugins/magento-2/magento-pwa-storefront) where you can see the requests that you need to send to the specific endpoints exposed by our plugin.

In your case I see that since you are using GraphQL (which we don't support at the moment but since there are already requests for it, it's definitely on our roadmap) the schemas (and therefore the request object from your storefront) are not correct therefore the payments request fails. Please check at first the request you send to the setPaymentMethodOnCart endpoint, to see the correct request object for the version 7 please see [this section of the PWA documentation](https://docs.adyen.com/plugins/magento-2/magento-pwa-storefront#create-a-data-object) and also [this to see how to place the order](https://docs.adyen.com/plugins/magento-2/magento-pwa-storefront#place-an-order)
You are going to see that we heavily rely on the [Checkout web components ](https://docs.adyen.com/online-payments/components-web) and it's `state.data` return object which we send without changes in the new version. In the version 6 we manually mapped them which added quite some extra manual work because of the changes in the `state.data` object properties.

After you changed the request object to the one in the documentation the `paymentMethod` node should appear in your /payments request object and the api call should succeed.

I will close this issue for now since this is not a potential bug but please feel free to reopen it if you face issues.
Also we are happy to hear any "change request" that would make your life easier integrating a storefront that we didn't include in the v7 release and it's documentation linked above.

Best,
Attila
Adyen
