### ISSUE TITLE
recurringProcessingModel set to 'Subscription' by default

### ISSUE THREAD

**Issue by aligent-lturner** [Adyen/adyen-magento2#1057]
**Describe the bug**
If vault and one click are disabled in Magento, the `recurringProcessingModel` is still set to `Subscription` on the payments request. This results in an error on the response about failing to create a billing agreement (though the order is still created).

**To Reproduce**
1. Disable Stored Payment Methods in admin.
2. Place a credit card order in the website

**Expected behavior**
Order is created without any errors, and without attempting to create a billing agreement

**Magento version**
2.3.x, 2.4.x

**Plugin version**
7.0.x

**Screenshots**
![image](https://user-images.githubusercontent.com/40189797/120145001-072d0680-c222-11eb-8593-a3f9b06fa954.png)

**Additional context**
The problem seems to be caused by https://github.com/Adyen/adyen-magento2/blob/f9afb3c4c12eddde5e0ae3ae84f8604bc64fad28/Helper/Requests.php#L398-L406
If vault is enabled, the value is set to `Subscription`. Otherwise, if One Click is enabled, the value is set to `CardOnFile`. But if both are disabled, it's set to `Subscription` again. I believe in the case when both are disabled, the value should not be set at all.

**Comment by acampos1916** [comment]
Hello @aligent-lturner, thanks for this report. Could you check if #1056 solves this issue for you?

**Comment by aligent-lturner** [comment]
@acampos1916 that PR does seem to fix the problem of `recurringProcessingModel` being set in the request to Adyen, but for some reason, the response from Adyen (test environment) is still sending back the recurring data - for example:

```
[2021-06-01 03:45:51] AdyenLoggerTest.INFO: JSON Response to Adyen:{"additionalData":{"recurringProcessingModel":"Subscription","recurring.shopperReference":"300030004501a09e43-7b73-4513-9a85-a858796cec6d","recurring.recurringDetailReference":"8416225191514798"},"pspReference":"862622519151465D","resultCode":"Authorised","amount":{"currency":"AUD","value":4999},"merchantReference":"3000300045"} {"is_exception":false} []
```
As a result, I still get the same error on the order.

Do you know what could be causing this?

**Comment by RokPopov** [comment]
Hi @aligent-lturner , this issue seems to be related to configuration of your Adyen environment, could you please double-check that the 'Recurring' is toggled off following:

Customer Area >> Account >> Checkout >> Tokenization >> Recurring

Does this solve the issue for you?

**Comment by aligent-lturner** [comment]
@RokPopov thanks - didn't know where it was set in the customer area - that has solved the issue.
