### ISSUE TITLE
Error is showing on top for non 3DS card

### ISSUE THREAD

**Issue by prathap2406** [Adyen/adyen-magento2#1061]
**Describe the bug**
Error message on the checkout page is showing on top of the page instead of displaying in payment area.See screenshot below

**To Reproduce**
1. Go to checkout page
2. provide non 3DS card and check the error **the payment is refused** is showing in the top of the page.

**Expected behavior**
Irrespective of the card, the error should be displayed in the payment section.

**Magento version**
[e.g. 2.3.6]

**Plugin version**
[e.g. 7.0.0]

**Comment by acampos1916** [comment]
Hello @prathap2406 thanks for opening this issue.

Looks like you're using a custom checkout, as the default one is not one step/page. Is this reproducible for you in the regular checkout?

Which extension are you using for checkout?

**Comment by prathap2406** [comment]
We're using amasty single step checkout, this issue wasn't happened with Adyen 6x after been upgraded to Adyen 7x we''re facing such issues.

**Comment by prathap2406** [comment]
Additionally, it's as expected for 3DS card but for other cards the error is displaying on top. Hope it clarifies.

Thanks,

**Comment by prathap2406** [comment]
@acampos1916 - Any workaround for this.

**Comment by cyattilakiss** [comment]
Hi @prathap2406 ,

I was checking this issue on my dev environment and basically on the default checkout it is using the exact same div that we create here: https://github.com/Adyen/adyen-magento2/blob/6.7.1/view/frontend/web/template/payment/cc-form.html#L62-L64 and the js kicks in (handling the 3DS2 failed scenario) here: https://github.com/Adyen/adyen-magento2/blob/6.7.1/view/frontend/web/js/view/payment/method-renderer/adyen-cc-method.js#L226

In both v6 and v7 we handle the non 3D failed scenario the same way basically by providing a standard Magento exception to the frontend here: https://github.com/Adyen/adyen-magento2/blob/6.7.1/Gateway/Validator/CheckoutResponseValidator.php#L209

This is the exception then what Magento (and I believe amasty single step checkout handles and for some reason not using the message containers linked above but probably a default one) handles and shows the error message.

At first I thought that maybe we changed an id or something in the html files but after comparing the https://github.com/Adyen/adyen-magento2/blob/6.7.1/view/frontend/web/template/payment/cc-form.html and the https://github.com/Adyen/adyen-magento2/blob/7.0.0/view/frontend/web/template/payment/cc-form.html file versions I couldn't find any significant difference which could cause this issue.

Did you upgrade anything else than the adyen magento plugin before noticing the shange?
Did you maybe have any custom code before which has been removed by the upgrade?

Best,
Attila
Adyen

**Comment by prathap2406** [comment]
@cyattilakiss 
Did you upgrade anything else than the adyen magento plugin before noticing the change? - NO
Did you maybe have any custom code before which has been removed by the upgrade? - NO

We upgraded Magento version and adyen version alone and after that we're having such issue. Please assist if you any idea.

**Comment by prathap2406** [comment]
@acampos1916 @cyattilakiss - Any clue on this? or any lead to modify js to append in payment section and I believe it's on bundle.js from adyen module.

**Comment by acampos1916** [comment]
Hello @prathap2406, this seems specifically related to the way your single step checkout plugin modifies the payment/checkout section. Are you able to investigate why the error message is shown in a different place? Is this reproducible for you in the regular Magento 2 checkout?

**Comment by cyattilakiss** [comment]
HI @prathap2406 ,

In both v6 and v7 we handle the non 3D failed scenario the same way basically by providing a standard Magento exception to the frontend here: https://github.com/Adyen/adyen-magento2/blob/6.7.1/Gateway/Validator/CheckoutResponseValidator.php#L209

This is the exception then what Magento handles and shows the error message. This is happening in your `app/code/Magento/Checkout/view/frontend/web/js/model/place-order.js` file here:
![image](https://user-images.githubusercontent.com/42297201/121647175-64cd1880-ca96-11eb-8df0-99e778ea3746.png)

The bundle.js is not responsible for any magento related javascript logic it is only responsible for rendering the frontend components for the adyen payment methods.

In case you disable amasty single page checkout do you still have the same problem showing the error message?

Best,
Attila
Adyen

**Comment by prathap2406** [comment]
It was one of the custom module which was causing the issue...
thanks for you timely help :)

**Comment by cyattilakiss** [comment]
Thanks for the feedback @prathap2406 !
Attila
Adyen
