### ISSUE TITLE
[PW-4945] Notice: Undefined property: Adyen\Payment\Helper\ConnectedTerminals::$adyenLogger

### ISSUE THREAD

**Issue by aman3103** [Adyen/adyen-magento2#1070]
**Describe the bug**
Notice: Undefined property: Adyen\Payment\Helper\ConnectedTerminals::$adyenLogger. Seem like you haven't defined that variable in the class Adyen\Payment\Helper\ConnectedTerminals

**To Reproduce**
1. Go to Magento admin -> configuration -> sales -> payment methods -> Adyen All in one payment method ->Point of Sale (POS) integration with Cloud API enable it 
2. Go to checkout 
3. You will see the above error

**Expected behavior**
Checkout should not show any error when Point of Sale (POS) integration with Cloud API enable 

**Magento version**
2.4.2

**Plugin version**
7.0.1

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by acampos1916** [comment]
Thanks for opening this issue @aman3103, I've created a PR for it and we'll merge it after tests. Could you also verify if it fixes the problem for you?
