### ISSUE TITLE
order state stuck to "payment_review" status changes to "processing"

### ISSUE THREAD

**Issue by zenisca** [Adyen/adyen-magento2#1081]
after successful payment and invoice creation: order state stays: "payment_review",
this leads to  shipment and other buttons hidden.
![image_2021_06_24T13_05_50_144Z](https://user-images.githubusercontent.com/7703078/123269662-2dfef580-d4cd-11eb-9876-6b1821ae18d4.png)

**Magento version**
2.4.2

**Plugin version**
7.0

**Screenshots**

**Comment by acampos1916** [comment]
Hello @zenisca thanks for opening this issue. Has your instance received the corresponding webhooks to move the order out of payment review? You can check that in System > Adyen > Notifications Overview. If the webhooks are there and have been processed then the order status history should have more information about the order flow.

Ultimately you can check the notification.log and cronjob.log files for more information.
