### ISSUE TITLE
PHP Fatal Error after update 6.1.2 to 7.1.0 -> Class TokenGooglePayUiComponentProvider

### ISSUE THREAD

**Issue by Jhoche** [Adyen/adyen-magento2#1083]
After update Plugin from 6.1.2 to 7.1.0, when access site.com/checkout/cart we got a PHP Fatal Error below:

```
[error] 26509#26509: *61234 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Class 'Adyen\Payment\Model\Ui\TokenGooglePayUiComponentProvider' not found in /var/www/magento2/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:121
Stack trace:
#0 /var/www/magento2/vendor/magento/framework/ObjectManager/Factory/Compiled.php(108): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject('Adyen\\Payment\\M...', Array)
#1 /var/www/magento2/vendor/magento/framework/ObjectManager/Factory/Compiled.php(150): Magento\Framework\ObjectManager\Factory\Compiled->create('Adyen\\Payment\\M...')
#2 /var/www/magento2/vendor/magento/framework/ObjectManager/Factory/Compiled.php(125): Magento\Framework\ObjectManager\Factory\Compiled->get('Adyen\\Payment\\M...')
#3 /var/www/magento2/vendor/magento/framework/ObjectManager/Factory/Compiled.php(86): Magento\Framework\ObjectManager\Factory\Compiled->parseArray(Array)
#4 /var/www/magento2/vendor/magento/framework/ObjectManager/Factory/Compiled.php(150): Magento\Framework\ObjectManager" while reading response header from upstream, client: x.x.x.x, server: , request: "GET /checkout/cart/ HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.2-fpm.sock:", host: mysite.com
```

**To Reproduce**
1. Remove plugin "composer remove"
2. Install new 7.1.0 plugin "composer require"
3. Deploy Store
4. Access cart or checkout page

**Expected behavior**
A white page and erros PHP Fatal Error on logs.

**Magento version**
2.3.4

**Plugin version**
7.1.0

**Desktop and Smartphone**
All Platforms

**Additional Information:**
We are using multi-store with more than 50 stores.

**Comment by acampos1916** [comment]
Hello @Jhoche, indeed TokenGooglePayUiComponentProvider has been removed in >7.0.0. Have you cleared the Magento generated files after upgrading the plugin? Something in your instance seems to be referencing TokenGooglePayUiComponentProvider still even though in the new version there's no usage of this class.

**Comment by Jhoche** [comment]
Hello @acampos1916 
Thanks for the answer.
Interestingly, even removing generated files, pre processed, full cache, the problem persists. Even in grep I don't find any reference. There's some other location that suggests we should clean up.

In this installation, we previously installed 7.0.0, then went back to 6.1.2, and now installed to retry the upgrade to 7.1.2.

**Comment by acampos1916** [comment]
@Jhoche that's weird, indeed there's no call to the class anymore so you shouldn't be having that issue. Is the plugin installed in app/code besides the composer installation perhaps? Maybe it's also worth checking the database if by any chance there's an entity where this is persisted, I'm not aware of it but good to double check.

**Comment by Jhoche** [comment]
@acampos1916 thats right. After we use in a clean install, without old version, the problem was resolved. After this, we re-deploy same store files in other web server, clean opcache, magento cache and in production was resolved, not getting anymore same errors 500 on checkout/cart. Thank you.
