### ISSUE TITLE
Selecting adyen_hpp after adyen_cc continues to attempt CC payment

### ISSUE THREAD

**Issue by zakisaad** [Adyen/adyen-magento2#1084]
**Preface**
We use the IOSC Onestepcheckout module - however we don't usually have any issues between payment methods that the Adyen module is exhibiting.

**Describe the bug**
When both Adyen credit card and other Adyen payment methods are enabled (local/hpp), if you select credit card payment method first and then select PayPal or any other method belonging to adyen_hpp and attempt to check out, you get an error.

As per our internal debugging we found that at [Magento\Checkout\view\frontend\js\action\set-payment-information-extended.js](https://github.com/magento/magento2/blob/2.3.6-p1/app/code/Magento/Checkout/view/frontend/web/js/action/set-payment-information-extended.js#L73) when the set-payment-information ajax request is made, the request payload sends the method code adyen_cc with additional data set to empty credit card, no matter if an adyen_hpp method is selected.

**To Reproduce**
1)	Navigate to checkout
2)	Select payment method adyen_cc
3)	Change payment method to any payment method belonging to adyen_hpp like PayPal
4)	Click to move ahead with the checkout

**Expected behavior**
Checkout attempt with PayPal/selected adyen_hpp method, without any error

**Magento version**
2.3.6-p1

**Plugin version**
7.0.1

**Comment by acampos1916** [comment]
Hello @zakisaad. Thanks for opening this issue.

Do you think this is related to the checkout module that is being used? Are you able to reproduce this in a vanilla Magento instance? That would help us try to reproduce and fix the issue, currently I'm not able to reproduce this with the regular checkout.
