### ISSUE TITLE
[PW-5090] Orders with NULL status are created for CC when payment is refused

### ISSUE THREAD

**Issue by yuriichayka** [Adyen/adyen-magento2#1087]
**Describe the bug**
Orders with NULL status are created for CC when payment is refused.
The same as https://github.com/Adyen/adyen-magento2/issues/901

**To Reproduce**
1. Go to checkout
2. Select CC payment
3. Enter test card data with **incorrect CVV code**
4. Observe that order is refused, but created in Magento with empty(NULL) status

**Expected behavior**
No magento order is created in such case, or it is created with cancelled status.

**Magento version**
2.3.5-p1

**Plugin version**
7.0.1

**Logs**
[2021-07-01 06:32:58] AdyenLoggerTest.INFO: JSON Response to Adyen:{"additionalData":{"recurringProcessingModel":"Subscription"},"pspReference":"xxx","refusalReason":"CVC Declined","resultCod
e":"Refused","refusalReasonCode":"24","merchantReference":"50000000030"} {"is_exception":false} []

**Comment by acampos1916** [comment]
Hello @yuriichayka thanks for reporting this. Are you reproducing this using Non-3DS cards just like in #901? [This](https://github.com/magento/magento2/blob/2.3.5-p1/app/code/Magento/Quote/Model/QuoteManagement.php#L411) is the place in 2.3.5-p1 where the quote is submitted and, if the payment is refused, the process is stopped and no order is created for Non-3DS cards. Is the process stopping for you there?

**Comment by yuriichayka** [comment]
Hello, 

Yes, it reproduces only for cards without 3DS. 
But for cards with 3DS - order becomes Canceled due to '3D Not Authenticated' reason.

In my case, exception appears in following place:
vendor/magento/module-checkout/Model/GuestPaymentInformationManagement.php:95
But at such moment, order has been already created in Magento.

**Comment by acampos1916** [comment]
@yuriichayka ok thanks. I've created an internal ticket to investigate this using the data you provided. If you find any extra info please share it here. We'll update this ticket with any progress made.

**Comment by tnaber** [comment]
Hi @yuriichayka,

I have not been able to reproduce this issue. I see a trend here as this was also the case in #901. If this is still an active problem for you, could you verify whether this also occurs in v8?

Cheers,
Titus

**Comment by tnaber** [comment]
Hi @yuriichayka,

As this issue has become stale and we have not been able to reproduce this I will be closing it. Please feel free to reopen if this is still an active problem for you :)

Cheers,
Titus
