### ISSUE TITLE
when I use 3D Secure 2 authentication I have this error: Payment details call failed, payment data not found

### ISSUE THREAD

**Issue by mattqiu** [Adyen/adyen-magento2#1088]
**Describe the bug**
{"message":"Payment details call failed, payment data not found","trace":"#0 [internal function]: Adyen\\Payment\\Model\\AdyenPaymentDetails->initiate(Array)\n#1 \/var\/www\/magento2\/vendor\/magento\/module-webapi\/Controller\/Rest\/SynchronousRequestProcessor.php(95): call_user_func_array(Array, Array)\n#2 \/var\/www\/magento2\/vendor\/magento\/module-webapi\/Controller\/Rest.php(188): Magento\\Webapi\\Controller\\Rest\\SynchronousRequestProcessor->process(Object(Magento\\Framework\\Webapi\\Rest\\Request\\Proxy))\n#3 \/var\/www\/magento2\/vendor\/magento\/framework\/Interception\/Interceptor.php(58): Magento\\Webapi\\Controller\\Rest->dispatch(Object(Magento\\Framework\\App\\Request\\Http))\n#4 \/var\/www\/magento2\/vendor\/magento\/framework\/Interception\/Interceptor.php(138): Magento\\Webapi\\Controller\\Rest\\Interceptor->___callParent('dispatch', Array)\n#5 \/var\/www\/magento2\/vendor\/magento\/framework\/Interception\/Interceptor.php(153): Magento\\Webapi\\Controller\\Rest\\Interceptor->Magento\\Framework\\Interception\\{closure}(Object(Magento\\Framework\\App\\Request\\Http))\n#6 \/var\/www\/magento2\/generated\/code\/Magento\/Webapi\/Controller\/Rest\/Interceptor.php(26): Magento\\Webapi\\Controller\\Rest\\Interceptor->___callPlugins('dispatch', Array, Array)\n#7 \/var\/www\/magento2\/vendor\/magento\/framework\/App\/Http.php(116): Magento\\Webapi\\Controller\\Rest\\Interceptor->dispatch(Object(Magento\\Framework\\App\\Request\\Http))\n#8 \/var\/www\/magento2\/generated\/code\/Magento\/Framework\/App\/Http\/Interceptor.php(24): Magento\\Framework\\App\\Http->launch()\n#9 \/var\/www\/magento2\/vendor\/magento\/framework\/App\/Bootstrap.php(261): Magento\\Framework\\App\\Http\\Interceptor->launch()\n#10 \/var\/www\/magento2\/pub\/index.php(74): Magento\\Framework\\App\\Bootstrap->run(Object(Magento\\Framework\\App\\Http\\Interceptor))\n#11 {main}"}

**To Reproduce**
when I click place order

**Expected behavior**

**Magento version**
2.3.4

**Plugin version**
7.0.0-rc.2

**Comment by acampos1916** [comment]
Hello @mattqiu, I see you're using a release candidate version, are you able to upgrade to the latest release to check if this is still reproducible?

**Comment by mattqiu** [comment]
yes,I already upgrade to 7.1.0.but still have a javascript error,
window.location.replace(url.build(
                        window.checkoutConfig.payment[quote.paymentMethod().method].successPage
                    ));
I console this quote.paymentMethod().method value it's not correct,I don't know why

**Comment by acampos1916** [comment]
@mattqiu ok thanks for the info. Could you also let us know which payment method is this? If it's Cards then are you testing with non-3DS, 3DS1 or 3DS2?

Can you post the relevant lines from the var/log/adyen/*.log files here?

**Comment by acampos1916** [comment]
Let us know about this @mattqiu, or if this has already been solved. You can send the log files to our support team (support@adyen.com).
