### ISSUE TITLE
[PW-5070] Coupon code used when order canceled

### ISSUE THREAD

**Issue by hharvel** [Adyen/adyen-magento2#1089]
Hello.

**Describe the bug**
When a payment with 3D Secure is refused an order is created and set to "Canceled status",
But if a coupon code is used, it is always counted as used by that order, whereas when an order is cancelled, it is not supposed to be counted.

**To Reproduce**
1. Create a new Cart Price Rules with a coupon in Magento Back Office
2. Make an order that use the rule
3. Go to checkout an choose CC Payment
4. Use a 3D Secure credit card insert a **wrong verification code** 
5. See the order created and in "Canceled" status in the Back Office
6. Check in database the `times_used` at 1 for the coupon in `salesrule_coupon` table

**Expected behavior**
As the order is canceled, the `times_used` field should be at 0. Otherwise it prevents the use of single-use coupons.

**Magento version**
2.3.6-p1

**Plugin version**
6.5.0 / 6.7.1

EDIT : Plugin updated to **6.7.1** , problem still present

**Comment by acampos1916** [comment]
Thanks for opening this issue @hharvel. Makes sense that the coupon should be restored if the payment fails and the order is cancelled. I've created an internal ticket to work on this.

**Comment by thedotwriter** [comment]
Hi,
Experiencing the same issue here.

This bug comes from the fact that the order is cancelled from the Order model instead of the OrderService model. 

In the method \Adyen\Payment\Model\AdyenThreeDS2Process::initiate, If the cancel() method was called from OrderService, [the plugin CouponUsagesDecrement](https://github.com/magento/magento2/blob/2.4.2/app/code/Magento/SalesRule/Plugin/CouponUsagesDecrement.php) would kick in and decrement the coupon usage.

Can we expect a fix soon?

**Comment by acampos1916** [comment]
Hello @thedotwriter, this is still in our backlog and will be worked on soon.

Your solutions seems like a quick fix though, and it should be verified both for the branches develop (v7) and develop-6 (v6). If this is pressing for your integration please consider contributing the solution to those branches, that would be greatly appreciated.

In the meantime we'll probably pick this up soon. Cheers!

**Comment by thedotwriter** [comment]
Hi @acampos1916,
I don't have enough time or knowledge of this module to be certain that a custom patch won't create further problems, we'll wait for your fix and update `salesrules_coupon_usage` manually for the meantime. We hope the fix won't take too long though :smile:

**Comment by aholovan** [comment]
Hi gents, 
Looks like there is one more problem with that. If order with one-time coupon applied is refused for some reasons (like wrong cvv or cc exp date) - next successfull attempt will place order without discount!
So, here is the patch for 8.0.0 version. Are You ok to verify and test it completely?
[coupon_code_if_order_canceled.patch.zip](https://github.com/Adyen/adyen-magento2/files/7728547/coupon_code_if_order_canceled.patch.zip)

**Comment by tnaber** [comment]
Thank you for the fix @aholovan, this fixes the problem for the 3DS2 flow. I have opened a PR, this is ready for merge once we have also resolved this issue for the 3DS1 flow.

**Comment by thedotwriter** [comment]
Hi,

Are you going to deliver a fix for 6.x ?

**Comment by tnaber** [comment]
Hi @thedotwriter,

We will include this fix in the upcoming release for v6. However, you should be aware that this might be the last release that we do for this version. To keep receiving regular releases we recommend updating to v8.

Cheers,
Titus

**Comment by thedotwriter** [comment]
Thanks for the quick feedback. We'll plan for an upgrade but for now the fix will be quite useful ; ).

Can we expect the fix in the coming week?

Cheers

**Comment by tnaber** [comment]
Good to hear, :)
You can expect this in the upcoming two weeks.

**Comment by thedotwriter** [comment]
Hi @tnaber,

Any news on this issue? : )

**Comment by tnaber** [comment]
Hi @thedotwriter,

We had trouble regarding some testing, the release is scheduled for this Wednesday. Thank your for your patience :)

Cheers,
Titus
