### ISSUE TITLE
[PW-5124] Credit Memo not created in Magento after refund in Adyen backoffice

### ISSUE THREAD

**Issue by yuriichayka** [Adyen/adyen-magento2#1092]
**Describe the bug**
When testing Adyen with Magento2, we detected that refunds in Adyen don't trigger cancelling order/creating Creditmemo in Magento.

Turned out, this is caused by following changes - https://github.com/Adyen/adyen-magento2/pull/1064/files
After reverting them, refunds work as expected.

**To Reproduce**
1. Place order, via CC for example
2. Create refund in Adyen BO
3. Observe order and adyen cronjob logs in Magento;
4. As result, only order comment about refund appears in Magento. And, logs contain following: `"Did not create a credit memo for this order because refund is done through Magento {"is_exception":false} []"`

**Expected behavior**
Order is cancelled and credit memo created when doing refund in Adyen

**Magento version**
2.3.5-p1

**Plugin version**
7.1.0

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
We have Immidiate capture configured.

**Comment by acampos1916** [comment]
Thanks for opening this issue @yuriichayka, indeed the PR you linked seems related. Can you verify in your case what's the difference between the PSP references [here](https://github.com/Adyen/adyen-magento2/pull/1064/files#diff-268ec544528639c51afd1e3bf006cbda6b1e51b8f818c93aee2296527b5035c1R1475). Maybe the regex is not working as expected.
