### ISSUE TITLE
Can't place order - TypeError: Argument 1 passed to Adyen\Payment\Helper\Address::getStreetAndHouseNumberFromAddress() must be an instance of Magento\Payment\Gateway\Data\AddressAdapterInterface

### ISSUE THREAD

**Issue by r-martins** [Adyen/adyen-magento2#1093]
**Describe the bug**
When placing an order in sandbox (didn't test on live), it creates an error when generating the URL for the ajax request. 
The error is printed within the URL which the ajax request would be sent to.
<img width="2550" alt="image" src="https://user-images.githubusercontent.com/191149/124581023-0a0bbe80-de94-11eb-9d59-a9bbb11e38b8.png">

After some debug, I could get the full value of the URL:

> https://magenteiro.test/rest/default/V1/adyen/orders/TypeError: Argument 1 passed to Adyen\Payment\Helper\Address::getStreetAndHouseNumberFromAddress() must be an instance of Magento\Payment\Gateway\Data\AddressAdapterInterface, instance of Magento\Sales\Model\Order\Address given, called in /var/www/html/vendor/adyen/module-payment/Helper/Requests.php on line 192 and defined in /var/www/html/vendor/adyen/module-payment/Helper/Address.php:41
> Stack trace:
> #0 /var/www/html/vendor/adyen/module-payment/Helper/Requests.php(192): Adyen\Payment\Helper\Address->getStreetAndHouseNumberFromAddress(Object(Magento\Sales\Model\Order\Address), '0', '4')
> #1 /var/www/html/vendor/adyen/module-payment/Gateway/Request/AddressDataBuilder.php(64): Adyen\Payment\Helper\Requests->buildAddressData(Object(Magento\Sales\Model\Order\Address), Object(Magento\Sales\Model\Order\Address), 1, Array)
> #2 /var/www/html/vendor/magento/module-payment/Gateway/Request/BuilderComposite.php(50): Adyen\Payment\Gateway\Request\AddressDataBuilder->build(Array)
> #3 /var/www/html/vendor/magento/module-payment/Gateway/Command/GatewayCommand.php(103): Magento\Payment\Gateway\Request\BuilderComposite->build(Array)
> #4 /var/www/html/vendor/magento/module-payment/Model/Method/Adapter.php(549): Magento\Payment\Gateway\Command\GatewayCommand->execute(Array)
> #5 /var/www/html/vendor/magento/module-payment/Model/Method/Adapter.php(451): Magento\Payment\Model\Method\Adapter->executeCommand('authorize', Array)
> #6 /var/www/html/vendor/magento/module-sales/Model/Order/Payment/Operations/AuthorizeOperation.php(45): Magento\Payment\Model\Method\Adapter->authorize(Object(Magento\Sales\Model\Order\Payment\Interceptor), 50)
> #7 /var/www/html/vendor/magento/module-sales/Model/Order/Payment/Processor.php(72): Magento\Sales\Model\Order\Payment\Operations\AuthorizeOperation->authorize(Object(Magento\Sales\Model\Order\Payment\Interceptor), true, 50)
> #8 /var/www/html/vendor/magento/module-sales/Model/Order/Payment.php(1136): Magento\Sales\Model\Order\Payment\Processor->authorize(Object(Magento\Sales\Model\Order\Payment\Interceptor), true, 50)
> #9 /var/www/html/vendor/magento/module-sales/Model/Order/Payment.php(458): Magento\Sales\Model\Order\Payment->authorize(true, 50)
> #10 /var/www/html/vendor/magento/module-sales/Model/Order/Payment.php(385): Magento\Sales\Model\Order\Payment->processAction('authorize', Object(Magento\Sales\Model\Order\Interceptor))
> #11 /var/www/html/vendor/magento/module-sales/Model/Order.php(983): Magento\Sales\Model\Order\Payment->place()
> #12 /var/www/html/vendor/magento/module-sales/Model/Order.php(1205): Magento\Sales\Model\Order->_placePayment()
> #13 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Sales\Model\Order->place()
> #14 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Sales\Model\Order\Interceptor->___callParent('place', Array)
> #15 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Sales\Model\Order\Interceptor->Magento\Framework\Interception\{closure}()
> #16 /var/www/html/generated/code/Magento/Sales/Model/Order/Interceptor.php(32): Magento\Sales\Model\Order\Interceptor->___callPlugins('place', Array, Array)
> #17 /var/www/html/vendor/magento/module-sales/Model/Service/OrderService.php(209): Magento\Sales\Model\Order\Interceptor->place()
> #18 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Sales\Model\Service\OrderService->place(Object(Magento\Sales\Model\Order\Interceptor))
> #19 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Sales\Model\Service\OrderService\Interceptor->___callParent('place', Array)
> #20 /var/www/html/vendor/magento/module-inventory-sales/Plugin/Sales/OrderManagement/AppendReservationsAfterOrderPlacementPlugin.php(195): Magento\Sales\Model\Service\OrderService\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Sales\Model\Order\Interceptor))
> #21 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(135): Magento\InventorySales\Plugin\Sales\OrderManagement\AppendReservationsAfterOrderPlacementPlugin->aroundPlace(Object(Magento\Sales\Model\Service\OrderService\Interceptor), Object(Closure), Object(Magento\Sales\Model\Order\Interceptor))
> #22 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Sales\Model\Service\OrderService\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Sales\Model\Order\Interceptor))
> #23 /var/www/html/generated/code/Magento/Sales/Model/Service/OrderService/Interceptor.php(32): Magento\Sales\Model\Service\OrderService\Interceptor->___callPlugins('place', Array, NULL)
> #24 /var/www/html/vendor/magento/module-quote/Model/QuoteManagement.php(566): Magento\Sales\Model\Service\OrderService\Interceptor->place(Object(Magento\Sales\Model\Order\Interceptor))
> #25 /var/www/html/vendor/magento/module-quote/Model/QuoteManagement.php(456): Magento\Quote\Model\QuoteManagement->submitQuote(Object(Magento\Quote\Model\Quote\Interceptor), Array)
> #26 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Quote\Model\QuoteManagement->submit(Object(Magento\Quote\Model\Quote\Interceptor))
> #27 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Quote\Model\QuoteManagement\Interceptor->___callParent('submit', Array)
> #28 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Quote\Model\QuoteManagement\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Quote\Model\Quote\Interceptor))
> #29 /var/www/html/generated/code/Magento/Quote/Model/QuoteManagement/Interceptor.php(23): Magento\Quote\Model\QuoteManagement\Interceptor->___callPlugins('submit', Array, Array)
> #30 /var/www/html/vendor/magento/module-quote/Model/QuoteManagement.php(414): Magento\Quote\Model\QuoteManagement\Interceptor->submit(Object(Magento\Quote\Model\Quote\Interceptor))
> #31 /var/www/html/vendor/magento/module-quote/Model/GuestCart/GuestCartManagement.php(87): Magento\Quote\Model\QuoteManagement->placeOrder('55', NULL)
> #32 /var/www/html/vendor/magento/module-checkout/Model/GuestPaymentInformationManagement.php(127): Magento\Quote\Model\GuestCart\GuestCartManagement->placeOrder('dU8IxAKUaU3nK4c...')
> #33 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Checkout\Model\GuestPaymentInformationManagement->savePaymentInformationAndPlaceOrder('dU8IxAKUaU3nK4c...', 'teste060721_19h...', Object(Magento\Quote\Model\Quote\Payment), Object(Magento\Quote\Model\Quote\Address\Interceptor))
> #34 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Checkout\Model\GuestPaymentInformationManagement\Interceptor->___callParent('savePaymentInfo...', Array)
> #35 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Checkout\Model\GuestPaymentInformationManagement\Interceptor->Magento\Framework\Interception\{closure}('dU8IxAKUaU3nK4c...', 'teste060721_19h...', Object(Magento\Quote\Model\Quote\Payment), Object(Magento\Quote\Model\Quote\Address\Interceptor))
> #36 /var/www/html/generated/code/Magento/Checkout/Model/GuestPaymentInformationManagement/Interceptor.php(23): Magento\Checkout\Model\GuestPaymentInformationManagement\Interceptor->___callPlugins('savePaymentInfo...', Array, Array)
> #37 [internal function]: Magento\Checkout\Model\GuestPaymentInformationManagement\Interceptor->savePaymentInformationAndPlaceOrder('dU8IxAKUaU3nK4c...', 'teste060721_19h...', Object(Magento\Quote\Model\Quote\Payment), Object(Magento\Quote\Model\Quote\Address\Interceptor))
> #38 /var/www/html/vendor/magento/module-webapi/Controller/Rest/SynchronousRequestProcessor.php(95): call_user_func_array(Array, Array)
> #39 /var/www/html/vendor/magento/module-webapi/Controller/Rest.php(188): Magento\Webapi\Controller\Rest\SynchronousRequestProcessor->process(Object(Magento\Framework\Webapi\Rest\Request\Proxy))
> #40 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Webapi\Controller\Rest->dispatch(Object(Magento\Framework\App\Request\Http))
> #41 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Webapi\Controller\Rest\Interceptor->___callParent('dispatch', Array)
> #42 /var/www/html/app/code/Chapagain/AutoCurrency/Plugin/FrontControllerInterface.php(59): Magento\Webapi\Controller\Rest\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
> #43 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(135): Chapagain\AutoCurrency\Plugin\FrontControllerInterface->aroundDispatch(Object(Magento\Webapi\Controller\Rest\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
> #44 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Webapi\Controller\Rest\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
> #45 /var/www/html/generated/code/Magento/Webapi/Controller/Rest/Interceptor.php(23): Magento\Webapi\Controller\Rest\Interceptor->___callPlugins('dispatch', Array, Array)
> #46 /var/www/html/vendor/magento/framework/App/Http.php(116): Magento\Webapi\Controller\Rest\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
> #47 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\Http->launch()
> #48 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\App\Http\Interceptor->___callParent('launch', Array)
> #49 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\Http\Interceptor->Magento\Framework\Interception\{closure}()
> #50 /var/www/html/generated/code/Magento/Framework/App/Http/Interceptor.php(23): Magento\Framework\App\Http\Interceptor->___callPlugins('launch', Array, Array)
> #51 /var/www/html/vendor/magento/framework/App/Bootstrap.php(263): Magento\Framework\App\Http\Interceptor->launch()
> #52 /var/www/html/pub/index.php(40): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http\Interceptor))
> ?_=1625564929493

**To Reproduce**
1. Create a sandbox account
2. Configure Magento to use it
3. Use Firecheckout (shoud not be relevant)
4. Store is configured to use BRL as currency and the user address is a Brazilian address
5. Address lines 1,2 and 4 were filled. Line 3 skipped.
6. Used credit card payment with 4111111111111111 as credit card number.
7. Configured adyen to display credit card holder name, witch I filled with `John Doe`(not relevant)

**Expected behavior**
Place the order successfuly after clicking on Place Order Button

**Magento version**
2.4.2-p1

**Plugin version**
7.1.0

**Screenshots**
<img width="2672" alt="image" src="https://user-images.githubusercontent.com/191149/124581663-a209a800-de94-11eb-922d-aa18c57235df.png">

<img width="1468" alt="image" src="https://user-images.githubusercontent.com/191149/124582071-0593d580-de95-11eb-815a-ed7ecad9d9a2.png">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome
 - Version 91.0.4472.106 (Official Build) (x86_64)

**Additional context**
* Magento is in developer mode running with markshust Docker stack.
* setup:di:compile, and setup:up, cache:clean... all executed before the test
* Credentials seems to be correct, as there's no exception of bad credentials in adyen logs. All the backend requests were successful.

**Comment by acampos1916** [comment]
Hey @r-martins thank you for this report. This issue seems related to #1082 which was fixed in #1086 and will be released soon, could you verify if #1086 solves it for you?
