### ISSUE TITLE
[PW-2765] Sending order item information to anti-fraud

### ISSUE THREAD

**Issue by felipe-webjump** [Adyen/adyen-magento2#1100]
**Describe the bug**
In snippet below, we can see that there is a collection of order item data, but this data is not being sent in the anti-fraud.

https://github.com/Adyen/adyen-magento2/blob/786255015a8a51b5ab100c210e1fcad03d88e078/Gateway/Request/CheckoutDataBuilder.php#L267-L302

**To Reproduce**
1. Make an Order in Website
2. Choose Adyen Credit Card payment method

**Expected behavior**
Sending order item information to anti-fraud.

**Magento version**
2.4.2

**Plugin version**
6.6.9

**Additional context**
This data is needed to increase the anti-fraud score.

**Comment by felipe-webjump** [comment]
Adyen support responded by telling me the correct format to send the order item data to anti-fraud, follow link https://docs.adyen.com/api-explorer/#/CheckoutService/latest/post/payments__reqParam_additionalData-AdditionalDataRisk-riskdata----customFieldName---

This code snippet is for sending order item data, but for another purpose.

Today in the module there is no implementation of sending this data to the anti-fraud.

**Comment by acampos1916** [comment]
Hello @felipe-webjump, thanks for opening this issue. This is correct, the docs you've been shown are the ones to follow if the risk data is to be added to the /payments requests. And indeed as of now this feature is not available in the plugin. It is in our backlog to add it after version 7.x.x and I've linked your request.

**Comment by acampos1916** [comment]
Related to #522

**Comment by acampos1916** [comment]
This ticket will be closed as it duplicates #522, please follow #522 for updates.
