### ISSUE TITLE
Unable to process binding foreach: function(){return adyenPaymentMethods }

### ISSUE THREAD

**Issue by killoff** [Adyen/adyen-magento2#1101]
**Describe the bug**
TypeError: Unable to process binding "foreach: function(){return adyenPaymentMethods }"
Message: Unable to process binding "afterRender: function(){return renderCheckoutComponent() }"
Message: Cannot read property 'join' of undefined
  at Object.renderCheckoutComponent(/static/version1626083548/frontend/**/custom/de_CH/Adyen_Payment/js/view/payment/method-renderer/adyen-hpp-method.js:263:47)

**To Reproduce**
1. Go to Magento Checkout
2. Go to Payment Methods

**Expected behavior**
No exception

**Magento version**
2.4.1

**Plugin version**
7.0.1

**Screenshots**
![Screenshot 2021-07-14 at 12 00 09](https://user-images.githubusercontent.com/3583507/125603715-2780b77a-7dd2-40f7-ae2f-9e160de4e865.png)

**Smartphone (please complete the following information):**
Mozilla/5.0 (iPhone; CPU iPhone OS 14_6 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) FxiOS/34.2  Mobile/15E148 Safari/605.1.15

**Additional context**
We have this error several times per day catched by sentry, meaning it reproduces approx. in 1% of checkout sessions.

**Comment by acampos1916** [comment]
Hello @killoff thanks for opening this issue. This has already been fixed in 7.1.0 https://github.com/Adyen/adyen-magento2/pull/1066
