### ISSUE TITLE
t.props.onError is not a function

### ISSUE THREAD

**Issue by killoff** [Adyen/adyen-magento2#1103]
**Describe the bug**
TypeError: t.props.onError is not a function. (In 't.props.onError(a||{errorType:"binLookup",message:"unknownError"})', 't.props.onError' is undefined)
  at ? (version1625750068/frontend/Drinks/custom/de_CH/Adyen_Payment/js/bundle.js:6:14)

**To Reproduce**
1. Go to Magento Checkout
2. Go to Payment Methods

**Expected behavior**
No exception

**Magento version**
2.4.1

**Plugin version**
7.0.1

**Screenshots**

![Screenshot 2021-07-14 at 12 22 11](https://user-images.githubusercontent.com/3583507/125606489-5d20ec9f-3ea9-4748-a875-134dfb3aa3b4.png)

**Smartphone (please complete the following information):**
Mozilla/5.0 (iPhone; CPU iPhone OS 14_6 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) GSA/167.0.382489606 Mobile/15E148 Safari/604.1

**Additional context**
We have this error several times per day catched by sentry, meaning it reproduces approx. in 1% of checkout sessions.

**Comment by cyattilakiss** [comment]
Hi @killoff ,

Thank you for opening this issue, we are going to investigate it and see how it can be solved.
@marcperez could you please help out with this issue?

Best,
Attila
Adyen

**Comment by acampos1916** [comment]
Hey @killoff, is this by any chance still an issue?

@marcperez do you happen to have any insights about this?

**Comment by killoff** [comment]
@acampos1916 no longer reproduced, I believe we can close the issue
