### ISSUE TITLE
No payment methods available

### ISSUE THREAD

**Issue by jonathanribas** [Adyen/adyen-magento2#1110]
**Describe the bug**

Response to /rest/it/V1/guest-carts/yyyyy/retrieve-adyen-payment-methods endpoint is:

`"{\"paymentMethodsResponse\":{\"paymentMethods\":{\"0\":{\"brands\":[\"amex\",\"maestro\",\"mc\",\"visa\"],\"details\":[{\"key\":\"encryptedCardNumber\",\"type\":\"cardToken\"},{\"key\":\"encryptedSecurityCode\",\"type\":\"cardToken\"},{\"key\":\"encryptedExpiryMonth\",\"type\":\"cardToken\"},{\"key\":\"encryptedExpiryYear\",\"type\":\"cardToken\"},{\"key\":\"holderName\",\"optional\":true,\"type\":\"text\"}],\"name\":\"Carta di Credito\",\"type\":\"scheme\"},\"1\":{\"configuration\":{\"merchantId\":\"merchant.com.adyen.CaudalieCom\",\"merchantName\":\"Caudalie SAS\"},\"details\":[{\"key\":\"applepay.token\",\"type\":\"applePayToken\"}],\"name\":\"Apple Pay\",\"type\":\"applepay\"},\"3\":{\"configuration\":{\"intent\":\"capture\"},\"name\":\"PayPal\",\"type\":\"paypal\"}}},\"paymentMethodsExtraDetails\":{\"scheme\":{\"icon\":{\"url\":\"https:\\\/\\\/checkoutshopper-live.adyen.com\\\/checkoutshopper\\\/images\\\/logos\\\/medium\\\/scheme.png\",\"width\":77,\"height\":50},\"isOpenInvoice\":false,\"configuration\":{\"amount\":{\"value\":2490,\"currency\":\"EUR\"},\"currency\":\"EUR\"}},\"applepay\":{\"icon\":{\"url\":\"https:\\\/\\\/checkoutshopper-live.adyen.com\\\/checkoutshopper\\\/images\\\/logos\\\/medium\\\/applepay.png\",\"width\":77,\"height\":50},\"isOpenInvoice\":false,\"configuration\":{\"amount\":{\"value\":2490,\"currency\":\"EUR\"},\"currency\":\"EUR\"}},\"paypal\":{\"icon\":{\"url\":\"https:\\\/\\\/it.caudalie.com\\\/static\\\/version1626689628\\\/base\\\/Magento\\\/base\\\/default\\\/Adyen_Payment\\\/images\\\/logos\\\/paypal.png\",\"width\":65,\"height\":41},\"isOpenInvoice\":false,\"configuration\":{\"amount\":{\"value\":2490,\"currency\":\"EUR\"},\"currency\":\"EUR\"}}}}"`

JS error message:

`bundle.min.js:formatted:16823 paymentMethodsResponse was provided but no payment methods were found.
(anonymous) @ bundle.min.js:formatted:16823
e @ bundle.min.js:formatted:16824
setOptions @ bundle.min.js:formatted:17120
e @ bundle.min.js:formatted:17126
t @ bundle.min.js:formatted:181
loadAdyenPaymentMethods @ adyen-hpp-method.min.js:1
initialize @ adyen-hpp-method.min.js:1
(anonymous) @ wrapper.min.js:3
UiClass @ class.min.js:3
initComponent @ layout.min.js:8
fire @ jquery.min.js:212
fireWith @ jquery.min.js:218
deferred.<computed> @ jquery.min.js:220
fire @ jquery.min.js:212
fireWith @ jquery.min.js:218
deferred.<computed> @ jquery.min.js:220
(anonymous) @ layout.min.js:7
execCb @ require.min.js:112
context.execCb @ resolver.min.js:11
check @ require.min.js:56
(anonymous) @ require.min.js:72
(anonymous) @ require.min.js:11
(anonymous) @ require.min.js:74
each @ require.min.js:3
emit @ require.min.js:74
check @ require.min.js:61
(anonymous) @ require.min.js:72
(anonymous) @ require.min.js:11
(anonymous) @ require.min.js:74
each @ require.min.js:3
emit @ require.min.js:74
check @ require.min.js:61
(anonymous) @ require.min.js:72
(anonymous) @ require.min.js:11
(anonymous) @ require.min.js:74
each @ require.min.js:3
emit @ require.min.js:74
check @ require.min.js:61
enable @ require.min.js:73
init @ require.min.js:54
(anonymous) @ require.min.js:66
(anonymous) @ require.min.js:11
(anonymous) @ mixins.min.js:8
execCb @ require.min.js:112
context.execCb @ resolver.min.js:11
check @ require.min.js:56
(anonymous) @ require.min.js:72
(anonymous) @ require.min.js:11
(anonymous) @ require.min.js:74
each @ require.min.js:3
emit @ require.min.js:74
check @ require.min.js:61
(anonymous) @ require.min.js:72
(anonymous) @ require.min.js:11
(anonymous) @ require.min.js:74
each @ require.min.js:3
emit @ require.min.js:74
check @ require.min.js:61
enable @ require.min.js:73
init @ require.min.js:54
callGetModule @ require.min.js:74
completeLoad @ require.min.js:103
onScriptLoad @ require.min.js:112
load (async)
req.load @ require.min.js:119
load @ require.min.js:112
load @ require.min.js:55
fetch @ require.min.js:55
check @ require.min.js:56
enable @ require.min.js:73
enable @ require.min.js:101
(anonymous) @ require.min.js:73
(anonymous) @ require.min.js:11
each @ require.min.js:3
enable @ require.min.js:71
init @ require.min.js:54
callGetModule @ require.min.js:74
completeLoad @ require.min.js:103
onScriptLoad @ require.min.js:112
load (async)
req.load @ require.min.js:119
load @ require.min.js:112
load @ require.min.js:55
fetch @ require.min.js:55
check @ require.min.js:56
enable @ require.min.js:73
enable @ require.min.js:101
(anonymous) @ require.min.js:73
(anonymous) @ require.min.js:11
each @ require.min.js:3
enable @ require.min.js:71
init @ require.min.js:54
(anonymous) @ require.min.js:97
setTimeout (async)
req.nextTick @ require.min.js:117
localRequire @ require.min.js:97
load @ mixins.min.js:8
(anonymous) @ require.min.js:71
(anonymous) @ require.min.js:11
on @ require.min.js:40
callPlugin @ require.min.js:61
fetch @ require.min.js:55
check @ require.min.js:56
enable @ require.min.js:73
enable @ require.min.js:101
(anonymous) @ require.min.js:73
(anonymous) @ require.min.js:11
each @ require.min.js:3
enable @ require.min.js:71
init @ require.min.js:54
callGetModule @ require.min.js:74
completeLoad @ require.min.js:103
onScriptLoad @ require.min.js:112
load (async)
req.load @ require.min.js:119
load @ require.min.js:112
load @ require.min.js:55
fetch @ require.min.js:55
check @ require.min.js:56
enable @ require.min.js:73
enable @ require.min.js:101
(anonymous) @ require.min.js:73
(anonymous) @ require.min.js:11
each @ require.min.js:3
enable @ require.min.js:71
init @ require.min.js:54
(anonymous) @ require.min.js:97
setTimeout (async)
req.nextTick @ require.min.js:117
localRequire @ require.min.js:97
defContext.require @ mixins.min.js:11
requirejs @ require.min.js:117
loadSource @ layout.min.js:7
(anonymous) @ jquery.min.js:219
fire @ jquery.min.js:212
add @ jquery.min.js:215
(anonymous) @ jquery.min.js:219
each @ jquery.min.js:28
(anonymous) @ jquery.min.js:219
jQuery.Deferred @ jquery-migrate.min.js:56
then @ jquery.min.js:219
initComponent @ layout.min.js:25
process @ layout.min.js:14
(anonymous) @ layout.min.js:25
_resolveRequest @ registry.min.js:16
_addRequest @ registry.min.js:16
get @ registry.min.js:15
waitParent @ layout.min.js:25
process @ layout.min.js:12
iterator @ layout.min.js:12
_.each._.forEach @ underscore.min.js:7
run @ layout.min.js:11
(anonymous) @ list.min.js:2
_.each._.forEach @ underscore.min.js:7
(anonymous) @ list.min.js:1
_resolveRequest @ registry.min.js:16
_addRequest @ registry.min.js:16
get @ registry.min.js:15
createRenderer @ list.min.js:1
(anonymous) @ list.min.js:1
(anonymous) @ underscore.min.js:5
_.each._.forEach @ underscore.min.js:7
(anonymous) @ list.min.js:1
notifySubscribers @ knockout.min.js:132
target.notifySubscribers @ knockout.min.js:171
(anonymous) @ knockout.min.js:172
notifySubscribers @ knockout.min.js:132
target.notifySubscribers @ knockout.min.js:171
valueHasMutated @ knockout.min.js:148
observable @ knockout.min.js:142
setPaymentMethods @ payment-service.min.js:3
(anonymous) @ get-payment-information.min.js:2
fire @ jquery.min.js:212
fireWith @ jquery.min.js:218
done @ jquery.min.js:628
callback @ jquery.min.js:655
XMLHttpRequest.send (async)
send @ jquery.min.js:652
ajax @ jquery.min.js:621
get @ storage.min.js:1
(anonymous) @ get-payment-information.min.js:2
navigate @ payment.min.js:2
(anonymous) @ step-navigator.min.js:4
handleHash @ step-navigator.min.js:4
initialize @ progress-bar.min.js:1
(anonymous) @ wrapper.min.js:3
UiClass @ class.min.js:3
initComponent @ layout.min.js:8
fire @ jquery.min.js:212
fireWith @ jquery.min.js:218
deferred.<computed> @ jquery.min.js:220
fire @ jquery.min.js:212
fireWith @ jquery.min.js:218
deferred.<computed> @ jquery.min.js:220
(anonymous) @ layout.min.js:7
execCb @ require.min.js:112
context.execCb @ resolver.min.js:11
check @ require.min.js:56
(anonymous) @ require.min.js:72
(anonymous) @ require.min.js:11
(anonymous) @ require.min.js:74
each @ require.min.js:3
emit @ require.min.js:74
check @ require.min.js:61
enable @ require.min.js:73
init @ require.min.js:54
(anonymous) @ require.min.js:66
(anonymous) @ require.min.js:11
(anonymous) @ mixins.min.js:8
execCb @ require.min.js:112
context.execCb @ resolver.min.js:11
check @ require.min.js:56
(anonymous) @ require.min.js:72
(anonymous) @ require.min.js:11
(anonymous) @ require.min.js:74
each @ require.min.js:3
emit @ require.min.js:74
check @ require.min.js:61
enable @ require.min.js:73
init @ require.min.js:54
callGetModule @ require.min.js:74
completeLoad @ require.min.js:103
onScriptLoad @ require.min.js:112
load (async)
req.load @ require.min.js:119
load @ require.min.js:112
load @ require.min.js:55
fetch @ require.min.js:55
check @ require.min.js:56
enable @ require.min.js:73
enable @ require.min.js:101
(anonymous) @ require.min.js:73
(anonymous) @ require.min.js:11
each @ require.min.js:3
enable @ require.min.js:71
init @ require.min.js:54
(anonymous) @ require.min.js:97
setTimeout (async)
req.nextTick @ require.min.js:117
localRequire @ require.min.js:97
load @ mixins.min.js:8
(anonymous) @ require.min.js:71
(anonymous) @ require.min.js:11
on @ require.min.js:40
callPlugin @ require.min.js:61
fetch @ require.min.js:55
check @ require.min.js:56
enable @ require.min.js:73
enable @ require.min.js:101
(anonymous) @ require.min.js:73
(anonymous) @ require.min.js:11
each @ require.min.js:3
enable @ require.min.js:71
init @ require.min.js:54
(anonymous) @ require.min.js:97
setTimeout (async)
req.nextTick @ require.min.js:117
localRequire @ require.min.js:97
defContext.require @ mixins.min.js:11
requirejs @ require.min.js:117
loadSource @ layout.min.js:7
(anonymous) @ jquery.min.js:219
fire @ jquery.min.js:212
fireWith @ jquery.min.js:218
deferred.<computed> @ jquery.min.js:220
(anonymous) @ layout.min.js:6
_resolveRequest @ registry.min.js:16
_updateRequests @ registry.min.js:16
later @ underscore.min.js:41
setTimeout (async)
(anonymous) @ underscore.min.js:41
set @ registry.min.js:15
initComponent @ layout.min.js:8
fire @ jquery.min.js:212
fireWith @ jquery.min.js:218
deferred.<computed> @ jquery.min.js:220
fire @ jquery.min.js:212
fireWith @ jquery.min.js:218
deferred.<computed> @ jquery.min.js:220
(anonymous) @ layout.min.js:7
execCb @ require.min.js:112
context.execCb @ resolver.min.js:11
check @ require.min.js:56
(anonymous) @ require.min.js:72
(anonymous) @ require.min.js:11
(anonymous) @ require.min.js:74
each @ require.min.js:3
emit @ require.min.js:74
check @ require.min.js:61
(anonymous) @ require.min.js:72
(anonymous) @ require.min.js:11
(anonymous) @ require.min.js:74
each @ require.min.js:3
emit @ require.min.js:74
check @ require.min.js:61
(anonymous) @ require.min.js:72
(anonymous) @ require.min.js:11
(anonymous) @ require.min.js:74
each @ require.min.js:3
emit @ require.min.js:74
check @ require.min.js:61
enable @ require.min.js:73
init @ require.min.js:54
(anonymous) @ require.min.js:66
(anonymous) @ require.min.js:11
(anonymous) @ mixins.min.js:8
execCb @ require.min.js:112
context.execCb @ resolver.min.js:11
check @ require.min.js:56
(anonymous) @ require.min.js:72
(anonymous) @ require.min.js:11
(anonymous) @ require.min.js:74
each @ require.min.js:3
emit @ require.min.js:74
check @ require.min.js:61
(anonymous) @ require.min.js:72
(anonymous) @ require.min.js:11
(anonymous) @ require.min.js:74
each @ require.min.js:3
emit @ require.min.js:74
check @ require.min.js:61
(anonymous) @ require.min.js:72
(anonymous) @ require.min.js:11
(anonymous) @ require.min.js:74
each @ require.min.js:3
emit @ require.min.js:74
check @ require.min.js:61
enable @ require.min.js:73
init @ require.min.js:54
callGetModule @ require.min.js:74
completeLoad @ require.min.js:103
onScriptLoad @ require.min.js:112
load (async)
req.load @ require.min.js:119
load @ require.min.js:112
load @ require.min.js:55
fetch @ require.min.js:55
check @ require.min.js:56
enable @ require.min.js:73
enable @ require.min.js:101
(anonymous) @ require.min.js:73
(anonymous) @ require.min.js:11
each @ require.min.js:3
enable @ require.min.js:71
init @ require.min.js:54
callGetModule @ require.min.js:74
completeLoad @ require.min.js:103
onScriptLoad @ require.min.js:112
load (async)
req.load @ require.min.js:119
load @ require.min.js:112
load @ require.min.js:55
fetch @ require.min.js:55
check @ require.min.js:56
enable @ require.min.js:73
enable @ require.min.js:101
(anonymous) @ require.min.js:73
(anonymous) @ require.min.js:11
each @ require.min.js:3
enable @ require.min.js:71
init @ require.min.js:54
callGetModule @ require.min.js:74
completeLoad @ require.min.js:103
onScriptLoad @ require.min.js:112
load (async)
req.load @ require.min.js:119
load @ require.min.js:112
load @ require.min.js:55
fetch @ require.min.js:55
check @ require.min.js:56
enable @ require.min.js:73
enable @ require.min.js:101
(anonymous) @ require.min.js:73
(anonymous) @ require.min.js:11
each @ require.min.js:3
enable @ require.min.js:71
init @ require.min.js:54
(anonymous) @ require.min.js:97
setTimeout (async)
req.nextTick @ require.min.js:117
localRequire @ require.min.js:97
defContext.require @ mixins.min.js:11
requirejs @ require.min.js:117
loadSource @ layout.min.js:7
(anonymous) @ jquery.min.js:219
fire @ jquery.min.js:212
fireWith @ jquery.min.js:218
deferred.<computed> @ jquery.min.js:220
(anonymous) @ layout.min.js:6
_resolveRequest @ registry.min.js:16
_updateRequests @ registry.min.js:16
later @ underscore.min.js:41
setTimeout (async)
(anonymous) @ underscore.min.js:41
set @ registry.min.js:15
initComponent @ layout.min.js:8
fire @ jquery.min.js:212
fireWith @ jquery.min.js:218
deferred.<computed> @ jquery.min.js:220
fire @ jquery.min.js:212
fireWith @ jquery.min.js:218
deferred.<computed> @ jquery.min.js:220
(anonymous) @ layout.min.js:7
execCb @ require.min.js:112
context.execCb @ resolver.min.js:11
check @ require.min.js:56
(anonymous) @ require.min.js:72
(anonymous) @ require.min.js:11
(anonymous) @ require.min.js:74
each @ require.min.js:3
emit @ require.min.js:74
check @ require.min.js:61
(anonymous) @ require.min.js:72
(anonymous) @ require.min.js:11
(anonymous) @ require.min.js:74
each @ require.min.js:3
emit @ require.min.js:74
check @ require.min.js:61
(anonymous) @ require.min.js:72
(anonymous) @ require.min.js:11
(anonymous) @ require.min.js:74
each @ require.min.js:3
emit @ require.min.js:74
check @ require.min.js:61
enable @ require.min.js:73
init @ require.min.js:54
(anonymous) @ require.min.js:66
(anonymous) @ require.min.js:11
(anonymous) @ mixins.min.js:8
execCb @ require.min.js:112
context.execCb @ resolver.min.js:11
check @ require.min.js:56
(anonymous) @ require.min.js:72
(anonymous) @ require.min.js:11
(anonymous) @ require.min.js:74
each @ require.min.js:3
emit @ require.min.js:74
check @ require.min.js:61
enable @ require.min.js:73
init @ require.min.js:54
callGetModule @ require.min.js:74
completeLoad @ require.min.js:103
onScriptLoad @ require.min.js:112
load (async)
req.load @ require.min.js:119
load @ require.min.js:112
load @ require.min.js:55
fetch @ require.min.js:55
check @ require.min.js:56
enable @ require.min.js:73
enable @ require.min.js:101
(anonymous) @ require.min.js:73
(anonymous) @ require.min.js:11
each @ require.min.js:3
enable @ require.min.js:71
init @ require.min.js:54
(anonymous) @ require.min.js:97
setTimeout (async)
req.nextTick @ require.min.js:117
localRequire @ require.min.js:97
load @ mixins.min.js:8
(anonymous) @ require.min.js:71
(anonymous) @ require.min.js:11
on @ require.min.js:40
callPlugin @ require.min.js:61
fetch @ require.min.js:55
check @ require.min.js:56
enable @ require.min.js:73
enable @ require.min.js:101
(anonymous) @ require.min.js:73
(anonymous) @ require.min.js:11
each @ require.min.js:3
enable @ require.min.js:71
init @ require.min.js:54
callGetModule @ require.min.js:74
completeLoad @ require.min.js:103
onScriptLoad @ require.min.js:112
load (async)
req.load @ require.min.js:119
load @ require.min.js:112
load @ require.min.js:55
fetch @ require.min.js:55
check @ require.min.js:56
enable @ require.min.js:73
enable @ require.min.js:101
(anonymous) @ require.min.js:73
(anonymous) @ require.min.js:11
each @ require.min.js:3
enable @ require.min.js:71
init @ require.min.js:54
callGetModule @ require.min.js:74
completeLoad @ require.min.js:103
onScriptLoad @ require.min.js:112
load (async)
req.load @ require.min.js:119
load @ require.min.js:112
load @ require.min.js:55
fetch @ require.min.js:55
check @ require.min.js:56
enable @ require.min.js:73
enable @ require.min.js:101
(anonymous) @ require.min.js:73
(anonymous) @ require.min.js:11
each @ require.min.js:3
enable @ require.min.js:71
init @ require.min.js:54
(anonymous) @ require.min.js:97
setTimeout (async)
req.nextTick @ require.min.js:117
localRequire @ require.min.js:97
defContext.require @ mixins.min.js:11
requirejs @ require.min.js:117
init @ main.min.js:1
(anonymous) @ main.min.js:6
_.each._.forEach @ underscore.min.js:7
(anonymous) @ main.min.js:5
apply @ main.min.js:5
fire @ jquery.min.js:212
add @ jquery.min.js:215
jQuery.fn.ready @ jquery.min.js:223
jQuery.fn.init @ jquery.min.js:200
jQuery.fn.init @ jquery-migrate.min.js:27
jQuery @ jquery.min.js:16
(anonymous) @ bootstrap.min.js:1
execCb @ require.min.js:112
check @ require.min.js:56
(anonymous) @ require.min.js:72
(anonymous) @ require.min.js:11
(anonymous) @ require.min.js:74
each @ require.min.js:3
emit @ require.min.js:74
check @ require.min.js:61
(anonymous) @ require.min.js:72
(anonymous) @ require.min.js:11
(anonymous) @ require.min.js:74
each @ require.min.js:3
emit @ require.min.js:74
check @ require.min.js:61
enable @ require.min.js:73
init @ require.min.js:54
(anonymous) @ require.min.js:66
(anonymous) @ require.min.js:11
(anonymous) @ mixins.min.js:8
execCb @ require.min.js:112
check @ require.min.js:56
(anonymous) @ require.min.js:72
(anonymous) @ require.min.js:11
(anonymous) @ require.min.js:74
each @ require.min.js:3
emit @ require.min.js:74
check @ require.min.js:61
(anonymous) @ require.min.js:72
(anonymous) @ require.min.js:11
(anonymous) @ require.min.js:74
each @ require.min.js:3
emit @ require.min.js:74
check @ require.min.js:61
enable @ require.min.js:73
init @ require.min.js:54
(anonymous) @ require.min.js:66
(anonymous) @ require.min.js:11
(anonymous) @ mixins.min.js:8
execCb @ require.min.js:112
check @ require.min.js:56
(anonymous) @ require.min.js:72
(anonymous) @ require.min.js:11
(anonymous) @ require.min.js:74
each @ require.min.js:3
emit @ require.min.js:74
check @ require.min.js:61
(anonymous) @ require.min.js:72
(anonymous) @ require.min.js:11
(anonymous) @ require.min.js:74
each @ require.min.js:3
emit @ require.min.js:74
check @ require.min.js:61
(anonymous) @ require.min.js:72
(anonymous) @ require.min.js:11
(anonymous) @ require.min.js:74
each @ require.min.js:3
emit @ require.min.js:74
check @ require.min.js:61
enable @ require.min.js:73
init @ require.min.js:54
callGetModule @ require.min.js:74
completeLoad @ require.min.js:103
onScriptLoad @ require.min.js:112
load (async)
req.load @ require.min.js:119
load @ require.min.js:112
load @ require.min.js:55
fetch @ require.min.js:55
check @ require.min.js:56
enable @ require.min.js:73
enable @ require.min.js:101
(anonymous) @ require.min.js:73
(anonymous) @ require.min.js:11
each @ require.min.js:3
enable @ require.min.js:71
init @ require.min.js:54
callGetModule @ require.min.js:74
completeLoad @ require.min.js:103
onScriptLoad @ require.min.js:112
load (async)
req.load @ require.min.js:119
load @ require.min.js:112
load @ require.min.js:55
(anonymous) @ require.min.js:55
(anonymous) @ require.min.js:11
execCb @ require.min.js:112
check @ require.min.js:56
(anonymous) @ require.min.js:72
(anonymous) @ require.min.js:11
(anonymous) @ require.min.js:74
each @ require.min.js:3
emit @ require.min.js:74
check @ require.min.js:61
(anonymous) @ require.min.js:72
(anonymous) @ require.min.js:11
(anonymous) @ require.min.js:74
each @ require.min.js:3
emit @ require.min.js:74
check @ require.min.js:61
enable @ require.min.js:73
init @ require.min.js:54
callGetModule @ require.min.js:74
completeLoad @ require.min.js:103
onScriptLoad @ require.min.js:112
load (async)
req.load @ require.min.js:119
load @ require.min.js:112
load @ require.min.js:55
fetch @ require.min.js:55
check @ require.min.js:56
enable @ require.min.js:73
enable @ require.min.js:101
(anonymous) @ require.min.js:73
(anonymous) @ require.min.js:11
each @ require.min.js:3
enable @ require.min.js:71
init @ require.min.js:54
callGetModule @ require.min.js:74
completeLoad @ require.min.js:103
onScriptLoad @ require.min.js:112
load (async)
req.load @ require.min.js:119
load @ require.min.js:112
load @ require.min.js:55
fetch @ require.min.js:55
check @ require.min.js:56
enable @ require.min.js:73
enable @ require.min.js:101
(anonymous) @ require.min.js:73
(anonymous) @ require.min.js:11
each @ require.min.js:3
enable @ require.min.js:71
init @ require.min.js:54
(anonymous) @ require.min.js:97
setTimeout (async)
req.nextTick @ require.min.js:117
localRequire @ require.min.js:97
fetch @ require.min.js:55
check @ require.min.js:56
enable @ require.min.js:73
enable @ require.min.js:101
(anonymous) @ require.min.js:73
(anonymous) @ require.min.js:11
each @ require.min.js:3
enable @ require.min.js:71
init @ require.min.js:54
callGetModule @ require.min.js:74
completeLoad @ require.min.js:103
onScriptLoad @ require.min.js:112
load (async)
req.load @ require.min.js:119
load @ require.min.js:112
load @ require.min.js:55
fetch @ require.min.js:55
check @ require.min.js:56
enable @ require.min.js:73
enable @ require.min.js:101
(anonymous) @ require.min.js:73
(anonymous) @ require.min.js:11
each @ require.min.js:3
enable @ require.min.js:71
init @ require.min.js:54
(anonymous) @ require.min.js:97
setTimeout (async)
req.nextTick @ require.min.js:117
localRequire @ require.min.js:97
load @ mixins.min.js:8
(anonymous) @ require.min.js:71
(anonymous) @ require.min.js:11
on @ require.min.js:40
callPlugin @ require.min.js:61
fetch @ require.min.js:55
check @ require.min.js:56
enable @ require.min.js:73
enable @ require.min.js:101
(anonymous) @ require.min.js:73
(anonymous) @ require.min.js:11
each @ require.min.js:3
enable @ require.min.js:71
init @ require.min.js:54
callGetModule @ require.min.js:74
completeLoad @ require.min.js:103
onScriptLoad @ require.min.js:112
load (async)
req.load @ require.min.js:119
load @ require.min.js:112
load @ require.min.js:55
fetch @ require.min.js:55
check @ require.min.js:56
enable @ require.min.js:73
enable @ require.min.js:101
(anonymous) @ require.min.js:73
(anonymous) @ require.min.js:11
each @ require.min.js:3
enable @ require.min.js:71
init @ require.min.js:54
(anonymous) @ require.min.js:97
setTimeout (async)
req.nextTick @ require.min.js:117
localRequire @ require.min.js:97
load @ mixins.min.js:8
(anonymous) @ require.min.js:71
(anonymous) @ require.min.js:11
on @ require.min.js:40
callPlugin @ require.min.js:61
fetch @ require.min.js:55
check @ require.min.js:56
enable @ require.min.js:73
enable @ require.min.js:101
(anonymous) @ require.min.js:73
(anonymous) @ require.min.js:11
each @ require.min.js:3
enable @ require.min.js:71
init @ require.min.js:54
callGetModule @ require.min.js:74
completeLoad @ require.min.js:103
onScriptLoad @ require.min.js:112
load (async)
req.load @ require.min.js:119
load @ require.min.js:112
load @ require.min.js:55
fetch @ require.min.js:55
check @ require.min.js:56
enable @ require.min.js:73
enable @ require.min.js:101
(anonymous) @ require.min.js:73
(anonymous) @ require.min.js:11
each @ require.min.js:3
enable @ require.min.js:71
init @ require.min.js:54
callGetModule @ require.min.js:74
completeLoad @ require.min.js:103
onScriptLoad @ require.min.js:112
load (async)
req.load @ require.min.js:119
load @ require.min.js:112
load @ require.min.js:55
fetch @ require.min.js:55
check @ require.min.js:56
enable @ require.min.js:73
enable @ require.min.js:101
(anonymous) @ require.min.js:73
(anonymous) @ require.min.js:11
each @ require.min.js:3
enable @ require.min.js:71
init @ require.min.js:54
(anonymous) @ require.min.js:97
setTimeout (async)
req.nextTick @ require.min.js:117
localRequire @ require.min.js:97
configure @ require.min.js:86
requirejs @ require.min.js:116
req.config @ require.min.js:117
(anonymous) @ requirejs-config.min.js:1
(anonymous) @ requirejs-config.min.js:1
(anonymous) @ requirejs-config.min.js:1
Show 318 more frames
bundle.min.js:formatted:16828 Uncaught TypeError: a.filter is not a function
    at new e (bundle.min.js:formatted:16828)
    at t.setOptions (bundle.min.js:formatted:17120)
    at t.e (bundle.min.js:formatted:17126)
    at new t (bundle.min.js:formatted:181)
    at UiClass.loadAdyenPaymentMethods (adyen-hpp-method.min.js:1)
    at UiClass.initialize (adyen-hpp-method.min.js:1)
    at UiClass.initialize (wrapper.min.js:3)
    at new UiClass (class.min.js:3)
    at Object.initComponent (layout.min.js:8)
    at fire (jquery.min.js:212)`

**To Reproduce**
1. Go to Payment Step
2. See error

**Expected behavior**
I should see available payment methods

**Magento version**
2.3.7

**Plugin version**
7.0.1

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOSX
 - Browser Chrome
 - Version 91.0.4472.114

**Comment by acampos1916** [comment]
Hello @jonathanribas, thanks for opening this issue.

We see that the merchant account you're using is already processing correctly. Has by any chance this issue been resolved?

If not, please inspect the payment methods object in these locations for Cards and local payment methods https://github.com/Adyen/adyen-magento2/blob/7.0.1/view/frontend/web/js/view/payment/method-renderer/adyen-cc-method.js#L83 https://github.com/Adyen/adyen-magento2/blob/7.0.1/view/frontend/web/js/view/payment/method-renderer/adyen-hpp-method.js#L113 Those should include a valid JSON with the retrieved payment methods.

**Comment by jonathanribas** [comment]
Hi @acampos1916, yes it is now solved. 

It seems PHP upgrade to 7.4 had an impact on one of our overrides showing payment methods or not.

**Comment by acampos1916** [comment]
Good to hear @jonathanribas, glad it was resolved.
