### ISSUE TITLE
Merchant is not getting confirmation for 3DS verified transactions on the Magento 2 Plug in

### ISSUE THREAD

**Issue by RobertJohnsonadyen** [Adyen/adyen-magento2#1113]
**Describe the bug**

Merchant is not getting confirmation for 3DS verified transactions on the Magento 2 Plug in, they receive confirmation fine without the 3DS redirect, but when 3DS is requested and completed they are directed straight to the below page and do not receive the confirmation message. 

![image](https://user-images.githubusercontent.com/86478027/126610892-abd13fbd-494f-4cf9-ac7b-0a96060f9f45.png)

Please advise if you need any more details from the merchant to review/ recreate and I will go back to them and request these.

**To Reproduce**

**Expected behavior**

Merchant expects that 3DS verified transactions will be given a confirmation and follow the same flow as non-3DS transactions.

**Magento version**

**Plugin version**
6.7.1

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by RobertJohnsonadyen** [comment]
Hi, 

Just to add the merchant is on Magento 2.4.2. 

They are pressing to go live tomorrow and this is the only issue they see so if someone can review this ASAP that would be much appreciated.

Regards, Rob

**Comment by acampos1916** [comment]
Hi @RobertJohnsonadyen, this seems related to the 3DS1 behavior https://docs.adyen.com/plugins/magento-2/set-up-the-plugin-in-magento#3ds1-behavior.

My guess is that the 3DS1 Authorization Behavior is set to Manual, which means a POST redirect. This could be breaking the user session. I would suggest to try the Auto setting by following those instructions.
