### ISSUE TITLE
 Warning: Illegal string offset 'returnUrl' 

### ISSUE THREAD

**Issue by jenzri-nizar** [Adyen/adyen-magento2#1114]
**Describe the bug**
During the Adyen test with Magento2, we detected that an exception during payment via credit card

**To Reproduce**
![image](https://user-images.githubusercontent.com/18179825/126616374-e600fc4e-e495-40b4-aff6-e16960639470.png)

**Magento version**
2.3.6

**Php version**
7.3

**Plugin version**
7.1.0

**Screenshots**
![image](https://user-images.githubusercontent.com/18179825/126615359-b835421a-96d9-4dd6-9ff3-07d148f134db.png)

**Comment by acampos1916** [comment]
Hello @jenzri-nizar, thank you for opening this issue.

I see that in version 7.1.0, in the file your log shows, there's no usage of the reuturnUrl index, rather in the 121 https://github.com/Adyen/adyen-magento2/blob/7.1.0/Gateway/Request/CheckoutDataBuilder.php#L122. Is there any modification in this file?

Also, the payment-information request in your screenshot contains a state data object as per this example, does it look the same to you? Maybe there's a JS error preventing the plugin from generating a state data to be sent, please check your browser console.

<img width="1642" alt="Screen Shot 2021-07-28 at 3 30 27 PM" src="https://user-images.githubusercontent.com/15349721/127331047-d8db51af-b490-46a3-b6d8-63859437225c.png">
