### ISSUE TITLE
[PW-5210] Icon images are not loaded on checkout page

### ISSUE THREAD

**Issue by smurflander** [Adyen/adyen-magento2#1118]
**Describe the bug**

**To Reproduce**
1. Images/logos folder is located in vendor/adyen/module-payment/view/base/web/images
2. Css file is located in vendor/adyen/module-payment/view/frontend/web/css/styles.css
3. Do bin/magento setup:static-content:deploy --strategy=compact
4. Images are generated under base folder while css under fronted folder
5. The consequence of this is 404 on all images defined in css file ( background: url(../images/logos/cc_border.png )) because it tries to load image from 'frontend' folder instead of 'base' folder

**Expected behavior**
Load the icons from correct path

**Magento version**
[e.g. 2.3.5]

**Screenshots**
https://i.imgur.com/XP0shUl.png

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser All browsers

**Additional context**
I think you need to reallocate images from base folder or css file from front-end folder.

**Comment by acampos1916** [comment]
Thanks for this report @smurflander, I have reproduced it and we'll work on it as soon as possible, possibly by moving the CSS file to the base directory.

Cheers,
Ángel

**Comment by tnaber** [comment]
Hi @smurflander,

In #1288, the css file has been moved to the base directory. Can you verify that this resolved your issue?

Cheers,
Titus

**Comment by smurflander** [comment]
Hi Tnaber

I just wanna to confirm that issue is not resolved. Tested on V7.3.6. We still have the same problem


> Hi @smurflander,
> 
> In #1288, the css file has been moved to the base directory. Can you verify that this resolved your issue?
> 
> Cheers, Titus

**Comment by tnaber** [comment]
Hi @smurflander,

The mentioned PR has been merged in v8.1.0. As this is not a blocker there is no high priority for rebuilding and merging it into the new v7 release. For now, we recommend upgrading. 
If we get more requests on this issue we will increase the priority.

Cheers,
Titus
