### ISSUE TITLE
Paid orders randomly stuck on payment pending

### ISSUE THREAD

**Issue by raphael96** [Adyen/adyen-magento2#1119]
Hello, I have an installation of Magento EE 2.4.2 with the Adyen 6.6.8 module and I am facing the following situation: some notifications end up being received and they do not update the order status, in the database I verify that the processing was completed and not there are errors but even so the order is waiting for payment.

1. Go to store and order any product, pay with credit card or Boleto
2. Issue may occur or not
4. See the notification but order wont updated as paid

**Expected behavior**
Order being marked as paid when Adyen notification is received and processed.

**Magento version**
2.4.2

**Plugin version**
6.6.8

**Screenshots**

![Screenshot_14](https://user-images.githubusercontent.com/10147707/127373751-23b6459e-dfae-456c-a45a-2e0c14974984.png)
![Screenshot_13](https://user-images.githubusercontent.com/10147707/127373754-0dcaca25-2995-4fa6-9278-9fb51e9cf595.png)
![Screenshot_15](https://user-images.githubusercontent.com/10147707/127373756-912c4ff3-9d0e-4f7f-b810-5ef0fe85d81c.png)

**Comment by raphael96** [comment]
Hello, logs from that order were archived, however i have other order with same issue: 000246088
cronjob.log
`[2021-08-03 19:53:03] AdyenLoggerTest.ADYEN_NOTIFICATION_CRONJOB: Processing notification 290731 {"is_exception":false} []
[2021-08-03 19:53:03] AdyenLoggerTest.ADYEN_NOTIFICATION_CRONJOB: Array
(
    [entity_id] => 290731
    [pspreference] => 4726280202752832
    [merchant_reference] => 000246088
    [event_code] => PENDING
    [success] => true
    [payment_method] => boletobancario_santander
    [amount_value] => 43848
    [amount_currency] => BRL
    [live] => true
    [additional_data] => a:6:{s:19:"boletobancario.data";s:708:"BQABAQA/---------------------------------------------------------------------------3OKuR92FcZ5W0Bh3pQczVOm56cHSbE/0eJaJ2BLsTPnNN9d9sv4WezJW+3GzTGoWRKbbwd4LUyaIeppZwyMn0wTFZdVhKS4OjV/bcxLiZUN/YpzdXTIpKrmBPlkQVfA3P/OZeDUipBfxXi5BL38u4TXwzhkSAqZagx/8xTG+vhKic+ZfO4a4Vw2lojAuBmkMiCXIM4M27RbRHH6REISsb8nGGasfAtwpx4IlUi0AALe4oeDTX2waxY03yV7UvkFJxyxeEa6EG1X5xe1OX9T/2eTgTx7qQT/U68Qy5/mrbTQ2wY2Vu4XikIHHXSE6tNAM8GC0wDN7C/y3VE/5l2c2P+f630dzbfzC9fk4ccGC02xsxW9HAjhTnwD/PAZs2CUaFrzOlfMQ8TeVKWN5CJ+DeUVEmhT4HpGRolaYtqSmROK6MiYD6xl8wikgfeIMt2/N4Aj1keumpm+aFF1YizXMGZFWDrXpvyLp+0PDC/3QxkqjQEh6Y3zDFM6qCg+1nmE2II5dLY7dbH3/I5m6ugyIkD8EzwGcb05MgtubIi25p+u/6vwqaV75gVk=";s:22:"boletobancario.dueDate";s:10:"2021-08-05";s:31:"boletobancario.barCodeReference";s:54:"03399.54349 20379.298795 98651.99999 1 87030000043848";s:18:"boletobancario.url";s:819:"https://live.adyen.com/hpp/generationBoleto.shtml?data=xxxxxxxxxxxxxxxxxxxxx";s:17:"acquirerReference";s:14:"792987998651-8";s:29:"boletobancario.expirationDate";s:10:"2021-08-20";}
    [done] => 0
    [processing] => 1
    [error_count] => 0
    [created_at] => 2021-08-03 19:51:17
)
 {"is_exception":false} []
[2021-08-03 19:53:03] AdyenLoggerTest.ADYEN_NOTIFICATION_CRONJOB: Created comment history for this notification with status change to: pending {"is_exception":false} []
[2021-08-03 19:53:03] AdyenLoggerTest.ADYEN_NOTIFICATION_CRONJOB: Updating the Adyen attributes of the order {"is_exception":false} []
[2021-08-03 19:53:03] AdyenLoggerTest.ADYEN_NOTIFICATION_CRONJOB: Processing the notification {"is_exception":false} []
[2021-08-03 19:53:03] AdyenLoggerTest.ADYEN_NOTIFICATION_CRONJOB: Notification 290731 is processed {"is_exception":false} []
[2021-08-03 19:53:03] AdyenLoggerTest.ADYEN_NOTIFICATION_CRONJOB: Cronjob updated 1 notification(s) {"is_exception":false} []`

notification.log

`[2021-08-03 19:51:17] AdyenLoggerTest.ADYEN_NOTIFICATION: The content of the notification item is: Array
(
    [additionalData] => Array
        (
            [boletobancario.data] => BQABAQA/---------------------------------------------------------------------------3OKuR92FcZ5W0Bh3pQczVOm56cHSbE/0eJaJ2BLsTPnNN9d9sv4WezJW+3GzTGoWRKbbwd4LUyaIeppZwyMn0wTFZdVhKS4OjV/bcxLiZUN/YpzdXTIpKrmBPlkQVfA3P/OZeDUipBfxXi5BL38u4TXwzhkSAqZagx/8xTG+vhKic+ZfO4a4Vw2lojAuBmkMiCXIM4M27RbRHH6REISsb8nGGasfAtwpx4IlUi0AALe4oeDTX2waxY03yV7UvkFJxyxeEa6EG1X5xe1OX9T/2eTgTx7qQT/U68Qy5/mrbTQ2wY2Vu4XikIHHXSE6tNAM8GC0wDN7C/y3VE/5l2c2P+f630dzbfzC9fk4ccGC02xsxW9HAjhTnwD/PAZs2CUaFrzOlfMQ8TeVKWN5CJ+DeUVEmhT4HpGRolaYtqSmROK6MiYD6xl8wikgfeIMt2/N4Aj1keumpm+aFF1YizXMGZFWDrXpvyLp+0PDC/3QxkqjQEh6Y3zDFM6qCg+1nmE2II5dLY7dbH3/I5m6ugyIkD8EzwGcb05MgtubIi25p+u/6vwqaV75gVk=
            [boletobancario.dueDate] => 2021-08-05
            [boletobancario.barCodeReference] => 03399.54349 20379.298795 98651.999999999 1 87030000043848
            [boletobancario.url] => https://live.adyen.com/hpp/generationBoleto.shtml?data=BQABAQA%2F--------------------------------------------------------------------------------------------------------------OKuR92FcZ5W0Bh3pQczVOm56cHSbE%2F0eJaJ2BLsTPnNN9d9sv4WezJW%2B3GzTGoWRKbbwd4LUyaIeppZwyMn0wTFZdVhKS4OjV%2FbcxLiZUN%2FYpzdXTIpKrmBPlkQVfA3P%2FOZeDUipBfxXi5BL38u4TXwzhkSAqZagx%2F8xTG%2BvhKic%2BZfO4a4Vw2lojAuBmkMiCXIM4M27RbRHH6REISsb8nGGasfAtwpx4IlUi0AALe4oeDTX2waxY03yV7UvkFJxyxeEa6EG1X5xe1OX9T%2F2eTgTx7qQT%2FU68Qy5%2FmrbTQ2wY2Vu4XikIHHXSE6tNAM8GC0wDN7C%2Fy3VE%2F5l2c2P%2Bf630dzbfzC9fk4ccGC02xsxW9HAjhTnwD%2FPAZs2CUaFrzOlfMQ8TeVKWN5CJ%2BDeUVEmhT4HpGRolaYtqSmROK6MiYD6xl8wikgfeIMt2%2FN4Aj1keumpm%2BaFF1YizXMGZFWDrXpvyLp%2B0PDC%2F3QxkqjQEh6Y3zDFM6qCg%2B1nmE2II5dLY7dbH3%2FI5m6ugyIkD8EzwGcb05MgtubIi25p%2Bu%2F6vwqaV75gVk%3D
            [acquirerReference] => 792987998651-8
            [boletobancario.expirationDate] => 2021-08-20
        )

    [amount] => Array
        (
            [currency] => BRL
            [value] => 43848
        )

    [eventCode] => PENDING
    [eventDate] => 2021-08-03T21:51:15+02:00
    [merchantAccountCode] => EditoraDoBrasilCOM
    [merchantReference] => 000246088
    [paymentMethod] => boletobancario_santander
    [pspReference] => 4726280202752832
    [success] => true
)
 {"is_exception":false} []
[2021-08-03 19:51:17] AdyenLoggerTest.ADYEN_NOTIFICATION: The result is accepted {"is_exception":false} []
[2021-08-04 07:34:27] AdyenLoggerTest.ADYEN_NOTIFICATION: The content of the notification item is: Array
(
    [additionalData] => Array
        (
            [boletobancario.originalAmount] => BRL 438.48
            [boletobancario.paymentDate] => 2021-08-03
            [boletobancario.paidAmount] => BRL 438.48
        )

    [amount] => Array
        (
            [currency] => BRL
            [value] => 43848
        )

    [eventCode] => AUTHORISATION
    [eventDate] => 2021-08-04T09:34:19+02:00
    [merchantAccountCode] => EditoraDoBrasilCOM
    [merchantReference] => 000246088
    [paymentMethod] => boletobancario_santander
    [pspReference] => 4726280202752832
    [reason] => 
    [success] => true
)
 {"is_exception":false} []
[2021-08-04 07:34:27] AdyenLoggerTest.ADYEN_NOTIFICATION: The result is accepted {"is_exception":false} []
`

**Note: BoletoData was trimmed in order to protect sensitive customer data **

**Comment by acampos1916** [comment]
Thanks @raphael96. If I understand correctly the notification received on `2021-08-04 07:34:27` changed the order status to "Pending" even though the event code is "AUTHORISATION", is that right?

I would suggest to debug [these lines](https://github.com/Adyen/adyen-magento2/blob/6.6.8/Model/Cron.php#L1073-L1074) in Cron.php so that we can see what is going on in your instance. The `_authorizePayment` call will do the logic.

Additionally, we recently addressed a similar issue on the latest version, it was reported [here](https://github.com/Adyen/adyen-magento2/issues/1085) and fixed [here](https://github.com/Adyen/adyen-magento2/pull/1104). It hasn't been included in a release yet but you can go through it to recognize if it's related to your case.

**Comment by raphael96** [comment]
Hello @acampos1916 i just applied your suggestion on the server, i will check the notifications tomorrow. I checked the older notifications and they still stuck in processing status.

**Comment by acampos1916** [comment]
Thanks for the update @raphael96. The older notifications that have already been processed will remain the same, but the new ones could be processed correctly by that PR. Let us know.

If you're still having this issue after applying that patch please debug [these lines](https://github.com/Adyen/adyen-magento2/blob/6.6.8/Model/Cron.php#L1073-L1074) to find out more.

**Comment by raphael96** [comment]
Even with that patch i had one order without payment confirmation. Can i send you logs for further investigation?

**Comment by raphael96** [comment]
Hello, the order 246654 stuck at pending.
Notification.log:
` 
                   	[2021-08-10 13:47:55] AdyenLoggerTest.ADYEN_NOTIFICATION: The content of the notification item is: Array
	           (
	                   	[additionalData] => Array
	            		(
				[expiryDate] => 12/2027
				[visaTemplate] => OneOffEcommerce
				[authCode] => 475468
				[cardSummary] => 7663
			)

		[amount] => Array
			(
				[currency] => BRL
				[value] => 5140
			)

		[eventCode] => AUTHORISATION
		[eventDate] => 2021-08-10T15:47:54+02:00
		[merchantAccountCode] => EditoraDoBrasilCOM
		[merchantReference] => 000246654
		[operations] => Array
			(
				[0] => CANCEL
				[1] => CAPTURE
				[2] => REFUND
			)

		[paymentMethod] => visa
		[pspReference] => 6129286032741463
		[reason] => 475468:7663:12/2027
		[success] => true
	)
	 {"is_exception":false} []
	[2021-08-10 13:47:55] AdyenLoggerTest.ADYEN_NOTIFICATION: The result is accepted {"is_exception":false} []

Cronjob.log didnt have any occurence of this number
`

**Comment by acampos1916** [comment]
Hello @raphael96, thanks for the info. The notification.log file will have the information about the notifications that are received, and cronjob.log will have the information about the actual processing of the notification.

If the order or the notification doesn't show up in the cronjob.log file it means that it hasn't been picked up by the cron. This could happen if there was an error in a previous cron run that is preventing the task to be executed again, this could be checked in the cron_schedule database table, filtering by Adyen jobs and checking the status.

In essence, the order remaining in Pending is correct because the notification has not been processed.

**Comment by raphael96** [comment]
There isn´t any relevant erros in cron_schedule table, however we still monitoring notifications vs paid orders that shows up in adyen customer area. Also we may create a script to handle notifications stuck on adyen_notification table?

**Comment by acampos1916** [comment]
Hello @raphael96. Also consider debugging the Cron.php class using a tool like Xdebug to check if the [notifications are being selected for processing](https://github.com/Adyen/adyen-magento2/blob/6.6.8/Model/Cron.php#L456) and if [there's an error while the process is taking place](https://github.com/Adyen/adyen-magento2/blob/6.6.8/Model/Cron.php#L587).

**Comment by acampos1916** [comment]
Hello @raphael96. issue 1085 relates to the order status changing when the `addStatusHistoryComment` function is used, I don't think this is the exact problem you're facing. Were you able to debug as suggested above?

**Comment by Skullsneeze** [comment]
Did a bit more digging in the database and the logs and one thing I noticed is I saw a few log message pop up for one of the "stuck" orders in the debug log. This contained just an array with some information related to the order, and I believe this is coming from the `\Adyen\Payment\Gateway\Command\PayByMailCommand` class. In this class I see the following happening:

```
// do not let magento set status to processing
$payment->setIsTransactionPending(true);
```

Could it be that for some reason the pay by mail command is triggered (order is paid with ideal)

**Comment by acampos1916** [comment]
Thanks for this investigation @Skullsneeze. I don't think that the Pay By Mail command would be triggered if this is a frontend order placed with iDEAL. Could you verify with extra log lines or with XDebug in `\Adyen\Payment\Gateway\Command\PayByMailCommand` if this is indeed the case?

In v6.6.8 the notification is moved to processing [here](https://github.com/Adyen/adyen-magento2/blob/6.6.8/Model/Cron.php#L468) using the function you found. After that line the notifications are looped and processed, is there something in that loop that could be causing the issue?

**Comment by acampos1916** [comment]
Good find about the PayByMail class @Skullsneeze. I'm still unable to reproduce that. Could you share the full logs for context?

**Comment by Skullsneeze** [comment]
Hi @acampos1916, "unfortunatly" since I've added the additional logging the issue has not occured again. I doubt that the logging fixed the issue though, but since we are not running Adyen on production yet, we are relying on test orders, which we have since not done many of. Since we are also looking to resolve some other issues we are actually opting to upgrade to the 7.x version of the module, so that might resolve this issue. Before we release the update though, i will place some new test orders just to see if the issue pops up again. If so I will share my findings again :)

**Comment by tnaber** [comment]
Closing this stale issue. Feel free to open it again if the problem still persists :)
