### ISSUE TITLE
[PW-5238] OFFER_CLOSED notifications are ignored for orders paid with Google Pay

### ISSUE THREAD

**Issue by ebaschiera** [Adyen/adyen-magento2#1121]
Hi,
server notifications with the event code `OFFER_CLOSED` don't affect orders paid with Google Pay.
The problem is a bit of logic that is missing here: https://github.com/Adyen/adyen-magento2/blob/7.1.0/Model/Cron.php#L1183
The order has payment method `adyen_google_pay`, but the server notification instead has the credit card brand in the `method` field, like for example `visa`, `mc`, `amex`.
So `$isOrderCc` is `false` and the order doesn't get canceled.
In my opinion `$isOrderCc` should be `true` when order payment method is `adyen_google_pay`.

**To Reproduce**
1. Make sure that open offers are configured to close automatically after a certain amount of time
2. Place an order with Google Pay, but don't complete the payment, so an open offer only is generated
3. Wait for the offer to close and receive the OFFER_CLOSED server notification
4. See that the order doesn't get canceled

**Expected behavior**
The order should be canceled.

**Magento version**
2.4.1

**Plugin version**
6.7.1 and 7.1.0

Thanks!

**Comment by acampos1916** [comment]
Hello @ebaschiera. It sounds like this could be an issue not only for Google Pay but also for other wallet methods. Thanks for the report, I've created an internal ticket to look into this.
