### ISSUE TITLE
[PW-5271] Adyen response validators implemented in Adyen extension for Magento 2 do not mark the response as failed for Magento

### ISSUE THREAD

**Issue by anthonydangbi** [Adyen/adyen-magento2#1125]
Certain Adyen response validators implemented in Adyen extension for Magento 2 do not mark the response as failed for Magento. Some of them are used on the current project, which makes the behaviour unexpected.

For instance, \Adyen\Payment\Gateway\Validator\CancelResponseValidator does not set $isValid to "false" for failed scenarios, while \Adyen\Payment\Gateway\Validator\CheckoutResponseValidator does the trick. The capture response validator has similar issues.

We have checked the latest codebase for response validators, it seems the issue still exists there. Could that be considered as a bug, so the patch is provided for current project. Otherwise what would be the suggestions from Adyen?

Current version of the Adyen extension for Magento 2 on the project is 6.0.0.

**To Reproduce**

Cart authorisation/cancellation API 

**Response with error:**
{
    "status": 422,
    "errorCode": "167",
    "message": "Original pspReference required for this operation",
     "errorType": "validation"
}

**The response will be validated successfully by this one:**
\Adyen\Payment\Gateway\Validator\CancelResponseValidator::validate()

**This is successful response:**
{"pspReference":"853625149067093J","response":"[cancel-received]"}

**Magento version**
2.4.1

**Plugin version**
6.0.0

**Additional context**

**Comment by cyattilakiss** [comment]
Hi @anthonydangbi ,

Thank you for raising this issue, I have created an internal ticket and we are going to look into it asap.

Best,
Attila
Adyen

**Comment by anthonydangbi** [comment]
Hi Attila

Thank you. Can you share a rough ETA once you get more details?

--

Anthony Dang

Project Manager
[image: Logo]

0401 477 449 / 1300 624 368

Melbourne / Sydney / Canberra / Brisbane / Auckland

balanceinternet.com.au / LinkedIn
<https://www.linkedin.com/company/balance-internet> / Subscribe to News
<https://www.balanceinternet.com.au/sign-up-to-the-balance-internet-newsletter/>
 / Twitter <https://twitter.com/balanceinternet> / Facebook
<https://www.facebook.com/BalanceInternet/>


<https://www.balanceinternet.com.au/news/publicis-groupe-anz-bolsters-commerce-capabilities-with-acquisition-of-balance-internet/>

**Comment by anthonydangbi** [comment]
Good morning

Is there any update on this?
--

Anthony Dang

Project Manager
[image: Logo]

0401 477 449 / 1300 624 368

Melbourne / Sydney / Canberra / Brisbane / Auckland

balanceinternet.com.au / LinkedIn
<https://www.linkedin.com/company/balance-internet> / Subscribe to News
<https://www.balanceinternet.com.au/sign-up-to-the-balance-internet-newsletter/>
 / Twitter <https://twitter.com/balanceinternet> / Facebook
<https://www.facebook.com/BalanceInternet/>


<https://www.balanceinternet.com.au/news/publicis-groupe-anz-bolsters-commerce-capabilities-with-acquisition-of-balance-internet/>

**Comment by acampos1916** [comment]
Hey @anthonydangbi, this is planned and still hasn’t been picked up by our team. If you do have more insights or feedback please share it here. We will update this ticket with any progress made.
