### ISSUE TITLE
Single use coupons are being 'consumed' even when orders fail.

### ISSUE THREAD

**Issue by dsingleton47** [Adyen/adyen-magento2#113]
Single use coupons are being 'consumed' even when orders fail to go through payment for whatever reason ( forgetting 3D secure password seems the common use case ).

We initially followed up with Magento Support, but after they confirmed the issue does not affect non-customised payment methods, they suggested we follow up with you.

Steps to reproduce:

1) On a 2.1.5 EE install, setup a Cart Price Rule with a single use coupon code - doesn't seem to matter if its a specific code, or generated. 
2) Go through the checkout with a valid product to allow you to apply the coupon code, apply the code and continue to checkout. 
3) Using a credit card with 3d secure validation, fail the validation. 
4) Attempt replace the same order - see the coupon code is now invalid.

**Comment by rikterbeek** [comment]
Hi @dsingleton47,

When you get redirected to 3D secure the order is already created in magento. When the authentication failed the order is cancelled and the customer can try again. What you can do is redeem back the coupon code if an order is cancelled.

Regards,
Rik
Adyen
