### ISSUE TITLE
[PW-5394] - Prevent logging to system.log which result of messy and duplicated log content

### ISSUE THREAD

**Issue by onlinebizsoft** [Adyen/adyen-magento2#1137]
**Describe the bug**
For every log information, the module is writing to both system.log and the own log files

**To Reproduce**
The issue can be reproduced by enable debug and placing an order via Adyen, a lots of Adyen information is writing to the system.log and also adyen log files

**Expected behavior**
Only adyen log files should have log

**Magento version**
Any version, I'm testing with 2.4.2 and 2.4.3

**Plugin version**
7.x

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by acampos1916** [comment]
@onlinebizsoft thanks for opening this issue, we've added it to our backlog and will be investigated soon.

**Comment by onlinebizsoft** [comment]
Oh look like there are many issues reported from time to time. This issue is still not picked after many weeks. You should add more developers to maintain your extension for the biggest ecommerce platform

**Comment by acampos1916** [comment]
Thanks for the input @onlinebizsoft. This enhancement is still low priority and we haven’t had more requests about it than this one. If this is pressing for your integration please consider collaborating with this open source project by adding it. Otherwise, we'll work on it as soon as other priorities are finished. Apologies for the delay.

**Comment by onlinebizsoft** [comment]
Almost 1 year now

**Comment by Morerice** [comment]
Hi @onlinebizsoft,

Apologies for the delay. Issue is fixed in the linked PR. This change will be live in the next release (planned for the week of 05/09/22).

Regards,
Jean
Adyen
