### ISSUE TITLE
[PW-5446] Incorrect capture amount in payment request

### ISSUE THREAD

**Issue by mirkocesaro** [Adyen/adyen-magento2#1138]
Hi, 
there is a problem with the capture when the Charged currency is set at the "display" level.

I have Adyen module to version 7.0.1 and to support the multicapture I added the patch[ [PW-5005] Capture subject amount instead of order full amount #1112](https://github.com/Adyen/adyen-magento2/pull/1112) 
In this case, the invoice on Magento won't capture the correct amount.

I found this problem in my environment, where an order was placed on a website with £239.11 as grand total and on the admin it has €281.13 as a base grand total.

When I performed the capture, there is mixed information added in the capture request:

```
(
[currency] => GBP
[value] => 28113
)

```
The right value should be 23911.

In this case, the capture didn't work because the authorized amount was less than the captured one, and I received this message as notification: "reason: Insufficient balance on payment"
But with a different currency, where the exchange rate is better for the EURO, I will capture a really small amount:
base grand total: €461.04 
grand total: CN¥3,507.17

capture request:
```
(
[currency] => CNY
[value] => 46104
)
```
 I lost ~3100 CNY

**To Reproduce**
1. enable different currencies on Magento
2. set, inside the config.php file, the display value for charged_currency in a website 
 ```
... 
       'payment' => [
                    'adyen_abstract' => [
                        'charged_currency' => 'display'
                    ]
         ],
...
 ```
3. set Adyen capture as manual
4. on the frontend, view the website in a currency different from the base currency
5. create an order
6. on the admin, create an invoice
7. wait for the notification 
8. if the exchange rate is unfavourable, you will get an "Insufficient balance on payment" notification message; otherwise, you captured less money for your item 

**Expected behavior**
The captured amount should be check the charged_currency feature

**Magento version**
2.4.1

**Plugin version**
7.0.1 with patch PW-5005

**Comment by mirkocesaro** [comment]
Hi @peterojo,
I just tried the new module but I still have the problem. 

I am not sure if you can check my PSP reference: 883631032074126E
In any case I made an order of ¥134,133.33 (the base amount is €1,028.64) of 3 items at the same price

This is the first invoice 
<img width="833" alt="Screenshot 2021-09-07 at 17 50 02" src="https://user-images.githubusercontent.com/1431255/132382142-c8496552-abf7-4ecc-880d-b427604fe390.png">

And this is the second:
<img width="846" alt="Screenshot 2021-09-07 at 17 50 38" src="https://user-images.githubusercontent.com/1431255/132382211-b6dba0f7-6f3b-4190-a700-205938f73250.png">

But inside the log (and on the adyen platform)
For the first capure:
`{"merchantAccount":"XXXXX","modificationAmount":{"currency":"JPY","value":353},"reference":"500014424","originalReference":"883631032074126E","applicationInfo":{"adyenLibrary":{"name":"adyen-php-api-library","version":"10.1.0"},"externalPlatform":{"version":"2.4.1","name":"Magento"},"merchantApplication":{"version":"7.2.0","name":"adyen-magento2"}}} {"is_exception":false}`

The value should be 44059.11  and not 353 (the value in euro)

For the second capture
`
:{"merchantAccount":"XXXX","modificationAmount":{"currency":"JPY","value":676},"reference":"500014424","originalReference":"883631032074126E","applicationInfo":{"adyenLibrary":{"name":"adyen-php-api-library","version":"10.1.0"},"externalPlatform":{"version":"2.4.1","name":"Magento"},"merchantApplication":{"version":"7.2.0","name":"adyen-magento2"}}} {"is_exception":false}
`
The value should be 88118.22  and not 676 (the value in euro)

Let me know if you need any other info.


Thanks,
Mirko

**Comment by mirkocesaro** [comment]
Hi @peterojo  cc @acampos1916 ,
did you see my message? Are you able to reproduce it? 

I look forward to hearing from you.

Thanks,
Mirko

**Comment by acampos1916** [comment]
Hello @mirkocesaro, this seems to be related to this line https://github.com/Adyen/adyen-magento2/blob/master/Gateway/Request/CaptureDataBuilder.php#L68 the amount being used comes from the invoice subject, but if the Adyen Charged Currency is set to Display there could be a mismatch.

Thanks for this report, I've added it to our backlog and will be fixed ASAP.

**Comment by mirkocesaro** [comment]
Hello @acampos1916 ,
do you have any updates on this bug? 

Thanks,
Mirko

**Comment by tnaber** [comment]
Hi @mirkocesaro,

Thank you for your patience :) The linked pull request should resolve this bug, both for partial and full invoices. Additionally, it should work in both 7.2 and 7.3. 

Let me know if you are still experiencing problems after this fix!

Cheers,
Titus
