### ISSUE TITLE
[PW-5458] Compile error in \Helper\Requests.php line 403 and forward (since release #1001)

### ISSUE THREAD

**Issue by krite** [Adyen/adyen-magento2#1148]
AdyenCcDataAssignObserver::ENCRYPTED_CREDIT_CARD_NUMBER and the other constants used in previous versions are still referenced in some places.

**Comment by AlexandrosMor** [comment]
Hello @krite ,

Could you provide us more examples and which version are you facing this issue? 

kind regards,
Alexandros
Adyen

**Comment by krite** [comment]
No modifications, the constants are referenced in current master and in latest release 7.2.0.
Check https://github.com/Adyen/adyen-magento2/blob/a428d81d8a7a1ebd163470ff20e41c9ecc366835/Helper/Requests.php#L403

Then check the constants those lines still refer to
https://github.com/Adyen/adyen-magento2/blob/a428d81d8a7a1ebd163470ff20e41c9ecc366835/Observer/AdyenCcDataAssignObserver.php#L35

These constants were removed by Attila in commit: caa0537143d464204c37639750c86acb37ab5a5b / release 7.0.0.

**Comment by acampos1916** [comment]
Hello @krite, indeed those constants are not present anymore and the usage should be removed, I'm creating a ticket for this. Be aware that the function `buildCCData()` is not being used anymore in the plugin, so is this maybe a customization?

**Comment by tnaber** [comment]
Hi @krite, after looking for some more unused references I found that most were removed. Do you have more examples where it should be fixed (in the current version)? Otherwise, I'll be closing this issue.
