### ISSUE TITLE
SQL error when checking out with AliPay due to conflict with amzn/amazon-pay-module

### ISSUE THREAD

**Issue by LRotherfield** [Adyen/adyen-magento2#1149]
**Describe the bug**
An SQL error is thrown after returning to the site from the Adyen acquirer simulator when using payments such as AliPay.
Full Error is:

```
SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'entity_id' in where clause is ambiguous, query was: SELECT `main_table`.*, `extension_attribute_amazon_order_reference_id`.`amazon_order_reference_id` AS `extension_attribute_amazon_order_reference_id_amazon_order_reference_id`, `extension_attribute_amazon_order_reference_id`.`quote_id` AS `extension_attribute_amazon_order_reference_id_quote_id`, `extension_attribute_amazon_order_reference_id`.`sandbox_simulation_reference` AS `extension_attribute_amazon_order_reference_id_sandbox_simulation_reference`, `extension_attribute_amazon_order_reference_id`.`confirmed` AS `extension_attribute_amazon_order_reference_id_confirmed` FROM `quote` AS `main_table`
 LEFT JOIN `amazon_quote` AS `extension_attribute_amazon_order_reference_id` ON main_table.entity_id = extension_attribute_amazon_order_reference_id.quote_id WHERE ((`entity_id` = '1019802'))
Exception #1 (PDOException): SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'entity_id' in where clause is ambiguous
```

This is caused by `magento/vendor/adyen/module-payment/Helper/Quote.php:127` calling `$this->searchCriteriaBuilder->addFilter('entity_id', $order->getQuoteId())` without specifying the table alias.  The conflicting amazon table is joined by `magento/vendor/amzn/amazon-pay-module/etc/extension_attributes.xml:21` and this module is included by core Magento.

**To Reproduce**
1. Start checkout and choose AliPay as the payment method so you are redirected to https://test.adyen.com/acquirersimulator/pay.shtml
2. Choose authorised
3. Click continue

**Expected behavior**
Order placed successfully and user redirected to checkout/success

**Magento version**
2.3.7-p1

**Plugin version**
7.2.0

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Brave v1.28

**Additional context**
This is easily resolved by adding the `main_table.` alias:
```
$this->searchCriteriaBuilder->addFilter('main_table.entity_id', $order->getQuoteId())
```

**Comment by acampos1916** [comment]
Thank you for your feedback @LRotherfield, the suggested fix was already introduced in #1144.
