### ISSUE TITLE
[PW-5456] 3DS1 card token not saved in vault [7.2.0]

### ISSUE THREAD

**Issue by LRotherfield** [Adyen/adyen-magento2#1153]
**Describe the bug**
After submitting a CC payment with a 3DS1 card and choosing "save for later payment", the token is not saved against the customers account.

**To Reproduce**
1. Go to checkout
2. Click on cc payment, use a [3DS1 card](https://docs.adyen.com/development-resources/test-cards/test-card-numbers#test-3d-secure-authentication) and check "save for later payment"
3. Submit payment and complete 3DS authorisation
4. Order will be created with successful payment but no token will be saved

**Expected behavior**
Token is saved for card so it can be used at a later date

**Magento version**
2.3.7-p1

**Plugin version**
7.2.0

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Brave v1.28

**Additional information**
As far as I can see, the path for 3DS1 to hit `\Magento\Vault\Observer\AfterPaymentSaveObserver::execute` is triggered by `magento/vendor/adyen/module-payment/Controller/Process/Result.php:252` (added in 7.2.0) which happens before the token details are added as an extension attribute here: `magento/vendor/adyen/module-payment/Controller/Process/Result.php:258`

This means the token is null at the point Magento tries to save it

**Comment by acampos1916** [comment]
Hello @LRotherfield thanks for opening this issue. I have confirmed that this could be an issue with saving 3DS1 tokens in Vault. We're going to look into it ASAP.

Cheers,
Ángel

**Comment by LRotherfield** [comment]
@acampos1916 do you think you will put up a bug fix point release (7.2.1) for the bugs currently reported?  For our clients, 7.0.x, 7.1.0 and 7.2.0 all have core bugs (not third party module dependent) that prevent us from launching them as they would affect the customer UX.  This means we are currently on the 6.7.x releases. Although we are interested in the features being added, it would be better for us to have a launch-able 7.2.1 than a new feature branch (7.3) that potentially adds new bugs and thus leaves us still on 6.7.

**Comment by acampos1916** [comment]
Hey @LRotherfield I understand the concern, unfortunately 7.3 is already on the way as some new features have already been merged. Would it be an option to apply this specific PR as a patch?
