### ISSUE TITLE
[PW-5649] Potential 704 issue

### ISSUE THREAD

**Issue by LRotherfield** [Adyen/adyen-magento2#1166]
**Describe the bug**
A while ago we reported a bug to @cyattilakiss (I think this was over the phone so I have no email log) where a customer was able, from some 3DS1 verification pages, to make a double post request to the Adyen redirect controller.  When that happened, the first request created a successful order, however the second request which the customers browser followed received a 704 response from the Adyen server and thus sent the user to the cart page with a failure notice.  This lead to the customer trying again and consequently ending up with 2 orders that they were charged for.

When the transparent redirect page was added, this inadvertently also fixed our issue so work on a patch was stopped.  However when I read the reason, in the 7.0.0 release notes, for removing the transparent redirect, it does not sound like the duplicate request issue was considered?

We are about to launch 7.1.0 with a number of patches from 7.2.0 and would just like to hear your thoughts, would you expect your changes to reintroduce this error?  Unfortunately this bug was not something we could replicate using the Adyen 3DS1 test system so we have no way of proving if it has been reintroduced.

The error in the logs was: AdyenLoggerTest.ERROR: 704: request already processed or in progress

**Comment by Morerice** [comment]
Hi @LRotherfield 

Thanks for opening this issue. Unfortunately we currently cannot provide a definitive answer regarding your request, since this will require some internal discussion from our part. We will provide some updates regarding this issue once these discussions are held.

In the meantime if you obtain some further information, feel free to update this ticket with more info.

Best regards,
Jean
Adyen

**Comment by Morerice** [comment]
Hi @LRotherfield,

Unfortunately we were unable to replicate the customer's issue either. Is there some further information you could share with us to help us investigate this?

Thanks,
Jean
Adyen

**Comment by Morerice** [comment]
Closing this issue for now since no further information is provided. Feel free to re-open if more details regarding this issue come up.

Thanks,
Jean
Adyen
