### ISSUE TITLE
Version 7.2.0 is no longer compatible with Magneto 2.3

### ISSUE THREAD

**Issue by Skullsneeze** [Adyen/adyen-magento2#1169]
**Describe the bug**
Adyen version 7.2.0 is no longer compatible with Magneto 2.3 (Tested on version 2.3.6). It requires a non existing class, and breaks the DI Compilation.

**To Reproduce**
1. Install or upgrade the Adyen plugin to version 7.2.0
2. Enable the module
3. Run bin/magento setup:di:compile
4. You will see the following exception:
```
Fatal error:  Class 'Magento\Multishipping\Block\Checkout\Success' not found in vendor/adyen/module-payment/Block/Checkout/Multishipping/Success.php on line 39
```

**Expected behavior**
The compilation of generated code succeeds

**Magento version**
2.3.6

**Plugin version**
7.2.0

**Additional context**
The current Readme.md file still states there is support for the following Magento versions:
- 2.2.9 and higher
- 2.3.1 and higher
- 2.4

**Comment by acampos1916** [comment]
Hey @Skullsneeze, thanks for the report. It looks like this class is indeed present in 2.3.6 https://github.com/magento/magento2/blob/2.3.6/app/code/Magento/Multishipping/Block/Checkout/Success.php, any ideas what could be wrong?

But it does look like the module should require Magento_Multishipping as a dependency.
