### ISSUE TITLE
[PW-5810] Unpredictable order state change

### ISSUE THREAD

**Issue by ryanpalmerweb** [Adyen/adyen-magento2#1173]
**Describe the bug**

When a payment is authorised (without a capture), if the selected status for this is assigned to more than one state, the behaviour is unpredictable as either of the available states could be selected.

`    /**
     * Set State from Status
     */

    protected function _setState($status)
    {
        $statusObject = $this->_orderStatusCollection->create()
            ->addFieldToFilter('main_table.status', $status)
            ->joinStates()
            ->getFirstItem();

        $this->_order->setState($statusObject->getState());
        $this->_adyenLogger->addAdyenNotificationCronjob('State is changed to  ' . $statusObject->getState());
    }`

We currently have a status 'processing_not_captured' assigned to both STATE_PENDING_PAYMENT and STATE_PROCESSING, this is to allow for multiple order flows across different stores.

As the relationship status and state do not have a one to one relationship, it is unsafe to rely on getFirstItem() as the admin user has no way to see which state will be used.

**To Reproduce**

1. Create a new order status (e.g processing_not_captured) and assign it to the processing state
2. Configure the Adyen module so that authorised orders should use this status
3. An authorisation in a notification will now set the order state to processing and status to processing_not_captured.
4. This order now appears in the sales reporting.

but

5. Additionally assign the order status to an additional state (e.g pending_payment)
6. Now, although the status is assigned to both pending_payment and processing, an authorisation in a notification will now set the order state to pending_payment and status to processing_not_captured.

This then leads to issues, for example in our situation the sales report module ignores any orders with a state of pending_payment

It is unsafe to choose the order state based on the status because of this, as from the admin configuration perspective there is no indication this could happen

<img width="1265" alt="Screenshot 2021-10-11 at 11 01 16" src="https://user-images.githubusercontent.com/7669058/136772230-59f5c5a7-c682-4978-bf6a-670e3d0b94c8.png">
<img width="668" alt="Screenshot 2021-10-11 at 11 03 05" src="https://user-images.githubusercontent.com/7669058/136772233-99ceedf3-c8c5-4afb-985a-6c043b3d8069.png">

**Expected behavior**

Either allow the user to choose a state in the configuration, or ensure that payments are kept in a consistent state.

**Magento version**
2.4.1

**Plugin version**
6.6.6

**Comment by ryanpalmerweb** [comment]
Also link to Magento docs below : 

https://docs.magento.com/user-guide/sales/order-workflow.html

> Step 3: Receive Payment
The status of the order changes to Processing when payment is received or **authorized.** Depending on the payment method, you might receive notification when the transaction is authorized or processed.

**Comment by tnaber** [comment]
Hi @ryanpalmerweb,

Thank you for opening this issue, an internal ticket has been created. This will be tackled soon.

Cheers,
Titus

**Comment by tnaber** [comment]
Hi @ryanpalmerweb,

When investigating this issue, we decided that we should follow the order workflow from Magento and will make sure that payments are kept in a consistent state.
However, as we are working on a restructuring of our webhooks, the fix for this issue will be postponed until after the introduction of this webhook module. It should be introduced in the next couple of sprints.

Cheers,
Titus
