### ISSUE TITLE
Optional Chaining used in latest 7.2.0 release

### ISSUE THREAD

**Issue by zakisaad** [Adyen/adyen-magento2#1191]
**Describe the bug**

Optional chaining (?. operator) has been used in client-side Javascript. Support on modern browsers is OK (https://caniuse.com/mdn-javascript_operators_optional_chaining), however not ideal to have customer-facing code using this without transpiling taking place first. Affected file:

https://github.com/Adyen/adyen-magento2/blob/19ed495c365312ea363915763020a6a1259fb98e/view/frontend/web/js/view/checkout/summary/agreements-assigner-mixin.js

This has actually broken our JS bundler setup, causing our site to clog up due to massive request load. The requirejs optimiser does not yet support optional chaining on the mainline release:

https://github.com/requirejs/r.js

https://github.com/requirejs/r.js/issues/1003

We've had to patch out the use of optional chaining to get the bundler to work on our M2 codebase.

**To Reproduce**
Attempt to optimise JS/use JS on older browser

**Expected behavior**
Backwards-compatible JS does not cause problems

**Magento version**
2.3.7-p1

**Plugin version**
7.2.0

**Comment by acampos1916** [comment]
Thanks @zakisaad, this has already been replaced.
