### ISSUE TITLE
[PW-5668] Orders staying in Payment Review after OFFER_CLOSED since 7.0.1 -> 7.2.0 upgrade

### ISSUE THREAD

**Issue by zakisaad** [Adyen/adyen-magento2#1193]
**Describe the bug**
This has been occuring since upgrading to 7.2.0 from 7.0.1 - OFFER_CLOSED notifications should cancel the related order, however the order is staying in Payment Review.

Status history is added to the order RE the closed offer, however the order stays open.

Our downstream systems listen to the state of the M2 order and therefore we have a building list of orders that are pending in our ERP. 

**To Reproduce**
Place order through Adyen, wait for OFFER_CLOSED, Magento accepts the notification but doesn't cancel the order.

**Expected behavior**
Order is to be cancelled with the acknowledgement of the OFFER_CLOSED notification.

**Magento version**
2.3.7-p1

**Plugin version**
7.2.0

**Screenshots**

![image](https://user-images.githubusercontent.com/7424248/137464516-c8d1fc6a-e003-41ff-afd8-81f95a1a90f3.png)

**Comment by zakisaad** [comment]
FYI, we had to urgently downgrade our M2 Adyen module from 7.2.0 to 7.0.1 last weekend.

This issue, along with the deprecation of 3DS2.0 toggle in settings (the native flow without this param set *does not work with on our store* - TEST cards do not have any issues, checkout seems OK, but 95% of local AU cards trying to checkout with native 3DS2.0 on our LIVE environment were not able to check out due to this deprecation), meant that customers were dropping off and stock holds were piling up.

Awaiting future releases, but looks like we'll have to do alot more extensive UAT in the future when upgrading as we did encounter multiple snags (including an optional chaining issue on client JS that we had to patch out).

Are there any plans to bring back the 3DS2.0 toggle in the settings or will we have to maintain a patch for this?

We use OneStepCheckout, so I know this isn't a supported use case, but nonetheless our store is broken with it native flow enabled - again, we can't replicate this issue on TEST. Only on our LIVE-connected production site do we have issues with native 3DS2.0.

Thanks!

**Comment by killoff** [comment]
@zakisaad thanks for submitting the issue. We are facing the same problem.

This is was my request to Adyen Support team and we're currently negotiating it:

```
We using Adyen Payments Plugin for Magento latest version  7.2.0
We recently upgraded module from 7.0.1 to 7.2.0
Not sure if this is a reason for this issue, but before we did not experience it.

The thing is, some orders getting Payment Review status.
Later on, OfferCancelled event triggered in Adyen and we getting notification OFFER_CLOSED
Accordingly to this kind of notification - Magento Order should be cancelled and everything is over.

However, order cannot be cancelled, because Magento can cancel only Pending orders.
As the result we have these "hanging" orders in Payment Review status.
```

**Comment by acampos1916** [comment]
Thanks for adding more info @killoff. Which payment method has been used in the orders that remain in Payment Review? Is there related information in `var/log/adyen/cronjob.log`?

**Comment by acampos1916** [comment]
Many thanks for this contribution @LRotherfield, we'll investigate what you found, review your patch and open a PR for it.
