### ISSUE TITLE
Live endpoint prefix protocol https duplication 

### ISSUE THREAD

**Issue by lano-vargas** [Adyen/adyen-magento2#1199]
**Describe the bug**
Field Live endpoint prefix  when entered "https://1797a841fbb37ca7-AdyenDemo-checkout-live.adyenpayments.com/checkout/v53/payments"  produce duplication of protocol when trying to connect.

**To Reproduce**
1. Log in to your live Customer Area.
2. Go to Developers > API URLs.
On the API URLs and Response page, you can see the configured endpoints for your company account.
3. Copy Checkout endpoint.
4. Go to Magento backend Stores->Configuration->Sales->Payment Methods->Adyen All-in-One Payment Solutions->Required Settings->Live endpoint prefix  and paste 
5. Save Config
6. Put an item in you basket got to checkout payment page.

A 500 error is receive on retrieving adyes payment methods. Looking at the error logs:
```
[2021-10-19 08:24:12] main.CRITICAL: Report ID: webapi-616e80ace4aac; Message: Could not connect to Adyen (https://https://random-myCompany-checkout-live.adyenpayments.com/checkout/v68/payments-checkout-live.adyenpayments.com/checkout/v67/paymentMethods).  Please check your internet connection and try again.

(Network error [errno 6]: Could not resolve host: https; Unknown error) {"exception":"[object] (Exception(code: 6): Report ID: webapi-616e80ace4aac; Message: Could not connect to Adyen (https://https://random-myCompany-checkout-live.adyenpayments.com/checkout/v68/payments-checkout-live.adyenpayments.com/checkout/v67/paymentMethods).  Please check your internet connection and try again.
```

**Expected behavior**
Should not duplicate https protocol when connecting should either use the field as is or check if contains https protocol already b4 adding it.

**Magento version**
[e.g. 2.3.5]

**Plugin version**
[e.g. 7.2.0]

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
For now to mitigate the error enter domain without protocol as the extension is adding it.
Helpfull to have in the comment to only enter domain without protocol or add a validation rule to the field.
![Screen Shot 2021-10-19 at 10 00 24](https://user-images.githubusercontent.com/3495481/137878199-4deed482-10b0-47ba-8753-e90590eb5dce.png)

**Comment by peterojo** [comment]
the tooltip has been updated to clarify the required input for `Live endpoint prefix`.
Closing this ticket
