### ISSUE TITLE
Does the extension allow to write tokens to the Magento Vault / Subscription payment support

### ISSUE THREAD

**Issue by amenk** [Adyen/adyen-magento2#120]
this would help to support Subscription Payments like 
https://store.paradoxlabs.com/store/magento2-subscriptions-recurring-billing.html (out of the box)
or 
https://www.magedelight.com/magento-2-extensions/subscribe-now-magento-2.html

**Comment by rikterbeek** [comment]
Hi @amenk,

We will look into if we can save the cards into the Vault as well. We provide the token back on a later stage through a Notification. I quickly looked into the Vault solution and it looks it does only support it when you receive the token back from the API call. This will limit it to Cards only and we would like to have support for all the payment methods where we allow this. Did you did some investigation as well into the Vault system maybe you have some ideas ?

Regards,
Rik
Adyen

**Comment by amenk** [comment]
We hired MageDelight to integrate there subscription module with your Adyen Module - they told me they would probably also be using the Vault in their solution. In case you are interested, I can establish a contact for you with them...

**Comment by rikterbeek** [comment]
HI @amenk,

If you can connect me directly to them that would be great.

Regards,
Rik
Adyen

**Comment by amenk** [comment]
@rikterbeek please drop me an email to a dot menk at imi dot de.

**Comment by danielozano** [comment]
@amenk @rikterbeek do you have more information about this? It's really interesting for me having adyen payments inside vault, even it it's only for credit cards.

There is any way I can help?

Thank you!

**Comment by rikterbeek** [comment]
@danielozano,

It looks like the problem we have with the vault solution is that the token needs to be provided in the result of the authorisation. What in our case is not the case what makes it difficult to integrate. On our end we want to provide the token in the responds but that is a project that will take some time before we have this finished. I did not dived to much into it but maybe you did and you see some kind of work around ?

Regards,
Rik
Adyen

**Comment by ebaschiera** [comment]
Hi,
is there any update on this with the official Adyen module? Is MageDelight's module the only solution available for subscription payments on Magento 2?
Thanks.

**Comment by danielozano** [comment]
Hi @ebaschiera, looks like the team is working on the implementation of vault (or they pretend to do it):
#253, #252, #255

I don't know if magedelight module is still compatible with adyen, because they use the encrypted data, which is removed on the new version of the adyen module (as far as I know)

I've invested a lot of time on trying to make adyen work with vault systems. There are other modules that create subscription systems compatible with vault payment methods, and also there is another module from aheadworks that implements adyen credit card out of the box.

I you want more information you can email me and I can provide you some information!

Regards.

**Comment by rikterbeek** [comment]
Hi @ebaschiera @danielozano @amenk,

We have started to build an integration into the vault system. It does basically the same as we already done with billing agreement but we see that tokens are used for a lot of 3rd party providers that have support for subscription. The code is commit against a feature branch https://github.com/Adyen/adyen-magento2/tree/feature/vault for testing purposes when completed we need to find a way to merge it into develop and have our customers have an option between billing agreements and vault implementation. Billing agreements has the advantage that the transactions are going over our ONECLICK technology where an extra security code is need to fill in where Vault is using only recurring.

Regards,
Rik
Adyen

**Comment by etessari** [comment]
Hi,
looking at the plugin page https://www.adyen.com/partners/magento it is mentioned "Start accepting subscription and recurring payments." 

so is the subscription payment method natively supported by the official plugin?
Thanks.

**Comment by msilvagarcia** [comment]
I'm closing this issue because Magento 2 Vault is supported.

Feel free to create a new one if there are any questions left.

Cheers!
Marcos
Adyen
