### ISSUE TITLE
[PW-5937] IE11 and older browsers not working.

### ISSUE THREAD

**Issue by s1nz** [Adyen/adyen-magento2#1202]
**Describe the bug**
Adyen payment methods are not working in IE11 and other older browsers. The problem occurs because of trailing commas in js files, modern js methods (Array.includes), URL API, negative lookbehind in regex.

File's with errors: `adyen-configuration.js`, `adyen-hpp-method.js`, `adyen-oneclick-method.js`. Probably other scripts are also affected.

**To Reproduce**
1. Go to checkout with IE11
2. There are no adyen payment methods

**Expected behavior**
The code should be using older js api's and work in IE11

**Magento version**
2.4.1

**Plugin version**
7.3.0

**Desktop:**
 - OS: [Windows 10, Mac OS]
 - Browser: [Internet Explorer, Safari]
 - Version: [11, 11.1]

**Mobile:**
- OS: iOS 13 and lower

**Comment by tnaber** [comment]
Hi @s1nz,

A small update on this matter: currently our QA pipeline is being expanded. This will provide automated testing for multiple browsers to prevent problems like this one in the future. However, as IE11 is near deprecation, this will not be included as a test case. In practice this means we will not be supporting IE11 on this plugin.

Cheers,
Titus

**Comment by jonathanribas** [comment]
Hi @tnaber, it would be interesting to know which browsers and versions does your extension support?

**Comment by tnaber** [comment]
Hi @jonathanribas, we are actively testing for the latest versions of Chrome, Safari and Firefox. We might expand to also test for older version but are not focussing on that right now. If there is a specific version that is important to you, let me know!

**Comment by jonathanribas** [comment]
Hi @tnaber, not a specific version in mind, it was just to tell our Digital team what we actually support in terms of browsers and versions.

**Comment by tnaber** [comment]
Currently our focus is on support for the latest versions of the major browsers (edge, safari, chrome, firefox). When our QA pipeline is expanded to also support older versions we will provide a support matrix.
I am closing this issue as we decided not to support IE11.
