### ISSUE TITLE
Google Pay is not available for not logged into Google Account users

### ISSUE THREAD

**Issue by VeronikaKurochkina** [Adyen/adyen-magento2#1208]
**Describe the bug**
When checking out and selecting Google Pay and error message states "Google Pay is not available". Is reproduced for customer who is not logged in to Google account.

**To Reproduce**
1 Add items to cart
2 Click on checkout
3 Select Google Pay as the payment method
4 See error

**Expected behavior**
Once you choose Google Pay you should be able to select to complete your order

**Magento version**
2.3.6

**Plugin version**
6.6.9

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
Sometimes I get an Error in the console: "Google Pay - No paymentMethodPresent"
![image](https://user-images.githubusercontent.com/93131106/138713980-cb54441a-fe6c-40a5-9c2a-8276e5877232.png)

![image](https://user-images.githubusercontent.com/93131106/138714132-9bfecd9a-7556-44b8-b5a4-fd69b8a3a0de.png)

**Comment by tnaber** [comment]
Hi,

I'm closing this. Please feel free to reopen if the issue still persists!

Cheers,
Titus
