### ISSUE TITLE
[PW-5086] Mismatch in increment ID in adyen and Magento for POS orders

### ISSUE THREAD

**Issue by LexKoomen** [Adyen/adyen-magento2#1209]
**Describe the bug**
If you place an order with the POS terminal you get a mismatch in increment_id in Magento and Adyen. Therefore the order payment is pushed to Adyen, but can not be pushed back to Magento because the increment id doesnt match.

This issue exists because the terminal payment method sets a reserved order id, but this order id is removed by another plugin.

This model adds the reserved order id:
https://github.com/Adyen/adyen-magento2/blob/develop/Model/AdyenInitiateTerminalApi.php L138:

```
$payment->setMethod(AdyenPosCloudConfigProvider::CODE);
$reference = $quote->reserveOrderId()->getReservedOrderId();

$service = $this->adyenHelper->createAdyenPosPaymentService($this->client);
```

These plugins remove the reserved order ids:
https://github.com/Adyen/adyen-magento2/blob/develop/Plugin/GuestPaymentInformationResetOrderId.php
https://github.com/Adyen/adyen-magento2/blob/develop/Plugin/PaymentInformationResetOrderId.php

I created a patch which surrounds the plugins with a check on payment method. And that solves the problem, but I do not believe this is the best solution, you decide :D 

```
Index: vendor/adyen/module-payment/Plugin/PaymentInformationResetOrderId.php
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/vendor/adyen/module-payment/Plugin/PaymentInformationResetOrderId.php b/vendor/adyen/module-payment/Plugin/PaymentInformationResetOrderId.php
--- a/vendor/adyen/module-payment/Plugin/PaymentInformationResetOrderId.php
+++ b/vendor/adyen/module-payment/Plugin/PaymentInformationResetOrderId.php	(date 1635163884996)
@@ -61,7 +61,10 @@
         $cartId
     ) {
         try {
-            $this->quoteRepository->get($cartId)->setReservedOrderId(null);
+            $quote = $this->quoteRepository->get($cartId);
+            if ($quote->getPayment()->getMethod() !== 'adyen_pos_cloud') {
+                $quote->setReservedOrderId(null);
+            }
         } catch (\Exception $e) {
             $this->adyenLogger->error("Failed to reset reservedOrderId " . $e->getMessage());
         }

Index: vendor/adyen/module-payment/Plugin/GuestPaymentInformationResetOrderId.php
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/vendor/adyen/module-payment/Plugin/GuestPaymentInformationResetOrderId.php b/vendor/adyen/module-payment/Plugin/GuestPaymentInformationResetOrderId.php
--- a/vendor/adyen/module-payment/Plugin/GuestPaymentInformationResetOrderId.php
+++ b/vendor/adyen/module-payment/Plugin/GuestPaymentInformationResetOrderId.php	(date 1635163885003)
@@ -72,7 +72,10 @@
         try {
             $quoteIdMask = $this->quoteIdMaskFactory->create()->load($cartId, 'masked_id');
             $quoteId = $quoteIdMask->getQuoteId();
-            $this->quoteRepository->get($quoteId)->setReservedOrderId(null);
+            $quote = $this->quoteRepository->get($quoteId);
+            if ($quote->getPayment()->getMethod() !== 'adyen_pos_cloud') {
+                $quote->setReservedOrderId(null);
+            }
         } catch (\Exception $e) {
             $this->adyenLogger->error("Failed to reset reservedOrderId for guest shopper" . $e->getMessage());
         }
```

**To Reproduce**
1. Create a quote and go to checkout
2. Try to pay with a terminal
3. See that you placed the order
4. Increment ID of order skips 1 order and doesnt match the increment id in Adyen

**Expected behavior**
The increment id of the order and the increment id in adyen should match. (for obvious reasons)

**Magento version**
2.3.7+

**Plugin version**
6.6.1 +

**Comment by tnaber** [comment]
Hi @LexKoomen,

After carefully reviewing this issue we have decided to adopt your solution. Thanks for the contribution!
Feel free to have a look at #1247 :)

Cheers,
Titus

**Comment by pmzandbergen** [comment]
Encountered the same issue today. Nice to see it has already been resolved GJ @LexKoomen / @tnaber
