### ISSUE TITLE
Magento headless integration documentation does not inform about 3DS1 flow support

### ISSUE THREAD

**Issue by Fifciu** [Adyen/adyen-magento2#1217]
**Describe the bug**
Magento headless integration documentation does not describe RedirectShopper flow.

**To Reproduce**
Check the document: https://docs.adyen.com/plugins/magento-2/magento-headless-integration#handling-the-paymentsdetails-response

**Expected behavior**
There is information for 3DS2 flow. But we also need steps to configure 3DS1 flow. It will be essential for also other Redirect-based payment methods like Klarna, Zip, Sofort, AfterPay etc.

**Comment by acampos1916** [comment]
Hello @Fifciu,

The RedirectShopper response and the rest of response codes are covered in the "Handle additional actions" section https://docs.adyen.com/plugins/magento-2/magento-headless-integration#handle-additional-actions

In a few words, the Web Components library can take care of the redirect if the action object is used in `createFromAction` or `handleAction`.

If you have any suggestions to improve the docs let us know!

**Comment by acampos1916** [comment]
@Fifciu I just checked the section you linked about the payment details request, in that part of the flow the redirect is handled with the `isFinal=false` and `action` object present scenario.

**Comment by Fifciu** [comment]
> Hello @Fifciu,
> 
> The RedirectShopper response and the rest of response codes are covered in the "Handle additional actions" section https://docs.adyen.com/plugins/magento-2/magento-headless-integration#handle-additional-actions
> 
> In a few words, the Web Components library can take care of the redirect if the action object is used in `createFromAction` or `handleAction`.
> 
> If you have any suggestions to improve the docs let us know!

It requires to:
- Set PWA's URL in the Magento
- Request magento to replace `merchantReference` to `orderId` (entity_id)
- Send `redirectResult` as a part of `details` to the `/adyen/paymentDetails` endpoint

What's more both `redirectResult` and `merchantReference` comes from the URL's query param.

Things above should be described in the linked document.
