### ISSUE TITLE
[Storefront] returnUrl field in Magento's Dashboard

### ISSUE THREAD

**Issue by Fifciu** [Adyen/adyen-magento2#1223]
**Is your feature request related to a problem? Please describe.**
In plugin's configuration we have 1 field and it's value is used for two purposes:
- as an `origin`
- to build `returnUrl`

It's problematic if the endpoint in our storefront starts with some prefix and we cannot change it as our system forces it. 

I have to redirect back after RedirectShopper process to the: `http://localhost:3000/api/adyen/process/result?someQueryData`. `/api` is our obligatory prefix. But its impossible for me to put there prefix part.    

If I set `Payment Origin URL` as `http://localhost:3000/api` then `orgin` is wrong.    
If I set `Payment Origin URL` as `http://localhost:3000` then `returnUrl` is wrong.

**Describe the solution you'd like**
A dedicated field for setting `returnUrl`.
So instead of:
```php
        $returnUrl = rtrim(
                $this->baseUrlHelper->getStoreBaseUrl($this->storeManager->getStore()->getId()), '/'
            ) . '/adyen/process/result?merchantReference=' . $order->getIncrementId();
```
We would have:
```php
$returnUrl = rtrim(
                $valueOfNewField), '/'
            ) . '?merchantReference=' . $order->getIncrementId();
```

**Comment by acampos1916** [comment]
Thanks for opening this issue and for the contribution @Fifciu, #1224 looks very nice.

What is the use case for the `/api` part of your returnUrl? Maybe this is an issue very specific to your implementation and it that case there wouldn't be much use for other integrations.

**Comment by Fifciu** [comment]
Each endpoint that does not render a view, starts with `/api` prefix so it does not pollute the main scope and it's just a space for Express API, independent from the frontend. The endpoint does its job and then redirects to the confirmation view in the frontend. 

It's the case especially related to PWAs - it doesn't have point to render additional view in PWA just to send a request and redirect. Secondly, different PWAs systems might have different requirements so giving the flexibility to provide returnUrl is very handy for every storefront integration. [Commercetools & Adyen integration](https://github.com/commercetools/commercetools-adyen-integration/blob/master/extension/docs/WebComponentsIntegrationGuide.md#step-5-make-a-payment) allows it and it works like a charm.

**Comment by acampos1916** [comment]
Sounds good @Fifciu, then if I get it correctly, in your integration the `/api` space will forward the request to the Adyen plugin Result.php controller?

**Comment by Fifciu** [comment]
> Sounds good @Fifciu, then if I get it correctly, in your integration the `/api` space will forward the request to the Adyen plugin Result.php controller?

Not exactly. In our integration (Vue Storefront 2) `/api/adyen/afterAuthRedirectBack` is our node.js equivalent of the Adyen plugin Result.php controller. It sends additional payment details to the Adyen and then redirects to checkout confirmation page.
