### ISSUE TITLE
PayPal RECURRING_CONTRACT not saved correctly

### ISSUE THREAD

**Issue by alessandroniciforo** [Adyen/adyen-magento2#123]
**Steps to reproduce**

1. On Magento Admin, configure Adyen to do RECURRING billing agreements (billing agreement section, oneclick section, hpp section). Ensure you have your cron for Magento configured and running. Ensure you have Paypal enabled on Adyen.
2. Complete a purchase with PayPal (on PayPal payment page you'll be asked the authorization for allowing the merchant to charge you for future purchases)
3. Wait for the Adyen notification to be processed by the cronjob

**Expected**

4. The notification is processed successfully, a new billing agreement is created in the table "paypal_billing_agreement" labeled as "PayPal myemail@example.org"

**Actual**

4. The processing of the notification gives errors and thus the new billing agreement is not created.

The actual error I'm getting is `PHP Notice:  Undefined index: lastKnownShopperEmail` issued at [Agreement.php#123](https://github.com/Adyen/adyen-magento2/blob/develop/Model/Billing/Agreement.php#L123). This is preventing the cronjob execution to complete successfully.
The expected key "lastKnownShopperEmail" is not in the array passed as argument that represents a single `RecurringDetail` of the response to `listRecurringDetails` but it's, instead, on main object returned by `listRecurringDetails`.

**Comment by rikterbeek** [comment]
Hi @alessandroniciforo,

Thanks for letting us know. Could you check if the fix above solve your issue. I see that lastKnownShopperEmail is a value that can be empty. It looks like we can get back the email from the tokenData that we get back from PayPal.

example of response PayPal Recurring contract:
    [tokenDetails] => Array
        (
            [tokenData] => Array
                (
                    [EmailId] => tedtest@test.nl
                    [PayPal.PayerId] => H95EPL8B2KFE6
                    [BillingAgreementId] => B-7MA42752FE774625C
                )

            [tokenDataType] => PayPal
        )



Regards,
Rik
Adyen

**Comment by alessandroniciforo** [comment]
Hi @rikterbeek,
just tried it and it does solve the issue!
Thanks,
Alessandro

**Comment by rikterbeek** [comment]
Hi @alessandroniciforo,

Great and thanks for letting us know.

Regards,
Rik
Adyen
