### ISSUE TITLE
I can't pay with Apple Pay if my quote grand total is updated

### ISSUE THREAD

**Issue by jonathanribas** [Adyen/adyen-magento2#1230]
**Describe the bug**

If you want to pay with Apple Pay and you choose a non free shipping method or create a new US shipping address where a tax will apply, it won't work.

Why?

When Adyen's payment methods are retrieved for the first time, no shipping address is set on your quote neither a shipping method selected. At the moment the call is done to retrieve them, it sends your current's quote base grand total.

It seems Apple Pay integration is different than Credit Card integration as if quote grand total change between the payment methods retrieve and the moment you will pay, it will work. With Apple Pay it won't as grand total has changed.

`[2021-11-05 15:33:22] AdyenLoggerTest.INFO: JSON Request to Adyen:{"channel":"Web","merchantAccount":"CaudalieUS","countryCode":"US","shopperLocale":"en_US","amount":{"currency":"USD","value":9000},"telephoneNumber":"+1555 555 5555"} {"is_exception":false} []
`

When you pay with Apple Pay, as you can see amount is now different:

`[2021-11-05 15:34:05] AdyenLoggerTest.INFO: JSON Request to Adyen:{"merchantAccount":"CaudalieUS","shopperReference":"xxxxxxx","shopperEmail":"yyyy@yyyy.com","telephoneNumber":"+1555 555 5555","shopperName":{"firstName":"Test","lastName":"Test"},"countryCode":"US","shopperLocale":"en_US","shopperIP":"194.172.44.186","billingAddress":{"street":"5601 Arringdon Park Drive","postalCode":"27560","city":"Morrisville","houseNumberOrName":"N\/A","country":"US","stateOrProvince":"NC"},"deliveryAddress":{"street":"5601 Arringdon Park Drive","postalCode":"27560","city":"Morrisville","houseNumberOrName":"N\/A","country":"US","stateOrProvince":"NC"},"amount":{"currency":"USD","value":9461},"reference":"82000432196_K8S","fraudOffset":"0","browserInfo":{"userAgent":"Mozilla\/5.0 (iPhone; CPU iPhone OS 12_5_5 like Mac OS X) AppleWebKit\/605.1.15 (KHTML, like Gecko) Version\/12.1.2 Mobile\/15E148 Safari\/604.1","acceptHeader":"*\/*"},"shopperInteraction":"Ecommerce","paymentMethod":{"type":"applepay","applePayToken":` 

Response:

[2021-11-05 14:26:36] AdyenLoggerTest.INFO: JSON Response to Adyen:{"status":422,"errorCode":"5_001","message":"ApplePay token amount-mismatch","errorType":"validation","pspReference":"861636122396428F"} {"is_exception":false} []

**To Reproduce**
1. Add a product to you cart
2. Use an US shipping address
3. Go to payment and select Apple Pay
4. Impossible to pay my order

**Expected behavior**
When tax is applied on 

**Magento version**
Abode Commerce 2.3.7

**Plugin version**
7.0.1

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOSX
 - Chrome
 - Version 95.0.4638.69 (Official Build) (x86_64)

**Additional context**

**Comment by jonathanribas** [comment]
Maybe fixed by https://github.com/Adyen/adyen-magento2/pull/1099?

**Comment by tnaber** [comment]
Hi @jonathanribas,

Thank you for opening this issue. It indeed looks like #1099, did you already try implementing that PR? Otherwise, I can try it out on my end :)

Cheers,
Titus

**Comment by jonathanribas** [comment]
Hi @tnaber , 

Yes, it fixes the issue.

Sorry for duplicate issue here.
