### ISSUE TITLE
[Storefront] Wrong response format in documentation

### ISSUE THREAD

**Issue by Fifciu** [Adyen/adyen-magento2#1231]
**Describe the bug**
Documentation shows wrong response from `/V1/adyen/orders/:orderId/payment-status` endpoint - [link](https://docs.adyen.com/plugins/magento-2/magento-headless-integration#payment-status). 

The documentation says its an object but in reality it's a stringified object which has to be parsed.

**To Reproduce**
1. Check what's the response when you hit mentioned endpoint.

**Expected behavior**
Documentation shows response as it is.

**Magento version**
2.4.3

**Plugin version**
7.3.0

**Comment by acampos1916** [comment]
Thanks for the heads up @Fifciu, we'll update the docs to reflect that the response is a stringified object.

**Comment by tnaber** [comment]
The docs have been updated!
