### ISSUE TITLE
[PW-5813] Persist 3DS and liabilityShift data in the payment table

### ISSUE THREAD

**Issue by LRotherfield** [Adyen/adyen-magento2#1233]
**Is your feature request related to a problem? Please describe.**
We need to provide liability shift data to a third party integration (I imagine a reasonably common task).  This works for the 3DS2 cc payment flow, but with 3DS1 none of the additional data is persisted to the payment table.  We used to get around this using the 3DSuccess node in additional_information that was persisted in the redirect controller, but that has been removed in 7.x so we now have no way of knowing if liability is shifted for the order.

**Describe the solution you'd like**
We would like the additional data (at least regarding liability shift status) to be persisted on the payment table during the 3DS1 flow, probably in additional_information which is where it is persisted for the 3DS2 flow

**Describe alternatives you've considered**
If there is an alternative to get this data for 3DS1 orders then please let us know.  We would like to avoid additional API requests though.

**Additional context**
Given the above, the ticket to remove the additional information data would actually cause us further problems unless the data removed does not include the liability/3DS information: https://github.com/Adyen/adyen-magento2/issues/1139

**Comment by LRotherfield** [comment]
Currently we are using an observer method to persist this data ourselves as a work around, however given the data is persisted for 3DS2 it seems better that this is done by the Adyen module for consistency.

**Comment by jonathanribas** [comment]
Hi, I disagree adding more and more data to native Adobe Commerce table. Additional Data is not here to put tons of data.
It should be placed on a custom Adyen table with an option to decide if you want to store all data or minimal required data for the module to work correctly.

**Comment by LRotherfield** [comment]
@jonathanribas I am not sure, PayPal Express Checkout is a core module and it stores quite a lot of keys in additional information including `paypal_protection_eligibility ` which in my understanding is very similar to liability shifted.

**Comment by LRotherfield** [comment]
@jonathanribas you said `Additional Data is not here to put tons of data` - according to what standard is it not here for that reason? - since that field was put there by the core team, I figured an appeal to how they use it would be valid.

I agree there is lots that can be removed, and I have no problem with it being a separate table and optional as your above idea.  I just disagree with `additional_information` not being a column that could legitimately hold liabilityShifted information according to its purpose given how those that created it currently use it.

**Comment by jonathanribas** [comment]
@LRotherfield, according to a standard that your payment table can't be the largest one in size in your e-commerce platform.

Actually Adyen is storing kilometric hashes for 3DS stuff, it's just too much.

Our payment table is sizing gigabytes today...

More and more data like this have high infrastructure costs, it shouldn't.

**Comment by LRotherfield** [comment]
@jonathanribas I have not requested large amounts of data to be stored in this ticket.  All I want is the key `"liabilityShift": "false",` which is in the `additional_data` node of the adyen response.  I am happy for most of the data to be removed, e.g I don't need any of the hashed data which is 90% or more of the data in the column.  

We also have control from the adyen admin panel over which keys are returned in the additional_data node, so if you don't want it, I think you could already turn it off.  
<img width="1059" alt="Screen Shot 2021-11-18 at 12 40 26" src="https://user-images.githubusercontent.com/186184/142468184-c403113d-2c86-4bb9-a7ed-f17ba3c754b4.png">

Thoughts?

**Comment by acampos1916** [comment]
Thanks for the thoughts @LRotherfield @jonathanribas, I also think that we can store that data in a separate table, maybe in some kind of key/value structure so that it can be used by more additional data, I think that would solve this and #1139.

@LRotherfield which event is your observer using to save the data?

**Comment by LRotherfield** [comment]
@acampos1916 we are using the `adyen_payment_process_resulturl_after` event

**Comment by tnaber** [comment]
Hi @LRotherfield and @jonathanribas, we are thinking of implementing a standard flow for saving the new additional data when a request for payment details is made (relevant for 3DS1 and 3DS2). This would mean that the additional data for all payment methods will be saved. In order to keep the payment table from growing too large we were thinking of a new table specifically for the additional info. Let me know what you think!

**Comment by LRotherfield** [comment]
@tnaber are you talking specifically about the `additionalData` node in the response JSON that you can configure the contents of from the Adyen admin panel (as shown in the screenshot above)?  i.e could someone select no data to be returned in `additionalData` and thus get no data stored in the table?
What about all the current hashed data that you store on the payment table, will you be dropping that?
If all the above are true, then we could work with that solution, it would require a small change in our code but would resolve our current issue.

**Comment by tnaber** [comment]
Both are true, good to hear!

**Comment by tnaber** [comment]
We have refined our plan and it came down to the following steps:

**Steps:**
1. Create a new helper class `PaymentDetails` to abstract the /details call and the storing of the additional data.
2. Implement the 'PaymentDetails' helper and replace the old flow in
 - PaymentResponseHandler.php.
 - Result.php.
3. Add new table 'adyen_payment_additional_information' with a migration script in UpgradeSchema.php. This table will have a payment_id and a longtext field for serialized additional data.
4. Create entity classes (Collection, ResourceModel, Model, etc.).
5. Create a helper for the `adyen_payment_additional_information` entity to store serialized objects.
6. Implement the `adyen_payment_additional_information` helper where the additional data needs to be saved.
7. Fetch from `adyen_payment_additional_information` using the helper where this data needs to be fetched.

Feel free to share your thoughts!

**Comment by jonathanribas** [comment]
Hi @tnaber, great plan but I have one suggestion:
In my opinion data migration from payment native table to the new custom Adyen's one should not be executed during `setup:upgrade` otherwise site will be down during all the time data is being migrated. In our stores with hundred K orders it could generate a 30 minutes downtime...

**Comment by tnaber** [comment]
Hi @LRotherfield, the request to persist the additional data has been implemented together with a bugfix in #1305 for convenience. This change was also pending in #1265 which aims to implement the plan that was discussed here.
Let's close this issue and move this conversation to the issue by @jonathanribas (#1139) once #1305 has been merged.

Cheers,
Titus
