### ISSUE TITLE
[PW-5812] CAPTURE_FAILED notification sent after order captured

### ISSUE THREAD

**Issue by killoff** [Adyen/adyen-magento2#1234]
**Describe the bug**
After Payment is authorised and order is completed, CAPTURE_FAILED notification sent by Adyen, which has no effect - order remains in status Processing.

**To Reproduce**
Place order with TWINT payment method

**Expected behavior**
Order status should not be Processing until the final decision.

**Magento version**
2.4.1

**Plugin version**
7.3.0

**Screenshots**
![Screenshot 2021-11-10 at 09 57 53](https://user-images.githubusercontent.com/3583507/141081998-40bafb9e-86e9-497a-8a70-311afcab6f82.png)

![Screenshot 2021-11-10 at 09 58 59](https://user-images.githubusercontent.com/3583507/141082174-5273419c-802e-4788-8629-761b82cfbb21.png)

![Screenshot 2021-11-10 at 09 59 30](https://user-images.githubusercontent.com/3583507/141082254-64ee0503-d3d4-43ae-8326-ca279498d199.png)

**Additional context**
So far we have just 2 orders with such issue. 
I don't have an idea, if it's TWINT specific problem when TWINT communicating to Adyen and then Adyen is forced to send CAPTURE_FAILED notification.
However, once the order gets status Processing - it's being considered as fully paid and ready to be dispatched.
Which leads to the delivery of non-paid orders.

**Comment by tnaber** [comment]
Hi @killoff,

Thank you for opening this issue! The problem seems to be in our code not allowing manual capture for Twint. An internal ticket will be created to investigate this and introduce a solution. 

Cheers,
Titus

**Comment by tnaber** [comment]
Hi @killoff,

The fix for this should be introduced by #1255, feel free to have a look!
Let me know if the problem still persists :)

Cheers,
Titus
