### ISSUE TITLE
Can't translate Aria labels

### ISSUE THREAD

**Issue by bchatard** [Adyen/adyen-magento2#1248]
**Describe the bug**
It's seems impossible to translate aria label in Credit Card iframe

**To Reproduce**
As mentioned in documentation, it's possible to translate fields: https://docs.adyen.com/online-payments/web-drop-in/customization#customizable-text

So I try to create a mixin to override the AdyenChekout initialization (since it's seems impossible to do so after initialization).

```js
const translations = {
    [this.getLocale()]: {
        'creditCard.encryptedCardNumber.aria.iframeTitle': $t('Card number'),
        'creditCard.encryptedCardNumber.aria.label': $t('Card number'),
        'creditCard.encryptedExpiryDate.aria.iframeTitle': $t('Expiry date'),
        'creditCard.encryptedExpiryDate.aria.label': $t('Expiry date'),
        'creditCard.encryptedExpiryMonth.aria.iframeTitle': $t('Expiry month'),
        'creditCard.encryptedExpiryMonth.aria.label': $t('Expiry month'),
        'creditCard.encryptedExpiryYear.aria.iframeTitle': $t('Expiry year'),
        'creditCard.encryptedExpiryYear.aria.label': $t('Expiry year'),
        'creditCard.encryptedSecurityCode.aria.iframeTitle': $t('Security code'),
        'creditCard.encryptedSecurityCode.aria.label': $t('Security code'),
        'creditCard.holderName.placeholder': `Jane DOE`,
        'creditCard.numberField.placeholder': `no credit card required ;)`
    }
};

// initialize adyen component for general use
this.checkout = new AdyenCheckout({
    locale: this.getLocale(),
    originKey: this.getOriginKey(),
    environment: this.getCheckoutEnvironment(),
    translations,
})
```

**Expected behavior**
We expect to have a good translation of fields

**Magento version**
2.4.2-p2

**Plugin version**
6.7.1

**Screenshots**
![CleanShot 2021-11-15 at 16 11 28@2x](https://user-images.githubusercontent.com/829364/141806174-8384d768-0785-4bde-abd4-23a9bc018ea1.png)

**Desktop (please complete the following information):**
 - OS: macOS 11.6.1
 - Browser Edge
 - Version 95.0.1020.40

**Additional context**
BTW the default aria-label doesn't match those described here https://github.com/Adyen/adyen-web/blob/master/packages/lib/src/language/locales/en-US.json#L190

**Comment by tnaber** [comment]
Hi @bchatard, 

This is most likely not a problem with the plugin itself, I will contact a different team to find a solution.

Cheers,
Titus

**Comment by tnaber** [comment]
Hi @bchatard,

Version 6.7.1 does not use the package that supports translating the aria labels via the translations object yet (it uses v3.x while it is only supported in >v4). To fix this you can upgrade your plugin to >v7 or have a look at this https://docs.adyen.com/online-payments/migrate-to-web-4-0-0?tab=web_components_3_23_0_or_earlier_2#aria-labels-in-transaltion-fields :)
Let me know if that helps!

Cheers,
Titus

**Comment by bchatard** [comment]
Hi @tnaber 

Thanks for your feedback!
We will investigate on v7 (or v8) update.

Thanks again!
