### ISSUE TITLE
Adyen module cancels orders that may still be received

### ISSUE THREAD

**Issue by zakisaad** [Adyen/adyen-magento2#1250]
**Describe the bug**

Afterpay orders (Australia) may move into an "OfferCancelled" state, and then subsequently get Received at a later stage. The Magento Adyen module will cancel the order when the "OfferCancelled" state comes into effect, and subsequently discard any "Received" events as the order has already been cancelled. Example:

![image](https://user-images.githubusercontent.com/7424248/141874993-8d1de1d4-ff27-45e2-a569-1e167ee6867d.png)

This results in an order that is stuck in an unrecoverable state. This has happened multiple times on our install.

**To Reproduce**
- Offer Afterpay through Magento/Adyen
- Allow customer to go through payment life cycle, using Afterpay
- Wait for Offer to be Cancelled (payment failure/rejected)
  - Order will be cancelled by Adyen M2 module
- Wait for customer to pay on Afterpay directly, resulting in a Received Offer
  - **Order is now in an unrecoverable state**

**Expected behavior**
Not too sure what we can do here since once the Magento order is cancelled, it can't be recovered. Maybe create a new order with the same lines/data, and mark the increment ID with a suffix:

INCREMENTID1234 (cancelled)
INCREMENTID1234-P1 (recreated by Adyen module due to new Received offer state)

Might be further implications of doing this.

**Magento version**
2.3.7-p1

**Plugin version**
7.0.1

**Comment by tnaber** [comment]
Hi @zakisaad,

Thank you for opening this issue. This problem might not be related to the problem. Could you please contact our support team via support@adyen.com and provide the following info:

- Relevant logs
- PSP reference
- A screen recording with the replication of the issue and the browser dev console open
- And possibly the HAR file (https://docs.adyen.com/online-payments/create-har-file)

Cheers,
Titus

**Comment by zakisaad** [comment]
Hi Titus,

I have reached out to support, and they said we will need to work with the Magento 2 module team to resolve this.

**Comment by tnaber** [comment]
Okay, I will discuss internally and get back to you.

**Comment by tnaber** [comment]
Hi @zakisaad,
Sorry for the inconvenience but we have trouble finding your ticket. Could you forward it to me on titus.naber-ghissues@adyen.com? Additionally, it would be helpful if you linked this issue in the support ticket :)

**Comment by tnaber** [comment]
Hi @zakisaad, I never seem to have received the email (I hope nothing went wrong). Did you manage to resolve the issue?

**Comment by tnaber** [comment]
Hi,

I'm closing this. Please feel free to reopen if the issue still persists!

Cheers,
Titus
