### ISSUE TITLE
Disable 3DS2 native (redirect instead)

### ISSUE THREAD

**Issue by BenEddi** [Adyen/adyen-magento2#1260]
Hello 👋 , We'd like to disable 3ds2 native and redirect the user to a secure URL. but we found out that there is no way to do this since you hardcoded this value to "true" un your request's code, Could you check please?
https://github.com/Adyen/adyen-magento2/blob/0f87b78b2343b25248b2965e32f6e9e2d7aa523c/Gateway/Request/CheckoutDataBuilder.php#L196

**Comment by tnaber** [comment]
Hi @BenEddi,

We decided that the plugin should support 3DS2 natively as we would like to encourage this flow. To implement your own redirect you can change it to ``` $requestBody['additionalData']['allow3DS2'] = false; ```. Hope this helps!

Cheers,
Titus

**Comment by BenEddi** [comment]
Hello @tnaber , Thank's for your reply!
