### ISSUE TITLE
Expired credit cards input is shown as valid

### ISSUE THREAD

**Issue by Skullsneeze** [Adyen/adyen-magento2#1275]
**Describe the bug**
Expired credit cards are shown as valid input (limited to an expiration that is 3 months in the past.
Note: When testing the response when trying to proceed will be "REFUSED"

**To Reproduce**
1. Start the checkout process and go payment step
2. Select the Creditcard payment method
3. Fill in correct (test) data, but for the expiration date, fill in a date that is 1 to 3 months in the past
4. The expiration date field is shown as valid

**Expected behavior**
Any Creditcard expiration date that is in the past should not be considered as a valid date

**Magento version**
2.3.6

**Plugin version**
7.2.0

**Screenshots**
Taken on 03-12-2021:
![Card accepted](https://user-images.githubusercontent.com/6089603/144585839-7937e9bc-ed64-42bc-913a-6e648bc5411f.jpg)
![Card too old](https://user-images.githubusercontent.com/6089603/144585854-ac544eb5-157a-4a67-91a3-6ce95377dfd4.jpg)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser Chrome
 - Version 95.0.4638.69 (Official Build) (64-bit)

**Smartphone (please complete the following information):**
N/A

**Additional context**
As mentioned with the screenshots this was tested on 03-12-2021, with an expiration date of 09/21 being valid, and 08/21 being invalid

**Comment by tnaber** [comment]
Hi @Skullsneeze,

Thanks you for opening this issue. However, this is done on purpose. Due to issuers not wanting cards that are just out of date to be refused the expiry can actually be valid up to 3 months in the past (and up to 30 years in the future).

Cheers,
Titus

**Comment by Skullsneeze** [comment]
Thanks for checking @tnaber , never knew this was a thing! You learn something new everyday :smile:
