### ISSUE TITLE
[PW-6021] Forced order status change for Capture notifications

### ISSUE THREAD

**Issue by sheppeybrian** [Adyen/adyen-magento2#1276]
**Describe the bug**
Force change of order status on capture notifications

Due to the capture of payment being one of the last functions in our order flow (we don't charge customer card until after despatch)
we require the order status to remain in its last state/status and not be forced back into a "processing" state / status.

This was possible in 7.2.0 by not allocating a dropdown option in admin setting 
"Order status: payment confirmed" --Please Select--

Since update if a option is not selected it results in a order status update to the default "closed" state in magento

Can you allow for a option of "No Status Change" 

I don't really see the requirement to restrict the order status options to only a Processing state either.  
A manual capture request could be requested during a On Hold or Complete state.

**To Reproduce**
Updated from 7.2.0 - 7.3.2
Suspect this may be a issue related to changes made to resolve [PW-5812]

**Expected behavior**
No change of order status if one is not selected in admin dropdown options

**Magento version**
2.4.3

**Plugin version**
7.3.2

**Comment by tnaber** [comment]
Hi @sheppeybrian,

Thank you for opening this issue and sorry for the slow response. So you would like to have the option of there being no status change when the manual capture webhook notification is handled? Especially since such a status change will cause the order to go back to the processing state which will ultimately interfere with your currently configured workflow. 
Can you verify that we correctly understand your problem?

Cheers,
Titus

**Comment by sheppeybrian** [comment]
Yes this is correct
Reverted back to 7.2.0 and the magento order status stays unchanged on capture as we have not allocated it one in modules configuration.
The new modules results in a closed order state if one is not selected.

A closed or processing state really does not work with our our order flow of not capturing payments until the order ships.

**Comment by tnaber** [comment]
Hi @sheppeybrian, 

We have been looking into this issue on v7.3.2. We could not replicate the behaviour that a flow enters the 'closed' state after processing the capture notification. 

Our states (not custom statuses) had the following flow for these steps: **Order created -> authorisation webhook -> invoice created -> capture notificaiton processed**
- Not setting the "Order status: payment confirmed" results in: _payment_review -> processing -> payment_review -> payment_review_
- Setting "Order status: payment confirmed" to processing results in: _payment_review -> processing -> payment_review -> processing_

As we understand it, you want to have the following flow: _payment_review -> processing -> payment_review -> payment_review_. With the option of having no state change after the capture notification. 

Could you provide me with:
- The flow you are experiencing with the same steps in v7.3.2 (or newer)
- A clear overview of the flow you would like to have (without custom statuses) and the corresponding steps for this flow

Cheers,
Titus

**Comment by sheppeybrian** [comment]
Hello Titus

It's the option to have no state change after a capture notification that
is required.  Or the ability to disable the capture notifications being
received altogether.

(Capture Mode Manual)
We only capture a customer's payment after shipping, therefore a state of
processing or payment_review is not suited to our requirements.
In fact we need to maintain our final custom status without further
change.

I know a lot of companies are now moving to a no capture before a POD
from their shipping carrier is confirmed
This is not going to be helpful if the order state then returns
to processing or payment_review in magento.


Many Thanks


Brian



AstroTex Ltd t/a expressgrass.com
Tribune Drive, Trinity Trading Estate
SITTINGBOURNE
Kent
ME10 2PG Map <https://www.google.com/maps/dir//expressgrass>

*tel*: 0844 855 4704
*direct line*: 01795 385202
*fax*: 01795 385001
*email*:
***@***.*** ***@***.***>**web*: www.expressgrass.com
*Reviews: Google Reviews <https://g.page/expressgrass/review?kd>*

P please don't print this e-mail unless you really need to

This email and its attachments may be confidential and are intended solely
for the use of the individual to whom it is addressed. Any views or
opinions expressed are solely those of the author and do not necessarily
represent those of expressgrass.com. If you are not the intended recipient
of this email and its attachments, you must take no action based upon them,
nor must you copy or show them to anyone. Please contact the sender if you
believe you have received this email in error

**Comment by tnaber** [comment]
Hi @sheppeybrian,

It is no option for us to implement the possibility of disabling the capture notification as this is the only way to verify whether the payment went through. 
Based on [this diagram](https://docs.magento.com/user-guide/sales/order-status-workflow.html) your suggestion would not comply with the suggested flow by Magento. However, if we would get more requests for the implementation of this flow we consider picking this up.
For now, could you provide us with a clear description of your desired flow in both statuses and states (in the same format as my previous comment).

We are curious to how to implement these new flows and are eager to help out if this would benefit multiple merchants!

Cheers,
Titus

**Comment by sheppeybrian** [comment]
Hello Titus

Thank you for your comments. Yes it's fully compatible with standard
magento work flows.
However if you a using delayed capture the new module version is forcing
unwanted state changes.
It's just a heads up that when we updated to your new version, orders that
we have already processed and shipped return to a process state.

This would cause the order to be processed twice.

We treat a Authorised notification as a successful transaction, a Capture
notification as a claim of payment post shipping the customers order.

We will stick to the old version for now as it works perfectly.
Just wanted to make you aware that the changes may lead issues with other
merchants updating customised order flows.
A opt out for all notification state changes should be made possible to
allow for greater flexibility upon a module update.

Brian

**Comment by jordanvector** [comment]
We are also very confused why there is no option to preserve order state during the capture notification, we have very common scenarios during the order flow where there are multiple partial captures as items ship at different times from different locations and need to preserve the order state until the very last capture, with the 8.x version we are forced choose a state change after every payment capture notification or the order ends in a closed state (which I don't believe you can issue a credit memo when an order is closed).

The desired state by myself and others on this thread it seems would be to not require a state change on the payment capture notification and allow magento to change state based on what is invoiced/shipped in the order.

**Comment by sheppeybrian** [comment]
@jordanvector 
We never had the 8.+ version running long enough to experience this before reverting back.  We do at times call for a partial payment capture on some orders and yes this also would result in a forced return to a processing state.
It seems that no consideration has been taken for any merchant using a delayed capture order flow.
Until this is resolved we are stuck with a outdated version that Adyen keep insisting is updated for security reasons...

**Comment by jordanvector** [comment]
Since this was put on hold by the vendor, we will write our own patch to remove this functionality because this new workflow in 8.x is simply not workable for us and our current fulfillment processes.

**Comment by sheppeybrian** [comment]
Be appreciated if you share that patch.  I think that many merchants are going to experience the same issue.  I have however requested the Adyen re-look at the suggested solution of a "No Status Change" option.

**Comment by maxinestewart** [comment]
@jordanvector if you can share the patch that would be amazing - as we are having the exact same issue on our client's site since upgrading to 7.3.5

**Comment by sheppeybrian** [comment]
@acampos1916 @tnaber really should be Adyen working on a resolution for this issue, not a 3rd party developer.   Reported since December 2021 and now with the identified vulnerabilities in 7.3.2 it should be made a priority to address as soon as possible.

**Comment by josh-carter** [comment]
For anyone who needs to know, the reason the orders are moved to Closed stems from the invoice being marked as Pending/Open, in `Adyen\Payment\Gateway\Response\PaymentCaptureDetailsHandler::handle`:

```
...
// The capture request will return a capture-received message, but it doesn't mean the capture has been final
// so the invoice is set to Pending
if ($response["response"] === TransactionCapture::CAPTURE_RECEIVED) {
    $this->setInvoiceToPending($payment);
}
...
``` 

This means that when the Order is saved core State checking logic in `Magento\Sales\Model\ResourceModel\Order\Handler\State::check`:

```
...
    if (!$order->isCanceled() && !$order->canUnhold() && !$order->canInvoice()) {
            if (in_array($currentState, [Order::STATE_PROCESSING, Order::STATE_COMPLETE])
                && !$order->canCreditmemo()
                && !$order->canShip()
            ) {
                $order->setState(Order::STATE_CLOSED)
                    ->setStatus($order->getConfig()->getStateDefaultStatus(Order::STATE_CLOSED));
...
```

The Order is closed because `!$order->canCreditmemo()` will pass due to the Invoice being pending (No amount to refund).

For us it was enough to create a quick patch to comment out the Invoice being set to Pending in the `PaymentCaptureDetailsHandler`, I don't imagine this will cover other peoples situations but feel free to use it:

```
diff --git a/vendor/adyen/module-payment/Gateway/Response/PaymentCaptureDetailsHandler.php b/vendor/adyen/module-payment/Gateway/Response/PaymentCaptureDetailsHandler.php
index b9805da87..324141788 100644
--- a/vendor/adyen/module-payment/Gateway/Response/PaymentCaptureDetailsHandler.php
+++ b/vendor/adyen/module-payment/Gateway/Response/PaymentCaptureDetailsHandler.php
@@ -75,9 +75,9 @@ class PaymentCaptureDetailsHandler implements HandlerInterface

             // The capture request will return a capture-received message, but it doesn't mean the capture has been final
             // so the invoice is set to Pending
-            if ($response["response"] === TransactionCapture::CAPTURE_RECEIVED) {
-                $this->setInvoiceToPending($payment);
-            }
+//            if ($response["response"] === TransactionCapture::CAPTURE_RECEIVED) {
+//                $this->setInvoiceToPending($payment);
+//            }
         }
     }

```

I guess maybe the response from Adyen should differentiate between captured payments an whatever they mean by

> but it doesn't mean the capture has been final

Then if it is final leave the Invoice as Paid, if it's not fair enough leave it as Pending. From what i've seen in the comments on this issue though v8 has changed a lot so i doubt that's the route to go down.

**Comment by tnaber** [comment]
Hi @sheppeybrian @jordanvector @josh-carter @maxinestewart,

As there has been quite some activity here, we will be picking this up. Feel free to leave any suggestion. I will keep you in the loop on development. 

Cheers,
Titus

**Comment by tnaber** [comment]
Hi @sheppeybrian @jordanvector @josh-carter @maxinestewart,
#1390 implements the enhancement as we interpret it. Your feedback would be greatly appreciated!

**Comment by jordanvector** [comment]
@tnaber this looks like the proper workflow here, thank you for all of the work here.
