### ISSUE TITLE
Parsing address incorrect when address contains non-latin characters

### ISSUE THREAD

**Issue by killoff** [Adyen/adyen-magento2#1281]
**Describe the bug**
Adyen Address Helper parses the billing/shipping address in order to get street name and house number.
See `\Adyen\Payment\Helper\Address::getStreetAndHouseNumberFromArray()`

The problem is, that regexp it uses, supports only a-zA-Z alphabet:
```
const STREET_FIRST_REGEX = "/(?<streetName>[a-zA-Z0-9.'\- ]+)\s+(?<houseNumber>\d{1,10}((\s)?\w{1,3})?)$/";
CONST NUMBER_FIRST_REGEX = "/^(?<houseNumber>\d{1,10}((\s)?\w{1,3})?)\s+(?<streetName>[a-zA-Z0-9.'\- ]+)/";

```
As the result, addresses that contain other letters (in our case ä, ü, ß etc. on german website) will be parsed incorrectly.
For example, address "Burgstraße 4" will give street name "e" and house number 4.

The issue is applicable to **all payment methods**.
The issue becomes high prio, when PayPal is being used on checkout, because it supports Shipping address and shopper just can't change the address, that came from the shop, i.e. from Adyen plugin.

So far, we fixed it on our side by rewriting `\Adyen\Payment\Helper\Address` and replacing regular expressions to the following:

```
const STREET_FIRST_REGEX = "/(?<streetName>[a-zA-Z0-9.'\- ]+)\s+(?<houseNumber>\d{1,10}((\s)?\w{1,3})?)$/";CONST NUMBER_FIRST_REGEX = "/^(?<houseNumber>\d{1,10}((\s)?\w{1,3})?)\s+(?<streetName>[a-zA-Z0-9.'\- ]+)/";
```
So, basically we accept any characters till the number met.

If you have a better idea, please share/

**To Reproduce**
1. Go to checkout
2. Enter the address, where street name contains something different than a-zA-Z (non-latin, german letters etc.)
3. Use any adyen payment method
2. Check adyen request json logs how `billingAddress` and `deliveryAddress` are being transferred to Adyen.

**Expected behavior**
`billingAddress.street` and `deliveryAddress.street` transferred correctly

**Actual behavior**
`billingAddress.street` and `deliveryAddress.street` are cut by letters than out of the range a-zA-Z

**Magento version**
2.4.2

**Plugin version**
7.3.0 (but the problem exists in all versions, even in 8.0.0)

**Additional context**
Issue can be fixed by clients by rewriting adyen helper address in local module:

`    <preference for="Adyen\Payment\Helper\Address" type="COMPANY\Adyen\Payment\Helper\Address" />`

```
namespace COMPANY\Adyen\Payment\Helper;

use Magento\Payment\Gateway\Data\AddressAdapterInterface;
use Magento\Sales\Api\Data\OrderAddressInterface;

class Address extends \Adyen\Payment\Helper\Address
{
    // Regex to extract the house number from the street line if needed (e.g. 'Street address 1 A' => '1 A')
    const STREET_FIRST_REGEX = "/(?<streetName>.+)[\s\,]+(?<houseNumber>\d{1,10}((\s)?.+)?)$/";
    CONST NUMBER_FIRST_REGEX = "/^(?<houseNumber>\d{1,10}((\s)?\w{1,3})?)\s+(?<streetName>.+)/";
    ...
}

```

**Comment by tnaber** [comment]
Hi @killoff,

Thank you for opening this issue. This problem has recently been addressed in #1268 (for v8, there are other PRs for other versions).
Can you verify whether this solves your issue?

Cheers,
Titus

**Comment by killoff** [comment]
hi @tnaber 
I did couple of tests and can confirm that this change
https://github.com/Adyen/adyen-magento2/pull/1268#discussion_r761812378
fixes the issue

**Comment by tnaber** [comment]
Thanks for your confirmation!

**Comment by killoff** [comment]
@tnaber one more thing.
I see that STREET_FIRST_REGEX has been fixed:
https://github.com/Adyen/adyen-magento2/blob/develop/Helper/Address.php#L48

but what about NUMBER_FIRST_REGEX?
https://github.com/Adyen/adyen-magento2/blob/develop/Helper/Address.php#L49

we don't mind much about the US addresses, however, I believe street in the second constant should be also replaced with `[:alnum:]`

**Comment by tnaber** [comment]
Good catch, we will be fixing that
