### ISSUE TITLE
[PW-5995] HPP payment methods are shown as "Alternative payment methods" in Customer and Admin order view

### ISSUE THREAD

**Issue by Skullsneeze** [Adyen/adyen-magento2#1282]
**Describe the bug**
After placing an order with an HPP payment menthod (for example iDeal), when viewing the order through the customer account, or through the admin UI, for Payment method instead of displaying "iDeal" we see "Alternative payment methods"

**To Reproduce**
1. Place an order using an HPP paymnet method (eg. iDeal)
2. After placing the order, navigate to your customer account
3. Open the "My Orders" page
4. Open your order, and scroll to the Payment Method section
5. Under payment method, you will see "Alternative Payment methods"

**Expected behavior**
I expect to see the name of the actual payment method used. For example, when paying with iDeal, I would expect to see iDeal under the payment method section

**Magento version**
2.3.6

**Plugin version**
7.2.0

**Screenshots**
![payment method](https://user-images.githubusercontent.com/6089603/145184061-1dda36f8-39e4-409e-b710-a3fcec2da9fa.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser Chrome
 - Version Version 95.0.4638.69 (Official Build) (64-bit)

**Smartphone (please complete the following information):**
N/A

**Additional context**
We noticed this behavior in a previous version, after which our client has been in touch with Adyen. It was mentioned that in the 7.0 and up versions this issue would be resolved.

**Comment by killoff** [comment]
Does not seem to be implemented in v. 7+
We implemented it on our side based on data in `sales_order_payment` table.
See `sales_order_payment.cc_type` and `sales_order_payment.additional_information.brand_code`

**Comment by tnaber** [comment]
Hi @Skullsneeze,

Thank you for opening this issue. This would indeed be a valuable improvement. We will be opening an internal ticket to investigate introducing this functionality.
@killoff feel free to open a PR and contribute your own solution :)

Cheers,
Titus

**Comment by tnaber** [comment]
Hi @Skullsneeze,

I opened a PR with a solution, feel free to check it out!

Cheers,
Titus

**Comment by Skullsneeze** [comment]
Hi @tnaber , sorry for taking a while to get back to you. I've checked the implemented solution, but I'm not sure this is the final fix yet. It seems the brand code that is displayed is a "machine readable" name, so for example, using Klarna - Pay Now will show klarna_paynow (see attached example).

![HPP method](https://user-images.githubusercontent.com/6089603/149351180-5d776b19-8753-44be-b5fb-91db3fb294f7.png)

Is there a way to get the same string that is shown during the checkout? Perhaps it can be stored in the additional payment data during the checkout process?
