### ISSUE TITLE
[PW-6184] Shipping address incorrect in PayPal

### ISSUE THREAD

**Issue by killoff** [Adyen/adyen-magento2#1291]
**Describe the bug**
When shipping and billing addresses are different - shipping address displayed incorrectly in Paypal.

**To Reproduce**
1. Go to checkout, enter different billing and shipping address
2. Select Paypal payment method
3. Check Shipping address passed to paypal

**Expected behavior**
Shipping address entered on checkout should be the same as on Paypal popup

**Actual behavior**
On Paypal popup: Firstname/Lastname are taken from Billing address, Street and city are correctly taken from Shipping address

**Magento version**
[e.g. 2.4.2]

**Plugin version**
[e.g. 8.0.0]

**Screenshots**
![Screenshot 2021-12-15 at 14 53 30](https://user-images.githubusercontent.com/3583507/146201702-1f3262ac-ef23-4225-9e62-827d824e2a79.png)
![Screenshot 2021-12-15 at 14 53 41](https://user-images.githubusercontent.com/3583507/146201712-cf1a4eed-e322-4124-8a96-510b293c049d.png)
![Screenshot 2021-12-15 at 14 56 48](https://user-images.githubusercontent.com/3583507/146201724-24eadd0f-977f-4f25-9ddb-5406b3d917a7.png)

**Comment by killoff** [comment]
I am not sure if it's possible to fix and if it is expected behavior. 
Because from adyen logs, Adyen does not store Firstname/Lastname  in the addresses. So it just takes shopperName and pass it to Paypal I guess

```
"shopperName":{"firstName":"Billing Firstname","lastName":"Billing Lastname"}
"billingAddress":{"street":"Billing street","postalCode":"8002","city":"Zurich","houseNumberOrName":"2","country":"CH"}
"deliveryAddress":{"street":"Shipping street","postalCode":"8000","city":"Uster","houseNumberOrName":"1","country":"CH"},
```

**Comment by tnaber** [comment]
Hi @killoff,

Thank you for opening this issue and clearly displaying the problem. To further investigate we were wondering whether this is a headless integration or not?

Cheers,
Titus

**Comment by tnaber** [comment]
Hi @killoff,

You were right in your assumption, the PayPal SDK gets its information from the payment request. Currently, it is not possible for us to pass multiple names in this payment request. Note that this does not impact Magento where the 'shipping name' is still available. 

Thank you for opening this issue, I am closing it as this is outside the scope of this plugin.

Cheers,
Titus
