### ISSUE TITLE
Payment Methods not shown in Magento orders grid for Alternative Payment Methods

### ISSUE THREAD

**Issue by ValeriaDel** [Adyen/adyen-magento2#1299]
When orders are placed with either PayPal, Klarna, Apple or Google Pay for Adyen they all fall under "Alternative Payment Methods". Understand Adyen is only interested at differentiating cards and other payments, but from an admin prospective it would be really beneficial to see the actual payment method in the Magento order grid, in order to identify immediately if a certain payment method is having an issue onsite.

Please can we add a split of actual payment methods in Magento order grid? They can still say "Alternative payment method" but maybe add a mention of the actual one i.e. "Alternative payment method - PayPal" etc.

**Comment by tnaber** [comment]
Hi @ValeriaDel,

Thank you for this proposal. I'll open an internal ticket to further investigate this enhancement.
I think you are aware, but for now the specific payment method can be found under the payment information details in the order view :)

Cheers,
Titus

**Comment by ebaschiera** [comment]
This has been discussed some time ago: https://github.com/Adyen/adyen-magento2/issues/180
Just for reference.

**Comment by AGo444** [comment]
I know the specific payment method can be found under the payment information in the order view but when you have klarna  set to manual capture it would be very convenient when orders can be filtered on payment method Klarna.

**Comment by Suzell** [comment]
Closing this as duplicate with #1791
