### ISSUE TITLE
Wrong link to documentation

### ISSUE THREAD

**Issue by pivulic** [Adyen/adyen-magento2#13]
### Problem
Both [README.md](https://github.com/Adyen/adyen-magento2/blame/develop/README.md#L8) and [dyen_getting_started.xml](https://github.com/Adyen/adyen-magento2/blob/develop/etc/adminhtml/system/adyen_getting_started.xml#L31) links to a 404: https://docs.adyen.com/manuals/magento2-integration

### Expected result
They should not link to a 404 page, i.e: https://docs.adyen.com/manuals/magento/magento2-integration

**Comment by rikterbeek** [comment]
Hi Pablo,

You are fast ;) We have yesterday combined the two manuals in a section magento. I will update the links and will be in the new release that will be done this morning.

Regards,
Rik
Adyen

**Comment by pivulic** [comment]
GR8 :+1:

**Comment by rikterbeek** [comment]
Fixed here:
https://github.com/Adyen/adyen-magento2/commit/339fd73b08618fbe15ff82978bffbd761d55887e
https://github.com/Adyen/adyen-magento2/commit/275eab86c6c3c1f02d2e40736eea05dd8c01ee51
