### ISSUE TITLE
Documentation is not updated for version 8.0.0

### ISSUE THREAD

**Issue by Fifciu** [Adyen/adyen-magento2#1310]
**Describe the bug**
Documentation is not updated for version 8.0.0

**To Reproduce**
1. Open https://docs.adyen.com/plugins/magento-2/magento-headless-integration#payment-status and compare it with breaking changes from v8.0.0: https://github.com/Adyen/adyen-magento2/releases/tag/8.0.0

**Expected behavior**
Documentation is up to date

**Plugin version**
8.0.0

**Comment by tnaber** [comment]
Hi @Fifciu,

Thank you for pointing out this mistake. We will make sure the documentation gets corrected :)

Cheers,
Titus

**Comment by tnaber** [comment]
Hi @Fifciu,

It is updated now! I'm closing this.

Cheers,
Titus
