### ISSUE TITLE
CSP blocking webhooks communication

### ISSUE THREAD

**Issue by rafaelstz** [Adyen/adyen-magento2#1320]
**Describe the bug**
During the tests, the communication between Magento and Adyen webhooks wasn't validated. The payment was working fine.

**To Reproduce**
Steps to reproduce the behaviour:

1. Configure the module
2. Access Adyen panel
3. Validate webhooks communication via Adyen panel
4. See the errors

**Expected behavior**
Validation works

**Magento version**
2.3.7

**Plugin version**
8.0.0

**Additional context**
We had to add a CSP skip in a custom code to make it work, as you can see below.

```php
<?php

namespace CustomModule\Csp\Plugin;

use Magento\Csp\Api\Data\PolicyInterface;
use Magento\Framework\App\Response\HttpInterface as HttpResponse;

class AdyenPlugin {

    /**
     * @param $subject
     * @param callable $proceed
     * @param PolicyInterface $policy
     * @param HttpResponse $response
     */

    public function aroundRender($subject, callable $proceed, PolicyInterface $policy = null, HttpResponse $response = null)

    {

        $url = $this->getUrlInterface();

        if (strpos($url->getCurrentUrl(), 'adyen/process') !== false) {
            return;
        }

        $result = $proceed($policy, $response);
        return $result;
    }

}
```

**Comment by tnaber** [comment]
Hi @rafaelstz,

Did you manage to find the corresponding errors?

Cheers,
Titus
