### ISSUE TITLE
MobilePay in native module

### ISSUE THREAD

**Issue by dronerdk** [Adyen/adyen-magento2#1324]
Adyen offer the payment method MobilePay:
https://www.adyen.com/payment-methods/mobilepay

But in this native Magento 2 module the method is not present.

Will you consider to create MobilePay as a payment method for Adyen Magento 2?

**Comment by Morerice** [comment]
Hi @dronerdk,

Thanks for opening this issue. MobilePay is available and operational on our Magento 2 module. Could you please reach out to your Adyen contact and verify if MobilePay is enabled on your Adyen account? Alternatively you can also reach out to our support team on support@adyen.com.

Thanks,
Jean
Adyen
