### ISSUE TITLE
Uncaught TypeError: base is not a constructor

### ISSUE THREAD

**Issue by richiardc** [Adyen/adyen-magento2#1335]
**Describe the bug**
Js error during checkout loading.
Probably the bug is on js validation mixin setted in vendor/adyen/module-payment/view/frontend/requirejs-config.js -> vendor/adyen/module-payment/view/frontend/web/js/view/checkout/validator-mixin.js where validator is used not correctly.

**To Reproduce**
1. Go to checkout
2. Looking for loading
3. Inspect browser console
4. See error: 
Uncaught TypeError: base is not a constructor
    at Function.$.widget (widget.js:75:25)
    at validation-mixin.js:8:11
    at 532e5e5b22ace8cae498d7cc683cd5a6.js:2154:22
    at Array.forEach (<anonymous>)
    at applyMixins (532e5e5b22ace8cae498d7cc683cd5a6.js:2153:16)
    at 532e5e5b22ace8cae498d7cc683cd5a6.js:2173:36
    at Object.execCb (532e5e5b22ace8cae498d7cc683cd5a6.js:1650:33)
    at Object.context.execCb (resolver.js:145:31)
    at Module.check (532e5e5b22ace8cae498d7cc683cd5a6.js:866:51)
    at Module.<anonymous> (532e5e5b22ace8cae498d7cc683cd5a6.js:1113:34)

**Magento version**
2.3.4

**Plugin version**
from Magento composer.json "adyen/module-payment": "^8.1" -> 8.1.1 in module composer.json

**Comment by dronerdk** [comment]
We have the same error on:
Catalog view page
Catalog list page

This error is only present in version 8.1.1

widget.js:75 
Uncaught TypeError: base is not a constructor
    at Function.$.widget (widget.js:75:25)
    at validation-mixin.js:7:11
    at mixins.js:105:22
    at Array.forEach (<anonymous>)
    at applyMixins (mixins.js:104:16)
    at mixins.js:129:36
    at Object.execCb (require.js:1650:33)
    at Module.check (require.js:866:51)
    at Module.<anonymous> (require.js:1113:34)
    at require.js:132:23

**Comment by apomili** [comment]
The mixin not return the original object, here the fix

define(['jquery'], function($) {
    'use strict';

    return function(target) {
        $.validator.addMethod(
            "validate-ssn-br",
            function(value, element) {
                // The format is 000.000.000-00
                return /^([-\.\s]?(\d{3})){3}[-\.\s]?(\d{2})$/.test(value);
            },
            $.mage.__('Please enter a valid brazilian social security number (Ex: 123.456.789-10).')
        )

        return target;
    }
});

**Comment by richiardc** [comment]
@apomili it seems that fix the issue. Thanks! Waiting for the merge of the fix on next release.

**Comment by Morerice** [comment]
Hi guys,

Thanks for reporting this issue and thanks to @apomili for providing a possible solution. Would it be possible for you to open a PR with this solution, so that we can verify it and then merge it?

Regards,
Jean
Adyen

**Comment by tnaber** [comment]
Thank your for opening the PR, it has been merged :)
