### ISSUE TITLE
Show holder name field for card payment methods visible

### ISSUE THREAD

**Issue by dronerdk** [Adyen/adyen-magento2#1336]
**Describe the bug**
If we set the "Show holder name field for card payment methods" to "No" in checkout experince configuration the name field in checkout will still be visible.

**To Reproduce**
1. set Show holder name field for card payment methods to No
2. Cache clean
3. Put product in cart and go to checkout and select credit card payment
4. Name field still visible

**Expected behavior**
The name field should not be visible if configuration is set to no

**Magento version**
2.4.3

**Plugin version**
8.1.0 + 8.1.1
![Skærmbillede 2022-01-27 kl  13 46 15](https://user-images.githubusercontent.com/15999222/151362066-2f295b0b-0542-49f1-bbcd-d3cc4aebab17.png)
![Skærmbillede 2022-01-27 kl  13 44 22](https://user-images.githubusercontent.com/15999222/151362071-0c69b7d1-4570-4d9e-a622-4d2f89f46ab6.png)

**Comment by Morerice** [comment]
Hi @dronerdk,

Thanks for opening this issue and providing clear steps to replicate the problem. We will investigate this and come back to you with any updates.

Regards,
Jean
Adyen

**Comment by Morerice** [comment]
Hi @dronerdk,

We have created a PR to fix this issue. It has already been tested on our setup, but feel free if you want to carry out some additional tests on your end.

Regards,
Jean
Adyen
