### ISSUE TITLE
[PW-6292/PW-6484] - Incorrect/inconsistent behavior in iDeal payments

### ISSUE THREAD

**Issue by niekv** [Adyen/adyen-magento2#1341]
**Describe the bug**

1.  A general error message is thrown when a frontend user does not select a bank in the iDeal payment method, but a specific error message to inform the user properly would be expected. The problem is very specific, so it would be advisable to show a specific error message. Currently the frontend user is advised to use another payment method, while they only need to choose a bank to proceed with the iDeal method. E.g. "Please select your bank before proceeding" 

![CleanShot 2022-02-03 at 09 21 39](https://user-images.githubusercontent.com/19262684/152306387-912b7a7a-249f-4280-bd29-852b459ca914.png)

Because of this current general error message users are switching to other payment methods, but that's undesirable. 

2. Bank is a required field in this payment method. But the payment button is available, even though the required option has not been selected. This is inconsistent behavior in comparison with Creditcard for example. In the case of Credit Card payments the proceed button is greyed out until all required fields are filled in. 

It would be advisable to also implement that behavior in the iDeal payment method to keep the user experience consistent. 

![CleanShot 2022-02-03 at 09 28 37](https://user-images.githubusercontent.com/19262684/152308790-809f600b-5508-4a6a-ba93-ecf7e7a7053c.png)

3. In some cases the order is added to Magento, before the required bank field has been chosen. The user gets the general message like described, and the order is added without a order status to Magento. 

**To Reproduce**
1. Add a product to the cart
2. Go to checkout step 1 (native Magento). Fill in dummy details, use shipping country "Netherlands". 
3. Select iDeal without a bank in step 2. 
4. Proceed with the order. 

**Expected behavior**
- A specific error message is thrown, e.g. "Please select a bank before proceeding"

**Magento version**
2.4.3-p1

**Plugin version**
8.1.1

**Desktop (please complete the following information):**
 - macOS: 
 - Firefox 96.0.3

**Comment by Morerice** [comment]
Hi @niekv,

Thanks for opening this issue. We have opened an internal ticket regarding this issue. Basically we will first identify which error code messages we should expose to the end user and then implement the changes regarding those error codes. In the meantime if you have any other input regarding this, feel free to keep in touch.

Best regards,
Jean
Adyen

**Comment by Morerice** [comment]
Fix to validate empty bank account was released in v8.2.2.
