### ISSUE TITLE
[PW-5275] Quote cleared after cancelling 'Payconiq by Bancontact' order

### ISSUE THREAD

**Issue by Tjitse-E** [Adyen/adyen-magento2#1346]
**To Reproduce**
1. Add a product to your cart
2. Go to the checkout 'Payconiq by Bancontact'
3. A Payconiq popup will open:
![CleanShot 2022-02-03 at 16 54 14](https://user-images.githubusercontent.com/14849044/152378550-7f9d87ba-162a-42dd-a559-8e0d5e10c772.png)
4. Close the Payconiq iframe

**Expected behavior**
The quote will persist and the customer can choose another payment method

**Actual behaviour**
The quote is cleared and an error will appear when choosing another payment method:
![CleanShot 2022-02-03 at 16 55 59](https://user-images.githubusercontent.com/14849044/152378857-cdd43225-332f-465f-8afd-a2a411bc17de.png)

**Magento version**
Magento 2.4.3-p1

**Plugin version**
adyen/module-payment 8.1.1

**Additional contect**
I tried enabling the 'clone quote on failed payment' setting, but this makes no difference.
![CleanShot 2022-02-03 at 17 02 23](https://user-images.githubusercontent.com/14849044/152380115-ba81a0fc-73a4-4aed-82bf-ac48514135f0.png)

**Comment by tnaber** [comment]
Hi @Tjitse-E,

Thank you for opening this issue. This is a known issue and is in our backlog. We will pick this up shortly.

Cheers,
Titus

**Comment by niekv** [comment]
@tnaber We could also reproduct this with failed creditcard payment. FYI.
