### ISSUE TITLE
[PW-6624] Giftcard payment methods cause an error due to lacking component object

### ISSUE THREAD

**Issue by LukasDeRuiter** [Adyen/adyen-magento2#1362]
**Describe the bug**

The following error is showing up in the browser console in magento 2 after updating the adyen-payment module to 8.1.1:

![adyenError](https://user-images.githubusercontent.com/79844540/154079244-f9b68e62-8b3e-4fb5-8d61-dee526bcd03f.jpg)

As of now, it seems to occur whenever a giftcard payment method is rendered on the checkout page. Upon further inspection I have concluded that this might be caused by the payment methods not having a component object on them, as both the result objects and the self.checkoutComponent objects lack any indication of these payment methods having components, which causes the error to be thrown.

**To Reproduce**
1. Go to the checkout page while having at least one giftcard payment method available.
2.  Allow the payment methods to be rendered.
3. The error should be thrown once per giftcard payment method.

**Magento version**
Version 2.4.3

**Plugin version**
Version 8.1.1

**Additional context**
As of now, the error does not cause any major issues, although for consistency sake it might be best practice to have a look at this. As of now, it seems the giftcards are missing a .component, which might cause further issues down the line.

**Comment by tnaber** [comment]
Hi @LukasDeRuiter,

Thank you for opening this issue. We have verified the problem on our end and agree that it should be resolved. However, the gift card flow is currently under review and scheduled to undergo a large change (which should also resolve this problem). As the issue does not cause any major issues we will not add it to our backlog for now.

Cheers,
Titus
