### ISSUE TITLE
Impossible to use custom translations

### ISSUE THREAD

**Issue by mushketer888** [Adyen/adyen-magento2#1370]
**Describe the bug**
Custom translations are not working
Maybe I'm doing something wrong?

**To Reproduce**
1. Create mixin with custom translation:
this.checkout = new AdyenCheckout({
                    locale: adyenConfiguration.getLocale(),
                    originKey: adyenConfiguration.getClientKey(),
                    environment: adyenConfiguration.getCheckoutEnvironment(),
                    paymentMethodsResponse: adyenPaymentService.getPaymentMethods().paymentMethodsResponse,
                    onAdditionalDetails: this.handleOnAdditionalDetails.bind(this),
                    translations: {
                        en_GB: {
                            'creditCard.cvcField.title': 'Security Number *',
                            'creditCard.holderName.placeholder': '',
                            'creditCard.numberField.placeholder': '',
                            'creditCard.cvcField.placeholder': '',
                            'holderName': 'Name on Card *',
                            'creditCard.numberField.title': 'Card Number *',
                            'creditCard.expiryDateField.title': 'Expiry Date *'
                        },
                        fr_FR: {
                            'creditCard.cvcField.title': 'Cryptogramme *',
                            'creditCard.holderName.placeholder': '',
                            'creditCard.numberField.placeholder': '',
                            'creditCard.cvcField.placeholder': '',
                            'holderName': 'Nom sur la carte *',
                            'creditCard.expiryDateField.title': 'Date dexpiration *',
                            'creditCard.numberField.title': 'Numéro de carte de crédit *'
                        }
                    },
                    allowAddedLocales: true
                });
Tried 
  'creditCard.cvcField.title':{
  'en_GB': 'Security Number *'
  } too

**Expected behavior**
CC fields being translated

**Magento version**
2.4.2-2.4.3

**Plugin version**
8.1.1

**Screenshots**
![2022-02-1715:49:45](https://user-images.githubusercontent.com/2189038/154495046-5ac2e1ee-211f-4f69-a40e-1cd48d728859.png)

**Comment by tnaber** [comment]
Hi @mushketer888,

This is most likely not a problem with the plugin itself. Looking at [these docs](https://docs.adyen.com/online-payments/migrate-to-web-4-0-0?tab=web_components_4_0_0_or_later_1#aria-labels-in-transaltion-fields), it seems like adding the '.aria' field might resolve this?

Cheers,
Titus

**Comment by mushketer888** [comment]
Thanks for your feedback!
But still can't get translations working

**Comment by tnaber** [comment]
Hi @mushketer888,

I would like to ask you to contact our support via your CA or support@adyen.com, please provide your merchant account and a link to this issue.

Cheers,
Titus
