### ISSUE TITLE
Virtuel orders and billing address

### ISSUE THREAD

**Issue by dronerdk** [Adyen/adyen-magento2#1372]
In our store we also sell 100% virtuel orders.
For that we dont need billing address in checkout, but Adyen payment requires billing informations for processing the order in checkout.
Could you make it as an option not make it mandatory to provide billing informations when processing virtuelt orders in checkout with Adyen payment?

**Comment by tnaber** [comment]
Hi @dronerdk,

In #1258 this problem has been addressed, does this also fix your issue?

Cheers,
Titus

**Comment by tnaber** [comment]
Hi @dronerdk,

From what I understand you would like to allow customers to pay with entering a shipping address and their full name. Although these details are not mandatory to be sent to the Adyen platform, they are required by some local payment methods and highly valued in the authentication process of card payments.
Concluding, you can implement this feature locally and this will work for some methods. However, we will not be implementing this feature for the full plugin.

Cheers,
Titus

**Comment by dronerdk** [comment]
No that is not what the features is about.

In Magento 2 if you try to checkout a 100% virtuel order, you should not enter shipping address. And that is good and should not be changed.
However the billing address informations is required by the payment methods. In Adyen Payment you requiere all informations for a customer as billing information; mail, name, address, phone.
My request is  if it is possbile for Adyen payment not to make all the billing informations mandatory so the customers with a 100% virtuel order only have to input mail, and not the other informations.

**Comment by tnaber** [comment]
I made a typo in my previous comment, I meant to say 'without entering the details'. We would rather not implement this feature as the data is valuable for authentication and required for some payment methods.

Cheers,
Titus

**Comment by dronerdk** [comment]
ok Titus. No problem.
But it could be nice if you could implement the feature for like CC payment, if the payment still would be complient.
Could make really fast virtuel order checkout with only req of mail.

**Comment by Morerice** [comment]
Hi @dronerdk,

Apologies for our delay on this issue. Unfortunately it not possible to know if the payment will/will not require such information before actually attempting it. It's not up to Adyen to identify if a payment will be compliant, but it's the issuing bank that ultimately informs us what authentication is required, after the payment is attempted.

I will close this issue for now as we don't have any plans to setup this functionality. If at any point our plans change, this issue will be re-opened along with some further information. Still, thanks for bringing this suggestion up.

Regards,
Jean
Adyen
