### ISSUE TITLE
[PW-6306] Klarna Payment method throws an error when the storeview currency isn't the same as the base currency.

### ISSUE THREAD

**Issue by DennisVendic** [Adyen/adyen-magento2#1377]
**Describe the bug**
When placing an order with Klarna in an different currency (displayed currency) then the base currency,  an error is thrown and the user can't proceed with the order. 

**Prerequisites**
- U need to have a Magento 2 store with at least two storeviews
- The base currency of the installation is set to Euro
- The displayed currency of one of the storeviews is set to CHF
- The Adyen charged currency for both storeviews is set to Euro

**To Reproduce**
1. Navigate to the storeview set to CHF
2. Add a product to the cart
3. Go to the checkout step 1 and fill in dummy details
4. Proceed the checkout step 2 (payment methods)
5. Select Klarna payment method "Sofort bezahlen mit Klarna." 
6. Try to finalize the order

**Expected behavior**
The order should be added to Magento 2 and the client should be able to proceed with the payment.

**Actual Result**
A generic error is thrown "Error with payment method please select different payment method." and the user isn't able to proceed with the payment. 

Error added to the logfile: `[2022-02-22 10:22:59] .CRITICAL: Placing an order with quote_id SXqeA6f1qBAZDKvr6WSa7SQcjGtswX9G is failed: Error with payment method please select different payment method. [] []`

**Magento version**
2.4.3-p1

**Plugin version**
8.1.1

**Screenshots**
![CleanShot 2022-02-22 at 11 23 01](https://user-images.githubusercontent.com/100120970/155112992-93bfa21a-9f84-42cb-9dec-128f2e9e6de1.png)

**Desktop (please complete the following information):**
 - MAC OS, Google Chrome 98.0.475.80

**Comment by tnaber** [comment]
Hi @DennisVendic,

Thank your for opening this ticket. We are experiencing multiple issues in this area and will be opening an internal investigation.

Cheers,
Titus

**Comment by DennisVendic** [comment]
@tnaber Do you have any update for us? We still aren't able to proceed payments.

**Comment by tnaber** [comment]
Hi @DennisVendic,

 #1388 should resolve this issue and is currently up for review. When this is merged it will be added in the next release.
 If you would like to use the solution earlier you can temporarily add the PR to your own codebase, copy the lines of code over or replace your version of the `Helper/ChargedCurrency.php` with the one in the PR.

Cheers,
Titus
