### ISSUE TITLE
Uncaught TypeError: base is not a constructor in module version 8.1.1

### ISSUE THREAD

**Issue by matmarchant** [Adyen/adyen-magento2#1386]
**Describe the bug**
Magento2 checkout is broken in version 8.1.1, the javascript console shows Uncaught TypeError: base is not a constructor
at Function $.widget (widget.js:75:25)

**To Reproduce**
1. Go to checkout
2. Loading spinner does not disappear
3. Inspect JS console

**Expected behavior**
The checkout should load and no errors displayed

**Magento version**
Commerce Edition 2.4.3p1

**Plugin version**
8.1.1

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser: Chrome
 - Version: 98.0.4758.102

**Additional context**
The issue is traced to the new JS mixin: view/frontend/web/js/view/checkout/validator-mixin.js
Downgrading to 8.1.0 resolves the issue

**Comment by Morerice** [comment]
Hi @Thokoop,

This issue is a duplicate of https://github.com/Adyen/adyen-magento2/issues/1335, which was solved by https://github.com/Adyen/adyen-magento2/pull/1339. This PR will be out on the next release (8.2.0).

Thanks,
Jean
Adyen
