### ISSUE TITLE
[PW-6442] Restore cart does not work

### ISSUE THREAD

**Issue by evgv** [Adyen/adyen-magento2#1392]
Making your own contribution is easy, encouraged and greatly appreciated! We will put effort into reviewing and merging your PR quickly. For more info, please refer to the contribution guidelines: https://github.com/Adyen/adyen-magento2/blob/develop/CONTRIBUTING.md

**Describe the bug**
Call the restoreQuote() in Adyen\Payment\Model\Api\AdyenPaymentDetails always return `false` in case of refused or cancelled payment, because it uses sessions but GraphQL does't it uses the token auth instead off cookies.

**To Reproduce**
1. Go to checkout with Adyen Drop in for example, choose PP or Klarna or any HPP method
2. Click on `Place Order` and go to the payment service page, then click 'Zuruk' for Klarna or `Back` for PP and you will return to the redirect URL (you Magento checkout page)
3. Then call the `adyenPaymentDetails` GraphQL query to check the payment status
4. It will return you 500 error but it's ok, let it be, but also before the throwing the error it should restore the quote from the last session order id but there is no any last order id in session because GraphQL doesn't use it.

**Expected behavior**
After return to the Magento checkout page and run the `adyenPaymentDetails` query, quote should be restored from the last order id that you have in query parameters.

**Magento version**
2.4.3-p1

**Plugin version**
8.2.0 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04 LTS
 - Browser Chrome

**Comment by tnaber** [comment]
Hi @evgv,

Thank you for opening this issue. We replicated the issue and are currently looking into alternative approaches for headless integrations.

Cheers,
Titus

**Comment by evgv** [comment]
Hi @tnaber 

Thanks for your reply!

As a suggestion I could say about to no to kill quote/cart for redirect payments (GraphQL) before redirect and do it only after if everything is ok, in other cases customer could stay with his cart and goods and still be able to make new payment try and place the order.

We had the similar approach with 6.x Adyen plugin version.

Regards,
Eugene
