### ISSUE TITLE
[PW-6480] 3DS modal on mobile partially obscured.

### ISSUE THREAD

**Issue by timjanssen95** [Adyen/adyen-magento2#1412]
**Describe the bug**
When visiting the checkout page and inputting test credentials for a credit card payment, the 3DS modal is opened but the width of the iframe within is set to 390px making it too wide for most mobile screens (especially when you account for the modals left property and padding). This in turn obscures parts of the password input field, OK button, and the complete 'What's this?' help dialog.

**To Reproduce**
Prerequisites: 3DS is enabled for your environment.

1. Go to the final page of the checkout
2. Input your cc credentials.
3. Click on place order
4. 3DS modal pops up

**Expected behavior**
The content of the iframe is the exact width of what is available on the users device. All CTA's are clickable and visible without the need of horizontal scrolling.

**Magento version**
2.4.2-p1

**Plugin version**
7.3.6

**Screenshots**
![image](https://user-images.githubusercontent.com/91065237/159885362-89dce897-8ba4-49a8-9979-d35ffc5cfd0f.png)

**Desktop:**
- Problem does not occur on desktop or larger screen devices.

**Smartphone:**
- Any smartphone in portrait mode.

**Comment by tnaber** [comment]
Hi @timjanssen95,

Thank you for opening this opening this issue! We have verified it on our end and will be changing the styling.

Cheers,
Titus

**Comment by timjanssen95** [comment]
Hi Titus! Thank you for looking into this!
