### ISSUE TITLE
Result controller not headless ready

### ISSUE THREAD

**Issue by marcoboom** [Adyen/adyen-magento2#1416]
**Describe the bug**
The /process/result controller depends on \Magento\Checkout\Model\Session and \Magento\Customer\Model\Session. This will only work on a session based frontend like native Magento and not for full headless frontends where you do no not use the cookie PHPSESSID.

**To Reproduce**
Use the Rest API or GraphQl to place an order and choose a HPP payment method wich results in a RedirectShopper action. Afther handling the payment you will be redirected to your shop url  /process/result. This controller will redirect you to the magento cart url /checkout/cart.

**Expected behavior**
The controller depends on the feedback given by Adyen within the URL to find the specific Magento quote / order.

**Comment by Morerice** [comment]
Hi @marcoboom

Thanks for opening this issue. We are currently looking for an alternative. Would you agree that this issue is identical to #1392, the only difference being that the connection on that issue was trough graphQl, whereas yours is trough traditional rest api?

Regards,
Jean
Adyen

**Comment by marcoboom** [comment]
Hi @Morerice , my issue concerns GraphQL.
