### ISSUE TITLE
[MBWay] Invalid phone number NO PAYLOAD

### ISSUE THREAD

**Issue by jonathanribas** [Adyen/adyen-magento2#1438]
Making your own contribution is easy, encouraged and greatly appreciated! We will put effort into reviewing and merging your PR quickly. For more info, please refer to the contribution guidelines: https://github.com/Adyen/adyen-magento2/blob/develop/CONTRIBUTING.md

**Describe the bug**

**To Reproduce**
1. Add a product to your cart
2. Go to payment step
3. Select MBWay
4. Insert a fake Portuguese phone number like `9 2 3 4 5 6 7 8` (with spaces)

**Request:**

`[INFO] JSON Request to Adyen:{"merchantAccount":"CaudalieCOM","shopperReference":"52000146410_K8Sad9ce20e-f83c-45f6-be42-094959360a88","shopperEmail":"regrgegegeg@gmail.com","telephoneNumber":"+351923456789","shopperName":{"firstName":"Hello","lastName":"World"},"countryCode":"PT","shopperLocale":"pt_PT","shopperIP":"194.177.44.186","billingAddress":{"street":"Avenida Lus\u00edada","postalCode":"1500-650","city":"Lisboa","houseNumberOrName":"100","country":"PT","stateOrProvince":"PT-11"},"deliveryAddress":{"street":"Avenida Lus\u00edada","postalCode":"1500-650","city":"Lisboa","houseNumberOrName":"100","country":"PT","stateOrProvince":"PT-11"},"amount":{"currency":"EUR","value":8890},"reference":"52000146410_K8S","fraudOffset":"0","browserInfo":{"userAgent":"Mozilla\/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/100.0.4896.60 Safari\/537.36","acceptHeader":"*\/*"},"storePaymentMethod":false,"shopperInteraction":"Ecommerce","paymentMethod":{"type":"mbway","telephoneNumber":"9 2 3 4 5 6 7 8"},"riskData":{"clientData":"eyJ2ZXJzaW9uIjoiMS4wLjAiLCJkZXZpY2VGaW5nZXJwcmludCI6ImRmLXRpbWVkT3V0In0="},"additionalData":{"allow3DS2":true},"returnUrl":"https:\/\/pt.integration.eu.k8s.caudalie-dev.com\/adyen\/process\/result?merchantReference=52000146410_K8S","channel":"web","origin":"https:\/\/pt.integration.eu.k8s.caudalie-dev.com\/","applicationInfo":{"adyenLibrary":{"name":"adyen-php-api-library","version":"11.0.0"},"externalPlatform":{"version":"2.4.3-p1","name":"Magento"},"merchantApplication":{"version":"8.1.1","name":"adyen-magento2"}}}`

**Response:** 

`[INFO] JSON Response to Adyen:{"additionalData":{"requestAmount":"8890","requestCurrencyCode":"EUR"},"pspReference":"TSFHK8CTZPHG5S82","resultCode":"Refused","merchantReference":"52000146410_K8S"}`

**On Adyen platform:**

Refused (ERROR -102: Invalid phone number - Invalid phone number NO PAYLOAD ) Shopper interaction

**Expected behavior**

I should see an error on frontend because telephone number doesn't meet Portuguese phone number pattern. No request is done to backend (and Adyen) until pattern has been met.

**Magento version**
2.4.3-p1

**Plugin version**
8.1.1

**Comment by tnaber** [comment]
Hi @jonathanribas,

Currently we see the Checkout component as our first line of defence. This should mean that the number would be accepted by magento but rejected when a payment is trying to be made, without it going through to the Adyen platform.

Cheers,
Titus

**Comment by jonathanribas** [comment]
Hi @tnaber, do you have news regarding this issue?
We are loosing business in Portugal :(
Thanks in advance!

**Comment by tnaber** [comment]
Hi @jonathanribas,

The mentioned issue (#1601) should fix the problem :)

Cheers,
Titus

**Comment by jonathanribas** [comment]
Hi @tnaber, thank you!
I will keep an eye on the progress.

**Comment by tnaber** [comment]
Hi @jonathanribas,

I am aiming to add this to the next release :)

Cheers,
Titus

**Comment by jonathanribas** [comment]
Thank you @tnaber, looking forward to it.
