### ISSUE TITLE
Adyen Logger causes exception while creating order

### ISSUE THREAD

**Issue by antonio-vitale** [Adyen/adyen-magento2#1448]
After activating Adyen Logger, creating a new order from admin will throw an Exception if any WARNING LEVEL MESSAGES are added.

1. Activate Logging
2. Create a new order from Backoffice
3. Select Adyen Payment method (e.g. Pay By Link)
4. Magento will throw an Error: 'Undefined class constant 'ADYEN_WARNING' in vendor/adyen/module-payment/Logger/AdyenLogger.php:80 '

**Magento version**
2.4.2

**Plugin version**
8.2.0

**Comment by Morerice** [comment]
Hi @antonio-vitale,

Thanks for opening this issue. We have already identified a solution which will be introduced next week on v8.2.1. The fix is to use the default `WARNING` constant and not the `ADYEN_WARNING` one.

Thanks,
Jean
Adyen

**Comment by antonio-vitale** [comment]
Hi @Morerice,

that's perfect! I'll close this issue :)
