### ISSUE TITLE
[PW-6548] Adyen Pay By link Exception: failed to parse taxPercentage.

### ISSUE THREAD

**Issue by antonio-vitale** [Adyen/adyen-magento2#1449]
I was creating a new order from Backoffice, using Pay By Link as payment method for my order. After I've placed it, in API logs i found that the field taxPercentage wasn't correct.

Actually, the correct value is '22', but the module parse this value into '2200'.

I found that in _\Adyen\Payment\Helper\Data.php_ there's a function named **formatAmount** that return the amount manipulated by php function number_format.

`
return (int)number_format($amount, $this->decimalNumbers($currency), '', '');
`

The 3rd param of this function is the **decimal_separator**, and it's empty. 
Filling this param with dot '.' seems fixing my issue.

 `
return (int)number_format($amount, $this->decimalNumbers($currency), '.', '');
`

[EDIT]
After more tests, using dot there will not really fix the problem. Adyen will generate the pay link but amount won't be correct. And the value 2200 it's actually right, so i was wrong about it.

[EDIT #2]
In vendor/adyen/module-payment/Gateway/Request/CheckoutDataBuilder.php:355, there is:

`
'taxPercentage' => ($formattedTaxAmount / $formattedPriceExcludingTax) * 100 * 100
`
(result: 2195.1256745 => failed to parse [x] as Long)

Changing it into:
`
'taxPercentage' => (int)(($formattedTaxAmount / $formattedPriceExcludingTax) * 100 * 100)
`
(result: 2195 => ok!)

Seems to fix the problem.

1. Activate Pay By Link
2. Create a new order from Backoffice, add a Product having a Tax Group and use Pay By Link
3. Check at API url

**Magento version**
2.4.2

**Plugin version**
8.2.0

**Comment by antonio-vitale** [comment]
In vendor/adyen/module-payment/Gateway/Request/CheckoutDataBuilder.php:355, parse the value as INTEGER and it seems to fix the problem.

`
'taxPercentage' => (int)(($formattedTaxAmount / $formattedPriceExcludingTax) * 100 * 100)
`

**Comment by tnaber** [comment]
Hi @antonio-vitale,

Thank you for opening this ticket. We have created a ticket and will be investigating this.

Cheers,
Titus

**Comment by tnaber** [comment]
Hi @antonio-vitale,

Currently, I am not able to recreate the issue. The item I order is taxed and ordered via the backend with PBL. The admin panel, PBL and the adyen backoffice return the correct amount. 
Could you give me a more clear description on how to recreate the issue and where in these steps your issue occurs?

Cheers,
Titus

**Comment by antonio-vitale** [comment]
Hi @tnaber,

Thanks for your reply.
Actually, i do the follow steps:

- Open Backoffice
- Create new Order
- Select a customer
- Add a product (price incl tax: €20.00, taxes: € 3.61)
- Select shipment (price incl tax: €10.00, taxes: €1.80)
- Select Pay By Link as Payment Method

I expect that payment method returns me a Payment Link but this doesn't actually happen.

In Log, i got:

[2022-04-08 13:48:32] AdyenLoggerTest.ERROR: 702: The ‘taxPercentage’ field is invalid. Failed to parse [2195.1219512195] as Long {“is_exception”:false} []

And the taxPecentage in this case is relative to shipment taxes.

**Comment by eliseyvrublevskiy** [comment]
exactly the same problem.

**Comment by tnaber** [comment]
Hi,

I added the fix in a PR, feel free to check it out!

Cheers,
Titus
