### ISSUE TITLE
Adyen resets Reserved Order ID for non-Adyen payment methods

### ISSUE THREAD

**Issue by pmzandbergen** [Adyen/adyen-magento2#1452]
**Bug Description**
On submitting payment information (e.g. placing an Order) the Adyen module resets the Reserved Order ID (if any) for all payment methods except `adyen_pos_cloud`. This will cause conflicts with other (non-Adyen) payment methods using a Reserved Order ID.

**Code**
See:
https://github.com/Adyen/adyen-magento2/blob/a5bb72a4ccf48d5c8a8096fb9664a902b28ec297/Plugin/PaymentInformationResetOrderId.php#L59
https://github.com/Adyen/adyen-magento2/blob/a5bb72a4ccf48d5c8a8096fb9664a902b28ec297/Plugin/GuestPaymentInformationResetOrderId.php#L68

**Suggested Fix**
Check if the used payment method is an Adyen payment method, for example instead of:
```
if ($quote->getPayment()->getMethod() !== 'adyen_pos_cloud') {
```
Use:
```
if (preg_match('/^adyen_(?!pos_cloud$)/', $quote->getPayment()->getMethod()) {
```

_Note: I'll create a PR._

**Comment by tnaber** [comment]
Hi @pmzandbergen, closing this as the PR is merged! Thanks for the contribution :)
