### ISSUE TITLE
Composer.json doesnt contain  "magento/module-quote-graph-ql": "*",

### ISSUE THREAD

**Issue by LexKoomen** [Adyen/adyen-magento2#1466]
We had all graphQL modules in the composer replace because we did not use this feature yet.
However the latest version (8.2.0) makes use of this module.

for example:

vendor/adyen/module-payment/Model/Cart/Payment/AdditionalDataProvider/AdyenCc.php
use Magento\QuoteGraphQl\Model\Cart\Payment\AdditionalDataProviderInterface; 

Maybe a best practice to add the module to the composer.json requirements?

**Comment by jonathanribas** [comment]
Hi @LexKoomen, I don't think we are talking about a bug here but it could be a great first contribution on Adyen module for Adobe Commerce!

**Comment by tnaber** [comment]
Hi @LexKoomen,

We also don't see anything breaking. Feel free to open a PR for this!
I will mark this as an enhancement.

Cheers,
Titus

**Comment by aligent-lturner** [comment]
@LexKoomen if you are using `replace` in `composer.json` to remove all graphql modules, then adding it as a requirement in this module won't affect anything.
