### ISSUE TITLE
GraphQL errors on adyen_payment_status field / adyenPaymentStatus query

### ISSUE THREAD

**Issue by marc-arnoult** [Adyen/adyen-magento2#1469]
**Describe the bug**
When i want to check the order status, the order do not exists on the GraphQL Resolver.

```
{
  "errors": [
    {
      "message": "Order does not exists",
      "extensions": {
        "category": "graphql-no-such-entity"
      },
      "locations": [
        {
          "line": 19,
          "column": 7
        }
      ],
      "path": [
        "placeOrder",
        "order",
        "adyen_payment_status"
      ]
    }
  ],
  "data": {
    "setPaymentMethodOnCart": {
      "cart": {
        "selected_payment_method": {
          "code": "adyen_cc",
          "title": "CB (Visa, MC, Amex)",
          "__typename": "SelectedPaymentMethod"
        },
        "__typename": "Cart"
      },
      "__typename": "SetPaymentMethodOnCartOutput"
    },
    "placeOrder": {
      "order": {
        "order_number": "12000817011_DEV",
        "cart_id": "UDCv115nyK9k7aAxPxvKdTizrxEKyzsj",
        "adyen_payment_status": null,
        "__typename": "Order"
      },
      "__typename": "PlaceOrderOutput"
    }
  }
}
```

The order is placed so the quote become inactive.

**To Reproduce**
Make a payment with GraphQL query from the documentation. https://docs.adyen.com/plugins/magento-2/magento-headless-integration#place-order

**Expected behavior**
I should be able to check the order status even if the order is placed.

**Magento version**
2.4.3-p1

**Plugin version**
8.2.0

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Chrome
 - Version: 100

**Comment by jonathanribas** [comment]
@marcoboom next time talk to @marc-arnoult ahah

**Comment by tnaber** [comment]
Closing this as it is a duplicate, let's continue the conversation in #1470
