### ISSUE TITLE
[PW-6589] Multishipping - paymentValidation mixin returning false on other payment methods

### ISSUE THREAD

**Issue by rob-vaimo** [Adyen/adyen-magento2#1475]
Magento 2.3.6

**Describe the bug**
If Bank Transfer or Cash on delivery (as examples) payment methods are enabled and selected  in Magento Multishipping, the "Review Your Order" button fails to take the user to the next page

The _validatePayment function called in /magento/module-multishipping/view/frontend/web/js/payment.js line 148 (defined line 79) returns 'false' due to the mixin at Adyen/module-payment/view/frontend/web/js/view/checkout/multishipping/payment-mixin.js

The input #stateData has an empty val();

**To Reproduce**
1. Go to Magento Multihshipping Payment page with Bank Transfer and Adyen Credit Cards as enabled option
2. Select "Bank Transfer" and click "Review your order"

**Expected behavior**
The user is redirected to the review order page with Bank Transfer as their selected Payment Method

**Magento version**
2.3.6-p1

**Plugin version**
7.3.5

**Additional context**

**Comment by tnaber** [comment]
Hi @rob-vaimo,

Thank you for opening this issue. I have created an internal ticket to investigate this.

Cheers,
Titus

**Comment by candemiralp** [comment]
Hi @rob-vaimo,

We've already created a PR related to this. Thank you for opening the issue. 

Sincerely,
Can
