### ISSUE TITLE
express checkout for Apple Pay / Amazon Pay / Google Pay

### ISSUE THREAD

**Issue by jamstew2001** [Adyen/adyen-magento2#1476]
@rikterbeek You have a feature request for express checkout on the product page, mini cart and basket for Magento. 2. Do you think this feature could be completed in the next couple of weeks? I think the feature would increase transactions dramatically. 

Thank you

James

**Comment by tnaber** [comment]
Hi @jamstew2001,

Your comment in #1079 has been noted and we will be discussing internally about this. I am closing this issue so we can continue in #1079

Cheers,
Titus
