### ISSUE TITLE
[PW-6627] Error when an order with a coupon is cancelled

### ISSUE THREAD

**Issue by jonathanribas** [Adyen/adyen-magento2#1479]
**Describe the bug**

When an order is placed with a coupon code and this one is cancelled, it's actually generating an error 500 when `/adyen/process/result` is called.

_NB: This is maybe a core Adobe Commerce issue._

**To Reproduce**
1. Add a product to your cart
2. Apply a coupon to your cart
3. Place an order that will generate a cancellation
4. We have the following error when `/adyen/process/result` is called

`Zend_Db_Statement_Exception: Noticed exception 'Zend_Db_Statement_Exception' with message 'SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`magento2`.`salesrule_customer`, CONSTRAINT `SALESRULE_CUSTOMER_RULE_ID_SEQUENCE_SALESRULE_SEQUENCE_VALUE` FOREIGN KEY (`rule_id`) REFERENCES `sequence_salesrule` (`sequence_value`) ON DELETE ), query was: INSERT INTO `salesrule_customer` () VALUES ()' in /var/www/html/vendor/magento/framework/DB/Statement/Pdo/Mysql.php:110
in Magento\Framework\DB\Statement\Pdo\Mysql::tryExecute called at /var/www/html/vendor/magento/framework/DB/Statement/Pdo/Mysql.php (92)
in Magento\Framework\DB\Statement\Pdo\Mysql::_execute called at /var/www/html/vendor/magento/zendframework1/library/Zend/Db/Statement.php (323)
in Zend_Db_Statement::execute called at /var/www/html/vendor/magento/zendframework1/library/Zend/Db/Adapter/Abstract.php (480)
in Zend_Db_Adapter_Abstract::query called at /var/www/html/vendor/magento/zendframework1/library/Zend/Db/Adapter/Pdo/Abstract.php (238)
in Zend_Db_Adapter_Pdo_Abstract::query called at /var/www/html/vendor/magento/framework/DB/Adapter/Pdo/Mysql.php (560)
in Magento\Framework\DB\Adapter\Pdo\Mysql::_query called at /var/www/html/vendor/magento/framework/DB/Adapter/Pdo/Mysql.php (627)
in Magento\Framework\DB\Adapter\Pdo\Mysql::query called at /var/www/html/vendor/magento/zendframework1/library/Zend/Db/Adapter/Abstract.php (576)
in Zend_Db_Adapter_Abstract::insert called at /var/www/html/vendor/magento/module-resource-connections/DB/Adapter/Pdo/MysqlProxy.php (1227)
in Magento\ResourceConnections\DB\Adapter\Pdo\MysqlProxy::insert called at /var/www/html/vendor/magento/framework/Model/ResourceModel/Db/AbstractDb.php (781)
in Magento\Framework\Model\ResourceModel\Db\AbstractDb::saveNewObject called at /var/www/html/vendor/magento/framework/Model/ResourceModel/Db/AbstractDb.php (421)
in Magento\Framework\Model\ResourceModel\Db\AbstractDb::save called at /var/www/html/vendor/magento/framework/Model/AbstractModel.php (655)
in Magento\Framework\Model\AbstractModel::save called at /var/www/html/vendor/magento/module-sales-rule/Model/Coupon/Usage/Processor.php (147)
in Magento\SalesRule\Model\Coupon\Usage\Processor::updateCustomerRuleUsages called at /var/www/html/vendor/magento/module-sales-rule/Model/Coupon/Usage/Processor.php (81)
in Magento\SalesRule\Model\Coupon\Usage\Processor::process called at /var/www/html/vendor/magento/module-sales-rule/Model/Coupon/UpdateCouponUsages.php (62)
in Magento\SalesRule\Model\Coupon\UpdateCouponUsages::execute called at /var/www/html/vendor/magento/module-sales-rule/Plugin/CouponUsagesDecrement.php (57)
in Magento\SalesRule\Plugin\CouponUsagesDecrement::afterCancel called at /var/www/html/vendor/magento/framework/Interception/Interceptor.php (146)
in Magento\Sales\Model\Service\OrderService\Interceptor::Magento\Framework\Interception\{closure} called at /var/www/html/vendor/magento/framework/Interception/Interceptor.php (153)
in Magento\Sales\Model\Service\OrderService\Interceptor::___callPlugins called at /var/www/html/generated/code/Magento/Sales/Model/Service/OrderService/Interceptor.php (23)
in Magento\Sales\Model\Service\OrderService\Interceptor::cancel called at /var/www/html/vendor/adyen/module-payment/Helper/Data.php (741)
in Adyen\Payment\Helper\Data::cancelOrder called at /var/www/html/vendor/adyen/module-payment/Controller/Process/Result.php (385)
in Adyen\Payment\Controller\Process\Result::_validateUpdateOrder called at /var/www/html/vendor/adyen/module-payment/Controller/Process/Result.php (285)
in Adyen\Payment\Controller\Process\Result::validateResponse called at /var/www/html/vendor/adyen/module-payment/Controller/Process/Result.php (185)
in Adyen\Payment\Controller\Process\Result::execute called at /var/www/html/vendor/magento/framework/Interception/Interceptor.php (58)
in Adyen\Payment\Controller\Process\Result\Interceptor::___callParent called at /var/www/html/vendor/magento/framework/Interception/Interceptor.php (138)
in Adyen\Payment\Controller\Process\Result\Interceptor::Magento\Framework\Interception\{closure} called at /var/www/html/vendor/magento/framework/Interception/Interceptor.php (153)
in Adyen\Payment\Controller\Process\Result\Interceptor::___callPlugins called at /var/www/html/generated/code/Adyen/Payment/Controller/Process/Result/Interceptor.php (23)
in Adyen\Payment\Controller\Process\Result\Interceptor::execute called at /var/www/html/vendor/magento/framework/App/Action/Action.php (111)
in Magento\Framework\App\Action\Action::dispatch called at /var/www/html/vendor/magento/framework/Interception/Interceptor.php (58)
in Adyen\Payment\Controller\Process\Result\Interceptor::___callParent called at /var/www/html/vendor/magento/framework/Interception/Interceptor.php (138)
in Adyen\Payment\Controller\Process\Result\Interceptor::Magento\Framework\Interception\{closure} called at /var/www/html/vendor/magento/framework/Interception/Interceptor.php (153)
in Adyen\Payment\Controller\Process\Result\Interceptor::___callPlugins called at /var/www/html/generated/code/Adyen/Payment/Controller/Process/Result/Interceptor.php (32)`

**Expected behavior**
Order should be canceled without any error.

**Magento version**
2.4.3-p1

**Plugin version**
8.2.0

**Comment by tnaber** [comment]
Hi @jonathanribas,

Thank you for opening this issue. I have created a ticket for this and we will be investigating whether this is a problem on our or Adobe's side.

Cheers,
Titus

**Comment by jonathanribas** [comment]
Hi @tnaber, this issue might be fixed by the following Adobe Commerce patch:
MDVA-43824 (for Adobe Commerce and Magento Open Source >=2.3.6 <=2.3.7-p3 || >=2.4.1 <2.4.5)-Fixes the issue where an error appears on canceling orders with a discount.

Source: https://devdocs.magento.com/quality-patches/release-notes.html#v1113

**Comment by tnaber** [comment]
Hi @jonathanribas, good to hear. I hope it does! Can you close this issue when you verify?

**Comment by jonathanribas** [comment]
Hi @tnaber, we are live with the Quality Patch MDVA-43824 for a few hours now and we haven't noticed error anymore.
