### ISSUE TITLE
[PW-8364][PW-6910] Amazon Pay: Recurring payment and storing in Magento vault

### ISSUE THREAD

**Issue by improove-jesper** [Adyen/adyen-magento2#1483]
**Is your feature request related to a problem? Please describe.**
We're using the Adyen Magento 2 module + Magento Vault to store payment methods for a client's subscription service. 
They want to add Amazon Pay for their US customers. 

**Describe the solution you'd like**
In the same way as for Apple Pay and Google Pay, by having Magento vault set up, after enabling Amazon Pay in Adyen and basic configuration in Magento, it should work out of the box.

**Describe alternatives you've considered**
Developing own solution.

**Additional context**
Our clients expect Adyen to be a one-stop-solution for payment methods, and more and more clients are looking into offering Subscription Services

**Comment by RokPopov** [comment]
Hi @improove-jesper ,

Apologies for the late reply. Thanks for opening this issue and providing a suggestion. We have created an internal ticket that we will refine and will get back to you.

Kind regards,
Rok,
Adyen

**Comment by candemiralp** [comment]
Hello @improove-jesper,

Amazon Pay recurring payments now can be used with the new version of plugin V9. The tokens generated are stored in `vault_payment_token` table.

Best Regards,
Can
