### ISSUE TITLE
Updated API resources / PWA requires (public) access token (why?!)

### ISSUE THREAD

**Issue by pmzandbergen** [Adyen/adyen-magento2#1489]
While updating to version 8.x for a PWA application I noticed the required resources for API endpoints have been modified:
https://github.com/Adyen/adyen-magento2/commit/1e548f9cd803937a20cff3418c050eafab88473c

**Examples**
A few updated API endpoints (resources):
- `/V1/guest-carts/:cartId/retrieve-adyen-payment-methods`: `Adyen_Payment::guestPaymentMethods` (previously: `anonymous`)
- `/V1/carts/mine/retrieve-adyen-payment-methods`: `Adyen_Payment::paymentMethods` (previously: `self`)

**Documentation**
The documentation states:
> From version 8.0.0 onwards, you have to use a Magento OAuth authenticated API integration.
https://docs.adyen.com/plugins/magento-2/magento-headless-integration#before-you-begin

**New Endpoints**
New endpoints have been added with formKey validation:
- `/V1/internal/guest-carts/:cartId/retrieve-adyen-payment-methods`
- `/V1/internal/carts/mine/retrieve-adyen-payment-methods`

**Thoughts**
This requires a public visible OAuth access token to be available for our PWA, and it should be created as follows according to Adyen documentation:
> For Resource Access select Custom. Select all the resources under the Adyen directory. Select Save.

This does not seems to be a feature-proof concept. At the moment the resources are limited:
https://github.com/Adyen/adyen-magento2/blob/develop/etc/acl.xml

In feature development one might define new (admin?) resources. The danger exists that when creating an access token for simply "all resources under the Adyen directory" anyone with this access token could use these newly defined resources. Since it's a PWA the access token will be public (unless some sort of proxy is being used).

**Suggestions**
I'm wondering why the API resources have been altered in the first place. Wouldn't it be easier to add a config option? Exampe:
`Form Key required (disable for PWA)`: `Yes / No`

**Comment by Morerice** [comment]
Hi @pmzandbergen,

This update was done to add security to the endpoints exposed by the adyen plugin. As you rightly pointed out, creating a single access token and re-using it indefinitely is not 100% secure. Hence, as mentioned in issue https://github.com/Adyen/adyen-magento2/issues/1457 we are now recommending the use OAuth-based authentication to secure these resources.

Best regards,
Jean
Adyen

**Comment by pmzandbergen** [comment]
Hi @Morerice,

Unfortunately Magento uses OAuth 1.0a based authentication, so we can't use a technique like PKCE to protect the used keys (sort of). Therefore one will still be able to retrieve the used tokens.

I doubt there is any real added value in this construction (can you please explain?). And can I have your opinion on making this a configurable option (specifically for PWA's to disable)?

**Comment by Morerice** [comment]
> Hi @Morerice,
> 
> Unfortunately Magento uses OAuth 1.0a based authentication, so we can't use a technique like PKCE to protect the used keys (sort of). Therefore one will still be able to retrieve the used tokens.
> 
> I doubt there is any real added value in this construction (can you please explain?). And can I have your opinion on making this a configurable option (specifically for PWA's to disable)?

Hi @pmzandbergen,

The value of this construction is to utilize the [OAuth 1.0a](https://devdocs.magento.com/guides/v2.4/get-started/authentication/gs-authentication-oauth.html) authentication that Magento offers, to restrict access to the resources that the adyen plugin exposes. If this was not the case, these resources (such as `/V1/guest-carts/:cartId/retrieve-adyen-payment-methods`) would be accessible without any authentication

Best regards,
Jean
Adyen

**Comment by pmzandbergen** [comment]
Hi @Morerice ,

> If this was not the case, these resources (such as `/V1/guest-carts/:cartId/retrieve-adyen-payment-methods`) would be accessible without any authentication

That would be just like all default Magento guest-cart API endpoints, which is perfectly fine since they are "protected" by a masked Quote ID:
https://github.com/magento/magento2/blob/96faea78235f05b5c74f78db9dc8d5661a38c2fd/app/code/Magento/Quote/etc/webapi.xml#L81L107

Adding a **public available** resource token doesn't seem to make it any safer, just more of a hassle with the (small) risks described earlier.

The effective part of this change seems to be the use of formKeys, they are checked in the `Internal*` proxy classes. For example:
https://github.com/Adyen/adyen-magento2/blob/develop/Model/Api/Internal/InternalGuestAdyenPaymentMethodManagement.php

Blocking the other (lets call them "non-internal") API endpoints by default and optionally (configurable) enabling them for PWA's would be sufficient to require formKey protection for non-PWA's.

**Comment by Morerice** [comment]
Hi @pmzandbergen

> That would be just like all default Magento guest-cart API endpoints, which is perfectly fine since they are "protected" by a masked Quote ID

Even though the masked quote id does offer some level of protection, it ultimately still does not provide any authentication to check if the request has the correct access roles. The request would only fail after Magento would have attempted to obtain the quote id related to the passed hash.

The use of formKeys (on the internal endpoints) is intended for non-headless merchants. Such merchants do not need to do any changes to update to v8 as we are automatically passing this form key in our [js files](https://github.com/Adyen/adyen-magento2/blob/51acd2b17cf26df977b5cb46b2c5266d3d189502/view/frontend/web/js/model/adyen-payment-service.js#L85)

> Adding a public available resource token doesn't seem to make it any safer, just more of a hassle with the (small) risks described earlier.

I'm not sure what you mean by publicly available. When an integration is created, its tokens (such as the consumer secret which is used to generate the signature) should not be publicly available as mentioned in the [Magento docs](https://docs.magento.com/user-guide/system/integrations.html#activate-an-integration). If somehow an attacker gains access to these tokens when they are sent from Magento to the callback url, that would indicate that there are much bigger security concerns on the merchant's platform.

Hence, would you agree that requiring an integration (for headless merchants) for these endpoints provides much better security than just leaving these endpoints open?

Best regards,
Jean
Adyen

**Comment by bramstroker** [comment]
@Morerice I also don't see why this would bring any extra security. The access-token must be passed as a bearer token and this is the same for all users of the GraphQL API. You can just inspect this headers in developer tools, and do any other requests with the same header. So this is what @pmzandbergen means with "public available".

**Comment by Morerice** [comment]
Hi @bramstroker

The access token won't be the only parameter required in the authorization header. Among others, a [successful authentication](https://devdocs.magento.com/guides/v2.4/get-started/authentication/gs-authentication-oauth.html#web-api-access) will also require the `oauth_signature` parameter that is generated by combining the consumer secret and the token secret.

Unfortunately we are bound by what Magento offers us to secure our endpoints (OAuth1.0a). With this change, we are following Magento's recommendations regarding how to authenticate these endpoints.

Best regards,
Jean
Adyen

**Comment by pmzandbergen** [comment]
@Morerice can you please provide an example how to use the API from a browser app (PWA) using JavaScript with OAuth 1.0a, where a user (being a **guest**) has no knowledge of the required keys / tokens / secrets? You can't, and that is exactly the problem I'm trying to point out.

You are adding authorization on endpoints which should not require any authorization. And even the implemented authorization is not being very useful, anyone who wants to abuse the endpoint can still do so by using the "internal" alternatives with a (valid) formKey.

> With this change, we are following Magento's recommendations regarding how to authenticate these endpoints.

Where did you exactly read this recommendation? You should require authentication on endpoints only if there is a reason to do so. For example getting a list of orders **for any given Customer**, that would require an Admin resource. Retrieving a list of **your own orders** would require a Customer resource. Getting Product information would not require any resource at all (or just "anonymous").

**If you want to protect your endpoints against (D)DOS or other sorts of abuse, authentication is not going to help (rate limiting will).**

I really don't understand this choice, neither did anyone I asked to have a look at it. Leaving me with the following options:
1. Patching your module fixing the resources
2. Use a publicly visible token (or OAuth keys / secrets)
3. Write a plug-in fixing overruling the resources
4. Use a proxy between the PWA and the Magento API endpoint

For those reading and needing an example for option 3:
```
<?php
declare(strict_types = 1);

namespace Vendor\Adyen\Plugin\Magento\Webapi\Controller\Rest\Router;

use Magento\Webapi\Controller\Rest\Router\Route as Subject;

class Route
{
    private const RESOURCES = [
        'V1/guest-carts/:cartId/retrieve-adyen-payment-methods' => ['anonymous'],
        'V1/carts/mine/retrieve-adyen-payment-methods' => ['self'],
        'V1/adyen/paymentDetails' => ['anonymous'],
    ];

    /**
     * Fix Permissions for PWA.
     *
     * @param Subject $subject
     * @param mixed   $result
     * @return mixed
     */
    public function afterGetAclResources(Subject $subject, $result)
    {
        $routePath = $subject->getRoutePath();

        return self::RESOURCES[$routePath] ?? $result;
    }
}
```
_Note: Patching the module is of course a better solution, since it doesn't introduce additional code_

**Comment by Morerice** [comment]
@pmzandbergen 

You can also re-enable token based authentication as mentioned [here](https://devdocs.magento.com/guides/v2.4/get-started/authentication/gs-authentication-token.html#integration-tokens) (point 2 on your list). This will also not introduce any additional code on your end.

We are not adding authorization to these endpoints. We are adding authentication. I am aware that this is not going to help against DDosS attacks, which is why I never mentioned that with this change we will mitigate DDoS attacks. Simply put this authentication is done to identify who is actually communicating with the backend, which ultimately is the whole point of authentication.

As I said, we are following Magento's recommendations regarding how to authenticate these endpoints. We are not following Magento’s recommendations on when to authenticate, because Magento doesn’t offer any guidelines on this, mainly because it’s not an in issue specific to Magento. It’s an issue related to general APIs.

The decision to add authentication to these endpoints was done after consultation with third-party organizations which conduct penetration tests on our module. Without these restrictions, there wouldn’t even be the possibility for any developers to develop the proxy that you mentioned (point 4) and utilize it with our module.

Obviously since the module will ultimately reside on your platform, you are free to create the plugin referenced by you, to modify this functionality.

Best regards,
Jean
Adyen

**Comment by pmzandbergen** [comment]
@Morerice

> You can also re-enable token based authentication as mentioned [here](https://devdocs.magento.com/guides/v2.4/get-started/authentication/gs-authentication-token.html#integration-tokens) (point 2 on your list). This will also not introduce any additional code on your end.

And is not recommended by Magento.

> We are not adding authorization to these endpoints. We are adding authentication.

Authentication which requires some sort of authorization, potato-potatoe.

> I am aware that this is not going to help against DDosS attacks, which is why I never mentioned that with this change we will mitigate DDoS attacks.

Since you are not giving any (understandable) reason for this change, I'll have to guess something.

> Simply put this authentication is done to identify who is actually communicating with the backend, which ultimately is the whole point of authentication.

Authentication was already in place for the "mine" cart routes (e.g. `/V1/carts/mine/retrieve-adyen-payment-methods`), this change ..................... never mind, not going to explain it all over again.

> As I said, we are following Magento's recommendations regarding how to authenticate these endpoints. We are not following Magento’s recommendations on when to authenticate, because Magento doesn’t offer any guidelines on this, mainly because it’s not an in issue specific to Magento. It’s an issue related to general APIs.
> 
> The decision to add authentication to these endpoints was done after consultation with third-party organizations which conduct penetration tests on our module. Without these restrictions, there wouldn’t even be the possibility for any developers to develop the proxy that you mentioned (point 4) and utilize it with our module.

And this third-party organization also suggested to duplicate the endpoint (the "internal" version), ***making the authentication useless***? Uhm, okay - really can't follow. :ghost:

> Obviously since the module will ultimately reside on your platform, you are free to create the plugin referenced by you, to modify this functionality.

For now I'll have to (sadly), it's not the first fix for this Adyen module.

_Note: This whole thread makes me wonder if I should invest any time in improving this module instead of keeping fixes & optimizations private._
