### ISSUE TITLE
[PW-6649] Valut and visa/dankort error

### ISSUE THREAD

**Issue by dronerdk** [Adyen/adyen-magento2#1501]
**Describe the bug**
We get an error when a logged in customer saves the card data for later use.
If the customer got to the card list in the customer account or try to checkout the error will come.

**To Reproduce**
1) Login as customer
2) Go to checkout with product
3) Save card data for next use
4) Complete order
5) Go to overview for cards or try to checkout again https://droner.dk/vault/cards/listaction/

**Magento version**
2.4.3-p1

**Plugin version**
8.1.0

**Screenshots**
<img width="2135" alt="Skærmbillede 2022-05-09 kl  23 52 43" src="https://user-images.githubusercontent.com/15999222/167505171-761b7ee9-554f-48b7-9527-e3f17061703f.png">

We are on live. Can we have a quick fix?

**Comment by dronerdk** [comment]
okay it is a easy fix by adding a visadankort_small.png in view/base/web/images/logos
But please make a fix so if the image is not present then a placeholder!!!!

**Comment by tnaber** [comment]
Hi @dronerdk,

I added the logo in the PR. I am not able to implement a correct placeholder as that code is not part of this plugin but Magento's :(

Cheers,
Titus

**Comment by dronerdk** [comment]
okay, you also need to add dankort_small. I think that is missing too.

**Comment by dronerdk** [comment]
You also need to add dankort_small.png
![zihplwbij0ir0q0e](https://user-images.githubusercontent.com/15999222/172374492-8e7f11ca-67ad-4625-932a-3cc6aede0ed2.png)

**Comment by tnaber** [comment]
Hi,
My apologies, I forgot about this.
See #1561
