### ISSUE TITLE
[PW-6650] Adyen_hpp popup modal is shown even when not used.

### ISSUE THREAD

**Issue by leonhelmus** [Adyen/adyen-magento2#1504]
Making your own contribution is easy, encouraged and greatly appreciated! We will put effort into reviewing and merging your PR quickly. For more info, please refer to the contribution guidelines: https://github.com/Adyen/adyen-magento2/blob/develop/CONTRIBUTING.md

**Describe the bug**
When using adyen hpp and having IDEAL and PayPal enabled. i get to see a popup whenever i click on "Place order" in the second step of the checkout. For Ideal this isn't such a big deal, because it will redirect afterwards to the adyen checkout. But for Paypal it is a issue, because after you clicked on "Paypal" you will get one popup and one new window. The new window is the authantication for Paypal to have a call for action to get the customer to log in. When i close this new window. You still see a model popup that is shown without any content. We applied the following patch to resolve the issue:

```
diff --git a/view/frontend/web/js/model/adyen-payment-modal.js b/view/frontend/web/js/model/adyen-payment-modal.js
--- a/vendor/view/frontend/web/js/model/adyen-payment-modal.js
+++ b/vendor/view/frontend/web/js/model/adyen-payment-modal.js
@@ -52,7 +52,6 @@
                     },
                 });

-                popupModal.modal('openModal');
                 return popupModal;
             },
             /**
```

**To Reproduce**
1. Add a product to the cart
2. Go to the checkout
3. Fill in shipping address and shipping method
4. Select a Adyen HPP method like paypal
5. Click on "Paypal" and a popup + a new window opens.
6. Close the new window
7. You'll see a popup without any content.

**Expected behavior**
1. The popup without any content should only be shown when it's used.

**Magento version**
2.4.3-p1

**Plugin version**
8.2.1

**Comment by leonhelmus** [comment]
Thanks for the fast reponse. Will check with the client if either are used and if not the patch is safe for now until you provide a fix for the bug.

**Comment by tnaber** [comment]
Hi @leonhelmus,

#1517 will be a foolproof fix for this!

Cheers,
Titus
