### ISSUE TITLE
Invoice paid but order total paid amount equal to 0

### ISSUE THREAD

**Issue by dimitriBouteille** [Adyen/adyen-magento2#1508]
**Describe the bug**

When invoice is paid, the order total paid, total due, ... are not updated.

**To Reproduce**

1. Create order with Adyen payment
2. Create paid invoice

In section order totals in admin : `Total Due != 0` and `Total Paid = 0` :( 

<img width="653" alt="Capture d’écran 2022-05-12 à 16 37 41" src="https://user-images.githubusercontent.com/34821762/168101318-f1723ffc-1707-4ec6-ad3c-06608fee0176.png">

When invoice is paid, total due must be equal to 0 and total paid must be equal to order grand total.

**Expected behavior**

The `sales_order.total_due` must be equal to 0 and `sales_order.total_paid` must be equal to order amount.

**The problem**

In the CRON adyen_payment_process_notification, here's what happens to capture the invoice :

- \Adyen\Payment\Helper\Webhook::handleOrderTransition(...)
- \Adyen\Payment\Helper\Webhook::handleManualCapture(...)
- \Adyen\Payment\Helper\Invoice::handleCaptureWebhook(...)
- Then, the invoice is pay() : 

https://github.com/Adyen/adyen-magento2/blob/5d6b157887eb3c4c810cad882d1c17b356309e23/Helper/Invoice.php#L208

- After, the order associate with the invoice is saved : 

https://github.com/Adyen/adyen-magento2/blob/5d6b157887eb3c4c810cad882d1c17b356309e23/Helper/Invoice.php#L210

- At this stage, all data is good : 

<img width="1664" alt="Capture d’écran 2022-05-12 à 16 35 00" src="https://user-images.githubusercontent.com/34821762/168102783-ae624ed1-1a1c-4519-afff-91e5bd368c20.png">

- Finally, \Adyen\Payment\Helper\Webhook::processNotification(...) LINE 360 : 

https://github.com/Adyen/adyen-magento2/blob/5d6b157887eb3c4c810cad882d1c17b356309e23/Helper/Webhook.php#L360

The problem: `$this->order` is not the same instance of $order object was use in `\Magento\Sales\Model\Order\Invoice::pay()`. So when invoice update order, $this->order is not updated.  So sales_order.total_paid, sales_order.base_total_paid, sales_order.base_total_due, ... have the wrong values.

<img width="1508" alt="Capture d’écran 2022-05-12 à 16 47 43" src="https://user-images.githubusercontent.com/34821762/168104141-87d3cc30-1806-4892-af62-4e4344d4c0ef.png">

**Versions**

- Magento version : ver. 2.4.3-p1
- adyen/module-payment : "8.2.2" (same bug with 8.1.1)

------

 Similar bug : https://github.com/Adyen/adyen-magento2/issues/1473#issuecomment-1117576217

**Comment by Morerice** [comment]
Hi @dimitriBouteille,

Thanks for opening this issue. Could you please mention which version this issue occurred on?

Thanks,
Jean
Adyen

**Comment by dimitriBouteille** [comment]
@Morerice I updated the issue :) 

- adyen/module-payment : "8.2.2" (same bug with 8.1.1)

**Comment by Morerice** [comment]
Hi @dimitriBouteille,

Unfortunately I was unable to replicate the issue. 
![Screen Shot 2022-05-17 at 11 31 45 AM](https://user-images.githubusercontent.com/11156828/168779802-8ace368b-6632-4d87-b8d0-21a3316803ca.png)

When examining your sceenshots a bit closer I noticed that the `$this->order->save()` call is done on line 379. However, in all of our v8.2 versions (where the Webhook.php file was introduced), that function call is made in a different line:

* 8.2.0 - [line 353](https://github.com/Adyen/adyen-magento2/blob/6197527fcdb859bf58b7c9ed380fc7ef05e210e2/Helper/Webhook.php#L353)
* 8.2.1 - [line 360](https://github.com/Adyen/adyen-magento2/blob/3e37cae661023036c31e9cef0d138b1aa6e735fb/Helper/Webhook.php#L360)
* 8.2.2 - [line 360](https://github.com/Adyen/adyen-magento2/blob/3e37cae661023036c31e9cef0d138b1aa6e735fb/Helper/Webhook.php#L360)

This might not be related to the problem but could you verify if you have any modifications to this file?

Regarding your final point (`$this->order->save()` being a different order instance). This instance should be updated with the newer values in this [function call](https://github.com/Adyen/adyen-magento2/blob/6197527fcdb859bf58b7c9ed380fc7ef05e210e2/Helper/Webhook.php#L1859), after the `handleCaptureWebhook()` function was called.

Could you please verify if this `setOrderByIncrementId()` function call is being made?

Thanks and regards,
Jean
Adyen

**Comment by dimitriBouteille** [comment]
Hi @Morerice

Thank you very much for your feedback, it has allowed me to better understand how the notification CRON works. 

I actually made a change to the `setOrderByIncrementId()` function, I now load the command with order_id.

In the first version of my code, the command was loaded from the `OrderRepository::get(...) `however there is a local cache in the function so that the command was loaded only once from the database and then the other times it was the cache that took over.

```php
public function setOrderByIncrementId(\Reflet\Adyen\Model\Notification $notification): void
{
    $orderId = $notification->getOrderId();
    if ($orderId) {
        $this->order = $this->orderRepository->get($orderId);
        if ($this->order) {
            return;
        }
    }

    ...
}
```

<img width="1056" alt="Capture d’écran 2022-05-18 à 15 26 22" src="https://user-images.githubusercontent.com/34821762/169492727-4c7bdffd-f0f2-47ff-8e61-402492254608.png">

I fixed this point, to load the command from the `OrderRepository::getList(...)` :

```php
protected function setOrderByIncrementId(\Adyen\Payment\Model\Notification $notification): void
{
    /** @var \Reflet\Adyen\Model\Notification $notification */
    $orderId = $notification->getOrderId();
    if ($orderId) {
        $searchCriteria = $this->searchCriteriaBuilder
            ->addFilter('entity_id', $orderId, 'eq')
            ->create();

        $orderList = $this->orderRepository->getList($searchCriteria)->getItems();

        /** @var \Magento\Sales\Model\Order $order */
        $order = reset($orderList);
        if ($order) {
            $this->order = $order;
            return;
        }
    }

    ...
}
```

Thank you for your help.
