### ISSUE TITLE
[PW-6744] Multishipping + Offline payment method error

### ISSUE THREAD

**Issue by matmarchant** [Adyen/adyen-magento2#1521]
**Describe the bug**
When using multishipping checkout and choosing to pay with an offline payment method e.g. check, cash on delivery, bank transfer, free. An error is thrown when you click place order because the resultCode is missing from the additional payment information and is required by adyen/module-payment/Block/Checkout/Multishipping/Success.php

**To Reproduce**
1. Go to Multishipping checkout
2. Check out using multiple addresses
3. Select any offline payment method
4. Click on Place Order
6. See error Notice: Undefined index: resultCode in adyen/module-payment/Block/Checkout/Multishipping/Success.php on line 168

**Expected behavior**
The checkout success page should be displayed

**Magento version**
2.4.3

**Plugin version**
8.1.1

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser Chrome
 - Version 101.0.4951.64

**Additional context**

**Comment by tnaber** [comment]
Hi @matmarchant,

Thank you for opening this issue. As the offline payments methods will not have a resultCode we should exempt them from our checker. I have created a ticket for this.

Cheers,
Titus

**Comment by Morerice** [comment]
Hi @matmarchant,

This issue has been fixed in the linked PR. It will be live in the next release, later this week.

Thanks,
Jean
Adyen
