### ISSUE TITLE
Google Analytics still reporting referrals

### ISSUE THREAD

**Issue by grantkemp** [Adyen/adyen-magento2#153]
Currently Google Analytics is still reporting issues which were fixed in #93 . It seems the fix is incomplete.  (released in v2.03)  

Currently Magento2 is generating success urls of /checkout/onepage/success/utm_nooverride/1/ instead of /checkout/onepage/success?utm_nooverride=1

Thus users are still getting incorrect Referral Traffic Channel Attribution and their Session counts in Google will be inflated.

**Comment by rikterbeek** [comment]
Hi @grantkemp,

Looks like we need to change /1 changed to =1 not sure how we can do this in the redirect, do you know ?

Regards,
Rik
Adyen

**Comment by rikterbeek** [comment]
Hi @grantkemp,

See commit above this should fix the issue you have.

Regards,
Rik
Adyen

**Comment by grantkemp** [comment]
@rikterbeek  were you able to test it? If not push it up in a shared instance and happy to help you test?

**Comment by rikterbeek** [comment]
Hi @grantkemp,

No I do not have anything setup for google analytics not our intrest just helping our merchants out with adding this into the extension.

Regards,
Rik
Adyen
