### ISSUE TITLE
Icon not showing on HPP integrations

### ISSUE THREAD

**Issue by kuwiano** [Adyen/adyen-magento2#154]
Hi everyone, we are using Magento version 2.1.7 and version 2.0.6 of your plugin and what is descibed in  #66 still happens

The generated link:
```/static/version1500970041/frontend/_view/fr_FR/Adyen_Payment/images/logos/cartebancaire.png```
The correct one:
```/static/version1500970041/frontend/Codazon/fastest_company/fr_FR/Adyen_Payment/images/logos/cartebancaire.png```

**Comment by rikterbeek** [comment]
Hi @kuwiano,

Are you able to upgrade to  2.1.7 ? The reason why I do not like to hardcode the location is that you can't update your own icons in your own theme.

Regards,
Rik
Adyen

**Comment by rikterbeek** [comment]
Hi @kuwiano,

The fix above should solve your issues. It is a core issue so hopefully they will fix it in the 2.2 release of Magento. When we merge the PR we can do the release next week for the time being just apply the changes manually and validate if this solves your issues.

Regards,
Rik
Adyen
