### ISSUE TITLE
[PW-6756] Checkout page won't load in MacOS 12.4 or IOS 15.5 if Limit IP Address Tracking enabled

### ISSUE THREAD

**Issue by bitumin** [Adyen/adyen-magento2#1540]
**Describe the bug**
Checkout page (select payment method step) with Paypal payment method won't load if using Safari on latest MacOS or iOS versions (MacOSX 12.4 or iOS 15.5), with network option "Limit IP Address Tracking" enabled.

**To Reproduce**
1. Update your iOS or Mac to the latest version (MacOS 12.4, iOS 15.5).
2. Verify that in your current Network / Wi-Fi connection the option "Limit IP Address Tracking" is enabled.    
3. Proceed to the Checkout page, last step of your web shop.
4. Page do not finalise loading, rendering the page unusable/unclickable.

**Expected behavior**
Checkout page should be loading. If one payment method does not successfully load (i.e. Paypal), the rest of the methods should be available.

**Magento version**
2.4.2-p2

**Plugin version**
7.2.0

**Screenshots**

**Desktop (please complete the following information):**
 - MacOS 12.4
 - Safari

**Smartphone (please complete the following information):**
 - iPhone11
 - iOS 15.5
 - Safari

**Additional context**
- If you are using Paypal Express Checkout it should be broken too (Paypal checkout button won't appear).
- If network option is disabled, everything works as expected.

**Comment by tnaber** [comment]
Hi @bitumin,

Thank you for opening this issue. We will be investigating this.
An obstacle for us might be that we would have to check for a specific MacOSX version, this might delay our solution. 
If you have any idea what might cause this, you are of course encouraged to open a PR proposing your own fix!

Cheers,
Titus

**Comment by tnaber** [comment]
Hi,

Currently we are having a hard time replicating this. As I understand it, the problem only occurs when Paypal (via Adyen) is enabled right? A satisfying solution would be to catch this error and let the other payments load anyway?

Cheers,
Titus

**Comment by AlexandrosMor** [comment]
Hello @bitumin,

We tested from our side and it works properly using the steps that you mentioned. We are going to close this issue and if the issue persists then re open it with more information.

kind regards,
Alexandros
Adyen

**Comment by jarcorreia** [comment]
Hello @AlexandrosMor 

This is an issue that is still happening.
**Magento version**
2.4.3-p2

**Plugin version**
8.1.1

This is related only to Safari as it works on Chromium based browsers. The following setting is preventing the checkout from loading completely. As soon as this MacOS option is disabled, it loads the checkout just fine.
<img width="268" alt="Screenshot 2022-10-06 at 17 46 10" src="https://user-images.githubusercontent.com/48832799/194371498-393eaff6-8da8-42d3-a74c-c69b6ffa6ddb.png">

The error that looks related:
<img width="1057" alt="Screenshot 2022-10-06 at 17 48 39" src="https://user-images.githubusercontent.com/48832799/194372106-575aea84-02cf-4da9-85b8-b8258c267446.png">


Best regards
Joao

**Comment by jarcorreia** [comment]
This is a big issue as customers that want to only pay using ApplePay can't do it as they need to be on Safari.

**Comment by bitumin** [comment]
> As I understand it, the problem only occurs when Paypal (via Adyen) is enabled right? A satisfying solution would be to catch this error and let the other payments load anyway?

Yes, you are 100% right. As I understand it, the underlying issue is with Paypal + Mac security network settings. The underlying issue cannot be fixed by Adyen (unless you guys have superpowers ;). But I would suggest that you make your payment methods loading process slightly more robust (if possible), to allow for the checkout page (and the other payment methods, if any) to finalise loading.
