### ISSUE TITLE
Show accepted credit card logos

### ISSUE THREAD

**Issue by xxuanng** [Adyen/adyen-magento2#1554]
**Is your feature request related to a problem? Please describe.**
When customers pay with credit card on the checkout page, they are not able to see the logos of credit cards that are accepted because no logos are rendered. This is a standard feature from other payment plugins like Telecash, Payone etc. 

It is important for customers to know which cards they can use to pay!

**Describe the solution you'd like**
The logos of accepted cards should be rendered on the UI, like in Adyen's Drop-in solution.

**Describe alternatives you've considered**
Customization has been suggested to us but we expected this to come out of the box from the plugin

**Comment by tnaber** [comment]
Hi @xxuanng,


Thank you for opening this feature request. We have updated our Checkout component for 8.2.4 (to be released) in #1551  which implements this feature:
![image](https://user-images.githubusercontent.com/23633368/171598955-9a07359f-a784-44cc-b17f-433e239dd6c4.png)

Let me know if this is indeed the feature you were requesting!

Cheers,
Titus

**Comment by norgeindian** [comment]
@tnaber , awesome, that's exactly what we were looking for, thanks a lot for the fast including.

**Comment by tnaber** [comment]
You can keep an eye on #1549!
