### ISSUE TITLE
Capture callbacks fail on 8.2.3

### ISSUE THREAD

**Issue by siimm** [Adyen/adyen-magento2#1562]
## Describe the bug
After upgrading to version 8.2.3 from 7.3.6, the order processing is broken, invoices are never finalised and orders are staying in "Closed" state with pending invoices.

The main problem is that in case order is shipped before invoice is created, then on invoice creation, \Magento\Sales\Model\ResourceModel\Order\Handler\State::check is setting the order in closed state, due to matching conditions.

This was the case also in 7.x.x Release line, but then the CAPTURE notifications eventually re-set the order to Complete or Processing state. 
Now the CAPTURE callbacks just fail, leaving the notifications in progress.

## To Reproduce
1. Make sure that capture is in manual mode
2. Make a purchase using adyen_cc (also same with adyen_hpp)
3. Wait until AUTHORIZATION webhook is processed
4. In M2 admin interface, find && open the order
5. Create a shipment for the order
6. Invoice the order
7. Order now has Closed status
8. CAPTURE callback arrives in a few moments and since Closed status is not described in \Adyen\Payment\Helper\Webhook::WEBHOOK_ORDER_STATE_MAPPING, that will log an error and will be left as processing=1 in the DB forever after

## Expected behaviour
Order is not receiving Closed status in case Invoice is done after the shipment OR webhooks for CAPTURE are still handled correctly in case the order is in Closed state

### Magento version
2.4.2-p2

### Plugin version
8.2.3

### Additional context
I see that a ticket has been created related to similar behaviour regarding refunds: https://github.com/Adyen/adyen-magento2/issues/1493
but the PR attached to it (https://github.com/Adyen/adyen-magento2/pull/1557/files) will handle "Closed" status as "Canceled" which is also incorrect if we look at current problem description here.

**Comment by tnaber** [comment]
HI @siimm,

Thank you for opening this issue and the clear description. This problem has been noticed and a fix has been added in 8.2.4. Have a look at #1533!
The PR should clearly describe our fix and points at some discussions we had about it here on GH. I would suggest upgrading to 8.2.4 and checking whether you are still experiencing this issue.

Let me know if this is indeed the problem you are experiencing!

Cheers,
Titus

**Comment by siimm** [comment]
Hi @tnaber 
thanks for the swift response - can confirm that this problem is indeed fixed in 8.2.4
It appears that the current issue is obsolete
Regards,
Siim
