### ISSUE TITLE
Compatibility with Adyen Drop-In and headless Magento

### ISSUE THREAD

**Issue by fahu** [Adyen/adyen-magento2#1579]
Hello everyone :) As Adyen is deprecating HPP we are currently in the progress to migrate to Adyen Drop-in. Our Magento is headless - the checkout is custom build by us and communicating with Magento Core + Magento Adyen API.

We tried to follow the [Adyen Magento headless integration guide](https://docs.adyen.com/plugins/magento-2/magento-headless-integration) and the [Adyen Web Drop-In guide before v5.0.0](https://docs.adyen.com/online-payments/web-drop-in/integrated-before-5-0-0).

However, it seems that the latest Magento Adyen module (v8.2.5) is **not** compatible with Web Drop-in before v5.0.0. Web Drop-In expects v67 as API version while the Magento Adyen module works with v68.

At the same time it is not possible to integrate Adyen Web Drop-in >= v5.0.0 because the Magento Adyen plugin does not return the required session ID and session data.

Are we correct in the assumption that the Adyen Magento module does not support Adyen Drop-In at all?

Making your own contribution is easy, encouraged and greatly appreciated! We will put effort into reviewing and merging your PR quickly. For more info, please refer to the contribution guidelines: https://github.com/Adyen/adyen-magento2/blob/develop/CONTRIBUTING.md

**Magento version**
2.4.3

**Plugin version**
8.2.5

**Comment by KarthikMadathil** [comment]
How will we create session ?
which Api/ Graph Should i call from frontend to create session .

**Comment by barbazul** [comment]
The drop-in components documentation mentions the requirement of the session configuration argument. 

the module does not seem to be using the `/sessions` endpoint at all. How should the Drop-in components be implemented in the headless integration?
