### ISSUE TITLE
Expired payment issue

### ISSUE THREAD

**Issue by dronerdk** [Adyen/adyen-magento2#1582]
We use Magento 2 and is located in Denmark.
Due to danish law we are not allowed to capture the payment before we ship the items.
So we don’t generate invoices before we ship the items.
And when we create then invoice the payment can be expired if it is more than 4 weeks old.

Are there any way we can have the webhook to ping magneto 2 about the expired payment before the invoice generation?

Feature request:
So the workflow could be
Expired payment (webhook)-> New order status in magneto 2 (expired payment)
If the status in magento 2 become expired payment then it should try to re-authorize the payment (the risk of this is of course on the vendor)
if success we get the pending status again.
If no success we should be able to set of many days it should retry.
If no success -> cancel state/order

Do you have any other way to handle the module based on the issue with expired payments and the danish not capture law?

**Comment by dronerdk** [comment]
Yes, but you should strongly develop the notifications as a webhook option in adyen playform so the module can be used with that functionality. What is the reason for the missing webhook for expired payments?

**Comment by RokPopov** [comment]
Hi @dronerdk ,

Thank you for your reply. 
Unfortunately, the notifications that originate from the Adyen platform are out of the scope of our Magento2 plugin.

I would recommend sending a ticket to [support@adyen.com](support@adyen.com) for further enquiry. 

Kind regards,
Rok,
Adyen
