### ISSUE TITLE
Orders stay in pending state

### ISSUE THREAD

**Issue by dronerdk** [Adyen/adyen-magento2#1599]
We have observed a new behaviour in the module from version 8.2.0 or 8.2.5 regarding order state.
We use Magento 2.4.3-p1.
We have the option to split payments and we have set Adyen to manual capture.
We do make partial invoice for orders.

We did have in previous versions this behaviour when we created a partial invoice for an order.

The order gets authorized by Adyen, but we do not create invoice and do not capture it right away.
The order now is in a state new and pending.
We do create the first partial invoice for the order. So if the order has 3 items we now only invoice and capture 1 item.
After the capture is done the order state will now be processing.

But in the new versions after we create same partial invoice the state will not go from pending to processing. It will stay in pending.
Is this normal behaviour for the new modules that a partial invoice will not move the order from pending to processing state?

**Comment by RokPopov** [comment]
Hi @dronerdk 

Thank you for opening this issue.

The change in the state you are mentioning was introduces in this [PR](https://github.com/Adyen/adyen-magento2/pull/1533) as a solution for the issues #1390 and #1276. 
I can confirm this flow is expected. By introducing the 'Pending Payment' state, the order will be set to Pending Payment after it has been invoiced. This allows for a quick second capture (in case of partial payment) and allows for Shipping the order (it will stay in Pending Payment). It will move to Processing if the full amount has been captured. 

Cheers,
Rok,
Adyen
