### ISSUE TITLE
Duplicated admin settings naming

### ISSUE THREAD

**Issue by pivulic** [Adyen/adyen-magento2#16]
### Problem
If you see in http://www.vaimo.com/snaps/pablo.ivulic/adyen-duplicate-admin-settings.png, you will see that there are two "Webservice username" and two "Webservice Password" passwords. 

It's not a big problem, since each setting has an excellent tool tip explanation, but might be slightly confusing for new eyes.

### Expected Result
Maybe name each setting differently, something like:

- Webservice username (test)
- Webservice Password (test)
- Webservice username (live)
- Webservice Password (live)

**EDIT**: Or name them so that they correspond to https://docs.adyen.com/manuals/magento/magento2-integration/configuring-the-adyen-plugin/required-settings :)

**Comment by rikterbeek** [comment]
Hi Pablo,

Thanks for letting us know it is now indicated.

Regards,
Rik
Adyen
