### ISSUE TITLE
Order should filter out payments failure notifications under adyen and paid with other method such as cashondelivery

### ISSUE THREAD

**Issue by razvan-optaros** [Adyen/adyen-magento2#1601]
The https://github.com/Adyen/adyen-magento2/blob/754264cf7305138673ca4073306a2aa434fd72ea/Helper/Webhook.php#L1862 should be something like 

```
        if (!empty($order) && strpos($order->getPayment()->getMethod(), 'adyen') !== false) {
            $this->_order = $order;
        }
```

cc @rikterbeek

**Comment by RokPopov** [comment]
Hey @razvan-optaros ,

Thank you for opening an issue with us.

For clarification, could you please further elaborate and provide a context so we can understand the issue you are experiencing? 

Thank you in advance,

Kind regards,
Rok,
Adyen

**Comment by RokPopov** [comment]
Hi @razvan-optaros,

Would you be able to elaborate a bit on the background of why this is posing an issue as Adyen platform doesn't send out a notification unrelated to Adyen payment methods?

Looking forward to your reply,

Kind regards,
Rok,
Adyen

**Comment by RokPopov** [comment]
Hi @razvan-optaros,

I will be closing this ticket due to inactivity.
We would highly appreciate if you would be able to address the above questions, in that case we could reopen the ticket in the future.

Kind regards,
Rok,
Adyen
