### ISSUE TITLE
[PW-6891] Re-authorized payments and order cancellations 

### ISSUE THREAD

**Issue by dronerdk** [Adyen/adyen-magento2#1604]
We face a behaviour that can be optimized when dealing with an expired payment and when we Re-authorized the payment.

Most of the times a re-authorized payment will pass and create a new transaction. That is fine.

However sometimes the Re-authorized payment will not pass in Adyen.
When the Re-authorized payment will fail, Adyen sends a webhook to magento and the webhook will cancel the order.
I do not like that behaviour because it will be impossible to let the order gets Re-authorized yet again.
Sometimes a Re-authorized payment will pass in the next try, but now the order is canceled, becacuse of the first webhook and will not change status again.

So my change would be like this.
If a payment gets Re-authorized and fails it do not cancel the order. 
The most optimal would be if we could change order status on magneto configuration when we get a Re-authorized fail.

**Comment by RokPopov** [comment]
Hi @dronerdk 

Thank you for reporting this issue with us.

Testing the edge-case, I can confirm that we are experiencing the same flow with the unsuccessful re-authorisations of the transaction.
Please kindly note that refactoring the webhook flow is in our pipelines in the near future.
Your feedback and the proposed way to handle this are highly appreciated and we will make sure to take them into consideration when refactoring the flow.

Cheers,
Rok,
Adyen
