### ISSUE TITLE
[PW-6911] No longer compatible with Magento 2.3.x

### ISSUE THREAD

**Issue by aligent-lturner** [Adyen/adyen-magento2#1615]
**Describe the bug**
A change was introduced in two places that is not compatible with Magento 2.3.x:

- v7 line:  https://github.com/Adyen/adyen-magento2/pull/1437
- main (v8) line: https://github.com/Adyen/adyen-magento2/pull/1436

The issue is that the code is relying on a function `getInitCustomerData`, which was introduced in this commit - https://github.com/magento/magento2/commit/4d24466fb2ce20fcd769fd4b68c9e4d3e476fe35
This commit is only present in 2.4.x of Magento (as can be seen from a list of tags for the commit).

From a technical point-of-view, 7.3.7 and 8.2.0 should have been major version upgrades, as they were not backwards-compatible. This is not really practical now, since there have been other versions released since then.
The code would need to be made compatible with 2.3.x, or there should be explicit directions that it is not compatible - either in documentation or by composer requirements.

**To Reproduce**
1. Make purchase in 2.3.x environment
2. Observe error on success page.

**Expected behavior**

**Magento version**
2.3.x

**Plugin version**
>= 7.3.7, >= 8.2.0

**Desktop (please complete the following information):**
 - OS: any
 - Browser any
 - Version any

**Smartphone (please complete the following information):**
 - Device: any
 - OS: any
 - Browser any
 - Version any

**Additional context**

**Comment by RokPopov** [comment]
Hi @aligent-lturner,

Thank you for reporting this and providing us with a detailed explanation.
Indeed, as you correctly pointed out `getInitCustomerData ` was introduced in v2.4.x of Magento2. We appreciate your feedback and we have already opened an internal investigation to look into whether a fix could be implemented to make this compatible with v2.3.x of Magento2.

Kind regards,
Rok,
Adyen
