### ISSUE TITLE
state=canceled, status=processing

### ISSUE THREAD

**Issue by Per-Kris** [Adyen/adyen-magento2#167]
Orders that get the CANCELLATION eventCode are updated to state=canceled correctly. The issue is that the status still is processing. An example is the order with pspReference: 1315018476053674

Magento ver. 2.1.3
Adyen Payment ver 2.0.2

**Comment by rikterbeek** [comment]
Hi @Per-Kris,

Could you address this issue to our support team magento@adyen.com ? If you can provide the steps you performed, screenshots of comment history of the order and the results of the notification and cron logs that would be very helpful to look closer into this issue. 

The order should be close see:
https://github.com/Adyen/adyen-magento2/blob/develop/Model/Cron.php#L759
https://github.com/Adyen/adyen-magento2/blob/develop/Model/Cron.php#L646-L680

Regards,
Rik
Adyen

**Comment by Per-Kris** [comment]
We got new information from our client now that the orders is payed for and they received the order confirmation email. So the issue is the opposite. That state is canceled. But perhaps it's something outside of Magento since the cancelation event was received.

I've just emailed magento@adyen.com with further information.
