### ISSUE TITLE
Order is not cancelled when receiving cancelled response from Adyen

### ISSUE THREAD

**Issue by jonathanribas** [Adyen/adyen-magento2#1687]
**Describe the bug**
When we receive an authResult Cancelled, order is not cancelled on Adobe Commerce even if you have the right setting in place on Adyen's module configuration:

Aug 31, 2022 5:33:50 AM Pending Customer Not Notified
Adyen Result URL response:
authResult: Cancelled
pspReference: REGREGRGRG
paymentMethod:

<img width="888" alt="Screenshot 2022-08-31 at 09 14 47" src="https://user-images.githubusercontent.com/3003782/187629633-9745cee0-c660-4474-82b4-b553954e78f0.png">

**To Reproduce**
1. Place an order
2. This order is cancelled on Adyen side
3. Adyen send a cancelled response
4. Adyen module is not cancelling the order. Order stays in it's current state.

**Expected behavior**
Order should be cancelled.

**Magento version**
Adobe Commerce 2.4.3-p1

**Plugin version**
8.3.5

**Comment by Morerice** [comment]
Hi @jonathanribas,

Thanks for opening this issue. Could you confirm that the webhook is being processed, by checking the corresponding entry in **System** > **Adyen** > **Webhooks Overview** in the Magento back office?

Thanks,
Jean
Adyen

**Comment by Morerice** [comment]
Hi @jonathanribas,

Please disregard my last message as this issue does not seem to be related to the webhooks. Could you please specify with which payment methods this issue is occurring?

Thanks,
Jean
Adyen

**Comment by jonathanribas** [comment]
Hi @Morerice, I thought it was related to webhooks but it's not.

We are experiencing this issue with orders that got a RedirectShopper (Apple Pay, Klarna ...), sometimes we got Cancelled response and other times nothing as customers just stay on the redirect page and don't do anything more.

**Comment by Morerice** [comment]
Hi @jonathanribas,

Thanks for clarifying the issue. In that case this may be related to webhooks after all. This is because in both of these cases we rely on the [OFFER_CLOSED](https://docs.adyen.com/plugins/magento-2/troubleshooting#orders) webhook to update the status to `Canceled`. Could you check if this webhook is being correctly processed?

Thanks,
Jean
Adyen

**Comment by jonathanribas** [comment]
Hi @Morerice, thank you! 

I'm gonna test it.

**Comment by jonathanribas** [comment]
Hi @Morerice, I've enabled `OFFER_CLOSED` notification our Adyen merchant accounts and orders are now automatically cancelled after 3 days.
You can close this ticket, sorry.

**Comment by Morerice** [comment]
> Hi @Morerice, I've enabled `OFFER_CLOSED` notification our Adyen merchant accounts and orders are now automatically cancelled after 3 days. We can close this ticket, sorry.

No worries! Thanks for investigating on your end.

Regards,
Jean
Adyen
