### ISSUE TITLE
Deprecated Functionality: explode(): Passing null to parameter #2 ($string) of type string is deprecated

### ISSUE THREAD

**Issue by thomas-kl1** [Adyen/adyen-magento2#1688]
**Describe the bug**
After a successful payment, we have the following history comment:

Deprecated Functionality: explode(): Passing null to parameter #2 ($string) of type string is deprecated in /var/www/html/vendor/adyen/module-payment/Model/Billing/Agreement.php on line 249

See \Adyen\Payment\Model\Billing\Agreement::setCcBillingAgreement

This is because those methods can return null:

\Adyen\Payment\Helper\Data::getAdyenPosCloudConfigData
\Adyen\Payment\Helper\Recurring::getRecurringTypeFromSetting
\Adyen\Payment\Helper\Config::getCardRecurringType

**Magento version**
2.4.4

**Plugin version**
8.3.5

**PHP version**
8.1

**Comment by Morerice** [comment]
Hi @thomas-kl1,

This will be out on the next release, which is scheduled for sometime next week.

Regards,
Jean
Adyen
