### ISSUE TITLE
v8.4.0 is documented to be not supported for Magento 2.3.x, however there is no such constrain in the composer.json

### ISSUE THREAD

**Issue by kanevbg** [Adyen/adyen-magento2#1690]
So in a Magento 2.3.x system composer will update the adyen/payment-module to 8.4.0 instead of to 8.3.5 or newer from 8.3.x release line.

**Comment by shyameasternent** [comment]
lastest version require php7.3 version and magento 2.3.5 require php7.2 so it is not possible to install module atleast.

**Comment by kanevbg** [comment]
@shyameasternent that is wrong information. I already got adyen 8.4.0 in magento 2.3.7.
Check https://devdocs.magento.com/guides/v2.3/install-gde/system-requirements.html
![image](https://user-images.githubusercontent.com/11477130/187903055-1adeab97-3e5f-469a-a9f9-f680664922b6.png)
