### ISSUE TITLE
[PW-7146] - IP verification issue

### ISSUE THREAD

**Issue by Nuranto** [Adyen/adyen-magento2#1694]
Making your own contribution is easy, encouraged and greatly appreciated! We will put effort into reviewing and merging your PR quickly. For more info, please refer to the contribution guidelines: https://github.com/Adyen/adyen-magento2/blob/develop/CONTRIBUTING.md

**Describe the bug**

Since one of a latest release, you force IP validation.
Bad thing is the current IP validation is not working on most environments.

You should use `Magento\Framework\HTTP\PhpEnvironment\RemoteAddress::getRemoteAddress()` instead of using `$_SERVER['REMOTE_ADDR']`. When using proxies, REMOTE_ADDR will be the proxy's IP. `RemoteAddress` class will deal with that and will use headers value  (`X-Forwarded-For`, `X-Real-IP`, ..)

**To Reproduce**
1. Use a proxy with its own IP on your infrastructure
2. Test webhook

The test will fail with this error in logs `Notification has been rejected because the IP address could not be verified¥

**Expected behavior**

Webhook test OK

**Magento version**

2.4.5

**Plugin version**

8.4.0

**Comment by Morerice** [comment]
Hi @Nuranto,

Thanks for opening this issue. We are of this issue and we currently have an internal ticket to tackle it.

Regards,
Jean
Adyen

**Comment by Morerice** [comment]
Hi @Nuranto,

We have updated this functionality in the linked PR. This PR will be included in the next release (sometime next week). If issue persists, feel free to reopen this issue.

Thanks,
Jean
Adyen

**Comment by ajith107** [comment]
@Morerice @Nuranto  We are using Adobe Commerce 2.4.4-p1 and the Adyen module 8.5.0 (which includes this fix as well).
But unfortunately, this issue still persists on the latest version too...

Can we please reopen this issue?

**Comment by Nuranto** [comment]
Hi @ajith107.

Have a look here : https://dev98.de/2017/01/02/how-to-add-alternative-http-headers-to-magento-2/

**Comment by stephanie-ehrling** [comment]
> Hi @ajith107.
> 
> Have a look here : https://dev98.de/2017/01/02/how-to-add-alternative-http-headers-to-magento-2/

I had the very same issue and that worked for me!
