### ISSUE TITLE
Masks for Brazilian SSN (CPF and CPNJ) are missing

### ISSUE THREAD

**Issue by flaviosans** [Adyen/adyen-magento2#1696]
**Describe the bug**
In the last step, when we have to fill the ssn field with brazilian CPF or CNPJ, the field is not masked. Even if correctly filled by user, with no mask, the validator rejects because of format, with no dots or slashes. If user inserts the mask manually, everything goes well.

**To Reproduce**
1. In the last step of checkout, choose the 'boleto' option;
2. Fill in the 'CPF/CNPJ' field with a valid CPF or CNPJ;
3. Place Order;

**Expected Behavior**
Order placed with success

**Screenshots**

![image](https://user-images.githubusercontent.com/17519137/187950231-9ba9d171-9f8d-4817-af99-3146b9ab79a9.png)
Valid CNPJ being rejected because has no mask.

**Additional context**
We need only apply the mask, to the entered number 12345678912 become 123.456.789-12 (for CNPJ) or the number 12345678123456 become 12.345.678/1234-56, for example.  The Module already has further validation for authenticity of this data.

**Comment by Morerice** [comment]
Hi @flaviosans,

Thanks for opening this issue. Unfortunately the Adyen Magento 2 Module is not responsible for the validation in the checkout page. The module utilizes the [web component](https://github.com/Adyen/adyen-web) for this functionality. This web component is then included into the module.

Could you please redirect your question to this repository? Please also include the version of the component you are utilizing. You can obtain this version, by first checking the version of your Magento 2 Module and then checking our [releases page](https://github.com/Adyen/adyen-magento2/releases) to identify which component version is utilized by the aforementioned module version.

Thanks,
Jean
Adyen
