### ISSUE TITLE
Minification issue with df.js

### ISSUE THREAD

**Issue by lancergr** [Adyen/adyen-magento2#170]
When setting JS minification to Yes, the https://live.adyen.com/hpp/js/df.js is resolved as https://live.adyen.com/hpp/js/df.min.js which leads to 404.

Relevant line: https://github.com/Adyen/adyen-magento2/blob/develop/view/frontend/requirejs-config.js#L10

**Comment by hostep** [comment]
The suggested solution from Magento is to add this url to the `minify_exclude` node in the `config.xml` file, see the comment over here: https://github.com/magento/magento2/issues/5835#issuecomment-259474472 & https://github.com/magento/magento2/issues/5835#issuecomment-296290118

I haven't actually tested this, just came across this a while ago and kept it in mind.
