### ISSUE TITLE
Non-managed error with Paypal

### ISSUE THREAD

**Issue by Nuranto** [Adyen/adyen-magento2#1705]
**Describe the bug**

Context : We are trying to add Paypal payment method.

When clicking the paypal button on checkout, there's a loading on paypal side, and then a redirect to Magento with error message `Error with payment method please select different payment method`.

Result is : 
```
[2022-09-09T09:41:19.645282+00:00] AdyenLoggerTest.INFO: JSON Response to Adyen:{"pspReference":"...","resultCode":"Error","merchantReference":"...."} [] []
```

We cannot find anywhere the detail of the error, leaving us without a clear problem, and so without any solution.

**Expected behavior**

Log an error message that can help undestand what went wrong.

**Magento version**
2.4.5

**Plugin version**
8.5

**Comment by Nuranto** [comment]
I was not asking for fixing the issue. But for correct logging data in the extension.

**Comment by Morerice** [comment]
Hi @Nuranto,

Based on the log snippet you showed, there is also no further information about the error sent from the Adyen platform to the module. Hence, it's not really possible for the plugin to display more information about it, which is why I advised to open an internal ticket.

Thanks,
Jean
Adyen

**Comment by Nuranto** [comment]
Hello @Morerice,

Ok it make sense if we consider that the module logs every response of Adyen !

However, my email to magento@adyen.com returned with an error : `450 4.1.1 <[magento@adyen.com](mailto:magento@adyen.com)>: Recipient address rejected: unverified address: unknown`

**Comment by Morerice** [comment]
Hi @Nuranto,

Apologies from my end. Please send the mail to support@adyen.com.

Thanks,
Jean
Adyen
