### ISSUE TITLE
Failed to reset reservedOrderId Deprecated Functionality: preg_match(

### ISSUE THREAD

**Issue by Nuranto** [Adyen/adyen-magento2#1711]
**Describe the bug**

Found in logs : 

```
AdyenLoggerTest.ERROR: Failed to reset reservedOrderId Deprecated Functionality: preg_match(): Passing null to parameter #2 ($subject) of type string is deprecated in /var/www/html/vendor/adyen/module-payment/Plugin/PaymentInformationResetOrderId.php on line 57 [] []
```

**To Reproduce**

I don't know how to reproduce.
But I guess a simple `(string)` could fix the issue

**Expected behavior**

**Magento version**
2.4.5

**Plugin version**
8.5

**Comment by Morerice** [comment]
Hi @Nuranto,

Thanks for opening this issue. Indeed the solution seems to be trivial (an is_null check could also work). Could you please also specify the PHP version you're on?

Thanks,
Jean
Adyen

**Comment by Nuranto** [comment]
```
PHP 8.1.10 (cli) (built: Sep 13 2022 10:17:59) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.10, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.10, Copyright (c), by Zend Technologies
```
