### ISSUE TITLE
[PW-7274] - Wrong brand_code on sales_order_payment table

### ISSUE THREAD

**Issue by jonathanribas** [Adyen/adyen-magento2#1736]
**Describe the bug**
After a first failed payment attempt with an HPP payment method (Apple Pay / Klarna), `brand_code` is set on `sales_order_payment` table /  `additional_information` field.

On a second attempt with Credit Card payment method, `brand_code` is not updated.

There are maybe other data that is not wanted from first attempt. 

If you have auto capture enabled for Open Invoice payment methods (Klarna ...), second attempt with Credit Card will go with auto-capture too and it's maybe not wanted on your setup: https://github.com/Adyen/adyen-magento2/blob/develop/Gateway/Request/CheckoutDataBuilder.php#L120

**To Reproduce**
1. Place an order with Apple Pay but it has to be refused
2. Do a second attempt with Credit Card which will be successful
3. Check `sales_order_payment` table for this order, on `additional_information` field, `brand_code` will have `apple_pay` value

**Expected behavior**
`brand_code` should be emptied for Credit Card .

**Solution**

Reinit Additional Information only with Credit Card data on https://github.com/Adyen/adyen-magento2/blob/develop/Observer/AdyenCcDataAssignObserver.php#L82

**Magento version**
2.4.5

**Plugin version**
8.3.5

**Comment by Morerice** [comment]
Hi @jonathanribas,

Thanks for opening this issue. We have created an internal ticket to investigate this further.

Thanks,
Jean
Adyen
