### ISSUE TITLE
Webhook is not working because of invalid HMAC key 

### ISSUE THREAD

**Issue by tigrensolutions** [Adyen/adyen-magento2#1737]
**Describe the bug**
Order status is not updated from the webhook. When testing webhook from Adyen dashboard, it gets invalid HMAC Key error.

**To Reproduce**
1. Place the order from Magento webiste
2. Payment is authorized successfully in Adyen but order status is not updated 
3. From Adyen Dashboard, go to Developers > Webhooks
4. Test a webhook and get the error 

**Expected behavior**
Magento should be able to get the webhook and update order status based on response 

**Magento version**
[e.g. 2.4.3]

**Plugin version**
[e.g. 8.6.0]

**Additional context**
We find out that the problem is because HMAC key was not configured correctly. In version 8.6.0, we cannot change this key from the backend anymore. Instead of that, the plug in will get the key from Adyen automatically and update to Magento DB. 
When the plugin saves the HMAC key, it is not encrypted. But when it validates the key, it still decrypt the saved key. And this is the problem.

**Comment by Morerice** [comment]
Hi @tigrensolutions,

Thanks for opening this issue and also the related pull request!

Regards,
Jean
Adyen
