### ISSUE TITLE
[PW-7506] - Tests error

### ISSUE THREAD

**Issue by Nuranto** [Adyen/adyen-magento2#1739]
**Describe the bug**

When launching tests : ``` PHP Fatal error:  Uncaught Error: Class "Adyen\Payment\Tests\Unit\AbstractAdyenTestCase" not found in /var/www/html/vendor/adyen/module-payment/Test/Unit/Helper/AddressTest.php:20```

**To Reproduce**

`php -dmemory_limit=-1 vendor/bin/phpunit -c dev/tests/unit/phpunit.xml.dist`

**Expected behavior**

No errors.

**Additional informations**

All tests have a namespace starting with `Adyen\Payment\Tests`, but are in folder `Test` without `s`

**Magento version**
2.4.5

**Plugin version**
8.6.0

**Comment by Morerice** [comment]
Hi @Nuranto,

Thanks for opening this issue. For further information, could you try to run the tests using the same command that is being used in the `RUN Phpunit` step, in [this](https://github.com/Adyen/adyen-magento2/actions/runs/3106459163/jobs/5033366037) github action?

Thanks,
Jean
Adyen

**Comment by Nuranto** [comment]
Hi @Morerice 

Testing the extension individually surely works with those parameters, since your CI passes. 
It's running phpunit for the whole magento project that doesn't work.

**Comment by Morerice** [comment]
Hi @Nuranto,

If you have time could you verify the PR linked above? From our end we were able to run the tests from the Magento directory with the command you provided and the tests that failed were not related to our module.

Thanks,
Jean
Adyen

**Comment by Nuranto** [comment]
Hi @Morerice,

I confirm this PR solves the issue, thanks !
