### ISSUE TITLE
Syntax error into Model/Config/Backend/OrderStatus.php

### ISSUE THREAD

**Issue by paolobattistella** [Adyen/adyen-magento2#1740]
Syntax error into Model/Config/Backend/OrderStatus.php at line 67.

Before

`    
public function afterSave()
    {
        $value = $this->getValue();
        $adyenPaymentMethods = $this->paymentMethodsHelper->getAdyenPaymentMethods();

        foreach ($adyenPaymentMethods as $adyenPaymentMethod) {
            $this->configWriter->save(
                'payment/' . $adyenPaymentMethod . '/order_status',
                $value,
            );
        }

        return $this;
    }
`

After

`    
public function afterSave()
    {
        $value = $this->getValue();
        $adyenPaymentMethods = $this->paymentMethodsHelper->getAdyenPaymentMethods();

        foreach ($adyenPaymentMethods as $adyenPaymentMethod) {
            $this->configWriter->save(
                'payment/' . $adyenPaymentMethod . '/order_status',
                $value
            );
        }

        return $this;
    }
`

**Comment by Morerice** [comment]
Hi @paolobattistella,

Thanks for opening this issue. The highlighted syntax issue (',') will only throw a syntax error if a PHP version < 7.3. However, for our latest version of the module this 7.3 is the minimum version required.

Could you check your PHP version and also the module version you're currently on?

Thanks,
Jean
Adyen
