### ISSUE TITLE
HMAC verification always fails when API endpoing is used by the adyen backend troubleshooter which results in 401

### ISSUE THREAD

**Issue by kanevbg** [Adyen/adyen-magento2#1748]
**Describe the bug**
Troubleshooter gives false possitive for having issue. The module is logging "HMAC key validation failed" but this is happening only for requests from the troubleshooter. To be more specific in my case the troubleshooter uses REFUND event.

**To Reproduce**
Activate HMAC verification in adyen's magento module and go to the webhook troubleshooter from the adyen's back office.

**Expected behavior**
Troubleshooter shows success, no logs "HMAC key validation failed"

**Magento version**
2.3.7-p2

**Plugin version**
8.3.5

**Additional context**
https://www.adyen.help/hc/requests/3336712

**Comment by Morerice** [comment]
Hi @kanevbg,

Thanks for opening this issue. To clarify, are your webhooks on the test/live environment operational? Then when you attempt to test them from the Adyen Customer Area the error you mentioned is being displayed?

Thanks,
Jean
Adyen

**Comment by kanevbg** [comment]
Hello,

yes they are actually operational. The manual testing from the adyen backend succeeds too. What fails is the Adyen's automated troubleshooter, so it pops a error for the webhook telling you that something is wrong while there is no problem at all. That seems to be because it's not using the HMAC configuration while communicating or it's using wrong HMAC key.

**Comment by Morerice** [comment]
Hi @kanevbg,

Thanks for your reply. In that case this issue will be closed since it is not related to any functionality within this magento repository. I would recommend pursuing this in the zendesk ticket already opened with our support team to identify if there is an issue with the troubleshooter.

Thanks,
Jean
Adyen

**Comment by pmzandbergen** [comment]
This is still an issue with the Adyen troubleshooter. @kanevbg did you get any follow-up on the original ticket?

Adyen is promoting HMAC signatures which is a good thing! Too bad the troubleshooter itself gives troubles 🤡.
