### ISSUE TITLE
[PW-7348] - PHP8 compatibility

### ISSUE THREAD

**Issue by devetus** [Adyen/adyen-magento2#1765]
**Describe the bug**
Checkout in Safari mobile view creates an order but payment request errors out and the customer is not redirected to success page:

`AdyenLoggerTest.ERROR: Failed to reset reservedOrderId for guest shopperDeprecated Functionality: preg_match(): Passing null to parameter #2 ($subject) of type string is deprecated in /vendor/adyen/module-payment/Plugin/GuestPaymentInformationResetOrderId.php on line 68 [] {"uid":"6168ce4"}`

```
URL: /rest/default/V1/internal/adyen/orders/payment-status
"message": "Internal Error. Details are available in Magento log file. Report ID: webapi-6346ca7040238"
Status: 500
```

**To Reproduce**
Checkout in mobile Safari with credit card payment.

**Magento version**
2.4.5-p1

**Plugin version**
8.7.0

**Comment by Morerice** [comment]
Hi @devetus,

Thanks for opening this issue. We have created an internal ticket to go over all the uses of the `preg_match` within our module and ensure that the second argument is never set to null.

Regards,
Jean
Adyen
