### ISSUE TITLE
dfSet is not defined.

### ISSUE THREAD

**Issue by kuwiano** [Adyen/adyen-magento2#177]
Hello there,

we just updated to 2.1.1 (because of #170 / #171) and now we are experience this error on checkout:

![image](https://user-images.githubusercontent.com/3833980/29570540-08a1c924-8757-11e7-8f8a-1301320d7edb.png)
Bundleling is activated.
This also completely block the checkout. Got any ideas?

Regards,

Dominik

**Comment by rikterbeek** [comment]
Hi @kuwiano,

We were not able to reproduce this problem. We have renamed the file from df to df.min
https://github.com/Adyen/adyen-magento2/pull/171/files
Could you check on your end what javascript is loaded in could be that you need to re-compile and clean your cache.


Regards,
Rik
Adyen

**Comment by kuwiano** [comment]
Hi @rikterbeek,

Error happens right here (with break on dom exception in chrome):

![image](https://user-images.githubusercontent.com/3833980/29604592-50919c1e-87e8-11e7-822f-5c94cd907539.png)

I already deleted pub/static/* and var/view_preprocessed/* and recompiled the entire project but the error still persists.

Regards,

Dominik

**Comment by rikterbeek** [comment]
Hi @kuwiano,

Could you check if the javascript file Adyen_Payment/js/view/payment/df.min is loaded into your system ?
This should be done by this line:
https://github.com/Adyen/adyen-magento2/blob/develop/view/frontend/requirejs-config.js#L10

Regards,
Rik
Adyen

**Comment by ptraing** [comment]
Hi @rikterbeek and @kuwiano,

I have the same error and found how to reproduce the bug.
To get this error you have to go into production mode, when we are in developer mode the error does not appear and the file df.min.js is loaded.
However, in developer mode, the df.min.js file is not loaded ...
Now I do not know how to make js files loaded in both modes.

Best regards,
Philippe

**Comment by kuwiano** [comment]
Hi @rikterbeek,

File is a found at this path:
```vendor/adyen/module-payment/view/frontend/web/js/view/payment/df.min.js```

In ```vendor/adyen/module-payment/view/frontend/requirejs-config.js``` I have this exact line:
``` 'adyen/df' : 'Adyen_Payment/js/view/payment/df.min'```

@ptraing our shop is in production mode.

Regards,
Dominik

**Comment by kuwiano** [comment]
Hi @rikterbeek,

without bundleling it works.

Regards,
Dominik

**Comment by fahu** [comment]
I can confirm this issue for Magento 2.1.8.
Mode: Production
Merging: Enabled
Bundling: Enabled

**Comment by boldbart** [comment]
We have the same issue on Magento 2.1.8, Adyen 2.1.1.
Mode: Production
Bundling: Enabled
Merging: Disabled

**Comment by lancergr** [comment]
Hi @fahu @boldbart @kuwiano @ptraing 

Thanks for reporting this! 
This fix should resolve this issue [c2aed95]

Could you let me know if it works for you?

Best Regards,
Giorgos
Adyen

**Comment by ptraing** [comment]
Hi @lancergr 

Thanks you it works !

Best Regards,
Philippe

**Comment by fahu** [comment]
@lancergr Thanks for your fast bug fix. I can confirm that the module is now working as it should. I really appreciate that you react so fast to troubles. However I really would wish a better quality management for the adyen magento module. The last couple of issues that happened could have been easily detected with basic testing. 

Best regards
Fabian

**Comment by lancergr** [comment]
Hi @fahu 

Glad to hear that it works for your case as well. This one was tricky since depending on the bundling/merging/minifying combination it would behave differently on different parts of the module.
We are busy on setting up a more automated way for build verification testing and hopefully we have this issues minimised in future!


Kind Regards,
Giorgos
Adyen

**Comment by fahu** [comment]
Hi @lancergr !

Yeah I understand that it's harder to test since these different configuration options. Good to hear that you are working on setting up a better testing environment.

Best regards
Fabian

**Comment by kuwiano** [comment]
Hi @lancergr,

works like a charm! Thanks for reacting so fast.

Best regards,
Dominik

**Comment by fahu** [comment]
Hi @lancergr when do you plan to release a new version containing this fix?

**Comment by lancergr** [comment]
Hi @fahu, you can expect it on the upcoming days!

Regards,
Giorgos
Adyen
