### ISSUE TITLE
Missing payment icon - critical exception breaks checkout

### ISSUE THREAD

**Issue by devetus** [Adyen/adyen-magento2#1778]
Checkout page crashes for a logged in customer because of a missing icon asset `mc_applepay_small.png`. Probably all Apple Pay variants are affected.

**Magento version**
2.4.5-p1

**Plugin version**
8.7.0

**Error log**
==> system.log <==
[2022-10-19T14:35:56.623693+00:00] report.CRITICAL: Magento\Framework\View\Asset\File\NotFoundException: Unable to resolve the source file for 'frontend/handh/cbii/en_GB/Adyen_Payment/images/logos/mc_applepay_small.png' in vendor/magento/framework/View/Asset/File.php:161
Stack trace:
#0 vendor/adyen/module-payment/Helper/Data.php(1654): Magento\Framework\View\Asset\File->getSourceFile()
#1 generated/code/Adyen/Payment/Helper/Data/Interceptor.php(608): Adyen\Payment\Helper\Data->getVariantIcon()
#2 vendor/adyen/module-payment/Model/Ui/AdyenUiComponentProvider.php(47): Adyen\Payment\Helper\Data\Interceptor->getVariantIcon()
#3 vendor/adyen/module-payment/Model/Ui/TokenUiComponentProvider.php(32): Adyen\Payment\Model\Ui\AdyenUiComponentProvider->getCardComponentForToken()
#4 vendor/magento/module-vault/Model/Ui/TokensConfigProvider.php(87): Adyen\Payment\Model\Ui\TokenUiComponentProvider->getComponentForToken()
#5 vendor/magento/module-checkout/Model/CompositeConfigProvider.php(39): Magento\Vault\Model\Ui\TokensConfigProvider->getConfig()
#6 vendor/magento/module-checkout/Block/Onepage.php(106): Magento\Checkout\Model\CompositeConfigProvider->getConfig()
#7 vendor/magento/module-checkout/Block/Onepage.php(128): Magento\Checkout\Block\Onepage->getCheckoutConfig()
#8 /var/view_preprocessed/pub/static/vendor/magento/module-checkout/view/frontend/templates/onepage.phtml(6): Magento\Checkout\Block\Onepage->getSerializedCheckoutConfig()

**Comment by Morerice** [comment]
Hi @devetus,

Thanks for opening this issue. Could you please find the `vault_payment_token` table and check if there is an entry where the `details` field contains `mc_applepay`?

Thanks,
Jean
Adyen

**Comment by devetus** [comment]
Hi @Morerice, yes we do have few records like that. Please note this is in Test mode so no live hashes below:
<img width="1103" alt="image" src="https://user-images.githubusercontent.com/45761712/197150356-5d49ec74-8be8-41f7-b1cd-c2e5fc453fd0.png">
We were testing latest module in our staging environment.

**Comment by Morerice** [comment]
Thanks for your quick reply,

In that case we know the cause of the issue. However, based on the functionality we have at this time and our tests, it shouldn't be possible for now to create a token trough applepay.

Were there any modifications to [this class](https://github.com/Adyen/adyen-magento2/blob/8.7.0/Helper/PaymentMethods/ApplePayPaymentMethod.php) from your end?

Thanks,
Jean
Adyen

**Comment by devetus** [comment]
No modifications to this area from our end. We were turning tokenization options on and off for Alternative Payment Methods config. 
One thing to note is that we keep payment methods config set on website scope level as we run different websites and Adyen payments are only available on one of them.

**Comment by Morerice** [comment]
Ok, in that case I'm not sure how a token with `mc_applepay` was created. Another question, could you please check the value in the `core_config_data` of the following path? `payment/adyen_hpp/tokenized_payment_methods`

Thanks,
Jean
Adyen

**Comment by devetus** [comment]
Currently it is set as below 
<img width="721" alt="image" src="https://user-images.githubusercontent.com/45761712/197158529-77fb5a01-fb61-4fbe-91ef-3ae6ef9fe0ba.png">
We had all options selected before, including Paypal and SEPA direct debits although we don't use them or have active in Adyen dashboard. Since the problem started with that particular user account we disabled Alternative Payment Methods tokenization completely and then switch to GooglePay tokenisation only but the template was still looking for mc_applepay icon. Basically tried different configuration options and run tests with various sandbox credit cards, but not sure why `mc_applepay` record got created.

**Comment by Morerice** [comment]
All the entries requested show the expected data. So as you said the question is how those `mc_applepay` entries got created. Could we maybe shift this conversation trough our support team, by contacting support@adyen.com? Please include a link to this issue in your message

This would enable us to share some pspReferences of the transactions that created these tokens so that maybe we can identify if it is an adyen module related issue or if it is something else.

Thanks,
Jean
Adyen

**Comment by devetus** [comment]
Sure, I've created support request #3381591 and sent more details including PSP
Thanks, Michal

**Comment by Morerice** [comment]
Hi,

Based on the conversation in the internal ticket, this issue was caused by enabling the `enableRecurring` toggle on Adyen customer area. This is a toggle that is currently deprecated and will be removed in the near future. To disable such option, login to the Adyen Customer Area, go to **Settings** > **Merchant Settings** and deselect this toggle.

![enableRecurring](https://user-images.githubusercontent.com/11156828/199698772-c6e460f8-0e29-4533-989b-6cb3488e11e4.png)

Regards,
Jean
Adyen
