### ISSUE TITLE
Adyen alternative payment methods doesn't adhere to Magento best practices for payment methods

### ISSUE THREAD

**Issue by GamesmenJordan** [Adyen/adyen-magento2#1791]
**Describe the bug**
Adyen alternative payment methods (AAPM) don't adhere to common best practices for Magento payment methods, because AAPM are all configured under a single "adyen_hpp" payment method most modules treat them as the same payment method.

This is undesirable behaviour, firstly most modules will expect that each type of payment method has a unique payment method identifier.

This means that it is significantly more likely to cause incompatibility (eg. we required OneStepCheckout.com to specifically implement support for AAPM)

Another scenario we have encountered is that we have difficulty adhering to conditions in agreements with payment method providers such as Afterpay and Zip regarding specific categories of products that are not permitted to be purchased using their payment method. 

All modules that have rules regarding payment method restrictions work on the assumption that the payment method identifier is unique to a single payment method, because this is not the case we only have the option to disable ALL alternative payment methods including PayPal, Google Pay, Apple Pay, etc. Extensive reworking of such modules would be required to support AAPM's non-standard way of handling payment methods.

In the same vein, modules that provide fraud checks can't be instructed to perform checks on Google Pay and Apple Pay but ignore PayPal.

**Expected behavior**
All payment methods should have unique payment method identifiers per the standard best practice for payment method providers in Magento.

**Magento version**
All

**Plugin version**
All current

**Comment by dimitriBouteille** [comment]
Good news :tada:

**Comment by GamesmenJordan** [comment]
> Hi @GamesmenJordan,
> 
> Thanks for opening this issue and providing great detail. Indeed, we agree with the points you are making here and currently looking into changing the way payment methods within our module are implemented, to adhere with the Magento best practices.
> 
> However, apart from requiring a big effort, this is a change that will require a major release. Currently, we are planning such a release sometime between Q1 and Q2 2023. Please keep following this issue for any questions/updates we may have.
> 
> Thanks, Jean Adyen

You can not believe how relieved hearing this makes me, it has been **the** biggest issue we have with the module and was almost a deal breaker on deciding to look elsewhere.

**Comment by speedupmate** [comment]
> Hi @GamesmenJordan,

> However, apart from requiring a big effort, this is a change that will require a major release. Currently, we are planning such a release sometime between Q1 and Q2 2023. Please keep following this issue for any questions/updates we may have.

wow 👯‍♀️  finally , after all this extension lifetime :D the change for this is actually not so big at all. You have to change two js methods and prob one plugin to backend to detect the code to achieve the proper payment method code logic. Might still need a major release from your side.

**Comment by aschrammel** [comment]
Hi @speedupmate,

As we are running into issues with the alternative payment methods as well currently on version 8.20.1, we stumbled upon this issue.
In your last comment you wrote following:

> the change for this is actually not so big at all. You have to change two js methods and prob one plugin to backend to detect the code to achieve the proper payment method code logic.

Therefore, wanted to ask, if you have a working workaround for that which you maybe could share?

@Morerice you mentioned a planned release between Q1 and Q2 2023. What's the status on that meanwhile in Q3? 😄

**Comment by candemiralp** [comment]
Hello all,

Closing this issue as `Separate Payment Methods` project has been released with V9 of the plugin. Please feel free to raise your concerns on a new Github issue if there are any.

Best regards,
Can
