### ISSUE TITLE
graphQl - Add checkout_frontend_region config

### ISSUE THREAD

**Issue by dimitriBouteille** [Adyen/adyen-magento2#1795]
Is it possible to add this configuration `payment/adyen_abstract/checkout_frontend_region` in the graphQl ?

Currently it is not possible to know which [environment](https://docs.adyen.com/online-payments/web-drop-in#test-and-go-live) should be used:(

**Comment by Morerice** [comment]
Hi @dimitriBouteille,

Apologies for the delay. Just to be sure that we are on the same page, are you referring to adding the `checkout_frontend_region` config to [this argument](https://github.com/Adyen/adyen-magento2/blob/b0571b03f3ccaee53dbcd0af0c97325cbf8a8a6d/etc/graphql/di.xml#L16)?

Regards,
Jean
Adyen

**Comment by dimitriBouteille** [comment]
Exactly:) 

```xml
<item name="adyen_checkout_frontend_region" xsi:type="string">payment/adyen_abstract/checkout_frontend_region</item>
```
