### ISSUE TITLE
Type hinting error (array) - Helper/Webhook::updateOrderPaymentWithAdyenAttributes 

### ISSUE THREAD

**Issue by saimwebdev** [Adyen/adyen-magento2#1821]
Type hinting error on **$additionalData** parameter in _updateOrderPaymentWithAdyenAttributes_ method inside Helper/Webhook.php on line 434
This happens because **$additionalData** could be a string, as declared in _updateAdyenAttributes_ method on line 407:
`
$additionalData = !empty($notification->getAdditionalData()) ? $this->serializer->unserialize(
    $notification->getAdditionalData()
) : "";
`

**Expected fix**
From
`
$additionalData = !empty($notification->getAdditionalData()) ? $this->serializer->unserialize(
    $notification->getAdditionalData()
) : "";
`
to
`
$additionalData = !empty($notification->getAdditionalData()) ? $this->serializer->unserialize(
    $notification->getAdditionalData()
) : [];
`

**Magento version**
2.4.4

**Plugin version**
8.9

**Comment by Morerice** [comment]
Hi @saimwebdev,

Thanks for opening this issue. We are currently reviewing https://github.com/Adyen/adyen-magento2/pull/1815, which should solve this issue. This PR should be live on the next release, which is due next week.

Thanks,
Jean
Adyen
