### ISSUE TITLE
No support for authorization token when payment return URL is involved

### ISSUE THREAD

**Issue by AndrewKMoses** [Adyen/adyen-magento2#1834]
**Describe the bug**
We have a headless integration to Magento. We use Graphql to communicate with Magento. For customer login we use [generateCustomerToken](https://devdocs.magento.com/guides/v2.4/graphql/mutations/generate-customer-token.html) and [authorization tokens](https://devdocs.magento.com/guides/v2.4/graphql/authorization-tokens.html#authorization-tokens).

As far as I can see, this is not supported as soon as the Payment Return URL (/adyen/process/result) is included for the payment method since that method is based on using the session to find the quote. In our case we do not use the session as we use authorization tokens as mentioned above.

Our specific issue can be seen [here](https://github.com/Adyen/adyen-magento2/blob/develop/Controller/Process/Result.php#L195). After placing the order, the customer recieves his old cart when calling [createEmptyCart](https://devdocs.magento.com/guides/v2.4/graphql/mutations/create-empty-cart.html).

We were previously using module version 6.7.2 where this issue was not visible and have now upgraded to 8.5.0 where it is an issue.

We are running Magento version 2.4.2-p2.

**To Reproduce**
1. Login user using Graphql generateCustomerToken
2. Create a cart using createEmptyCart
3. Place order with payment method where redirect is involved (i.e. 3DS card)
4. You are now redirected to /adyen/process/result and onwards your success page
5. Create a new cart using createEmptyCart and you will see that your old cart is given back to you

**Expected behavior**
The quote should be inaktive after placing order

**Magento version**
2.4.2-p2

**Plugin version**
8.5.0

**Comment by peterojo** [comment]
Hi @AndrewKMoses thanks for reaching out! We have added the option for headless integrations to send the `returnUrl` that you would like to use for the payment (#1630)
Could you please test and see if this works for you?

**Comment by AndrewKMoses** [comment]
That might be an idea. However, which types of HTTP requests should we expect to that endpoint? The comment [here](https://github.com/Adyen/adyen-magento2/blob/develop/Controller/Process/Result.php#L171) says both GET and POST while the description [here](https://docs.adyen.com/online-payments/web-components/integrated-before-5-0-0#handling-redirects-v67) says GET.

If it's only GET it's easier to handle, but a POST to a PWA is more complicated.

**Comment by Morerice** [comment]
Hi @AndrewKMoses,

In these cases it is always advised to follow the official documentation, so the `returnUrl` will only be accessed with a GET.

I'm closing this issue since it seems that @peterojo has already provided a solution. If however there is still a problem with this, feel free to comment on this issue again and we'll give it a look.

Thanks,
Jean
Adyen

**Comment by AndrewKMoses** [comment]
Hi

So I've tried the solution with `returnUrl` but the session is still not resolved properly. It seems Magento does not resolve the session for controllers (which Result.php is). It seems it only works for Web API endpoints.

How come the controller uses the session when the merchantReference (order increment ID) is included in the query to the controller? Can't we use it to resolve the quote?

**Comment by AndrewKMoses** [comment]
So we ended up overriding `Result.php::execute` like this

`
    public function execute()
    {
        // This controller does not support resolving session from authorization header token.
        // We resolve the token and correct the session data here so that the parent function
        // works as intended (since it based on session data).
        $authorization = $this->getRequest()->getHeader('AUTHORIZATION');
        $token = $authorization ? explode('bearer ', $authorization)[1] ?? null : null;

        if ($token) {
            $tokenFactory = $this->tokenFactory->create();

            $tokenFactory->loadByToken($token); // Load token factory with customer data
            $customerId = $tokenFactory->getCustomerId();
            $customer = $this->customerRepository->getById($customerId);
            $quote = $this->cartRepository->getActiveForCustomer($customerId);

            $this->session->replaceQuote($quote);
            $this->session->setCustomerData($customer);
            $this->session->setCustomerGroupId($customer->getGroupId());
        }

        return parent::execute();
    }
`

Sorry can't get the code to format correctly.
