### ISSUE TITLE
[PW-7500] - Can`t save multiple installments for one threshold

### ISSUE THREAD

**Issue by Stereck** [Adyen/adyen-magento2#1840]
**Describe the bug**
Adyen offers to configure multiple installment rules, for a certain threshold, card type and number of installments.
If there is more than one rule that is matching for a certain credit card, the user can pick the desired number of installments in the checkout with an dropdown.

Unfortunately you cannot save multiple installment rules that have the same card type and min threshold.
This is because this line would always overwrite multiple rules, when the module configuration is saved in the backend.
https://github.com/Adyen/adyen-magento2/blob/develop/Model/Config/Backend/Installments.php#L80 

**To Reproduce**
1. Go to Backend -> Store -> Configuration -> Sales -> Payment Methods -> Adyen Payments -> Configure Payment Methods -> Card Payments -> Installments Setup
2. Create 2 new installment rules like
- 10 (Minimum Amount) 2 (Number of Installments) "Visa"
- 10 (Minimum Amount) 3 (Number of Installments) "Visa"
3. Save Configuration
4. Open the same configuration to see that only one of aboves rules is saved.

**Expected behavior**
All rules should be saved (even if they are using the same card type and minimum amount.

**Magento version**
2.4.5 but not limited to it...

**Plugin version**
8.9.0 but same issue in older versions...

**Additional context**
I've checked the Adyen Documentation and it should be possible to offer the user a choice of the number of installments.
It also works when I manually push the settings to the database.
It's just that this code prevents this config from being saved.
https://github.com/Adyen/adyen-magento2/blob/develop/Model/Config/Backend/Installments.php#L80
Looks like a defect and no purpose.

**Comment by Morerice** [comment]
Hi @Stereck,

Thanks for creating this issue and including all these details. I've created an internal ticket for us to investigate this issue.

Regards,
Jean
Adyen
