### ISSUE TITLE
Magento 2.2 compatibility

### ISSUE THREAD

**Issue by davidverholen** [Adyen/adyen-magento2#185]
Hi, just wanted to ask if you are already working on magento 2.2 testing? The current release is not installable with magento 2.2 rc so it's not possible to start testing against it when the adyen payment extension is used.

**Comment by davidverholen** [comment]
ok I see you already removed the restrictions in the develop branch.

**Comment by rikterbeek** [comment]
HI @davidverholen,

Don't see any issues thy out our develop version and let us know if you see any issues.

Regards,
Rik
Adyen
