### ISSUE TITLE
Add form-action policy into csp whitelist

### ISSUE THREAD

**Issue by Nuranto** [Adyen/adyen-magento2#1861]
Hello,

We are (trying to) implementing a frontend react implementation of our M2 checkout. And we got this issue :  
```
Refused to send form data to 'https://pal-test.adyen.com/threeds2simulator/acs/startMethod.shtml' because it violates the following Content Security Policy directive: "form-action 'self'
```

It would be quite simple to add the csp_whitelist in a module of our own, but I guess it's be better if that stands in your module's csp_whitelist

**Comment by candemiralp** [comment]
Hello @Nuranto,

Thank you for your enhancement suggestion to the repository. A PR has been created for this enhancement by @Marwaa92 and will be released soon.

Best Regards,
Can
