### ISSUE TITLE
[PW-7618] - Virtual orders and payment links

### ISSUE THREAD

**Issue by dronerdk** [Adyen/adyen-magento2#1873]
Hello

We have an issue when a admin creates an order with only a virtuel product and selects Adyen payment link.
This error will appear when trying to submit order:
Error: Call to a member function getStreet() on null in /var/www/droner.dk/public_html/vendor/adyen/module-payment/Gateway/Request/CheckoutDataBuilder.php:241
Stack trace:

M2: 2.4.3-p3
Adyen: 8.11.0

**Comment by Morerice** [comment]
Hi @dronerdk,

Thanks for opening this issue and providing the error. An internal ticket has been created to checkout this issue.

Regards,
Jean
Adyen
