### ISSUE TITLE
Open Invoice methods broken since 8.9.0

### ISSUE THREAD

**Issue by xsarus-academy** [Adyen/adyen-magento2#1904]
**Describe the bug**
Since version 8.9.0 Open Invoice Methods like Afterpay are not working anymore, this is because the following change in the file Observer/AdyenHppDataAssignObserver.php:

```php
$paymentInfo->unsAdditionalInformation('brand_code');
```

This has effect on Gateway/Request/CheckoutDataBuilder.php#L121 where brandCode is expected to check if this is a open invoice method, but due to the change in the observer, brandCode will be empty.

**To Reproduce**
- Place a Magento order with for example Afterpay. 
- The error message you will see is: Invalid open invoice request.
- Inspect the adyen/info.log and notice that the lineItems element is missing in the request.

**Expected behavior**
Brand code will not be unset and is available for checking in the CheckoutDataBuilder class.

**Magento version**
2.4.4

**Plugin version**
8.9.x, 8.10.x 8.11.x, 8.12.x

**Comment by Morerice** [comment]
Hi @xsarus-academy,

Thanks for opening this issue. We have already identified this problem and added the fix in https://github.com/Adyen/adyen-magento2/pull/1903.

Regards,
Jean
Adyen
