### ISSUE TITLE
Update magento Marketplace

### ISSUE THREAD

**Issue by djino87** [Adyen/adyen-magento2#1906]
Hi,

Could you update the magento marketplace with the new Adyen version please ? Indeed, I have the next message when I try to deploy : 

" [Exception] Higher matching version 8.12.0 of adyen/module-payment was found in public repository packagist.org than 8.11.1 in private https://repo.magento.com. Public package might've been taken over by a malicious entity,  please investigate and update package requirement to match the version from the private repository"

Thanks in advance

**Comment by candemiralp** [comment]
Hello @djino87,

Thanks for reaching out to us. Version 8.12.0 of the `adyen/module-payment ` is on the manual technical tests phase. It will be on the market after the tests.

Best Regards,
Can
