### ISSUE TITLE
Request for New Payment Methods: BACS and Samsung Pay

### ISSUE THREAD

**Issue by Radgon1212** [Adyen/adyen-magento2#1915]
Request for supporting BACS Direct Debit and Samsung Pay on Magento 2.

**Comment by Morerice** [comment]
Hi @Radgon1212,

Thanks for opening this issue. I have successfully managed to process a payment using BACS on my magento instance so this payment method should already be operational. Regarding Samsung Pay, I have created an internal ticket to add this payment method.

Regards,
Jean
Adyen

**Comment by candemiralp** [comment]
Hello @Radgon1212,

Thank you again for this issue. Samsung Pay is still not supported by the Adyen Web components library. Therefore, it is not possible to support it via plugin. Once it is available, we will update the docs.

Best Regards,
Can
