### ISSUE TITLE
[PW-7948] Webhook Notifications cronjob fails to handle REPORT_AVAILABLE notifications

### ISSUE THREAD

**Issue by enl** [Adyen/adyen-magento2#1920]
**Describe the bug**

When  `\Adyen\Payment\Cron\WebhookProcessor::execute` cron job tries to handle `REPORT_AVAILABLE` notification, it fails with TypeError:

```
Cron Job adyen_payment_process_notification has an error: Adyen\Payment\Helper\Order::getOrderByIncrementId(): Argument #1 ($incrementId) must be of type string, null given, called in /vendor/adyen/module-payment/Helper/Webhook.php on line 135.
```

This is happening because notification has empty `merchant_reference` field, which in turns means we call with it:

```
\Adyen\Payment\Helper\Webhook::processNotification(Notification $notification)
```

And this function calls

```
// Because $notification->getMerchantReference() returns null
\Adyen\Payment\Helper\Order::getOrderByIncrementId(null)
```

But the function expected `string`.

**To Reproduce**
1. Enable REPORT_AVAILABLE notifications
2. Wait for it to be received
3. Check cron job logs for errors

**Expected behavior**

These notification are either handled separately or ignored by the web hook.

**Magento version**
2.4.5-p1

**Plugin version**
8.11.1

**Comment by candemiralp** [comment]
Hello @enl,

Thank you for raising this issue. We created an internal ticket for investigation and fix. 

Best Regards,
Can

**Comment by enl** [comment]
Meanwhile, this is how I patched it in our project. I'm not entirely sure, what Magento is supposed to do with these notifications, so I'm not making a proper PR out of it :)

```
--- a/Model/ResourceModel/Notification/Collection.php
+++ b/Model/ResourceModel/Notification/Collection.php
@@ -58,6 +58,7 @@
         $this->addFieldToFilter('processing', 0);
         $this->addFieldToFilter('created_at', $dateRange);
         $this->addFieldToFilter('error_count', ['lt' => \Adyen\Payment\Model\Notification::MAX_ERROR_COUNT]);
+        $this->addFieldToFilter('event_code', ['neq' => \Adyen\Payment\Model\Notification::REPORT_AVAILABLE]);

         // Process the notifications in ascending order by creation date and event_code
         $this->getSelect()->order('created_at ASC')->order('event_code ASC');
```

**Comment by candemiralp** [comment]
Hello @enl,

Thank you for the proposed solution. Indeed, as you mentioned some of the notifications are not aimed to be used in Magento. We will try to implement an abstract solution for this issue. Because, it could be any other unsupported webhook notification like `REPORT_AVAILABLE`.

Best Regards,
Can
