### ISSUE TITLE
Error: LIVE: <shop> is NOT accepting Notifications

### ISSUE THREAD

**Issue by kuwiano** [Adyen/adyen-magento2#193]
Hi, 

currently we sometimes get the mentioned error. Adyen responses by sending us a email with this exact information. After a few minutes we get another email saying everything is alright again.

Do you have any information on this?

**Comment by lancergr** [comment]
Hi @kuwiano 

This is sent when an endpoint that has been configured in Server communication settings doesn't accept notification(s).
The second e-mail means that the endpoint is now accepting notifications normally.

This can happen when your site has some downtime and is not reachable from Adyen.

Regards,
Giorgos
Adyen
