### ISSUE TITLE
Not all active alternative payment methods are received

### ISSUE THREAD

**Issue by DanieliMi** [Adyen/adyen-magento2#1931]
**Describe the bug**
I am not sure if this belongs here or rather as a support request. When going to the checkout not all activated alternative payment methods are shown. We recently upgraded from 8.2.5 to 8.10.0 and believe this issue was introduced by this update. Updating to the latest version 8.14.0 does not help. In the checkout Klarna, Giropay and ApplePay should be shown but they are missing form the available payment methods. Debugging into `\Adyen\Payment\Helper\PaymentMethods::fetchPaymentMethods` the methods are already missing in the response from `\Adyen\Payment\Helper\PaymentMethods::getPaymentMethodsResponse`. Interestingly enough on our production system it works in chrome but going the checkout in firefox the methods are not display and in the test environment it works in neither browser.

**To Reproduce**
1. Go to the checkout

**Expected behavior**
Alternative payment methods like Klarna, Giropay or ApplePay are displayed.

**Actual behavior**
Alternative payment methods like Klarna, Giropay or ApplePay are not displayed.

**Magento version**
2.4.5-p1

**Plugin version**
8.14.0

**Desktop (please complete the following information):**
 - Ubuntu
 - chrome, firefox

**Comment by Morerice** [comment]
Hi @DanieliMi,

Thanks for opening this issue. Based on the fact that the expected payment methods are already not being returned in the response from `\Adyen\Payment\Helper\PaymentMethods::getPaymentMethodsResponse` it seems that this is not an issue related to the plugin. However at this point we can't be sure.

My suggestion would be to open a support request by sending a mail to support@adyen.com and including a link to this github issue. If eventually we identify an issue within the plugin, we will update this issue with the relevant information and fix.

Regards,
Jean
Adyen

**Comment by DanieliMi** [comment]
The problem was a wrong country being sent. In `\Adyen\Payment\Helper\PaymentMethods::getCurrentCountryCode` the country was retrieved from `$this->getQuote()->getBillingAddress()->getCountry()` and there was the false value stored. Setting the country_code fixed for the payment method (`\Adyen\Payment\Helper\Data::getAdyenHppConfigData`) solved the issue.
