### ISSUE TITLE
Fatal error: Uncaught Error: Class 'Adyen\Client' not found 

### ISSUE THREAD

**Issue by Mage2you** [Adyen/adyen-magento2#194]
Please check the following error in magento2 checkout upon clicking place order.

<br />
<b>Fatal error</b>:  Uncaught Error: Class 'Adyen\Client' not found in /home/techstag/public_html/dto/app/code/Adyen/Payment/Gateway/Http/Client/TransactionAuthorization.php:67
Stack trace:
#0 /home/techstag/public_html/dto/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(93): Adyen\Payment\Gateway\Http\Client\TransactionAuthorization-&gt;__construct(Object(Magento\Framework\Model\Context), Object(Magento\Framework\Encryption\Encryptor), Object(Adyen\Payment\Helper\Data), Object(Adyen\Payment\Logger\AdyenLogger), Object(Adyen\Payment\Model\RecurringType), Array)
#1 /home/techstag/public_html/dto/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(89): Magento\Framework\ObjectManager\Factory\AbstractFactory-&gt;createObject('Adyen\\Payment\\G...', Array)
#2 /home/techstag/public_html/dto/vendor/magento/framework/ObjectManager/ObjectManager.php(71): Magento\Framework\ObjectManager\Factory\Dynamic\Developer-&gt;create('Adyen\\Payment\\G...')
#3 /home/techstag/public_html/dto/vendor/magento/framework/ObjectM in <b>/home/techstag/public_html/dto/app/code/Adyen/Payment/Gateway/Http/Client/TransactionAuthorization.php</b> on line <b>67</b><br />
{"messages":{"error":[{"code":500,"message":"Server internal error. See details in report api\/658357738081"}]}}

**Comment by lancergr** [comment]
@Mage2you , the fact that Adyen\Client is not found means that the classes are not autoloaded.
By running composer require, you should have the php-api-library placed under vendor/adyen folder? Do you have this in your Magento?

Regards
Giorgos
Adyen

**Comment by Mage2you** [comment]
No, I don’t see adyen folder in my vendor directory.

Initially I installed the extension manually without composer and then for when this problem occurred I tried using composer require command.

Thanks.

--
Regards,
Sudhanshu Soni

**Comment by lancergr** [comment]
Hi @Mage2you 

How did you installed the extension manually?
Could you copy paste the command line output (including the composer command)?

Regards,
Giorgos
Adyen

**Comment by Mage2you** [comment]
Hello,

Below is the output of composer command.

---------------------------------------------------------------------------------------------------------

composer require adyen/module-payment
Using version ^2.1 for adyen/module-payment
./composer.json has been created
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 4 installs, 0 updates, 0 removals
  - Installing psr/log (1.0.2): Downloading (100%)
  - Installing monolog/monolog (1.23.0): Downloading (100%)
  - Installing adyen/php-api-library (1.3.0): Downloading (100%)
  - Installing adyen/module-payment (2.1.2): Downloading (100%)
monolog/monolog suggests installing aws/aws-sdk-php (Allow sending log messages to AWS services like DynamoDB)
monolog/monolog suggests installing doctrine/couchdb (Allow sending log messages to a CouchDB server)
monolog/monolog suggests installing ext-amqp (Allow sending log messages to an AMQP server (1.0+ required))
monolog/monolog suggests installing ext-mongo (Allow sending log messages to a MongoDB server)
monolog/monolog suggests installing graylog2/gelf-php (Allow sending log messages to a GrayLog2 server)
monolog/monolog suggests installing mongodb/mongodb (Allow sending log messages to a MongoDB server via PHP Driver)
monolog/monolog suggests installing php-amqplib/php-amqplib (Allow sending log messages to an AMQP server using php-amqplib)
monolog/monolog suggests installing php-console/php-console (Allow sending log messages to Google Chrome)
monolog/monolog suggests installing rollbar/rollbar (Allow sending log messages to Rollbar)
monolog/monolog suggests installing ruflin/elastica (Allow sending log messages to an Elastic Search server)
monolog/monolog suggests installing sentry/sentry (Allow sending log messages to a Sentry server)
Writing lock file
Generating autoload files

---------------------------------------------------------------------------------------------------------

Thanks.
--
Regards,
Sudhanshu Soni

**Comment by lancergr** [comment]
Hi @Mage2you 

How did you install Magento? It seems that you don't have a composer.json in your Magento 2.
http://devdocs.magento.com/guides/v2.0/extension-dev-guide/build/composer-integration.html
https://github.com/magento/magento2/blob/2.2-develop/composer.json

You first need to have the composer.json and all its autoloader in place in order to install the plugin properly.

Regards,
Giorgos
Adyen
