### ISSUE TITLE
[PW-8344] APIKeyMessage useless message 

### ISSUE THREAD

**Issue by maaarghk** [Adyen/adyen-magento2#1947]
Hi,

[`APIKeyMessage::isDisplayed()`](https://github.com/Adyen/adyen-magento2/blob/8.14.0/AdminMessage/APIKeyMessage.php#L88) is displaying a message about API key missing for blank web service user. This is because #1868 incorrectly [removed](https://github.com/Adyen/adyen-magento2/commit/a22665308150ec6df94b58a36143500523a3e7c8#diff-0f03b03fb9228457435edaea538f847b2db3838d09f8af34ba72380d9b33d4aaL79) the condition that `getWsUsername()` shouldn't be empty.

The quick fix is to reinstate the `!empty` check to stop default config throwing errors where store views are configured properly, but the non-lazy fix is probably to add one message per store view.

cc: @candemiralp

cheers.

**Comment by Morerice** [comment]
Hi @maaarghk,

Thanks for opening this issue. Could you please add some steps to reproduce the issue?

Thanks,
Jean
Adyen

**Comment by maaarghk** [comment]
log in to admin on a site where neither the ws username or API key is filled out in default scope config - see a message about API key being required. 

fill in API key and ws username on store config. continue to see message.

**Comment by Seppo-Konttinen-Solteq** [comment]
@Morerice hi. I think I created duplicate for this issue https://github.com/Adyen/adyen-magento2/issues/1999

There are some more info, screenshots and steps if those help. Should I close my issue as duplicate tho?

**Comment by candemiralp** [comment]
Hello @maaarghk,

If those information is missing, plugin creates a system message with severity `Critical`. Even if you fill out those information, you will see the notification unless you read that system message or mark as read/remove it from the system notifications.

Best Regards,
Can

**Comment by candemiralp** [comment]
@hello @Seppo-Konttinen-Solteq,

Thank you for mentioning the details in the duplicate issue. I would like to recap. Basically, Adyen module shouldn't show that exception if any of the Adyen payment methods is being used for that store/website. I will discuss that idea with our product manager and inform you afterwards.

Best Regards,
Can

**Comment by maaarghk** [comment]
Previously, it would only show the message if you filled in WS Username field, but now it always shows it. But it only checks default scope, so on a multi store site where there is a different config defined at store scope, the message is incorrect. 

`!empty($this->adyenHelper->getWsUsername()) && empty($this->adyenHelper->getAPIKey())` was replaced with `$isApiKeyMissing`, but the definition of `isApiKeyMissing` is `empty($this->adyenHelper->getAPIKey());`, which is missing the getWsUsername check. 

Reinstating the getWsUsername check is a good start but I think it has to check whether any adyen payment method is enabled. But to be honest I think the whole idea of making an admin area message about this is an anti pattern, because it can't be done on any scope other than default and it really just feels like spam. I personally struggle to imagine the situation where someone managed to fill in a username but didn't fill in an API key and they somehow need a critical system message to remind them of this; validation when saving the config would be more appropriate

**Comment by candemiralp** [comment]
Hello all,

We created an internal ticket to improve this flow.

Best Regards,
Can
