### ISSUE TITLE
Adyen 

### ISSUE THREAD

**Issue by santhiya-nits** [Adyen/adyen-magento2#1964]
Making your own contribution is easy, encouraged and greatly appreciated! We will put effort into reviewing and merging your PR quickly. For more info, please refer to the contribution guidelines: https://github.com/Adyen/adyen-magento2/blob/develop/CONTRIBUTING.md

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Magento version**
[e.g. 2.4.1]

**Plugin version**
[e.g. 6.6.8]

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by candemiralp** [comment]
Hello @santhiya-nits,

I am closing issue since it doesn't contain any information regarding to an actual issue.

Best Regards,
Can
