### ISSUE TITLE
[PW-8343] Adyen GraphQL does not differentiate between Cancelled Orders and orders where payment fails.

### ISSUE THREAD

**Issue by JamelleG** [Adyen/adyen-magento2#1966]
**Describe the bug**
When using Klarna/Clearpay where a redirect is involved, the error message that we get on return isn't clear that an order has been cancelled by the user. 

The functionality for this can be seen on the following file https://github.com/Adyen/adyen-magento2/blob/09caf3ab63a4e0010673647ba448652d8ba0c389/Model/Resolver/GetAdyenPaymentDetails.php#L126

**To Reproduce**
1. Add to basket
2. Pay via klarna
3. Cancel Klarna payment

**Expected behavior**
If we cancel we should get an error message such as "Payment cancelled" 

**Magento version**
2.4.4

**Plugin version**
8.3.5

**Comment by candemiralp** [comment]
Hello @JamelleG,

Thank you for raising this issue. We created an internal investigation ticket to solve this issue. You will be informed when we finish the investigation.

Best Regards,
Can

**Comment by Nuranto** [comment]
Hi guys,

I just made a PR for this. However, I was just looking to fix the error message when payment fails, so that's the only case I tested. I don't use Klarna/Clearpay, so that case should be tested.
