### ISSUE TITLE
[PW-8242] - Error when RedirectShopper is returned when using vault payment method

### ISSUE THREAD

**Issue by maaarghk** [Adyen/adyen-magento2#1980]
**Describe the bug**
Shopper is shown error message "undefined index pspReference"  when attempting to use vault payment method 

I patched the module to add a debug log instead and the stack trace is as follows:

```
[2023-03-02 17:19:41] main.ERROR: Response does not contain pspReference {"response":{"resultCode":"RedirectShopper","action":{"paymentMethodType":"scheme","url":"<snip 3ds url>", "data": {<snip 3ds data>},"method":"POST","type":"redirect"}},"request_uri":"/storecode/rest/storecode/V1/carts/mine/payment-information"},"trace":"
#0  Monolog\\Logger->addRecord() called at [vendor/monolog/monolog/src/Monolog/Logger.php:712]
#1  Monolog\\Logger->error() called at [vendor/magento/framework/Logger/LoggerProxy.php:126]
#2  Magento\\Framework\\Logger\\LoggerProxy->error() called at [vendor/adyen/module-payment/Gateway/Response/PaymentAuthorisationDetailsHandler.php:40]
#3  Adyen\\Payment\\Gateway\\Response\\PaymentAuthorisationDetailsHandler->handle() called at [vendor/magento/module-payment/Gateway/Response/HandlerChain.php:51]
#4  Magento\\Payment\\Gateway\\Response\\HandlerChain->handle() called at [vendor/magento/module-payment/Gateway/Command/GatewayCommand.php:118]
#5  Magento\\Payment\\Gateway\\Command\\GatewayCommand->execute() called at [vendor/magento/module-payment/Gateway/Command/CommandManager.php:65]
#6  Magento\\Payment\\Gateway\\Command\\CommandManager->executeByCode() called at [vendor/magento/module-vault/Model/Method/Vault.php:452]
#7  Magento\\Vault\\Model\\Method\\Vault->authorize() called at [vendor/magento/module-sales/Model/Order/Payment/Operations/AuthorizeOperation.php:45]
#8  Magento\\Sales\\Model\\Order\\Payment\\Operations\\AuthorizeOperation->authorize() called at [vendor/magento/module-sales/Model/Order/Payment/Processor.php:72]
#9  Magento\\Sales\\Model\\Order\\Payment\\Processor->authorize() called at [vendor/magento/module-sales/Model/Order/Payment.php:1136]
#10 Magento\\Sales\\Model\\Order\\Payment->authorize() called at [vendor/magento/module-sales/Model/Order/Payment.php:458]
#11 Magento\\Sales\\Model\\Order\\Payment->processAction() called at [vendor/magento/module-sales/Model/Order/Payment.php:385]
#12 Magento\\Sales\\Model\\Order\\Payment->place() called at [vendor/magento/module-sales/Model/Order.php:992]
#13 Magento\\Sales\\Model\\Order->_placePayment() called at [vendor/magento/module-sales/Model/Order.php:1214]
#14 Magento\\Sales\\Model\\Order->place() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#15 Magento\\Sales\\Model\\Order\\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#16 Magento\\Sales\\Model\\Order\\Interceptor->Magento\\Framework\\Interception\\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#17 Magento\\Sales\\Model\\Order\\Interceptor->___callPlugins() called at [generated/code/Magento/Sales/Model/Order/Interceptor.php:50]
#18 Magento\\Sales\\Model\\Order\\Interceptor->place() called at [vendor/magento/module-sales/Model/Service/OrderService.php:209]
#19 Magento\\Sales\\Model\\Service\\OrderService->place() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#20 Magento\\Sales\\Model\\Service\\OrderService\\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#21 Magento\\Sales\\Model\\Service\\OrderService\\Interceptor->Magento\\Framework\\Interception\\{closure}() called at [app/code/StripeIntegration/Payments/Plugin/Sales/Model/Service/OrderService.php:25]
#22 StripeIntegration\\Payments\\Plugin\\Sales\\Model\\Service\\OrderService->aroundPlace() called at [vendor/magento/framework/Interception/Interceptor.php:135]
#23 Magento\\Sales\\Model\\Service\\OrderService\\Interceptor->Magento\\Framework\\Interception\\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#24 Magento\\Sales\\Model\\Service\\OrderService\\Interceptor->___callPlugins() called at [generated/code/Magento/Sales/Model/Service/OrderService/Interceptor.php:32]
#25 Magento\\Sales\\Model\\Service\\OrderService\\Interceptor->place() called at [vendor/magento/module-quote/Model/QuoteManagement.php:575]
#26 Magento\\Quote\\Model\\QuoteManagement->submitQuote() called at [vendor/magento/module-quote/Model/QuoteManagement.php:456]
#27 Magento\\Quote\\Model\\QuoteManagement->submit() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#28 Magento\\Quote\\Model\\QuoteManagement\\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#29 Magento\\Quote\\Model\\QuoteManagement\\Interceptor->Magento\\Framework\\Interception\\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#30 Magento\\Quote\\Model\\QuoteManagement\\Interceptor->___callPlugins() called at [generated/code/Magento/Quote/Model/QuoteManagement/Interceptor.php:23]
#31 Magento\\Quote\\Model\\QuoteManagement\\Interceptor->submit() called at [vendor/magento/module-quote/Model/QuoteManagement.php:414]
#32 Magento\\Quote\\Model\\QuoteManagement->placeOrder() called at [vendor/magento/module-checkout/Model/PaymentInformationManagement.php:125]
#33 Magento\\Checkout\\Model\\PaymentInformationManagement->savePaymentInformationAndPlaceOrder() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#34 Magento\\Checkout\\Model\\PaymentInformationManagement\\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#35 Magento\\Checkout\\Model\\PaymentInformationManagement\\Interceptor->Magento\\Framework\\Interception\\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#36 Magento\\Checkout\\Model\\PaymentInformationManagement\\Interceptor->___callPlugins() called at [generated/code/Magento/Checkout/Model/PaymentInformationManagement/Interceptor.php:23]
#37 Magento\\Checkout\\Model\\PaymentInformationManagement\\Interceptor->savePaymentInformationAndPlaceOrder()
#38 call_user_func_array() called at [vendor/magento/module-webapi/Controller/Rest/SynchronousRequestProcessor.php:95]
#39 Magento\\Webapi\\Controller\\Rest\\SynchronousRequestProcessor->process() called at [vendor/magento/module-webapi/Controller/Rest.php:188]
#40 Magento\\Webapi\\Controller\\Rest->dispatch() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#41 Magento\\Webapi\\Controller\\Rest\\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#42 Magento\\Webapi\\Controller\\Rest\\Interceptor->Magento\\Framework\\Interception\\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#43 Magento\\Webapi\\Controller\\Rest\\Interceptor->___callPlugins() called at [generated/code/Magento/Webapi/Controller/Rest/Interceptor.php:23]
#44 Magento\\Webapi\\Controller\\Rest\\Interceptor->dispatch() called at [vendor/magento/framework/App/Http.php:116]
#45 Magento\\Framework\\App\\Http->launch() called at [vendor/magento/framework/App/Bootstrap.php:264]
#46 Magento\\Framework\\App\\Bootstrap->run() called at [pub/index.php:29]
```

Offending code is [here](https://github.com/Adyen/adyen-magento2/blob/8.15.0/Gateway/Response/PaymentAuthorisationDetailsHandler.php#L36)

For non-vault, [this](https://github.com/Adyen/adyen-magento2/blob/8.15.0/Gateway/Response/CheckoutPaymentsDetailsHandler.php) is used which seems to be identical except performing an `!empty` check, so maybe this would be a sufficient fix.

**To Reproduce**
1. Save card with 3d secure enabled
2. Place new order and attempt to use card
3. If 3d secure redirect is returned from the gateway, user will see error

**Expected behavior**
3d secure is either not requested or handled correctly

**Magento version**
2.4.3-p3

**Plugin version**
8.15.0

**Additional context**
Manual capture is enabled

**Comment by Morerice** [comment]
Hi @maaarghk,

Thanks for creating this issue. One question from our part. Are you seeing this issue on live, or test or both?

Thanks,
Jean
Adyen

**Comment by maaarghk** [comment]
Live, I haven't recreated on test yet because the card I tested with there had no 3ds but I'll check that later.

**Comment by maaarghk** [comment]
I confirmed it on test with the 3d-secure enabled test card. 

I have tested adding `if (!empty($request['pspReference']))` on Test, and it only makes the problem worse - the `RedirectShopper` response does not seem to be processed, so the iframe is never shown, the Offer is never converted to a Payment, Magento accepts the "RedirectShopper" response as a valid authorisation, the customer sees "order placed successfully" and the order is placed in Payment Review state, _BUT_ no authorisation took place therefore there is no way to capture the payment.

Just to confirm repro steps on test:

* Disable immediate capture
* Enable storing tokens in vault
* Place order with test card 4917 6100 0000 0000, passing 3d secure
* Capture order
* Attempt to place another order using saved card ending 0000

It would be useful if you could provide an estimate as to whether this is likely to be a quick fix (e.g. a week); the retailer processes about ~£5k per day, right now I have a patch which replaces the exception with a message about re-entering your card details but if it's going to be more than a week I imagine the customer will just want me to disable recurring payments completely until they work properly.

**Comment by Morerice** [comment]
Hi @maaarghk,

Thanks a lot for doing this research. Unfortunately I don't think this is something that will have a quick fix, since it's not necessarily a code change required by the plugin. This is something that we will have to check internally within the adyen platform.

I will update this issue with any relevant information we get.

Regards,
Jean
Adyen

**Comment by maaarghk** [comment]
@Morerice - I'm going to recommend my client escalates this from the other end; some customers are retrying over and over again after seeing the exception message, and this is causing their bank to see repeated failed 3d secure attempts and block their card. "My card got blocked because I used it on <retailer> website" is a terrible reputational risk that we can't accept.

In the mean time for anyone else finding this issue on Google my recommendation is simply to disable saving card tokens if you regularly have cardholder-present transactions with high values, or products in a retail category that would cause card issuers to aggressively validate 3DSv2.

**Comment by Morerice** [comment]
Hi @maaarghk,

We have created an internal ticket to solve this issue. Unfortunately escalating this from another end will not yield any different result, since ultimately it's still gonna be us that implement a solution. Normally we recommend reaching out to our support team if we need info that shouldn't be public, there is no code line referenced or if we can't reproduce this issue. 

In this case we have already managed to reproduce the issue. Also, it would be better if we continue the discussion here so that it is publicly visible.

Regards,
Jean
Adyen

**Comment by Morerice** [comment]
Hi @lrotherfield-function,

We don't have any set dates yet but we will try to include it in the release that's due next week.

Regards,
Jean
Adyen

**Comment by candemiralp** [comment]
Hello @maaarghk and @lrotherfield-function,

Thank you for raising this issue. We created a PR for this issue. Currently, our development team is reviewing it. After the code review, we will merge it and release on the upcoming release.

This issue will be closed after merging the PR.

Best Regards,
Can
