### ISSUE TITLE
[PW-8243] - Add config max_order_total for AdyenCc and AdyenHpp

### ISSUE THREAD

**Issue by dimitriBouteille** [Adyen/adyen-magento2#1981]
Hey,

It is possible to add the `max_order_total` option for the AdyenCc and AdyenHpp methods, this is a native feature in Magento available for all payment methods.

For info it is this class that allows to control the display of the method according to the amount of the cart: `\Magento\Payment\Model\Checks\TotalMinMax`.

```xml
<group id="adyen_cc">
    <field id="max_order_total"
           translate="label"
           type="text"
           sortOrder="50"
           showInDefault="1"
           showInWebsite="1">
        <label>Maximal order total</label>
        <config_path>payment/adyen_cc/max_order_total</config_path>
    </field>
</group>
<group id="adyen_hpp">
    <field id="max_order_total"
           translate="label"
           type="text"
           sortOrder="40"
           showInDefault="1"
           showInWebsite="1">
        <label>Maximal order total</label>
        <config_path>payment/adyen_hpp/max_order_total</config_path>
        <depends>
            <field id="active">1</field>
        </depends>
    </field>
</group>
```

Thanks :heart:

**Comment by Morerice** [comment]
Hi @dimitriBouteille,

Thanks for opening this issue. We have created an internal ticket to implement this functionality. In the meantime if you want to speed up this process we encourage you to open a pull request, which we will review asap.

Regards,
Jean
Adyen

**Comment by RokPopov** [comment]
Hi @dimitriBouteille,

I hope you are doing good!
 
We wanted to update you with the information that we are planning on deprecating those fields for v9. 

The reason behind this is that this is a [setting](https://docs.adyen.com/issuing/authorisation/transaction-rules) that can be configured in Adyen Customer Area, and when applied, the payment methods to be shown in the checkout page will already be filtered in Adyen platform.

Kind regards,
Rok
