### ISSUE TITLE
Checkout javascript implementation blocks extensibility

### ISSUE THREAD

**Issue by kweij** [Adyen/adyen-magento2#199]
The chosen javascript implementation utilizes two javascripts to handle the actual placing of the order and passing the form-data to Magento's (Guest)PaymentInformationManagement, these are:
`view/frontend/web/js/action/place-order.js` (non-hpp) and `view/frontend/web/js/action/set-payment-method.js` (hpp).

These javascripts overwrite native Magento 2 functionality that is about exactly the same, except that the Adyen payments add a redirect after successfully performing saving the payment information.

This creates a problem when extending the checkout out, e.g. adding a custom field, because the `payload` of the information that is sent to `(Guest)PaymentInformationManagement` is overwritten.

**What I'd do in a default Magento checkout**

The uiComponent that handles the placing of the order, `module-checkout/view/frontend/web/js/view/payment/default.js` uses `module-checkout/view/frontend/web/js/action/place-order.js` to gather the `payload` that is sent along with the request to save payment information:

    ...
    return function (paymentData, messageContainer) {
        var serviceUrl, payload;

        payload = {
            cartId: quote.getQuoteId(),
            billingAddress: quote.billingAddress(),
            paymentMethod: paymentData
        };

        if (customer.isLoggedIn()) {
            serviceUrl = urlBuilder.createUrl('/carts/mine/payment-information', {});
        } else {
            serviceUrl = urlBuilder.createUrl('/guest-carts/:quoteId/payment-information', {
                quoteId: quote.getQuoteId()
            });
            payload.email = quote.guestEmail;
        }

        return placeOrderService(serviceUrl, payload, messageContainer);
    };
    ...

This information is passed to the `placeOrderService`, the function returned by `module-checkout/view/frontend/web/js/model/place-order.js` that I can extend/wrap to add custom fields to the `payload`:

    ...
    return function (serviceUrl, payload, messageContainer) {
        fullScreenLoader.startLoader();

        return storage.post(
            serviceUrl, JSON.stringify(payload)
        ).fail(
            function (response) {
                errorProcessor.process(response, messageContainer);
                fullScreenLoader.stopLoader();
            }
        );
    };
    ...

**The Adyen implementation**

The uiComponents for the Adyen payment methods don't make use of these Magento components by means of javascript mixins. Instead, `view/frontend/web/js/action/place-order.js` and `view/frontend/web/js/action/set-payment-method.js` each implement these functionalities, impeding extensibility.

I suppose that the Adyen payment methods should make use of the Magento `../js/action/place-order.js` and `../js/model/place-order.js` to implement Adyen specific behaviour. Because now, for adding a field to the payment step I have to use a javascript mixin to overwrite the whole of `view/frontend/web/js/action/place-order.js` and `view/frontend/web/js/action/set-payment-method.js`.

**Comment by rikterbeek** [comment]
Hi @kweij,

Many thanks for this detailed description. We will investigate this and see if that is something we can use.

Regards,
Rik
Adyen

**Comment by rikterbeek** [comment]
Hi @kweij,

I have made some changes to use as many of the core methods please check #241. Does this solves all your issues ?

Regards,
Rik
Adyen
