### ISSUE TITLE
[PW-8203] - Swish states failure despite successful payment

### ISSUE THREAD

**Issue by janhemmingsson** [Adyen/adyen-magento2#1990]
We have several cases every day that goes like this:
- Customer comes to checkout and select Swish as payment method.
- Customer makes payment
- Message appears that the payment failed.
- Now more often than not, the customer places a new order, sometimes with Swish, sometimes with card.
- Second payment is successful

Outcome: It turns out that the first payment was actually successful, despite the error message.
The customer has now made two orders with successful payments.

Expected outcome: If the payment was successful, the message should be that it was successful.

We have also had cases where the customer is asked to "activate" Swish, despite already using it on a daily basis.

I have contacted Adyen support, and they came to this conclusion:
===============================
 
I have been investigating further the issue with Swish payments and found that this is related to an issue that in Checkout v69, which is the version that Magento is running on. This issue was resolved on v70 but not yet implemented in Magento. 
...
=====================================

We run on Magento 2.4.5, Adyen Plugin 8.15.0

As stated from Adyen support, this would most likely be fixed through update to Checkout v70.
For us, it is very important that Swish works properly. Such errors several times a day gives a very bad impression. Therefore i filed it here as a bug, and not as a feature request.

**Comment by Morerice** [comment]
Hi @janhemmingsson,

Thanks for opening this issue. We have created an internal ticket to update our module to use checkout v70.

Regards,
Jean
Adyen
