### ISSUE TITLE
Payment status endpoint issue for guest customer.

### ISSUE THREAD

**Issue by vijayatseepossible** [Adyen/adyen-magento2#1996]
Describe the bug
Guest customer while place order not showing order success page due to payment status endpoint.
In js orderId is blank.

To Reproduce
1. Go to checkout page
2. Click on place order button

Expected behavior
Order success page.

Magento version
2.4.1

Plugin version
8.15.0

Screenshots
<img width="1376" alt="Screenshot 2023-03-17 at 5 25 52 PM" src="https://user-images.githubusercontent.com/71834444/225897928-58860bb2-7719-449a-92ea-29d794dc221a.png">
<img width="1375" alt="Screenshot 2023-03-17 at 5 26 03 PM" src="https://user-images.githubusercontent.com/71834444/225897960-1b7b4c58-2eb4-4607-ba05-50db4f55a9fc.png">

**Desktop 
OS: MacOS
Browser Chrome
Version 109.0.5414.119

**Comment by Morerice** [comment]
Hi @vijayatseepossible,

Thanks for opening this issue. I was unable to reproduce the problem based on the steps to reproduce provided. Is there any other detail that could maybe help us reproduce it?

Regards,
Jean
Adyen

**Comment by vijayatseepossible** [comment]
@Morerice That was custom plugin issue.
Above issue is resolved.
Thank you for help.
