### ISSUE TITLE
[PW-8301] Notification  Payment Method: scheme

### ISSUE THREAD

**Issue by simonebraan** [Adyen/adyen-magento2#2005]
Hi,
I reached out to Adyen Support because we are receiving notifications in Magento which indicate the payment method as "scheme" see screenshot below. As a result the orders remain on hold by our systems awaiting confirmation of the correct payment method.

Adyen's development team confirmed that there is a bug with the notification "Payment Method: scheme" and suggested reaching out through Github.

Magento version 2.4.4
Plugin version 8.10.0
<img width="366" alt="Immagine Payment Method Scheme" src="https://user-images.githubusercontent.com/128717342/227238521-f2d45335-db29-4d2b-8785-57474c4b0373.png">

Thanks

**Comment by candemiralp** [comment]
Hello @simonebraan,

Thank you again for raising this issue. The PR is merged and will be released this week.

Best Regards,
Can
