### ISSUE TITLE
Order status stuck in "Payment review" when it actually has completed successfully

### ISSUE THREAD

**Issue by mksvn-gmbh** [Adyen/adyen-magento2#2022]
### **Describe the bug**
We are experiencing similar issue to the ones reported in #744, #782, #887, #963 - unfortunately, there was no solution or fix posted there.

Since mid March when we upgraded to **Magento 2.4.3-p3** and **Adyen 7.3.13** we have had a number of cases where orders with successful credit card transactions were not transitioned from _Payment review_ status to _Processing_ status. This issue still randomly occurs - there is no one scenario for this issue, it happens for Mastercard and Visa cards, different countries etc.

In the Adyen admin panel payment (of the affected order) is listed as successful. Magento order details page (see screenshot below) shows that payment was successfully authorized and captured and status was changed to processing - but in reality status was not changed. Status of the order in the orders grid or the status displayed at the top of the order detail page is still _Payment review_. The order is then not possible to process correctly and affects other automations that depend on the orders status.

### **To Reproduce**
No exact scenario on how to reproduce this issue, occurs randomly.

### **Expected behavior**
Order status should be changed from **Payment review** to **Processing** when payment was successfully captured.

### **Screenshots**
![image](https://user-images.githubusercontent.com/73602009/231102528-7a8c9adf-f3be-4042-a0c5-55efe3b7fe43.png)

### **Additional context**
Started to occur after migrating to Magento 2.4.3-p3 and Adyen 7.3.13 - did not happens on previous (older) Adyen module versions.

**Comment by candemiralp** [comment]
Hello @mksvn-gmbh,

Thank you for reaching out and raising this issue. We couldn't reproduce your issue and at this point I would recommend reaching out to our support team (support@adyen.com) with the logs, which includes the records of the related order. 

We don't consider sharing logs and payment related information on Github safe. Also, this Github issue is not highlighting a code snippet and doesn't have an exception/error message. Under those circumstances, it would be better to solve your issue with a support ticket.

Please note that version 7 is on [level 3](https://github.com/Adyen/adyen-magento2#support--maintenance) support, which means only very critical security patches will be released. Otherwise there won't be any updates/fixes for that version.

Best Regards,
Can

**Comment by LucScu** [comment]
@mksvn-gmbh i have the same issue 
magento 2.3.4
adyen/module-payment 8.1.1
adyen/php-api-library 11.0.0

Did you try to update your adyen module version from 7.3 to the latest?

**Comment by LucScu** [comment]
@candemiralp After upgrade to v8.18.1 the issue is still present: some order remain in payment review even if notification log says
"Order status was changed to authorised status: processing"

**Comment by your-favorite-pm** [comment]
@candemiralp @LucScu we can confirm something similar happened to us. We are running on
- Magento 2.4.5-p1
- Adyen 8.1.18

**Comment by LucScu** [comment]
@your-favorite-pm we add custom log in the adyen flow and nothing strange happens.
Maybe the culprit is another plugin, the main suspect is another payment gateway.
We'll try to add more log with a before plugin on order repo save method, then i hope to find an answer.

**Comment by dejankar** [comment]
@LucScu, @candemiralp  
We are experiencing the same with

- Magento 2.4.6
- Adyen 8.18.1

However, in our case is sporadic and it happens only on a few orders while the rest are fine.

**Comment by mfickers** [comment]
Can this issue please be reopened? We are still experiencing this on Magento 2.4.5-p4 and Adyen 8.20.1.

@LucScu, did you ever find out more with your logging?

**Comment by mfickers** [comment]
@LucScu, thank you for pointing me in the right direction. Thanks to you mentioning the Adyen cron, I finally found the issue. There was an error message that could only be found in the cron_schedule table. 

In our case, there was a problem during rendering of the invoice mail. Sending of the invoice mail happens after the webhook is processed but before the new order state is saved. Which means even though the webhook event was marked as successful, the order was never put into the next state.

Maybe some of the others reporting the same issue have similar problems? I think it would be a good idea to harden the cron process against this by catching exceptions here:
https://github.com/Adyen/adyen-magento2/blob/develop/Helper/Invoice.php#L216

**Comment by Karthik041100** [comment]
@mfickers 

We are also facing the same issue on our website. In our case, the notification event_code is AUTHORISATION, and even though the invoice email sending configuration is disabled, the order status still remains in Payment Review.

Did you face the same issue in this scenario as well?

Magento Version - 2.4.6-p3

Adyen Version - 8.21.0

**Comment by mfickers** [comment]
@Karthik041100 My specific issue had been fixed in 8.22.0. I suggest updating the extension to 8.24.0, maybe that will resolve your problem.

Also, there are major security issues with running 2.4.6-p3 in production. You should upgrade to 2.4.6-p11 ASAP.
