### ISSUE TITLE
PHP 7.1 support

### ISSUE THREAD

**Issue by mwienk** [Adyen/adyen-magento2#203]
Is there any reason there is no PHP 7.1 support in the composer file? Magento 2.2 has 7.1 support (http://devdocs.magento.com/guides/v2.2/install-gde/system-requirements-tech.html) and your module has Magento 2.2 support.

**Comment by rikterbeek** [comment]
Hi @mwienk,

No there should be no problem. I removed the php version we allow all versions that Magento2 supports. https://github.com/Adyen/adyen-magento2/commit/74a0b2918ceeb5d11cdb33082fecd4b4f6577fa9

Regards,
Rik
Adyen

**Comment by gulshan-streammarket** [comment]
Hi,
I am also facing the same issue. I get the following message.
`Could not find package adyen/module-payment at any version matching your PHP version 7.1.10.0`
Can you please look into this.

**Comment by rikterbeek** [comment]
Hi @gulshan-streammarket,

Probably because it is not on our master fixed. Can you check if develop branch does work ?

Regards,
Rik
Adyen

**Comment by gulshan-streammarket** [comment]
Hi Rik,

I tried "composer require adyen/module-payment develop" but it throws exception

  ```
[UnexpectedValueException]
  Could not parse version constraint develop: Invalid version string "develop"
```
Any idea?

**Comment by rikterbeek** [comment]
Hi,

Looks like you did not specify development mode correctly. It is now solved on the master as well so it is solved.

Regards,
Rik
Adyen

**Comment by gulshan-streammarket** [comment]
Many Thanks Rik
