### ISSUE TITLE
sales_order_grid -> Payment Method / Extend title to also show the brand_code (like: Adyen: klarna)

### ISSUE THREAD

**Issue by ggmmoebel** [Adyen/adyen-magento2#2038]
Is it planned to extend the Sales Order Grid Payment Method by the Brand code if the method is adyen_hpp?

**Comment by candemiralp** [comment]
Hello @ggmmoebel,

Thank you for your suggestion! That will be possible with the individual implementations of the payment methods. On v9 we are deprecating the payment method `adyen_hpp` and will have `adyen_klarna` individually.

I am adding this issue to the V9 milestone.

Best Regards,
Can

**Comment by ggmmoebel** [comment]
Is there an estimate when V9 will be released?

**Comment by candemiralp** [comment]
Hello @ggmmoebel,

The estimated time for the release is end of Q2 or beginning of Q3 2023.

Best Regards,
Can

**Comment by candemiralp** [comment]
Hello @ggmmoebel,

As we discussed before, V9 of our plugin supports individual payment methods and shows payment method code on the grid. V9 was released and can be used now.

Best Regards,
Can
