### ISSUE TITLE
Adyen Payment throw error during place order

### ISSUE THREAD

**Issue by patelnimesh1988** [Adyen/adyen-magento2#2046]
**Describe the bug**
While placing an order. Order is placed but not redirected to the Success page. It throw below error

URL: V1/internal/adyen/orders/payment-status
Uncaught Error: Call to a member function getAdditionalInformation() on null in vendor/adyen/module-payment/Model/Api/AdyenOrderPaymentStatus.php:80

After disabling **Adyen_Payment** extension order was placed successfully. When **Adyen_Payment** enable not allowed to place an order using another payment.

When I open Error place order in admin it also throws below an error

Fatal error: Uncaught Error: Call to a member function canReviewPayment() on null

**To Reproduce**
1. Add Configurable product to the cart
2. Go to Checkout
3. Palce Order Using a Credit Card
4. You will get an Error from Brower **Network** Section

**Expected behavior**
Order Place successfully and redirect to Order Success Page

**Magento version**
2.3.7-p2

**Plugin version**
8.3.5

**Screenshots**
![Screenshot-from-2023-05-04-03-32-30](https://user-images.githubusercontent.com/6728907/236061539-66d392a2-7cfb-48c7-9eb9-d1f4850a1b7a.png)

**Desktop (please complete the following information):**
 - Ubuntu
 - chrome

**Comment by RokPopov** [comment]
Hi @patelnimesh1988 

Thank you for opening an issue with us.

As we are not able to reproduce your issue, the way to approach this would be to investigate this with our support engineers. Would you be able to send a ticket with as many details as possible to support@adyen.com, as the information necessary for debugging your issue also includes PII?

Cheers,
Rok
