### ISSUE TITLE
[PW-8394] Avoid using "new" to instantiate classes

### ISSUE THREAD

**Issue by nkarthickannan** [Adyen/adyen-magento2#2048]
**Is your feature request related to a problem? Please describe.**
Yes, it is related to a problem. I'm trying to override the class. But Adyen module is instantiating the class using "new". This is not in accordance with the Magento best practices and thus making it not open for customisation. The affected class can be found here https://github.com/Adyen/adyen-magento2/blob/develop/Helper/Webhook/WebhookHandlerFactory.php#L166

**Describe the solution you'd like**
The solution is to avoid using the "new" to instantiate a class. Instead, Magento's constructor dependency injection can be used.

**Describe alternatives you've considered**
There is no alternative for this issue.

**Additional context**
N/A

**Comment by candemiralp** [comment]
Hello @nkarthickannan,

Thank you for creating this issue and for the suggestion. As you mentioned, this pattern is not aligned fully with the Magento best practices. But at the moment of implementation, we had valid reasons to implement in that way.

However, it is time to investigate the possibility to improve that approach and see if we can refactor it into a way that we can use dependency injection. We created an internal investigation ticket for this issue and you will be informed when it is done.

Best Regards,
Can
