### ISSUE TITLE
Adyen CC JS validation is not working

### ISSUE THREAD

**Issue by rudiwang** [Adyen/adyen-magento2#2050]
**Describe the bug**
When checking out with Ayden Credit Card payment method, the JS validation is not working properly.

**To Reproduce**
1. Go to checkout after add any product to cart
2. Add shipping address and shipping method, click "Next"
3. Choose Adyen payment method
4. It shows invalid message that says "Incomplete field"  
5. Add CC number, exp date and CVV
6. Even added correct information, the invalid message still shows up

**Expected behavior**
When adding correct CC number, exp date and CVV, the JS validation should work and invalid message that says "Incomplete field" should be removed.

**Magento version**
2.3.5-p2

**Plugin version**
7.3.13

**Screenshots**
![image](https://github.com/Adyen/adyen-magento2/assets/104393803/0469ce5b-474b-4ddc-a47f-dbffd53c2379)

**Desktop (please complete the following information):**
 - OS: iOS / Win
 - Browser: Chrome / Safari

**Comment by candemiralp** [comment]
Hello @rudiwang,

Thank you for raising this issue. Unfortunately, we couldn't reproduce the issue that you described.

Besides that, version 7 of the module was deprecated and not getting any updates. Support to that version was also dropped. I would highly recommend upgrading the plugin to a recent version. You can check the [upgrade documentation](https://docs.adyen.com/plugins/adobe-commerce/upgrade) for further information.

Best Regards,
Can
