### ISSUE TITLE
Refund is not working when using the test account

### ISSUE THREAD

**Issue by santhiya-nits** [Adyen/adyen-magento2#2054]
**Problem Statement**
Refund is not working when using the test account

Reference:
Adyen PSP Reference: **GK5LX5385TGLNK82**

![Screenshot from 2023-05-15 18-48-27](https://github.com/Adyen/adyen-magento2/assets/119569918/0a5021b8-8963-4806-b430-440e137c99e8)

**Comment by RokPopov** [comment]
Hi @santhiya-nits,

Thank you for opening the issue with us. 
These kinds of issues are better investigated first with our tech support team, therefore please reach out to them via support@adyen.com

I will be closing this issue for now.

Kind regards,
Rok
