### ISSUE TITLE
Database tables not being created on install

### ISSUE THREAD

**Issue by downfall24** [Adyen/adyen-magento2#2057]
When installing this plugin via composer the database tables aren't being created and thus I am receiving this error when running setup:upgrade

Notice: Undefined index: adyen_order_payment in vendor/magento/framework/Setup/Declaration/Schema/Db/SchemaBuilder.php on line 152

Inside the 'setup' folder there doesn't appear to be any create DB files? is this correct?

**Magento version**
2.3.7

**Plugin version**
8.14

**Comment by RokPopov** [comment]
Hi @downfall24,

Thank you for opening this issue.
Indeed, this is correct as we are using a [declarative setup](https://github.com/Adyen/adyen-magento2/blob/develop/etc/db_schema.xml) based on [database structure declarations](https://devdocs.magento.com/guides/v2.3/extension-dev-guide/declarative-schema/db-schema.html). 
This approach is indeed supported  with the version of Magento platform you are using, therefore please reach out to our tech support via support@adyen.com for further troubleshooting.

I will be closing this issue for now.

Kind regards,
Rok
