### ISSUE TITLE
WYSIWYG editor not working

### ISSUE THREAD

**Issue by iflairBhavin** [Adyen/adyen-magento2#207]
**Magento version**: 2.1.9 (EE)
**Plugin version**: 2.1.2
**Description**
We are using Adyen payment method for our webshop. In the admin area WYSIWYG editor not working due to Adyen payment extension. 

We are using minify and merge js and production mode over Magento cloud server. We have contacted Magento support team and below is reply from support.

"Dev team responded that this issue caused by Adyen_Payment extension, please contact extension vendor or disable it."

Please advice. Thanks in advance for your help.

**Comment by lancergr** [comment]
Hi @iflairBhavin 

Thanks for reporting this!
We have pushed a bugfix for it here: 14802ff0de91f30d793bf3ccc08db9d370c59aa2

Please let me know if this works for you.

Best Regads,
Giorgos
Adyen
