### ISSUE TITLE
[PW-8454] Payment Notifications with Emojis can't be processed.

### ISSUE THREAD

**Issue by fahu** [Adyen/adyen-magento2#2072]
**Describe the bug**
If a user uses Emojis in his/her shopper details the Adyen module fails to process the notification with "Unable to unserialize value, string is corrupted.".

For "normal" payment methods this is not a big issue as we can validate the shipping & billing address for invalid characters. However, with express payment methods (e.g. Apple Pay) it's fairly hard to prevent users from using Emojis.

**To Reproduce**
1. Configure your Apple Pay account to have Emojis in the name.
2. Add a product to the cart.
3. Checkout with the product and use Apple pay as payment method
4. Finish the checkout

**Expected behavior**
The order gets created and will be moved to "processing" after Adyen has processed the notification.

**Actual behaviour**
The order gets created but stays in status "pending" because the Adyen module fails to process the notification.

**Magento version**
2.4.3-p3

**Plugin version**
8.11.0

**Screenshots**
![image](https://github.com/Adyen/adyen-magento2/assets/2507037/130fd8af-7abc-452c-8bbd-a9b4ad7986aa)

**Comment by raoulritter** [comment]
Hi @fahu,

Would you be able to help provide us more information in this case.

I have been trying to replicate this issue but have been struggling to do so as I am unable to setup my Apple Id to have an Emoji in the name. Could you specify what you are passing through and where/ how specifically. Thanks in advance.


Kind regards,

Raoul  


![image](https://github.com/Adyen/adyen-magento2/assets/59527829/da9bcb07-bed4-4651-b811-a4894400bf47)

**Comment by RokPopov** [comment]
Hi @fahu,

As per the fact the issue is not replicable and due to inactivity, we are closing this issue.

Cheers,
Rok
