### ISSUE TITLE
IpAddress helper issue 

### ISSUE THREAD

**Issue by Nuranto** [Adyen/adyen-magento2#2078]
This is just a case issue. `config` instead of `Config` : 

<img width="1273" alt="Capture d’écran 2023-06-02 à 07 01 11" src="https://github.com/Adyen/adyen-magento2/assets/1633463/c7913ace-26f1-482f-8133-858f708cb2d0">

**Comment by candemiralp** [comment]
Hello @Nuranto,

Thank you for raising this issue and proposing the solution as well. We are going to merge the solution.

Best Regards,
Can
