### ISSUE TITLE
Dankort and payment method

### ISSUE THREAD

**Issue by dronerdk** [Adyen/adyen-magento2#2083]
Hello
Small bug here.
If a customer use a Visa/Dankort and Adyen use Dankort, it will show as Visa as payment method in Magento and not Dankort.
<img width="433" alt="Skærmbillede 2023-06-05 kl  20 45 55" src="https://github.com/Adyen/adyen-magento2/assets/15999222/97080e80-4d2f-401c-8af7-91c61ba7dc0b">
<img width="676" alt="Skærmbillede 2023-06-05 kl  20 44 55" src="https://github.com/Adyen/adyen-magento2/assets/15999222/2a87761f-f432-47df-aedb-f64e3938f16e">

**Comment by candemiralp** [comment]
Hello @dronerdk,

Thanks for raising this issue. I need some extra details to solve this issue. Could you please specify the value of `paymentMethod` field returning from the `/payments` or `/payments/details` calls or from `Authorisation` webhook?

Best Regards,
Can

**Comment by candemiralp** [comment]
Closing this issue since it needs more info.
