### ISSUE TITLE
[PW-8505] Add support for recurring for Trustly

### ISSUE THREAD

**Issue by fahu** [Adyen/adyen-magento2#2095]
**Describe the bug**
Trustly does not work with recurring payments even though the [documentation](https://docs.adyen.com/payment-methods/trustly#refunds) states that it does.
![image](https://github.com/Adyen/adyen-magento2/assets/2507037/7612f88b-983b-4f0e-87f3-6fb7d5813d21)

**Magento version**
Magento 2.4.6

**Plugin version**
v8.18.2

**Comment by RokPopov** [comment]
Hi @fahu,

Thank you for opening this issue with us.

Please know that we have opened an internal ticket in order to handle this. We will update this issue once the task will be completed.

Kind regards,
Rok

**Comment by candemiralp** [comment]
Hello @fahu,

Recurring payments functionality for payment method Trustly has been added on our new major version V9. You can upgrade the plugin to the latest version.

Please let us know if upgrading to V9 is not an option.

Best Regards,
Can
