### ISSUE TITLE
Graphql Place Order: Undefined array key 241783 in  /magento/vendor/adyen/module-payment/Helper/StateData.php

### ISSUE THREAD

**Issue by milindsingh** [Adyen/adyen-magento2#2099]
**Describe the bug**
`main.ERROR: Warning: Undefined array key 241783 in 
/magento/vendor/adyen/module-payment/Helper/StateData.php on line 98`

**To Reproduce**
1. Place order using graphql query as below:

```
mutation {
    setPaymentMethodOnCart(
    input: {
      cart_id: "6RsV5fLQBPKc7s5x4mTKA7ng8F6bzVmR"
      payment_method: {
        code: "adyen_hpp"
        adyen_additional_data_hpp: { brand_code: "scheme", stateData: "{\"paymentMethod\":{\"type\":\"scheme\"},\"clientStateDataIndicator\":true}" }
      }
    }
  ) {
    cart {
      id
      selected_payment_method {
          code
          title
          purchase_order_number
      }
      shipping_addresses {
        selected_shipping_method {
            carrier_code
            method_code
            method_title
            carrier_title
            amount {
               currency
               value
            }
        }
      }
      prices {
        grand_total {
          currency
          value
        }
      }
    }
  }
  placeOrder(input: { cart_id: "6RsV5fLQBPKc7s5x4mTKA7ng8F6bzVmR" }) {
    order {
      order_number
      adyen_payment_status {
        action    
        resultCode
        additionalData
        isFinal
      }
    }
  }
}
```

**Expected behavior**
Order should be placed successfully.

**Magento version**
2.4.5

**Plugin version**
8.18.2

**Screenshots**
NA

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - Browser: Chrome
 - Version : lastest

**Additional context**
Using Graphcommerce graphql payment

**Comment by RokPopov** [comment]
Hi @milindsingh,

Thank you for reporting the issue with us.

Could you please reach out to our tech support team at support@adyen.com in order to troubleshoot the issue you are experiencing? I will be closing of this issue as of now.

Thank you in advance,

Kind regards,
Rok

**Comment by milindsingh** [comment]
Are you not taking bug reports from GitHub issues?
