### ISSUE TITLE
Sending invoice on successful payment

### ISSUE THREAD

**Issue by robinwestra** [Adyen/adyen-magento2#210]
**Magento version**: 2.2.0
**Plugin version**: 2.1.2
**Description**
There are some traces of a setting to send an email after the order has been paid. It appears that it is not implemented though because the config setting 'send_invoice_update_mail' is not available.

If it is manually added to the database, it still won't work because it makes a call to Magento\Sales\Model\Order\Invoice::sendEmail which does not exist in Magento 2 anymore. 
Instead, Magento\Sales\Model\Order\Email\Sender\InvoiceSender should be used.

Do you want me to create a pull request for this fix?

**Comment by rikterbeek** [comment]
Hi @robinwestra,

I see what you mean. Is this a functionality you want to use ? if so do a PR we can merge it into the extension otherwise we could think of removing this feature from the code.

Regards,
Rik
Adyen

**Comment by robinwestra** [comment]
Hi,

I've created a pull request. I've also modified the code to check the default Magento 2 setting for invoice mails, instead of having a module specific setting.

**Comment by rikterbeek** [comment]
Hi,

Thanks is merged in #212.

Regards,
Rik
Adyen
