### ISSUE TITLE
Address Verification - N/A Submitted

### ISSUE THREAD

**Issue by cascaderack** [Adyen/adyen-magento2#2114]
When transactions are pushed from Magento to Adyen for address verification the characters "N/A" are always pushed into the address field.  This is causing some issues verifying customer addresses.  Sometimes this works fine, but customers with suite or apartment numbers always get rejected.  

Extension version | 8.15.0
Magento version | 2.4.5-p1

![Screenshot (7)](https://github.com/Adyen/adyen-magento2/assets/44014006/950f5b2d-f548-4305-b32b-e381c24e5185)

**Comment by candemiralp** [comment]
Hello @cascaderack,

As I see from the screenshot, you haven't configured `Address street line used for the house number input` configuration field under `Checkout Experience` tab. You can specify the line number of the address to be used as the house number. This input field will be used for the house number and it won't send N/A.

Best Regards,
Can
