### ISSUE TITLE
[ECP-8627] Deprecated Functionality: strcmp(): Passing null to parameter #2

### ISSUE THREAD

**Issue by RomanMoshchytskiy** [Adyen/adyen-magento2#2166]
`Deprecated Functionality: strcmp(): Passing null to parameter #2 ($string2) of type string is deprecated in vendor/adyen/module-payment/Helper/PaymentMethods.php on line 819`

When using the pay_by_link payment method, cc_type is not filled in the database. And since the value of cc_type in the database, if it is null, an error occurs.

**Magento version**
[e.g. 2.4.4-p1]

**Plugin version**
[e.g. 8.11.0]

**Comment by candemiralp** [comment]
Hello @RomanMoshchytskiy,

Thank you for raising this issue. We created an internal investigation ticket to check and fix the issue. You will be informed when the investigation is done.

Best Regards,
Can

**Comment by khushboo-singhvi** [comment]
Hello @RomanMoshchytskiy, 

Thank you for bringing this issue to our attention. We would like to inform you that it has been solved and merged. It will be released soon with the latest version. 
If you encounter any difficulties implementing these changes or have more information to share, feel free to update this issue or open a new one if necessary. 

Thank you again for your contribution and for helping make our plugin better.

Best regards,
Khushboo

**Comment by alexsimache** [comment]
@khushboo-singhvi @candemiralp  We’ve recently encountered the same issue, but in the context of PayPal Express:
`Critical error occurred. Notification XXX had an error: Deprecated Functionality: strcmp(): Passing null to parameter #2 ($string2) of type string is deprecated in /var/www/html/vendor/adyen/module-payment/Helper/PaymentMethods.php on line 925`.

Environment details:
	•	Magento: 2.4.8-p3
	•	adyen/module-payment: 10.6.1
	•	adyen/adyen-magento2-expresscheckout: 3.1.0

Have you seen this issue in this setup as well, or is there a recommended fix / patch for it? Should i create a New Issue for this?

**Comment by candemiralp** [comment]
Hello @alexsimache, thanks for reaching out. 

I'm having difficulty to reproduce this issue with PayPal express. If you have clear steps to reproduce the issue, I would recommend creating a new Github Issue. Otherwise, please reach out to our support team by sending an email to `support@adyen.com` explaining the issue briefly with some example psp references.

Best Regards,
Can
