### ISSUE TITLE
[ECP-8625] Wrong Apple Pay Certificate Url

### ISSUE THREAD

**Issue by scribam** [Adyen/adyen-magento2#2186]
The file Setup/Patch/Data/ApplePayCertificateUrlPath.php setup the Apple Pay Certificate Url with a wrong url https://docs.adyen.com/reuse/payment-method-pages/apple-pay/adyen-certificate/apple-developer-merchantid-domain-association.zip as it leads to a 404.

https://github.com/Adyen/adyen-magento2/blob/44ce7b82b80524f82c635f0d940fb993045ed31f/Setup/Patch/Data/ApplePayCertificateUrlPath.php#L18

**Comment by candemiralp** [comment]
Hello @scribam,

Thank you for raising this issue. We created an internal ticket to solve this issue. You will be informed when the issue is resolved.

Best Regards,
Can

**Comment by scribam** [comment]
Fixed by https://github.com/Adyen/adyen-magento2/pull/2243

**Comment by kanevbg** [comment]
It is wrong again, it is returning 404.
The actual one seems to be https://docs.adyen.com/payment-methods/apple-pay/web-component/apple-developer-merchantid-domain-association-2024.zip
