### ISSUE TITLE
Using Paypal creates order in Magento before actual payment 

### ISSUE THREAD

**Issue by RobKega** [Adyen/adyen-magento2#2199]
When a customer selects paypal and goes to the checkout procedure, an pending order is already created, this leads to stock getting reserved in the Magento backend, if the customer then decides to change the payment method or cancel the checkout procedure as a whole, the product may not be available for purchase due to stock quantity limitations. 

**To Reproduce**
1. Order a product
2. Go to checkout
3. Select paypal and continue to payment screen
4. Cancel payment 
5. See order created in Magento backend

**Expected behavior**
Don't see an order being created

**Magento version**
2.4.5-p3

**Plugin version**
8.15.0

**Desktop (please complete the following information):**
 - OS: Any
 - Browser Any
 - Version Any

**Comment by candemiralp** [comment]
Hello @RobKega,

Thanks for raising this issue. This situation is known and there is no fix unfortunately. Let me explain the integration flow.

Adyen frontend checkout component for PayPal requires an
