### ISSUE TITLE
[ECP-8626] adyen_payment_cancel_expired_orders memory issues

### ISSUE THREAD

**Issue by frostblogNet** [Adyen/adyen-magento2#2202]
Hi adyen team we came cross an memory issue and want to report it to you.

**Describe the bug**
The cron job adyen_payment_cancel_expired_orders is allocating more than 8GB Memory. The reason for that is that the order colection is only filtered based on the order state. 

vendor/adyen/module-payment/Cron/Providers/PayByLinkExpiredPaymentOrdersProvider.php
`
    private function getStateFilterGroup()
    {
        $stateFilter = $this->filterBuilder->setField('state')
            ->setConditionType('eq')
            ->setValue(Order::STATE_NEW)
            ->create();

        return $this->filterGroupBuilder->setFilters([$stateFilter])->create();
    }
`

**Expected behavior**
The filter should be limited to someting like

- load only adyen orders 
- do not load orders without date filter

**Magento version**
>2.4.4

**Plugin version**
8.20.1

**Comment by candemiralp** [comment]
Hello @frostblogNet,

Thank you for raising this issue. We created an internal investigation ticket to check and fix the issue. You will be informed when the investigation is done.

Best Regards,
Can
