### ISSUE TITLE
adyen respond with "request already processed or in progress" for successfull payment 

### ISSUE THREAD

**Issue by vakokakokit** [Adyen/adyen-magento2#2211]
After we upgrade to adyen from 8.10 to  8.19.0 we are facing a strange issue it happens very rare but on daily basis.
After a **successfull payment** customer see this message on cart page.
`Your payment failed, Please try again later'`
So customer thinks the payment is failed so they again go for checkout and create new order which is successfull.

So now they have 2 sucessfull payment and 2 order from which 1 is pending state.
when the cron process the webhooks  the first order which give error to customer is also turn in Processing as Adyen says the payment was successfull.

So now we have 2 prcessing order with 2 sucessfull payments but customer thinks his second payment was sucessfull

According to log the first order response was

`[2023-09-11T09:13:03.748862+00:00] AdyenLoggerTest.ADYEN_RESULT: Processing ResultUrl [] {"uid":"2939b05"}
[2023-09-11T09:13:03.831359+00:00] AdyenLoggerTest.ERROR: Unexpected result query parameter. Response: {"error":"request already processed or in progress"} [] {"uid":"2939b05"}
[2023-09-11T09:13:03.831246+00:00] AdyenLoggerTest.ADYEN_RESULT: Response from Payment gateway for  order no 115650372 : {"error":"request already processed or in progress"    } [] {"uid":"2939b05"}
[2023-09-11T09:13:03.901914+00:00] AdyenLoggerTest.ADYEN_RESULT: Payment for order 115650372 was unsuccessful,   OFFER_CLOSED notification has been processed. [] {"uid":"2939b05"}`

So first time when magento validate the payment adyen respond with `request already processed or in progress`
But when cron process the webhook its validate the order sucessfully.

Magento version 2.4.6-p2
Adyen module version 8.19.0

I noticed that adyen has included Idempotency after 8.15.0 can it be the reason ?

**Comment by candemiralp** [comment]
Hello @vakokakokit,

Thank you for raising this issue. However, we can't help you on Github for this case. Github Issues is only for reproducible errors with clear exception messages and code references, enhancements etc.

For your case, our support engineers need to investigate the payment carefully. That requires sharing some sensitive information. We strongly discourage our merchants to share sensitive information on Github.

Please send a support request to support@adyen.com with log files which contain information for the given two payment attempts and pspreferences if possible.

Best Regards,
Can
