### ISSUE TITLE
Call to undefined function AdyenLogger::addWarning in GetAdyenPaymentStatus

### ISSUE THREAD

**Issue by RobKega** [Adyen/adyen-magento2#2224]
In the catch block in the GetAdyenPaymentStatus, line 105 there is a call to the addWarning method on the logger object, but this method does not exist, it probably should be addAdyenWarning 

**Magento version**
2.4.5-p3

**Plugin version**
8.15.0

**Comment by candemiralp** [comment]
Hello @RobKega,

Thanks for raising this issue. However, this was resolved in #2033. Please upgrade your plugin to solve this issue.

Best Regards,
Can
