### ISSUE TITLE
Riverty/Afterpay | Other solution for a birth day picker

### ISSUE THREAD

**Issue by mdlatzee** [Adyen/adyen-magento2#2235]
**Is your feature request related to a problem? Please describe.**
Payment method > Riverty/Afterpay
When selecting this payment methode. A 'date of birth' is required. When this field is selected a datepicker is shown. On desktop there isn't a problem. But the datepicker on Android and IOS aren't really user friendly. This has multiple factors;
- the 'start date' is the date of the current day. As this is a 'birthday' selector, this is never going to be the current date
- IOS; the selector has no way to select a year, so you have to swipe month, to month, to month, etc.
- Android: you get a calender view, where a date selector is more friendly.

**Describe the solution you'd like**
There are 2 solutions possible
- the day, month and year fields are seperated so you fill in one by one.
- there is a different selector called on. Not a date picker, but a datepicker dialog (android) or Picker - date (IOS)

**Additional context**
More about the picker in IOS (native)
https://developer.apple.com/design/human-interface-guidelines/pickers
More about the datepicker dialog in Andriod (native)
https://developer.android.com/develop/ui/views/components/pickers

**Comment by candemiralp** [comment]
Hello @mdlatzee,

Thank you for creating this issue for enhancement! Unfortunately, our team can't implement this enhancement because we are the consumer of that product also. 

Could you please post your message on [Adyen Web](https://github.com/Adyen/adyen-web) repository? Related team is going to review it.

Best Regards,
Can
