### ISSUE TITLE
[ECP-8675] Warning: Undefined array key "pspreference" 

### ISSUE THREAD

**Issue by dronerdk** [Adyen/adyen-magento2#2251]
Hello

We use an ERP system to handle our pick and pack in magneto.
(Boostmyshop ERP)
Iin the latest version we cannot generate the invoice from the pick and pack system.
We get this error.
This has been working fine before.

Warning: Undefined array key "pspreference" in /var/www/droner.dk/public_html/vendor/adyen/module-payment/Gateway/Http/Client/TransactionCapture.php on line 131

M2.4.6-p1

**Comment by candemiralp** [comment]
Hello @dronerdk,

Thank you for raising this issue. We've created a ticket to solve this issue.

Best Regards,
Can

**Comment by dronerdk** [comment]
Thanks a lot!

When will this be implemented in a release?

**Comment by dronerdk** [comment]
Hello

Is this fix in the latest release?

**Comment by nareshanjuru** [comment]
The issue got resolved in the release 8.22.4

**Comment by candemiralp** [comment]
Hello all,

Following PRs have been released to address and solve this issue.

https://github.com/Adyen/adyen-magento2/pull/2302
https://github.com/Adyen/adyen-magento2/pull/2304

Thank you for your contribution.

Best Regards,
Can
