### ISSUE TITLE
Checkout is loading Google Fonts (Potential for GDPR Violation?)

### ISSUE THREAD

**Issue by amenk** [Adyen/adyen-magento2#2281]
**Describe the bug**

As long as Google Pay is provided in the Checkout, a connection to fonts.googleapis.com is made

**To Reproduce**
1. In the consent manager of your choice (we use consentmanager.net) don't allow google fonts
2. Go to checkout (Onestep checkout)
3. Check the network tab
4. Google fonts are loaded

**Expected behavior**

Google fonts are only loaded if the user gives consent.

**Magento version**
2.4.5

**Plugin version**
8.10.0

**Screenshots**
![image](https://github.com/Adyen/adyen-magento2/assets/1087128/fedc9c15-056f-48c5-b4ba-36a794825c86)
**Desktop (please complete the following information):**
 - OS: Linux, Windows
 - Browser Chrome
 - Version 117

**Additional context**

In Germany there are was a wave of cease and desist letters to not use Google Fonts, so this is a quite important topic.

I guess it would be okay to load google fonts as soon as Google Pay is selected, but it is loading initially on opening the checkout.

Can this be optimized?

**Comment by candemiralp** [comment]
Hello @amenk,

Thank you for raising this issue and explaining your concern in details. However, Google Fonts is loaded by Google Pay payment component and our plugin has no control over it. This is maintained in [Adyen Web](https://github.com/Adyen/adyen-web) repository by another team.

Could you please inform them about this potential GDPR violation via their Github issues?

Best Regards,
Can
