### ISSUE TITLE
[ECP-8718] BCMC is handled as autocapture, should be manually captured

### ISSUE THREAD

**Issue by ebaschiera** [Adyen/adyen-magento2#2314]
**Describe the bug**
payments with BCMC are handled as "not manually capturable", so Magento creates Invoice as soon as the authorization notification is processed. This leads to a situation where Magento cannot capture the payment and the payment is authorized indefinetly (it will expire if not manually captured in Adyen CA).

**To Reproduce**
1. Set capture delay to "manual" in Magento configuration
2. Set Adyen merchant account to manual capture
3. make a purchase with BCMC
4. See the order has an invoice, but the payment is still authorized

**Expected behavior**
The order should not have an invoice created at payment authorization. The order should behave like if it was paid with a credit card: manual invoice creation with online capture should be possible. The payment should be captured at invoice creation.

**Magento version**
2.4.2

**Plugin version**
8.18.1

Thanks!

**Comment by candemiralp** [comment]
Hello @ebaschiera,

Thank you for raising this issue. We created an internal ticket to solve this one.

Best Regards,
Can
