### ISSUE TITLE
[ECP-8729] MobilePay missing

### ISSUE THREAD

**Issue by dronerdk** [Adyen/adyen-magento2#2322]
In lastest version 9.02 the payment method is not present in checkot.

M2.4.6-p1

https://www.adyen.com/da_DK/betalingsmetoder/mobilepay?utm_source=Google&utm_medium=Online%20Advertising&utm_campaign=2022.00-SEA-DK-Brand_Broad&gclid=EAIaIQobChMInOCz3qGrggMVQZFoCR2qKA6IEAAYAyAAEgJZbPD_BwE

**Comment by candemiralp** [comment]
Hello @dronerdk,

Thanks for raising this issue. We created a ticket to implement this payment method.

Best Regards,
Can

**Comment by dronerdk** [comment]
Status?

**Comment by dronerdk** [comment]
Hello

Do you have a status?

**Comment by candemiralp** [comment]
Hello @dronerdk,

Our apologies for the late response. Since we had 2 Github issues related to MobilePay, we missed to respond this one unfortunately.

MobilePay has been implemented with PR #2512 and has been released on version 9.2.0.

Best regards,
Can
