### ISSUE TITLE
 The required string "[accepted]" is not in the result.

### ISSUE THREAD

**Issue by urkekega94** [Adyen/adyen-magento2#2327]
The bug is happening when you sucessfully fullfill the order from Magento side and webhook for Authorisation breaks with the error from the title.

**To Reproduce**
1. Go to site
2. Place something in the cart 
3. Pay with IDeal or creadit card (both having same issue)
4. Go to Adyen Dashboard and see history of events

**Expected behavior**
It should go thru Authorisation and return proper status of the order, in this case we end up with Pending status. 

**Magento version**
2.4.5-p3

**Plugin version**
9.0.2

**Comment by skeutmeier** [comment]
I have the same problem in 2.4.6-p2

**Comment by candemiralp** [comment]
Hello @urkekega94,

Thank you for raising this issue. I've tried the below steps to reproduce the issue without any success. At the end, I got a successful `Authorisation` webhook processed and my order status went to `processing`.

1. Capture mode was set to `immediate`
2. Placed the order with iDeal and Credit Card
3. Processed the `Authorisation` webhook successfully. 

Could you please provide more specific information like screenshot or exception message for us to try to reproduce it again?

Best Regards,
Can

**Comment by AW3i** [comment]
Hello @candemiralp,

We recently upgraded the module to 9.0.2 as well and have issues with the Webhooks failing. 

It seems that the configured API URL Endpoint is missing. When firing the Webhook to
` <store-url>/<store>/adyen/process/json `
the response is a **302 - Found** instead of a **200 - accepted**.

Until this is resolved we downgraded to 8.22.4 where the Webhooks work as they used to.

**Magento version:** 2.4.5-p5

**Comment by urkekega94** [comment]
> Hello @urkekega94,
> 
> Thank you for raising this issue. I've tried the below steps to reproduce the issue without any success. At the end, I got a successful `Authorisation` webhook processed and my order status went to `processing`.
> 
>     1. Capture mode was set to `immediate`
> 
>     2. Placed the order with iDeal and Credit Card
> 
>     3. Processed the `Authorisation` webhook successfully.
> 
> 
> Could you please provide more specific information like screenshot or exception message for us to try to reproduce it again?
> 
> Best Regards, Can

Hello Can,

Thanks for the reply. Maybe it's gonna be easier to connect it and reproduce it withing our support ticket that we created on Adyen Dashboard.
Case number is : Case 03163806

Thanks in advance.

**Comment by mdlatzee** [comment]
Same issue here. Please let me know @candemiralp if you need any more information.

**Comment by Nuranto** [comment]
Same issue here. Magento 2.4.6-p3 / Adyen 9.0.2

**Comment by Nuranto** [comment]
Hi guys,

I just looked into it, and it seems that they changed the webhook route :  

Where in v8 it was `adyen/process/json`, in v9 it now is : `adyen/webhook/index`.

**Comment by candemiralp** [comment]
Hello all,

As @Nuranto mentioned webhook processing endpoing has changed on V9. You can find the details on [Migration guide](https://docs.adyen.com/plugins/adobe-commerce/migrate-to-a-new-version/#step-4-change-your-webhook-server-configuration).

Best Regards,
Can

**Comment by mdlatzee** [comment]
@candemiralp has this been fixed in the 9.0.3 release?

**Comment by sanganinamrata** [comment]
@candemiralp Any Fixes of this issue? Two of my live clients were facing the same issue.
