### ISSUE TITLE
number_of_installments is missing

### ISSUE THREAD

**Issue by jonathanribas** [Adyen/adyen-magento2#2346]
**Describe the bug**

**To Reproduce**
1. Place an order with Credit Card chosing more than 1 installment
2. Go to backoffice order view
3. I can't see I've placed an order with installments on payment block from sales order view.
4. `number_of_installments` is also missing inside `additional_information` field from `sales_order_payment` table.
5. I can see the number of installments inside Adyen's backoffice.

**Expected behavior**
I should see the number of installments on payment block from sales order view.

**Magento version**
2.4.6-p2

**Plugin version**
8.19.1

**Comment by jonathanribas** [comment]
Hi @candemiralp, 

Magento: 2.4.8-p4
Adyen: 10.5.5

Placing an order on a Brazilian website, I choose 4 installments on checkout:

I can't see installments from backoffice sales order view and number_of_installments is not present inside sales_order_payment additional_information.

**Comment by candemiralp** [comment]
Hello @jonathanribas,

After checking on v10.5.5 and v10.9.0, I am still not able to reproduce the issue. Could you please add some breakpoints to observe [AdyenCcDataAssignObserver](https://github.com/Adyen/adyen-magento2/blob/359ce2d9fb21b8f219c8c60b37825929305ceef4/Observer/AdyenCcDataAssignObserver.php#L140)?

Before processing webhook
<img width="339" height="181" alt="Image" src="https://github.com/user-attachments/assets/f74c5233-b4a5-47d7-9e04-661c3c5be58e" />

After processing webhook
<img width="363" height="309" alt="Image" src="https://github.com/user-attachments/assets/75277d1c-522e-4556-987b-263c8dd6f917" />

Best Regards,
Can

**Comment by jonathanribas** [comment]
@candemiralp, thanks for your reply.

Actually we have a double mutation in order to avoid 2 consecutive calls, that's why it's resetting installments :(

`setPaymentMethodOnCart(input: { cart_id: $cartId, payment_method: $paymentMethod }) {
      cart {
        selected_payment_method {
          code
          title
        }
      }
    }

    placeOrder(input: { cart_id: $cartId, operator: $operator }) {
      order {
        order_number
        cart_id
        adyen_payment_status {
          isFinal
          resultCode
          additionalData
          action
        }
      }
    }`

**Comment by candemiralp** [comment]
Hello @jonathanribas,

Thank you for the additional information. I've successfully reproduced the issue and created an internal ticket to solve the matter. 

Best Regards,
Can
