### ISSUE TITLE
Gender field layout in HPP not ok.

### ISSUE THREAD

**Issue by victorhuisman** [Adyen/adyen-magento2#236]
**Magento version**: 2.x.x
**Plugin version**: 2.1.3
**Description**
In the hpp page, the layout of the gender field is not rendered ok. See pull request https://github.com/Adyen/adyen-magento2/pull/235.

**Comment by rikterbeek** [comment]
Hi @victorhuisman,

Thanks for the PR this solves this problem.

Regards,
Rik
Adyen
