### ISSUE TITLE
Order email can be sent twice

### ISSUE THREAD

**Issue by Cornoud** [Adyen/adyen-magento2#24]
Within cron.php no check is done if the order email already has been sent.
If  _authorizePayment is called twice or case Notification::PENDING: hits twice (or a combination of the two) the customer will receive multiple order confirmation emails.

**Comment by rikterbeek** [comment]
Hi Cornoud,

Thanks for letting us know. Indeed in Magento2 there is no check if the order confirmation is send. I added this check in our code see commit below.

Regards,
Rik
Adyen
