### ISSUE TITLE
[ECP-8855] Notification executed with a non logical order

### ISSUE THREAD

**Issue by dimitriBouteille** [Adyen/adyen-magento2#2409]
**Describe the bug**

We found a bug in the case where an order has several payment attempts. In our case, the notification for the first payment attempt (which is failing) was executed after the payment success notification, it is not very logical. So Magento is a bit lost ... 

![image](https://github.com/Adyen/adyen-magento2/assets/34821762/3d776172-ea7c-4322-a092-b636d04d1d65)

As you can see, the customer tried to pay several times and Magento received 2 notifications. The notification for PSP `BQ5S2Q8SS4K4J4C2` was executed after `X53Z3SPFFFLNTM52` :(

![Capture d’écran du 2023-12-22 11-33-28](https://github.com/Adyen/adyen-magento2/assets/34821762/8ec70594-fe5f-498f-b74a-7ca1d83c70ba)

![Capture d’écran du 2023-12-22 11-19-08](https://github.com/Adyen/adyen-magento2/assets/34821762/9aec9e89-e332-4dc3-854f-9f779066c8d1)

**To Reproduce**

Here is a proposal to try to reproduce the bug: 

- Place order with invalid card
- Waiting 1-2 minutes
- Try place order with valid card
- The payment is validated and the order is created

If everything goes well, Magento should receive 2 notifications for the 2 payment attempts.

- 1 notification with status success `false`
- 1 notification with status success `true`

![Capture d’écran du 2023-12-22 11-19-08](https://github.com/Adyen/adyen-magento2/assets/34821762/9aec9e89-e332-4dc3-854f-9f779066c8d1)

**Expected behavior**

The notification of the first payment attempt should be executed **FIRST** and then the notification for the second payment attempt should be executed.

Generally, notifications should be executed in the same order as payment attempts.

**Details**

- Magento Version: `2.4.5-p5`
- Plugin version: `8.7.0`

**Additional context**

Here is an example of a PSP for which we had a problem: `BQ5S2Q8SS4K4J4C2` and `X53Z3SPFFFLNTM52`.

**Comment by hossam-adyen** [comment]
Hi @dimitriBouteille, from the plugin prospective, it just receiving and handling notification in FIFO terms 'first come first serve' and have no control on the order of the received notifications, but even with the delayed notification, what is the impact on your order processing? do those delayed notifications breaking that flow?

**Comment by dimitriBouteille** [comment]
Hey @hossam-adyen 

Thank for details, he still has a problem.

If there are several PSP for an order as in my case, it is the reference in error that is displayed in Magento ... When I look at the table of payments in Adyen, the order is consistent:

 - **BQ5S2Q8SS4K4J4C2**: Dec 16, 2023, 18:29:27
-  **X53Z3SPFFFLNTM52**: Dec 16, 2023, 18:32:54

In  `Payment Information` section, the **X53Z3SPFFFLNTM52** must be displayed !

![Capture d’écran du 2023-12-28 17-32-02](https://github.com/Adyen/adyen-magento2/assets/34821762/abe67d68-2b67-4a85-a284-513e3570e497)

![image](https://github.com/Adyen/adyen-magento2/assets/34821762/0b45e4c2-4477-4cab-ad29-cc20737784c5)

**Comment by hossam-adyen** [comment]
Hi @dimitriBouteille, thanks for providing more context, we added in our internal backlog and will keep you posted here once it got fix

**Comment by candemiralp** [comment]
Hello @dimitriBouteille,

This issue has been fixed and the PR will be released soon.

Best Regards,
Can
