### ISSUE TITLE
Notification model `getUpdatedAt` method takes `created_at` date

### ISSUE THREAD

**Issue by pawel-ledwig** [Adyen/adyen-magento2#2416]
**Describe the bug**
Notification model `getUpdatedAt` method takes `created_at` date instead of `updated_at` date.

**Expected behavior**
Notification model `getUpdatedAt` method takes `updated_at` date.

**Magento version**
Any

**Plugin version**
9.0.4

**Comment by candemiralp** [comment]
Hello @pawel-ledwig,

Thanks for raising this issue and creating a fix for it. This issue will be closed after merging the PR.

Best Regards,
Can
