### ISSUE TITLE
[ECP-8889] Indentation caused by opening same container twice

### ISSUE THREAD

**Issue by aweb3r** [Adyen/adyen-magento2#2424]
Plugin Version: 9.0.5
Adobe Version: 2.4.6-p3
Step-by-step Flow to Reproduce the Issue: Go to Checkout -> Payment Step
Any Customizations Made in Place: none

Opening the same container twice ( `<div class="payment-method-title field choice">` ) creates an indentation of the Adyen Payment Methods:

![image](https://github.com/Adyen/adyen-magento2/assets/20281771/afd3ed77-243b-4507-9f84-ccfeacf8e06d)

**Comment by aweb3r** [comment]
@khushboo-singhvi done.

**Comment by khushboo-singhvi** [comment]
Hello @aweb3r,

Thank you for all the details provided. 
We have opened an internal ticket to check and solve the duplicacy.

Regards!
Khushboo

**Comment by aweb3r** [comment]
any updates?

**Comment by khushboo-singhvi** [comment]
Hey @aweb3r,

Thank you for waiting on it patiently, but we are still in process to address the issue. I assure you that it will be soon picked up and we will inform you.

Regards!
Khushboo
