### ISSUE TITLE
[ECP-8890]Wrong helper dependency usage in Payment Request API model

### ISSUE THREAD

**Issue by antonio30111988** [Adyen/adyen-magento2#2427]
**Describe the bug**
Call to undefined method Adyen\\Config::getAdyenAbstractConfigData() at /app/xxxx/vendor/adyen/module-payment/Model/Api/PaymentRequest.php:175)

**To Reproduce**
1. Go to 'recurring payment request 
2. See error

**Expected behavior**
No error
**Magento version**
[e.g. 2.4.6]

**Plugin version**
[e.g. 9.0.5]

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by antonio30111988** [comment]
Fix: 
- use **adyenHelper** instead of **configHelper** inside mentioned file

**Comment by khushboo-singhvi** [comment]
Hey @antonio30111988,

Thank you for bringing the reported issue to our attention. To address this matter promptly, we have opened an internal ticket for thorough investigation and resolution.

We will keep you informed about the progress and any updates related to the investigation. If you have any additional information, insights, or questions, please feel free to share them with us.

Thank you for your cooperation and understanding.

Regards!
Khushboo
