### ISSUE TITLE
GraphQL : Installment not valid errors.

### ISSUE THREAD

**Issue by marc-arnoult** [Adyen/adyen-magento2#2428]
Making your own contribution is easy, encouraged and greatly appreciated! We will put effort into reviewing and merging your PR quickly. For more info, please refer to the contribution guidelines: https://github.com/Adyen/adyen-magento2/blob/develop/CONTRIBUTING.md

**Describe the bug**
When we pay with installment on GraphQL method, we always have the error message : `Installments not valid.`

The order is OK on Magento and Adyen, payment is well made with the good amount of installment.
payload : 

```
[
  {
    "stateData": {
      "riskData": {
        
      },
      "paymentMethod": {
        "type": "scheme",
        "holderName": "",
        "encryptedSecurityCode": "",
        "storedPaymentMethodId": "BH7WNMQRZPBDVP65",
        "brand": "visa",
        "checkoutAttemptId": ""
      },
      "installments": {
        "value": 2
      },
      "browserInfo": {
        "acceptHeader": "*/*",
        "colorDepth": 24,
        "language": "en-US",
        "javaEnabled": false,
        "screenHeight": 1080,
        "screenWidth": 1920,
        "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
        "timeZoneOffset": -60
      },
      "clientStateDataIndicator": true,
      "storePaymentMethod": true
    },
    "recurringProcessingModel": "CardOnFile"
  }
]
```
response : 
```
{
    "errors": [
        {
            "message": "Installments not valid.",
            "locations": [
                {
                    "line": 2,
                    "column": 3
                }
            ],
            "path": [
                "setPaymentMethodOnCart"
            ],
            "extensions": {
                "category": "graphql-input"
            }
        }
    ],
    "data": {
        "setPaymentMethodOnCart": null,
        "placeOrder": {
            "order": {
                "order_number": "102000102261_K8S",
                "cart_id": "xyCYOnR3YXDyPtuTrsqx2HNEcbJ5N30D",
                "adyen_payment_status": {
                    "isFinal": true,
                    "resultCode": "Authorised",
                    "additionalData": null,
                    "action": null,
                    "__typename": "AdyenPaymentStatus"
                },
                "__typename": "Order"
            },
            "__typename": "PlaceOrderOutput"
        }
    }
}
```

**To Reproduce*.*
Make an order with installment on with GraphQL.

**Expected behavior**
We should not have an error message when everything is fine.

**Magento version**
2.4.6-p2

**Plugin version**
8.22.4

**Desktop (please complete the following information):**
 - OS: OS X
 - Browser: Chrome
 - Version: 120.0

**Smartphone (please complete the following information):**

**Additional context**

**Comment by candemiralp** [comment]
Hello @marc-arnoult,

Thanks for creating this issue. I checked your comments and tried to reproduce it. I partially succeeded when I didn't configure the installation options properly on the plugin configuration page.

[InstallmentValidator](https://github.com/Adyen/adyen-magento2/blob/ea3b60cfd8f01ab7f91792b1195aac215622ceb1/Gateway/Validator/InstallmentValidator.php#L71) is responsible for validating the input data. If you don't configure `Installments Setup` properly under `Card Payments`, you will end up with getting this error message.

However, I see another issue here that validator doesn't stop the order placement action even though the validation has failed. I will create an investigation ticket for this.

Could you please try to configure installments on the configuration page and be sure that your GraphQL request contains [number_of_installments](https://github.com/Adyen/adyen-magento2/blob/ea3b60cfd8f01ab7f91792b1195aac215622ceb1/etc/schema.graphqls#L127) field in it?

Best Regards,
Can

**Comment by candemiralp** [comment]
Closing this issue since there is no response. Please re-open this issue if the error is persistent.
