### ISSUE TITLE
[ECP-8972][ECP-8902] Giftcard payment (GraphQL) not working anymore in V9

### ISSUE THREAD

**Issue by bramstroker** [Adyen/adyen-magento2#2430]
**Describe the bug**
We are in the process of upgrading module from V8 to V9, however we have troubles getting the giftcards working again.
Previously with same GraphQL request (see in reproduction steps) everything was working fine.
Please advice how we can make a succesfull giftcard order.

**To Reproduce**
1. Enable giftcard in adyen backend
2. Enable alternative payment methods in Magento backend
3. Using GraphQL, create empty cart, add products, address, guestEmail etc.
4. Execute GraphQL query to set the giftcard payment method and placeOrder:

```graphql
mutation setPaymentMethodAndPlaceOrder(
    $cartId: String!, $paymentMethod: PaymentMethodInput!
) {
    setPaymentMethodOnCart(
        input: {
            cart_id: $cartId
            payment_method: $paymentMethod
        }
    ) {
        cart {
            selected_payment_method {
                code
                title
            }
        }
    }

    placeOrder(
        input: {
            cart_id: $cartId
        }
    ) {
        order {
            order_number
            adyen_payment_status {
                isFinal
                resultCode
                additionalData
                action
            }
        }
    }
}
```

*paymentMethod input*
```json
{
	"code": "adyen_hpp",
	"adyen_additional_data": {
		"brand_code": "genericgiftcard",
		"stateData": "{\"paymentMethod\":{\"type\":\"giftcard\",\"brand\":\"genericgiftcard\"}}"
	}
}
```

This results in error: `Unable to place order: Error with payment method, please select a different payment method.`

Error from Adyen error log:

`Required object 'paymentMethod' is not provided.`

Also tried following combinations to no avail:

```json
{
	"code": "adyen_giftcard",
	"adyen_additional_data": {
		"brand_code": "genericgiftcard",
		"stateData": "{\"paymentMethod\":{\"type\":\"giftcard\",\"brand\":\"genericgiftcard\"}}"
	}
}
```

and

```json
{
	"code": "adyen_giftcard",
	"adyen_additional_data": {
		"brand_code": "giftcard",
		"stateData": "{\"paymentMethod\":{\"type\":\"giftcard\",\"brand\":\"genericgiftcard\"}}"
	}
}
```

**Expected behavior**
Order is placed succesfully and we get a redirectURL to the hosted payment page.

**Magento version**
2.4.6-p3

**Plugin version**
9.0.5

**Additional context**

ideal is working fine.

Output of Magento available_payment_methods:

```json
{
	"data": {
		"cart": {
			"available_payment_methods": [
				{
					"code": "adyen_ideal",
					"title": "iDeal"
				},
				{
					"code": "adyen_cc",
					"title": "Credit Card"
				},
				{
					"code": "adyen_klarna",
					"title": "Klarna"
				},
				{
					"code": "adyen_giftcard",
					"title": "Giftcard"
				},
				{
					"code": "adyen_klarna_account",
					"title": "Klarna Pay over Time"
				},
				{
					"code": "cashondelivery",
					"title": "Betaling bij levering"
				},
				{
					"code": "adyen_cc_vault",
					"title": "Stored Cards (Adyen)"
				},
				{
					"code": "adyen_klarna_vault",
					"title": "Stored Klarna"
				},
				{
					"code": "adyen_pos_cloud",
					"title": "Adyen POS Cloud API"
				}
			]
		}
	}
}
```

Output of adyen payment methods:

```json
{
	"data": {
		"adyenPaymentMethods": {
			"paymentMethodsResponse": {
				"paymentMethods": [
					{
						"name": "iDEAL",
						"type": "ideal",
						"issuers": [
							{
								"id": "1121",
								"name": "Test Issuer"
							},
							{
								"id": "1154",
								"name": "Test Issuer 5"
							},
							{
								"id": "1153",
								"name": "Test Issuer 4"
							},
							{
								"id": "1164",
								"name": "SNS"
							},
							{
								"id": "1152",
								"name": "Test Issuer 3"
							},
							{
								"id": "1163",
								"name": "Ideal bridge test issuer"
							},
							{
								"id": "1151",
								"name": "Test Issuer 2"
							},
							{
								"id": "1162",
								"name": "Test Issuer Cancelled"
							},
							{
								"id": "1161",
								"name": "Test Issuer Pending"
							},
							{
								"id": "1160",
								"name": "Test Issuer Refused"
							},
							{
								"id": "1159",
								"name": "Test Issuer 10"
							},
							{
								"id": "1158",
								"name": "Test Issuer 9"
							},
							{
								"id": "1157",
								"name": "Test Issuer 8"
							},
							{
								"id": "1156",
								"name": "Test Issuer 7"
							},
							{
								"id": "1155",
								"name": "Test Issuer 6"
							}
						],
						"brands": null,
						"details": null
					},
					{
						"name": "Credit Card",
						"type": "scheme",
						"issuers": null,
						"brands": [
							"mc",
							"visa",
							"maestro"
						],
						"details": null
					},
					{
						"name": "Achteraf betalen. Klarna.",
						"type": "klarna",
						"issuers": null,
						"brands": null,
						"details": null
					},
					{
						"name": "Generic GiftCard",
						"type": "giftcard",
						"issuers": null,
						"brands": null,
						"details": null
					},
					{
						"name": "Gespreid betalen. Klarna.",
						"type": "klarna_account",
						"issuers": null,
						"brands": null,
						"details": null
					}
				]
			},
		}
	}
}
```

**Comment by candemiralp** [comment]
Hello @bramstroker,

Adyen has deprecated hosted payment pages a while ago ([reference](https://docs.adyen.com/online-payments/classic-integrations/hosted-payment-pages/deprecation/)). Our giftcard implementation on V8 relies on hosted payment pages with a redirect. However, after this deprecation, we've implemented new giftcard flow which uses Adyen's [Order API](https://docs.adyen.com/api-explorer/Checkout/71/post/orders) on V9. 

With this new flow, you can redeem multiple giftcards and pay the rest with complementary payment method. Although [this](https://docs.adyen.com/plugins/adobe-commerce/migrate-to-a-new-version/#step-6-verify-changes-Uto-the-gift-card-flow) part of the migration guide to V9 mentions giftcard flow changes, some of the technical documentation is still missing. I will create an internal ticket to update the headless documentation.

You can check out default Luma frontend to see our implementation of new giftcards flow. If you don't have a fresh instance feel free to use our example [Gitpod repository](https://github.com/adyen-examples/adyen-magento-plugin-demo).

You will be informed when the docs are ready and thank you for raising this issue.

Best Regards,
Can

**Comment by bramstroker** [comment]
@candemiralp Thanks for the heads up. Looking forward to the new docs for headless integration.

**Comment by mmurakami** [comment]
@candemiralp I just saw you merged in some code update and closed this ticket. Does that mean we have to pick up a certain V9 version to get fixed? If so, would you let us know when it's released?
Also, is `setPaymentMethodOnCart` now expect any different data to be passed on? The documentation you mentioned before, if it's updated, please let us know!
