### ISSUE TITLE
adyen.createEncryption when placing an order

### ISSUE THREAD

**Issue by VincentMarmiesse** [Adyen/adyen-magento2#245]
**Magento version**: 2.2.2
**Plugin version**: 2.2.0
**Description**

Hello,

I have the following error when I try to place an order:
```
Uncaught TypeError: adyen.createEncryption is not a function
    at UiClass.placeOrder (adyen-cc-method.js:172)
    at HTMLButtonElement.<anonymous> (knockout.js:3863)
    at HTMLButtonElement.dispatch (jquery.js:5226)
    at HTMLButtonElement.elemData.handle (jquery.js:4878)
```

The store I'm working on has some heavy customization so I think I removed something Adyen needs but I don't find where this `createEncryption` function is supposed to be.

Is it a file or something which should be included?

Thanks for the help!

**Comment by rikterbeek** [comment]
Hi @VincentMarmiesse,

Can you please make sure you set the Library token of Test/Live Adyen Web Service User on your environment under Adyen CreditCard API Integration?

Regards,
Rik
Adyen

**Comment by VincentMarmiesse** [comment]
Hi @rikterbeek,

Indeed, I missed that part, it works after filling the config.

Thanks!
