### ISSUE TITLE
[ECP-8933] [V9] Support swish method

### ISSUE THREAD

**Issue by dimitriBouteille** [Adyen/adyen-magento2#2468]
In V9, `swish` method not available in `etc/config.xml`, Please add `swish` method :heart: 

https://www.adyen.com/fr_FR/moyens-de-paiement/swish

**Comment by khushboo-singhvi** [comment]
Hello @dimitriBouteille 

Thank you for bringing this to our attention. We want to assure you that we are actively working on the adding new payment methods, and we have created an internal ticket for it. 

We appreciate your patience and understanding as we work to address this. If you have any further questions or if there's anything else you'd like to discuss, feel free to let us know.

Regards!
Khushboo

**Comment by khushboo-singhvi** [comment]
Hey @dimitriBouteille, 
Hope you are doing good!
We already had this PaymentMethod with the attached [PR](https://github.com/Adyen/adyen-magento2/pull/2203)
