### ISSUE TITLE
Known issues are missing from release notes

### ISSUE THREAD

**Issue by maaarghk** [Adyen/adyen-magento2#2473]
An example: #2471 

i filed this report after upgrading to 9.0.7 caused a client's production site to stop processing payments

afterwards we (users) get to be aware that an internal ticket numbered ECP-8903 already exists for this bug.

based on ECP-8902 being given to an issue reported 3 weeks ago, this bug has been known _at least_ since 9.0.5.

if the release notes had included a "known issues" section stating (among other things) "merchants who use the queue to process webhooks should temporarily disable this functionality or postpone upgrading" then i wouldn't have wasted time on (a) filing a (basically duplicate) bug report; (b) actually doing the upgrade when it's known my client's config wouldn't be compatible

**Comment by khushboo-singhvi** [comment]
Hello @maaarghk,

Thank you for bringing this to our attention, and we sincerely apologize for any inconvenience this may have caused. Your feedback is invaluable to us.

We acknowledge the importance of documenting known issues, and we regret the oversight in the last release. Rest assured, we take this matter seriously, and we are committed to improving our processes.

We appreciate your understanding, and please be assured that we are taking steps to address this issue. In our upcoming releases, we will make sure to include a dedicated section for known issues to provide transparency and keep our users well-informed.

If you have any further concerns or suggestions, please don't hesitate to let us know. We greatly value your input, and your patience is highly appreciated.

Thank you for your continued support.

Regards!
Khushboo
