### ISSUE TITLE
[ECP-8941][V9] Why some methods are active in config.xml ?

### ISSUE THREAD

**Issue by dimitriBouteille** [Adyen/adyen-magento2#2474]
Why some methods are active in `etc/config.xml` ? This following methods are active by default : 

- adyen_ideal
- adyen_klarna
- adyen_paypal
- adyen_bcmc_mobile
- adyen_dotpay
- adyen_amazonpay
- adyen_googlepay
- adyen_multibanco
- adyen_facilypay_3x
- adyen_sepadirectdebit
- adyen_applepay
- adyen_giftcard

I think this is a problem, when I configure in the Magento BO with a bad configuration, all these methods are returned in graphql in `cart.available_payment_methods` ...

Is there a reason to activate these methods?

**Magento version**

2.4.6

**Plugin version**

9.0.5

**Additional context**

The `/v70/paymentMethod`s query returns an error because the credentials are not good.

![Capture d’écran du 2024-01-31 10-49-22](https://github.com/Adyen/adyen-magento2/assets/34821762/326c80eb-476c-4581-b0b4-82fcf472e284)
![Capture d’écran du 2024-01-31 10-49-51](https://github.com/Adyen/adyen-magento2/assets/34821762/092f0f16-857e-4347-ac55-e2e4e0cddd3e)

**Comment by khushboo-singhvi** [comment]
Hello @dimitriBouteille, 

Thank you for bringing this to our attention. We have created an internal investigation ticket and want to assure you that we are actively working on it.
We appreciate your contribution and understanding as we work to address this. If you have any further questions or if there's anything else you'd like to discuss, feel free to let us know.

Regards!
Khushboo
