### ISSUE TITLE
Expired payments

### ISSUE THREAD

**Issue by dronerdk** [Adyen/adyen-magento2#2489]
Hello

We have a lot of expired payments due to that we by law only can capture payment when we ship the order.
Therefor if we have backorders we often get our payment expired.

I would like to discuss a feature with you that can help with this.
The feature should work like when a payment is expired the customer should get a new payment link to be able to pay again for the order in backorder. It should work like this.

1) In adyen the payment get expired. 
2) Adyen send out a expired payment call to Magento via webook.
3) Magento should change order status to ex expired payment.
4) Magento should then send out an Adyen payment link via mail and some explanation regarding the new payment.
5) The amount of the payment link should be the same as the amount of the Total order due.
6) If the customer pays with via the payment link it can go back in the same order status flow "Authorized"
7) If the customer do not pay the order should be canceled at last.

What do you think? I did see another online store do this, on some items in backorder.

**Comment by candemiralp** [comment]
Hello @dronerdk,

Thank you for creating this Github issue. Let me discuss this enhancement with our product manager and get back to you soon.

Best Regards,
Can

**Comment by dronerdk** [comment]
Did you look into this?

**Comment by candemiralp** [comment]
Hello @dronerdk,

We are currently trying to scope this project out and reaching out to more merchants to validate this issue and the proposed solution. We will update you soon.

Best Regards,
Can

**Comment by dronerdk** [comment]
Did you get any further with this? 
We only have massive issues with the payments the is expired, so some kind of automated workflow is needed.

**Comment by dronerdk** [comment]
Could you consider this?
1) When Adyen sent the webhook to magneto, that the payment is expired that we could change the order status?

2) See the webhook in magento that we already receive, but we cannot change the status of the order, ex from approved to payment expired:
 Approved (Payment Authorized) Customer Not Notified
The order failed to update: Unsupported webhook notification: EXPIRE
