### ISSUE TITLE
Google Pay(Alternative payment method) not appearing after upgrading to the latest version 9.0.7

### ISSUE THREAD

**Issue by karmdip-magneto** [Adyen/adyen-magento2#2490]
Hello,

**Describe the bug**
I have recently upgraded to the module's latest version 9.0.7. After upgrading the extension, the Google Pay payment method stopped appearing on the checkout. We're using Magento 2.4.5-p5 in our project. I have reproduced the issue in the fresh Magento 2.4.5-p5 setup and verified the issue, it's not appearing in the fresh Magento setup as well.

**To Reproduce**
1. Upgrade the Adyen payment module to version 9.0.7 with all dependencies.
2. Go to checkout > Payment

**Expected behavior**
Google Pay should be visible as a payment method along with others.

**Magento version**
2.4.5-p5

**Plugin version**
9.0.7

**Comment by candemiralp** [comment]
Hello @karmdip-magneto,

Thanks for raising this issue. It seems like a configuration issue. If you have `paywithgoogle` TX variant set up on your Customer Area, Google Pay will not work on V9. This TX variant has been deprecated and the new one is `googlepay`. 

Could you please send a support request to `support@adyen.com` about the issue? Our support engineers will help you out about this issue and fix your payment method configuration.

Best Regards,
Can
