### ISSUE TITLE
[ECP-8984] Setup are not launched when upgrading

### ISSUE THREAD

**Issue by benjamin-volle** [Adyen/adyen-magento2#2496]
**Describe the bug**

When upgrading the module from 8.17.0 to 9.0.7, the new Setup Patches are not launched.
List of affected patches:

- Adyen\Payment\Setup\Patch\Data\CreateStatusAuthorized
- Adyen\Payment\Setup\Patch\Data\CreditCardsBecomeCards
- Adyen\Payment\Setup\Patch\Data\RatepayIdConfiguration
- Adyen\Payment\Setup\Patch\Data\RemoveMinMaxOrderConfigMigration

**To Reproduce**
1. Install the 8.17.0 version
2. Launch setup:upgrade command
3. Upgrade (via composer update) the module to 9.0.7
4. Launch setup:upgrade command
5. The patches are listed in the table "patch_list" but no "apply" function have been called

**Expected behavior**
The patches should be played.

**Magento version**
2.4.5-p3

**Plugin version**
9.0.7

**Additional context**
The issue comes from the implementation of the method "getVersion()", so the patches are skipped here : \Magento\Framework\Setup\Patch\PatchBackwardCompatability::isSkipableByDataSetupVersion

Other point : "setup_version" in the module.xml file is deprecated, and should be removed

**Comment by candemiralp** [comment]
Hello @benjamin-volle,

Thank you for creating this Github issue. We have created an investigation ticket to reproduce and find a solution to this one. You will be informed when the investigation is done.

Best Regards,
Can

**Comment by benjamin-volle** [comment]
Hi @candemiralp !

Any news on that topic ?
