### ISSUE TITLE
refunds not implemented 

### ISSUE THREAD

**Issue by Cornoud** [Adyen/adyen-magento2#25]
Refunds initiated from Adyen are not implemented. Code is quoted.
Also when buildign this function emailing the credit email to the customer should NOT be depending on orderupdate email setting but on a seperate setting (allow sent refund emails)

**Comment by rikterbeek** [comment]
Hi Cornoud,

Refunds are implemented and not quoted. See here:
https://github.com/Adyen/adyen-magento2/blob/develop/Model/Method/Cc.php#L357-L372

We do not send email for a credit memo this is native Magento functionality.

Regards,
Rik
Adyen

**Comment by Cornoud** [comment]
Hi Rik,

Within https://github.com/Adyen/adyen-magento2/blob/master/Model/Cron.php the function _refundOrder is quoted.
Also the refund is only emailed when send_update_email is enabled. This setting is also used for other emails within Adyen module which in most cases are not desired to be sent to the customer.


[cid:image001.png@01D18A74.36ECC0E0]

Kind regards,

Cornoud

**Comment by Cornoud** [comment]
Hi Rik,

When will the master branch be updated with the latest fixes?

Kind regards,

Cornoud

**Comment by rikterbeek** [comment]
Hi Cornoud,

This is because you need to do the refund from inside Magento.
If you do an online credit memo in magento it will automatically do a refund call to our platform.

Regards,
Rik
Adyen

**Comment by rikterbeek** [comment]
Hi Cornoud,

the send_update_email is not a setting from us and if I look into code from Magento2 the setting is absolute. https://github.com/magento/magento2/blob/develop/dev/tests/static/testsuite/Magento/Test/Legacy/_files/obsolete_methods.php#L1764

Regards,
Rik
Adyen

**Comment by Cornoud** [comment]
Hi Rik,

So support for refunds made in Adyen is dropped in M2?

Not all customers will do the refund from Magento.
Some of our customers do the refund from Adyen.


Kind regards.

Cornoud

**Comment by rikterbeek** [comment]
Hi Cornoud,

Why is it not done through Magento ? In Adyen partial refund is going to be diffecult to do because you do not know what items are refunded. For M1 we get the questions from merchants asking to not update magento if you do a refund on Adyen so that is why it is not included.

Regards,
Rik
Adyen

**Comment by Cornoud** [comment]
Hi Rick,

I do agree the best solution is thru magento, this what I advise to all my customers.
But I still do not like removing functionality which is present in most/all PSP implementations.

About 30% of ISM customers is still creating the refund in Adyen backoffice.
And using Magento for sending the credit email.
Reason for doing this in Adyen

-          Fulfillment such as shipments and credits within Magento,

-          Direct link between ERP and Adyen

-          Manual processing by Financial employee without access to Magento

Kind regards,

Cornoud

**Comment by rikterbeek** [comment]
Hi Cornoud,

Let me have a look this week it should not be hard to implement.

Regards,
Rik
Adyen

**Comment by rikterbeek** [comment]
Hi Cornoud,

It is diffecult to realize this because of the protected function they have introduced for prepareCreditMemo. There is a method called registerRefundNotification that is public but there is a bug in this call see: https://github.com/magento/magento2/pull/2656

Regards,
Rik
Adyen

**Comment by Cornoud** [comment]
Hi Rik,

I would suggest not building the functionality for the moment.

Thx,

Cornoud

**Comment by rikterbeek** [comment]
Hi Cornoud,

We will wait until there is a proper solution available in magento2.

Regards,
Rik
Adyen

**Comment by alessandroniciforo** [comment]
@rikterbeek it looks like [2656](https://github.com/magento/magento2/pull/2656) has been fixed. Maybe this issue can be solved now?

**Comment by rikterbeek** [comment]
Hi @alessandroniciforo,

Sorry for the late reply missed your comment.  Thanks for letting us know. We highly advise you to do refunds directly form inside Magento because of extra functionality as option to put back in stock and partial refunds of particular products. Is there a reason why you can't use this inside Magento ?

Regards,
Rik
Adyen

**Comment by alessandroniciforo** [comment]
@rikterbeek at this stage, we're just exploring all the different functionalities and while trying to issue refunds from Adyen backend I stumbled upon this commented piece of code with the reference to issue #2656 on Magento, so I thought of updating this issue.
I think we should be fine doing it inside Magento.
Thanks,
Alessandro
