### ISSUE TITLE
Incompatibility with onestepcheckout/iosc

### ISSUE THREAD

**Issue by DanieliMi** [Adyen/adyen-magento2#2504]
**Describe the bug**
After upgrading from `8.22.2` to `9.1.0` no Adyen payment methods are listed in combination with [OneStepCheckout](https://www.onestepcheckout.com/magento-2/). The issue seems similar to #2492.

**To Reproduce**
1. Have OneStepCheckout installed
2. Add a product to the cart
3. Go to the checkout

**Expected behavior**  
All available Adyen payment methods are listed.

**Actual behavior**  
No Adyen payment methods are shown.

**Magento version**  
2.4.6-p3

**Plugin version**  
9.1.0

**Additional context**
I have tried modifying the initialization method like mentioned in #2492 and then at least the credit card payment method is shown. Other `adyen_hpp` methods are still missing.

**Comment by hossam-adyen** [comment]
Hi @DanieliMi, thanks for reporting this issue, I'm going to close this one as it was reported already before https://github.com/Adyen/adyen-magento2/issues/2492
