### ISSUE TITLE
[ECP-9042] Usage of unexisting AdyenBoletoConfigProvider class

### ISSUE THREAD

**Issue by aelmizeb** [Adyen/adyen-magento2#2505]
**Describe the bug**
There is a use of unexisting class on the code
use Adyen\Payment\Model\Ui\AdyenBoletoConfigProvider;

file : vendor/adyen/module-payment/Gateway/Request/CheckoutDataBuilder.php

**To Reproduce**
check the code

**Expected behavior**
No dead code

**Magento version**
2.4.6-p3

**Plugin version**
9.1.0

**Screenshots**
![image](https://github.com/Adyen/adyen-magento2/assets/19288561/2a51818a-d5a8-46c8-a5d7-0808f04c39fe)

**Additional context**
- NA

**Comment by hossam-adyen** [comment]
Hi @aelmizeb, thanks for pointing out this and report this issue, this sounds a good PR to introduce to this repository, would you mine to open a PR with this change?

**Comment by candemiralp** [comment]
Hello @aelmizeb,

Thanks for creating this issue. We've created a fix for this issue and it will be merged soon.

Best Regards,
Can
