### ISSUE TITLE
Version 2.2.0 doesn't compile in Magento 2.1.7

### ISSUE THREAD

**Issue by danielozano** [Adyen/adyen-magento2#251]
**Magento version**: 2.1.7
**Plugin version**: 2.2.0
**Description**
When trying to compile `bin/magento setup:di:compile` I get the following error: `PHP Fatal error:  Class 'PHPUnit\Framework\TestCase' not found in module-path/adyen/module-payment/tests/Helper/DataTest.php on line 29`

The problem seems to be related to the PHPUnit version:
 - [4.1.0](https://github.com/magento/magento2/blob/2.1/composer.json#L70) for magento 2.1.*
 - [6.2.0](https://github.com/magento/magento2/blob/2.2/composer.json#L76) for magento 2.2.*

Both versions of PHPUnit are no backward compatible, for example in 4.1.0 the naming convention doesn't follow camelcase: `\PHPUnit_Framework_TestCase`

## Steps to Reproduce
 -  Install Magento 2.1.*
 - Try to compile: `bin/magento setup:di:compile`

**Comment by lancergr** [comment]
Hi @danielozano 

This is indeed related to phpunit version of Magento. 
It has been fixed here: https://github.com/Adyen/adyen-magento2/commit/52b17c07aa6989072840cbe9a1054c4f3301e1e8 and merged to develop branch. It will be included on the next release!

Kind Regards,
Giorgos
Adyen
