### ISSUE TITLE
[ECP-9041] Alternative payment methods content created inside title

### ISSUE THREAD

**Issue by albertoDigio** [Adyen/adyen-magento2#2531]
**Describe the bug**
The payment-method-content in altenative payment methods are being created inside payment-method-title

![issue_front](https://github.com/Adyen/adyen-magento2/assets/89900405/0973419b-092a-4f9f-9c37-0f8ed24c6b16)
![issue_code](https://github.com/Adyen/adyen-magento2/assets/89900405/d15960e6-7c11-4b1d-8729-3ad28522a040)

**Magento version**
2.4.5-p6

**Plugin version**
Adyen 2.9.0

**Comment by candemiralp** [comment]
Hello @albertoDigio,

Thank you for creating this Github issue. We've created a fix for it and it will be merged soon.

Best Regards,
Can
