### ISSUE TITLE
[V9] Payment methods are not in the same order as defined in Adyen BO

### ISSUE THREAD

**Issue by dimitriBouteille** [Adyen/adyen-magento2#2549]
**Describe the bug**

As indicated in this [documentation](https://help.adyen.com/knowledge/plugins/adobe-commerce/how-can-i-change-the-order-of-the-payment-methods-adobe-commerce), it is possible to change the order of payment methods in the Adyen interface.

Adyen :

![Capture d’écran du 2024-03-08 12-26-54](https://github.com/Adyen/adyen-magento2/assets/34821762/7e7ff842-f521-4d02-8d44-9623a94de720)

Magento graphQl `cart.available_payment_methods result` :

![Capture d’écran du 2024-03-08 12-28-17](https://github.com/Adyen/adyen-magento2/assets/34821762/ca6631f7-a93d-47a3-9ac3-1c557c3b946f)

This query should return the methods in this order:

- `adyen_cc`
- `adyen_zip`
- `adyen_applepay`

**To Reproduce**

- Setup payment method position in Adyen | `Customer Area  > Account > Checkout`.
- Enable `Payment methods enabled` option in Magento | `Configuration > Sales > Payment Methods > Adyen > Accepting payments > Payment methods`.
- Go to checkout
- 🔥 See that the payment methods are not sorted in the right order

**Expected behavior**

Payment methods must be in the same order as defined in Adyen.

**Additional context**

- Magento version: `2.4.6`
- Plugin version: `9.2`

**Comment by thaulow** [comment]
I still have this issue...  

<img width="685" alt="Screenshot 2024-10-19 at 13 49 09" src="https://github.com/user-attachments/assets/306a778f-4fd7-4d04-88b9-9584c6b77fa9">
<img width="784" alt="Screenshot 2024-10-19 at 13 49 15" src="https://github.com/user-attachments/assets/5c774ead-5015-47fc-a2e4-1bd804d51987">
