### ISSUE TITLE
[QUESTION] SEPA payments status change

### ISSUE THREAD

**Issue by danielozano** [Adyen/adyen-magento2#256]
**Magento version**: 2.1.7
**Plugin version**: 2.1.3
**Description**
It's just a question, not a bug at the moment. Testing sepa transactions (oneclick + ideal and directly sepa as payment method), I get the payment inside the adyen platform but I don't receive the notification back into M2 (If I enable direct debit and bank transfer notifications in adyen I get the pending notification).
If sepa payments have a settlement period of 2 days, in the test environment do I've to way 2 days to get the payment notification (authorisation) back in M2 for finishing the order process?

Thanks!

**Comment by rikterbeek** [comment]
Hi @danielozano,

Indeed if you are using SEPA in the sale method (what is the default) then when the money is settled you will receive the AUTHORISATION notification that updates the order in magento. This normally takes a day or so.

Regards,
Rik
Adyen

**Comment by danielozano** [comment]
Hi @rikterbeek,

Thanks a lot for the fast confirmation, thought I was doing something wrong. Could be great in the test environment to force that settlement, I'll wait then!

Regards
