### ISSUE TITLE
Add support for Hyvä Checkout

### ISSUE THREAD

**Issue by kweij** [Adyen/adyen-magento2#2562]
We want to make use of the Hyvä Checkout, which is an alternative to Luma-based checkout, delivers a huge improvement in performance and is built on current tech (Tailwind, AlpineJS, Livewire/Magewire).

However, in order to be able to continue using Adyen, the integration with Magento needs to support the Hyvä Checkout. I would love to see official support for the Hyvä Checkout provided by Adyen itself.

The community of developers working with Hyvä is growing and so is the number of shops using it. Hyvä provides a community built integration module for Adyen. I have tried it, but it is incomplete and troubled with blocking issues preventing us from using it. Also, this module only supports Adyen v8, preventing us from upgrading the Adyen payments module.

Please take the the shops based on Hyvä in consideration for official support ❤️ 

Edit: I got the community built integration module I mentioned working (with some patches).

**Comment by candemiralp** [comment]
Hello @kweij,

Thank you for reporting this enhancement. We are currently looking into it and will update you once we find a solution.

Best Regards,
Can

**Comment by ThijsdejongSNC** [comment]
+1 for Hyva support!

**Comment by Funfelek** [comment]
@kweij have You checked Hyva checkout Payment Integrations ? https://docs.hyva.io/checkout/hyva-checkout/integrations/available-payment-methods.html#stripe

there is already Adyen compatibility module
https://gitlab.hyva.io/hyva-checkout/checkout-integrations/magento2-hyva-checkout-adyen-payment/

**Comment by kweij** [comment]
@Funfelek I am making use of the Hyvä Checkout Adyen compatibility module, which I mentioned as the community built integration module in the initial post. It still has a few flaws, but I managed to get it working with the latest version of the Hyvä Checkout with some local patches (pending PR's).

However, although I can take of with using Adyen, this module only supports Adyen v8. Rather sooner than later we want to upgrade to v9, but support Hyvä Checkout for that version is not available.

**Comment by candemiralp** [comment]
Dear all,

We've finally released official Hyvä Checkout compatibility module https://github.com/Adyen/adyen-magento2-hyva. This compatibility module is compatible with >v9.6.1.

Please feel free to contribute to the repository for any issues or pull requests.

Best Regards,
Can
