### ISSUE TITLE
[ECP-9173] Add PayPo support in Magento plugin

### ISSUE THREAD

**Issue by mmackowiakSP** [Adyen/adyen-magento2#2601]
**Is your feature request related to a problem? Please describe.**
We'had issues with Magento plugin and it's already cost us a lot of additional development. As you can imagine this is very frustrating. Now it turns out that PayPo payment method is not supported in it. And it should be. It's one the most common buy now, pay later methods in the Polish market.

**Describe the solution you'd like**
The solution is -> Magento plugin supporting PayPo payment method.

**Describe alternatives you've considered**
There isn't really an alternative. You could say "why don't you use Klarna?" Well, true, but... those two are very different in terms of costs and popularity in the market. So there is no real alternative, to be honest. Plus our customers use PayPo, we already know that.

**Additional context**
Don't have high hopes, to be honest. But I am sending request as suggested by Adyen support.

**Comment by RokPopov** [comment]
Hi @mmackowiakSP, thank you for requesting this enhancement. 

I have created an internal ticket to add the support for PayPo payment method. Once the task is completed and the PR is merged, this issue will automatically close.

Kind regards,
Rok

**Comment by mmackowiakSP** [comment]
Hi,

Thank you for information.

Cheers
Maciej

--
“People think that stories are shaped by people. In fact, it's the other way around.” Terry Pratchett
