### ISSUE TITLE
[ECP-9194] Adyen 9.2.0 conflicting with Avalara Avatax - Payment methods not loaded - adyen_payment_methods_response empty

### ISSUE THREAD

**Issue by Linek** [Adyen/adyen-magento2#2602]
**Describe the bug**
Adyen 9.2.0 is not working correctly with other extension (in this case Avalara Avatax).

After we have updated adyen/module-payment to version 9.2.0,
We have encountered a problem that the Adyen payment method is not showing up on Magento checkout.

I was checking what is the reason,
And the problem is that there is "conflict" within mixin in Avalara extension:
https://github.com/avadev/Avalara-AvaTax-for-Magento2/blob/master/view/frontend/web/js/model/shipping-save-processor/default.js

In this mixin there is asynchronous shipping-information request, and because of this response with adyen_payment_methods_response is received too late and adyenPaymentMethodsResponse is empty in:
html/vendor/adyen/module-payment/view/frontend/web/js/model/get-payment-information-mixin.js

![image](https://github.com/Adyen/adyen-magento2/assets/136248/8ec7c277-571b-4e37-9135-9dd76c2e8f50)

**To Reproduce**
1. Install adyen/module-payment, version 9.2.0 & avalara/avatax-magento, version 2.5.0
2. Go to Checkout
3. Go to Payment Step

**Expected behavior**
We should have all payment method visible.

**Magento version**
2.4.5-p6

**Plugin version**
9.2.0

**PHP Version**
8.1

**Desktop (please complete the following information):**
 - OS: MacOS 14.4.1
 - Browser Chrome 
 - Version 124.0.6367.92

**Additional context**
I'm aware that your extension is working perfectly find with clean Magento website and it might be the case that Avalara extension is "incorrectly" integrated that it's conflicting with yours.
However it would be great to know your opinion to define next steps.

**Comment by RokPopov** [comment]
Hi @Linek, 

Thank you for reporting this issue.
We will investigate the root cause of the issue internally and update you with the decision made on top of it.

Kind regards,
Rok

**Comment by raoulritter** [comment]
Hi @Linek,

I've tried to replicated this issue. I've been unable to get this to happen on 9.2.0 with 2.5.0, in that case I get the following exception message:

![image](https://github.com/Adyen/adyen-magento2/assets/59527829/a6c52b12-b4a2-4112-b7bf-65f967e6c7cf)


However when i use 2.6.0 I have no issues, would you be able to confirm if this issue persists with this version? Or if we missed something while testing? Thanks in advance.
