### ISSUE TITLE
List incompatible changes when upgrading to 9.x

### ISSUE THREAD

**Issue by rutgerrademaker** [Adyen/adyen-magento2#2603]
**Is your feature request related to a problem? Please describe.**
As an integration partner I'd like to have a clear overview of backwards incompatible changes when updating to 9.x

**Describe the solution you'd like**
From a developer's perspective adding these changes in the README.md of this module (adding a link would also just do, it's just that this is the place where I start looking when doing a major version upgrade

**Describe alternatives you've considered**
Alternatives could be introducing some clear warnings in the admin on that some manual steps need to be taken care off

**Additional context**
Things we encountered so far:

1) all payment methods were disabled by default due to a change in config path
`payment/adyen_hpp/active` was moved to `payment/adyen_abstract/payment_methods_active`

2) The webhook url changed  from `adyen/process/json` to `adyen/webhook`
Only after reverse engineering why webhooks stopped working  I found this page describing these needed changes
https://docs.adyen.com/plugins/adobe-commerce/set-up-adyen-customer-area/?tab=manual_2#step-3-set-up-webhooks

Of course there might be more that we are not yet aware of

**Comment by candemiralp** [comment]
Hello @rutgerrademaker,

Thank you for creating this Github issue. Indeed, as you mentioned, there are some breaking changes on V9 of the plugin and sorry to hear that you had a bad experience while upgrading the plugin.

However, breaking changes were listed on release notes of V9 and on [this](https://docs.adyen.com/plugins/adobe-commerce/migrate-to-a-new-version/) migration guide on Step 4 and Step 5. As I see, this guide was missed during the upgrade.

Even though there is a link to the official documentation of the plugin on Readme file, we will add link to the migration guide as well.

Best regards,
Can
