### ISSUE TITLE
Improvement Suggestion: Add index to merchant_reference column in adyen_payment_response

### ISSUE THREAD

**Issue by furan917** [Adyen/adyen-magento2#2608]
If possible I'd like the team to do an quick additional optimization pass on the `db_schema.xml` file to add DB indexes to tables where queries are ran against. 

Specifically one of my clients is seeing increased performance loss on any pathway searching on the `merchant_reference` which is causing 2-4s additional load time. 

**Describe the solution you'd like**
A quick addition of an index to `adyen_payment_response` on `merchant_reference`

**Additional context**
This is not a big problem, but a nice to have, especially as we can manually add a reference ourselves. 
```
CREATE INDEX ADYEN_PAYMENT_RESPONSE_MERCHANT_REFERENCE ON adyen_payment_response (merchant_reference);
```

**Comment by RokPopov** [comment]
Hi @furan917, thank you for raising this with us.

We currently have an investigation ticket opened for looking into the necessity of the `adyen_payment_response` table alltogether. You can follow the progress of the issue related to the investigation [here](https://github.com/Adyen/adyen-magento2/issues/2578).

I will be closing the ticket for now.

Kind regards,
Rok
