### ISSUE TITLE
[ECP-9223] Apple Pay Certificate can't be downloaded

### ISSUE THREAD

**Issue by JuliosDnd** [Adyen/adyen-magento2#2615]
**Describe the bug**
Apple Pay Certificate can't be downloaded from the Back Office

**To Reproduce**
1. Go to 'System > Configuration > Payment Methods > Adyen > Accepting Payments > Alternative Payments Methods'
2. Click on 'Apple Pay Certificate > Download Certificate'
3. See error "Failed to download the ApplePay certificate, please do so manually"

**Expected behavior**
We can download ApplePay certificate without any error

**Magento version**
2.4.6-p5

**Plugin version**
9.4.1

**Desktop (please complete the following information):**
 - OS: all
 - Browser all
 - Version all

**Smartphone (please complete the following information):**
 - Device: all
 - OS: all
 - Browser all
 - Version all

**Additional context**
It seems the url from `\Adyen\Payment\Controller\Adminhtml\Configuration\DownloadApplePayCertificate::APPLEPAY_CERTIFICATE_URL` redirect to 404 web page.

**Comment by RokPopov** [comment]
Hi @JuliosDnd,

Thank you for reporting this issue. We have opened an internal ticket about this. Once it is solved, this issue will automatically be closed.

Kind regards,
Rok
