### ISSUE TITLE
 Parse error: syntax error, unexpected ')', expecting variable (T_VARIABLE) in /var/www/html/magento2422/app/code/Adyen/Payment/Helper/Webhook/WebhookHandlerFactory.php on line 62

### ISSUE THREAD

**Issue by AaryanSinghVision** [Adyen/adyen-magento2#2619]
Parse error: syntax error, unexpected ')', expecting variable (T_VARIABLE) in /var/www/html/magento2422/app/code/Adyen/Payment/Helper/Webhook/WebhookHandlerFactory.php on line 62
PHP Parse error:  syntax error, unexpected ')', expecting variable (T_VARIABLE) in /var/www/html/magento2422/app/code/Adyen/Payment/Helper/Webhook/WebhookHandlerFactory.php on line 62
[sudo] password for admink: 
PHP Parse error:  syntax error, unexpected ')', expecting variable (T_VARIABLE) in /var/www/html/magento2422/app/code/Adyen/Payment/Helper/Webhook/WebhookHandlerFactory.php on line 62
PHP Parse error:  syntax error, unexpected ')', expecting variable (T_VARIABLE) in /var/www/html/magento2422/app/code/Adyen/Payment/Helper/Webhook/WebhookHandlerFactory.php on line 62
PHP Parse error:  syntax error, unexpected ')', expecting variable (T_VARIABLE) in /var/www/html/magento2422/app/code/Adyen/Payment/Helper/Webhook/WebhookHandlerFactory.php on line 62
PHP Parse error:  syntax error, unexpected ')', expecting variable (T_VARIABLE) in /var/www/html/magento2422/app/code/Adyen/Payment/Helper/Webhook/WebhookHandlerFactory.php on line 62

**Comment by tuyennn** [comment]
@RokPopov apparently the last comma from https://github.com/Adyen/adyen-magento2/blob/develop/Helper/Webhook/WebhookHandlerFactory.php#L61 was causing the problem

**Comment by RokPopov** [comment]
Hi @tuyennn, thank you for introducing the fix!
