### ISSUE TITLE
Failed to load "adyen-sepa-method" component 

### ISSUE THREAD

**Issue by dhawal-p** [Adyen/adyen-magento2#264]
**Magento version**: 2.2.2 and above
**Plugin version**: 2.2.0
**Description**

Steps to reproduce this issue:
1. Install Adyen Payment plugin via composer on blank Magento Commerce instance (luma theme) with one virtual product based on the instructions provided in https://docs.adyen.com/developers/plug-ins-and-partners/magento/magento-2
2. Run upgrade, static-content deploy and cache flush commands.
3. Configured Adyen plugin based on the instructions provided on https://docs.adyen.com/developers/plug-ins-and-partners/magento/magento-2/configuring-the-adyen-plug-in
4. Setup Required settings, Advanced settings and HPP Payment methods based on the instructions in docs.
5. Disable API Credit Card Payments and all other Payment methods except Adyen SEPA.
6. In your Adyen SEPA configurations Payment from Specific countries is set to UK and it matches Customer Area > Skins > [yourskincode] > Payment methods > pen icon > Override available countries as per the instructions in docs.
7. Now try to checkout with the Virtual Product, on Checkout page it shows below error message.
![image](https://user-images.githubusercontent.com/14078802/37960185-3d3086fe-31b5-11e8-8119-6a992b426ded.png)

**Note**: Adyen SEPA is the only Payment method enabled in Adyen Plugin. Other payment method available is Check/Money Order.

**Comment by rikterbeek** [comment]
Hi @dhawal-p,

The payment method Adyen SEPA is not related to the Skin configuration. It is a direct API call to our platform and works if you have SEPA payment method available on your account. Not sure why you are limited it to UK where SEPA is only for currency EUR. The error message is strange could you check if the component exists in your file system ? As well if you remove the specific country setup in magento payment method does that solves the issue ?

Regards,
