### ISSUE TITLE
Populate houseNumberOrName for Credit Card payments

### ISSUE THREAD

**Issue by lancergr** [Adyen/adyen-magento2#265]
**Magento version**: 2.1+
**Plugin version**: latest
**Description**
Populate houseNumberOrName for Credit Card payments https://github.com/Adyen/adyen-magento2/blob/develop/Gateway/Request/AddressDataBuilder.php#L69
in same way as alternatives/HPP https://github.com/Adyen/adyen-magento2/blob/develop/Block/Redirect/Redirect.php#L354
using Adyen helper

**Comment by rkewlani** [comment]
Thanks @lancergr! We have created internal backlog item to look into this. We will keep you posted.
Regards,
Rajni
Adyen

**Comment by cyattilakiss** [comment]
Hey @lancergr ,

We use the checkout component which handles populating the necessary fields so I will close this issue for now.

Best,
Attila
