### ISSUE TITLE
Firecheckout: Paymethods not rendering when using one step checkout

### ISSUE THREAD

**Issue by xgerhard** [Adyen/adyen-magento2#2650]
**Describe the bug**
After upgrading Adyen/module-payment from 8.22.5 to 9.5.3 payment methods are not rendering on one page checkout layouts.
Previous version worked fine with Firecheckout using one step checkout.
When using a multistep checkout (Either Firecheckout or default Magento) the payment methods are shown.

Did an attempt to debug, this observer which is exectued in a multistep checkout, does not get reached on the one step checkout page: https://github.com/Adyen/adyen-magento2/blob/main/view/frontend/web/js/view/payment/method-renderer/adyen-cc-method.js#L92

**To Reproduce**
1. Install firecheckout / adyen payment
2. Set Firecheckout layout to any but Multistep (for example 3 column)
3. Add product to cart
4. View checkout

**Expected behavior**
Payment methods will show

**Magento version**
2.4.5

**Plugin version**
swissup/module-firecheckout: 1.31.7
adyen/module-payment: 9.5.3

**Screenshots**
Added some logging to the file linked above:
![ady2b252fb4e62d98fb9acaa9f2cb2db629](https://github.com/Adyen/adyen-magento2/assets/13732765/480ed606-3832-4e9d-ac6c-1a0e0b1e9d64)

**Comment by samaitos** [comment]
> Just found this other issue #2492 . Seems similar.

Did you end up solving this or applied same as #2492  suggestion ?

**Comment by xgerhard** [comment]
I've put updating to the latest version on hold and wait for an update from Adyen. But I think the suggestion from the other issue would work yeah.

**Comment by samaitos** [comment]
Thanks for the update

**Comment by samaitos** [comment]
@xgerhard i just found a solution that worked for me. Might be specific to my config but could be considered to look at.
We are using cookieyes for consent. Turned out that when blocking Functional cookies the payment method does now show up. ( this changed after the update to adyen 9.5.3 , it worked before )
So what i have moved these functional cookies into Necessary and bam all works now.
