### ISSUE TITLE
[ECP-9290] Undocumented breaking change in 9.6.0

### ISSUE THREAD

**Issue by Nuranto** [Adyen/adyen-magento2#2663]
**Describe the bug**

In 9.6.0, This commit changes the graphql schema : https://github.com/Adyen/adyen-magento2/commit/a2839a368785cb739dcdc98bf859c325757d4f68

Our react checkout was using that `details` field.

I checked releases notes, I can't find anything about `ECP-9053`. Can you give us more information about this change ?

**Comment by RokPopov** [comment]
Hi @Nuranto,

Thank you for spotting and reporting this issue! I have created an internal ticket to remove the breaking change. Once completed, this ticket will automatically close.

Kind regards,
Rok

**Comment by dimitriBouteille** [comment]
Hi @RokPopov 

I think the best practice is :

- Deprecate the property in `schema.graphqls` with `@deprecated` tag 
- Permanently delete the property in another (major) version 

And maybe add `breaking change` in release note :)
