### ISSUE TITLE
Klarna Order Status Not Updated

### ISSUE THREAD

**Issue by chrisoliver90** [Adyen/adyen-magento2#2678]
**Describe the bug**
For failed/abandoned Klarna Payment the order status is stuck in Pending.
When we cancel these orders from the Magento order grid or within the order, the status remains as Pending.
Orders from other payment methods seem to be fine.

**To Reproduce**
1. Go to order grid
2. Select an order started with Klarna and abandoned in Pending status
3. Select cancel from the dropdown

**Expected behavior**
The order status is updated to cancelled on the grid and in the order

**Actual behavior**
The order status remains as Pending

**Magento version**
2.4.7-p1

**Plugin version**
adyen/module-payment: 9.5.3
adyen/php-api-library: 17.5.0

**Screenshots**
![grid](https://github.com/Adyen/adyen-magento2/assets/174329701/580011a3-59be-4478-a4ce-0d8cb5d10332)

Order grid showing Klarna order that has been cancelled but still in Pending status

**Desktop (please complete the following information):**
 - OS: Linux & Windows
 - Browser: Chrome
 - Chrome Version: 125.0.6422.60

**Additional context**
This issue has been present since Magento 2.4.7-p1 upgrade and is only reproducible on our live site with live Adyen webhook, not on our dev environment.

**Comment by chrisoliver90** [comment]
I opened a ticket with Adyen for this. It seems they are already aware of the issue and are working a on fix.

> We are aware of this already and we have an internal ticket open with the development team that has a high priority assigned. The reference for this is ECP-9261. Our team has already started working on it. 
> 
> Unfortunately I do not have an ETA I can provide at the moment for completion but we do expect resolution soon. We recommend to keep an eye on our GitHub release page as well for mention of ECP-9261.

**Comment by khushboo-singhvi** [comment]
Hey @chrisoliver90, 

Thank you for bringing this issue to our attention. We wanted to let you know that the pull request addressing this issue has been completed(https://github.com/Adyen/adyen-magento2/pull/2679). The fix will be included in the upcoming release of version 9.6.2 of the plugin.

We appreciate your patience and support. If you have any further questions or need additional assistance, please feel free to reach out.

Best regards,
Khushboo.
