### ISSUE TITLE
Property with dot in name can't be serialized

### ISSUE THREAD

**Issue by evs-xsarus** [Adyen/adyen-magento2#2682]
Making your own contribution is easy, encouraged and greatly appreciated! We will put effort into reviewing and merging your PR quickly. For more info, please refer to the contribution guidelines: https://github.com/Adyen/adyen-magento2/blob/develop/CONTRIBUTING.md

**Describe the bug**
When using Adyen and Flowmailer in Magento, the order confirmation can't be sent do to the additionalData containing properties with a dot in the name. Flowmailer serializes this data using Symfony Serializer.

**To Reproduce**
1. Place an order
2. Pay it
3. Open the order in the admin
4. Add a comment
5. Select 'Send mail'
6. Place the comment
7. Now, a message is shown > Can't get a way to read the property "bankAccount" in class "stdClass".

**Expected behavior**
The mail is send.

**Magento version**
2.4.7

**Plugin version**
9.6.0

**Screenshots**
Trace

> #0 /home/svc-dlk_acc_a/releases/e39ad7bd/vendor/symfony/property-access/PropertyAccessor.php(320): Symfony\Component\PropertyAccess\PropertyAccessor->readProperty()
> #1 /home/svc-dlk_acc_a/releases/e39ad7bd/vendor/symfony/property-access/PropertyAccessor.php(104): Symfony\Component\PropertyAccess\PropertyAccessor->readPropertiesUntil()
> #2 /home/svc-dlk_acc_a/releases/e39ad7bd/vendor/symfony/serializer/Normalizer/ObjectNormalizer.php(146): Symfony\Component\PropertyAccess\PropertyAccessor->getValue()
> #3 /home/svc-dlk_acc_a/releases/e39ad7bd/vendor/symfony/serializer/Normalizer/AbstractObjectNormalizer.php(194): Symfony\Component\Serializer\Normalizer\ObjectNormalizer->getAttributeValue()
> #4 /home/svc-dlk_acc_a/releases/e39ad7bd/vendor/symfony/serializer/Serializer.php(159): Symfony\Component\Serializer\Normalizer\AbstractObjectNormalizer->normalize()
> #5 /home/svc-dlk_acc_a/releases/e39ad7bd/vendor/symfony/serializer/Normalizer/AbstractObjectNormalizer.php(223): Symfony\Component\Serializer\Serializer->normalize()
> #6 /home/svc-dlk_acc_a/releases/e39ad7bd/vendor/symfony/serializer/Serializer.php(159): Symfony\Component\Serializer\Normalizer\AbstractObjectNormalizer->normalize()
> #7 /home/svc-dlk_acc_a/releases/e39ad7bd/vendor/symfony/serializer/Normalizer/AbstractObjectNormalizer.php(223): Symfony\Component\Serializer\Serializer->normalize()
> #8 /home/svc-dlk_acc_a/releases/e39ad7bd/vendor/symfony/serializer/Serializer.php(159): Symfony\Component\Serializer\Normalizer\AbstractObjectNormalizer->normalize()
> #9 /home/svc-dlk_acc_a/releases/e39ad7bd/vendor/symfony/serializer/Normalizer/AbstractObjectNormalizer.php(223): Symfony\Component\Serializer\Serializer->normalize()
> #10 /home/svc-dlk_acc_a/releases/e39ad7bd/vendor/symfony/serializer/Serializer.php(159): Symfony\Component\Serializer\Normalizer\AbstractObjectNormalizer->normalize()
> #11 /home/svc-dlk_acc_a/releases/e39ad7bd/vendor/symfony/serializer/Normalizer/AbstractObjectNormalizer.php(223): Symfony\Component\Serializer\Serializer->normalize()
> #12 /home/svc-dlk_acc_a/releases/e39ad7bd/vendor/symfony/serializer/Serializer.php(159): Symfony\Component\Serializer\Normalizer\AbstractObjectNormalizer->normalize()
> #13 /home/svc-dlk_acc_a/releases/e39ad7bd/vendor/symfony/serializer/Normalizer/AbstractObjectNormalizer.php(223): Symfony\Component\Serializer\Serializer->normalize()
> #14 /home/svc-dlk_acc_a/releases/e39ad7bd/vendor/symfony/serializer/Serializer.php(159): Symfony\Component\Serializer\Normalizer\AbstractObjectNormalizer->normalize()
> #15 /home/svc-dlk_acc_a/releases/e39ad7bd/vendor/symfony/serializer/Serializer.php(138): Symfony\Component\Serializer\Serializer->normalize()
> #16 /home/svc-dlk_acc_a/releases/e39ad7bd/vendor/flowmailer/flowmailer-php-sdk/src/Flowmailer.php(438): Symfony\Component\Serializer\Serializer->serialize()
> #17 /home/svc-dlk_acc_a/releases/e39ad7bd/vendor/flowmailer/flowmailer-php-sdk/src/Endpoints.php(1743): Flowmailer\API\Flowmailer->createRequest()
> #18 /home/svc-dlk_acc_a/releases/e39ad7bd/vendor/flowmailer/flowmailer-php-sdk/src/Endpoints.php(1753): Flowmailer\API\Endpoints->createRequestForSubmitMessage()
> #19 /home/svc-dlk_acc_a/releases/e39ad7bd/vendor/flowmailer/m2connector/Plugin/TransportPlugin.php(132): Flowmailer\API\Endpoints->submitMessage()
> #20 /home/svc-dlk_acc_a/releases/e39ad7bd/vendor/flowmailer/m2connector/Plugin/TransportPlugin.php(165): Flowmailer\M2Connector\Plugin\TransportPlugin->submitMessages()
> #21 /home/svc-dlk_acc_a/releases/e39ad7bd/vendor/magento/framework/Interception/Interceptor.php(135): Flowmailer\M2Connector\Plugin\TransportPlugin->aroundSendMessage()
> #22 /home/svc-dlk_acc_a/releases/e39ad7bd/vendor/magento/module-email/Model/Mail/TransportInterfacePlugin.php(48): Magento\Email\Model\Transport\Interceptor->Magento\Framework\Interception\{closure}()
> #23 /home/svc-dlk_acc_a/releases/e39ad7bd/vendor/magento/framework/Interception/Interceptor.php(135): Magento\Email\Model\Mail\TransportInterfacePlugin->aroundSendMessage()
> #24 /home/svc-dlk_acc_a/releases/e39ad7bd/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Email\Model\Transport\Interceptor->Magento\Framework\Interception\{closure}()
> #25 /home/svc-dlk_acc_a/releases/e39ad7bd/generated/code/Magento/Email/Model/Transport/Interceptor.php(23): Magento\Email\Model\Transport\Interceptor->___callPlugins()
> #26 /home/svc-dlk_acc_a/releases/e39ad7bd/vendor/magento/module-sales/Model/Order/Email/SenderBuilder.php(75): Magento\Email\Model\Transport\Interceptor->sendMessage()
> #27 /home/svc-dlk_acc_a/releases/e39ad7bd/vendor/magento/module-sales/Model/Order/Email/NotifySender.php(38): Magento\Sales\Model\Order\Email\SenderBuilder->send()
> #28 /home/svc-dlk_acc_a/releases/e39ad7bd/vendor/magento/module-sales/Model/Order/Email/Sender/OrderCommentSender.php(100): Magento\Sales\Model\Order\Email\NotifySender->checkAndSend()
> #29 /home/svc-dlk_acc_a/releases/e39ad7bd/vendor/magento/module-sales/Controller/Adminhtml/Order/AddComment.php(68): Magento\Sales\Model\Order\Email\Sender\OrderCommentSender->send()
> #30 /home/svc-dlk_acc_a/releases/e39ad7bd/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Sales\Controller\Adminhtml\Order\AddComment->execute()
> #31 /home/svc-dlk_acc_a/releases/e39ad7bd/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Sales\Controller\Adminhtml\Order\AddComment\Interceptor->___callParent()
> #32 /home/svc-dlk_acc_a/releases/e39ad7bd/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Sales\Controller\Adminhtml\Order\AddComment\Interceptor->Magento\Framework\Interception\{closure}()
> #33 /home/svc-dlk_acc_a/releases/e39ad7bd/generated/code/Magento/Sales/Controller/Adminhtml/Order/AddComment/Interceptor.php(23): Magento\Sales\Controller\Adminhtml\Order\AddComment\Interceptor->___callPlugins()
> #34 /home/svc-dlk_acc_a/releases/e39ad7bd/vendor/magento/framework/App/Action/Action.php(111): Magento\Sales\Controller\Adminhtml\Order\AddComment\Interceptor->execute()
> #35 /home/svc-dlk_acc_a/releases/e39ad7bd/vendor/magento/module-backend/App/AbstractAction.php(151): Magento\Framework\App\Action\Action->dispatch()
> #36 /home/svc-dlk_acc_a/releases/e39ad7bd/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Backend\App\AbstractAction->dispatch()
> #37 /home/svc-dlk_acc_a/releases/e39ad7bd/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Sales\Controller\Adminhtml\Order\AddComment\Interceptor->___callParent()
> #38 /home/svc-dlk_acc_a/releases/e39ad7bd/vendor/magento/module-backend/App/Action/Plugin/Authentication.php(145): Magento\Sales\Controller\Adminhtml\Order\AddComment\Interceptor->Magento\Framework\Interception\{closure}()
> #39 /home/svc-dlk_acc_a/releases/e39ad7bd/vendor/magento/framework/Interception/Interceptor.php(135): Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch()
> #40 /home/svc-dlk_acc_a/releases/e39ad7bd/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Sales\Controller\Adminhtml\Order\AddComment\Interceptor->Magento\Framework\Interception\{closure}()
> #41 /home/svc-dlk_acc_a/releases/e39ad7bd/generated/code/Magento/Sales/Controller/Adminhtml/Order/AddComment/Interceptor.php(32): Magento\Sales\Controller\Adminhtml\Order\AddComment\Interceptor->___callPlugins()
> #42 /home/svc-dlk_acc_a/releases/e39ad7bd/vendor/magento/framework/App/FrontController.php(245): Magento\Sales\Controller\Adminhtml\Order\AddComment\Interceptor->dispatch()
> #43 /home/svc-dlk_acc_a/releases/e39ad7bd/vendor/magento/framework/App/FrontController.php(212): Magento\Framework\App\FrontController->getActionResponse()
> #44 /home/svc-dlk_acc_a/releases/e39ad7bd/vendor/magento/framework/App/FrontController.php(146): Magento\Framework\App\FrontController->processRequest()
> #45 /home/svc-dlk_acc_a/releases/e39ad7bd/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\FrontController->dispatch()
> #46 /home/svc-dlk_acc_a/releases/e39ad7bd/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\App\FrontController\Interceptor->___callParent()
> #47 /home/svc-dlk_acc_a/releases/e39ad7bd/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}()
> #48 /home/svc-dlk_acc_a/releases/e39ad7bd/generated/code/Magento/Framework/App/FrontController/Interceptor.php(23): Magento\Framework\App\FrontController\Interceptor->___callPlugins()
> #49 /home/svc-dlk_acc_a/releases/e39ad7bd/vendor/magento/framework/App/Http.php(116): Magento\Framework\App\FrontController\Interceptor->dispatch()
> #50 /home/svc-dlk_acc_a/releases/e39ad7bd/vendor/magento/framework/App/Bootstrap.php(264): Magento\Framework\App\Http->launch()
> #51 /home/svc-dlk_acc_a/releases/e39ad7bd/pub/index.php(154): Magento\Framework\App\Bootstrap->run()
> #52 {main} [] []

Complete additionalData:

```json
 {
  "issuerCountry": "unknown" 
  "bankAccount.ownerName": "D. Klaassen" 
  "authorisedAmountCurrency": "EUR" 
  "merchantReference": "1234" 
  "authorisedAmountValue": "123" 
  "bankSummary": "" 
  "bankAccount.iban": "NL16TEST0436169118" 
}
```

NB Looking through Adyens code, I see only references to bankAccountOwnerName thus camelcased. There is a reference to the one with iban.

NBB This is also a bug in the symfony serializer, but Adyen could workaround it by camelcasing the properties. SEe https://github.com/symfony/symfony/issues/41845

**Comment by evs-xsarus** [comment]
PS Such a property can be created with:

```php
$stdclass = (object) ['bankAccount.iban' => 'NL16TEST0436169118', 'bankSummary' => ''];
```

**Comment by candemiralp** [comment]
Hello @evs-xsarus,

Thank you for raising this issue and apologies for the delayed response.

As we investigated the issue, we've decided not to introduce a fix for it. Because, this issue is related to the serialiser on Symfony framework itself. It's not possible to change the keys of the values as a workaround as there are many properties used in hundreds of payment methods that Adyen supports. In addition to that, we don't guarantee the compatibility of the payment module with the third parties.

Please don't hesitate to reach out to us if you have further questions.

Best Regards,
Can

**Comment by evs-xsarus** [comment]
Fixed by Sympony.
