### ISSUE TITLE
Order in pending status if already cancelled

### ISSUE THREAD

**Issue by dimitriBouteille** [Adyen/adyen-magento2#2708]
**Describe the bug**

Bug is partially fixed in the following MR https://github.com/Adyen/adyen-magento2/pull/2592 but there is still a small problem.

Indeed, if the graphQl `adyenPaymentDetails` query is executed multiple times for, the order is passed to status `pending` instead of remaining `canceled`.

As the following screenshot shows, the order is in pending status after executing `adyenPaymentDetails` 2 times (or more)

![Capture d’écran du 2024-08-13 12-26-25](https://github.com/user-attachments/assets/04d929bd-2aed-48ef-b1d3-bece17042fda)

![Capture d’écran du 2024-08-13 14-18-52](https://github.com/user-attachments/assets/41dec544-f9e9-4617-81e5-bad90ec70067)

**To Reproduce**

1. Try place order with adyen_twint payment
2. Cancel payment in Twint interface
3. Execute `adyenPaymentDetails` multiple times
4. The first time the order is cancelled with canceled status and after the order is in pending status ...

**Expected behavior**

If the order is already cancelled, the status must not change.

**Versions**

- Magento: ver. 2.4.5-p8
- Adyen module: 9.7.0

**Comment by candemiralp** [comment]
Hello @dimitriBouteille,

Thank you for your contribution and raising this issue. I've left a small comment on the PR. Let's discuss the details on the comment.

Best Regards,
Can
