### ISSUE TITLE
Sofort (DirectEbanking) logo is actually Klarna's logo

### ISSUE THREAD

**Issue by peterjaap** [Adyen/adyen-magento2#272]
I can't believe nobody noticed this before (committed 7 months ago!) but the logo for DirectEbanking is actually the Klarna logo; https://github.com/Adyen/adyen-magento2/blob/develop/view/base/web/images/logos/directEbanking.png

**Comment by peterjaap** [comment]
Also; https://github.com/Adyen/adyen-magento2/blob/develop/view/base/web/images/logos/directEbanking_de.png

**Comment by peterjaap** [comment]
Correct images can be found here; https://github.com/Adyen/adyen-magento2/tree/46dbf14c047ebfe2b25f68e28428840eeeacfc8f/view/base/web/images/logos

**Comment by peterjaap** [comment]
This is the closest one to the correct one in this repo; https://github.com/Adyen/adyen-magento2/blob/develop/view/base/web/images/logos/directEbanking_de_small.png

**Comment by rikterbeek** [comment]
Hi @peterjaap,

Sofort has been taken over by Klarna. We need to follow the guidelines of Klarna. For more information about the guidelines of the Sofort payment methods see: https://developers.klarna.com/en/no/kco-v3/sofort-design-guidelines/how-to-display-sofort#how-to-display-sofort

Regards,
Rik
Adyen

**Comment by peterjaap** [comment]
Ah didn't know that, thanks for the info!
