### ISSUE TITLE
Confirmation Email is sent for order cancelled by 3D secure

### ISSUE THREAD

**Issue by jayalakshmit** [Adyen/adyen-magento2#275]
**Magento version**: 2.1.4
**Plugin version**: dev-develop
**Description**
Step 1: Place an order with 3d secure card
Step 2: It will redirected to enter username and password.
Step 3: When authentication fails, we are redirected to our website with message "3D-secure validation was unsuccessful" and order cancelled by default, which is fine and working perfectly. Mean while order confirmation email triggered, which is unexpected.

Can we have an explanation for this and we don't want new order email to be triggered if 3D secure is cancelled.

**Comment by lancergr** [comment]
Hi @jayalakshmit 

On 3D secure failure, the order cancellation and quote restoration should be called, which shouldn't cause order confirmation logic to be executed:
https://github.com/Adyen/adyen-magento2/blob/2258ec7a9958947c29390d6cf249603a9a65c1ec/Controller/Process/Validate3d.php#L139

Could you check that you don't have any observer that trigger these e-mails on any of these events?

Best Regards,
Giorgos
Adyen

**Comment by lancergr** [comment]
Hi @jayalakshmit 

I am closing this, feel free to re-open if the issue persists.

Best Regards,
Giorgos
Adyen
