### ISSUE TITLE
Deprecated Functionality: Creation of dynamic property $adyenHelper is deprecated

### ISSUE THREAD

**Issue by adamkarnowka** [Adyen/adyen-magento2#2750]
Hello - There is an error in the file:
https://github.com/Adyen/adyen-magento2/blob/main/Model/Resolver/StoreConfig/StoreLocale.php#L27

**Describe the bug**
When graphql schema is fetched, it cannot fetch because of error:

```Deprecated Functionality: Creation of dynamic property Adyen\Payment\Model\Resolver\StoreConfig\StoreLocale\Interceptor::$adyenHelper is deprecated in /app/xxxxxxxxxxx/vendor/adyen/module-payment/Model/Resolver/StoreConfig/StoreLocale.php on line 35```

Because property is called `protected Data $dataHelper;` while in constructor you are using `$this->adyenHelper = $adyenHelper;` (`dataHelper` != `adyenHelper`)

**To Reproduce**
1. Have latest version installed and php8.2
2. Try to fetch graphql schema:
```json
{
    __schema {
        types {
            __typename
        }
    }
}
```

**Expected behavior**
Schema is fetched without errors

**Magento version**
`2.4.6-p7`

**Plugin version**
`9.8.1`

**Screenshots**
![image](https://github.com/user-attachments/assets/0e0d2d7e-16af-471a-983d-a65b54864e17)

**Comment by dimitriBouteille** [comment]
🚀 https://github.com/Adyen/adyen-magento2/pull/2743

**Comment by candemiralp** [comment]
Hello @adamkarnowka and @dimitriBouteille ,

Thank you for reporting this issue and providing a fix. The fix will be merged.

Best Regards,
Can
