### ISSUE TITLE
[ECP-9534] Adyen\Payment\Controller\Return\Index::isResponseAlreadyProcessed() throw exception if comment is empty

### ISSUE THREAD

**Issue by dimitriBouteille** [Adyen/adyen-magento2#2775]
In some case the order comment can be empty (null) so the function `str_contains` throw exception :(

![Capture d’écran du 2024-10-22 10-34-44](https://github.com/user-attachments/assets/3d2681de-d188-4305-97c4-da5a04b77d76)

> Deprecated Functionality: str_contains(): Passing null to parameter \#1 ($haystack) of type string is deprecated in /vendor/adyen/module-payment/Controller/Return/Index.php on line 213

**Comment by candemiralp** [comment]
Hello @dimitriBouteille,

Thank you for creating this issue. We have created an internal ticket to solve this issue.

Best Regards,
Can

**Comment by khushboo-singhvi** [comment]
Hey @dimitriBouteille,

Here is the related PR - https://github.com/Adyen/adyen-magento2/pull/2796
Closing the issue.

Regards!
Khushboo
