### ISSUE TITLE
[ECP-9354] Improve Adyen\Payment\Helper\PaymentResponseHandler::isValidMerchantReference()

### ISSUE THREAD

**Issue by dimitriBouteille** [Adyen/adyen-magento2#2786]
Hey,

I just updated the module to the latest version, but this version brings a major change that breaks part of my site.

Since 9.6.2, the `isValidMerchantReference` function has been added (PR https://github.com/Adyen/adyen-magento2/pull/2655), this function is fine for most orders however there may be a problem.

In my case, I have the possibility to pay an order in several times and each payment has a unique reference that is not specifically linked to the order number. Which makes this function will return `false` during the second payment, 3rd payment,...

An example of the references is:

- First payment: PRE-DE-2024100143
- 2nd payment: PRE-DE-2024100143A
- 3rd payment: PRE-DE-2024100143B
- ...

It would be nice to make this function and the rest of the module more easily modifiable as proposed by Magento (plugin, preference,...)

![Capture d’écran du 2024-10-28 16-34-46](https://github.com/user-attachments/assets/d907fd54-d66c-433c-b6c1-e1914d0afd1e)

**Describe the solution you'd like**

3 solutions : 

- Switch the function to `public` or `protected` so the user can easy create plugin or extend the class
- Create new class with this check so user can easy create plugin, extend the class or edit the dependency injection with `di.xml`
- Edit function and check the reference with `sales_order_payment.adyen_psp_reference` maybe ?

**Describe alternatives you've considered**

The only two solutions today is 

- Create patch
- Create a preference and duplicate the whole class

Neither of the two solutions is clean and especially in time it is very complicated to maintain...

**Comment by candemiralp** [comment]
Hello @dimitriBouteille,

Thank you for creating this issue and sharing your concerns about `isValidMerchantReference()` method. This method has been implemented to prevent order status change to `Pending` unless the current status is `Pending Payment`. However, this has been handled in `PaymentResponseHandler` class and it looks like `isValidMerchantReference()` method is redundant (and buggy indeed).

This method will be removed soon and I believe that will solve your issue.

Best Regards,
Can

**Comment by khushboo-singhvi** [comment]
Hey @dimitriBouteille,

Here is the related PR - https://github.com/Adyen/adyen-magento2/pull/2796
Closing the issue.

Regards!
Khushboo
