### ISSUE TITLE
[ECP-9561] Issue while trying to capture the PayByLink from magento.

### ISSUE THREAD

**Issue by ga3003** [Adyen/adyen-magento2#2816]
I am working on implementing a custom requirement to track all PayByLink transactions in our Magento system. As part of this process, I call the capture API to capture the payment whenever we receive an authorization webhook. However, when the Capture webhook is triggered in Magento, the following error appears on the order details page:

"The order failed to update: Unable to find adyen_invoice linked to original reference XXXXXXXXXXXXXX, psp reference XXXXXXXXXXXXXX, and order 000032862. Cannot create an invoice."

Upon debugging, I found the issue is caused by the following lines of code:

<img width="903" alt="image" src="https://github.com/user-attachments/assets/6437425b-f2be-4877-afa1-adecd67b8bda">

File path: [vendor/adyen/module-payment/Helper/Invoice.php](https://github.com/Adyen/adyen-magento2/blob/0431f3b59a9f76d3a77d28f97b4e4db407bbdd30/Helper/Invoice.php#L286)

In lines 291 and 292, the total amount used is base_grand_total, but the currency corresponds to the customer's order currency, not the base currency. As a result, when verifying whether the full payment has been completed, the system throws the error above.

I verified that after changing the $order->getBaseGrandTotal() to $order->getGrandTotal(), it solved the issue.

**Comment by candemiralp** [comment]
Hello @ga3003,

Thank you for creating this issue and providing detailed explanation of the issue. We have created an internal ticket to solve this issue.

Best Regards,
Can

**Comment by ga3003** [comment]
Hi @candemiralp, Is there any update on this issue?

**Comment by candemiralp** [comment]
Hi @ga3003,

The ticket has been created and put to our backlog and it will be handled based on the priority. We haven't pulled that ticket to our sprint yet and current priority of this task is not high as this issue has not been reported by any other merchants yet.

If this patch is very urgent for you, I would encourage you to create a pull request to solve this. Then, our team can quickly review and release the patch.

Best Regards,
Can

**Comment by ga3003** [comment]
Thanks @candemiralp for fixing this issue. I will update module in our project.
