### ISSUE TITLE
Add all cards types supported by Adyen in Brazil

### ISSUE THREAD

**Issue by deniscsz** [Adyen/adyen-magento2#282]
**Magento version**: 2.1.8
**Plugin version**: 2.1.2
**Description**
There are types of cards that Adyen supports in Brazil but are not available in the module. Brands like ELO and Hipercard do not exist as allowed cards but are available on adyen website. (https://www.adyen.com/pt_BR/metodos-pagamento/elo, https://www.adyen.com/pt_BR/metodos-pagamento/hipercard).

**Comment by rikterbeek** [comment]
Hi @deniscsz,

We are aware of this problem. We are using Magento for displaying the card options and they don't have these card brands in there system. To fix this we need a core change in the platform we are looking into it if we can provide a PR to Magento so it will be included.
https://github.com/magento/payment-improvements/issues/1

Regards,
Rik
Adyen

**Comment by deniscsz** [comment]
Hi @rikterbeek Thanks for the answer.

I added the new card types to Magento. I really needed to rewrite the core. I will generate a Pull Request for Magento 2, but I do not have much hope that it will be processed in time for use in any upcoming project.

**Comment by rikterbeek** [comment]
Hi @deniscsz,

If you can provide code to me then I can push it to magento as I am in contact with them around this and they said they were willing to merge the code.

Regards,
Rik
Adyen

**Comment by rikterbeek** [comment]
@deniscsz,

Could you send me the PR link you created ?

Regards,
Rik
Adyen
