### ISSUE TITLE
Use adyen/php-api-library hmac signature calculation

### ISSUE THREAD

**Issue by torreytsui** [Adyen/adyen-magento2#283]
**Magento version**: 2.2.3
**Plugin version**: master
**Description**

Should this module update to use adyen/php-api-library offered hmac signature calculation? I'm happy to create PR.

https://github.com/Adyen/adyen-php-api-library/blob/master/src/Adyen/Util/Util.php#L7

https://github.com/Adyen/adyen-magento2/blob/develop/Block/Redirect/Redirect.php#L319

**Comment by torreytsui** [comment]
Hi @rikterbeek, I suppose this could be a question for you?

**Comment by rikterbeek** [comment]
Hi @torreytsui,

The extension has a dependency to the php-api-libary see composer: 
https://github.com/Adyen/adyen-magento2/blob/develop/composer.json#L17

REgards,

**Comment by torreytsui** [comment]
@rikterbeek Thanks for the prompt update.

Yes, I notice that the dependency is added in composer. I very much appreciate the decoupling between the library and magento. 

The library offers a `Adyen\Util\Until:: calculateSha256Signature()` method, and I suspect that a re-implementation is done in the magento2 module itself on below lines

https://github.com/Adyen/adyen-magento2/blob/develop/Block/Redirect/Redirect.php#L311-L319

Is it good to use the library method instead? This generally speaking can reduce technical debts

**Comment by rikterbeek** [comment]
Hi @torreytsui,

Yes indeed we can use the library implementation thought we already did this. If you can do a PR that would be great something we can merge :)

Regards,
Rik
Adyen

**Comment by torreytsui** [comment]
Wonderful, @rikterbeek! I will do a PR 👍
