### ISSUE TITLE
Undefined index: cc_type  AdyenCcDataAssignObserver.php on line 65

### ISSUE THREAD

**Issue by ad1s** [Adyen/adyen-magento2#286]
**Magento version**: 2.2.4
**Plugin version**: 2.3.0
**Description**
In checkout, we sometimes get the notice:
Notice: Undefined index: cc_type in /vendor/adyen/module-payment/Observer/AdyenCcDataAssignObserver.php on line 65

**Comment by rikterbeek** [comment]
Hi @ad1s,

cc_type should always be set for the creditcard payment method. Are you able to debug if this notice happen what the value here is ? https://github.com/Adyen/adyen-magento2/blob/develop/view/frontend/web/js/view/payment/method-renderer/adyen-cc-method.js#L141

Regards,
Rik
Adyen

**Comment by sanderkwantes** [comment]
Hi @rikterbeek,

We experience the same issue with some orders where 'paymethod' is 'banktransfer'. I cannot see any consistency. We are currently using the M2 API to create orders. Today we got this error response in our logging for about 15 times. Order creation results in failure.

Regards,
Sander
on behalf of Meitrade B.V.

**Comment by rikterbeek** [comment]
HI @sanderkwantes,

This is a notice so this can't be a reason for order creation failure. AdyenCcDataAssignObserver will only be called for card payment not alternative payment methods as banktransfer. There should be more logs why order creation results in a failure.

Regards,
Rik
Adyen

**Comment by sanderkwantes** [comment]
Hi @rikterbeek ,

You were right, issue is fixed and was not related to your extension.

Thanks,
Sander

**Comment by rikterbeek** [comment]
Hi @sanderkwantes,

Good to hear thanks for the feedback. Closing the issue.

Regards,
Rik
Adyen

**Comment by f123248** [comment]
> Hi @rikterbeek ,
> 
> You were right, issue is fixed and was not related to your extension.
> 
> Thanks, Sander

Hi @sanderkwantes ,

Can you kindly share how you fix it?
I faced the same issue that banktransfer was settled the cc_type by a wrong action
