### ISSUE TITLE
Type H: illegal hex digit

### ISSUE THREAD

**Issue by strm76** [Adyen/adyen-magento2#29]
Hi,
I'm getting this error when going to checkout on my local machine in developer mode:
Warning: pack(): Type H: illegal hex digit ! in /vendor/adyen/php-api-library/src/Adyen/Util/Util.php on line 23

May be related to this, described on stackoverflow:
http://stackoverflow.com/questions/4732681/pack-in-php-illegal-hex-digit-warning

Regards
Stefan

**Comment by rikterbeek** [comment]
Hi strm76,

It looks like you are using the wrong HMAC key. Make sure you have SHA256 in Adyen and copied that code over to magento and not SHA1.

Regards,
Rik
Adyen

**Comment by rikterbeek** [comment]
Hi @strm76 

Did this solve your issue ?

Regards,
Rik
Adyen

**Comment by rikterbeek** [comment]
Hi @strm76

Thinks your issue is solved and it is a configurational issue so I am going to close this issue.

Regards,
Rik
Adyen
