### ISSUE TITLE
Generic giftcard image not working in HPP

### ISSUE THREAD

**Issue by TommyKolkman** [Adyen/adyen-magento2#291]
**Magento version**: 2.2.5
**Plugin version**: 2.3.0
**Description** HPP: Icon for genericgiftcard isn't shown.

The icon for the genericgiftcard is not shown while using HPP. The info log shows that the images are available, but they're not shown.

```           
[0] => Array
                (
                    [brandCode] => genericgiftcard
                    [logos] => Array
                        (
                            [normal] => https://test.adyen.com/hpp/img/pm/genericgiftcard.png
                            [small] => https://test.adyen.com/hpp/img/pm/genericgiftcard_small.png
                            [tiny] => https://test.adyen.com/hpp/img/pm/genericgiftcard_tiny.png
                        )

                    [name] => Generic GiftCard
                )
```

The image for the genericgiftcard is not available in view/base/web/images/logos as well. As a test, I've placed an image there, but that doesn't work either. Any idea?

**Comment by rikterbeek** [comment]
Hi @TommyKolkman,

Can you check the element is no image src created or is the link image not correct ?

Regards,
Rik
Adyen

**Comment by TommyKolkman** [comment]
Seems to work on 2.3.1, so I think you guys can close this!
