### ISSUE TITLE
Place order - Error JS "adyen.createEncryption is not a function"

### ISSUE THREAD

**Issue by anthonyherve** [Adyen/adyen-magento2#292]
**Magento version**: 2.2.5
**Plugin version**: 2.3.0
**Description**
I have an error when I place order (at the end of checkout). When I click on the button, I have next JS error:
`Uncaught TypeError: adyen.createEncryption is not a function at UiClass.placeOrder (adyen-cc-method.js:175) at HTMLButtonElement.<anonymous> (knockout.js:3863) at HTMLButtonElement.dispatch (jquery.js:5226) at HTMLButtonElement.elemData.handle (jquery.js:4878)
`

How can I check if object is well loaded? Did you have already this error?

Thank you for your help.

**Comment by rikterbeek** [comment]
HI @anthonyherve,

can you add a debug it in your browser and check if the adyen object exists ?
https://github.com/Adyen/adyen-magento2/blob/develop/view/frontend/web/js/view/payment/method-renderer/adyen-cc-method.js#L175

Did you configure a Library token in your adyen creditcard settings ?

Regards,
Rik
Adyen

**Comment by anthonyherve** [comment]
Hi @rikterbeek ,

Thank you for your help.
I did not configure Library token in my CreditCard API integration, but it's now done. Unfortunately it does not work and I have same error.
I added a console.debug with object "adyen" and I have following debug:
`{cse: {…}, createEncryptedForm: ƒ}
  createEncryptedForm:ƒ ()
    arguments:null
    caller:null
    length:0
    name:""
    prototype:{constructor: ƒ}
    __proto__:ƒ ()
    [[FunctionLocation]]:8015325980131542.shtml:7
    [[Scopes]]:Scopes[1]
  cse:
    available:false
    version : "0_1_18"
    __proto__:Object
    __proto__:Object`

And in shtml file, I have this code:
` ( function() {
    var adyen = window.adyen = window.adyen || {};
    adyen.cse = adyen.cse || {};
    adyen.cse.version = "0_1_18";

    adyen.cse.available = false;
    adyen.createEncryptedForm = function() {
        // Noop
    };

}() );`

Thank you for your help.

Regards,
Anthony

**Comment by rikterbeek** [comment]
Hi @anthonyherve,

Could you send your question to support@adyen.com together with a url of your side and your merchantAccount. Then we can investigate what is going wrong. It seems that this is more a configurational issue then an coding problem.

Regards,
Rik
Adyen

**Comment by anthonyherve** [comment]
Hello,

Thank you for your help. We have found the error. It was just that no payment method was activated in Adyen backend. It's now worked very well.

Regards,
Anthony
