### ISSUE TITLE
Checkbox "Billing and shipping address are the same" missing in the payment step

### ISSUE THREAD

**Issue by sezio** [Adyen/adyen-magento2#293]
**Magento version**: 2.2.2
**Plugin version**: 2.3.0
**Description**

Hello, 

On a magento 2.2.2 fresh install with Adyen Payment module 2.3.0, we can't see the checkbox "billing and shipping address are the same". 
With all the other payment methods, the checkbox appears (at least the one I tested : check / bank transfer / paypal). 

Is this a normal behavior ? Maybe I'm wrong thinking that the problem comes from the module so please correct me if so. 

Thanks, 

Sébastien

**Comment by rikterbeek** [comment]
Hi @sezio,

We load some core templates of magento in our payment method to facilitate this. Could you provide some screenshots and provide us the element that is missing ? Then we can investigate further.

Regards,
Rik
Adyen

**Comment by msilvagarcia** [comment]
I'm closing this issue because this feature is present in the latest version of the plugin.

Feel free to create a new one if there are any questions left.

Cheers!
Marcos
Adyen
