### ISSUE TITLE
Deleting Vault token plugin throws exception

### ISSUE THREAD

**Issue by Maikel-Koek** [Adyen/adyen-magento2#297]
**Magento version**: 2.2.5
**Plugin version**: feature/vault
**Description**

Can be reproduced by running `\Magento\Braintree\Controller\Cards\DeleteActionTest::testExecute`.

The `assertSessionMessages` assertion will fail, because the exception "Failed to disable this contract" will be triggered, which is added here:
https://github.com/Adyen/adyen-magento2/commit/5f1ff32cf1ab5e8d4b229515aa3e0a86afd2794a

The plugin probably needs to check if the payment token contains an Adyen payment method code before proceeding, so the errors isn't triggered when another payment provider is trying to delete a token.

**Comment by Maikel-Koek** [comment]
@rikterbeek Could you verify my PR is correct?

**Comment by rikterbeek** [comment]
Hi @Maikel-Koek,

Many thanks for the PR! I merged it. Will close this issue.

Regards,
Rik
Adyen
