### ISSUE TITLE
Translate cause problems

### ISSUE THREAD

**Issue by bdandreas** [Adyen/adyen-magento2#301]
https://github.com/Adyen/adyen-magento2/blob/38699823996576b691218e5a621b9492a5e6a029/Block/Redirect/Pos.php#L222

Remove $this->
$myReceiptOrderLines .= "  " . 1 . " " . $this->__('Total Discount') . "| " .
$myReceiptOrderLines .= "  " . 1 . " " . __('Total Discount') . "| " .

**Comment by rikterbeek** [comment]
HI @bdandreas,

Why do you want to remove it and what is causing the issue?

Regards,
Rik
Adyen

**Comment by msilvagarcia** [comment]
I'm closing this issue because it seems it's fixed in the most recent version of the plugin.

Feel free to create a new one if there are any questions left.

Cheers!
Marcos
Adyen
