### ISSUE TITLE
Question about cron model in function _processNotification

### ISSUE THREAD

**Issue by bdandreas** [Adyen/adyen-magento2#307]
Magento version: 2.2.3
Plugin version: 2.3.0
File: Adyen\Payment\Model\Cron.php

I have a question with the Cron task which gave a unexpected behaviour in our payment process.

In the Cron.php on line 791 there is a case "case Notification::AUTHORISATION:".
I had to remove the if statement "if ($_paymentCode != "adyen_pos") " and always execute this->_authorizePayment();

This finally will do the trick to do a call back to Adyen and update the adyen_notification table column "done" from 0 to 1 and other data we need. 

Any reason why this if state should be there ? 
Because in our order, the payment method is "adyen_pos"  and won't go through  again to check if the payment is okay at Adyen.

Regard 
B. Andreas

**Comment by rikterbeek** [comment]
Hi @bdandreas,

I see the problem. Previously there was an authorisation and a capture for pos payments. Now we have POS on the same flow as ecom so we don't have to do this anymore. We fix it in magento1 but not in magento2 yet. Are you able to provide a Pull Request where you removed this line ?


Regards,
Rik
Adyen
