### ISSUE TITLE
Label not clickable due to duplicate ID:s "billing-save-in-address-book" 

### ISSUE THREAD

**Issue by carolinevaimo** [Adyen/adyen-magento2#31]
How to reproduce:
1. Log in and make sure you have an address saved in you address book.
2. Go to the payment step, choose Adyen (issue reproduced using Adyen HPP)
3. Uncheck "My billing and shipping address are the same"
4. Choose "new address" in the dropdown. 
5. The label for the checkbox "Save in Address book" below the address form is not clickable. 

The reason for this is that multiple checkboxes with the same ID (billing-save-in-address-book) exists.

Attached screenshot of affected checkbox
![screen shot 2016-04-25 at 11 34 02](https://cloud.githubusercontent.com/assets/16153084/14812312/f31f8e6a-0b9c-11e6-942a-3f3b095610f1.png)

**Comment by rikterbeek** [comment]
Hi carolinevaimo,

I do not have this issue in my magento2 checkout. This section is loaded into all payment methods so duplicate id should not be an issue. This section is handled by the core of Magento so think you need to investigate why in your case it is not clickable.

Regards,
Rik
Adyen

**Comment by carolinevaimo** [comment]
You are right. Reproduced the issue with other payment methods too. Will report as a Magento bug. Thank you for the fast reply
