### ISSUE TITLE
New order after pos payment has the wrong status

### ISSUE THREAD

**Issue by rklerck** [Adyen/adyen-magento2#33]
I'm trying to implements the POS payment on my magento website, so I created a new order status (pending payment) on which the order should be set when it is created. After the payment is finished it should be processing or canceled. But it still gets the status 'Pending', before the payment is even finished. Also the mail is send before the payment is finished..

I'm using version 1.2.1 of the adyen extension and one of the latest clones of the magento develop branche.

Looks like a bug?

**Comment by rikterbeek** [comment]
Hi Rick,

Thanks for letting us know. I have fixed it in the commit above.

Regards,
Rik
Adyen
