### ISSUE TITLE
Confirmation emails sent out too early

### ISSUE THREAD

**Issue by TommyKolkman** [Adyen/adyen-magento2#34]
Using Magento 2.0.5 and adyen-magento-2 1.2.1 in test mode for HPP, I get my confirmation emails when I go to the HPP provider already. I haven't paid anything at that time yet - my order is coming in ad pending, but of course it isn't. Anyone experiencing this?

**Comment by TommyKolkman** [comment]
Oh and - my Magento cronjobs are configured correctly.

**Comment by rikterbeek** [comment]
Hi @TommyKolkman,

Sorry for the late reply thanks for letting us know I will have a look into this.

Regards,
Rik
Adyen

**Comment by rikterbeek** [comment]
Hi @TommyKolkman,

I could not reproduce this. I have looked into the code and can see we explicit let magento know not to send this order confirmation mail see: https://github.com/Adyen/adyen-magento2/blob/develop/Model/Method/Hpp.php#L216

Regards,
Rik
Adyen

**Comment by rikterbeek** [comment]
Hi @TommyKolkman ,

Is the issue resolved ?

Regards,
Rik
Adyen

**Comment by TommyKolkman** [comment]
Can confirm it's solved in 1.3.0!

**Comment by rikterbeek** [comment]
Hi @TommyKolkman,

That is great so I am closing this issue.

Regards,
Rik
Adyen
