### ISSUE TITLE
Entercash icon doesn’t show up on checkout

### ISSUE THREAD

**Issue by jobarbosa** [Adyen/adyen-magento2#342]
**Magento version**: 2.2.3
**Plugin version**: 2.1.3
**Description**

I add entercash as a payment method but the icon doesn't show up on checkout, as you can see in the image bellow:

<img width="940" alt="icon_missing" src="https://user-images.githubusercontent.com/44647448/48698712-b44d4f80-ebdf-11e8-80d5-2e7a912d44b2.png">

So, I search a little bit and found that entercash icon is missing in adyen module (directory: vendor/adyen/module-payment/view/base/web/images/logos). 
There is an easy way to fix this?

**Comment by Aleffio** [comment]
Hi @jobarbosa ,

A new plugin version(2.4.0) has been released with the fix: #346
Closing this issue.

Regards,
Alessio
Adyen
