### ISSUE TITLE
Unable to use Adyen client because of nonexisting function

### ISSUE THREAD

**Issue by FreekVandeursen** [Adyen/adyen-magento2#353]
**Magento version**: 2.2.6
**Plugin version**: 2.4.0
**Description**
When trying to create an online refund from Magento, an error is thrown in live mode. `Adyen\Payment\Helper\Data::initializeAdyenClient` calls the `getLiveEndpointPrefix` function, which does not exist.

**Comment by Aleffio** [comment]
Hi @FreekVandeursen ,

Can you please check if the Adyen PHP Api library installed on your server is updated?
It should be at least 1.5.3, we are releasing a fix to automatically update the library version.

Regards,
Alessio
Adyen

**Comment by FreekVandeursen** [comment]
Hi @Aleffio 

The Adyen PHP Api library is 1.5.4. That doesn't help though, since the helper class calls `$this->getLiveEndpointPrefix`, and that function definitely doesn't exist in that same class.

**Comment by Triickii** [comment]
We are also receiving this error after upgrade to Magento 2.2.7. 

`PHP message: PHP Fatal error: Uncaught Error: Call to undefined method Adyen\Payment\Helper\Data::getLiveEndpointPrefix() in /public_html/vendor/adyen/module-payment/Helper/Data.php:1294\nStack trace:\n#0 /public_html/vendor/adyen/module-payment/Gateway/Http/Client/TransactionAuthorization.php(63): Adyen\Payment\Helper\Data->initializeAdyenClient()\n#1 /public_html/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(111): Adyen\Payment\Gateway\Http\Client\TransactionAuthorization->__construct(Object(Magento\Framework\Model\Context), Object(Magento\Framework\Encryption\Encryptor), Object(Adyen\Payment\Helper\Data), Object(Adyen\Payment\Logger\AdyenLogger), Object(Adyen\Payment\Model\RecurringType), Array)\n#2 /public_html/vendor/magento/framework/ObjectManager/Factory/Compiled.php(108): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject('Adyen\\Payment\\G...', Array)\n#3 /public_html/vendor/magento/framework/ObjectManager/Facto...\n', referer: https://www.[domain].co.uk/checkout/`

**Comment by tom-iweb** [comment]
Looking into this issue further this line "https://github.com/Adyen/adyen-magento2/blame/develop/Helper/Data.php#L1294" was updates 19 days ago to include a function call '$this->getLiveEndpointPrefix($storeId)' however that function was never implemented.

Removing '$this->getLiveEndpointPrefix($storeId)' from that file resolves the issue, but this function needs implementing

**Comment by cyattilakiss** [comment]
Hi @FreekVandeursen ,

Indeed, we tried to use a function that only exists on one of our feature branches so thank you for the issue report. We have just releases the version 2.4.1 which includes the fix for this issue as well.

Best,
Attila
Adyen
