### ISSUE TITLE
Error in BeforeShipmentObserver

### ISSUE THREAD

**Issue by dev-awevo** [Adyen/adyen-magento2#362]
**Magento version**: 2.2.7
**Plugin version**: 2.4.2
**Description**

Hello,
There is an error in the Observer BeforeShipmentObserver.
When i try to create a Shipment from the Admin Interface, i got the error
> report.CRITICAL: Notice: Undefined property: Adyen\Payment\Observer\Adminhtml\BeforeShipmentObserver::$_adyenHelper in .../vendor/adyen/module-payment/Observer/Adminhtml/BeforeShipmentObserver.php on line 57

I saw the code of the observer. The line 57 is
> $captureOnShipment = $this->_adyenHelper->getConfigData('capture_on_shipment', 'adyen_abstract', $order->getStoreId());

But the definition of the variable is
> private $adyenHelper;
> $this->adyenHelper = $adyenHelper;

I corrected it while waiting for your next release but I wanted to inform you of this error because I do not know if you saw it

Regards

**Comment by Aleffio** [comment]
Hi @dev-awevo ,

Thank you very much for pointing out the issue,
we will release another version with the fix very soon.

Regards,
Alessio
Adyen
