### ISSUE TITLE
setState function can cause order state to be set to NULL

### ISSUE THREAD

**Issue by yanielliot** [Adyen/adyen-magento2#384]
Plugin version: >=2.3.1

setState function added in 2.3.1 can result in order state being set to NULL. 

```
    protected function _setState($status)
    {
        $statusObject = $this->_orderStatusCollection->create()
            ->addFieldToFilter('main_table.status', $status)
            ->addFieldToFilter('state_table.is_default', true)
            ->joinStates()
            ->getFirstItem();

        $this->_order->setState($statusObject->getState());
        $this->_adyenLogger->addAdyenNotificationCronjob('State is changed to  ' . $statusObject->getState());
    }
```

Line:

```
->addFieldToFilter('state_table.is_default', true)
```

makes the assumption that the status set in Adyen module config is the default status for a least 1 state. If this is not true no state is returend and the function sets order to state NULL.

Additionally line:

```
->getFirstItem();
```

may result in order state being set differently than user intended as status can be default for multiple states so may not return desired/expected state.

Would recommend that either config status fields are replaced with all possible state/status combinations so user can explicitly set what state and status the order is set to at each step. Alternatively config status fields could be limited to statuses of specific order states that make sense for that step from viewpoint of standard Magento order flow (eg to me Manual Review Accept status would be one belonging to state "processing").

Either way feel order state should be known and passed into setState function along with order status, rather than the function trying to work out which state to use, as order state and status are regularly used as key indicators during order processing and 3rd party systems integrations.

**Comment by ebaschiera** [comment]
I second this issue.
For my use case, it's enough to remove the following line:
`->addFieldToFilter('state_table.is_default', true)`

Thanks!

**Comment by ebaschiera** [comment]
Hi Devs,
this bug is as small as easy to solve. Do you really need a PR for that? :)

The bug report is detailed and summarize deeply the issue.

Just try setting up a couple of statuses per state and then configure Adyen module to set one of the non-default statuses. It will set order status to NULL.

Thanks!

**Comment by AlexandrosMor** [comment]
Hello  @ebaschiera,

It would be great if you can do a pull request so we can review it and merge the changed code. 

regards,
Alexandros
