### ISSUE TITLE
Magento 2.3 compatibility

### ISSUE THREAD

**Issue by jayalakshmit** [Adyen/adyen-magento2#386]
We are planning to upgrade our store from Magento Cloud version 2.1.4 to Magento 2.3.
On this regard, we would like to get clarification on below points.

Currently we are using Adyen Plugin version: 2.2.0
1. Would the latest version of Adyen 3.0.0 be fully compatible with Magento version 2.3?
2. Are there any known issues in using this extension with Magento 2.3?

**Comment by cyattilakiss** [comment]
Hi @jayalakshmit ,

Yes the plugin is fully compatible with Magento2 version 2.3, you can upgrade the version without any problems. We have already several implementations on test and live, yet without issue reports.

Best,
Attila
Adyen
