### ISSUE TITLE
Incompatibility with magento commerce, issues with core tables modification 

### ISSUE THREAD

**Issue by cherednichenkoa** [Adyen/adyen-magento2#405]
**Magento version**: 
``` "magento/product-enterprise-edition": "2.2.7" ```
**Plugin version**: 3.0.0

Hello dear community, I am currently having an issue with this extension, but I am not sure how I can contribute in following case. 
Unfortunately I was not able to find compatibility notes for this extension, does it compatible with magento commerce ?

Magento commerce has one interesting feature that very useful for high loaded projects - it is split database solution, 
https://devdocs.magento.com/guides/v2.3/config-guide/multi-master/multi-master.html
Sales tables database can be divided into separate database, and quote tables as well, from master database. 

So such code as in 
Setup/UpgradeSchema.php:92

```
        $connection->addColumn(
            $setup->getTable('sales_order'),
            'adyen_notification_event_code_success',
            $adyenNotificationEventCodeSuccessColumn
        );
```
So such code as in 
Setup/UpgradeSchema.php:106
```       
 $connection->addColumn($setup->getTable('sales_order_payment'), 'adyen_psp_reference', $pspReferenceColumn);
```

will not work, as connection to the sales  database should be taken, not like it has been done in code   
```
$connection = $setup->getConnection();
```
but like this 
```
$connection = $setup->getConnection('sales');
```
consequently, join between tables from master database and sales database can give issues either 

Furthermore, I would like to mention that fix for such issues could be much easier,
if that changes for core tables were applied via extension attributes that stored into separate tables (core tables modification is abandoned in m2 as extension attributes has been added for core entities modification purpose).  

I have following questions :
- does this extension compatible for magento commerce version ?
- I have found such issue https://github.com/Adyen/adyen-magento2/issues/8 , but it is not a magento bug, it is incompatibility of the extension with split database solution, are you going to work on this issue, or are you accepting PR for EE version as well ? 
- what do you think of moving your custom attribute that modified core tables to extension attribute additional table ?

**Comment by cherednichenkoa** [comment]
as a reference to the  functionality you can check out this docs 
How this mechanism works
https://devdocs.magento.com/guides/v2.3/config-guide/multi-master/multi-master.html

how to split database 
https://devdocs.magento.com/guides/v2.3/config-guide/multi-master/multi-master_masterdb.html

Additionally you can find fallback for this approach in magento community 

https://github.com/magento/magento2/blob/741e610789dae6fa45065911b89f1af5007c3218/lib/internal/Magento/Framework/App/ResourceConnection.php#L96

Pay attention to getConnection method where it takes getConnectionByName method, in commerce magento all sales modules take connection with 'sales' name that is located in env.php config 

You can check config that works with split database solution here 

```
 'db' =>
  array (
    'connection' =>
    array (
      'indexer' =>
      array (
        'host' => 'default-master-host',
        'dbname' => 'magento',
        'username' => 'magento',
        'password' => 'magento',
        'active' => '1',
        'persistent' => NULL,
      ),
      'default' =>
      array (
        'host' => 'default-master-host',
        'dbname' => 'magento',
        'username' => 'magento',
        'password' => 'magento',
        'active' => '1',
      ),
      'checkout' =>
      array (
        'host' => 'checkout-master-host',
        'dbname' => 'checkout',
        'username' => 'magento',
        'password' => 'magento',
        'model' => 'mysql4',
        'engine' => 'innodb',
        'initStatements' => 'SET NAMES utf8;',
        'active' => '1',
      ),
      'sales' =>
      array (
        'host' => 'sales-master-host',
        'dbname' => 'sales',
        'username' => 'magento',
        'password' => 'magento',
        'model' => 'mysql4',
        'engine' => 'innodb',
        'initStatements' => 'SET NAMES utf8;',
        'active' => '1',
      ),
    ),
    'slave_connection' =>
    array (
      'default' =>
      array (
        'host' => 'default-slave-host',
        'dbname' => 'magento',
        'username' => 'read_only',
        'password' => 'password',
        'active' => '1',
      ),
      'checkout' =>
      array (
        'host' => 'checkout-slave-host',
        'dbname' => 'checkout',
        'username' => 'read_only',
        'password' => 'password',
        'model' => 'mysql4',
        'engine' => 'innodb',
        'initStatements' => 'SET NAMES utf8;',
        'active' => '1',
      ),
      'sales' =>
      array (
        'host' => 'sales-slave-host',
        'dbname' => 'sales',
        'username' => 'read_only',
        'password' => 'password',
        'model' => 'mysql4',
        'engine' => 'innodb',
        'initStatements' => 'SET NAMES utf8;',
        'active' => '1',
      ),
    ),
    'table_prefix' => '',
  ),

```

https://devdocs.magento.com/guides/v2.3/config-guide/multi-master/multi-master_slavedb.html

**Comment by cyattilakiss** [comment]
Dear @cherednichenkoa ,

Thank you for the heads up, we will definitely look into the split database compatibility with our extension. 

The extension is partly compatible with the Magento commerce version so as you just pointed it out, not with all the EE specific features like the split database setting.

We welcome and appreciate any pull request, also for the EE (mostly if the compatibility with the open source version is also taken into account).

For your last question I cannot answer right know, we will look into this as well and discuss it with the team.

Best,
Attila
Adyen
