### ISSUE TITLE
4.0.0 is not presented in composer

### ISSUE THREAD

**Issue by denissdubinin** [Adyen/adyen-magento2#419]
**Magento version**: 2.2.6
**Plugin version**: 3.0.0
**Description**
I am trying to upgrade plugin to 4.0.0 that is released 4 days ago, but composer sees only 3.0.0.

`composer show adyen/module-payment --all` shows all available versions and the latest version is 3.0.0 - http://prntscr.com/mwain0

Here is 4.0.0 release - https://github.com/Adyen/adyen-magento2/releases/tag/4.0.0

**Comment by catalinmoiceanu** [comment]
We are having same issue, it looks like version 4.0.0 is not present in Packagist - https://packagist.org/packages/adyen/module-payment

**Comment by denissdubinin** [comment]
Exactly.

There is a known issue with github hooks: pushing a tag pointing to a commit which is already available on Github (and so not pushing any new commit) does not trigger the push webhook, and so Packagist is not notified.
The workaround is to trigger a manual update in the packagist UI. Otherwise the tag will be picked only the next time you push a commit to github.

**Comment by mageho** [comment]
+1 here

**Comment by Aleffio** [comment]
Hi @denissdubinin , 
we triggered a manual update on packagist,
I am closing the issue, please feel free to reopen it if it doesn't work.

Regards,
Alessio,
Adyen
