### ISSUE TITLE
Infinite spinner on Hybris Select Payment Method

### ISSUE THREAD

**Issue by mcovarrubias** [Adyen/adyen-magento2#420]
**Hybris version**: 6.5.0 
**Plugin version**: 4.1.0
**Description**
I'm trying to test the plugin, so i followed up the configuration steps according to this page:
https://docs.adyen.com/developers/plugins/hybris/set-up-the-add-on

but each time I click on the Credit Card radio button, a spinner appears and nothing else.
No JS errors on Web browser development console everything seems to be fine

![adyen](https://user-images.githubusercontent.com/20228751/54322715-de29e800-45bb-11e9-8616-2eb2e8dc6689.png)

Please advise!

thanks!

**Comment by cyattilakiss** [comment]
Hi @mcovarrubias ,

Can you please open the same issue in our Hybris repo? :)
Thank you
Attila
Adyen
