### ISSUE TITLE
Version 4.0.0 is not working on PHP 7.2

### ISSUE THREAD

**Issue by schiriac** [Adyen/adyen-magento2#421]
**Magento version**: 2.3.0
**Plugin version**: 4.0.0
**Description**

When installing via composer version 4.0.0, I receive the following error because the version required for magento-module-vault is not compatible witth PHP 7.2

```
Problem 1
    - magento/module-vault 101.0.5 requires php ~7.0.13|~7.1.0 -> your PHP version (7.2.4) does not satisfy that requirement.
    - magento/module-vault 101.0.4 requires php ~7.0.13|~7.1.0 -> your PHP version (7.2.4) does not satisfy that requirement.
    - magento/module-vault 101.0.3 requires php ~7.0.13|~7.1.0 -> your PHP version (7.2.4) does not satisfy that requirement.
    - magento/module-vault 101.0.2 requires php 7.0.2|7.0.4|~7.0.6|~7.1.0 -> your PHP version (7.2.4) does not satisfy that requirement.
    - magento/module-vault 101.0.1 requires php 7.0.2|7.0.4|~7.0.6|~7.1.0 -> your PHP version (7.2.4) does not satisfy that requirement.
    - magento/module-vault 101.0.0 requires php 7.0.2|7.0.4|~7.0.6|~7.1.0 -> your PHP version (7.2.4) does not satisfy that requirement.
    - adyen/module-payment 4.0.0 requires magento/module-vault 101.0.* -> satisfiable by magento/module-vault[101.0.0, 101.0.1, 101.0.2, 101.0.3, 101.0.4, 101.0.5].
    - Installation request for adyen/module-payment 4.0.0 -> satisfiable by adyen/module-payment[4.0.0].
```

**Comment by Aleffio** [comment]
Hi @schiriac,

thank you for reporting the issue, we are going to update the dependencies and release the fix

Kind Regards,
Alessio
Adyen

**Comment by mageho** [comment]
Magento 2.3
Adyen Payment 4.0.0

Good afternoon @Aleffio,

I do not want to bother you, but I meet the same problem on our installation, but even If I downgrading to a previous version of php (PHP 7.1.27) in our environment, I have an error output in composer : 

> Problem 1
>     - Installation request for adyen/module-payment ~4.0.0 -> satisfiable by adyen/module-payment[4.0.0].
>     - Conclusion: remove magento/framework 102.0.0

Your composer.json declaration : 
https://github.com/Adyen/adyen-magento2/blob/c84a4038044e039fd1961d8c146ebbb88ee4e37e/composer.json#L18

Our magento/framework version is too high for your declaration ? 

Ilan PARMENTIER

**Comment by Aleffio** [comment]
Hi @mageho ,
the magento/framework version should not be a problem since we specify it should be higher than 101.
We are going to release a new version soon, so that it can be used with PHP 7.2
Kind Regards,
Alessio
Adyen
