### ISSUE TITLE
I can place orders without filling in the billing address.

### ISSUE THREAD

**Issue by tzyganu** [Adyen/adyen-magento2#426]
**Magento version**: 2.2.6
**Plugin version**: 2.3.0
**Description**
Steps to reproduce:
 - add a product to the cart
 - go to the checkout 
 - select Adyen HPP as payment method (or any of the methods available from adyen if the config setting for selecting payment on adyen page is set to 'No')
 - Uncheck the checkbox "My billing and shipping address are the same".
 - The billing address should be empty

Expected result:
 - I should not be able to press the "place order button"

Actual result:
 - I can place the order.

Additional info (maybe solution).

The buttons for place order should have a `disabled` property.  
The `data-bind` attribute on the 'continue to adyen' button should be

`data-bind="click: continueToAdyen, enable: (getCode() == isChecked()), css: {disabled: !isPlaceOrderActionAllowed()}"` for the payment method "Adyen HPP" (when the user should select the actual payment method on adyen website)

and 

`data-bind="click: $parent.continueToAdyenBrandCode, enable: (value == $parent.isBrandCodeChecked()), css: {disabled: !$parent.isPlaceOrderActionAllowed()}"`
when the user selects the payment method directly on the website.

the `css` part is missing for both buttons.

**Comment by cyattilakiss** [comment]
Hi @tzyganu ,

Thank you for the detailed bug report and the suggestion for solution. We are going to look into this issue soon but until that, as I remember in the #390 we have already fixed this issue which went live with the v4.0.0 release. If you could verify this, you would help a lot :)

Best,
Attila
Adyen

**Comment by tzyganu** [comment]
@cyattilakiss Unfortunately at the moment I cannot upgrade to 4.0.0. Will check as soon as I can.

**Comment by cyattilakiss** [comment]
Hi @tzyganu ,

I will close the ticket now, please let me know when you can check it with the upgraded version :)

Best,
Attila
