### ISSUE TITLE
HPP not showing "credit card" form

### ISSUE THREAD

**Issue by DePalmo** [Adyen/adyen-magento2#429]
**Magento version**: 2.2.3
**Plugin version**: 4.0.1
**Description**
Hello. After recent upgrade of your plugin, we're experiencing issues. Already contacted your company through email but no solution was provided so I'm hoping that we can find a solution over here.
The problem is that HPP does not load "credit card" form. Your support already checked out settings on our end and all look OK, we also double checked settings in Adyen itself and all OK there as well. There are no errors logged in console and none in `var/logs/Adyen`. The credit card form keeps loading but never loads ... I followed steps to upgrade outlined here: https://github.com/Adyen/adyen-magento2/releases/tag/4.0.1

Other things I tried:
- regenerated API key multiple times
- removed your extension with 'adyen/php-api-library' too and reinstalled
- reverted design changes I did to your templates to default
- moved our staging to SSL, before was on normal http
- changed settings at random (like disabling HPP, enabling CreditCard API or in reverse)

Please note that if I disable the "HPP" and leave enabled "CreditCard API integration", all enabled credit cards get listed. But since we had only one form for those under HPP in v3.0.0, I expected that we could have the same in v4.0.1.

I can provide login credentials to our store for you to check things our, but not in public.

Would appreciate a response, so that we can solve this one out.

**Comment by cyattilakiss** [comment]
Hi  @DePalmo ,
I found your ticket in our system, I will answer there.
Best,
Attila 
Adyen
