### ISSUE TITLE
Boleto invalid billing address

### ISSUE THREAD

**Issue by zanatta** [Adyen/adyen-magento2#431]
**Magento version**: 2.3
**Plugin version**: 4.0.2
**Description**
I know this magento version is not worked but, as I'm being able to checkout with credit card, I think that I could ask some help about boleto.

When I try to close a boleto checkout, I receive: AdyenLoggerTest.ERROR: 117: Invalid billing addresss

I'm not using any custom template, and even if I type specific billing address, I get the same error.

Could you help me to debug it properly to understand what's missing?

**Comment by zanatta** [comment]
If anyone had the same issue, the problem is at Post-code. Brazilian post code contains - example: 12345-678, and the - is not allowed.

**Comment by cyattilakiss** [comment]
Hi @zanatta ,

Thank you for the explanation, hopefully it will be valuable for others as well.

Best,
Attila
Adyen
