### ISSUE TITLE
No validation for Credit Cart payment method

### ISSUE THREAD

**Issue by denissdubinin** [Adyen/adyen-magento2#435]
**Magento version**: 2.2.6
**Plugin version**: 4.0.0
**Description**:
Currently, for credit card payment fields there is no empty field validation, only validation for incorrect data persisted.

Am i missing some configuration or 'required' validation is not provided by adyen? Because now 'Place order' button can proceed with an empty payment form. Error appears only after payment request gets response.

Video: https://streamable.com/l6zbl

**Comment by cyattilakiss** [comment]
Hi @denissdubinin ,

In the plugin in this line: https://github.com/Adyen/adyen-magento2/blob/develop/view/frontend/web/js/view/payment/method-renderer/adyen-cc-method.js#L115 the placeOrderAllowed should be set to false which disables the place order button so the order cannot be placed anymore only if a valid credit card number is provided. 
Could you please check if your place order button has the default functionality regarding the placeOrderAllowed function?

Best,
Attila
Adyen

**Comment by denissdubinin** [comment]
Hi @cyattilakiss,

alright, thank you, due to customization, placeOrderAllowed didn't work correctly. This solves the issue partially. I still want to have empty validation. I think this can be easily implemented since there is validation for card format etc.

**Comment by cyattilakiss** [comment]
Hi @denissdubinin ,

Since we provide the card component that provides the validation I think the easiest would be to add the empty validation to the card component's onChange callback here: https://docs.adyen.com/payment-methods/cards/#collect-with-card-component 

The docs for our card components can also help understanding the components: https://docs.adyen.com/payment-methods/cards/#collect-with-card-component 

I hope it will help

Best,
Attila
Adyen

**Comment by denissdubinin** [comment]
@cyattilakiss 
Thank you for suggestions, but this is not what i want.

1. For holderName that event is triggered only on focusing out, however, for all other fields, it's triggered on keypress. In result, it's hard to make same validation for all fields.
2. Might be possible to add `required` attribute for all CC fields from your side?
3. Other solution might be catch `.chckt-input-field--validated.js-chckt-input-field-validated` classess for inputs. If field is invalid or empty, those classes are not persisted, but it's not possible to get input classes outside of iframe.

**Comment by denissdubinin** [comment]
Look what i've got now. But i have 2 problems here:
1. It's really poor solution
2. Red validation is not removed while entering data. While entering data, text in black, but input is red. Video - https://streamable.com/byss6

So i really need a support for `required` validation.

**Comment by cyattilakiss** [comment]
Hi @denissdubinin ,

Sorry for the late response, I've just checked it with the checkout team if they have any idea to help you with this. With the newest release it is also possible to trigger the showValidation() for the card component.

You can use this var where we save the cardComponent: https://github.com/Adyen/adyen-magento2/blob/develop/view/frontend/web/js/view/payment/method-renderer/adyen-cc-method.js#L119

And then just simply `cardComponent.showValidation()` when the user clicks on the place order button. Also I would suggest to remove the place order button disabling functionality like these: https://github.com/Adyen/adyen-magento2/blob/develop/view/frontend/web/js/view/payment/method-renderer/adyen-cc-method.js#L137 from your process.

Or if you would like to have real control over your card component you can implement the secured fields component which is a new component and shipped with our latest release. Here you can find the documentation to implement it: https://docs.adyen.com/payment-methods/cards/custom-card-fields#collect-shopper-details-with-secured-fields Although this is a bigger piece of development and maybe you can have the same functionality with the idea I was writing first.

Best,
Attila
Adyen
