### ISSUE TITLE
Guest checkout - Remember these details

### ISSUE THREAD

**Issue by jzahedieh** [Adyen/adyen-magento2#45]
My QA team has picked up on this issue and I am wondering if this intended behaviour or if this is a bug.

I have tried to use one click checkout after placing an order as a guest but it doesn't store the credit card details for future reuse both as a guest and a registered user with the same email, this is the behaviour I would expect for security reasons.

Can you please confirm, thanks.

### Issue

Guest able to see and select remember card details in card payment section, doesn't seem to have any functional use.

### Steps to replicate

1 Launch site on browser
2 Add an item to the cart from PLP/PDP/SRP
3 Click on basket icon
4 Click edit cart link in the Utility menu
5 Click checkout option from the Shopping Cart page
6 Add Shipping address
7 Select shipping method & click Next
8 Select My billing and shipping address are the same and continue to payment section
9 Check card payment option is available
10 Select the Card option & select a card
11 Verify the option to save the payment card 

### Expected Behaviour

1 User should able to launch site on browser
2 User should able to add an item to cart form any PLP/PDP/SRP
3 User should able to view utility menu
4 Shopping Cart page should be displayed with all the items that is added by the user
5 User should navigate to Checkout page
6 User should be able to add shipping address
7 Shipping method should be selected & user should navigate to Billing Information section
8 Billing address saved same as shipping address .
9 Card payment option is available in the Payment page
10 Card payment section expands
11 Option to save payment card should not be available 

### Image

![remember](https://cloud.githubusercontent.com/assets/2098908/15963346/24da7066-2f09-11e6-8424-44666522f615.png)

**Comment by rikterbeek** [comment]
Hi @jzahedieh,

For a guest checkout should it not be possible to remember these details. This is now fixed thanks for letting us know. See commit below. If you are a customer you can decide to save it. If you want to show the card the next time you need to do two things:

1. Ask our support to enable recurring_contract notification on your account.
2. Enable the adyen OneClick payment method in magento backend payment configurations.

Regards,
Rik
Adyen

**Comment by jzahedieh** [comment]
Thanks, confirmed fix.
