### ISSUE TITLE
Use `checkout.create('securedfields')` instead of `checkout.create('card')`

### ISSUE THREAD

**Issue by NickdeK** [Adyen/adyen-magento2#451]
**Magento version**: 2.3.1
**Plugin version**: 4.0.3
**Description**

Is there a way to use the `checkout.create('securedfields')` with the module instead of the `checkout.create('card')` function [here](https://github.com/Adyen/adyen-magento2/blob/develop/view/frontend/web/js/view/payment/method-renderer/adyen-cc-method.js#L102)? The [API documentation](https://docs.adyen.com/checkout/api-integration/build-your-own-payment-form/#step-2-collect-shopper-details-with-secured-fields) shows how to use this and the main advantage to use this is that you can create your own layout for the payment fields without being stuck with the html structure that `checkout.create('card')` returns.

Tried to change it in the module but I get a `The passed payment method is not a valid Checkout Component` javascript error. Is there any way we can use this?

**Comment by cyattilakiss** [comment]
Hi @NickdeK ,

The securedfields component doesn't exists in the version that you use right now. If you update to the latest version of the plugin you can start using it but be aware that you will need to modify a lot on the frontend to make it work.

If you have any more questions please let me know.

Best,
Attila
Adyen
