### ISSUE TITLE
Bankaccount is missing on success page and backend

### ISSUE THREAD

**Issue by gigadesign1** [Adyen/adyen-magento2#454]
**Magento version**: 2.3.1
**Plugin version**: 4.2.0
**Description**
After selecting bank transfer as the payment method the customer receives information on how to execute the bank transfer.
The information listed is the amount, the reference and the name of bank account holder.
The bank account (IBAN) itself is missing in this information.
The same issue occurs in the backend of Magento.

**Comment by cyattilakiss** [comment]
Hi @gigadesign1 ,

Thank you for raising this issue. We are going to check it and after we can reproduce it fix it asap.

Best,
Attila
Adyen

**Comment by cyattilakiss** [comment]
Hi @gigadesign1 ,

We have just released the fix for this issue. Please let me know if you have any other issue or question.

Best,
Attila
Adyen

**Comment by gigadesign1** [comment]
Hi @cyattilakiss,

Thank you for fixing this so quickly!

Will update right away.
