### ISSUE TITLE
Payments are being auto-saved even if the customer has not selected to save them

### ISSUE THREAD

**Issue by nikosgram** [Adyen/adyen-magento2#457]
**Magento version**: 2.2.5
**Plugin version**: 4.0.3
**Description**

Customers who have never saved their card details with us, are actually being saved in the checkout. I am also an example of this.

I have no stored payment methods on my account.

However, when I log in and go to checkout, my card details from a previous order are already there – and there is no way to remove them.

![image](https://user-images.githubusercontent.com/3318873/59340634-46dd4980-8cfe-11e9-8f6e-3796d721fed6.png)

**Comment by cyattilakiss** [comment]
Hi @nikosgram ,

Can you please provide us a test site where we can see the flow?
In the credit or debit card payment method there should be a checkbox to store the payment method. If that is unticked it should not be saved.
In the account overview in the billing agreements section they can remove the stored payments.

Best,
Attila
Adyen

**Comment by jos-enigma** [comment]
Hi Attila,

I work with Nikos on the site and am also looking into the situation with him. I'm afraid that we are unable to share a test site with you, but I can share further details about the functionality to see if this helps. The customer report is that the box is unticked, and therefore the customer did not expect it to be saved. Their stored payments section is empty, so they have no payment methods to view or remove. However when checking out, they are given the option, as in nikos's screenshot, to use a stored payment method.

Thanks

**Comment by cyattilakiss** [comment]
Hi @jos-enigma ,

Do they have the method stored in their billing agreements section?
Can you do a test payment on your own please to verify if the checkbox is unticked than the payment method is still stored? 

Best
Attila
Adyen

**Comment by nikosgram** [comment]
Hello @cyattilakiss,

I found another kind of issue, when you save a payment method, is not showing it in Account -> Payment methods. This might be a Magento issue.

There is a big possibility that the payment method that is shown is already saved from a previous order, but, because it is not showing up on Account -> Payment methods, the user may think that it was incorrectly saved from their most recent order.

Thanks.

**Comment by cyattilakiss** [comment]
Hi @nikosgram ,

Unfortunately in the "Stored Payment Methods" the vault methods are saved and the one click payment methods are saved into the "Billing Agreements".

I hope this helps.

Best,
Attila

**Comment by nikosgram** [comment]
Hello @cyattilakiss.

Thank you for the fast response times today. I really appreciate it. Me and my team found the problem. It was not an Adyen issue, rather than Magento's miss configuration.

Thank you for your time.
