### ISSUE TITLE
Refresh payment methods on country change

### ISSUE THREAD

**Issue by sanderjongsma** [Adyen/adyen-magento2#461]
**Magento version**: 2.3.1
**Plugin version**: 4.1.0
**Description**
The payment methods are rendered if you move from the shipping to the payment step. But if you move back to the shipping step from the payment step and change the country, the shipping methods are not refreshed. 

I think it is a bug because a lot of payment options are based on the country. Do you agree? Or is it supposed to work like this.

**Comment by cyattilakiss** [comment]
Hi @sanderjongsma ,

Thank you for raising the issue.
We are going to test asap it and making the fix after being able to reproduce this.

Best,
Attila
Adyen

**Comment by cyattilakiss** [comment]
Hi @sanderjongsma we are going to release the changes this week.

Best,
Attila
