### ISSUE TITLE
Show invoice number as (extra) reference

### ISSUE THREAD

**Issue by evs-xsarus** [Adyen/adyen-magento2#463]
**Magento version**: 2.2.7
**Plugin version**: 2.4.3
**Description**

I would like to set the merchant reference to the order increment ID and the invoice increment ID. Since Magento creates the invoice after receiving the payment, how could this be achieved?

**Comment by cyattilakiss** [comment]
Hi @evs-xsarus ,

I think you need to create a plugin creating the invoice before we actually build the request so the adyen request builder will already have the invoice number information and it can use that in the merchant reference. Also pay attention to set the invoice creation after payment to false so you won't end up with 2 invoices.

I hope I could help.
Best,
Attila
Adyen

**Comment by evs-xsarus** [comment]
@cyattilakiss makes sense, thank you for this pointer.

**Comment by ayesha-tab** [comment]
Hi @cyattilakiss ,

could you please give more info about this implementation.. i have 3d cc enabled for which function i should write before plugin .. so that i takes the order modified increment ID (ORD-MMDDYY-XXX).

**Comment by cyattilakiss** [comment]
Hi @ayesha-tab ,

For the card payments we increment the order id to avoid issues with 3ds1 in this line: https://github.com/Adyen/adyen-magento2/blob/develop/Model/AdyenPaymentProcess.php#L149
So the plugin where you overwrite the original increment id generation with yours should be extended for the quote regarding function as well. Then when we send the reserved order id as a merchant reference in the /payments request here: https://github.com/Adyen/adyen-magento2/blob/develop/Helper/Requests.php#L279 we would use your custom order id and not the quote's original increment id.

Best,
Attila
Adyen

**Comment by ayesha-tab** [comment]
Hello @cyattilakiss 
   The actual problem i am facing is orders are showing status suspected fraud even i have completed successfully the card payment .. and status are not changing .. this is happening only for credit card others are working fine. if you think its cron not updating then in https://github.com/Adyen/adyen-magento2/blob/develop/Model/Cron.php#L361 its fetching 
                // get order
                $incrementId = $notification->getMerchantReference();
                $searchCriteria = $this->searchCriteriaBuilder
                    ->addFilter('increment_id', $incrementId, 'eq')
                    ->create();
Then this query may fail for credit card because we are not passing increment id as Merchant Reference.. Kindly help 

Thanks,
Ayesha

**Comment by cyattilakiss** [comment]
Hi @ayesha-tab ,

We don't restrict any of our merchants from using custom order ids in their systems. Our queries and database tables also do support strings not just integer variables. It may happen that you have to customise more than one thing to achieve custom order ids in Magento2, so only start it if you really have a deep understanding in Magento customising. I would also recommend you to check out of the box solutions for custom order numbers and then try to customise our plugin to retrieve the modified order id - maybe the third party plugin uses other fields and not the increment id.

I hope this will help.

Best,
Attila
Adyen

**Comment by ayesha-tab** [comment]
Hello @cyattilakiss ,

Thanks a lot for your help , i have added custom increment id and passing .. now its working perfectly and cron is also working and status are also updating correctly.

Thanks,
Ayesha

**Comment by yurirn** [comment]
@ayesha-tab could you pass that plugin you made to create custom code? I need this solution
