### ISSUE TITLE
Checkout breaks when using OpenInvoice in combination with seperate street+housenumber fields

### ISSUE THREAD

**Issue by peterjaap** [Adyen/adyen-magento2#468]
**Magento version**: 2.2.8

**Plugin version**: 4.1.2

**Description**
Checkout breaks when using OpenInvoice (Afterpay or Klarna) in combination with seperate street+housenumber fields.

It boils down to this function in `Request.php`;

```
    private function getStreetStringFromAddress($address)
    {
        if (method_exists($address, 'getStreetFull')) {
            // Parse address into street and house number where possible
            $address = $this->adyenHelper->getStreetFromString($address->getStreetFull());
        } else {
            $address = $this->adyenHelper->getStreetFromString($address->getStreetLine1());
        }

        return $address;
    }
```

The 'getStreetFull()` method exists on the `\Magento\Customer\Model\Address\AbstractAddress` class, but the `getStreetLine1()` exists on the `\Magento\Payment\Gateway\Data\Order\AddressAdapter` class.

Since a certain version of Magento (2.3?) the `order` and `quote` objects return an instance of the AddressAdapter class, which caues the `getStreetStringFromAddress` function to use the `getStreetLine1` value to retrieve the housenumber & streetname.

But; street line 1 in our case only returns the street name, since we use separate fields for street (street line 1) and house number (street line 2). The `houseNumberOrName` field referenced in `\Adyen\Payment\Helper\Requests::buildAddressData` is therefore not filled, causing Adyen to refuse the payment.

The fix is fairly simple;

```
$address = $this->adyenHelper->getStreetFromString(implode(' ', [$address->getStreetLine1(), $address->getStreetLine2()]));
```

**Comment by cyattilakiss** [comment]
Hi @peterjaap ,

Thank you for the information. Could you please open a PR with this fix? After checking the backwads compatibility we could merge it next week.

Thank you in advance,
Attila
Adyen

**Comment by peterjaap** [comment]
@cyattilakiss https://github.com/Adyen/adyen-magento2/pull/471

**Comment by cyattilakiss** [comment]
Hi @peterjaap 

We are going to release this fix soon, thank you for the PR :)

Best,
Attila
Adyen
