### ISSUE TITLE
'Invalid Form Key. Please refresh the page.' error after Bancontact payment

### ISSUE THREAD

**Issue by davekleijnkega** [Adyen/adyen-magento2#476]
**Magento version**: 2.3.2
**Plugin version**: 4.2.1
**Description**

I get the following error after placing an order with Bancontact: 'Invalid Form Key. Please refresh the page.'

This is after the redirect from the 3DS page. This is caused by the CSRF validation that is new in Magento 2.3.X.

I already found a solution and will create a PR for this.

**Comment by rkewlani** [comment]
As discussed in #477 , this is fixed as part of https://github.com/Adyen/adyen-magento2/pull/497 hence closing this issue here. 
thanks for the contribution.
