### ISSUE TITLE
Shipping undefined when cancelling POS payment

### ISSUE THREAD

**Issue by rklerck** [Adyen/adyen-magento2#49]
When it returns to the website after a cancelled or failed POS payment, the summary shows "Shipping (undefined - undefined)". It's on the first page where it's redirected to, along with the error message of the failed payment.

**Comment by rikterbeek** [comment]
Hi @rklerck,

I could not reproduce this on my environment. What kind of shipping method do you have turned on ?

Regards,
Rik
Adyen

**Comment by rklerck** [comment]
The Point of Sale (POS) integration method.

**Comment by rikterbeek** [comment]
Hi @rklerck,

I understand but I meant what shipping method did you chosen in the checkout ?

Regards,
Rik
Adyen

**Comment by rklerck** [comment]
It doesn't matter which shipping method I select, I always return to the page with the message "Your payment failed, please try again later". And in the summary it's "Shipping (undefined - undefined)".

**Comment by rikterbeek** [comment]
Hi @rklerck,

I can not reproduce it so think you have some issues with your shipping method. The summary "Shipping (undefined - undefined)" is not coming from our module so think something else is triggering this.

Can you try this on a clean Magento installation ?

Regards,
Rik
Adyen

**Comment by rklerck** [comment]
It should be something with the cookie, right? The undefined - undefined comes from the fact it "lost" the selected shipping method.

So on your environment you see the error + in the summary you see the correct shipping method?

**Comment by rikterbeek** [comment]
@rklerck,

I cannot reproduce it. I got this:
![img_0393](https://cloud.githubusercontent.com/assets/5948499/16616482/d1c3243e-437d-11e6-9815-2a2dec81a3f7.PNG)


Regards,
Rik
Adyen

**Comment by rklerck** [comment]
Strange.. 

Could you show me the complete url (with all parameters) which you get back from de adyen app? 
Something like "..../adyen/process/resultpos/originalCustomCurrency......"

**Comment by rikterbeek** [comment]
Hi @rklerck,

[2016-07-22 08:57:31] AdyenLoggerTest.ADYEN_RESULT: Array
(
    [originalCustomAmount] => 84000
    [result] => CANCELLED
    [cs] => 5
    [cancelMessage] => Transaction cancelled while waiting for terminal to come online
    [originalCustomSessionId] => d8bf4e00c2c60d22a403ae608a2b43dd
    [sessionId] => d8bf4e00c2c60d22a403ae608a2b43dd
    [originalCustomCurrency] => EUR
    [merchantAccount] => PME_POS
    [merchantReference] => 000000220
    [originalCustomMerchantReference] => 000000220
    [cancelCode] => 30100
)
 {"is_exception":false} []
[2016-07-22 08:57:31] AdyenLoggerTest.ADYEN_RESULT: Checksum is valid {"is_exception":false} []
[2016-07-22 08:57:31] AdyenLoggerTest.ADYEN_RESULT: Result is:CANCELLED {"is_exception":false} []
[2016-07-22 08:57:31] AdyenLoggerTest.ADYEN_RESULT: Order is cancelled {"is_exception":false} []

Regards,
Rik
Adyen

**Comment by rikterbeek** [comment]
Hi @rklerck,

Is your problem solved ?

Regards,
Rik
Adyen
