### ISSUE TITLE
Disabled payment methods still available in Magento

### ISSUE THREAD

**Issue by sanderjongsma** [Adyen/adyen-magento2#491]
**Magento version**: 2.3.2
**Plugin version**: 4.3
**Description**
In the skin I disabled some payment methods, but they are still visible in Magento as payment methods. 
![Screenshot from 2019-08-05 15-34-05](https://user-images.githubusercontent.com/2726055/62468622-c2a3c180-b796-11e9-95b3-f7c15e9fefd0.png)

The adyen backend does not support disabling payment methods from the payment view:
![Screenshot from 2019-08-05 15-37-58](https://user-images.githubusercontent.com/2726055/62468728-0bf41100-b797-11e9-949b-1f09497b5077.png)

So I disabled them in the skin but they still appear in magento, is this supposed to work this way or is it a bug?

**Comment by trebb0r** [comment]
A far as I know, they removed the ability to use skins fom version 3.0.0 and up. You can only enable / disable payment methods by country and even then, you might need help from Adyen support to set that up for you.

**Comment by sanderjongsma** [comment]
Ah I think you are right. Thanks for your help.
