### ISSUE TITLE
Magento 2.3.2 3D Secure Redirect broken

### ISSUE THREAD

**Issue by davidverholen** [Adyen/adyen-magento2#492]
**Magento version**: 2.3.2
**Plugin version**: 4.3.0
**Description**
When paying with credit card with 3d Secure enabled, after 3d Secure validation the customer is redirected to the Homepage with the error Message "Ivalid Form Key"

The order is created but the payment authorization does not happen so basically the payment cannot be captured.

The issue itself is known and was already fixed, and the fix worked until 2.3.1 I guess.
A possible solution is provided in https://github.com/Adyen/adyen-magento2/pull/477, unfortunately this would probably mean to lose compatibility for 2.2.

I'm creating this issue to keep this on the tracker since currently this Module is not working with 2.3.2.

**Comment by rikterbeek** [comment]
Hi @davidverholen,

I think adding a value is solving the issue for all 3.3 and 3.2 versions. I am verifying this with @AntonEvers from Magento if this is indeed the solution.

Regards,
Rik
Adyen

**Comment by cyattilakiss** [comment]
Hi @davidverholen ,

Could you please confirm that the new release of the plugin which also includes the fix for your issue is working for you as well?

Thank you in advance,
Attila
Adyen
