### ISSUE TITLE
Expired orders don't get canceled

### ISSUE THREAD

**Issue by juliansthl** [Adyen/adyen-magento2#50]
The Magento Cron does not clear any orders where Adyen HPP was used as a payment method.
If the customer leaves the checkout process on the Adyen HPP page, the order status stays on "pending" and is not set to "cancelled" by the Magento expired orders cron (module-sales/Model/CronJob/CleanExpiredOrders.php).

We believe the reason is, that CleanExpiredOrders.php is looking for orders with the status STATE_PENDING_PAYMENT (line 55), but the Adyen extension is setting the order status to what is configured in the Adyen configuration options (line 221 in adyen-magento2/Model/Method/Hpp.php). The "pending" option in the dropdown in the Adyen config is really "pending" though and there is no option to choose "pending_payment".

Thanks,
Julian

**Comment by rikterbeek** [comment]
Hi @juliansthl,

With canceling payments by automatic scripts you need to be very careful. For example for bank transfer payments it could take a week before you have received this payment. I am not sure how this script work but i don't think it is looking at the payment method type. We need to have a closer look if this is something we can support or this is to risky to allow by default.

Regards,
Rik
Adyen

**Comment by juliansthl** [comment]
Hi @rikterbeek ,

Thanks for your quick response!
The CleanExpiredOrders function only cancels orders that have the status "pending_payment" (this is not the same as "pending"). The core paypal module for example sets the status "pending_payment".

Best,
Julian

**Comment by rikterbeek** [comment]
Hi @juliansthl,

Yes that is clear but you do not want to cancel some payments that are in pending mode like for example bank transfers.

Regards,
Rik
Adyen
