### ISSUE TITLE
Adyen credit card type restriction is not working correctly when multiple options are selected

### ISSUE THREAD

**Issue by cmopt** [Adyen/adyen-magento2#504]
**Magento version**: 2.3.*
**Plugin version**: 4.3.0

**Description**

Steps to reproduce:

1. Navigate to Admin>Stores>Configuration>Sales>Payment Method
2. Expand Adyen Credit Card API Integration
3. In Credit Card Types select multiple entries (e.g Mastercard AND American Express)
4. Login to website, add a product to cart and proceed to checkout
5. For payment method input a valid credit card type that is not eligible (e.g Visa)
6. Complete order

Notice that the card appears is not recognized but appears validatedvalidated (green checkmark but with a generic icon instead of the Visa logo)

Notice that the user can place the order with the Visa card even if it is not supported

This issue does not occur if only one selection is made for credit card types (e.g if only Mastercard is selected then Visa credit cards are rejected)

**Comment by msilvagarcia** [comment]
I can reproduce this issue. Added to the team's backlog, will update this when we fix it.

**Comment by msilvagarcia** [comment]
After further investigation we realized the problem is actually in Checkout. It should also not be accepted in the `/payment` call.

Feel free to create a new issue if there are any questions left.

Cheers!
Marcos
Adyen
