### ISSUE TITLE
User is not asked for CVC when using a saved Adyen credit card with One-Click Agreement type

### ISSUE THREAD

**Issue by cmopt** [Adyen/adyen-magento2#505]
**Magento version**: 2.3.*
**Plugin version**: 4.3.0

**Description**

1. Navigate to admin>Stores>Configuration>Sales>Payment methods expand 
2. Expand Stored Payment Methods - Requires Adyen Credit Card and set Agreement type as One-Click
3. Save changes and clear cache
4. Login to website, add product to cart and complete checkout with an Adyen card while ticking the Save for later use checkbox
4. Add another product to cart and proceed to checkout
5. Select saved credit card

Notice that the CVC is not asked and the user can complete the purchase without inputting any other details

According to Adyen documentation user must input CVC when using a saved card when One-Click Agreement type is selected. User should not be asked for CVC only when Recurring is set as Agreement Type

<img width="945" alt="Screenshot 2019-08-21 at 19 11 26" src="https://user-images.githubusercontent.com/54363917/63448999-d19d9b80-c447-11e9-8ea6-56824cacfbb3.png">
<img width="992" alt="Screenshot 2019-08-21 at 19 10 39" src="https://user-images.githubusercontent.com/54363917/63449000-d19d9b80-c447-11e9-8dd8-49a472cf08f7.png">
<img width="900" alt="Screenshot 2019-08-21 at 19 10 15" src="https://user-images.githubusercontent.com/54363917/63449002-d19d9b80-c447-11e9-9519-da66eec97c1a.png">

**Comment by msilvagarcia** [comment]
I can reproduce this issue. Added to the team's backlog, will update this when we fix it.

**Comment by Aleffio** [comment]
Hi @cmopt ,

The Vault Enabled setting will override the Stored Payment Methods option.
Since the Vault only uses Recurring option(without the shopper needing to insert the CVC), this will not use the Oneclick function.

Can you please disable the Vault Enabled option?
We are working on making the description of the configuration menu more clear.

Kind Regards,
Alessio
Adyen
