### ISSUE TITLE
psd/2 compliance

### ISSUE THREAD

**Issue by davidverholen** [Adyen/adyen-magento2#507]
**Magento version**: all
**Plugin version**: latest
**Description**

Creating this for tracking any possible issues / updates for psd/2 since its only a few more weeks

1. will there be a new release / is there anything to do in the extension 
2. Are there any configurations maybe that have to be set in a specific way for psd/2?

**Comment by cyattilakiss** [comment]
Hi @davidverholen ,

There is no planned next release (feature) for PSD2 functionality in the plugin, the latest version is enough to process.
You just need to enable the 3DS2 under the card payments section in your Magento Adyen plugin settings and if everything is already configured correctly it should work out of the box :)

Best,
Attila
Adyen
