### ISSUE TITLE
Adyen recording same billing and shipping address as shipping address when they are different in Magento

### ISSUE THREAD

**Issue by sskharate** [Adyen/adyen-magento2#508]
**Magento version**: Magento Commerce Cloud 2.2.9 
**Plugin version**: 4.2.1
**Description**
We are seeing some cases where - On Adyen, the billing and shipping address are both same as the order shipping address when they are different in Magento Order.

Is this a known issue? and is there a fix available?

Thanks
Sagar

**Comment by cyattilakiss** [comment]
Hi @sskharate ,

We are retrieving the billing address and shipping address from the quote but it can be that it is still not updated when we retrieve the data in the backend. We are going to look into it and inform you. Meanwhile if you have any solution we really appreciate the pull request :)

Best,
Attila
Adyen

**Comment by sskharate** [comment]
Hi @cyattilakiss 

Is there a fix for this now?

Thanks
Sagar

**Comment by cyattilakiss** [comment]
Hi @sskharate ,

Not yet, but we are going to pick this item up in the next sprint. and hopefully going to fix it quick.

Best,
Attila
Adyen

**Comment by cyattilakiss** [comment]
Hi @sskharate ,

I will close this PR since it is already fixed in the version 5 and above. See my comment in the related PR: https://github.com/Adyen/adyen-magento2/pull/543#issuecomment-547443754

Have a nice day!
Best,
Attila
Adyen
