### ISSUE TITLE
Order is payed, but is not created in Magento

### ISSUE THREAD

**Issue by gigadesign1** [Adyen/adyen-magento2#526]
**Magento version**: 2.3.2
**Plugin version**: 4.5.2
**Description**
We have been seeing payments in Adyen that don't have a corresponding order in Magento for a while now. This doesn't happen often and only seem to happen with creditcard payments.

There is no error recorded in the logs in Magento and usually the customers pay the order again, so they pay for their order twice.
When we contact the customer they say that the first order 'went wrong' and they just tried again.

I also checked if there is some module using an observer or a plugin around the placement of the order, but we have none. Everything is done through the cronjob.

We can provide transaction numbers if needed.

I'm wondering if anyone else is experiencing this same issue.

**Comment by yanielliot** [comment]
We have seen this issue a number of times, mainly during high load periods like flash sales or hyped product launches.

When it does happen we often find the Adyen merchant reference (Magento order number) in the Magento "quote" table as a "reserved_order_id".

Like you, can't find any errors in Magento logs related to these orders. Haven't had time dig into this issue to try and replicate.

**Comment by gigadesign1** [comment]
I just noticed that a customer wanted to place an order, but the placing of the order failed again.
The server was running smoothly at the time of ordering, the load was normal.

After digging through the logs I found that a request to save the payment information failed:
"POST /rest/[store_code]/V1/guest-carts/[cart_id]/payment-information HTTP/1.1" 400

This issue is reported quite often over all versions of Magento 2:
https://www.google.com/search?q=magento+2+post+request+guest-carts+payment-information+400+bad+request

Apparently, the message is saying "There was a problem on the server, try to place the order again."
This explains why customers always try again and pay for their order twice or more until they hit the fraud score.

I will create a module to log the actual message to a log file in case this issue happens again.

I'm still not convinced that this is a Magento bug and has nothing to do with the Adyen module, since we are using 3 different payment modules and only the Adyen module is giving this issue.
So please keep this issue open for now.

**Comment by cyattilakiss** [comment]
Hi @gigadesign1 ,
 
Thank you for raising this issue. If you could log the message that would be a really big help for us also to see if the issue is happening on the plugin end or if there is a performance issue maybe during doing the payment.

We have just implemented the idempotency key in the current release 4.5.3 so even if the 400 error is still there and the payment went through but the order was not created and the server "died" and the shopper placed the order again it will just end up with the previous status of the payment and no second transaction is created.

Please let me know if you can log the actual error message and please send it to us.
Also please upgrade to the latest version and to have the idempotency key feature.

Best,
Attila
Adyen

**Comment by gigadesign1** [comment]
I have implemented the log and I have found that the issue is caused by the ChangeQuoteControlInterface returning false on the isAllowed method.

"CRITICAL: Magento\Framework\Exception\StateException: Invalid state change requested in vendor/magento/module-quote/Model/QuoteRepository/Plugin/AccessChangeQuoteControl.php:45"

So it seems like logged in customers are not allowed to change their own cart or guest customers have an active cart with a customer id.

There is no module in the stack trace, only core Magento methods. So it doesn't seem to be an issue related to the Adyen Payment module or any other thrid party module.

I'm trying to figure out how a customer ends up with a 'corrupt' cart at the time of placing an order so that I can reproduce the issue and report it at Magento.

Thanks for your information. I will update to the newest version to prevent duplicate payments in the future.

I'll close this issue for now since it doesn't seem to be an issue in the Adyen module.

**Comment by tcmax76** [comment]
Did you ever figure anything out with this? We're having the same issue on our sites (not using the Adyen module, but running into the same missing orders and Invalid State change error), but can't seem to find a solution to this.

**Comment by gigadesign1** [comment]
Hi @tcmax76 ,

I wasn't able to reproduce the issue yet.

For the time being I wrote a small module that updates the quote when the invalid state is detected.
So if a logged in customer wants to pay for a guest cart, the module will just assign the customer to that cart and vice versa.
It's not a great permenant solution, but it fixes the issue and enables the customers to place an order again.

I'm running this for a couple of weeks and I haven't had any reports of order that weren't created.

I'll tidy up the module and share the code on my github if I have time tonight. I'll let you know.

**Comment by tcmax76** [comment]
@gigadesign1 Thank you! We'd love to test out your module if you have time to post the code. We're getting a few missing orders every day on our sites, it seems, so anything that could resolve that would be a huge help.

If you don't have time to tidy it up, if you could just share the applicable code we could package it into our own module, as well. Thanks again!

**Comment by gigadesign1** [comment]
@tcmax76 You can find the module here: https://github.com/gigadesign1/module-magento2-fix-invalid-state-change
You can install it through composer if you want to.
Please let me know if this fixes your issue.

**Comment by tcmax76** [comment]
Thank you @gigadesign1 ! We're going to install this and test it out...really appreciate it.
