### ISSUE TITLE
[PW-1796] Validation for social security number is missing

### ISSUE THREAD

**Issue by omarmohssen** [Adyen/adyen-magento2#542]
**Magento version**: 2.3.2
**Plugin version**: 4.3.0
**Description**
1- Boleto enabled from backoffice 
2- Proceed to checkout 
3- choose Boleto as a payment method and complete an invalid Social security number (ex: 5 digits)

actual behaviour: the order is placed without errors
expected behaviour: the Social number should be validated and an error message should be thrown

The issue is available on other payment methods as well but seems to work on cash on delivery

**Comment by msilvagarcia** [comment]
Hey @omarmohssen !

We are taking a look into this and will provide more information soon.

Cheers!
Marcos
Adyen
