### ISSUE TITLE
Incorrect grand total amount when using REST API

### ISSUE THREAD

**Issue by sergy-gzh** [Adyen/adyen-magento2#546]
**Magento version**: 2.3.3
**Plugin version**: 4.5.4
**Description**
When calling `retrieve-adyen-payment-methods` API for both `customer` and `guest` Adyen magento module is using session to fetch quote info.
As a result incorrect quote info (empty) is achieved and default value of (10) is communicated.
**Expected**
Rest API will load quote data based on the provided `cart_id` not session data.
https://github.com/Adyen/adyen-magento2/blob/develop/Helper/PaymentMethods.php#L383

**Comment by cyattilakiss** [comment]
Hi @sergy-gzh ,

Thank you for raising the issue, we are aware of the problem and going to work on it as soon as possible.

Best,
Attila
Adyen

**Comment by sergy-gzh** [comment]
Wow, easy stale bot! Issue is relevant.

**Comment by cyattilakiss** [comment]
@sergy-gzh sorry for the bot :) We just installed it and haven't set all the necessary tags yet but we are on it.

**Comment by cyattilakiss** [comment]
Hi @sergy-gzh , 

Thank you for the patience. The fix has just been released in the version 6.0.0 but you can also give a look to the pull request with the fix #667

Please note that for PWA integrations version 6.0.0 includes breaking changes and the updated documentation for PWA integration is coming soon on our docs page.

I will close this issue now, but please feel free to reopen it if you still experience the issue after the upgrade.

Best,
Attila
Adyen
