### ISSUE TITLE
Support for Magento 2.1

### ISSUE THREAD

**Issue by kweij** [Adyen/adyen-magento2#56]
With the release of Magento 2.1 I'd really like to upgrade, however the Adyen-Magento-2 module does not support it yet. When may I (we) expect support for 2.1 (or internal/composer version 100.1.*)? The change could possibly be small (only in composer.json) but the code needs to be tested with the new version.

Thanks in advance!

**Comment by rikterbeek** [comment]
Hi @kweij,

I am now installing the 2.1.0 module to check if it is compatible. I don't think it will break so then hopefully we have this today ready and otherwise on Monday.

Regards,
Rik
Adyen

**Comment by rikterbeek** [comment]
Hi @kweij,

Did not see any strange things on the new 2.1.0 release of magento so I created a new release that supports this see: https://github.com/Adyen/adyen-magento2/releases/tag/1.4.3

Regards,
Rik
Adyen
