### ISSUE TITLE
[PW-1941] Adyen payment resets the data (on selected payment method that reuires additional input) every time you change something in the address or the address is validated

### ISSUE THREAD

**Issue by othuress** [Adyen/adyen-magento2#561]
**Magento version**: 2.3.3
**Plugin version**: x4.4.0
Adyen payment resets the data (selected bank in the bank dropdown and "Personal Number") every time you change something in the address or the address is validated:

**Comment by cyattilakiss** [comment]
Hi @othuress ,

Thank you for raising this issue, we are going to pick this up into our backlog.
This should only happen if the shipping address is changed and not the billing address.

Best,
Attila
Adyen

**Comment by othuress** [comment]
Hi Attila.

Thanks for the feedback.

Can you test this behaviour in our checkout and see for your self?
http://dev-m2.beslagsbutiken.se/

Not sure that would solve this issue: "This should only happen if the shipping address is changed and not the billing address."

Regards
Ola

**Comment by lukaszlempicki-sii** [comment]
@cyattilakiss How is it going with fixing the issue?

**Comment by AlexandrosMor** [comment]
Hello @othuress,

I see there is an internal ticket for this issue. We are going to add it to our future sprints. 

kind regards,
Alexandros

**Comment by othuress** [comment]
Hello @AlexandrosMor 

Excellent!

Regards,
Ola

**Comment by tnaber** [comment]
Hi,

I'm closing this issue as the flow has changed and it is therefore not relevant anymore. Please reopen if the issue still persists for you :)

Cheers,
Titus
