### ISSUE TITLE
[PW-2771] Invoice paid even if the capture fails

### ISSUE THREAD

**Issue by alexlarocca** [Adyen/adyen-magento2#592]
**Magento version**: 2.3.3
**Plugin version**: 5.0.2
**Description**

When the invoice is created, the invoice state immediately is set to Paid. Anyway we only received the synchronous api response “capture-received”. This does not mean that payment has already captured. It just means that Adyen is taking care to capture the payment, and the result will be notified within a couple of minutes by the asynchronous notification. Only this will confirm if the payment has been successfully captured or not. 

Then the correct way to manage the invoice state by asynchronous notification is the following:

1) when the invoice is created the invoice state is “Pending”
2) when the asynchronous notification is received the invoice state changes to “Paid” if the payment was captured successfully. While if the capture failed, the invoice state changes to “Canceled”

A simple case: 
- Make a first partial invoice (status is paid)
- First invoice receives a capture notification with success=true
- Make a second invoice for the rest of the order (status is paid)
- Since my account does not have multi captures enabled, the second invoice receives a capture notification with success=false
- the order on Magento appears totally invoiced and paid, unless a comment on the history reporting the failure

**Comment by Aleffio** [comment]
Hi @alexlarocca ,
when the invoice is created, it is set automatically to state Paid,
do you have any suggestions on how to create it in a pending state?
https://magento.stackexchange.com/questions/237492/magento-2-status-invoice-not-paid-yet-instead-of-paid
Here they suggest to use a Plugin, but it is also an old issue, do you have any other ideas?

Regards,
Alessio

Adyen

**Comment by alexlarocca** [comment]
Hi @Aleffio, 
I suggest you to give a look at the Amazon Pay module. At least their module for Magento 1 was able to do it. Like Adyen, even on Amazon Pay a capture response can be async. At first stage, it creates a pending/open (state=0) invoice. Then the async notification changes the state according the capture result to 1 (paid) or 2 (canceled). 

Magento 2 embed the Amazon Pay module. Currently I have not an amazon merchant account to test but I guess it still works like the previous version.

**Comment by alexlarocca** [comment]
I'm not an experienced magento 2 developer, but this is how a pending invoice can be created:

```
$invoice = $order->prepareInvoice();
$invoice->getOrder()->setIsInProcess(true);
$pspReference = $order->getPayment()->getAdyenPspReference();
$invoice->setTransactionId($pspReference);
// $invoice->register()->pay();
$invoice->setState(1); // 1 = OPEN, 2 = PAID, 3 = CANCELED
$invoice->register();
$invoice->save();

```
Next, when the capture notification is processed the invoice state can be updated accordingly:

```
$invoice->pay();
$invoice->save();

```

**Comment by alexlarocca** [comment]
Hi @Aleffio,
Is there a way to programmatically understand if an invoice has been successfully paid or not?
The capture result comes from the async notification and it is stored within the table adyen_notification (success).
The notification can be related to the order by mean of the merchant_reference field but, since an order can have more invoices, 
I need to relate the notification to the invoice that triggered the capture.
The link between the notification and the invoice should be the pspreference returned by the call to the capture request api. 
Unfortunately it seems that this useful information is not stored anywhere, just added to the order history with the capture request result (capture-received).
Is there a way to catch the pspreference and store it on a custom attribute of the invoice table?

**Comment by acampos1916** [comment]
Hello @alexlarocca, picking this issue up!

I believe the plugin stores the invoice-PSPref relationship in the adyen_invoice table, and this could be used to move the desired invoice to Paid when the capture notification with a PSPref is received.

And the capture handler can be used to set the status of the invoice to "Pending" if the response is "[capture-received]".

We're planning this change now and will update here with any progress made.
