### ISSUE TITLE
OFFER_CLOSED cancel cancelled orders

### ISSUE THREAD

**Issue by peterlembke** [Adyen/adyen-magento2#594]
**Magento version**: 2.3.2
**Plugin version**: 5.0.2
**Description**
When we manually cancel an order and later get an OFFER_CLOSED then the order is cancelled again.
https://github.com/Adyen/adyen-magento2/blob/develop/Model/Cron.php#L959

We get double entries in table inventory_reservation

279599	2	CAR01-6000-60041-46	-1.0000	{"event_type":"order_placed","object_type":"order","object_id":"275926"}
300060	2	CAR01-6000-60041-46	1.0000	{"event_type":"order_canceled","object_type":"order","object_id":"275926"}
341434	2	CAR01-6000-60041-46	1.0000	{"event_type":"order_canceled","object_type":"order","object_id":"275926"}

That makes our salable stock higher that it actually is.

**Comment by Aleffio** [comment]
Hi @peterlembke , 
thank you for opening the issue,
I submitted a PR that will solve this, we will review and merge it soon.

Regards,
Alessio
Adyen
