### ISSUE TITLE
Possibility to edit payment method names

### ISSUE THREAD

**Issue by JeroenVanLeusden** [Adyen/adyen-magento2#595]
**Magento version**: 2.3.3
**Plugin version**: 5.0.2
**Description**
API call made in `\Adyen\Payment\Helper\PaymentMethods::fetchAlternativeMethods()` fetches all available payment methods with a predefined name. We'd like the possibility to alter these payment method names.

Would be nice to have a configuration somewhere that can fetch available payment methods and let us edit the names.

**Comment by Aleffio** [comment]
Hi @JeroenVanLeusden,

Thank you for opening the issue, unfortunately it is not possible to edit the predefined names we have at the moment from the /paymentMethods call.

Regards,
Alessio
Adyen
