### ISSUE TITLE
[PW-1972] Housenumber/addition not visible in Adyen for paypal and credit cards orders

### ISSUE THREAD

**Issue by vpodorozh** [Adyen/adyen-magento2#596]
**Magento version**: 2.3.1
**Plugin version**: 5.0.2
**Description**
When the address is added manually on checkout, there is a possibility to fill in the "Addition" field, if needed.
The value from this field is not displayed in Adyen if the payment method is Paypal or credit cards.

-----------------------------------

![Visa](https://user-images.githubusercontent.com/16047928/70249630-54dbc680-1785-11ea-91e6-f8bfc28bfb2b.png)

**Comment by rkewlani** [comment]
Hi @ vpodorozh, thanks for contacting us. We are looking into this issue and will get back to you as soon as possible.
Regards,
Adyen

**Comment by cyattilakiss** [comment]
Hi @vpodorozh ,

Is the 3rd street line, the "Addition" field you mention? Indeed we just use the streetLine1 and streetLine2 but not the streetLine3.
We are going to pick this up into our backlog to send the 3rd line as well in the request not just the first 2.

Best regards,
Attila
Adyen

**Comment by vpodorozh** [comment]
Hello, yes - it is the 3rd line of the street address.

**Comment by vpodorozh** [comment]
Any update on this?

**Comment by melnickforever** [comment]
Do you have any update on this?

**Comment by cyattilakiss** [comment]
Hi @vpodorozh , @melnickforever 

We have just picked up this ticket in the current sprint and we plan to release it 2 weeks from now in case there are no unexpected blockers.

Best,
Attila
Adyen

**Comment by cyattilakiss** [comment]
Hi @vpodorozh , @melnickforever

6.1.1 version has just been released. Let me know if you still face issues regarding this ticket.

Best,
Attila
Adyen

**Comment by melnickforever** [comment]
thank you
