### ISSUE TITLE
"3DS2.0 Enabled" configuration setting is not used

### ISSUE THREAD

**Issue by galdiuz** [Adyen/adyen-magento2#599]
**Magento version**: 2.3.2
**Plugin version**: 5.0.2
**Description**:
The "3DS2.0 Enabled" setting found under "CreditCard API integration" in Magento system config is never used since v5.0.0. The only usage of the setting in the code is in `Adyen\Payment\Helper\Data::isCreditCardThreeDS2Enabled`, but that function is never used.

```
➜  magento git:(master) grep -rni "threeds2_enabled" vendor/adyen
vendor/adyen/module-payment/etc/adminhtml/system/adyen_cc.xml:66:            <config_path>payment/adyen_cc/threeds2_enabled</config_path>
vendor/adyen/module-payment/etc/config.xml:64:                <threeds2_enabled>1</threeds2_enabled>
vendor/adyen/module-payment/Helper/Data.php:1821:        return $this->getAdyenCcConfigDataFlag('threeds2_enabled', $storeId);
➜  magento git:(master) grep -rni "isCreditCardThreeDS2Enabled" vendor/adyen
vendor/adyen/module-payment/Helper/Data.php:1819:    public function isCreditCardThreeDS2Enabled($storeId = null)
```

It used to be used in Adyen\Payment\Model\AdyenPaymentProcess, which was [removed in v5.0.0](https://github.com/Adyen/adyen-magento2/commit/01997eee61bbed0f60fb8ae5cf07ed36c2bb366d#diff-1e83b8f13c9c4345dfc50a69c1718572L167).

While I'm not fully aware of how the payment flow works, one suggestion of where this perhaps should be used is in [`Adyen\Payment\Helper\Requests::buildThreeDS2Data`](https://github.com/Adyen/adyen-magento2/blob/5.0.2/Helper/Requests.php#L307), like so:
```diff
diff --git a/Helper/Requests.php b/Helper/Requests.php
index 9111572..afe9294 100644
--- a/Helper/Requests.php
+++ b/Helper/Requests.php
@@ -304,7 +304,7 @@ class Requests extends AbstractHelper
      */
     public function buildThreeDS2Data($request = [], $additionalData)
     {
-        $request['additionalData']['allow3DS2'] = true;
+        $request['additionalData']['allow3DS2'] = $this->adyenHelper->isCreditCardThreeDS2Enabled();
         $request['origin'] = $this->adyenHelper->getOrigin();
         $request['channel'] = 'web';
         $request['browserInfo']['screenWidth'] = $additionalData[AdyenCcDataAssignObserver::SCREEN_WIDTH];
```

**Comment by cyattilakiss** [comment]
Hi @galdiuz ,

Thank you for raising this issue.
We are going to pick up this issue immediately.

Best,
Attila
Adyen

**Comment by cyattilakiss** [comment]
Hi @galdiuz ,

We are going to release the fix for this issue soon, so I will close the issue for now.
Please feel free to reopen it if you have any questions.

Have a great day!
Best,
Attila
Adyen

**Comment by BenEddi** [comment]
Hello @cyattilakiss, The issue is not fixed yet, please is there any updates on this matter?
