### ISSUE TITLE
Exception on "sales_order_invoice_pay" event makes Order to be stuck on "Payment Review"

### ISSUE THREAD

**Issue by viniciusfabri** [Adyen/adyen-magento2#603]
**Magento version**: 2.3.2
**Plugin version**: 4.5.1
**Description**
Steps to reproduce: 
- Create an Observer on _sales_order_invoice_pay_ that throws an exception (\Magento\Framework\Exception\CouldNotSaveException in our case)
- Create an order and pay with Adyen

Expected results:
- Notification is not processed correctly, on the catch of the exception in the Adyen module the database changes are reverted 

Actual results:
- Notification is not processed correctly, but _adyen_order_payment_ entry is still in there, so the next time the cron job tries to process that notification, we get an "Unique constraint violation" in that table because the pspreference is already there

Adyen\Model\Cron::_createInvoice() triggers that event, and a third party module has an observer that sends the Order to a third party service that does some business logic, but throws an exception if it fails (in this case it seems the service was down). I don't think this is the best solution, but I still don't think the Adyen module should put itself in a stuck position if the notification process fails for some reason

**Comment by cyattilakiss** [comment]
Hi @viniciusfabri ,

Thank you for raising the issue. I picked up this item into our backlog to find a solution.

Best,
Attila
Adyen

**Comment by cyattilakiss** [comment]
Hi @viniciusfabri ,

Just merged a PR which will introduce a fix for this issue. We are going to release it in the next release cycle.

Best,
Attila
Adyen
