### ISSUE TITLE
Under some circumstances, it's possible to make a payment but no Order created

### ISSUE THREAD

**Issue by viniciusfabri** [Adyen/adyen-magento2#629]
**Describe the bug**
If Persistent Cart and Guest Checkout are both enabled, if the customer's session expires with an on-going cart, the user is able to make all the way through to the payment step, submit their credit card info, Adyen processes the notification, but an exception is thrown in Magento that blocks the order from being created (but the customer's card was charged already)

**To Reproduce**
1. Enable Persistent Cart and Guest Checkout, with Adyen Credit Card as payment method
2. Create customer account
3. Login to customer account
4. Add product to cart
5. Go to checkout
6. Edit PHPSESID cookie and set a different value; or delete the cookie. Main idea is to get a different session (as if your current session expired for various reasons), meaning you will no longer be logged in but persistence will keep your current customer data.
7. Refresh page. If redirected to empty cart use minicart to go back to back to checkout. May have to try multiple times, sometimes it does not work from the first try.
8. Fill checkout form data and place order

**Expected behavior**
User is able to place Order

**Actual behavior**
User is shown "Invalid State Change Requested" exception message, Order is not created, but their card was charged (if payment is authorised immediately)

**Screenshots**
Below is a screenshot of our exception.log in Production:
![image](https://user-images.githubusercontent.com/11316647/72433626-05cc7c80-379a-11ea-9f47-8afc1f4c5d48.png)
Each exception is one submission of the payment form, meaning that this particular customer was charged more than 5 times.
This patterns repeats every couple of days on a small/medium sized e-commerce, so I imagine it's not that rare

**Additional context**
I did some digging on this. I initially thought it was a Magento bug, but I could not reproduce it there. Then I noticed it was happening only with Adyen as the payment method. When the scenario above occurs (guest customer trying to finish an order from a quote that belonged to a customer), Magento would "anonymize" the Quote on _vendor/magento/module-persistent/Model/Checkout/GuestPaymentInformationManagementPlugin.php_, which basically removes the customer ID, customer, etc from the Quote object and then saves it.

The Adyen module, however, gets the quote from the Session [here](https://github.com/Adyen/adyen-magento2/blob/develop/Gateway/Validator/InstallmentValidator.php#L80), which then Magento fills the customer information back in, making the check in vendor/magento/module-quote/Model/ChangeQuoteControl.php::isAllowed() fail

My suggestion for the fix would be to change [this](https://github.com/Adyen/adyen-magento2/blob/develop/Gateway/Validator/InstallmentValidator.php#L80) to instead of grabbing the quote from the session, to instead load the quote using a QuoteRepository and getting the Quote ID from $validationSubject['payment']->getQuoteId(), this way you'll get the latest quote information from the DB

**Comment by cyattilakiss** [comment]
Hi @viniciusfabri ,

Thank you for raising this issue and for the digging. We are going to look into it immediately and roll out the fix asap since this is a pretty nasty issue.

Best,
Attila
Adyen
