### ISSUE TITLE
Google Pay not correctly set up in production mode

### ISSUE THREAD

**Issue by ebaschiera** [Adyen/adyen-magento2#640]
**Describe the bug**
Hi,
when configuring Google Pay to work in production mode, at checkout Google Pay says "Google Pay is not available".
It looks like the environment variable is not correctly initialized.

**To Reproduce**
1. Configure Adyen moduel for production mode
2. Activate and enable Google Pay

**Expected behavior**
At checkout the Google Pay button should appear. Instead the button is not visible and there's an error message: "Google Pay is not available"

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser: Chrome 
 - Version 79

**Additional context**
The problem IMHO is at line https://github.com/Adyen/adyen-magento2/blob/develop/view/frontend/web/js/view/payment/method-renderer/adyen-google-pay-method.js#L104 where Google Pay expects "PRODUCTION" but it gets "LIVE".

Thanks!

**Comment by cyattilakiss** [comment]
Hi @ebaschiera,

Thank you for raising this issue. We are going to test it against your steps in our instances and in case we can reproduce the issue we are going to make a bug fix asap.
Also if you could provide a pull request with the fix we would be grateful review and release that.

Best,
Attila
Adyen

**Comment by cyattilakiss** [comment]
Hi @ebaschiera ,

Indeed, I verified that we do propagate the wrong value.

Best,
Attila

**Comment by Aleffio** [comment]
Hi @ebaschiera,

This issue has been fixed in the latest(5.4.0) release,
closing the issue,

Kind Regards,
Alessio
Adyen
