### ISSUE TITLE
[PW-2096] Google Pay button doesn't validate checkout data before placing order

### ISSUE THREAD

**Issue by ebaschiera** [Adyen/adyen-magento2#642]
**Describe the bug**
Hi,
if at checkout there are some required Terms and Conditions to be checked before placing the order, the form is not validated when clicking on the "Pay with Google Pay" button.

**To Reproduce**
1. Enable Google Pay at checkout
2. Add a Terms and Conditions entry in Stores -> Terms and Conditions
3. Set that T&C as "Applied: Manually"
4. Place an order

**Expected behavior**
If I don't flag the checkbox of T&,C I should be blocked with a "missing required field" message and order should not be placed.

**Screenshots**
![googlepay-tc](https://user-images.githubusercontent.com/5667462/74160600-f36d2380-4c1d-11ea-80d8-b6ef6ed09a5a.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser: Chrome
 - Version: 79

**Additional context**

**Comment by cyattilakiss** [comment]
Hi @ebaschiera ,

Thank you for raising this issue regarding Google pay as well. I already verified the issue so I will tag it with a Bug label. We gonna roll out the fix for this one as well as soon as possible.

Best,
Attila
Adyen

**Comment by cyattilakiss** [comment]
Hi @ebaschiera ,

I've raised this issue for the checkout team who is working on the components to make this feature possible but I haven't got any update yet. Let me check with them if it's now possible to do the validation before the Google pay frame shows up.

Best,
Attila
Adyen

**Comment by cyattilakiss** [comment]
Hi @ebaschiera ,

the issue has been fixed in the version 6.6.1.
I will close this issue for now but please feel free to reopen it if you still face any issue related to this.

Best,
Attila
Adyen
