### ISSUE TITLE
A bug found in checkout process with Adyen CC latest version

### ISSUE THREAD

**Issue by vtransy** [Adyen/adyen-magento2#654]
Detail description of this issue noted here:

https://mrvts.wordpress.com/2020/02/26/magento-2-aduyen-bug-report-wrong-format-of-after-plugin-in-checkout-process-public-function-aftersavepaymentinformationandplaceorder/

Please check and fix ASAP

Thank you!

**Comment by acampos1916** [comment]
Hello @vtransy, thank you for raising this issue.

This has already been reported in #590 and a fix is soon to be released.

Please keep the issue reports in the recommended format so we can easily identify duplicates and reproduce.
