### ISSUE TITLE
[PW-2759] Online payouts support

### ISSUE THREAD

**Issue by vikramgorla** [Adyen/adyen-magento2#655]
**Is your feature request related to a problem? Please describe.**
We have alternate payment methods (e.g,. ATM payments in Portugal, Invoice payments in Switzerland,..) where the payout process is manual and disconnected with the order flow in Magento (no link to credit memo for e.g,. when you refund ATM payment using Adyen console to a bank account)

**Describe the solution you'd like**
1. Functionality in this extension, where when we create a credit memo/refunds on an order with alternate payment method (offline method like ATM payment or Invoice), possibility to select Online payout mode (e.,. card payout, bank account payout, wallet,.), enter payout reference (account number, card numner, wallet id,.) and trigger payout using Adyen online payouts.
2. Possibility to convert Store Credits in Magento into Online Payout so that we can either manually (in Magento Admin Panel) or programatically 
3. A Helper method in Adyen Magento module) to trigger a payout (which could support #2 as well)

**Describe alternatives you've considered**
We have a workaround to trigger it manually in Adyen console, but it is time consuming and breaking integrity (no reference to Magento objects)

**Comment by AlexandrosMor** [comment]
Hello @vikramgorla,
 
Thank you for raising this issue. We created an internal ticket to discuss this suggestion and going to get back to you with the answer. After that if you could also create a PR for this new functionality that would be very nice and we could include this feature in the next release as well. Contribution is always appreciated :)

kind regards,
Alexandros

**Comment by Morerice** [comment]
Hi @vikramgorla,

Apologies for the nearly three year delay, but as I thing you can assume, implementing payout functionality is not in our plans.

Regards,
Jean
Adyen
