### ISSUE TITLE
Alternative payment methods allow user to bypass required payment address

### ISSUE THREAD

**Issue by acjbizar** [Adyen/adyen-magento2#662]
**Describe the bug**
On the one-page checkout, the alternative payment methods of Adyen (in our case iDEAL and Klarna), seem unconcerned with whether the payment address is filled in correctly (or at all).

Native Magento payment methods only activate the payment button when the payment address is filled in correctly. The Adyen iDEAL payment method only requires a vendor/bank to be selected, and the Adyen Klarna payment method does not require any action.

**To Reproduce**
1. Go to `/checkout`
2. Click on on one of the Adyen (alternative) payment methods
3. Leave the payment address form empty
4. Watch the payment button get activated.

**Expected behavior**
I would expect the payment button to remain disabled until the required payment address form is filled in correctly, as appears to be the case with the native Magento payment methods.

**Screenshots**
![image](https://user-images.githubusercontent.com/411726/75979100-17035100-5ee0-11ea-80b1-551486df912b.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 80

**Additional context**
I see a difference in the `data-bind` of the payment button in comparison with the Magento native payment methods.

Magento (native) payment methods:
```
    click: placeOrder,
    attr: {'title': $t('Place Order')},
    enable: (getCode() == isChecked()),
    css: {disabled: !isPlaceOrderActionAllowed()}
```

Adyen (alternative) payment methods:
```
    click: $parent.continueToAdyenBrandCode, enable: placeOrderAllowed() && (value == $parent.isBrandCodeChecked())
```

I am guessing this causes it to miss some of the required conditions.

**Comment by cyattilakiss** [comment]
Hi @acjbizar ,

Thank you for raising this issue.
I just checked it and indeed, we let the user place the order when they disable the 'My billing and shipping address are the same' checkbox but since they don't update the address with the empty fields - because Magento by default does validation on it - we still use the billing address which is still there so the payment will go through.
I picked up this ticket into our backlog.

Best,
Attila
Adyen

**Comment by acjbizar** [comment]
Hi @cyattilakiss,

Thanks for your reply. The thing is though, this website does not use a shipping address, since their products are not shipped. (Instead, the user selects a pick-up location.) So this actually becomes a business critical issue for us.

Having said that, is it at all possible to make this a bit more high priority than putting it on a backlog? I think adding a `isPlaceOrderActionAllowed` condition to the submit button might fix it (but to be fair I have not tested this).

**Comment by acjbizar** [comment]
We needed to fix this for a client. We did so by overruling the template `hpp-form.html` in our theme.

I created a pull request (#685) that fixes this issues on the module level.

**Comment by rikterbeek** [comment]
@acjbizar,

Thanks for the PR that is now merged. I will close this ticket feel free to open a new issue if there are still issues to solve.

Regards,
Rik
Adyen
