### ISSUE TITLE
[BUG] Payment Methods do not match cart total amount

### ISSUE THREAD

**Issue by GGMCarl** [Adyen/adyen-magento2#664]
**Describe the bug**
Endpoint: rest/V1/guest-carts/XXX/retrieve-adyen-payment-methods

If payment amount is greater than XXX Eur for example payment methods do not change. Invoice like Klarna should not be possible to select and therefore be hidden in the response. Value should be detected by submitted cart id of magento. Currently the Module is broken at this point.. .also Adyen Rest-API Does always return same payment methods...

**Comment by GGMCarl** [comment]
Maybe releated to hist https://github.com/Adyen/adyen-magento2/issues/546

**Comment by cyattilakiss** [comment]
Hi @GGMCarl ,

Thank you for raising this issue, we are going to look into it and create the necessary follow up steps.

Best,
Attila
Adyen

**Comment by cyattilakiss** [comment]
Hi @GGMCarl ,

The fix has just been released in the version 6.0.0
Please note that this is a major release including breaking changes for backwards compatibility. (You can read more about the changes in the release notes)

I will close this issue for now but please feel free to reopen it if you still experience the issue after the upgrade.

Best,
Attila
Adyen
