### ISSUE TITLE
Payment methods not showing after upgrade from 1.3 to 1.4.3

### ISSUE THREAD

**Issue by martijn94** [Adyen/adyen-magento2#68]
Hi,

I just upgraded the extension to 1.4.3 via composer. But now my payment menthods are not showing anymore. Before the upgrade at version 1.3 they were showing just fine. I am using the Adyen test setup. Is there a setting changed that I cant find or is this a known issue maybe?

Thanks!

**Comment by rikterbeek** [comment]
Hi @martijn94,

The alternative payment methods (Adyen HPP) are now loaded into the checkout through a ajax call to the server. Make sure you have payment methods made available for the country that you have selected in the checkout.

Regards,
Rik
Adyen

**Comment by martijn94** [comment]
hi @rikterbeek 

Thanks for your fast response, do you mean inside the Adyen Backoffice or in Magento? In Magento I selected 'all allowed countries'.

In the Adyen backoffice I seem to have payment methods configured for this country (NL) by checking (settings > payment methods).

**Comment by rikterbeek** [comment]
Hi @martijn94,

Did you select netherlands as country in your checkout ?

Regards,
Rik
Adyen

**Comment by martijn94** [comment]
Hi @rikterbeek 

Yes, just tested the USA and I am experiencing the same issues there while there are several payment methods set to 'ANY' country.

**Comment by rikterbeek** [comment]
hi @martijn94,

There should be some exceptions/logging in the var/log directory could you check that make sure you have loggin enabled in magento. What payment methods are not showing, Adyen CC or Adyen HPP ?


Regards,
Rik
Adyen

**Comment by martijn94** [comment]
Hi @rikterbeek 

There are fresh logs printed on loading the payment selection page in /var/log/adyen/*. We hare using HPP. 

Magento itself does seem to print the following in the system.log but that doens seem to have been an issue when using 1.3.

`[2016-07-26 14:27:58] main.CRITICAL: Broken reference: the 'catalog.compare.sidebar' element cannot be added as child to 'sidebar.additional', because the latter doesn't exist [] []
[2016-07-26 14:27:58] main.CRITICAL: Broken reference: the 'sale.reorder.sidebar' element cannot be added as child to 'sidebar.additional', because the latter doesn't exist [] []
[2016-07-26 14:27:58] main.CRITICAL: Broken reference: the 'wishlist_sidebar' element cannot be added as child to 'sidebar.additional', because the latter doesn't exist [] []
[2016-07-26 14:27:58] main.CRITICAL: Broken reference: the 'store.settings.currency' tries to reorder itself towards 'store_language', but their parents are different: 'store.settings' and 'header.panel' respectively. [] []
`

Thanks!

**Comment by rikterbeek** [comment]
@martijn94,

That are just magento errors. There should be logs in the var/log/adyen directory don't you have any logging there ? What exact payment method is causing the issue ?

Regards,
Rik
Adyen

**Comment by martijn94** [comment]
Hi @rikterbeek 

There are logs, but no new logs are generated when opening the payment selection page. Do you have any help with the lastest log print? 

I basicly have issues with any payment method as none is being showed. We have iDeal and CreditCards activated along with some others.

**Comment by rikterbeek** [comment]
HI @martijn94,

What version of Magento2 are you on ?
Best to be on version 2.1.

Regards,
Rik
Adyen

**Comment by martijn94** [comment]
Hi @rikterbeek 

Currently running v2.0.7, do you think that could be the source of the issue?

**Comment by rikterbeek** [comment]
Hi @martijn94,

Not sure could you update to v2.1 and check if that solves your issues ?

Regards,
Rik
Adyen

**Comment by rikterbeek** [comment]
Hi @martijn94,

Are you problems solved on v2.1 ?

Regards,
Rik
Adyen

**Comment by martijn94** [comment]
Hey @rikterbeek 

We have not been able to test this just yet, I will close and reopen if needed.

Thanks!
