### ISSUE TITLE
Hitting enter on cc form redirects to checkout

### ISSUE THREAD

**Issue by teuma86** [Adyen/adyen-magento2#680]
**Describe the bug**
I noticed unexpected functionality when submitting an Adyen payment on the iPad. I entered all Adyen card details and on typing the final field I tapped the enter key on the iOS keyboard to submit the payment rather than tapping the Place Order button as I would normally do.

This then took me back to step 1 of the checkout process and required me to run through the whole checkout process again. Having checked the admin panel I can confirm the order wasn’t processed. I was then able to replicate this on desktop.

**To Reproduce**
Steps to reproduce:
1. Launch the website.
2. Login to an account.
3. Add an item to the basket.
4. Navigate to the checkout.
5. Select the Adyen payment method.
6. Enter the payment card details for each field.
7. On the final field, tap the enter key on the iOS keyboard or press the “Enter” key on the keyboard to submit the payment.

**Result**
The user is taken back to the first step of the checkout process.
 

**Expected behavior**
The order is submitted or the enter key has no functionality.

**Desktop (please complete the following information):**
Windows 10 - Chrome (latest), Edge (latest), IE11
OSX Chrome

**Smartphone (please complete the following information):**
iPad 6th Generation - 13.3.1
iPhone SE - 13.3.1

**Comment by cyattilakiss** [comment]
Hi @teuma86 ,

Thank you for raising this issue. I verified it and tagged it as a bug.
We are going to pick up this item to our backlog and fix it as soon as possible.

Best,
Attila
Adyen
