### ISSUE TITLE
Paypal logo missing from checkout

### ISSUE THREAD

**Issue by louisyatnam** [Adyen/adyen-magento2#69]
Hi,

After having the static content deploy done the Paypal logo gets missing in checkout page.

The image source points to:
https://www.domain.com/pub/static/frontend/_view/en_GB/Adyen_Payment/images/logos/paypal.png
Which is wrong - it should be something like:
https://www.domain.com/pub/static/frontend/domain/default/en_GB/images/paypal.png

Can you guys please have a look into this.

**Comment by rikterbeek** [comment]
Hi @louisyatnam,

Looks like this issue is already described here: #66 

Regards,
Rik
Adyen
