### ISSUE TITLE
Credit card fields not selectable on Edge versions

### ISSUE THREAD

**Issue by paulstolkbbd** [Adyen/adyen-magento2#693]
**Describe the bug**
Credit card fields cannot be focused on in the payment step in the checkout. This seems to be only in Edge 17 + Edge 18 and when in production mode. 

**To Reproduce**
1. Go to the payment step of the checkout in Edge 17 of 18
2. Select the credit card payment method
3. Try to fill in the credit card fields

**Expected behavior**
You can fill in all four credit card fields
Instead you can only fill in the name, the other fields cannot be selected

**Screenshots**
![Reproduced](https://user-images.githubusercontent.com/45177756/79544109-ca8a6400-808e-11ea-8d30-221afd1163d5.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Edge
 - Version: 17 + 18

**Additional context**
The webshop has different storeviews (different languages), and surprisingly they all have the problem except one storeview; the Dutch storeview works. My OS is Dutch, but I am not sure if that is related. 

When giving a **display: block !important;** to the .js-iframe class in the browser CSS editor I can select the fields again. 
![image](https://user-images.githubusercontent.com/45177756/79544403-4389bb80-808f-11ea-8bfe-8217cd732583.png)

**Comment by Aleffio** [comment]
Hi @paulstolkbbd ,
thanks for reporting this issue,
we are investigating internally about it,
can you please specify which version of the plugin are you using?
thanks,

Kind Regards,
Alessio
Adyen

**Comment by paulstolkbbd** [comment]
Hi Alessio,

We found out this was due to a Javascript file outside of the module, sorry! I will close this issue.
