### ISSUE TITLE
Magento adyen payment upgrade don't work

### ISSUE THREAD

**Issue by xandedf** [Adyen/adyen-magento2#699]
Running the composer upgrade command (composer require adyen / module-payment) the module version to 6.0.0, the process is not completed and displays the message below ...

   Problem 1
     - Installation request for adyen / module-payment ^ 6.0 -> satisfiable by adyen / module-payment [6.0.0].
     - Conclusion: remove adyen / php-api-library 4.2.0
     - Conclusion: don't install adyen / php-api-library 4.2.0
     - adyen / module-payment 6.0.0 requires adyen / php-api-library ~ 6 -> satisfiable by adyen / php-api-library [6.0.0, 6.0.1, 6.1.0].
     - Can only install one of: adyen / php-api-library [6.0.0, 4.2.0].
     - Can only install one of: adyen / php-api-library [6.0.1, 4.2.0].
     - Can only install one of: adyen / php-api-library [6.1.0, 4.2.0].
     - Installation request for adyen / php-api-library (locked at 4.2.0) -> satisfiable by adyen / php-api-library [4.2.0].

**Comment by acampos1916** [comment]
Hey @xandedf,

You can try requiring the package including it's dependencies so the PHP API Library also gets an update:

`composer require adyen/module-payment --update-with-dependencies`

I'm closing this issue now but feel free to reopen it if you keep experiencing problems with the composer installation.
