### ISSUE TITLE
Not able to see the HPP iDEAL option in admin panel

### ISSUE THREAD

**Issue by yogendrabmishra** [Adyen/adyen-magento2#70]
Hi Team,

First of all thanks for fantastic plugin. I have installed the extension on my Magento2 EE and I can able to see the all payment option except HPP iDEAL and that's the option I have to work on. Could you please advise what I have missing so I can fix it.

Groet,
Yogi

**Comment by rikterbeek** [comment]
Hi @yogendrabmishra,

Thanks appreciate it! This will be visible if you are selecting "Netherlands" as country in shipping address of the checkout.

Regards,
Rik
Adyen
