### ISSUE TITLE
Error when I cancel paypal payment

### ISSUE THREAD

**Issue by ptraing** [Adyen/adyen-magento2#701]
**Magento version**: 2.3.4
**Plugin version**: 6.0.0
**Description**
- Add product in cart
- Go to shipping
- Go to payment
- Choose paypal payment
- Click on "cancel" for go to back  website

**Expected** : Back to website

**Undesired result** : 

`1 exception(s):
Exception #0 (Exception): Notice: Undefined index: storeId in /var/www/magento/vendor/adyen/module-payment/Gateway/Http/Client/TransactionCancel.php on line 57

Exception #0 (Exception): Notice: Undefined index: storeId in /var/www/magento/vendor/adyen/module-payment/Gateway/Http/Client/TransactionCancel.php on line 57
<pre>#1 Adyen\Payment\Gateway\Http\Client\TransactionCancel->placeRequest() called at [vendor/magento/module-payment/Gateway/Command/GatewayCommand.php:106]
#2 Magento\Payment\Gateway\Command\GatewayCommand->execute() called at [vendor/magento/module-payment/Model/Method/Adapter.php:547]
#3 Magento\Payment\Model\Method\Adapter->executeCommand() called at [vendor/magento/module-payment/Model/Method/Adapter.php:486]
#4 Magento\Payment\Model\Method\Adapter->cancel() called at [vendor/magento/module-sales/Model/Order/Payment.php:1150]
#5 Magento\Sales\Model\Order\Payment->_void() called at [vendor/magento/module-sales/Model/Order/Payment.php:880]
#6 Magento\Sales\Model\Order\Payment->cancel() called at [vendor/magento/module-sales/Model/Order.php:1240]
#7 Magento\Sales\Model\Order->cancel() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#8 Magento\Sales\Model\Order\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#9 Magento\Sales\Model\Order\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/module-sales-rule/Plugin/CouponUsagesDecrement.php:42]
#10 Magento\SalesRule\Plugin\CouponUsagesDecrement->aroundCancel() called at [vendor/magento/framework/Interception/Interceptor.php:135]
#11 Magento\Sales\Model\Order\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#12 Magento\Sales\Model\Order\Interceptor->___callPlugins() called at [generated/code/Magento/Sales/Model/Order/Interceptor.php:78]
#13 Magento\Sales\Model\Order\Interceptor->cancel() called at [vendor/adyen/module-payment/Helper/Data.php:803]
#14 Adyen\Payment\Helper\Data->cancelOrder() called at [vendor/adyen/module-payment/Controller/Process/Result.php:133]
#15 Adyen\Payment\Controller\Process\Result->_cancel() called at [vendor/adyen/module-payment/Controller/Process/Result.php:110]
#16 Adyen\Payment\Controller\Process\Result->execute() called at [vendor/magento/framework/App/Action/Action.php:108]
#17 Magento\Framework\App\Action\Action->dispatch() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#18 Adyen\Payment\Controller\Process\Result\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#19 Adyen\Payment\Controller\Process\Result\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/module-customer-segment/Model/App/Action/ContextPlugin.php:81]
#20 Magento\CustomerSegment\Model\App\Action\ContextPlugin->aroundDispatch() called at [vendor/magento/framework/Interception/Interceptor.php:135]
#21 Adyen\Payment\Controller\Process\Result\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#22 Adyen\Payment\Controller\Process\Result\Interceptor->___callPlugins() called at [generated/code/Adyen/Payment/Controller/Process/Result/Interceptor.php:26]
#23 Adyen\Payment\Controller\Process\Result\Interceptor->dispatch() called at [vendor/magento/framework/App/FrontController.php:159]
#24 Magento\Framework\App\FrontController->processRequest() called at [vendor/magento/framework/App/FrontController.php:98]
#25 Magento\Framework\App\FrontController->dispatch() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#26 Magento\Framework\App\FrontController\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#27 Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/module-store/App/FrontController/Plugin/RequestPreprocessor.php:99]
#28 Magento\Store\App\FrontController\Plugin\RequestPreprocessor->aroundDispatch() called at [vendor/magento/framework/Interception/Interceptor.php:135]
#29 Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/module-page-cache/Model/App/FrontController/BuiltinPlugin.php:69]
#30 Magento\PageCache\Model\App\FrontController\BuiltinPlugin->aroundDispatch() called at [vendor/magento/framework/Interception/Interceptor.php:135]
#31 Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#32 Magento\Framework\App\FrontController\Interceptor->___callPlugins() called at [generated/code/Magento/Framework/App/FrontController/Interceptor.php:26]
#33 Magento\Framework\App\FrontController\Interceptor->dispatch() called at [vendor/magento/framework/App/Http.php:116]
#34 Magento\Framework\App\Http->launch() called at [vendor/magento/framework/App/Bootstrap.php:261]
#35 Magento\Framework\App\Bootstrap->run() called at [pub/index.php:40]
</pre>`

**Return URL** : https://localhost/fr_eu/adyen/process/result?payload=Ab02b4c0%21BQABAgCHS%2BboaHd6TRCIZ1CFmnt7rgwbpBb%2BaPJIDf838aDSLzjvwHY54II%2BsYASvWNsbeneAK81WLAy3KBJyzf7OdBNeJ58aDD%2BNm5snJlod8Zx%2BIvA9Siu3RDxyPr1tQ2EXVTbhXmUkUfn%2BW4%2B6kcmWykx0N6FkoM%2FK7WRBLVfg1%2FjA%2BK3gL8kk%2BsieDK22V%2FuhZu3RWribCzn0S%2B4XuoRRhf%2FWRjWsK%2F1G6IBAP8JCbQp88f104kCVwrvjz6Iq0wi6Cz7XVT5Is3pEVOJ89yiZEpmDK%2F1m4Zd%2BqTK%2F%2FJ7UOnuflWBKLZWmJcbZMc6JHpMe0ZRAvUoYAz5CMWZExjScjXorycshwxVtEPb5W9t2tt5PgDYm8LMmcXC8HWi3rQCIROKSit4tYBPrkIzj%2FSOsg2G6D0UEeYBpU0phkPPERkOVlx5b5wErIkdo2Rj5BoCHkY%2FyZxG1iLeNdsxG0Y5nYMp6risBnBNMEVdJhShkvPhG1b5MPR2FTuRCjCstnoydxYCMV4fSPtx3x%2FwWcL5eTR38Ww60G%2FnX8EECTwxpGDmgnGG4kHhbm07I02%2FvcgIy9MRffaJ48WLUv39kC9Fu9e8q3yq%2BwU7Tqb5HhRUBbwN93sNyjW7E4%2BCmY85GzePbRJcyUHSuB7uE21Y8ZeF03588qp3Oet8F6THTKT6e8jbQBAzKjIxJzjGYREASzgg6N7DAEp7ImtleSI6IkFGMEFBQTEwM0NBNTM3RUFFRDg3QzI0REQ1MzkwOUI4MEE3OEE5MjNFMzgyM0Q2OERBQ0M5NEI5RkY4MzA1REMifT5smOxvtvtBHmLWs4PR0YdJyqkYlJopf80VsXRM46sAaiIKEzbv8tGAiUyGKiQR9CKq8qsovwcdg8LSm6%2FE5i9XZJbYCOA06ZGmhV8%2BpyYBBIA8X71Ok3gL1QiSc5l0k9yjb1RL843OECKPRUg04YAqqMib7bdU2grN10h28oRwFMhR%2BKW1RJ5kHkywpU2u8K5IhI2mxDKHZ3ZYM9VNgpIp4VmAsSSOTYZv54q77BKbC9Ckt%2BT9TSqScBjtkQ65%2FNosy7Ovxt7eW6gSkVs%3D&type=complete&resultCode=cancelled

**Comment by cyattilakiss** [comment]
Hi @ptraing ,

Thank you for opening this issue, we are going to look into it and try to reproduce it.

Best,
Attila
Adyen

**Comment by msilvagarcia** [comment]
Hey @ptraing ,

I couldn't reproduce the issue with the Magento 2 and plugin versions mentioned.

Some steps that we recommend our clients to use when facing issues we cannot reproduce are the following:
- Disable other plugins. Some plugins interact badly with each other. Knowing which one does and why could help us provide a more stable environment for our users.
- Check templates. Maybe a variable is missing from the payment form or trying to read something after the shopper is redirected.
- Provide us more information. Our test might be too narrow, maybe there's some setting you use that we don't. I see there's a `storeId` in the stack trace, are you using a multi-store setup? Can you think of something else we might check to reproduce your issue?

Hope to hear back from you.
Cheers!
Marcos
Adyen

**Comment by ptraing** [comment]
Hi @msilvagarcia ,

Thank you for your answer. 
I'll test and let you know.

I do use a multi-store.

Best regards,

**Comment by AlexandrosMor** [comment]
Hello @ptraing,

Did you had some time to test it ?

kind regards,
Alexandros

**Comment by ptraing** [comment]
Hi ,
Sorry for the delay.
I think it’s from a third party module. So I close thé ticket.
Thank for your help. 

Best regards
