### ISSUE TITLE
Bancontact(BCMC) is not working if used as an alternative payment method, it only works in the Credit Card method - fix is available in 5.2.0

### ISSUE THREAD

**Issue by melnickforever** [Adyen/adyen-magento2#702]
**Describe the bug**
Bankcontact method is not present in the alternative payment method section in BO and not present as separate payment method in frontend in version 6.0.0 (should be fixed in 5.2.0)

**To Reproduce**
1. Go to the 2 step checkout page.

**Expected behavior**
Bank contact presents as separate payment method in checkout.

**Screenshots**

**Desktop (please complete the following information):**
 
 - Version 6.0.0

**Comment by acampos1916** [comment]
Hello @melnickforever,

Thanks for opening this issue. BCMC is not available as a separate payment section as it is an unsupported alternative payment method at Adyen.

Let me know if you have further questions,
Ángel Campos

**Comment by cyattilakiss** [comment]
Hi @melnickforever,

Just to add some additional info to this issue let me explain it a bit further.
In the current implementation we handle the BCMC in the card component that is the reason why it has been removed as a separate redirect payment method. To have a better user experience in the checkout I recommend you to modify the title of the card payments in your plugin's admin page to something like 'Card and BCMC payment' just to be sure that the user will be able to perform the payment.

We are still investigating if we should show BCMC as a separate payment method (the same way as we currently do with the card payments using the card component). Your input is very much appreciated so please let us know what would you prefer.

Best,
Attila
Adyen

**Comment by melnickforever** [comment]
Thanks for the response. our client needs to have a  separate method.
Will be good to have this in future releases.
