### ISSUE TITLE
[PW-2379] Exporting/Dumping keys to env.php

### ISSUE THREAD

**Issue by bash247** [Adyen/adyen-magento2#703]
**Describe the bug**

Magento version: 2.3.4
Plugin version: 6.0.0

Description
We have multiple environments (dev, stage and live) configured for our magento instance. I noticed that the Adyen module currently dumps the API keys in config.php. When these keys are moved to env.php and removed from config.php, the Adyen module believes there are no keys, and it won't let us use the payment gateway. Currently to work around this, we're having to remove the keys from config and add them via the admin area within Magento.

**Expected behavior**
Dumping config, splits the sensitive information to `env.php`

**Desktop (please complete the following information):**
 - OS: Ubuntu 16.04
 - Browser: Firefox
 - Version: 75

**Additional context**

This could be helpful - devdocs.magento.com/guides/v2.3/extension-dev-guide/configuration/sensitive-and-environment-settings.html

**Comment by acampos1916** [comment]
Hello @bash247,

Thank you for this feedback, some configuration values should be tagged as sensitive like you mention. We will address this and keep you posted.

Best,
Ángel Campos

**Comment by acampos1916** [comment]
Hi @bash247,

This recommendation has been implemented and merged, thanks again!

Ángel Campos
