### ISSUE TITLE
Boleto lastname sent incorrectly

### ISSUE THREAD

**Issue by alexzt** [Adyen/adyen-magento2#714]
**Describe the bug**
Instead of sending to Boleto the lastname enterend in the payment area of the M2 checkout, the customer lastname is sent. 

**To Reproduce**
1. Add product to cart.
2. Go to checkout (select valid shipping, billing address, shipping method)
3. Select Adyen Boleto Payment Method
4. Enter Social Security Number, FirstName, Lastname (choose a firstname and lastname different than the customer firstname and lastname).
5. Place order.
6. Download Boleto PDF 

**Expected behavior**
The lastname from boleto pdf to be the same with the lastname entered in the boleto payment method.

**Additional context**
Module version:
 "name": "adyen/module-payment",
  "description": "Official Magento2 Plugin to connect to Payment Service Provider Adyen.",
  "type": "magento2-module",
  "version": "6.0.0",
  "license": [
    "OSL-3.0",
    "AFL-3.0"
  ],

The request in checkout:

rest/V1/carts/mine/payment-information

will generate a request with payment method info for boleto:

`"paymentMethod":{"additional_data":{"firstname":"Test","lastname":"Name","social_security_number":"16092013886"},"extension_attributes":{"agreement_ids":[]},"method":"adyen_boleto"}`

which will be saved in additional_information on quote:

vendor/adyen/module-payment/Observer/AdyenBoletoDataAssignObserver.php

const SOCIAL_SECURITY_NUMBER = 'social_security_number';
const BOLETO_TYPE = 'boleto_type';
const FIRSTNAME = 'firstname';
const LASTNAME = 'lastname';

foreach ($this->additionalInformationList as $additionalInformationKey) {
   if (isset($additionalData[$additionalInformationKey])) {
      $paymentInfo->setAdditionalInformation(
          $additionalInformationKey,
          $additionalData[$additionalInformationKey]
      );
    }
}

But when retrieving that information from the quote in

vendor/adyen/module-payment/Gateway/Request/CheckoutDataBuilder.php

for lastname, the lastName key is checked instead of lastname, which isn't found, and will be populated with customer lastname instead.

        if ($payment->getAdditionalInformation("firstname")) {
            $requestBody['shopperName']['firstName'] = $payment->getAdditionalInformation("firstname");
        }

        if ($payment->getAdditionalInformation("lastName")) {
            $requestBody['shopperName']['lastName'] = $payment->getAdditionalInformation("lastName");
        }

**Comment by acampos1916** [comment]
Hello @alexzt,

Thank you for this detailed report. We'll attempt to verify it and keep you posted.

Regards,
Ángel Campos

**Comment by acampos1916** [comment]
Hey @alexzt,

The fix for this issue has been merged now.

Cheers,
Ángel Campos

**Comment by alexzt** [comment]
Hi @acampos1916,

Thanks for the heads up!

Would it be available in the next release? When will that be out?

Thanks,
Alexandra

**Comment by acampos1916** [comment]
@alexzt,

The next release will be in about 2 weeks. Feel free to apply this fix as a patch in the meantime.

Ángel Campos

**Comment by cyattilakiss** [comment]
Hi @alexzt,

6.1.1 version has just been released. Let me know if you still face issues regarding this ticket.

Best,
Attila
Adyen
