### ISSUE TITLE
[PW-2475]: Adyen Klarna "invoice on shipment" does not capture funds

### ISSUE THREAD

**Issue by MikeParkin** [Adyen/adyen-magento2#726]
**Describe the bug**
When the config option for "payment/adyen_abstract/capture_on_shipment" is enabled, the user would expect that an order is both invoiced in Magento and the payment is captured in Adyen when creating a shipment. 

**To Reproduce**
1. Enable payment/adyen_abstract/capture_on_shipment
2. Create a Klarna purchase
3. Ship the order (without invoicing first)

**Expected behavior**
A shipment and invoice should be generated, with the payment captured in Adyen.

**Actual result**
The shipment and invoice are created, but the funds are not captured.

**Cause**
The invoice object needs to be told to capture (this flag is set when invoicing the order in the admin panel by Magento, but it is not set in your observer). 

Additionally, the error message can never be seen because there is a missing % in the pattern.

```
diff --git a/Observer/Adminhtml/BeforeShipmentObserver.php b/Observer/Adminhtml/BeforeShipmentObserver.php
index aa86468..1957a10 100755
--- a/Observer/Adminhtml/BeforeShipmentObserver.php
+++ b/Observer/Adminhtml/BeforeShipmentObserver.php
@@ -26,6 +26,7 @@ namespace Adyen\Payment\Observer\Adminhtml;
 
 use Magento\Framework\Event\Observer;
 use Magento\Payment\Observer\AbstractDataAssignObserver;
+use Magento\Sales\Model\Order\Invoice;
 
 /**
  * Class DataAssignObserver
@@ -71,10 +72,11 @@ class BeforeShipmentObserver extends AbstractDataAssignObserver
                         // set transaction id so you can do a online refund from credit memo
                         $pspReference = $order->getPayment()->getAdyenPspReference();
                         $invoice->setTransactionId($pspReference);
+                        $invoice->setRequestedCaptureCase(Invoice::CAPTURE_ONLINE);
                         $invoice->register()->pay();
                         $invoice->save();
                     } catch (\Exception $e) {
-                        throw new \Exception(sprintf('Error saving invoice. The error message is:', $e->getMessage()));
+                        throw new \Exception(sprintf('Error saving invoice. The error message is: %s', $e->getMessage()));
                     }
                 }
             }
```

Furthermore, you have only added the observer to the Adminhtml namespace, this means that any cron jobs that run that create a shipment (for example, automatically importing shipments from an ERP) never create the invoice or capture the payment.

This can be added like this: 

```
diff --git a/etc/crontab/events.xml b/etc/crontab/events.xml
new file mode 100644
index 0000000..41f8113
--- /dev/null
+++ b/etc/crontab/events.xml
@@ -0,0 +1,5 @@
+<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:Event/etc/events.xsd">
+    <event name="sales_order_shipment_save_before">
+        <observer name="adyen_shipment_save_before" instance="Adyen\Payment\Observer\Adminhtml\BeforeShipmentObserver" />
+    </event>
+</config>
```

**Comment by acampos1916** [comment]
Hello @MikeParkin,

Thank you for this feedback and suggestions. We've opened an internal ticket to look at it in detail. You'll be updated about it soon.

Ángel Campos
