### ISSUE TITLE
Boleto PDF link is empty in customer account order details

### ISSUE THREAD

**Issue by jdunand13** [Adyen/adyen-magento2#727]
**Describe the bug**
After ordering using the Boleto payment method, you can access the details of the order in the customer account. On this page, you have the possibility to print the PDF of your Boleto, but unfortunately, the link is empty.

It seems the way the link is retrieved in the following file: adyen-magento2-develop/view/frontend/templates/info/adyen_boleto.phtml is incorrect and results in an empty string. Apparently this link should be retrieved from additionalInformation['action']['downloadUrl'] rather than just additionalInformation['url'].

**To Reproduce**
1. Create a Boleto order
2. Access order details in customer account
3. Click on [Click here to download Boleto PDF.]
4. PDF is not displayed, instead the page is refreshed because the link is empty

**Expected behavior**
Boleto PDF should be displayed

**Desktop (please complete the following information):**
 - OS: macOS
 - Firefox / Chrome
 - Latest

**Comment by acampos1916** [comment]
Hello @jdunand13,

Thank you for reporting this bug, we've opened a PR to fix this. #728 

Ángel Campos

**Comment by cyattilakiss** [comment]
Hi @jdunand13,

6.1.1 version has just been released. Let me know if you still face issues regarding this ticket.

Best,
Attila
Adyen
