### ISSUE TITLE
Card encryption failed..

### ISSUE THREAD

**Issue by kamal250** [Adyen/adyen-magento2#73]
I have enabled "CreditCard API integration" and already configured the Magento 2 extension. During payment process, I am getting following error message in console.
`{"message":"Card encryption failed"}`

Here is the parameters posted in request:
`{"cartId":"3","paymentMethod":{"method":"adyen_cc","additional_data":{"cc_type":"VI","encrypted_data"
:"adyenjs_0_1_16$g7cxP/kxSip2kHPqr8/xj4NKl1DUJtwvJ1mCvbNH4+yQL1VsnaB5phxlVFmThDlzYWirVp6C8D4die/NfJDs7Jyj75tLUtpNaAickYhJTNJBxsVqU4ZPbhfJO
+bqXQAzY9hqMOiiZfqKbYmYLp+vz2d9TseCA73/VBFmKmfdWbktjQxBcX/U5YqMIQGliXqT8k9YAP6bUDz8Z6xvkj/Dvh2/u0e0iFHkjfHQlONS1TD0k63wDDXnRHsq82UljoB89wTPoBaKDErilcFbhlpoDyQHawlTE
/f7W0xRiwePJdcTVnGMX8quoCUfYRbL/+7TAdPdkFgb1ZngR9H8Y2RKgQ==$JcmVNWuXcuV5fK+EIsgZygQDjzTpGmDhi6wNEgqSJcnss5kgWzCYJAusvVtFCQkJJWTzyNBAV6oFS9385zMVPZTq4F7SaD9yagHSAgVT
+CGG9/VNvUcYrO/fiDahSTalqBTw+IywV4fdIB+R0CLhp/pH5MR9+QCSuuWDmjaFkvOP9ANqOr/KCPL0gTOGyYTPqOW2axabzDdxhsx3kbCx
+MX290ZlmIvYUPizRBPWl7zPV+rIjAn0R6SVSsjHZ18VKvpXuRxZ84KPXSZM9thv8g/U6qNlA1J9o6pvRcZf3QBoia+wP8BHBZiysLHEjiwbDcsmtrtaln
+DI+Mpghyxc7JBc4UxBGhHddZZfO9m2ylw0ENwLColJCxjVmMrAGPqwgqz0F0DusOjo0ZPFFCZq8x2bZDCJ75X6sBG45Ajbw27QV9JODpuuUf0wzpsqFw8
+lMY0QBVzJ9qX9gKeNoVvFZPShujgJBZMJ6VaGNhyA0tdXvFgf5QjVLtLRFzimTYbeVoALjtgTPr1okeN2dc0rbPNuuPtMXnzQJOI6fNW7s0ORrKc1fL9nHiQdQ
=","store_cc":true}},"billingAddress":{"countryId":"US","regionId":"56","regionCode":"TN","region":"Tennessee"
,"street":["10510 Fireweek Ln."],"company":"","telephone":"7845986512","postcode":"38017","city":"Collierville"
,"firstname":"David","lastname":"Johnson","save_in_address_book":true,"saveInAddressBook":false}}`

I did check the code in vendor directory and noticed that following code under adyen/module-payment/Model/Method/Cc.php is responsible for error:

`if (isset($additionalData['encrypted_data'])) {
                $infoInstance->setAdditionalInformation('encrypted_data', $additionalData['encrypted_data']);
            } else {
                throw new \Magento\Framework\Exception\LocalizedException(__('Card encryption failed'));
            }`

But strange thing is I do have "encrypted_data" in post parameters. Please suggest.

**Comment by rikterbeek** [comment]
Hi @kamal250,

That is very strange. In our develop branch we have switched to the new payment method structure.
For now can you debug the assignData() method to check if the cse_key is in the $data variable maybe something goes wrong in the conversion to DataObject or switch to the develop branch and check if that solves the issue.

Regards,
Rik
Adyen

**Comment by rikterbeek** [comment]
Hi @kamal250,

Did you saw my response and is your issue now resolved ?

Regards,
Rik
Adyen

**Comment by kamal250** [comment]
Hi @rikterbeek,

I have forked repo and added log in assignedData method. I will test it out and will inform you.

Thanks,
Kamal

**Comment by kamal250** [comment]
Hi @rikterbeek,

Here is the log info:

`Magento\Framework\DataObject::__set_state(array(
   '_data' => 
  array (
    'method' => 'adyen_cc',
    'checks' => 
    array (
      0 => 'checkout',
      1 => 'country',
      2 => 'currency',
      3 => 'total',
    ),
    'cc_type' => 'VI',
    'encrypted_data' => 'adyenjs_0_1_16$Qf37LT9wl+68dg+KSCm/OGrEIx4LizvuC15gmrS3RcrwUd3m4iSuUwunXNn34CH9nuUzlH9
/d/ro9jiufroP8qnN9nxL1yeCJnHoq/mdoGW9gbLGz3I7uJrgQbw0XcwXcFtl19woH2mD09SWUD4SiuD7fVSNCOqaQ+R3WlXknHL12Mjlb4qMYFsf7P7m5LL
+rhX6Q+OL1CRvkOBjM6qGzbp9B1L3TZxYttKMLT9GymmeKF2ztfSgASyYS9huCFrthlZIKi467MXcqNwBLTC76Eg+IJ0pqK89wy6tLLpf0OSP
+Cq/2PlKmLb1BJJrgwRlFubbgs4/1hJsIrKmanTo2Q==$fbQZjvCOB0bcySi5LSNlyMx1v3pf25w2DGcLWib+3pz7ps9GtGA/xE5
/MsoxGqVCP74RhZiVg0vBO4GaV56fHT/CfVxu1EDkReAJevWQUMJyMJHVF6jwOfTE2lk4xdpz4kJDM1glMlSz2AHDcZcaLBYMsRl9gWww
+Zf73+H2ORwV2k3nLctR1B62JdyyynHuLQvGNGuYjgYbGawmFfe0V3dFy+7lfHiHSSBOJ6MlPc+9tINjE/dBXifFV01mSi6sEkD755W3Ij2KzV1zehKJbvcD4fCcAQxvIYAVqphpDAfKljxJygCicm
/X78lyP/vZ6RePA3g2iLHXC7MNB7Cc3sbPu6m9lC1TjqKpIY2EeRCs+ZCFnPxMTN2+UodHRvOT',
    'store_cc' => '1',
  ),
))`

That's the output of $data but when I debug $additionalData, it is having NULL value.

It seems like develop branch is having no Cc.php method. Can you please guide me what changes do I need to make in order to checkout develop branch?

I am having following entry in composer.json.
`"require": {
        ----
        "adyen/module-payment": "^1.4",
        ----
    },`

Thanks,
Kamal

**Comment by rikterbeek** [comment]
Hi @kamal250,

The develop branch works in a new way that is introduced by magento. So we do not have a method\Cc.php anymore this is covered on a different approach using the Facade pattern.
You need to point to the develop branch instead of an actual release.

Regards,
Rik
Adyen
