### ISSUE TITLE
[PW-2546] Ability to retrieve storedPaymentMethods

### ISSUE THREAD

**Issue by rvitaliy** [Adyen/adyen-magento2#731]
**Is your feature request related to a problem? Please describe.**
We store payment methods of customers in adyan to be able reuse this information.
We enable this fields as documented here: https://docs.adyen.com/plugins/magento-2/set-up-adyen-customer-area#step-5-set-up-billing-agreements
but when we go to call https://github.com/Adyen/adyen-magento2/blob/34cfc4a6deea40c6d25b0e8100632b4b363fb8d0/etc/webapi.xml#L38 we retrieve only paymentMethods because php code skip other fields.

**Describe the solution you'd like**
solution 1: add a new magento api to retrieve storedPaymentMethods

solution 2: https://github.com/Adyen/adyen-magento2/blob/34cfc4a6deea40c6d25b0e8100632b4b363fb8d0/etc/webapi.xml#L38 return paymentMethods & storedPaymentMethods

**Describe alternatives you've considered**
write a custom API to retrieve this informations, but i think it's a usefull feature for all community

**Additional context**
the call to internal adyen API alread has paymentMethods & storedPaymentMethods information

**Comment by acampos1916** [comment]
Hello @rvitaliy,

Thanks for this feedback. I've created an internal ticket to follow up on this enhancement, will let you know of any progress.

Cheers.
Ángel Campos

**Comment by rvitaliy** [comment]
this feature is really blocked for your implementation.
could you please provide us an eta?

**Comment by acampos1916** [comment]
Hello @rvitaliy,

Depending on the timeline of your integration project is possible that building it yourself is the best approach. It could take 2 months for us to address this enhancement.

If you do create a separate API endpoint for this don't hesitate to contribute it to this repo and receive our feedback.

Ángel

**Comment by eugene-shramko** [comment]
Hi @acampos1916 
Any update on the issue, is it expected to be released soon?

**Comment by floorjubbega** [comment]
Hi @eugene-shramko, 

We are going to check internally on the timeline for this. 
We will come back to you as soon as possible, 

Regards, 
Floor

**Comment by floorjubbega** [comment]
Hi @eugene-shramko, 

We estimate to implement this in the coming month. 
Let us know if you have further questions on this in the meantime, 

Regards, 
Floor
