### ISSUE TITLE
[PW-2518] Vault tokens not saved for 3DS 2 adyen_cc payments

### ISSUE THREAD

**Issue by LRotherfield** [Adyen/adyen-magento2#738]
**Describe the bug**
When checking out with a 3DS 2 enabled card using the adyen_cc payment method the recurring payment token will not be stored for the customer in vault_payment_token table.

**To Reproduce**
Checkout using adyen_cc in the test environment with a 3DS 2 enabled card (https://docs.adyen.com/development-resources/test-cards/test-card-numbers/#test-3d-secure-2-authentication) clicking the save for later checkbox.  The order places successfully but the card will not be stored.

**Expected behavior**
The token should be stored in the database as the recurring.recurringDetailReference value is sent in the adyen response data 

**Additional context**
Magento version: "magento/product-community-edition": "2.3.4-p2"
Adyen module version: "adyen/module-payment": "6.0.0"
Module settings:
payment/adyen_abstract/demo_mode: Tested with both 1 and 0 (test and production)
payment/adyen_cc_vault/active: 1
payment/adyen_cc/active: 1
payment/adyen_cc/threeds2_enabled: 1
payment/adyen_oneclick/active: 1
payment/adyen_oneclick/recurring_payment_type: ONECLICK

There seem to be only 2 methods where a vault token set on a payment and thus persisted to the database for the adyen_cc method:

1. magento/module-vault/Observer/AfterPaymentSaveObserver.php:88 which relies on adyen/module-payment/Gateway/Response/VaultDetailsHandler.php:81 setting the token.  This seems to only happen if the response code to the API authorize call in magento/module-payment/Gateway/Command/GatewayCommand.php:106 is "Authorise" rather than one of the 3DS responses of RedirectShopper or IdentifyShopper
2. adyen/module-payment/Controller/Process/Redirect.php:212 which relies on the request method being POST and the keys 3dActive and 3dSuccess being true on the payment.  These conditions only seem to be satisfied by the RedirectShopper flow which according to https://docs.adyen.com/classic-integration/3d-secure/native-3ds2/authentication-only-integration sounds like it only happens for 3DS 1 requests

In all of my testing I have not managed to save a 3DS 2 enabled card vault token.  This makes sense, given the above I cannot see how a response code of "IdentifyShopper" to an authorise request will ever hit a point in the code where it will save a token? This can be replicated in the test environment using any of the 3DS 2 cards

We are also seeing this in our live environment where 3DS 1 requests (RedirectShopper) and non 3DS requests(Authorised) with enableRecurring set to true are successfully saving tokens but no 3DS 2(IdentifyShopper) requests are.

**Comment by AlexandrosMor** [comment]
Hello @LRotherfield 

We created an internal ticket for this issue. We are going to pick it up soon. 

regards,
Alexandros

**Comment by LRotherfield** [comment]
Hey @AlexandrosMor 

Could you give us an update of this issue please?

Kind Regards
Luke

**Comment by floorjubbega** [comment]
Hi @LRotherfield this was solved by #814
