### ISSUE TITLE
Swish payments not working

### ISSUE THREAD

**Issue by tieroom** [Adyen/adyen-magento2#741]
**Describe the bug**
When choosing Swish as payment method and then clicking "place order", an error message is presented to the user: "_Error with payment method please select different payment method_"

**Expected behavior**
I expect the customer to be forwarded to the Adyen hosted Swish confirmation page.

**Screenshots**
https://www.dropbox.com/s/0vu771348jh2nfy/Sk%C3%A4rmklipp%202020-06-15%2016.58.41.png?dl=0

**Enironment:**
 - Magento 2.3.4-p2
 - Adyen extension 6.1.0
 - Checkout extension Firecheckout 1.23.0
 
**Additional context**
Looks like this has been broken since we upgrade to 6.1.0 a couple of weeks back. Log output available on request.

**Comment by gabwik** [comment]
@tieroom we got the same issue but on Magento 2.3.1 and the same Adyen version.

**Comment by acampos1916** [comment]
Hello @tieroom @gabwik,

Thanks for this feedback. A recent change to Adyen Checkout API made Swish not available in this plugin. We're already working on a new approach that solves this issue and we'll link a PR here when ready.

Ángel Campos

**Comment by gabwik** [comment]
@acampos1916 any idea when you could publish the fix or just send the code that need to be changed?

**Comment by acampos1916** [comment]
@gabwik it could take 1.5 or 2 months for the release containing this new approach to be published. Unfortunately at the moment there is not a single patch I could point you to that contains these improvements.

When the PR created we'll link this issue so you get notified.

Ángel

**Comment by AlexandrosMor** [comment]
Hello @tieroom 

Swish payment is added in this [pull request](https://github.com/Adyen/adyen-magento2/pull/770), Therefore  we can close the issue.

Kind regards,
Alexandros
