### ISSUE TITLE
[PW-2589] Enable installments for saved Credit Cards

### ISSUE THREAD

**Issue by jdunand13** [Adyen/adyen-magento2#742]
**Is your feature request related to a problem? Please describe.**
Currently, when customers give their credit card details, they have the possibility to choose the number of installments they wish to use. It seems that if the credit card was previously stored in Magento (token), the option to choose the number of installments is not displayed to the customer.

**Describe the solution you'd like**
Ideally, when a customer selects a previously saved credit card, he should have the option to choose the number of installments, just like he can when using a new credit card. Of course, only if installments are enabled.

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by acampos1916** [comment]
Thank you for this feedback @jdunand13,

We'll follow up on this request internally and let you know.

Ángel

**Comment by tnaber** [comment]
Closing this as it has been checked and verified to work in the current version.
