### ISSUE TITLE
Add new logo vvvcadeaubon

### ISSUE THREAD

**Issue by JosienV92** [Adyen/adyen-magento2#752]
**Type of issue:** Improvement
**Problem**: Right now, the payment method VVV Giftcard has an old logo. A new logo is available already through the Adyen API.
**Proposed solution**: Add the new logo to the module as well.

**Comment by cyattilakiss** [comment]
Hi @JosienV92 ,

The new logo has been added in the commit: https://github.com/Adyen/adyen-magento2/commit/4446527d7aa4ad9c16cf4bb1fd044b7001c16618
We are going to release it as soon as possible :)

Best,
Attila
Adyen
