### ISSUE TITLE
PaymentMethod::getCurrentPaymentAmount has a wrong behavior

### ISSUE THREAD

**Issue by rvitaliy** [Adyen/adyen-magento2#756]
https://github.com/Adyen/adyen-magento2/blob/c19023412c8bee916d2e71581dd17d6c292ee5d0/Helper/PaymentMethods.php#L258

**Expected behavior**
this method must return a float or throw exception because getGrandTotal is invalid for execute a payment with adyen

**Comment by cyattilakiss** [comment]
Hi @rvitaliy ,

Thank you for raising this issue and providing a PR to fix that, we really appreciate it.
Could you please provide us a test case when this issue occurs so we can test it against the current implementation? 

Thank you in advance.
Best,
Attila
Adyen

**Comment by rvitaliy** [comment]
@cyattilakiss 
Yes sure, to test this code you must reproduce an cart with grandTotal <= 0.0.
You can try to create a product with price at 0 and add it to your cart.


I think that this code is self explanatory that something is wrong in this:
```
    /**
     * @return bool|int
     */
    protected function getCurrentPaymentAmount()
    {
        if (($grandTotal = $this->getQuote()->getGrandTotal()) > 0) {
            return $grandTotal;
        }
        return 10;
    }
```

why default return is 10?
phpdoc declare return bool|int but getGrandTotal declare return a float (it's not true magento return numeric string) in my PR i manage all possible type returned from getGrandTotal we are ready to receive int | float | string(numeric) and validate if value is > 0.0 in other case we throw exception.

**Comment by AlexandrosMor** [comment]
Hello @rvitaliy,

We merged your PR and it is going to be included in the next magento 2 release. 

kind regards,
Alexandros
