### ISSUE TITLE
ERROR on composer install Magento 2 plugin

### ISSUE THREAD

**Issue by Danustyle** [Adyen/adyen-magento2#761]
i have magento 2.2.2 version and have this error on composer install : 

$ composer require adyen/module-payment
Using version ^6.2 for adyen/module-payment
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for adyen/module-payment ^6.2 -> satisfiable by adyen/module-payment[6.2.0].
    **- adyen/module-payment 6.2.0 requires magento/framework >=101.0.8 <102 || >=102.0.1 -> no matching package found.**

this magento version is compatible ?

If I install the module (master branch) manually via ftp, the module is displayed correctly in the Magento administrator, but when I go to the cart it returns this error:

![tempsnip](https://user-images.githubusercontent.com/14804828/86796073-80ea5d80-c06e-11ea-9c3d-2c215b7008eb.png)

Is it possible to solve this error without going through the composer installation?

thx

**Comment by cyattilakiss** [comment]
Hi @Danustyle ,

Unfortunately the plugin is only compatible with version 2.2.8 or higher as described here: https://github.com/Adyen/adyen-magento2#requirements
It is recommended to update your Magento 2 instance to a newer version to benefit from the security patches Magento provides!

Best,
Attila
Adyen
