### ISSUE TITLE
Payment SEPA in Magento 2

### ISSUE THREAD

**Issue by Ame394** [Adyen/adyen-magento2#762]
Hi,

It's not a bug but our contact tell us to create a bug issue.

We would like to use Adyen payment SEPA in Magento 2. In the Back office we don't see the option to activate or desactivate this payment option.
Actually, our version of Adyen is 6.1.2.
Can you explain us how we can configure this please ?

Thanks in advance.
<img width="753" alt="Capture d’écran 2020-07-08 à 15 29 36" src="https://user-images.githubusercontent.com/62744060/86926434-5661d880-c132-11ea-9e08-6f0fdf32237d.png">

**Comment by YanP-Adyen** [comment]
Internal follow up : payment method is activated on our side but does not shows up on Magento, did I miss something ?

**Comment by acampos1916** [comment]
Hello @Ame394 @YanP-Adyen,

Thanks for opening this issue. Payment Methods not showing up in the Magento checkout even when enabled in Adyen Customer Area might be related to a currencies or available countries configuration.

If the store is correctly set up to use the right currency and the customer address uses the correct country then I would recommend to check the log files in the Magento instance to see if the parameters sent to the /paymentMethods endpoint match the configuration for SEPA in CA.

Let us know if this was indeed the problem,
Ángel Campos

**Comment by YanP-Adyen** [comment]
@acampos1916 @Ame394 
Thanks for the quick answer. By looking at the logs on our side [here](https://logsearch-test.is.adyen.com/#eyJzZWFyY2giOiJyZW1vdGVVc2VyOlwid3NAQ29tcGFueS5UZXh0aWxlc0ltcHJlc3Npb25zUHVibGljaXRlU2VydmljZVwiIEFORCBtZXRob2Q6XCJwYXltZW50TWV0aG9kc1wiIiwiZmllbGRzIjpbImFwcCIsImNsYXNzbmFtZSIsInRocmVhZGlkIiwicHNwcmVmZXJlbmNlIiwibWVzc2FnZSIsIm1zIl0sIm9mZnNldCI6MCwidGltZWZyYW1lIjoiNjA0ODAwIiwiZ3JhcGhtb2RlIjoiY291bnQiLCJ0aW1lIjp7InVzZXJfaW50ZXJ2YWwiOjB9LCJvcmRlciI6ImRlc2MiLCJzdGFtcCI6MTU5NDIxNzg4MzAyOX0=) we can see that "bankTransfer_IBAN" is present in the response of paymentMethods so the configuration seems to match the expected one.

**Comment by Ame394** [comment]
I don't understand because in the Back Office we have the good configuration.
<img width="998" alt="Capture d’écran 2020-07-08 à 17 42 46" src="https://user-images.githubusercontent.com/62744060/86940181-c8421e00-c142-11ea-8507-b94845324556.png">
<img width="982" alt="Capture d’écran 2020-07-08 à 17 43 15" src="https://user-images.githubusercontent.com/62744060/86940189-ca0be180-c142-11ea-8040-fc198187993f.png">

And in the logs we also have the "bankTransfer_IBAN" in the response of paymentMethodes
![107493232_631064217767487_1536855379190893839_n](https://user-images.githubusercontent.com/62744060/86940500-34248680-c143-11ea-8779-e7e390ae7431.png)

So, I don't understand what we need ?

**Comment by acampos1916** [comment]
@Ame394 @YanP-Adyen thanks for the info.

If the PM is present in the /paymentMethods response then indeed the problem might be something else.

I would check if there are any console errors at the moment of displaying the checkout and payments page, an error there could be stopping the script from running further.

[This is the function responsible for fetching the PMs in the frontend](https://github.com/Adyen/adyen-magento2/blob/master/view/frontend/web/js/view/payment/method-renderer/adyen-hpp-method.js#L135). Could you debug the execution of that function in your Magento instance to check if SEPA is present in the paymentMethods object?

Also, [this function is executed to display SEPA](https://github.com/Adyen/adyen-magento2/blob/master/view/frontend/web/js/view/payment/method-renderer/adyen-hpp-method.js#L384), it can also be debugged to check if it runs on when displaying the payment page.

Ángel Campos

**Comment by Ame394** [comment]
It seems ok now, we have activated the payment method Bank Transfer and when we place the order we have the screen : 
![107525962_911501199345135_3548735675840829738_n](https://user-images.githubusercontent.com/62744060/87041636-cc2d7900-c1f2-11ea-81da-6c9cd6313367.png)

**Comment by YanP-Adyen** [comment]
@Ame394 This is good news, thanks for the feedback. 
Did you make a specific action on your side ? It could be helpful to know it in case it happens again in the future.

**Comment by Ame394** [comment]
Yes, I have activated the option 'Alternative payment methods'.
<img width="810" alt="Capture d’écran 2020-07-09 à 14 50 59" src="https://user-images.githubusercontent.com/62744060/87042252-b4a2c000-c1f3-11ea-90cf-9f572cee42d4.png">

But another payment method appears in the same. It is named 'Paysafecard'. Is it configurable on your side @YanP-Adyen ?
![107592812_716875475523487_108715305077254027_n](https://user-images.githubusercontent.com/62744060/87042361-dd2aba00-c1f3-11ea-809f-435099509b18.png)

**Comment by YanP-Adyen** [comment]
@Ame394 let's close this ticket, I will answer you through email.
@acampos1916 : issue fixed, you can close this one.

**Comment by Ame394** [comment]
Thank you for your answers
