### ISSUE TITLE
[PW-2756] Risk notifications detail

### ISSUE THREAD

**Issue by YanP-Adyen** [Adyen/adyen-magento2#763]
**Is your feature request related to a problem? Please describe.**
On Magento 1 we can see few informations from the notifications (see screenshot)
![image](https://user-images.githubusercontent.com/68015043/87060411-c93e8280-c20a-11ea-9295-197bdd94b16a.png)
However we just see a few of this fields, as per this function https://github.com/Adyen/adyen-magento/blob/167bb71e15d6bf39d57c6e8bd580d15b8e1b1c59/app/code/community/Adyen/Payment/Model/ProcessNotification.php#L1520-L1526
The idea would be to have the risk details (https://docs.adyen.com/risk-management/handle-risk-rule-notifications?utm_source=bo_test) in order to let the merchant know which risk rules got triggered for an unsuccessful transaction.
 
**Describe the solution you'd like** 
Maybe let Magento 2 consumes the entire notifications ? (like a raw pretty ?)

**Describe alternatives you've considered**
Any alternatives that could help the merchant to have this information can be considered, as long as it doesn't involve looking at the logs, or anything too "techy".

**Additional context**
This feature was requested by Danone which is under Magento 1 but will switch to Magento 2 before the end of the year.

**Comment by AlexandrosMor** [comment]
Hello @YanP-Adyen,

We created an internal ticket to investigate the possibility to add this feature. 

kind regards,
Alexandros

**Comment by Suzell** [comment]
Removed as its Magento 1
