### ISSUE TITLE
Notice: Undefined index: screen_width during checkout #73

### ISSUE THREAD

**Issue by atishgoswami** [Adyen/adyen-magento2#766]
We are using Magento 2.2.11 and recently upgraded adyen/module-payment to version 6.2.0, and using the sandbox credential for testing on our QA environment using the test credit cards mentioned here:
https://docs.adyen.com/development-resources/test-cards/test-card-numbers#test-3d-secure-2-authentication

When trying to checkout using 3DS2 option enabled we are facing an issue with vendor/adyen/module-payment/Helper/Requests.php following is the error logged:

```
[2020-07-11 23:04:11] main.CRITICAL: Notice: Undefined index: screen_width in vendor/adyen/module-payment/Helper/Requests.php on line 318 {"exception":"[object] (Exception(code: 0): Notice: Undefined index: screen_width in vendor/adyen/module-payment/Helper/Requests.php on line 318 at vendor/magento/framework/App/ErrorHandler.php:61)"} []
```

**To Reproduce**
1. Enable Adyen Method
2. Enable 3D S2 option
3. Using sandbox / testing credentials 
4. Try placing an order, using the Adyen payment method with VISA card

**Expected behavior**
Order should be placed successfully

**Additional context**
Logged the value for `$additionalData` `\Adyen\Payment\Helper\Requests::buildThreeDS2Data($additionalData, $storeId, $request = [])` it seem that the addition info array does not contain the expected values

```
{"additional":{"cc_type":"visa","method_title":"Adyen CreditCard"}}
```
If i disable the 3DS2 option, order is getting placed in payment review

**Comment by AlexandrosMor** [comment]
Hello @atishgoswami,

It sounds like the plugin is not properly installed or configured. Could you please reinstall it and clear cache? Furthermore do a static deployment and easier way is to change to Developer mode: https://devdocs.magento.com/guides/v2.4/config-guide/cli/config-cli-subcommands-mode.html#change-to-developer-mode.

Testing on our end  3ds2 works properly 

kind regards,
Alexandros

**Comment by AlexandrosMor** [comment]
Furthermore I would like to ask you to send us the payment-information request as a request object when you place the order. It might be the case that the device or the browser that you are testing can not retrieve the browser info which are needed to perform 3DS2. 

Thank you in advance,
Alexandros

**Comment by atishgoswami** [comment]
@AlexandrosMor thanks for the reply, we have a complete headless setup for magento with Laravel as the storefront and the Magento APIs getting used by the Laravel application.

This might be the reason why the module might not be receiving the browser details. Can you point me the direction where this informed is gathered in the code, so that I can make the changes accordingly to suit the module data requirements

Thanks and Regards,
Atish

**Comment by timdk** [comment]
@atishgoswami try to submit these properties beside `number`, `expiryDate`, `expiryMonth` and `cvc`

```javascript
screen_width: window.screen.width,
screen_height: window.screen.height,
screen_color_depth: window.screen.colorDepth,
timezone_offset: new Date().getTimezoneOffset(),
language: window.navigator.language
```

I ran into the same issue and managed to get around it by providing these.

**Comment by atishgoswami** [comment]
Thanks @timdk will give it a try 😃

**Comment by floorjubbega** [comment]
We are closing this issue because it appears resolved, but if you have any questions/issues feel free to reopen it!

Kind regard, 
Floor
