### ISSUE TITLE
[PW-2754] Payment surcharge

### ISSUE THREAD

**Issue by david8305** [Adyen/adyen-magento2#767]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Apply a payment surcharge per payment method. Fixed and variable(%). The payment surcharge should be visible on the magento invoice.

**Describe alternatives you've considered**
Third party extensions. 

**Additional context**
No

**Comment by AlexandrosMor** [comment]
Hello @david8305,

Thank you for the suggestion. We are going to create an internal ticket and pick it up when it is possible. 

kind regards,

**Comment by AlexandrosMor** [comment]
Hello @david8305 

Surcharges on payment method is not something we want to stimulate as well following PSD2 regulations becoming more and more restrictive. Integration of surcharges is a massive integration if you want to support this generically with all the tax configurations. If you want to provide surcharges, we would strongly advise you to first look into the regulations and if allowed build custom integration for this.

regards,
Alexandros

**Comment by Suzell** [comment]
Hello, this feature should be released in the Adyen CA whereafter we'll add it to the plugin. Closing this ticket for now.
