### ISSUE TITLE
sepadirectdebit payment method not handled

### ISSUE THREAD

**Issue by paulappelbe** [Adyen/adyen-magento2#768]
Hi,
There is a problem with the **sepadirectdebit**  payments. They don't seem to be handled at all. 

It looks like getVaultPaymentToken() in magento/vendor/adyen/module-payment/Gateway/Response/VaultDetailsHandler.php doesn't handle the response.

The payment is ok in the Adyen interface, as well as in Magento, but the frontend gives an error. Which cause problems for customer on basic use, but also for recurring payments.
Thanks

**Comment by AlexandrosMor** [comment]
Hello @paulappelbe,.

We are going to test this issue and come back to you.

kind regards,
Alexandros

**Comment by paulappelbe** [comment]
Hi,
How are you testing ? One of your support team told us it was a known issue... 
The frontend gives you an error, so if you look on Adyen and in Magento's backend, it works, but the SEPA is not saved in Magento because there is an error message on the frontend.
Please tell us how you tested to see if we can get it working the same way.
Thank you.

**Comment by AlexandrosMor** [comment]
Hello @paulappelbe,

The issue was fixed in [PR 795](https://github.com/Adyen/adyen-magento2/pull/795) and was released with Adyen Payment 6.6.0. SEPA is saved properly in Magento 2. We can close the issue. 

kind regards,
Alexandros
