### ISSUE TITLE
AbstractMethod is Deprecated

### ISSUE THREAD

**Issue by sIiiS** [Adyen/adyen-magento2#77]
As I see you code, you used `AbstractMethod` in you code for example for "Hpp"
but is good you know that Magento is not use this method since 2.0.6 and will be remove completely in next release
It is good to correct your codes
See here : https://www.maxpronko.com/blog/devletter-magento-2-0-6-payment-changes

**Comment by rikterbeek** [comment]
Hi @sIiiS,

This is already be done in our develop branch. Will be in our next release of the module.

Regards,
Rik
Adyen
