### ISSUE TITLE
[PW-2464] Payment Links created in Customer Area with merchant reference interfer/interact with Magento BE

### ISSUE THREAD

**Issue by othuress** [Adyen/adyen-magento2#772]
**Describe the bug**
Payment Links created in Customer Area with merchant reference interfer/interact with Magento BE changing the order status

**To Reproduce**
Create, pay and deliver a Magento Order.
Create a credit for this order.
Create a paymentlink in CA with the order as merchant reference

**Expected behavior**
A closed order will change status from closed to Pending (Payment authorisation)

**Screenshots**
attached

**Additional context**
We just had the most strange thing ever happened with adyen paymentsolution and I think you need to look at this ASAP.
We had an order that the customer returned to us and we made a refund working as expected.
![pendingpayment_for_closed_order](https://user-images.githubusercontent.com/57142707/88176666-e9693b00-cc27-11ea-8fdb-d448f487870c.PNG)
![Payment_link](https://user-images.githubusercontent.com/57142707/88176668-ea01d180-cc27-11ea-921b-42bae949f014.PNG)

Then we sent out new goods to the customer and issued a paymentlink from adyen backend, then the order went from closed to Pending (Payment authorisation) in Magento backend!? Should not be possible or is this an expected outcome?

**Comment by acampos1916** [comment]
Hello @othuress, thank you for opening this issue.

We'll try reproducing it to verify. Just one question, in *Expected behavior* did you actually mean *Actual behavior*?

Cheers,
Ángel Campos

**Comment by othuress** [comment]
Hello @acampos1916 ,

Well both: is it expected behaviour (or bugg)? and it is actual behaviour.

Not sure if I make sense.

Cheers,
Ola

**Comment by AlexandrosMor** [comment]
Hello @othuress,

We created an internal ticket to investigate this issue and we are going to pick it up as soon as possible. 

regards,
Alexandros

**Comment by othuress** [comment]
@AlexandrosMor  okej great!

**Comment by ebaschiera** [comment]
In our stores sometimes we leverage this behaviour to restore stuck orders with failed transactions. It works very well! Don't change it! :smile:

**Comment by tnaber** [comment]
Should be fixed by PW-4159
