### ISSUE TITLE
Uncaught TypeError: Cannot read property 'name' of undefined {during checkout}

### ISSUE THREAD

**Issue by scubastore** [Adyen/adyen-magento2#776]
**Describe the bug**
Uncaught TypeError: Cannot read property 'name' of undefined console error during checkout

And different errors within the backend admin

**To Reproduce**
1. Go to test.scuba.store / login with: 
User: scub
Password : scu-ba-st-ore

Place an order and go to checkout

2. Click on checkout process
3. See error in console

**Expected behavior**
Checkout succes page

**Screenshots**
Checkout
![checkout](https://user-images.githubusercontent.com/68759965/88442727-d9af4980-ce15-11ea-81f8-102fe15da8e7.png)
Backend
![backend](https://user-images.githubusercontent.com/68759965/88442738-e895fc00-ce15-11ea-867d-7441641a334e.png)

**Comment by scubastore** [comment]
Issue is on Magento 2.2.11

**Comment by AlexandrosMor** [comment]
Hello @scubastore,

Testing the web site I have got the same result. This is not common behaviour for the plugin. Did you do any customisation ?

kind regards,
Alexandros

**Comment by scubastore** [comment]
@AlexandrosMor we haven't done any customisation. It's just the clean install. 👍

**Comment by AlexandrosMor** [comment]
@scubastore Which plugin version are you using? Can you try with the latest ?

**Comment by scubastore** [comment]
@AlexandrosMor we are using the latest one. ;-)

**Comment by AlexandrosMor** [comment]
@scubastore 
If the plugin throws an exception it should be in the Adyen folder log. Could check the logs for Adyen exceptions ? Furthermore in the screen shot we do not see any Adyen related error. 

Thank you in advance
Alexandros

**Comment by floorjubbega** [comment]
Due to the lack of activity we are closing the issue. Feel free to reopen if needed!

Kind regards, 
Floor
