### ISSUE TITLE
[PW-2871] 3DS1 in PWA

### ISSUE THREAD

**Issue by Fifciu** [Adyen/adyen-magento2#787]
**Describe the bug**
I am developing Adyen x VueStorefront integration with Magento2. With small changes in plugin I was able to succeed with 3ds2 (https://github.com/Adyen/adyen-magento2/issues/785). However, it looks like I cannot support 3DS1. When I test card with 3ds1 I am getting:
```js
// GET /adyen/orders/<order_id>/payment-status
{
  threeDS2: false,
  type: 'RedirectShopper'
}
```
How should I consume that response? In Adyen Dashboard, I have just "Open"-ed transaction. Payment is not done due to luck of 3ds1 auth.

**Expected behavior**
Support for 3DS1 Auth in PWAs

**Comment by acampos1916** [comment]
Hey @Fifciu thanks for opening this issue,

Not sure if this is a bug. Here you can find our documentation to learn what to do with the `RedirectShopper` response https://docs.adyen.com/classic-integration/3d-secure/3d-secure-1#step-1-authorise-the-3d-secure-payment

Feel free to come back with additional questions. I'll close this ticket for now.

Cheers,
Ángel

**Comment by Fifciu** [comment]
Thanks for reply @acampos1916, 

I get your point, but look at my response:
```js
{
  threeDS2: false,
  type: 'RedirectShopper'
}
```

I understand I have to *Redirect* but there is no information where I should redirect. That's the point

**Comment by danslo** [comment]
Would be nice if this could be reopened @acampos1916 , as we currently upgrading from 4.x and 6.x and run into this as well.
That is not to say that 4.x contained a way to do 3DS1 payments, but we had a custom solution that is no longer compatible.

I will spend some time to see if I can forward-port this solution, and share with you @Fifciu . But would be nice to have this natively supported.

**Comment by acampos1916** [comment]
@Fifciu I see what you mean, I reopened the ticket and will discuss it internally.

@danslo thanks for your input. Could you share a general idea of the solution you used for 4.x? That could be valuable for a native support.

**Comment by danslo** [comment]
The old code to do the actual 3DS1 process was:

```
class AdyenThreeDS1Process implements AdyenThreeDS1ProcessInterface
{
    private $cartRepository;
    private $adyenHelper;
    private $paymentTokenFactory;
    private $quoteResource;
    private $logger;
    private $lossPrevention;

    public function __construct(
        CartRepositoryInterface $cartRepository,
        Data $adyenHelper,
        PaymentTokenFactoryInterface $paymentTokenFactory,
        QuoteResource $quoteResource,
        LoggerInterface $logger,
        LossPrevention $lossPrevention
    ) {
        $this->cartRepository = $cartRepository;
        $this->adyenHelper = $adyenHelper;
        $this->paymentTokenFactory = $paymentTokenFactory;
        $this->quoteResource = $quoteResource;
        $this->logger = $logger;
        $this->lossPrevention = $lossPrevention;
    }

    public function authorise(int $cartId, string $md, string $paRes): void
    {
        try {
            /** @var Quote $cart */
            $cart = $this->cartRepository->get($cartId);
            /** @var Payment $payment */
            $payment = $cart->getPayment();
            $paymentsResponse = $payment->getAdditionalInformation('paymentsResponse');
            $storedMd = $paymentsResponse['redirect']['data']['MD'];
            if ($storedMd === $md) {
                $result = $this->authorise3d($payment, $paRes);
                $responseCode = $result['resultCode'];

                if ($responseCode == 'Authorised') {
                    $payment->setAdditionalInformation('3dActive', '');
                    $payment->setAdditionalInformation('3dSuccess', true);
                    if (isset($result['additionalData'])) {
                        $payment->setAdditionalInformation('additionalData', $result['additionalData']);
                        $payment->setCcLast4($result['additionalData']['cardSummary']);
                        if (preg_match('/^[0-9]{2}\/[0-9]{4}/', $result['additionalData']['expiryDate'])) {
                            list($month, $year) = explode('/', $result['additionalData']['expiryDate']);
                            $payment->setCcExpYear($year);
                            $payment->setCcExpMonth($month);
                        }
                        $payment->setCcType(strtoupper($result['additionalData']['paymentMethod']));
                    }
                    //Setting the pspReference on the Payment Response carries it through to the order and order export
                    $paymentsResponse['pspReference'] = $result['pspReference'];
                    $payment->setAdditionalInformation('paymentsResponse', $paymentsResponse);

                    $this->quoteResource->save($cart);
                } elseif ($responseCode === 'Refused') {
                    $this->lossPrevention->logRefusedTransaction(
                        $result['additionalData']['paymentMethod'],
                        $result['additionalData']['cardSummary'],
                        $result['additionalData']['expiryDate'],
                        $cart->getGrandTotal(),
                        $result['merchantReference'],
                        $result['resultCode'],
                        $result['refusalReason'],
                        $cart->getCustomerId()
                    );
                    $this->logger->debug('An error occurred during payment processing: transaction refused');
                    throw new Exception(
                        'There was a problem processing your card - please check your details or try a different card'
                    );
                } else {
                    throw new Exception(sprintf('3D-secure validation was unsuccessful. Response Code: %s', $responseCode));
                }
            } else {
                throw new Exception('3D-secure validation was unsuccessful');
            }
        } catch (Exception $e) {
            $this->logger->debug($e->getMessage());
            throw new LocalizedException(
                __('There was a problem processing your card - please check your details or try a different card')
            );
        }
    }

    private function authorise3d(PaymentInterface $payment, string $paRes)
    {
        $paymentsResponse = $payment->getAdditionalInformation('paymentsResponse');
        $request = [
            'paymentData' => $paymentsResponse['paymentData'],
            'details' => [
                'MD' => $paymentsResponse['redirect']['data']['MD'],
                'PaRes' => $paRes
            ]
        ];

        $client = $this->adyenHelper->initializeAdyenClient($payment->getQuote()->getStoreId());
        $service = $this->adyenHelper->createAdyenCheckoutService($client);
        $result = $service->paymentsDetails($request);

        return $result;
    }
```
Probably no longer works (unsure).

How we got the 3DS1 meta information to the frontend I am not so sure at the moment.

**Comment by danslo** [comment]
For adding RedirectData, we're currently going with:

```php
class ThreeDS1RedirectPlugin
{
    private $orderRepository;

    public function __construct(OrderRepositoryInterface $orderRepository)
    {
        $this->orderRepository = $orderRepository;
    }

    public function afterGetOrderPaymentStatus(AdyenOrderPaymentStatus $adyenOrderPaymentStatus, $response, $orderId)
    {
        if (!is_string($response)) {
            return $response;
        }

        $payment = $this->orderRepository->get($orderId)->getPayment();

        if ($payment->getMethod() === AdyenCcConfigProvider::CODE ||
            $payment->getMethod() === AdyenOneclickConfigProvider::CODE
        ) {
            $response = json_decode($response, true);

            if (($response['threeDS2'] ?? false) === false && ($response['type'] ?? '') === 'RedirectShopper') {
                $additionalInformation = $payment->getAdditionalInformation();

                $response = array_merge($response, [
                    'redirect' => [
                        'data' => [
                            'PaReq' => $additionalInformation['paRequest'] ?? null,
                            'MD' => $additionalInformation['md'] ?? null,
                            'TermUrl' => null
                        ],
                        'method' => $additionalInformation['redirectMethod'] ?? 'POST',
                        'url' => $additionalInformation['redirectUrl'] ?? null
                    ]
                ]);

                return json_encode($response);
            }
        }

        return $response;
    }
}
```

**Comment by danslo** [comment]
And here the 3DS1 code amended to work with new 6.x flows (working based on the order instead of quote). Clearly it isn't the best looking - I've just patched the bits that were needed, but it's working for us at the moment:

```php
class AdyenThreeDS1Process implements AdyenThreeDS1ProcessInterface
{
    private $adyenHelper;
    private $paymentTokenFactory;
    private $logger;
    private $orderRepository;
    private $session;

    public function __construct(
        Data $adyenHelper,
        PaymentTokenFactoryInterface $paymentTokenFactory,
        LoggerInterface $logger,
        OrderRepositoryInterface  $orderRepository,
        Session $session
    ) {
        $this->adyenHelper = $adyenHelper;
        $this->paymentTokenFactory = $paymentTokenFactory;
        $this->logger = $logger;
        $this->orderRepository = $orderRepository;
        $this->session = $session;
    }

    public function authorise(int $orderId, string $md, string $paRes): void
    {
        try {
            /** @var Order $order */
            $order = $this->orderRepository->get($orderId);

            /** @var Payment $payment */
            $payment = $order->getPayment();
            if ($payment->getAdditionalInformation('md') === $md) {
                $result = $this->authorise3d($payment, $paRes);
                $responseCode = $result['resultCode'];

                if ($responseCode == 'Authorised') {
                    $payment->setAdditionalInformation('3dActive', '');
                    $payment->setAdditionalInformation('3dSuccess', true);
                    if (isset($result['additionalData'])) {
                        $payment->setAdditionalInformation('additionalData', $result['additionalData']);
                        $payment->setCcLast4($result['additionalData']['cardSummary']);
                        if (preg_match('/^[0-9]{2}\/[0-9]{4}/', $result['additionalData']['expiryDate'])) {
                            list($month, $year) = explode('/', $result['additionalData']['expiryDate']);
                            $payment->setCcExpYear($year);
                            $payment->setCcExpMonth($month);
                        }
                        $payment->setCcType(strtoupper($result['additionalData']['paymentMethod']));
                    }
                    $payment->save();
                } elseif ($responseCode === 'Refused') {
                    $this->logger->debug('An error occurred during payment processing: transaction refused');
                    throw new Exception(
                        'There was a problem processing your card - please check your details or try a different card'
                    );
                } else {
                    throw new Exception(sprintf('3D-secure validation was unsuccessful. Response Code: %s', $responseCode));
                }
            } else {
                throw new Exception('3D-secure validation was unsuccessful');
            }
        } catch (Exception $e) {
            if (!$order->canCancel()) {
                $order->setState(\Magento\Sales\Model\Order::STATE_NEW);
            }

            $order->cancel()->save();

            // We don't actually use the session,
            // but it provides useful methods to restore the quote from a failed order.
            $this->session->restoreQuote();

            $this->logger->debug($e->getMessage());
            throw new LocalizedException(
                __('There was a problem processing your card - please check your details or try a different card')
            );
        }
    }

    private function authorise3d($payment, string $paRes)
    {
        $request = [
            'paymentData' => $payment->getAdditionalInformation('paymentData'),
            'details' => [
                'MD' => $payment->getAdditionalInformation('md'),
                'PaRes' => $paRes
            ]
        ];

        $client = $this->adyenHelper->initializeAdyenClient($payment->getOrder()->getStoreId());
        $service = $this->adyenHelper->createAdyenCheckoutService($client);
        $result = $service->paymentsDetails($request);

        return $result;
    }
```

**Comment by pablogiralt** [comment]
hi @danslo would you be able to create a PR?

**Comment by pablogiralt** [comment]
hi @acampos1916

I am also sharing our approach in the 4.x version https://github.com/jimmylion/adyen-magento2/commit/2b799e4d243d907374f337efb016be2799375790

**Comment by pablogiralt** [comment]
hi @acampos1916 would you be able to give me a rough estimate on when will this be implemented? Just wanna evaluate if we can wait for official fix or we need to implement our own

thanks

**Comment by pablogiralt** [comment]
Please @acampos1916, we really need an idea on when can this be implemented.  We even can help with PR but would like to check with you how would official solution ideally look

thanks

**Comment by pablogiralt** [comment]
ok acampos1916, I will talk it with the team and let you know our thoughts

**Comment by real34** [comment]
Hi!
We are working on this for other redirect methods (Klarna, Oney…) and got it working. I'll test it a bit more next week with 3DS and could create a PR.

**Comment by pablogiralt** [comment]
hi @real34, thanks for that.  I see the code changes to return RedirectShopper necessary data.  What about the returning back the result from the authentication? 

@acampos1916 what do you think about @real34 code for adding `action` and `additionalData` to the `payment-status` endpoint, and how `returnUrl` is generated using `getOrigin`?

**Comment by real34** [comment]
@pablogiralt this is the missing part that will have to be added indeed. For simple redirects, the return url can check the payment status and rely on the notification webhook. However for 3DS, there will be a need to add a `/payment/details` REST endpoint I think.

I haven't checked if the `/V1/adyen/threeDS2Process` endpoint documented on https://docs.adyen.com/plugins/magento-2/magento-pwa-storefront#additional-actions-3ds can be sufficient or not though.

**Comment by pablogiralt** [comment]
hi @real34 seems you have made a lot of progress with 3DS1

How far are you from creating a PR?  Let me know if we can help with testing

Also, we had scheduled working on this next week.  Is there anything we can help with?

thanks for all the work!

**Comment by real34** [comment]
Hi!

Sorry, I didn't noticed that my `push -f` triggered a notification here :joy: 

It _should_ be okay in its current state. Most success paths are working for 3DS1 and other payment methods that redirects (Klarna, Giropay, Oney…).
We are going to do some heavier testing in the next few days, and ensure that errors/cancellations can also be handled.

I'll do a PR by Monday so that it could be reviewed. I need to check if there are tests to write or documentation to update in the repository as I joyfully coded with `var_dumps` and manual tests so far!

If you could test it on your side and provide feedbacks for errors, or improve the PR that would be awesome.
Thanks!

**Comment by pablogiralt** [comment]
will do! thanks

**Comment by real34** [comment]
@pablogiralt I rebased on `develop` and opened the PR. I tried to list everything that I detected there.
It seems that #821 introduced a behavior that is not satisfying for 3DS1 support and I'd appreciate if you could provide feedback to find a satisfying solution for these url redirections to the correct storefront (Magento or external PWA such as VSF or Front-Commerce).

**Comment by pablogiralt** [comment]
@real34 awesome job! I will test this beginning next week on Vue Storefront with our [vsf-adyen module](https://github.com/jimmylion/vsf-payment-adyen/tree/develop)

@acampos1916 can you give us your thoughts on #821?  As @real34 points out, it introduces a regression for the fix added in https://github.com/Adyen/adyen-magento2/pull/786 and https://github.com/Adyen/adyen-magento2/pull/806.
This not only prevents @real34 solution for 3DS1 to work but I imagine (have not tested) that it will also prevent 3DS2 from working in PWA as it re-introduces this issue: https://github.com/Adyen/adyen-magento2/issues/785

**Comment by pablogiralt** [comment]
@acampos1916 your input would be really helpfull

**Comment by acampos1916** [comment]
Hello @pablogiralt @real34. Great work! These contributions are very much appreciated.

I've been doing some reading on this thread and related PRs, let me know if my assumptions below are correct:

#821 indeed uses the Magento URL and this would break the 3DS1 redirect for storefronts that use a different URL. I've opened the issue #826 so we can change this and test it using the `getOrigin()` function instead.

I believe #785 would be unaffected as the `buildRedirectData` function and `RedirectDataBuilder` are only necessary for 3DS1. Or am I missing something @pablogiralt? 

In general the PR looks good to me, I left a couple of comments there and I'm asking about the customer's order check.

**Comment by pablogiralt** [comment]
you are right @acampos1916, https://github.com/Adyen/adyen-magento2/issues/785 is fixed by `getOrigin` in  `buildThreeDS2Data`

Thanks for openning https://github.com/Adyen/adyen-magento2/issues/826.  Would this be something that we can expect to be handled by Adyen team soon?  If this is not possible, can we please start a discussion on what would be a satisfying solution for these url redirections to the correct storefront, which works both for magento front-end and pwa?

**Comment by acampos1916** [comment]
@pablogiralt we'll be working and testing a solution for #826 in the next few days. Implementing the getOrigin() function should enable the redirect for PWA integrations and address the regression.

**Comment by pablogiralt** [comment]
hi @acampos1916 any updates on this? thanks

**Comment by acampos1916** [comment]
Hi @pablogiralt,

Working on #826 is still in our short term roadmap but hasn’t been picked up yet unfortunately. Will notify here when this is done.

**Comment by Fifciu** [comment]
Any updates?
It is a pretty important functionallity.
