### ISSUE TITLE
[PW-3338] Unable to use open invoice payment method in pay by mail

### ISSUE THREAD

**Issue by JeroenVanLeusden** [Adyen/adyen-magento2#791]
**Describe the bug**
Unable to use open invoice payment method in pay by mail.

**To Reproduce**
1. Setup pay by mail method.
2. Setup klarna method.
3. Create order in Magento backend using pay by mail payment method.
4. Open payment link visible in order overview.
5. Choose Klarna as payment method.

**Expected behavior**
Be able to pay order using an open invoice payment method.

**Screenshots**
![Screen Shot 2020-08-14 at 11 31 51](https://user-images.githubusercontent.com/14925052/90235562-d3632a80-de21-11ea-836f-595e642edb13.png)

**Comment by JeroenVanLeusden** [comment]
Managed to get a payment through by adding openinvoicedata lines but now it gets refused because of an invalid country. After applying https://github.com/Adyen/adyen-magento2/pull/792 countryCode is present.

**Comment by floorjubbega** [comment]
Hi @JeroenVanLeusden, 

Thank you for opening this issue! We have created an internal ticket and will let you know if any progress is made.

Regards, 
Floor

**Comment by Suzell** [comment]
We have added our Adyen pay by link feature which will replace pay by mail. Open invoice payment methods are fully supported.
