### ISSUE TITLE
Chrome autofill does not populate cardholder name

### ISSUE THREAD

**Issue by astiskala** [Adyen/adyen-magento2#797]
**Describe the bug**

If you have credit card details saved into Chrome, when you click on the credit card number field Chrome will prompt you if you want to fill in the number. If you select the card, the credit card number and expiry date will be filled in, but the cardholder name will not.

Adyen's Magento 2 plugin uses Adyen Secure Fields for the card number, expiry and CVC/CVV field, but the cardholder name appears to be rendered natively in Magento 2 and does not have the necessary attributes for the autofill to work. The field currently looks like this:

`<input class="adyen-checkout__input adyen-checkout__input--text adyen-checkout__card__holderName__input sMjS8HCbKiP5yR9Td9ZgQ adyen-checkout__input--large" placeholder="J. Smith" required="" type="text">`

To enable the autofill, the attribute `autocomplete="cc-name"` should be added. See https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete

**To Reproduce**

1. Enable the Adyen card payment method in Magento
2. In Chrome to go Settings > Auto-Fill > Payment Methods and add a credit card
3. Checkout on Magento
4. Click the credit card number field
5. Select your saved card from the dropdown

**Expected behaviour**

The cardholder name will populate.

**Screenshots**

![image](https://user-images.githubusercontent.com/12061596/90750416-1b011f00-e318-11ea-94c1-c0aa1cda375b.png)

**Comment by cyattilakiss** [comment]
Hi @astiskala ,

Thank you for raising this issue. We are going to implement the holder name using the checkout component soon which will solve this issue.

Best,
Attila
Adyen

**Comment by floorjubbega** [comment]
Hi @astiskala, 

We are going to close this issue as it is going to be implemented once we update to a newer checkout version. 
Let us know if you have further questions.

Kind regards, 
Floor
