### ISSUE TITLE
Klarna order is cancelled hours after it was successfully authorized

### ISSUE THREAD

**Issue by chefbuitenhuis** [Adyen/adyen-magento2#798]
**Describe the bug**
Our client has had a Klarna order that was acknowledged only to be canceled 9 hours later. At this point, it was already synchronized with the ERP and shipped out to the customer.

**To Reproduce**
Steps to reproduce

1. Place successful Klarna order
2. Now we are unsure how to reproduce this cancellation scenario.

**Expected behavior**
Orders shouldn't be automatically be canceled after it was acknowledged, as it might already have been picked up by external processes. The client's return process should be executed.

**Screenshots**
The screenshot below outlines the flow for the faulty order.
![image (1)](https://user-images.githubusercontent.com/7578636/90775484-33ae0c80-e2f9-11ea-9d44-485e53368e22.png)

**Desktop (please complete the following information):**
Magento 2.3.5-p1
Adyen 6.1.1

**Comment by elzekool** [comment]
For who ever reads this. This is not an Adyen issue but a "feature" from Magento. By default Magento orders with the status "Pending Payment" are cancelled after 8 hours. This is controlled by the setting "sales/orders/delete_pending_after" which can be found in the Admin under "Sales" -> "Sales" -> "Orders Cron Settings" -> "Pending Payment Order Lifetime (minutes)". 

It would have been nice if the Adyen module included a warning in the configuration setting that sets the "auto capture" functionality as I think there are more merchants impacted by this.

**Comment by MarcusSchwarz** [comment]
Thank you @elzekool ! Your comment saved us a lot of work!
