### ISSUE TITLE
Install fails when using split database setup M2

### ISSUE THREAD

**Issue by stefandoorn** [Adyen/adyen-magento2#8]
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'magento.sales_order' doesn't exist, query was: DESCRIBE `sales_order`

I think it happens due to the fact that I'm using the split database options M2 EE offers (http://devdocs.magento.com/guides/v2.0/config-guide/multi-master/multi-master.html). It can't find the `sales_order` table in the default magento db, as it is in the OMS database. I can't find directly how to fix this unfortunately.

**Comment by rikterbeek** [comment]
Hi Stefan,

Where is this error thrown it looks more that this is in core magento2 instead of our module.

Regards,
Rik
Adyen

**Comment by stefandoorn** [comment]
Filed a bug at Magento, as it seems something in the core that should support this split database methods. Keep you posted.

**Comment by stefandoorn** [comment]
Apparently M2 doesn't support this in setup scripts yet. I'm reverting to the non-split database setup and M2 will add support later.

**Comment by shireenn2587** [comment]
Were you able to find out any solution for referring to the slave db in setup scripts of magento2?

**Comment by stefandoorn** [comment]
Nope.
