### ISSUE TITLE
Swish on mobile

### ISSUE THREAD

**Issue by gabwik** [Adyen/adyen-magento2#800]
**Describe the bug**
We got an issue when the user is placing the order from the mobile phone and switching between the browser and Swish. When the user switching the customer gets an error believing that the order didn't went throw but the order is going trough to Magento and the order confirmation is sent.  

**To Reproduce**
Steps to reproduce
Go to the cart using a mobile phone, selected Swish, place order go to the Swish app to confirm the order. 

**Expected behavior**
The customer is redirected to the success page after confirming the order in Swish. 

Magento 2.3.1
Adyen 6.3.0

**Comment by AlexandrosMor** [comment]
Hello  @gabwik,

Thank you for raising this issue. There is a [pr](https://github.com/Adyen/adyen-magento2/pull/793) currently about this issue which is merged. We will release it as soon as possible. 

kind regards,
Alexandros
