### ISSUE TITLE
[PW-3140] Google Pay Integration issue

### ISSUE THREAD

**Issue by jugnu247commerce** [Adyen/adyen-magento2#801]
**Describe the bug**
We upgraded Adyen Module to latest version 6.4.0
and we are facing some console error related Google Pay once we are setting as Production mode from Admin Panel of Adyen Setting.
**Uncaught Error: Unable to process binding "afterRender: function(){return renderGooglePay() }"
Message: Parameter environment in PaymentsClientOptions can optionally be set to PRODUCTION, otherwise it defaults to TEST.**

**To Reproduce**
1. Go to 'https://staging-5em2ouy-skgf53svryxle.eu-3.magentosite.cloud/checkout/#payment'
2. Right Click on page and inspect the Element and check the console error.
3. Scroll down to last in console and check the error related Google Pay.

**Expected behavior**
The Console error should not available related to Google Pay.

**Desktop (please complete the following information):**
 - Magento 2.3.5p1 Version
 - Chrome
 - Extension Version 6.4.0

**Comment by msilvagarcia** [comment]
Hey @jugnu247commerce !

We made some changes to the Google Pay component in #808 which was released in version 6.5.0. Could you check if the issue still happens?

Cheers!
Marcos
Adyen

**Comment by jugnu247commerce** [comment]
Thank You so much for your update.
I will try and let you know,

Can you please suggest, Quickly how can I upgrade to latest version through Command line interface, it will much helpful for me.



Regards,
Jugnu

**Comment by jugnu247commerce** [comment]
@msilvagarcia 
Hi as per your suggestion we updated the Module to latest version but still we are facing the same issue, (Google Pay is not available) Can you please fix this issue. As we stuck with this issue to go live.

http://99.80.184.198/finerfilters/


![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/63045192/94038268-dcadc280-fde3-11ea-9e63-3cc3783b39ee.png)
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/63045192/94038280-df101c80-fde3-11ea-8c70-1235bed59546.png)

**Comment by cyattilakiss** [comment]
Hi @jugnu247commerce ,

I see that now the payment method shows up correctly on the staging site:
![image](https://user-images.githubusercontent.com/42297201/94679329-36e8df00-0320-11eb-80b9-9efd8d57de71.png)

But not on the http://99.80.184.198/finerfilters/

During the investigation I've already found an issue which I believe is causing the issue you describe in this ticket. I will provide you a quick fix which we are testing today and release it in the next patch release.

Best,
Attila
Adyen

**Comment by cyattilakiss** [comment]
Hi @jugnu247commerce ,

The fix takes a bit longer time than expected but will happen in the next couple of days. I will keep you posted.

Thank you for your patience,
Best,
Attila
Adyen

**Comment by cyattilakiss** [comment]
Hi @jugnu247commerce ,

the fix has been released under the version 6.6.1.
I will close this issue for now but please feel free to reopen it if you still face any issue related to this.

Best,
Attila
Adyen
