### ISSUE TITLE
Request for backporting PR #614 to 4.5.x

### ISSUE THREAD

**Issue by AntonEvers** [Adyen/adyen-magento2#802]
HI @rikterbeek, I would like to request to backport https://github.com/Adyen/adyen-magento2/commit/f2d13c2576186e0a6362aa446ad3c6e970751d3b to version 4.5.x. There are a couple of customers that are using this version and seeing payment notifications that are not imported in Magento. They need a little more time to upgrade to version 6.4 but would like an intermediate solution to enable them handling their notifications that are now stuck.
Related to #603, #610 and #614

**Comment by floorjubbega** [comment]
Hi @AntonEvers, 

Apologies for the delay, could you inform us if this is still an issue for you?
In that case we will further investigate if it is possible to patch your current version.

Kind regards,

Floor

**Comment by AntonEvers** [comment]
Hi Floor,

To my knowledge, the customer I was referring to is now using version 6. However, if you are still supporting version 4.5.x then this should be considered a severe bug and clients using 4.5.x would be very happy to see the back-port.

**Comment by floorjubbega** [comment]
Hi @AntonEvers, 

After further discussing it internally we will not be able to patch previous versions, as we have released quite some patches since 4.5.x. Please let us know if you have further questions.

Kind regards, 
Floor
