### ISSUE TITLE
[PW-3027] MBWay implementation

### ISSUE THREAD

**Issue by jonathanribas** [Adyen/adyen-magento2#804]
Hello, 

We heard from our Account Manager that Adyen is now supporting MBWay (Multibanco).

As a merchant (Zadig & Voltaire), we would like to have this payment method available in your Magento 2 module. Multibanco is used quite a lot in Portugal and we want to offer it to our customers.

Thanks in advance!

**Comment by floorjubbega** [comment]
Hi Jonathan, 

Thank you for your feature request!
We are working on including this in our Magento 2 plugin, and will update you once it is available.

Kind regards, 
Floor

**Comment by jonathanribas** [comment]
Great! Thank you!

**Comment by AlexandrosMor** [comment]
Hello @jonathanribas,

The magento plugin supports Multibanco. You can set it up from the Adyen backoffice as payment method at your merchant account. It is always recommended to update to the latest version, 

kind regards,
Alexandros

**Comment by jarcorreia** [comment]
Hi, sorry for re-opening this but seems that we're talking 2 different payment methods. One is Multibanco and the other one is MbWay. Multibanco as been already implemented.

Do we have any ETA for MbWay?

**Comment by Suzell** [comment]
MBway is now included in version 7.0.0 and from 6.7 in branch 6.
