### ISSUE TITLE
[PW-3140] Google Pay Integration Bug

### ISSUE THREAD

**Issue by thangasujithas** [Adyen/adyen-magento2#805]
**Describe the bug**
We upgraded Adyen Module to latest version 6.4.0
and we are facing some console error related Google Pay once we are setting as Production mode from Admin Panel of Adyen Setting.
Uncaught Error: Unable to process binding "afterRender: function(){return renderGooglePay() }"
Message: Parameter environment in PaymentsClientOptions can optionally be set to PRODUCTION, otherwise it defaults to TEST.

**To Reproduce**

Go to the payment page of the site
Right Click on page and inspect the Element and check the console error.
Scroll down to last in console and check the error related Google Pay.
See error
**Expected behavior**
The Console error should not available related to Google Pay.

Desktop (please complete the following information):

Magento 2.3.4 Version
Browser: Chrome
Extension Version 6.4.0

**Comment by thangasujithas** [comment]
Please update the status..still we having the console error

**Comment by cyattilakiss** [comment]
Hi @thangasujithas ,

We have identified the issue and going to fix it in the next couple of days. Will reference this issue in the fix pull request as soon as it's opened.

Thank you for your patience,
Best,
Attila
Adyen

**Comment by thangasujithas** [comment]
Thank you
