### ISSUE TITLE
[PW-3140] Google Pay Integration Issue 6.5.0

### ISSUE THREAD

**Issue by lucygecko** [Adyen/adyen-magento2#810]
**Describe the bug**
We have enabled Google Pay on our live site, at the payment stage the frontend displays "Google Pay is not available".  The console logs an error `Unable to process binding "afterRender: function(){return renderGooglePay() )"`

**To Reproduce**
1. Go to the checkout payment stage
2. Click the Google Pay option

**Expected behavior**
The Google Pay button to load at the payment stage

**Screenshots**
[Frontend](https://drive.google.com/file/d/15o1kfUn-jq69sMMCCyIztQHHdrkXJtLQ/view?usp=sharing)
[Console log](https://drive.google.com/file/d/1BJfg6mKl2er-4qCzOisJHMqacJaFDNMY/view?usp=sharing)

**Desktop:**
 - Magento: 2.3.5-p1
 - Browser: chrome
 - Version: 6.5.0

**Comment by cyattilakiss** [comment]
Hi @lucygecko ,

Thank you for raising this issue.
We have identified the issue and going to fix it in the next couple of days. Will reference this issue in the fix pull request as soon as it's opened.

Thank you for your patience,
Best,
Attila
Adyen

**Comment by cyattilakiss** [comment]
Hi @lucygecko ,

the fix has been released under the version 6.6.1.
I will close this issue for now but please feel free to reopen it if you still face any issue related to this.

Best,
Attila
Adyen
