### ISSUE TITLE
Unable to complete checkout with paypal, redirected back to 2nd step

### ISSUE THREAD

**Issue by korostii** [Adyen/adyen-magento2#823]
**Describe the bug**
After upgrading to Magento 2.3.5-p2 (from 2.2.9, Magento Enterprise Cloud Edition) and updating the adyen/module-payment to version 6.5.0, we're experiencing a consistently reproducible on our, where attempting to checkout with PayPal through Adyen fails, without any visible error message; page reloads instead of redirecting to PayPal for payment.

**To Reproduce**
1. Add a product cart, proceed to 2nd step of checkout, use Adyen's PayPal payment method.
2. Click on 'Place Order'

**Expected behavior**
User is redirected to PayPal, is able to complete payment and redirected back to success page.

**Actual behavior**
User is being redirected back to the 2nd step of checkout with weird additional GET parametrs, URL looks like the following: `http://my.store.url/checkout/?form_key=XXXXXXXXXXX&payment%5Bmethod%5D=paypal&billing-address-same-as-shipping=on&agreement%5B6%5D=6&billing-address-same-as-shipping=on#payment`

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser: both Chrome and Firefox

**Additional context**
Not sure if relevant, but we also have explicit dependency on adyen/php-api-library v6.3.0 and we have installed veriteworks/cookiefix v2.4.0 in order to overcome SameSite cookie issues. Any pointers whatsoever appreciated.

**Comment by SimonPrins** [comment]
I am also experiencing this issue after upgrading to version 6.6.0 of the Adyen module. Has anyone looked into this yet?

**Comment by cyattilakiss** [comment]
Hi @korostii , @SimonPrins 

Thank you for raising this issue. We are going to try and reproduce the issue first and then investigate it further. Let me get back to you until the weekend with the results of these.

Best,
Attila
Adyen

**Comment by cyattilakiss** [comment]
Hi @korostii ,

Are you using any one page checkout module?

Best,
Attila
Adyen

**Comment by korostii** [comment]
Hi @cyattilakiss ,
No, we don't, our checkout is mostly standard out-of-the-box stuff. 
And, I think that's about all the detail I can give out publicly, but: we did also open a support ticket with Adyen, ticket ID #1592397 - we might be able to provide more detailed info in there, if requested.

**Comment by AlexandrosMor** [comment]
Hello @korostii 

I see that you opened a support ticket and it is closed at the moment. I will close also this issue. If you have more question fill free to open another github issue or contact our support.

Kind regards,
Alexandros
Adyen
