### ISSUE TITLE
[PW-3138] 3DSecure authorisation fails

### ISSUE THREAD

**Issue by florinm8** [Adyen/adyen-magento2#825]
**Describe the bug**
After selecting the credit card option and using a card with 3d secure option enabled, the redirect to success page fails. This causes the order to get canceled.
After applying the fix mentioned in https://github.com/Adyen/adyen-magento2/issues/815 the issue is reproducing randomly.

**To Reproduce**
1. Pay order with credit card with 3d secure 
2. Complete 3dSecure step
3. Page crashes

**Expected behavior**
Redirect to success page.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
1
**Additional context**
From \Adyen\Payment\Controller\Process\Redirect controller there is a call to $this->_authorise3d($order->getPayment()) that is calling the paymentDetails service which makes a curl_exec call that sometimes fails.

Before adding the http2 max_field_size config to nginx the flow was breaking before reaching 3d secure check step at this url 
https://domainname/adyen/process/redirect?MD=<huge hash>
The request was not reaching Magento at all, now the flow gets to the redirect controller and fails at paymentDetails service call.

**Comment by bmxpasw** [comment]
On Adyen 6.6 when do 3DS transaction:

`[2020-09-30 10:06:17] main.CRITICAL: Report ID: webapi-5f74589984e21; Message: Notice: Undefined index: additionalData in /var/www/html/release/vendor/adyen/module-payment/Model/AdyenThreeDS2Process.php on line 176 {"exception":"[object] (Exception(code: 0): Report ID: webapi-5f74589984e21; Message: Notice: Undefined index: additionalData in /var/www/html/release/vendor/adyen/module-payment/Model/AdyenThreeDS2Process.php on line 176 at /var/www/html/release/vendor/magento/framework/Webapi/ErrorProcessor.php:208, Exception(code: 0): Notice: Undefined index: additionalData in /var/www/html/release/vendor/adyen/module-payment/Model/AdyenThreeDS2Process.php on line 176 at /var/www/html/release/vendor/magento/framework/App/ErrorHandler.php:61)"} []
`

**Comment by cyattilakiss** [comment]
hi @bmxpasw ,

Thank you for raising this issue and providing the error message.
I see that the google pay button shows up correctly on the site:
![image](https://user-images.githubusercontent.com/42297201/94676339-7bbe4700-031b-11eb-8b64-4fdf72ffcbf4.png)

For the error message I can provide a quick fix that we are testing today and which you can immediately apply. We are going to release it in the next patch release.

Best,
Attila
Adyen

**Comment by cyattilakiss** [comment]
Hi @bmxpasw ,

I've just created the PR to fix the issue indicated in your error message.
I noticed that the additionalData is empty in case some additional fields are not set up which you could add as described here: https://github.com/Adyen/adyen-magento2/pull/833 Even if you don't want to store the payment methods (your adyen_cc vault setting is disabled) but you set these in the adyen CC this error message will be gone without applying the referenced #833 fix.

I hope this helps, let me know if you have any questions.

Best,
Attila
Adyen

**Comment by cyattilakiss** [comment]
Hi @bmxpasw ,

the fix has been released under the version 6.6.1.
I will close this issue for now but please feel free to reopen it if you still face any issue related to this.

Best,
Attila
Adyen
