### ISSUE TITLE
[PW-3111] Using Magento's base URL as 3DS1 returnUrl breaks redirect for PWA storefronts

### ISSUE THREAD

**Issue by acampos1916** [Adyen/adyen-magento2#826]
**Describe the bug**
#786 and #806 introduced an URL setting for PWA integrations to be used when the storefront's URL and Magento's base URL differ.

#821 uses `$this->urlBuilder->getUrl('adyen/process/redirect');` which does not consider the PWA URL setting, thus 3DS1 redirects fail.

**To Reproduce**
1. Use the plugin in Magento + PWA environment
2. Set a different frontend URL in PWA settings
3. Process a 3DS1 payment

**Expected behavior**
Customer is redirected to the frontend `adyen/process/redirect` endpoint so the GET response can be processed.

**Actual behavior**
Customer is redirected to the Magento `adyen/process/redirect` endpoint.

**Additional context**
Raised in #787

**Comment by fahu** [comment]
What's the progress on this one? We're facing the same issue :(

**Comment by acampos1916** [comment]
Hey @fahu,

Working on this issue is still in our short term roadmap but hasn’t been picked up yet unfortunately. Will notify here when this is done.

**Comment by TonyRutherford1** [comment]
Hi @acampos1916 Any update to this issue? Also facing the same issue

**Comment by edroberts** [comment]
@any updates on this? Over 6 months now since reported - it's not like 3DS1 has just 'disappaeared' from the internet and PWA adoption is only increasing - so unclear why there's no serious priority on this - other gateways can handle it

**Comment by acampos1916** [comment]
Hello @edroberts this has already been fixed in #988 and is being released with #1001. I'm tagging the PR so that the release closes this issue.
