### ISSUE TITLE
[PW-2753] Magento 2.4.0 Compatibility

### ISSUE THREAD

**Issue by jaycroll** [Adyen/adyen-magento2#827]
We are planning to upgrade our store from Magento Cloud version 2.3.4 to Magento 2.4.0.
On this regard, I tried installing Adyen 6.6.0 on the newest Magento 2.4.0 version, but it seems the Magento framework version (`magento/framework: 103.0.0`) is not yet supported. Is there a timeline where in we can expect a full compatibility with Magento 2.4.0?

```
  Problem 1
    - Installation request for adyen/module-payment ^6.6 -> satisfiable by adyen/module-payment[6.6.0].
    - adyen/module-payment 6.6.0 requires magento/framework >=101.0.8 <102 || >=102.0.1 -> no matching package found.
```

**Comment by cyattilakiss** [comment]
Hi @jaycroll ,

Thank you for raising this issue, we have this task in our backlog already.
We are currently working on a major release and during that we are going to test the compatibility with 2.4.* as well.
I've assigned a ticket number to this Github issue.
You can expect an update on this issue in 4 weeks.

Best,
Attila

**Comment by TonyRutherford1** [comment]
Hi @cyattilakiss Any update on this issue?

**Comment by jaycroll** [comment]
Hi @cyattilakiss any update on this?

**Comment by cyattilakiss** [comment]
Hi @jaycroll , @TonyRutherford1 

The task is in progress, we are creating the docker environment for the Magento 2.4.0 version at the moment and after that we are validating the compatibility. We plan to finish this task in a week.

Best,
Attila
Adyen

**Comment by AlexandrosMor** [comment]
Hello @jaycroll @TonyRutherford1,

We are still busy with creating the docker environment for the Magento 2.4.0 version. We will keep you updated.

kind regards,
Alexandros

**Comment by acampos1916** [comment]
@jaycroll @TonyRutherford1,

The plugin and its functionalities are compatible with Magento 2.4.

Moreover, from the original post:

> ...(`magento/framework: 103.0.0`) is not yet supported. Is there a timeline where in we can expect a full compatibility with Magento 2.4.0?
> 
> ```
>   Problem 1
>     - Installation request for adyen/module-payment ^6.6 -> satisfiable by adyen/module-payment[6.6.0].
>     - adyen/module-payment 6.6.0 requires magento/framework >=101.0.8 <102 || >=102.0.1 -> no matching package found.
> ```

`magento/framework: 103.0.0` is satisfied by the `>=101.0.8 <102 || >=102.0.1` constraint, maybe there’s something wrong with that composer setup?

I'll close this issue now but feel free to add new messages and it can be reopened if needed.

Best,
Ángel
