### ISSUE TITLE
Error while install Adyen module - 5.4.0 on Magento Version 2.2.8 with Php 7.1

### ISSUE THREAD

**Issue by MeetKamal** [Adyen/adyen-magento2#832]
Hello Dear,

We are facing one issue while installing Adyen Payment module 5.4.0  in the Magento 2.2.8. Below error we are getting while Installing this module, Below steps we have done

1. composer require  - done 
2. composer update - done
3. php bin/magento s:up  - when we tried that steps below error appear. 

  [Exception]                                                                                                                                 
  Warning: array_merge(): Argument #1 is not an array in /vendor/magento/framework/App/Config/Initial/Converter.php   on line 78

We did some research on this type or error and noticed it happen majorly with wrong configuration in config.xml file,  we also checked the config.xml file and it seems okay. But at the end of xml file there is code base to exclude Adyen payment module for Minification that may cause this error 

File Path:  vendor/adyen/module-payment/etc/config.xml 
"<dev>
            <js>
                <minify_exclude>
                    <adyen_payment>adyen.com/checkoutshopper</adyen_payment>
                </minify_exclude>
            </js>
            <css>
                <minify_exclude>
                    <adyen_payment>adyen.com/checkoutshopper</adyen_payment>
                </minify_exclude>
            </css>
        </dev>"

Can you please try to re-produce it at your end and let us know how to fix this issue.

**Comment by etienne-blackbird** [comment]
Hi,

We have the same issue as of Adyen_Payment 6.6.0. and Magento 2.2.11.
This issue seems to come indeed from the config.xml file of the module 

```
<minify_exclude>
    <adyen_payment>adyen.com/checkoutshopper</adyen_payment>
</minify_exclude>


<minify_exclude>
    <adyen_payment>adyen.com/checkoutshopper</adyen_payment>
</minify_exclude>
```

should be changed to : 

```
<minify_exclude>
adyen.com/checkoutshopper
</minify_exclude>


<minify_exclude>
adyen.com/checkoutshopper
</minify_exclude>
```

**Comment by AlexandrosMor** [comment]
Hello @MeetKamal, 

Indeed this setting in the configuration is not supported from magento 2.3 so [we did remove it ](https://github.com/Adyen/adyen-magento2/pull/850).  We are planning to create a generic fix in the coming releases

regards,
Alexandirs
