### ISSUE TITLE
Google Pay Integration Issue 6.6.0

### ISSUE THREAD

**Issue by gbukhtatyy** [Adyen/adyen-magento2#842]
**Describe the bug**
We have enabled Google Pay on our live site, at the payment stage the frontend displays "Google Pay is not available". The console logs an error Unable to process binding  `Unable to process binding "event: function(){return { change:onPaymentMethodContentChange} }"`

**To Reproduce**
- Go to the checkout payment stage
- Click the Google Pay option

**Expected behavior**
The Google Pay button to load at the payment stage

**Screenshots**
![image](https://user-images.githubusercontent.com/38346385/95198111-59c53880-07e3-11eb-8edc-a45772df8c3c.png)

**Files:**
[google-pay-form.html](https://github.com/Adyen/adyen-magento2/blob/6.6.0/view/frontend/web/template/payment/google-pay-form.html)
[adyen-google-pay-method.js](https://github.com/Adyen/adyen-magento2/blob/6.6.0/view/frontend/web/js/view/payment/method-renderer/adyen-google-pay-method.js)

**Desktop:**
Magento: 2.3.5-p1
Browser: chrome
Version: 6.6.0

**Comment by acampos1916** [comment]
Hello @gbukhtatyy, this has already been fixed in #836 and will be released in the next few days.

Cheers,
Ángel

**Comment by gbukhtatyy** [comment]
Hello, @acampos1916, Thanks!

Cheers,
George

**Comment by cyattilakiss** [comment]
Hi @gbukhtatyy ,

the fix has been released under the version 6.6.1.
I will close this issue for now but please feel free to reopen it if you still face any issue related to this.

Best,
Attila
Adyen
