### ISSUE TITLE
3D-secure validation was unsuccessful but order processes

### ISSUE THREAD

**Issue by karlsminton** [Adyen/adyen-magento2#844]
**Describe the bug**
Using adyen version 6.1.0, magento 2.3.3 
Client placing an order is getting redirected to the cart and getting a `3D-secure validation was unsuccessful` message, however the order is going through and they are receiving an order confirmation email. This is happening inconsistently.   When the client reattempted ordering this worked as intended and successfully validated.

**To Reproduce**
1. Filled shipping and billing information
2. After clicking place order I am taken to HSBC 3d secure, it asks to send me a text message with a code which I type in and submit. it then gives me the message that it was successful and I click continue. 
3. I then land on the 'unsuccessful' page in the screenshot and assume my order didn't place. However I got an order confirmation and it's sent to fulfilment in my account.

**Expected behavior**
Either a failed order, not going through to processing and customer receiving an email OR a successful 3DS validation.

**Desktop (please complete the following information):**
 - OS: Windows (uncertain)
 - Browser: Chrome

**Additional context**
Seems to not happen consistently.

**Comment by floorjubbega** [comment]
Hi @karlsminton, thank you for opening this issue and apologies for the delay!
We will jump in the open support ticket you have with us and continue the investigation in there. 
Note that the Magento Adyen plugin only send a mail once an invoice is created, so this should indeed not happen if the transactions are not completed. 

Regards, 
Floor

**Comment by floorjubbega** [comment]
Hi @karlsminton, 

Was this issue resolved for you? Otherwise feel free to reach out and we can further look into it!

Regards, 
Floor 
Adyen

**Comment by cyattilakiss** [comment]
Hi @karlsminton ,

I will close this issue for now because we haven't heard from you back for some time now but please feel free to reopen the issue if it is still unresolved.

Best,
Attila
Adyen
