### ISSUE TITLE
Order staying in state "new" and status "pending" despite being paid and captured

### ISSUE THREAD

**Issue by etienne-blackbird** [Adyen/adyen-magento2#848]
**Describe the bug**
For some orders our Magento is receiving multiple notifications with the eventCode "AUTHORISATION". Whenever the first notification is not in success it cancels the order. Then we receive a second notification a few minutes later that is in success and make the order goes to state : "new" and status "pending" and the invoice is not created.
This breaks our flow of orders as we are exporting the orders when they hit the 'processing' state.

After the successful notification the order items in the table 'sales_order_item' remains with a 'qty_cancel' above 0 and thus the order is not invoiced.

**To Reproduce**
1. Create an order
2. use an invalid card number (or whatever could make a payment refused in the first place)
3. use a valid card number
4. Check the status of the order in Magento.

**Expected behavior**
An order with the state and status to 'processing' and with an invoice created.

**Screenshots**
![image](https://user-images.githubusercontent.com/30313013/95474195-215d6000-0985-11eb-84af-567dcd4ed465.png)

**Desktop:**
 - OS: windows (uncertains
 - Browser. Chrome

**Additional context**
Magento version 2.2.11
Adyen's module version : 6.5.0.
Happens consistently

**Comment by floorjubbega** [comment]
Hi @etienne-blackbird, 

We have seen this issue either by using third party modules for order number generation that does not reset the order ID after a transaction fails, or when using our Adyen module in combination with non-Adyen payment methods (PR #830). 
Could you check if your issue might be related to either of these, and let us know?

Best, 
Floor
Adyen

**Comment by etienne-blackbird** [comment]
Hi @floorjubbega 

We do not have a third party module for order number generation.
We are using the default Magento's module for Paypal payment integration and it's the only other non-Adyen payment method. 

Kind regards,
Etienne

**Comment by floorjubbega** [comment]
Hi @etienne-blackbird, 

Thank you for clarifying! Indeed, then this issue was resolved in #830 (in version 6.6.1). 
Could you update to preferably our latest Magento 2 version (currently 6.6.8)? Feel free to reopen this issue if the problem persists.

Regards,
Floor
Adyen
