### ISSUE TITLE
[PW-3288] Customer is not redirected to 3D gateway when paying with Google Pay

### ISSUE THREAD

**Issue by fahu** [Adyen/adyen-magento2#854]
We upgraded the Magento Adyen module from v4.4 to v6.6.1. After the upgrade it's not possible anymore to place orders using Google Pay with 3D secure enabled. After selecting the payment method and clicking on 'Continue' in Google Pay the user is redirected to `/adyen/process/redirect` and instead of being redirected again to the 3D secure payment gateway a blank page appears. 

The reason for the blank page is because the following exception is thrown:
```
AdyenException: No paRequest is provided.
```

The exception is thrown because in `adyen/module-payment/view/frontend/templates/redirect/redirect.phtml` we try to get the `paRequest` (`$block->getPaReq()`) but the `paRequest` is not set and an exception is thrown.

The `paRequest` does not get set because in `CheckoutResponseValidator.php` we validate the response from Adyens `/authorise` endpoint and expect that the response contains `PaReq`, `MD`, `TermUrl`. However, for Google Pay the `TermUrl` is missing. Therefore we don't set the `PaReq` and the above exception is thrown on redirect to `/adyen/process/redirect`

I'm not a 100% sure if this is a bug in the Adyen `/authorise` endpoint or in the Adyen module, but I assume it's the Adyen module as it used to work in v4.4. Additionally, the `TermUrl` validation has been introduced lately with #799

Due to this issue the whole Google Pay functionality is broken (again!). I kindly ask you to prioritise this issue.

**To Reproduce**
1. Checkout with Google Pay
2. *Google Pay dialog pops up*
3. Select payment method and click on `continue`
4. The user is redirected to `/adyen/process/redirect`and a blank screen appears.

**Expected behavior**
The user is redirected to the 3D secure payment gateway.

**Additional context**
Probably caused due to #799

**Comment by floorjubbega** [comment]
Hi @fahu, 

Thank you for opening this issue.
We have opened an internal ticket to investigate the issue and will come back to you as soon as possible.

Regards, 
Floor

**Comment by fahu** [comment]
Thank you @floorjubbega 

If you need additional input or help to reproduce it then please let me know.

**Comment by fahu** [comment]
As already suspected #852 fixes this bug.
