### ISSUE TITLE
sessionValidity is in the past

### ISSUE THREAD

**Issue by hatimeria-artur-jewula** [Adyen/adyen-magento2#86]
I've installed the module in very fresh magento2 platform for testing purposes. However the module is not working and logs tells me this is because "Error: sessionValidity is in the past". The parameter that is send is in UTC (+00:00), example values are:
2016-12-15T12:05:40+00:00 send at 11:05:40+00:00. 
It seems to me that this is not parsed and it is treated as a different timezone. I am not seeing any timezone options in the merchant settings.

**Comment by rikterbeek** [comment]
Hi @hatimeria-artur-jewula,

The timzone is defined in the php.ini file. Looks like you have some misconfiguration here.

Regards,
Rik
Adyen

**Comment by hatimeria-artur-jewula** [comment]
Hi @rikterbeek, what misconfiguratio? php.ini is set to UTC timezone and date() function will out put just right that. There is timezone indication in the sessionValidity string (+00:00). It looks to me that the system on adyen side does not recognize it correctly. If this is not the case what timezone should be set in php.ini?

**Comment by hatimeria-artur-jewula** [comment]
I do not see this issue anymore. Tested on 2 separate machines.
