### ISSUE TITLE
Fatal error after 3D Secure validation

### ISSUE THREAD

**Issue by mksvn-gmbh** [Adyen/adyen-magento2#866]
**Describe the bug**
We have updated Adyen Magento 2 extension to the latest version 6.6.2 on our Magento 2.3.2 Open Source in order to resolve the issue with 3DS redirect. Now, after placing an order in Test Mode using test Credit Card with 3D Secure 2 authentication order results in Fatal Error.

Test Credit Cards without 3D Secure 2 authentication work as expected.

Stack trace:
`Fatal error: Uncaught Error: Class 'Adyen\Service\Validator\DataArrayValidator' not found in /var/www/vhosts/stage.auronia.de/htdocs/vendor/adyen/module-payment/Block/Transparent/Redirect.php:73 Stack trace: #0 /var/www/vhosts/stage.auronia.de/htdocs/generated/code/Adyen/Payment/Block/Transparent/Redirect/Interceptor.php(37): Adyen\Payment\Block\Transparent\Redirect->getPostParams() #1 /var/www/vhosts/stage.auronia.de/htdocs/vendor/adyen/module-payment/view/frontend/templates/transparent/redirect.phtml(25): Adyen\Payment\Block\Transparent\Redirect\Interceptor->getPostParams() #2 /var/www/vhosts/stage.auronia.de/htdocs/vendor/magento/framework/View/TemplateEngine/Php.php(59): include('/var/www/vhosts...') #3 /var/www/vhosts/stage.auronia.de/htdocs/vendor/magento/framework/View/Element/Template.php(271): Magento\Framework\View\TemplateEngine\Php->render(Object(Adyen\Payment\Block\Transparent\Redirect\Interceptor), '/var/www/vhosts...', Array) #4 /var/www/vhosts/stage.auronia.de/htdocs/vendor/magento/framework/Interception/I in /var/www/vhosts/stage.auronia.de/htdocs/vendor/adyen/module-payment/Block/Transparent/Redirect.php on line 73`

**To Reproduce**
1. Go to checkout
2. Provide all necessary data
3. On Billing Step select Credit Card as payment method
4. Provide CC data
![image](https://user-images.githubusercontent.com/73602009/97458676-37828e80-193b-11eb-86b9-3958a7fd9640.png)
5. Click Place Order
6. You will be redirected to 3DS simulation service
![image](https://user-images.githubusercontent.com/73602009/97458820-600a8880-193b-11eb-92b7-7a649a59e967.png)
7. Provide Username and Password
8. You will see Fatal Error
![image](https://user-images.githubusercontent.com/73602009/97458861-68fb5a00-193b-11eb-8f65-7089372dc644.png)
9. Despite the error order is placed and visible in Magento 2 Admin Panel with following info:
`Customer was redirected to bank for 3D-secure validation. Once the shopper authenticated, the order status will be updated accordingly.
Make sure that your notifications are being processed!
If the order is stuck on this status, the shopper abandoned the session. The payment can be seen as unsuccessful.
The order can be automatically cancelled based on the OFFER_CLOSED notification. Please contact Adyen Support to enable this.`

**Expected behavior**
3DS authorization should be successfully preformed and user should be redirected to Magento Success page.

**Screenshots**
![image](https://user-images.githubusercontent.com/73602009/97460759-58e47a00-193d-11eb-8bef-5b5daa98bd5a.png)
![image](https://user-images.githubusercontent.com/73602009/97460782-5eda5b00-193d-11eb-82b8-a206ea91f197.png)
![image](https://user-images.githubusercontent.com/73602009/97460825-67cb2c80-193d-11eb-939d-6bae6c94f852.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 86.0.4240.111
 - Magento version: 2.3.2 Open Source

**Additional context**
This issue happens when **3DS2.0 Enabled** setting is set to **No** in Magento Admin Panel. When it is set to *Yes* this issue is not happening, however in that case 3D Secure authorization is different:
![image](https://user-images.githubusercontent.com/73602009/97459839-7cf38b80-193c-11eb-9501-935fafaf20c3.png)
This scenario works, but it was always working in the Test Mode even with the 5.4.0 version of the extension that we used previously. At the same time none of the CC order with 3DS made in Live Mode where successful - all of them were stuck on on the verification state with the following info:
`Customer was redirected to bank for 3D-secure validation. Once the shopper authenticated, the order status will be updated accordingly.
Make sure that your notifications are being processed!
If the order is stuck on this status, the shopper abandoned the session. The payment can be seen as unsuccessful.
The order can be automatically cancelled based on the OFFER_CLOSED notification. Please contact Adyen Support to enable this.`

**Comment by AlexandrosMor** [comment]
Hello @mksvn-gmbh,

This issue was reported again #861  and it is fixed with the latest version (6.6.4)[https://github.com/Adyen/adyen-magento2/releases/tag/6.6.4]

kind regards
Alexandros
