### ISSUE TITLE
Cash payment method not implemented?

### ISSUE THREAD

**Issue by ebaschiera** [Adyen/adyen-magento2#87]
Hi,
in module for Magento 1 there is a "cash" payment method, which is very useful for us. Is there also in Adyen module for Magento 2? Can you implement that, please? Or can you provide some information on how to develop that?
Thank you.

-Ermanno Baschiera

**Comment by rikterbeek** [comment]
Hi @ebaschiera,

Cash is not implemented for Magento2. Where do you want to use it for ? It is not hard to implement you can see the exact code here for M1:  https://github.com/Adyen/adyen-magento/blob/develop/app/code/community/Adyen/Payment/Model/Adyen/Cash.php#L86-L156
This is an old HTTP POST implementation and we should add it to our API lib that we use for the  Magento2 plugin. see API lib here: https://github.com/Adyen/adyen-php-api-library

Regards,
Rik
Adyen

**Comment by ebaschiera** [comment]
Allright, thank you, Rik.
And how about the Payment Fee extension? We find it very useful. Do you plan to implement it?

Thank you.
Best regards.

-Ermanno Baschiera

**Comment by rikterbeek** [comment]
Hi @ebaschiera,

See response on this here :#92

Regards,
Rik
Adyen
