### ISSUE TITLE
[PW-3463] 'MANUAL_REVIEW_REJECT ' (trailing space) instead of 'MANUAL_REVIEW_REJECT' (no trailing space)

### ISSUE THREAD

**Issue by aloupfor** [Adyen/adyen-magento2#872]
**Describe the bug**

I spotted a trailing space that might lead to execution of code that is not related to `MANUAL_REVIEW_REJECT` notification event code.

I did not try to reproduce it (and will let you confirm the issue) but line: https://github.com/Adyen/adyen-magento2/blob/develop/Model/Notification.php#L46 is:

```
    const MANUAL_REVIEW_REJECT = 'MANUAL_REVIEW_REJECT ';
```
I think it should be:

```
    const MANUAL_REVIEW_REJECT = 'MANUAL_REVIEW_REJECT';
```

**To Reproduce**
1. Receive a notification with event code `MANUAL_REVIEW_REJECT`.
2. Run `adyen_payment_process_notification`

**Expected behavior**

A notification with event code `MANUAL_REVIEW_REJECT` should execute : https://github.com/Adyen/adyen-magento2/blob/develop/Model/Cron.php#L1030-L1032

```
            case Notification::MANUAL_REVIEW_REJECT:
                // don't do anything it will send a CANCEL_OR_REFUND notification when this payment is captured
                break;
```

instead of executing: https://github.com/Adyen/adyen-magento2/blob/develop/Model/Cron.php#L1345-L1349

```
            default:
                $this->_adyenLogger->addAdyenNotificationCronjob(
                    sprintf('This notification event: %s is not supported so will be ignored', $this->_eventCode)
                );
                break;
```

**Comment by cyattilakiss** [comment]
Hi @aloupfor ,

Thank you for spotting this. Indeed it looks like a bug, let us validate it and create a quick fix for it.

Best,
Attila
Adyen

**Comment by AlexandrosMor** [comment]
Hello @aloupfor,

We removed the trail space from  `MANUAL_REVIEW_REJECT`. It would be add it to the next adyen-magento2 plugin release

PR #886 

Kind regards,
Alexandros
Adyen
