### ISSUE TITLE
[PW-3388] Credit cards are being saved without selecting the option

### ISSUE THREAD

**Issue by marquesdevopen** [Adyen/adyen-magento2#873]
**Describe the bug**
Adyen 6.6.0 on magento 2.2.9.
After making the payment, the cards are being saved without the customer selecting the option to save card at the time of payment.

**To Reproduce**
1. Go to checkout and place an order with a credit card without selecting the option "save card for future purchases".
2. Place an order again, and you will see that the card has been saved.

**Expected behavior**
Credit cards should not been saved if the option is not selected.

**Desktop (please complete the following information):**
 - OS: macos
 - Browser crome
 - Version 86

**Additional context**
We have not found any log related to this error.

**Comment by msilvagarcia** [comment]
Hey @marquesdevopen 

Thanks for the feedback. I could reproduce the issue and will look into it.

Cheers!
Marcos
Adyen

**Comment by msilvagarcia** [comment]
Hey there,

Just tested with Magento 2.4.1 with the following settings:

- Advanced: Billing Agreements
    - Enable OneClick: No
    - Enable Recurring: Yes
- CreditCard API Integration
    - Vault Enabled: Yes
- Stored Payment Methods - Requires Adyen Credit Card
    - Agreement Type: RECURRING

And with these settings:

- Advanced: Billing Agreements
    - Enable OneClick: Yes
    - Enable Recurring: No
- CreditCard API Integration
    - Vault Enabled: No
- Stored Payment Methods - Requires Adyen Credit Card
    - Agreement Type: ONECLICK

In none of these cases a logged in user had their credit card stored when the checkbox was unchecked. Would you mind double-checking your configuration and confirming if this still happens?

Kind regards,
Marcos
Adyen

**Comment by adoles** [comment]
Hi,

We just tested your new version and we can confirm that the error still happens.

Our Magento version is 2.2.9, and our configuration is:

- Advanced: Billing Agreements
  - Enable OneClick: Yes
  - Enable Recurring: No
- CreditCard API Integration
  - Vault Enabled: No
- Stored Payment Methods - Requires Adyen Credit Card
  - Agreement Type: ONECLICK

**Comment by msilvagarcia** [comment]
My bad. I was able to reproduce it now, and figured out what's the issue.

Our plugin is sending `shopperReference` and, if your account is set to enable recurring payments (which most merchants will want), the server will automatically store the payment method.

We will push a fix to this in up to two weeks and update you when we do so.

Cheers!
Marcos
Adyen
