### ISSUE TITLE
Klarna/Paypal redirect to their gateway failed and stuck on checkout page

### ISSUE THREAD

**Issue by ronakchauhan** [Adyen/adyen-magento2#878]
**Describe the bug**
I have upgrade adyen Payment module to it's latest version and got error like Klarna or paypal methods are not redirecting to it's gateway and stuck on Checkout Page

**To Reproduce**
1. Go to Checkout Page
2. Click on Klarna/Paypal payment
3. Click on Buy now
4. Page is loading only one time and redirecting on same page.

**Expected behavior**
It should redirect to paypal/Klarna gateway to proceed payment

**Screenshots**
![Screenshot 2020-11-09 at 17 04 59](https://user-images.githubusercontent.com/8565366/98565675-28da9680-22ae-11eb-9302-517b88164f07.png)

**Desktop (please complete the following information):**
 - OS: MacOs Catalina 10.15.7
 - Browser: Chrome (Latest version)
 - Version: Magento 2.3.4 - Module version 6.6.4

**Additional context**
Please resolve this issue as soon as possible

**Comment by cyattilakiss** [comment]
Hi @ronakchauhan ,

Thank you for opening this issue.

Unfortunately I am not able to reproduce this issue with Klarna or Paypal.
Do you see any error in the console?
Is there a /payments request in your info.log file?
Are you able to reproduce this issue in a staging/test environment or only on live?

Meanwhile I recommend you to contact our [support](https://support.adyen.com/hc/en-us/requests/new?ticket_form_id=360000705420) and send them the related log files (empty the log files, go to checkout and place a paypal order, all the adyen log files and the exception.log file that has content can be sent to support) and the url of your staging website where we can also reproduce this issue.

Best,
Attila
Adyen

**Comment by karlsminton** [comment]
Can also confirm that we are experiencing this issue in magento 2.4.1 and adyen/module-payment 6.6.5. Just for paypal, we're not using Klarna.

**Comment by karlsminton** [comment]
We found that a template override for `hpp-form.html` in our theme was causing the issue. @ronakchauhan does your theme have an override for this template?

**Comment by floorjubbega** [comment]
Hi @ronakchauhan, 

We will close this issue due to inactivity, and as @karlsminton has found that a template override might be causing the issue here. 
If your issue is not resolved, feel free to reach out to the support team so we can further help you troubleshoot!

Best, 
Floor 
Adyen
