### ISSUE TITLE
Magento 2.1.3

### ISSUE THREAD

**Issue by Ylmzef** [Adyen/adyen-magento2#88]
There no configuration page on Magento 2.1.3

**Comment by TommyKolkman** [comment]
Second that!

**Comment by ebaschiera** [comment]
Me too I am having the same problem. Tried installing, uninstalling, reinstalling Adyen module, but I can't find the configuration section in Magento backend.
There aren't evident error messages in log files.

Thank you.

**Comment by TommyKolkman** [comment]
@rikterbeek told me it's fixed here, https://github.com/Adyen/adyen-magento2/pull/90, and will be in an update today or later, @ebaschiera.

**Comment by ebaschiera** [comment]
Wonderful! Thank you!

**Comment by rikterbeek** [comment]
@Ylmzef @TommyKolkman  and @ebaschiera this is now in our latest 2.0.2 release.
