### ISSUE TITLE
[PW-3528] Can't capture orders with Zip payment method

### ISSUE THREAD

**Issue by trang1104isobar** [Adyen/adyen-magento2#885]
**Describe the bug**
For orders with Zip payment method, I notice that when Adyen send to Magento an Authorisation notification, Magento creates an invoice with status "paid". Because of that, we can not send capture request to Adyen from Magento, since Magento considers orders with paid invoice as "unable to capture". The only way to capture the payment is to do it manually on Adyen dashboard.

Note that I can capture other Authorised orders with other Adyen payment methods just fine, only Zip has this problem.

**To Reproduce**
1. Place an order with Zip payment method
2. Go to Magento admin and view the order, wait till it receives Authorisation notification.
3. Click on the invoice tab
4. See that it creates a paid invoice automatically, while it doesn't happen with other Adyen payment methods.

**Expected behavior**
Paid invoice should not be created before capturing the payment.

**Comment by cyattilakiss** [comment]
Hi @trang1104isobar ,

Thank you for raising this issue. An internal ticket has been created for it and will be investigated in the next week.
We are going to keep you updated about it.

Best,
Attila
Adyen

**Comment by AlexandrosMor** [comment]
Hello @trang1104isobar,

We were able to reproduce the issue and we opened a [PR](https://github.com/Adyen/adyen-magento2/pull/927) to add the zip payment to open invoice list. Furthermore please make sure that in the admin panel the Use auto-capture for OpenInvoice payments is set to No. 
It will be added in the next plugin release.

kind regards,
Alexandros

**Comment by trang1104isobar** [comment]
Hi @AlexandrosMor,

Thank you for the update.

I wasn't able to upgrade Adyen to new version yet, so I have copied the code from this commit: https://github.com/Adyen/adyen-magento2/pull/944/commits/96a946837e855366221f3ed7cde2b201fa5a6a97

However, I couldn't be redirected to ZIP gateway after that, it showed me this error message:
![image](https://user-images.githubusercontent.com/39576667/106884610-1d173880-6714-11eb-97c8-76cafd455d0e.png)

The error message in Adyen dashboard:
![image](https://user-images.githubusercontent.com/39576667/106884724-4041e800-6714-11eb-8fad-e3032123967c.png)

If I remove the code, it'd work normally again. Can you help me to see what I'm doing wrong here? Thank you very much!

**Comment by trang1104isobar** [comment]
bump

**Comment by tnaber** [comment]
Hi @trang1104isobar,

Sorry for the slow response. Did you manage to figure out the problem in the meantime?

Cheers,
Titus

**Comment by tnaber** [comment]
Closing this as it has become stale, please reopen if this is still an active problem.
