### ISSUE TITLE
[PW-4236] Order in status "Payment review" when it actually has completed sucessfully

### ISSUE THREAD

**Issue by nathantodd247** [Adyen/adyen-magento2#887]
We have had occurrences of https://github.com/Adyen/adyen-magento2/issues/744

Order stays at "Payment Review" even though the order status history shows the order moving to status "Processing"

On Test systems and Live

Magento 2.3.5 P2

**Comment by amenk** [comment]
Check you access logs for requests like

     82.199.90.163 - - [15/Jan/2021:12:37:24 +0100] "POST /adyen/process/json HTTP/1.1" 301 658 "-" "Adyen HttpClient 1.0"

And if they go through .. in our case we had a IP whitelist in the test system and they are blocked.

**Comment by nathantodd247** [comment]
Hi

 

Many thanks for that, this is a random issue on production, 99.99% go through OK

 

 

Kind regards,

Nathan Todd | Project Manager
247 Commerce Limited 
Unit 1, Lincoln House, GWQ, Great West Road, Brentford TW8 0GE
Registered No. 07775662 in England and Wales. 

Phone: +44 20 8940 7011
Email : nathan.todd@247commerce.co.uk <mailto:nathan.todd@247commerce.co.uk>  ||  <http://www.247commerce.co.uk/> www.247commerce.co.uk

The information in this e-mail may be confidential and or legally privileged. It is intended solely for the use of the addressee. Access to this e-mail by anyone else is unauthorised. If you are not the intended recipient, any disclosure, copying, distribution or any action taken or omitted to be taken in reliance on it, is prohibited and may be unlawful.

**Comment by acampos1916** [comment]
Hello all, seems like this issue was originally related to an IP whitelist. I'm going to close it now, but please leave a comment if any new info is found.
