### ISSUE TITLE
Apple Pay: {amount} is not a valid amount

### ISSUE THREAD

**Issue by atty31** [Adyen/adyen-magento2#894]
**Describe the bug**
Cannot place an order with Apple Pay. JS error is triggered. The error is triggered from: vendor/adyen/module-payment/view/frontend/web/js/view/payment/method-renderer/adyen-apple-pay-method.js:88
`var session = new ApplePaySession(applePayVersion, request);`

**To Reproduce**
1. Add a product to cart. The price of the product is 0.6 
2. Go to checkout 
3. Select Apple Pay
4. Accept Terms and Conditions
5. Press the pay button

**Expected behavior**
To submit the order 

**Screenshots**
See screenshot: https://imgur.com/a/iAvl2TH

Magento version: 2.4.0
Adyen Version: 6.6.5

**Comment by floorjubbega** [comment]
Hi @atty31, 

Thank you for opening this issue!
Do you have the JS error only for particularly small amounts (such as EUR 0.6), or for any amount?
We also suggest to open ticket with our support team, so we can help troubleshoot using the logs. 

Best, 
Floor 
Adyen

**Comment by cyattilakiss** [comment]
Hi @atty31 

There has been a lot of improvements regarding apple pay and I believe this issue has been fixed since then. In case you still face this issue with the latest plugin version please feel free to reopen this issue.

Best,
Attila
Adyen

**Comment by ebaschiera** [comment]
For the record: the problem was that the amount should be rounded to the correct decimals. In my case the amount in Euro had 3 decimals instead of 2.
I fixed it by porting more or less what has been done for Google Pay here in Adyen module.
