### ISSUE TITLE
Headless - 3DS process type error

### ISSUE THREAD

**Issue by brightonmike** [Adyen/adyen-magento2#895]
**Describe the bug**
threeDS2process POST throwing type error

```
{"message":"The \"array\" value's type is invalid. The \"string\" type was expected. Verify and try again.","trace":null}
```

I'm getting this error on `adyen/threeDS2Process` endpoint. I've checked that I'm passing the right information. I've tried adding logging to `vendor/adyen/module-payment/Model/AdyenThreeDS2Process.php` but nothing throws.

Example body:

```
{"payload":{"details":{"threeds2.fingerprint":"346346436346=="},"paymentData":"","orderId":"10"}}
```

Non-3DS card payments are operating normally. Frustratingly the error does not provide information on what was passed as an array and shouldn't. I've checked all other requests to Adyen and only the street address is passed as an array which is normal?

**Comment by acampos1916** [comment]
Hello @brightonmike, thanks for opening this issue,

In which version of the plugin and Magento2 have you encountered this? Are you able to use a debugger and breakpoints in the `AdyenThreeDS2Process.php` to pinpoint the issue?

**Comment by brightonmike** [comment]
@acampos1916  this appears to be because I was not wrapping the payload in `JSON.stringify()`. It seems strange to need to do this as the whole object is wrapped in another `JSON.stringify()` but this did fix the issue.
