### ISSUE TITLE
Store frontend returns "Server error"

### ISSUE THREAD

**Issue by imrankln** [Adyen/adyen-magento2#896]
**Describe the bug**
While using non allowed card type. Suppose we are not allowing JCB, while customer tries to checkout with JCB card, system returns following error:
 "A server error stopped your order from being placed. Please try to place your order again"

**To Reproduce**
1. Go to checkout page
2. Input non allowed type of credit card
3. click on Place order
4. See error (js)

**Expected behavior**
Error should be the following one:
"Error with payment method please select different payment method"
old version 6.6.1 returned the above error but the latest version returns "server error"

**Screenshots**
![image](https://user-images.githubusercontent.com/4917977/100825300-144b8180-349b-11eb-827a-78539b71e9a6.png)

**Desktop (please complete the following information):**
 - OS: [all]
 - Browser [all]
 - Version [all]

**Smartphone (please complete the following information):**
 - Device: [all]
 - OS: [all]
 - Browser [all]
 - Version [all]

**Additional context**
LOG
> main.CRITICAL: Notice: Undefined index: resultCode in /opt/cbe/mjp-magento/vendor/adyen/module-payment/Gateway/Validator/CheckoutResponseValidator.php on line 69

**Comment by floorjubbega** [comment]
solved by #897
