### ISSUE TITLE
Error on checkout page.

### ISSUE THREAD

**Issue by Rutvi06** [Adyen/adyen-magento2#9]
I have successfully installed the module and I can configure it from backend for test.
But when I go to checkout page it gives me error like:

Fatal error: Class 'Adyen\Client' not found in C:\xampp\htdocs\magento2\app\code\Adyen\Payment\Model\Api\PaymentRequest.php on line 96

Please help.
Thanks

**Comment by rikterbeek** [comment]
Hi Rutvi06,

Did you install the module through composer ? Make sure you have the api library installed. see https://github.com/Adyen/adyen-magento2/blob/develop/composer.json#L33

Regards,
Rik
Adyen

**Comment by Rutvi06** [comment]
Hi Rik,

Thnaks for the quick reply. 
I have adyen-api defined in my composer. But when i am trying to install composer, it gives me error like-
 [UnexpectedValueException]
 Repository "0" ({"adyen":{"type":"vcs","url":"git@github.com:Adyen\/adyen-p
 hp-api-library.git"}}) must have a type defined.
Please help

Regards,
Rutvi

**Comment by rikterbeek** [comment]
Hi Rutvi06,

That is not needed anymore so i removed it in the develop branch will be in the release branch next bugfix release and that will be somewhere this week.

Regards,
Rik

**Comment by Rutvi06** [comment]
Hi Rik,
            Thanks for help.once you commit let me know so i can test it.
Regards,
Rutvi.

**Comment by rikterbeek** [comment]
Hi Rutvi06,

I did a new release 1.1.1 this has not this repository part in it could you check again?

Regards,
Rik
Adyen

**Comment by Rutvi06** [comment]
Hi Rik,
I have installed new realease but i have same fatal error as above.
so I want to know that I am trying to test on my local so is it possible that it is my configuration error to adyen ? i want to ask if I want to run on my local what I can do? so give step for adyen configuration on test.

Regards,
Rutvi

**Comment by rikterbeek** [comment]
Hi Rutvi06,

I think because you installed it the first time not with composer. Could you remove the folder app/code/Adyen. You should run composer and that will install the module into the vendor directory together with the library. You should have the following directories then:
vendor/adyen/adyen-php-api-library
vendor/adyen/module-payment

Regards,
Rik
Adyen

**Comment by Rutvi06** [comment]
Hi Rik,
I remove adyen folder but i have to add something for adyen somewhere? because it could't generate directly in vendor.

Regards,
Rutvi

**Comment by rikterbeek** [comment]
Hi Rutvi06,

Have a look here how you can install the module with composer this should work:
https://firebearstudio.com/blog/how-to-install-magento-2-modules-extensions.html

Regards,
Rik
Adyen

**Comment by rikterbeek** [comment]
Hi Rutvi06,

I am closing this issue.

Regards,
Rik
Adyen
