### ISSUE TITLE
[PW-3384/3658] SEPA direct debit saved in vault - 2nd use, incorrect information saved

### ISSUE THREAD

**Issue by paulappelbe** [Adyen/adyen-magento2#900]
**Describe the bug**
When a SEPA direct debit is saved to the vault : the first payment is fine, but when a payment uses the vault (so second payment onwards) the data saved to the order is wrong, it treats it « half » like a credit card 

**To Reproduce**
1. Create an order, use sepa direct debit and save to vault
2. Create another order using sepa direct debit from vault
3. see order email & payment information in admin -> wrong data - half of the information is credit card related which is obviously incorrect

**Expected behavior**
![expected](https://user-images.githubusercontent.com/45454205/100981376-05220d80-3547-11eb-8564-4818e8415667.png)

**Actual behavior**

![Capture d’écran 2020-11-20 à 11 21 52](https://user-images.githubusercontent.com/45454205/100981003-70b7ab00-3546-11eb-89fd-a79b86d647db.png)

**Comment by acampos1916** [comment]
Hello @paulappelbe,

Indeed this is a known situation. In order to use Vault with a non-card payment method we still had to use card tokens. Magento doesn't support Vault tokenisation for payment methods with initialize command. See #822.

Still, we're investigating an alternative solution, I've added this issue to our internal tracker.

Best,
Ángel

**Comment by gudal** [comment]
Hello, 
Do you know when this issue will be dealt with ?

Thanks,
Guillaume Dalaudier

**Comment by acampos1916** [comment]
Hello @gudal,

It is still in our backlog, as soon as it is addressed we'll update this issue.

**Comment by gudal** [comment]
Hello, 

Any news on this issue ?

Thanks,
Guillaume Dalaudier

**Comment by gudal** [comment]
Hello,

Any news on this issue ?

Thanks,
Guillaume Dalaudier

**Comment by acampos1916** [comment]
Hey @gudal apologies for the delay. Unfortunately still in our backlog but we've preliminary planned the following:

Since the payment info block is showing the data from the vault payment method provider (in this case CC vault):

- Create a service to store method names and codes using the payment methods call.
- Link the order payment with the adyen_order_payment entity and DB table using the order ID, increment ID, PSP reference or Payment ID.
- Use the parent's _toHtml method to get the full method info and replace the title using regex to insert the one coming from adyen_order_payment.

We're still having discussions if this is the best way to approach it, and we'll update this issue with progress made ASAP.

**Comment by mverroyedata** [comment]
Hi,
Regarding your code, it seems that you use same payment method ("adyen_cc_vault") for all vault payments  (in our case CC and HPP). So all vault payment are marked as "CC" (credit card).
Also you  are recording all vault_payment_token as adyen_cc.
I add a fix by creating "adyen_hpp_vault" payment method which doesn't exist and changing value of payment_method_code for HPP payent with "adyen_hpp_vault" value. I don't make any changes for frontend part because we don't use it.
I'm waiting for your correction to replace this fix.

Regards,

**Comment by acampos1916** [comment]
@mverroyedata thanks for your feedback. Indeed we thought of that solution as well, but HPP is a payment method that requires an `initialize` command and Magento doesn't support initialize + vault. Here we rolled back those changes #822. If you're not using Magento's frontend maybe you already have a workaround for this and it works for you.

**Comment by mverroyedata** [comment]
Yes HPP requires an initialize but not HPP_vault wich works like CC_VAULT used at now (with token). 
So you can create an HPP_VAULT method with a specific configuration and set "can_initialize" to 0. 
I have created "adyen_hpp_vault" based on virtualtype AdyenPaymentHppVaultFacade with code "adyen_hpp_vault" and 
specific config AdyenPaymentHppVaultConfig, specific valueHandlerPool , specific vaultProvider, ... 
And I still use adyen_hpp (with initialize) to new sepa payment.
Hope it can help.

**Comment by acampos1916** [comment]
@mverroyedata interesting! Which vault provider did you use? https://github.com/Adyen/adyen-magento2/pull/822/files#diff-093a1e43a11122404c853506b7ca4f661e18dd4f6557ec3089cad8ceae34a606L62

If it's possible for you, a PR with this recommendation to our develop branch would be greatly appreciated.

**Comment by mverroyedata** [comment]
Hi,


I use « AdyenPaymentHppVaultAdapter ». I don’t make lot of changes :



Etc/config.xml :



<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:module:Magento_Store:etc/config.xsd">
    <default>
        <payment>
            <adyen_hpp>
                <active>0</active>
                <model>AdyenPaymentHppFacade</model>
                <order_status>pending</order_status>
                <title>Alternative payment methods</title>
                <allowspecific>0</allowspecific>
                <ratepay_id>oj9GsQ</ratepay_id>
                <sort_order>3</sort_order>
                <payment_action>authorize</payment_action>
                <is_gateway>1</is_gateway>
                <can_use_checkout>1</can_use_checkout>
                <can_capture>1</can_capture>
                <can_capture_partial>1</can_capture_partial>
                <can_use_internal>0</can_use_internal>
                <can_refund_partial_per_invoice>1</can_refund_partial_per_invoice>
                <can_refund>1</can_refund>
                <can_void>1</can_void>
                <can_cancel>1</can_cancel>
                <can_authorize_vault>1</can_authorize_vault>
                <can_capture_vault>0</can_capture_vault>
                <can_initialize>1</can_initialize>
                <group>adyen</group>
            </adyen_hpp>
            <adyen_hpp_vault>
                <model>AdyenPaymentHppVaultFacade</model>
                <title>Stored Alternative payment methods (Adyen)</title>
                <instant_purchase>

<available>Adyen\Payment\Model\InstantPurchase\CreditCard\AvailabilityChecker</available>
<tokenFormat>Adyen\Payment\Model\InstantPurchase\CreditCard\TokenFormatter</tokenFormat>

                </instant_purchase>
                <order_status>pending</order_status>
                <allowspecific>0</allowspecific>
                <ratepay_id>oj9GsQ</ratepay_id>
                <sort_order>3</sort_order>
                <payment_action>authorize</payment_action>
                <is_gateway>1</is_gateway>
                <can_use_checkout>1</can_use_checkout>
                <can_capture>1</can_capture>
                <can_capture_partial>1</can_capture_partial>
                <can_use_internal>0</can_use_internal>
                <can_refund_partial_per_invoice>1</can_refund_partial_per_invoice>
                <can_refund>1</can_refund>
                <can_void>1</can_void>
                <can_cancel>1</can_cancel>
                <can_authorize_vault>1</can_authorize_vault>
                <can_capture_vault>1</can_capture_vault>
                <group>adyen</group>
                <can_initialize>0</can_initialize>
            </adyen_hpp_vault>
        </payment>
    </default>
</config>



Etc/di.xml :



<virtualType name="AdyenPaymentHppVaultFacade" type="Magento\Vault\Model\Method\Vault">
    <arguments>
        <argument name="code" xsi:type="const">Danone\Adyen\Model\Ui\AdyenHppConfigProvider::CC_VAULT_CODE</argument>
        <argument name="config" xsi:type="object">AdyenPaymentHppVaultConfig</argument>
        <argument name="valueHandlerPool" xsi:type="object">AdyenPaymentHppVaultPaymentValueHandlerPool</argument>
        <argument name="vaultProvider" xsi:type="object">AdyenPaymentHppVaultAdapter</argument>
    </arguments>
</virtualType>
<virtualType name="AdyenPaymentHppVaultAdapter" type="Magento\Payment\Model\Method\Adapter">
    <arguments>
        <argument name="code" xsi:type="const">Adyen\Payment\Model\Ui\AdyenHppConfigProvider::CODE</argument>
        <argument name="formBlockType" xsi:type="string">Adyen\Payment\Block\Form\Hpp</argument>
        <argument name="infoBlockType" xsi:type="string">Adyen\Payment\Block\Info\Hpp</argument>
        <argument name="valueHandlerPool" xsi:type="object">AdyenPaymentHppVaultValueHandlerPool</argument>
        <argument name="validatorPool" xsi:type="object">AdyenPaymentHppValidatorPool</argument>
        <argument name="commandPool" xsi:type="object">AdyenPaymentHppCommandPool</argument>
    </arguments>
</virtualType>
<virtualType name="AdyenPaymentHppVaultValidatorPool" type="Magento\Payment\Gateway\Validator\ValidatorPool">
    <arguments>
        <argument name="validators" xsi:type="array">
            <item name="country" xsi:type="string">AdyenHppVaultCountryValidator</item>
        </argument>
    </arguments>
</virtualType>
<virtualType name="AdyenHppVaultCountryValidator" type="Magento\Payment\Gateway\Validator\CountryValidator">
    <arguments>
        <argument name="config" xsi:type="object">AdyenPaymentHppVaultConfig</argument>
    </arguments>
</virtualType>
<virtualType name="AdyenPaymentHppVaultConfigValueHandler" type="Magento\Payment\Gateway\Config\ConfigValueHandler">
    <arguments>
        <argument name="configInterface" xsi:type="object">AdyenPaymentHppVaultConfig</argument>
    </arguments>
</virtualType>
<virtualType name="AdyenPaymentHppVaultValueHandlerPool" type="Magento\Payment\Gateway\Config\ValueHandlerPool">
    <arguments>
        <argument name="handlers" xsi:type="array">
            <item name="default" xsi:type="string">AdyenPaymentHppVaultConfigValueHandler</item>
        </argument>
    </arguments>
</virtualType>
<virtualType name="AdyenPaymentHppVaultPaymentValueHandler" type="VaultPaymentDefaultValueHandler">
    <arguments>
        <argument name="configInterface" xsi:type="object">AdyenPaymentHppVaultConfig</argument>
    </arguments>
</virtualType>
<virtualType name="AdyenPaymentHppVaultPaymentValueHandlerPool" type="VaultPaymentValueHandlerPool">
    <arguments>
        <argument name="handlers" xsi:type="array">
            <item name="default" xsi:type="string">AdyenPaymentHppVaultPaymentValueHandler</item>
        </argument>
    </arguments>
</virtualType>
<virtualType name="AdyenPaymentHppVaultConfig" type="Magento\Payment\Gateway\Config\Config">
    <arguments>
        <argument name="methodCode" xsi:type="const">Danone\Adyen\Model\Ui\AdyenHppConfigProvider::CC_VAULT_CODE
        </argument>
    </arguments>
</virtualType>
<virtualType name="AdyenPaymentHppCommandManager" type="Magento\Payment\Gateway\Command\CommandManager">
    <arguments>
        <argument name="commandPool" xsi:type="object">AdyenPaymentHppCommandPool</argument>
    </arguments>
</virtualType>
<type name="Magento\Payment\Gateway\Command\CommandManagerPool">
    <arguments>
        <argument name="executors" xsi:type="array">
            <item name="adyen_hpp" xsi:type="string">AdyenPaymentHppCommandManager</item>
        </argument>
    </arguments>
</type>
<virtualType name="AdyenPaymentHppVaultAuthorizeCommand" type="Magento\Payment\Gateway\Command\GatewayCommand">
    <arguments>
        <argument name="requestBuilder" xsi:type="object">AdyenPaymentHppVaultAuthorizeRequest</argument>
        <argument name="transferFactory" xsi:type="object">Adyen\Payment\Gateway\Http\TransferFactory</argument>
        <argument name="client" xsi:type="object">Adyen\Payment\Gateway\Http\Client\TransactionAuthorization
        </argument>
        <argument name="validator" xsi:type="object">GeneralResponseValidator</argument>
        <argument name="handler" xsi:type="object">AdyenPaymentHppVaultResponseHandlerComposite</argument>
    </arguments>
</virtualType>
<virtualType name="AdyenPaymentHppCommandPool" type="Magento\Payment\Gateway\Command\CommandPool">
    <arguments>
        <argument name="commands" xsi:type="array">
            <item name="initialize" xsi:type="string">AdyenPaymentHppAuthorizeCommand</item>
            <item name="capture" xsi:type="string">AdyenPaymentCaptureCommand</item>
            <item name="void" xsi:type="string">AdyenPaymentCancelCommand</item>
            <item name="refund" xsi:type="string">AdyenPaymentRefundCommand</item>
            <item name="cancel" xsi:type="string">AdyenPaymentCancelCommand</item>
            <item name="vault_authorize" xsi:type="string">AdyenPaymentHppVaultAuthorizeCommand</item>
        </argument>
    </arguments>
</virtualType>
<virtualType name="AdyenPaymentHppVaultAuthorizeRequest" type="Magento\Payment\Gateway\Request\BuilderComposite">
    <arguments>
        <argument name="builders" xsi:type="array">
            <item name="merchantaccount" xsi:type="string">
                Adyen\Payment\Gateway\Request\MerchantAccountDataBuilder
            </item>
            <item name="customer" xsi:type="string">Adyen\Payment\Gateway\Request\CustomerDataBuilder</item>
            <item name="customerip" xsi:type="string">Adyen\Payment\Gateway\Request\CustomerIpDataBuilder</item>
            <item name="address" xsi:type="string">Adyen\Payment\Gateway\Request\AddressDataBuilder</item>
            <item name="payment" xsi:type="string">Adyen\Payment\Gateway\Request\PaymentDataBuilder</item>
            <item name="browserinfo" xsi:type="string">Adyen\Payment\Gateway\Request\BrowserInfoDataBuilder</item>
            <item name="recurring" xsi:type="string">Adyen\Payment\Gateway\Request\RecurringVaultDataBuilder</item>
        </argument>
    </arguments>
</virtualType>
<virtualType name="AdyenPaymentHppVaultResponseHandlerComposite" type="Magento\Payment\Gateway\Response\HandlerChain">
    <arguments>
        <argument name="handlers" xsi:type="array">
            <item name="payment_details" xsi:type="string">
                Adyen\Payment\Gateway\Response\PaymentAuthorisationDetailsHandler
            </item>
            <item name="payment_comments" xsi:type="string">
                Adyen\Payment\Gateway\Response\PaymentCommentHistoryHandler
            </item>
        </argument>
    </arguments>
</virtualType>





I changed \Adyen\Payment\Model\Ui\AdyenHppConfigProvider by adding

const CC_VAULT_CODE = 'adyen_hpp_vault';

and on getConfig methode

$config = [
    'payment' => [
        self::CODE => [
            'vaultCode' => self::CC_VAULT_CODE,
            'isActive' => true,
            'redirectUrl' => $this->urlBuilder->getUrl(
                'adyen/process/redirect',
                ['_secure' => $this->getRequest()->isSecure()]
            )
        ]
    ]
];



Finally, on \Adyen\Payment\Model\Cron in methode _processNotification you make this test

if ($_paymentCode == 'adyen_hpp' && $this->configHelper->isStoreAlternativePaymentMethodEnabled()) {

then you set payment code as CC code ‘adyen_cc’

$paymentTokenAlternativePaymentMethod->setCustomerId($customerId)->setGatewayToken($this->_pspReference)->setPaymentMethodCode(AdyenCcConfigProvider::CODE)

I changed it by ‘adyen_hpp_vault’

$paymentTokenAlternativePaymentMethod->setCustomerId($customerId)->setGatewayToken($this->_pspReference)->setPaymentMethodCode(AdyenHppConfigProvider::CC_VAULT_CODE)



Regards,



***@***.***D727CD.F981A0C0]

De : Ángel Campos ***@***.***>
Envoyé : vendredi 2 avril 2021 09:30
À : Adyen/adyen-magento2 ***@***.***>
Cc : Maxime VERROYE ***@***.***>; Mention ***@***.***>
Objet : Re: [Adyen/adyen-magento2] [PW-3384] SEPA direct debit saved in vault - 2nd use, incorrect information saved (#900)


@mverroyedata<https://github.com/mverroyedata> interesting! Which vault provider did you use? https://github.com/Adyen/adyen-magento2/pull/822/files#diff-093a1e43a11122404c853506b7ca4f661e18dd4f6557ec3089cad8ceae34a606L62

If it's possible for you, a PR with this recommendation to our develop branch would be greatly appreciated.

**Comment by candemiralp** [comment]
Issue was fixed on #1563.
