### ISSUE TITLE
Checkout front-end resources 404 error in production mode

### ISSUE THREAD

**Issue by mksvn-gmbh** [Adyen/adyen-magento2#903]
**Describe the bug**
We are using Adyen Magento 2 module version 6.6.3 on Magento 2.3.2 Open Source. The problem is that when the Magento instance is switched to **production mode** where JS minification is enabled Adyen Payment Methods are not available on the Checkout page.

There is 404 error in the console regarding following file: _https://checkoutshopper-live.adyen.com/checkoutshopper/sdk/3.4.0/adyen.min.js_
![image](https://user-images.githubusercontent.com/73602009/101151490-02481b00-3622-11eb-9789-a0667333f126.png)

The problem is that the minified version is requested and it is not available. 

The problem exists only in **production mode** - there is no problem in the **developer mode** as there not minified version is not used.

**To Reproduce**
1. Enable JS minification on you Magento instance
2. Switch to production mode
3. Navigate to Checkout payment step
4. You will see that Adyen Payment Methods are not available
5. Open browser consle
6. You will see 404 error regarding Live endpoint for Checkout front-end resources

**Expected behavior**
Minified version of the Checkout front-end resources should be provided OR they should be excluded from the minification, so that Adyen Payment Methods will work correctly in **production mode**

**Screenshots**
![image](https://user-images.githubusercontent.com/73602009/101151913-a5993000-3622-11eb-9517-0a2dbc0b4706.png)

**Desktop (please complete the following information):**
 - Adyen module version: 6.6.3
 - Magento version: 2.3.2 Open Source
 - Browser: Chrome 86.0.4240.198

**Additional context**
Problem exists only in **Production mode**, no issue in **Developer mode**.

**Comment by acampos1916** [comment]
Hello @mksvn-gmbh, thanks for opening this issue.

We had created a PR to fix this with a [minification exclusion](https://github.com/Adyen/adyen-magento2/pull/816) but had to be [reverted](https://github.com/Adyen/adyen-magento2/pull/850) because it wasn't compatible with some older Magento versions. We are planning to make a generic fix for this which will cover all versions, in the meantime feel free to apply #816 as a patch.

Cheers,
Ángel
