### ISSUE TITLE
[PW-4315]OneClick - Incompatibility with version 2.3.5 and 2.4.X

### ISSUE THREAD

**Issue by anthonyherve** [Adyen/adyen-magento2#904]
Hello,

I use Magento Commerce.
I have a problem when I use a saved credit card on Magento 2.3.5 Commerce and above (2.4.X also, I don't see my registered cards with version 2.4.X Commerce), but not problem with 2.3.4.

When I want to use this saved credit card (exactly when I click on radio button), I have a 500 error:
[2020-10-26 09:01:35] report.CRITICAL: Report ID: webapi-5f96906fc0b15; Message: Notice: Undefined index: variant in /app/yrhay22bhhyla_stg/vendor/adyen/module-payment/Observer/AdyenOneclickDataAssignObserver.php on line 98 {"exception":"[object] (Exception(code: 0): Report ID: webapi-5f96906fc0b15; Message: Notice: Undefined index: variant in /app/yrhay22bhhyla_stg/vendor/adyen/module-payment/Observer/AdyenOneclickDataAssignObserver.php on line 98 at /app/yrhay22bhhyla_stg/vendor/magento/framework/Webapi/ErrorProcessor.php:208, Exception(code: 0): Notice: Undefined index: variant in /app/yrhay22bhhyla_stg/vendor/adyen/module-payment/Observer/AdyenOneclickDataAssignObserver.php on line 98 at /app/yrhay22bhhyla_stg/vendor/magento/framework/App/ErrorHandler.php:61)"} []

In my Adyen account (Account > API URLs > Additional data settings), I have checked data following documentation:
{
   "additionalData": {
      "cardHolderName": "Test Cardholder",
      "cardBin": "541333",
      "cardSummary": "1111",
      "expiryDate": "8/2018",
      "paymentMethod": "visa",
      "recurring.shopperReference": "testshopper",
      "recurring.recurringDetailReference": "1111111111111111"
   }
}

Thank you for your help.

Regards,
Anthony HERVE

**Comment by floorjubbega** [comment]
Hi @anthonyherve, 

Thank you for opening this issue!

It seems the error is thrown as the parameter `variant` is missing in the additional API settings. 
Could you add this parameter in the Customer Area (Account >> API URLs), as described [here](https://docs.adyen.com/plugins/magento-2/stored-payment-methods#step-2-set-up-billing-agreements-in-your-customer-area)?
Let us know if adding the variant parameter resolves the incompatibility issue, 

Regards, 
Floor 
Adyen

**Comment by anthonyherve** [comment]
Hi,

Thank you for your answer.
I have checked my configuration on Additional data settings and I have
these data:
{
   "additionalData": {
      "cardHolderName": "Test Cardholder",
      "cardBin": "541333",
      "cardSummary": "1111",
      "expiryDate": "8/2018",
      "paymentMethod": "visa",
      "recurring.shopperReference": "testshopper",
      "recurring.recurringDetailReference": "1111111111111111"
   }
}

Checked checkboxes are:

   - Cardholder name
   - Card bin
   - Card summary
   - Expiry date
   - Variant
   - Recurring details

Do I need to check other checkboxes?
And why I have problem only with versions <=2.3.4?

Thank you for your help.

Regards,
Anthony


Le lun. 28 déc. 2020 à 16:36, floorjubbega <notifications@github.com> a
écrit :

**Comment by floorjubbega** [comment]
Hi @anthonyherve, 

Thank you for your response, and apologies for the delay from my side. 
We have resolved the incompatibility with **billing agreements** for version 2.4 with our [release 6.6.9.](https://github.com/Adyen/adyen-magento2/releases) 
Could you please upgrade to this version, and check if the release resolves the issue you have been seeing?

Regards, 
Floor 
Adyen

**Comment by anthonyherve** [comment]
Hello,

Thank you for your answer.
I have tested your new release 6.6.9 with Magento 2.4.1 and I have same error as first time: 500 error when I select a saved card.
The called URL is /rest/default/V1/carts/mine/set-payment-information

Thank you for your help.

Regards,
Anthony

**Comment by AlexandrosMor** [comment]
Hello @anthonyherve,

I tested also with the 2.4.1 and I cannot reproduce the issue. The steps that I followed:

1. Create a magento account
2. Make a payment with credit card and check `Save for my next payment` and complete the order 
3. Create a new order and chose to pay with the saved card

Do you have additional steps that we can try to reproduce the issue ? 

Kind regards,
Alexandros

**Comment by anthonyherve** [comment]
Hello,

Thank you for your answer.
I do exactly the same thing but I have the error. FOr your information, I
use Magento Commerce and not Magento Commnuity.

Regards,
Anthony

**Comment by anthonyherve** [comment]
Hello,

I have no additional step. I use Magento Commerce and not Magento Community. Did you test on Community or Commerce?

Thank you for your help.

Regards,
Anthony

**Comment by AlexandrosMor** [comment]
Hello @anthonyherve,

We are testing in community at the moment so we will create a commerce environment to test on our side. Did you try the one click with community too ? 

kind regards,
Alexandros 
Adyen

**Comment by tnaber** [comment]
Hi,

Closing this issue as we could not replicate the issue and it has now become stale. Please reopen if this is still an active problem for you :)

Cheers,
Titus
