### ISSUE TITLE
Add German Translation

### ISSUE THREAD

**Issue by amenk** [Adyen/adyen-magento2#908]
de_DE translation is missing.

Would a pull request be in scope or shall we translate in our theme?

**Comment by floorjubbega** [comment]
Hi @amenk, 

Thank you for opening this issue!

Could you elaborate where the translation is currently missing for you (for a certain payment method)?
Then we can further check why it might be missing and if it would need to be added.

Regards, 
Floor
Adyen

**Comment by amenk** [comment]
Basically the error message if you abort a payment is missing..there seem no de_DE CSV files. Would be great if you add them

**Comment by floorjubbega** [comment]
Hi @amenk, 

Very sorry for the delay from our side!
We currently unfortunately do not support any translations aside from English and Dutch (found [here](https://github.com/Adyen/adyen-magento2/tree/develop/i18n)). 
I will create an internal ticket, but in the meantime we suggest to add a translation file by custom adding it or adding it through a module. Let us know if you have further questions!

Regards, 
Floor
Adyen
