### ISSUE TITLE
[PW-2089]Afterpay Housenumber missing

### ISSUE THREAD

**Issue by david8305** [Adyen/adyen-magento2#913]
**Describe the bug**
Housenumber is not sent to adyen/afterpay.

**To Reproduce**
1. Go to checkout
2. Enter adress with housenumber addition (like 'c')
3. Try to place order
4. See error : REFUSED
5. Backend adyen says:
Refused (2 : Geweigerd - validatie : Failure= shipto.housenumber: field.shipto.housenumber.missing, billto.housenumber: field.billto.housenumber.missing)

**Expected behavior**
Housenumber apears not to be sent to adyen/afterpay, it should be.

I've tried:
1. Adding all adress fields to the first line
2. Adding the number and addition to the second address line.
3. Seperating all address lines like:
First line: Street
Second line: housenumber
Third line: addition

Using magento 2.3.6, adyen 6.6.5.

PSP refs from my test:

4816082169350130
1516082168929130
1316082168534430
1319082168304290
1519082167897760
4816082165767320
4516082163948260
1516082163546770
4716082161863100
1616082161760090

**Comment by AlexandrosMor** [comment]
Hello @david8305,

Thank you for raising this issue. We were able to reproduce it so we are going to investigate it and come back to you as soon as possible.

kind regards,
Alexandros

**Comment by AlexandrosMor** [comment]
Hello @david8305,

I tested this issue with after pay and checking the request I see the house number is in the request, The house number has the addition C. 
`
	"deliveryAddress": {
		"street": "Street",
		"postalCode": "2415AW",
		"city": "Leiden",
		"houseNumberOrName": "15C",
		"country": "NL"
	},
`  
Could you maybe do another test and send us the deliveryAddress ? 

kind regards,
Alexnadros

**Comment by david8305** [comment]
Hello @AlexandrosMor ,

I've just made another payment (pspref: 1619128631797611) in CA the delivery adress is shown as it should. But the aquirer response is still:


Refused (2 : Geweigerd - validatie : Failure= shipto.housenumber: field.shipto.housenumber.missing, billto.housenumber: field.billto.housenumber.missing)

Best regards,
david

**Comment by AlexandrosMor** [comment]
Hello @david8305,

After searching the transaction, I saw that the difference is that you add the house number addition with a space  for example `Street 14 C` and not `Street 14C`. Now we have more information and we can investigate it further,

regards,
Alexandros

**Comment by Alainvdz99** [comment]
Are there any updates about this issue?

**Comment by Alainvdz99** [comment]
I can confirm this has been fixed in release 6.7

**Comment by acampos1916** [comment]
Thanks @Alainvdz99,

Also, a new component is being used in #1001 for Afterpay that displays the house number field. Closing this issue now.
