### ISSUE TITLE
[PW-3708] Duplicated Quote IDs in sales_order_table

### ISSUE THREAD

**Issue by rqsakai** [Adyen/adyen-magento2#915]
**Describe the bug**
When you place an order that does not approve a payment, the module is placing an order with the current quote_id, when the customer fixes the payment data, it places the order again successfully order with the same quote_id.

The conclusion is that we have 2 orders in the database with the same quote_id

**To Reproduce**
1. Try to place an order that will refuse the payment
2. Go to the database and check the last order created
3. Fix the payment and place another order
4. Check the database again for an order with the same quote_id

**Expected behavior**
Once the order fails to place, duplicate the current quote and close the previous quote

**Comment by peterojo** [comment]
Hi @rqsakai, 
Thanks for the report. I am able to reproduce this issue, and will be looking into possible solutions together with the team.

**Comment by peterojo** [comment]
Hi @rqsakai this issue is being investigated, we will provide an update as soon as we have a working solution.

**Comment by peterojo** [comment]
Fix has been merged and will be released with the next release.

**Comment by acampos1916** [comment]
Hello @rqsakai, we've made some adjustments to this fix, would you be able to test it? https://github.com/Adyen/adyen-magento2/pull/959
