### ISSUE TITLE
Invoice isn't created if first payment failed but second approved

### ISSUE THREAD

**Issue by kisroman** [Adyen/adyen-magento2#918]
**Describe the bug**
After first payment failed and second payment is approved invoice isn't created in Magento.

**To Reproduce**
1. Create order on frontend with failed payment. Order will be created and will be in "Pending" status.
2. Find this order in backend. Go to payment section and click "Copy payment link to clipboard".
3. Open copied link in new tab. Pay with other payment method(not the same as first time).
4. Invoice should be created in Magento after run "php bin/magento cron:run", but invoice is missing in Magento.

**Expected behavior**
Payment successful and invoice is created in Magento.
**Screenshots**
<img width="710" alt="Screenshot 2020-12-18 at 17 03 43" src="https://user-images.githubusercontent.com/39631677/102629965-9652d000-4154-11eb-8f82-dc475e951a80.png">

**Comment by acampos1916** [comment]
Hello @kisroman, thank you for raising this issue.

I've been looking into this. As you can see from the order history an `OFFER_CLOSED` notification was received and the order was cancelled, then Magento can't generate an invoice. This is the way it is supposed to work.

In 6.6.1 we added a [feature to avoid order cancellation with notifications](https://github.com/Adyen/adyen-magento2/pull/692) by setting `payment/adyen_abstract/notifications_can_cancel` to false. This means that orders need to be manually cancelled when required, or new payments/invoices could be added to failed orders, maybe this is something that fits your business flow.

I'll be closing this ticket for now but let me know if you have extra feedback.

Cheers,
Ángel
