### ISSUE TITLE
Applied charge by Adyen - can we see it in Magento?

### ISSUE THREAD

**Issue by TommyKolkman** [Adyen/adyen-magento2#92]
We're using HPP, so we can't control an added fee for specific payment methods (in this example, Amex - we've got a 3,95% charge added in Adyen there).

However, these charges are never visible in Magento, and our customers wants to add them in their order export (so they can show them in their ERP, Navision in this case).

Is that (or will that ever) be possible?

**Comment by rikterbeek** [comment]
Hi @TommyKolkman,

Adding extra charge on the skin will not be shown in Magento and will not be added into the total amount. The only way to do this is by implementing payment fee inside magento. We have build this into our M1 extension but not in M2. In M1 we have seen that is can cause issues with other modules not sure if M2 have a better total structure that solves this kind of issues. At the moment we do not going to implement it into the module on a short term but you are welcome to contribute this  into our code base.

Regards,
Rik
Adyen

**Comment by peterjaap** [comment]
Any thoughs on whether you are going to pick this up? It's kinda weird that this option is offered in the Adyen control panel but there's no support for it in the Magento extension...

**Comment by rikterbeek** [comment]
Hi @peterjaap,

The skins is on the way out with our new Checkout APIs. As well adding surcharges is not compliant with PSD2.

Regards,
Rik
Adyen

**Comment by peterjaap** [comment]
As far as I understood surcharges for *creditcards* are not compliant with PSD2, but surcharges for for example Afterpay or Klarna are. See for example the explanation at https://support.stripe.com/questions/what-is-the-scope-of-the-surcharge-ban-under-psd2

**Comment by msilvagarcia** [comment]
I'm closing this issue as this is not something we want to implement in the plugin.

Ruling seemed a bit vague to our standards and we see no need to integrate this feature.

Feel free to create a new one if there are any questions left.

Cheers!
Marcos
Adyen
