### ISSUE TITLE
Cannot read property 'contentWindow' of null

### ISSUE THREAD

**Issue by killoff** [Adyen/adyen-magento2#925]
**Describe the bug**

TypeError: Cannot read property 'contentWindow' of null
  at t.iframeOnLoad (/checkoutshopper/sdk/3.4.0/adyen.js:4:159312)

/checkoutshopper/sdk/3.4.0/adyen.js in t.iframeOnLoad at line 4:159312

window._a$checkoutShopperUrl = "https://checkoutshopper-live.adyen.com/checkoutshopper/";
window._a$hppUrl = "https://live.adyen.com/hpp/";
{snip} eof this.props.callback&&this.props.callback(this.iframeEl.contentWindow)},t.prototype.componentDidMount=function(){this.iframeEl.addEventLi {snip}

**To Reproduce**

Here are the sequence of shopper requests:

POST https://SHOP_URL/de/rest/de/V1/adyen/threeDS2Process [400]
GET https://SHOP_URL/de/customer/section/load/?sections=... [200]
POST https://SHOP_URL/de/rest/de/V1/guest-carts/d8GJnZNQwp3zqQzKNI0PheSu4X1ky0em/payment-information [200]
POST https://SHOP_URL/de/captcha/refresh/ [200]
GET https://SHOP_URL/de/customer/section/load/?sections=... [200]
GET https://SHOP_URL/de/rest/de/V1/adyen/orders/461***/payment-status?_=1608643337312 [200]
POST https://SHOP_URL/de/rest/de/V1/adyen/threeDS2Process [400]
GET https://SHOP_URL/de/customer/section/load/?sections=... [200]
POST https://SHOP_URL/de/rest/de/V1/guest-carts/d8GJnZNQwp3zq******/payment-information [200]
POST https://SHOP_URL/de/captcha/refresh/ [200]
GET https://SHOP_URL/de/customer/section/load/?sections=... [200]
GET https://SHOP_URL/de/rest/de/V1/adyen/orders/461***/payment-status?_=1608643337315 [200]

**TypeError: Cannot read property 'contentWindow' of null**

**Expected behavior**
No JS errors occurred.

**Desktop:**
 - OS: win10
 - Browser Chrome 87.0.4280
 - Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36

**Comment by acampos1916** [comment]
Hello @killoff, thanks for opening this issue.

We started using `3.4.0/adyen.js` on 6.3.0 so I'm guessing it is >=6.3.0. And looks like a 3DS2 payment. With those conditions I was not able to reproduce using Chrome 87.

Is this reproducible in a clean dev/staging environment? Maybe there are some third party modules conflicting with the JS.

Best,
Ángel

**Comment by jonathanribas** [comment]
Hi,

We also had this error on our production website on Chrome 90:

**Error message**
Cannot read property 'contentWindow' of null

**Exception type**
TypeError

**Browser**
Chrome 90

**Device type**
Mobile

**Operating System**
Android

**Comment by AlexandrosMor** [comment]
Hello @marcperez,

This issue looks like an error from checkout component 
`TypeError: Cannot read property 'contentWindow' of null
at t.iframeOnLoad (/checkoutshopper/sdk/3.4.0/adyen.js:4:159312`

Could you confirm that Marc? 

thank you in advance
Alexandros
Adyen

**Comment by tnaber** [comment]
Hi,

I'm closing this as the issue has become stale. Please feel free to reopen if the problem still persists!

Cheers,
Titus
