### ISSUE TITLE
Creating Refferral Inconsistencies and inflated session counts  in Google Analytics 

### ISSUE THREAD

**Issue by grantkemp** [Adyen/adyen-magento2#93]
It appears that the plugin is missing the ?utm_nooverride=1 parameter when redirecting to store. This means that successful sales are showing up as coming from the bank ( if 3d Secure is enabled ) instead of the original Marketing source.  This is becuase Google uses the Last Non-direct attribution when logging ecommerce sales. 

Please see this link for how its been done on the original M1 adyen module. 

https://github.com/Adyen/adyen-magento/commit/3b0cd9575a7d62b0bf62d78f36d248e7c59eb174

Please can this be ported to this module so Adyen doesn't break customers Google Analytics Attribution and inflates session counts.

**Comment by rikterbeek** [comment]
Hi @grantkemp,

See commit above this should be able to fix your issues.

Regards,
Rik
Adyen

**Comment by rikterbeek** [comment]
Hi @grantkemp,

This will be in 2.0.4 release, the release date is not yet defined.

Regards,
