### ISSUE TITLE
[PW-3707] Cannot place order with other than Adyen payment method

### ISSUE THREAD

**Issue by vileyne** [Adyen/adyen-magento2#937]
**Describe the bug**
If not only Adyen payment methods are used on webshop (e.g. default magento "Check/Money Order"), button "Place Order" is disabled for these payment methods and therefore order cannot be placed.

**To Reproduce**
1. Go to Admin panel - Stores -> Configuration -> Sales -> Payment Methods
2. Enable "Check/Money Order"
3. Go to FE - add product to cart and proceed to checkout
4. Fill data, go to payment step
5. Select "Check/Money Order" 
6. See button "Place Order" is disabled

**Expected behavior**
Button "Place Order" is enabled, order can be placed with other than Adyen payment methods.

**Magento version**
2.3.5

**Plugin version**
6.1.1

**Additional context**
Issue is caused by https://github.com/Adyen/adyen-magento2/blob/develop/view/frontend/web/js/view/payment/method-renderer/adyen-hpp-method.js#L220. In our case, once Ideal is rendered, original isPlaceOrderActionAllowed set to false which disables the button for default magento payment methods.

**Comment by peterojo** [comment]
Hi @vileyne, thanks for reporting this issue. 
I am able to reproduce the problem and I will create an internal ticket to fix it.

**Comment by peterojo** [comment]
Hello @vileyne, just a quick confirmation, we were only able to reproduce this issue when we enable 'Terms $ Conditions`. Can you please confirm whether this bug still exists with 'T & C' disabled?

**Comment by vileyne** [comment]
> Hello @vileyne, just a quick confirmation, we were only able to reproduce this issue when we enable 'Terms & Conditions`. Can you please confirm whether this bug still exists with 'T & C' disabled?

I cannot confirm that, on our project this bug exists with disabled 'Terms & Conditions' (but maybe it is related to our customizations).

**Comment by peterojo** [comment]
Hi @vileyne can you test the changes in [this PR](https://github.com/Adyen/adyen-magento2/pull/954) to see if your issue is solved?

**Comment by vileyne** [comment]
> Hi @vileyne can you test the changes in [this PR](https://github.com/Adyen/adyen-magento2/pull/954) to see if your issue is solved?

Hi @peterojo,
Tested -> our issue is solved, thanks!
