### ISSUE TITLE
PHP Fatal error:  Declaration of Adyen\Payment\Tests\Helper\DataTest::setUp()

### ISSUE THREAD

**Issue by tuanhatay88** [Adyen/adyen-magento2#939]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Magento version**
[e.g. 2.4.1]

**Plugin version**
[e.g. 6.6.8]

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by tuanhatay88** [comment]
PHP Fatal error:  Declaration of Adyen\Payment\Tests\Helper\DataTest::setUp()

**Comment by AlexandrosMor** [comment]
Hello @tuanhatay88, 

Would you like to send us more information about this issue? It would be great to explain us how we can reproduce it. 

kind regards
Alexandros

**Comment by acampos1916** [comment]
Hi @tuanhatay88 I'll be closing this issue now but let us know if you have more information about it.
