### ISSUE TITLE
localization for text "The payment is REFUSED"

### ISSUE THREAD

**Issue by moiashvin** [Adyen/adyen-magento2#946]
**Describe the bug**
In the code, the text used is __('The payment is REFUSED.');  
while in the i18n csv files, the text available is 'The payment is REFUSED' 
Issue is the csv file needs to be updated with the full stop.

**Expected behavior**
Add the full stop in the i18n for text "The payment is REFUSED"

**Magento version**
2.4.1
[e.g. 2.4.1]

**Plugin version**
6.6.8

**Comment by acampos1916** [comment]
Thanks for creating this issue @moiashvin. It is being fixed in #947
