### ISSUE TITLE
[PW-3880] Unable to check checkout agreements for alternative payment methods (HPP)

### ISSUE THREAD

**Issue by Skullsneeze** [Adyen/adyen-magento2#948]
**Describe the bug**
When checkout agreements are enabled, and the target Terms and conditions are set to be applied manually the checkbox to agree with the terms and conditions cannot be checked for alternative payment methods, with the exception of the first alternative payment method.

This is happening because Magento generates the ID of the input field based on data that is set for the specified payment method. In the case of alternative payment methods (HPP) this data is missing.

**To Reproduce**
1. In the Magento admin, go to Stores > Configuration > Sales > Checkout and under "Checkout options", set "Enable Terms and Conditions" to "Yes"
2. In the Magento admin, go to Stores > Terms and Conditions, and add a new condition with "Applied" set to "Manual"
3. Navigate to the payment page, and select an alternative payment method (other than the first), and try to check the terms and conditions checkbox
4. The checkbox will not be selected

**Expected behavior**
When clicking the checkbox for the terms and conditions, I expect the checkbox to be checked.

**Magento version**
2.3.6

**Plugin version**
6.6.9

**Desktop (please complete the following information):**
 - OS: macOs Mojave 10.14.6
 - Browser: Chrome
 - Version: 87.0.4280.141

**Comment by acampos1916** [comment]
Hey @Skullsneeze thanks for opening this issue.

I can confirm that the IDs for the T&C checkboxes are the same for all HPP methods. I've created an internal ticket to work on this.

Best,
Ángel

**Comment by acampos1916** [comment]
Thanks for the PR @Skullsneeze, it has been merged.

**Comment by Skullsneeze** [comment]
Cheers @acampos1916, thanks for the quick response!
