### ISSUE TITLE
Uncaught TypeError: Cannot read property 'split' of null at Encryption.createRSAKey

### ISSUE THREAD

**Issue by advokata** [Adyen/adyen-magento2#95]
When i click Place Order on my Magento 2 I got this JavaScript error. All required settings in admin panel about adyen is configured except Webservice username for Live	and Webservice Password for Live because I don't have that yet. Screenshot https://www.dropbox.com/s/qnlyz1jjlznha5y/Screenshot%202017-03-04%2000.34.24.png?dl=0

adyen.encrypt.min.js:16 Uncaught TypeError: Cannot read property 'split' of null
    at Encryption.createRSAKey (adyen.encrypt.min.js:16)
    at Encryption.encrypt (adyen.encrypt.min.js:16)
    at UiClass.placeOrder (adyen-cc-method.js:157)
    at HTMLButtonElement.<anonymous> (knockout.js:3863)
    at HTMLButtonElement.dispatch (jquery.js:4624)
    at HTMLButtonElement.elemData.handle (jquery.js:4292)

**Comment by rikterbeek** [comment]
Hi @advokata,

Did you entered a CSE encryption key in the configurations ?

Regards,
Rik
Adyen

**Comment by advokata** [comment]
Where to find it in the adyen admin panel

**Comment by rikterbeek** [comment]
Hi @advokata,

Got to settings -> users  and select your webserver user. If you need any help please contact our support at support@adyen.com.

Regards,

**Comment by Mage2you** [comment]
the same issue with me on test account with magento2 . Although I have configured the CSE public key in my magento admin.

**Comment by rikterbeek** [comment]
Hi @Mage2you,

I really don't think it is a coding issue. Could you please raise this questions to our magento@adyen.com they would able to help out where the problem lies.

Regards,
Rik
Adyen
