### ISSUE TITLE
To close the 3D secure window that cannot proceed the checkout 

### ISSUE THREAD

**Issue by lyvia-chung** [Adyen/adyen-magento2#958]
**Describe the bug**
We are using the adyen plug-in.   on the checkout page selected the credit card and fill-in all the required information. 
when 3D pop-up then close the 3D window w/o input anything.   
resubmit the  order.  and I will  get the error message "Keine Eintrag mit cartid=779"  and this order would never able to submitted

**To Reproduce**
1. On the checkout page, input the  Credit Card information 
2. Click on 'Submit Order'
3. 3D secure pop-up 
4. Close the 3D secure w/o input anything
5. return to the checkout page
6. either to resubmit the order or change the payment method and submit the order
7. we will always get the error message.  

**Expected behavior**
I expected that order can still be processed.  

**Magento version**
[2.3.4].  will upgrade to 2.3.4-p2 soon

**Plugin version**
[6.6.5]

**Screenshots**
[ErrorWhen Place Order.docx](https://github.com/Adyen/adyen-magento2/files/5884099/ErrorWhen.Place.Order.docx)

**Desktop (please complete the following information):**
 - OS: [Win10]
 - Browser [chrome]
 - Version 87.0.4280.141 (Official Build) (64-bit)]

**Smartphone (please complete the following information):**

**Additional context**

**Comment by AlexandrosMor** [comment]
Hello @lyvia-chung,

Thank you for raising this issue. I was trying to reproduce the issue but with no success. In our test environment I placed an order and in the checkout page I used a 3ds2 test card. It is not possible to close the pop up if the user do not provide anything for password. Using a 3ds1 card redirects to 3ds1 authentication page and then I returned to the store with the browser back button. The cart is empty and I simple create a new order which is not throwing any errors. Could you explain us how do you close the pop up for 3ds2  ?  Furthermore, did you modified any parts of the plugin ?

kind regards,
Alexandros

**Comment by lyvia-chung** [comment]
Hi, Alexandro, 
I will close the ticket as tested in Production that's  different behavior .   I will created separated ticket for production. 

regards, 
Lyvia
