### ISSUE TITLE
Module Changes the checkout layout

### ISSUE THREAD

**Issue by juanmtnez** [Adyen/adyen-magento2#96]
After installing you module the complete layout of the checkout changed.
I realized that the problem was on the checkout_index_index.xml file. The layout there is "1column" and the layout on the checkout must be "checkout" (no menu, no footer,...)

thanks!

**Comment by rikterbeek** [comment]
Hi @juanmtnez,

Sorry for the late reply. Above fix should solve your issue.

Regards,
Rik
Adyen

**Comment by juanmtnez** [comment]
Thanks a lot!!

Juan.
