### ISSUE TITLE
[PW-4236] Order status stuck in 'Payment Review'

### ISSUE THREAD

**Issue by lucygecko** [Adyen/adyen-magento2#963]
We have an issue where occasionally a successful orders status isn't updated from 'Payment Review'

In the Adyen interface I can see that the payment is successful and Magento & Adyen are communicating well.

Cron logs show everything is completed succesfully for the order. 

The comments on the Magento order show the state should have changed to Processing.

Looks to be similar to the following reported issues:
#782 #887 #936 

This only happens intermittently, so is hard to reproduce.

**Expected behavior**
Order that are processed successfully should be updated to processing status.

Magento 2.3.5 P2

**Comment by cyattilakiss** [comment]
Hi @lucygecko ,

Have you had the chance to update to a later version of 7?
The related issues you also mentioned in your issue description has already been closed and verified so there is a big chance that your issue is as well fixed.
Please let us know.

Best,
Attila

**Comment by tnaber** [comment]
Hi,

I'm closing this as the issue has become stale. Please feel free to reopen if the problem still persists!

Cheers,
Titus
