### ISSUE TITLE
No field validation on credit card when leave it blank

### ISSUE THREAD

**Issue by lyvia-chung** [Adyen/adyen-magento2#964]
**Describe the bug**
When place the credit card order,  we can leave the fields empty but submitting the order 
Is that anyway we can check all the fields been input before to submit the order 

**To Reproduce**
1. Go to checkout page
2. select the credit card as payment method
3. no input on all the fields.  e.g.  credit card,   expire day, CVV.. etc but submit the order
4. the system will only show the name with error red box but not the other fields

**Expected behavior**
when leaving the credit card input box w/o enter anything,  the system should give the red box just like field - Name

**Magento version**
 2.3.4-p2 

**Plugin version**
[6.6.5]

**Screenshots**
<img width="482" alt="checkout error" src="https://user-images.githubusercontent.com/78121371/107615818-d3849b80-6c87-11eb-9813-e044e0f99be6.png">

**Desktop (please complete the following information):**
OS: [Win10]
Browser [chrome]
Version 87.0.4280.141 (Official Build) (64-bit)]

**Smartphone (please complete the following information):**

**Additional context**

**Comment by AlexandrosMor** [comment]
Hello @lyvia-chung,

Thank you for raising this issue. I tried to reproduce it but the place order button is disabled when the credit card fields are empty.  In order for the button to enable it needs to have all the fields set. Could you please try it in a clean magento installation ?

kind regards,
Alexandros
Adyen

**Comment by lyvia-chung** [comment]
Hi, @AlexandrosMor ,

Thanks for your response.  Do you have demo site that we can access to test?

regards, 
Lyvia

**Comment by lyvia-chung** [comment]
The issue had been fixed on our end.   I can close it.
