### ISSUE TITLE
Wrongfully disabled place order button hpp payment methods

### ISSUE THREAD

**Issue by Thokoop** [Adyen/adyen-magento2#966]
**Describe the bug**
The 'place order' button for the hpp methods are all initially disabled. 
When selecting iDeal and a bank from the dropdown the other hpp payment methods 'place order' buttons get enabled again.

**To Reproduce**
1. Make sure to have the following methods enabled, preferably even with this exact sorting order:
-  iDeal
-  Klarna
-  VVV Giftcard
2. Go to the checkout and select the radio button of the Klarna or VVV giftcard payment method
3. Note that the button doesn't have the 'disabled' attribute but it does have the class 'disabled' (with css pointer-events: none; ) 
4. Select the iDeal payment method and select an issuer from the dropdown.
5. Note that the button is enabled for iDeal and other hpp payment methods.

**Expected behavior**
The place order button is initially only disabled for payment methods that require additional input from the end-user.

**Magento version**
2.4.1

**Plugin version**
6.6.8

**Screenshots**
![Afrekenen++Rivi%C3%A8ra+Maison+2021-01-12+22-19-50](https://user-images.githubusercontent.com/11939567/107626302-dff3fe80-6c5d-11eb-98ec-334f80c924f6.png)

**Desktop:**
 - OS: Ubuntu 20.04.2 LTS
 - Browser : Chrome 
 - Version 88.0.4324.96 (Official Build) (64-bit)

**Additional context**

I've created the following patch that fixes the issue. Since the buttons are only disabled because of the css class, I've used the existing placeOrderAllowed() function that is already used to enable the button by removing the 'disabled' attribute from the button element to make it consistent.

```diff --git a/view/frontend/web/template/payment/hpp-form.html b/view/frontend/web/template/payment/hpp-form.html
--- a/view/frontend/web/template/payment/hpp-form.html
+++ b/view/frontend/web/template/payment/hpp-form.html
@@ -318,7 +318,7 @@
                                 data-bind="
                                     click: continueToAdyenBrandCode,
                                     enable: placeOrderAllowed() && (value == $parent.isBrandCodeChecked()),
-                                    css: {disabled: !$parent.isPlaceOrderActionAllowed()}"
+                                    css: {disabled: !placeOrderAllowed()}"
                                 disabled>
                             <span data-bind="text: $t('Place Order')"></span>
                         </button>```

**Comment by killoff** [comment]
Can confirm the issue. We have Alternative Payment Methods enabled (Adyen_hpp)
We use Klarna, Giropay and Sepa.
Apparently, button "Place Order" for Klarna and Giropay depends on Sepa form.

As long as Sepa form not filled in (Name and Account number) - it is impossible to place order with Klarna/Giropay.

See screenshots

### Sepa form is not filled in:
<img width="579" alt="Screenshot 2021-03-30 at 14 21 59" src="https://user-images.githubusercontent.com/3583507/112988311-fbf72500-9163-11eb-9c8d-2b8d26ad877c.png">
<img width="553" alt="Screenshot 2021-03-30 at 14 22 06" src="https://user-images.githubusercontent.com/3583507/112988318-fdc0e880-9163-11eb-9b46-0209524e31d0.png">


### Sepa form is filled in:

<img width="578" alt="Screenshot 2021-03-30 at 14 22 16" src="https://user-images.githubusercontent.com/3583507/112988321-fef21580-9163-11eb-84bf-2416ab0874cc.png">
<img width="419" alt="Screenshot 2021-03-30 at 14 22 22" src="https://user-images.githubusercontent.com/3583507/112988322-ff8aac00-9163-11eb-9c07-9293e1ed4c99.png">

**Comment by acampos1916** [comment]
Hello @Thokoop @killoff sorry for the late response on this one.

I see that the way the HPP methods are rendered and the button enabled/disabled was rewrote in the latest version of the plugin, are you able to verify if this is still an issue for you using >7.0.0?

**Comment by killoff** [comment]
@acampos1916 Unfortunately it's reproduced on 7.0.1
I was debugging view/frontend/web/js/view/payment/method-renderer/adyen-hpp-method.js, but no luck.
I expect, that selectPaymentMethodType() should call smth like validate and change "Place Order" button state from disabled to enabled, but it does not.

So far, I desperately rewritten web/template/payment/hpp-form.html and hardcoded enabled to "true".
Since Alternative Payment Methods normally do not expect additional data to enter from customer.

**Comment by acampos1916** [comment]
Thanks for the info @killoff. Seeing as your temporary fix is different than @Thokoop's it looks like this this issue might have different causes in  v6 and v7.

@killoff since `enable` originally uses `$parent.isButtonActive()` could you debug that function to check why it isn't returning true in your instance? https://github.com/Adyen/adyen-magento2/blob/7.0.1/view/frontend/web/js/view/payment/method-renderer/adyen-hpp-method.js#L683-L686

**Comment by tnaber** [comment]
Hi @killoff,

I have not been able to recreate this issue in my local v7 version. Is this still a problem for you?

Cheers,
Titus
