### ISSUE TITLE
Possible issue with Magento 2.4.2 and Google Analytics

### ISSUE THREAD

**Issue by brightonmike** [Adyen/adyen-magento2#969]
Please be aware I've experience conflicts between the Adyen Web JS library and Magento 2.4.2 when Google Analytics is enabled.

The related issue on Magento repository can be found here: https://github.com/magento/magento2/issues/31916

For now, I've resolved by overriding the guilty file and removing the prototype library dependancy.

Specifically, the issue is caused by the prototype library overriding the `node.remove()` method.

**Comment by acampos1916** [comment]
Thanks for the heads up @brightonmike

**Comment by aisoly** [comment]
@brightonmike Hello, how do you deal with this problem，Can you provide specific processing code！Thanks

**Comment by brightonmike** [comment]
@aisoly you need to override the core Universal Analytics JS file to remove the dependancy on prototype library

**Comment by aisoly** [comment]
@brightonmike Can you provide some help, I know jquery but not prototype, can you provide the source code you processed, thank you!

**Comment by andrewdaluz** [comment]
Thank U @brightonmike 
I was able to fix it by applying a patch and removing the prototype requirement on: vendor/magento/module-google-tag-manager/view/frontend/web/js/google-analytics-universal.js

I hope this helps someone else who needs it. As the patch MDVA-33289 doesn't fix it.
