### ISSUE TITLE
Terms and conditions acceptance with HPP method fails when customer is logged in

### ISSUE THREAD

**Issue by ebaschiera** [Adyen/adyen-magento2#97]
Hi,
if I enable one or more Terms and Conditions, at checkout the customer is required to check each checkbox before placing the order. The checkboxes appear below each payment method.
With HPP methods the backend validation fail all the time when customer is logged in.
Please note that the javascript validation is ok, it's the server-side validation that returns an error.
I debugged a bit, and found out that the exception is thrown in vendor/magento/module-checkout-agreements/Model/Checkout/Plugin/Validation.php::validateAgreements().
I could not understand why the agreements array is empty when it reaches that validation.
I am on Magento EE 2.1.4 Luma theme.

Thanks.
Best regards.

**Comment by rikterbeek** [comment]
Hi @ebaschiera,

Sorry for the late reply. This commit below should solves your issue. 

Regards,
Rik
Adyen

**Comment by ebaschiera** [comment]
Hi @rikterbeek ,
thanks a lot for the fix. It works perfectly.

Best regards.
