### ISSUE TITLE
RC2 HPP/PayPal odd behaviour with virtual/gift card orders

### ISSUE THREAD

**Issue by brightonmike** [Adyen/adyen-magento2#971]
**Describe the bug**

When you have an order which is only virtual products or virtual gift card, the Adyen HPP methods behave oddly.

- Klarna, Apple Pay and Google Pay do not get returned and do not render
- PayPal renders, but does not function, when you click the button the checkout gets stuck in a loading state

**To Reproduce**

1. Add a virtual product or virtual gift card to order
2. Proceed to checkout
3. Proceed to payment
4. Observe missing Klarna, Apple Pay and Google Pay
5. Attempt to use PayPal

**Expected behavior**

1. Not sure if Klarna, Apple Pay and Google Pay should work, possibly not? Although, why not?
2. PayPal should either function correctly or not be returned

Please note I originally observed this bug using Adyen in a headless React checkout.

Via headless, the issue seems to occur with PayPal when you pass the action data e.g. `paymentComponent.handleAction(adyenActionData);`

I think the action data is either wrong, or missing something. It is returning as "pending" and the component handleAction does nothing. It's odd to me that PayPal shows, but Klarna/AP/GP do not and it's also suspicious that PayPal breaks. 

With core, the issue is a bit different, it's bugging out looking for shipping address data but there is no shipping address for virtual orders. You can't even get to the handleAction, but I suspect that even if you could you would then get the same issue as I'm getting via headless where the handleAction doesn't do anything.

If core was working, it'd probably show what we've done wrong on headless.

```
if (!!quote && !!quote.shippingAddress()) {
    city = quote.shippingAddress().city;
    country = quote.shippingAddress().countryId;
    postalCode = quote.shippingAddress().postcode;
    street = quote.shippingAddress().
        street.
        join(' ');
    firstName = quote.shippingAddress().firstname;
    lastName = quote.shippingAddress().lastname;
    telephone = quote.shippingAddress().telephone;

    if (!!customerData.email) {
        email = customerData.email;
    } else if (!!quote.guestEmail) {
        email = quote.guestEmail;
    }

    shopperGender = customerData.gender;
    shopperDateOfBirth = customerData.dob;
}
```

**Magento version**
2.4.2

**Plugin version**
7.00 RC-2

**Screenshots**

<img width="1643" alt="Screenshot 2021-02-23 at 10 34 41" src="https://user-images.githubusercontent.com/2071150/108832797-ea9a8600-75c3-11eb-97c4-d6b4ca7f7772.png">

**Comment by brightonmike** [comment]
For me changing the street JS to the following seems to resolve the problem:

```
                                    street = quote.shippingAddress().
                                    street ? quote.shippingAddress().
                                        street.
                                        join(' ') : '';```

**Comment by AlexandrosMor** [comment]
Hello @brightonmike,

Thank you for raising this issue. The 7.00 RC-2 is patched some times so I would suggest to update the plugin version to the latest one. Furthermore, I tested klarna, google pay, paypal and all of them works fine for 7.0.1. 
If you have more questions or issues feel free to open a new issue.

kind regards,
Alexandros
Adyen

**Comment by acampos1916** [comment]
Also related to #1066
