### ISSUE TITLE
[PW-4524] BIZUM PAYMENT METHOD

### ISSUE THREAD

**Issue by Mecalux-Developer** [Adyen/adyen-magento2#974]
Hi, 

Can you implement the bizum payment method?

https://bizum.es/en/

Thanks

**Comment by cyattilakiss** [comment]
Hi @Mecalux-Developer ,

Thank you for raising this issue.
At the moment Adyen doesn't provide the bizum payment method but as soon as it gets added (the core teams are going to look into it) to our list of offers we are also going to implement it into the plugin.

I have created an internal ticket and going to close this issue for now.

Best,
Attila
Adyen

**Comment by Mecalux-Developer** [comment]
Thanks! 👍
