### ISSUE TITLE
Some paid orders are stuck on status / state new / pending 

### ISSUE THREAD

**Issue by rutgerrademaker** [Adyen/adyen-magento2#983]
**Describe the bug**
One of our clients is experiencing issues with Adyen payments (probably since they updated to 6.6.8 / magento 2.4.1)
Somehow the comments / status history looks like this for a lot of orders

```
Mar 15, 2021 8:04:17 PM Pending Customer Notified
Mar 15, 2021 8:04:17 PM
Mar 15, 2021 8:05:38 PM
Mar 15, 2021 8:10:05 PM Processing
Mar 15, 2021 8:10:05 PM Processing
Mar 15, 2021 8:10:05 PM Pending
Mar 15, 2021 8:10:05 PM Invoice #3000013486 created
```

As you can see there are 3 status updates in the same second, the latest one is (new) / pending but in this case the order was actually paid

When looking at store using  6.6.9 / magento 2.4.1 In another store also see similar issues

```
Mar 2, 2021 12:57:44 PM Pending Customer Notified
Mar 2, 2021 12:57:44 PM
Mar 2, 2021 12:57:50 PM
Mar 2, 2021 12:59:02 PM Processing
Mar 2, 2021 12:59:02 PM Pending
Mar 2, 2021 12:59:02 PM Pending
Mar 2, 2021 12:59:02 PM Invoice #000000133 created Customer Notified

```

**To Reproduce**
1. Place an order
2. Log into the admin, open the order > comments history
3. See that, for some orders,  multiple conflicting status updates are done in the same second

N.B. the error does not apply to all orders, for some it goes well(!)

**Expected behavior**

* No duplicate / conflicting status updates are done in the same second
* Order should not be left in the new/pending state when it was actually paid for

**Magento version**
2.4.1 / 2.4.1-p1

**Plugin version**
6.6.8 / 6.6.9

**Comment by berkanduzgun** [comment]
Here are some additional findings.

The order is placed using iDeal.

![Selection_010](https://user-images.githubusercontent.com/1146294/112158524-8a115f80-8be8-11eb-9cf9-8d71c3780613.png)

For iDeal an authorisation event is created in the notifications table.

![Selection_011](https://user-images.githubusercontent.com/1146294/112158855-dceb1700-8be8-11eb-85ee-50e849400671.png)

Isn't iDeal a capture only method. I believe after the invoice is created after the Adjen cron job which processed the notification, Magento interfered and changed the status back to pending. Because the payment transaction is also in Authorization state not capture.

Can you help us solve the issue?

**Comment by ryanpalmerweb** [comment]
We are also experiencing this issue with ideal payments - they are showing as not captured, an invoice is not created and an amount due remains against the order, however the Adyen interface shows the payment has been captured immediately.

Below you can see the order comments from an order where this has happened - when the order was initially placed an authorisation was created with the following output 'Payment is authorised waiting for capture'

Further down when an admin attempts to manually capture the order, Adyen is returning 'This is sale transaction, ignoring this request' but then it is allowing Magento to create an invoice, mark the order as processing and removes the amount due.

**Initial order placed** 

Mar 14, 2021 8:24:12 Processing (not captured)  - Customer Not Notified
Payment is authorised waiting for capture

Mar 14, 2021 8:24:12 Pending  - Customer Not Notified
Adyen HTTP Notification(s):
eventCode: AUTHORISATION
pspReference: XXX
paymentMethod: ideal
success: true

Mar 14, 2021 8:23:13  - Customer Not Notified
Adyen Result URL response:
authResult: Authorised
pspReference: XXX
paymentMethod: ideal

Mar 14, 2021 8:19:04  - Customer Not Notified
Adyen Result response:
authResult: RedirectShopper

**Admin attempted to perform an online capture**

Mar 31, 2021 12:29:04 Processing  - Customer Not Notified
Adyen HTTP Notification(s):
eventCode: CAPTURE
pspReference: XXXX
paymentMethod: ideal
success: true
reason:This is sale transaction, ignoring this request

Mar 31, 2021 12:25:36 Processing  - Customer Not Notified
Captured amount of €287.10 online. Transaction ID: "XXXX-capture"

Mar 31, 2021 12:25:36 Processing (not captured)  - Customer Not Notified
Adyen Result response:
authResult: [capture-received]
pspReference: XXXX

**Comment by acampos1916** [comment]
Hello @rutgerrademaker @berkanduzgun @ryanpalmerweb sorry for the late reply.

I recently attempted to reproduce this in the version 6.6.8 of the plugin. Using iDeal I received only 1 notification for AUTHORISATION, when this notification is processed by the cronjob the order comments look like this:
<img width="432" alt="Screen Shot 2021-06-09 at 4 40 47 PM" src="https://user-images.githubusercontent.com/15349721/121376116-8bc60600-c941-11eb-9a1b-de3ee8585963.png">

So, 2 comments when the order is still in Pending, and afterwards the order is moved to Processing (there's no comment for that order status change, but the order is in Processing when the cronjob finishes).

Is there something extra I can do to reproduce the issue?
