### ISSUE TITLE
[PW-4742] Adyen partial refund - pspreference don't match and of by one cent refunds

### ISSUE THREAD

**Issue by JeroenBoersma** [Adyen/adyen-magento2#987]
**Describe the bug**
When we have partial refunds based on multiple credit-memo's there is no clear reference which refund belongs to which creditmemo. The reference is only back to the original order.

There are 2 things off here:
- price in cents of by cents with the refund (checked the refund setting, which is based on `refund from first payment first`
- the reference in `adyen_notification` is the order increment id and not the credit memo id

**To Reproduce**
1. Create a partial refund
2. Refund online
3. A log record `REFUND` is returned in `adyen_notification`

**Expected behavior**
There should be a correct relation back to the actual refund.
This could be

**Magento version**
`2.4.1`

**Plugin version**
`6.6.9`

**Screenshots**
Backend setting for refund
![image](https://user-images.githubusercontent.com/1163348/112502427-5a9a5880-8d8a-11eb-995a-b3e0966a8cd0.png)

Related data in `adyen_notification`
![image](https://user-images.githubusercontent.com/1163348/112503211-05ab1200-8d8b-11eb-98e0-59b654a0e92b.png)

**Additional context**
We cannot match the `pspreference` with the corresponding credit memo which makes it impossible to do a reconciliation.
Also a second refund doesn't create a extra transaction in the transactions table (this could be a Magento issue)

**Magento insides**
- Credit memos are linked to Orders
- Invoices are linked to Orders
- Payments are linked to Orders
- Transactions are linked to Payments
- No reference exists between Invoice/Credit memo and Transactions/Payments

**Comment by peterojo** [comment]
Hi @JeroenBoersma thanks for opening this issue, we will investigate it and keep you posted.

**Comment by AlexandrosMor** [comment]
Hello @JeroenBoersma,

For the first point about the prices, the transaction amount needs to be represented in minor units according to the following [table](https://docs.adyen.com/development-resources/currency-codes).
Furthermore the `adyen_notification` table stores the notification data as are provided from the Adyen backend and the table is not updated based on the credit memo. 
I hope these information helps you. 

kind regards,
Alexandros
Adyen

**Comment by JeroenBoersma** [comment]
Working out an full example together with our customer, we'll post this here today!

We understand your response, my question is not specific enough.

**Comment by JeroenBoersma** [comment]
We have responded in a support ticket `2094827`, the price part is something we will park.
But matching Credit Memo's with refunds is something that needs attention.

Hope we can work this out

**Comment by AlexandrosMor** [comment]
Hello @JeroenBoersma,

We are going to pick up this issue in the future as an investigation ticket to see if we could connect the credit memos with the refund notification using the `pspreference`. 

kind regards,
Alexandros 
Adyen

**Comment by JeroenBoersma** [comment]
still awaiting response

**Comment by tnaber** [comment]
Hi @JeroenBoersma, 

Sorry for it taking a while for this to be picked up. In #1317 we propose the following solution to this problem: 
- The table 'adyen_creditmemo' has been added 
- adyen_creditmemo contains all individual partial refunds tied to a specific creditmemo (in sales_creditmemo) 
- every entry contains: 
    - unique id, 
    - pspreference of refund request,
    - original pspreference (link to original payment request), 
    - creditmemo_id (foreign key to sales_creditmemo), 
    - amount (in the paid currency, not in cents), 
    - adyen_order_payment_id (foreign key to adyen_order_payment, similar to original pspreference) 

This solution enforces the following behavior:
- _Scenario 1: A single payment is partially refunded multiple times._
In this case the 'adyen_creditmemo' table will contain an entry for each of these partial refunds. These entries will be linked to the same overarching creditmemo in 'sales_creditmemo' and the corresponding payment in 'adyen_order_payment'.

- _Scenario 2: Multiple partial refunds are triggered in the case of a full refund of an order that has been completed using multiple payment methods (e.g. partially paying with your gift card and completing with your credit card)._
In this case the refund to each payment method will have their own entry in the 'adyen_creditmemo' table. In case of the example, both entries will be linked to the same overarching creditmemo in 'sales_creditmemo'. Additionally, the entries will be linked to their individual payment in 'adyen_order_payment'.

Regarding the example in your issue:
A link between the refund notification in 'adyen_notifcation' and the creditmemo's, such a link is now created by the 'original_reference' in 'adyen_creditmemo' and 'pspreference' in 'adyen_notification'. 

To conclude:
We feel that this change should implement a sufficient link between the different creditmemo's, Adyen's refund requests and their corresponding payments. However, we would love your input on this! Let me know what you think :)

Cheers,
Titus

**Comment by RokPopov** [comment]
Hi @JeroenBoersma ,

As the solution has been proposed in #1317 I am closing this issue for now, however if you have any input or feedback for us, please feel free to reopen it.

Thank you in advance,

Kind regards,
Rok,
Adyen
