### ISSUE TITLE
[PW-3410] Amazon Pay (end checkout support)

### ISSUE THREAD

**Issue by fahu** [Adyen/adyen-magento2#995]
As Adyen offers full support for Amazon Pay (including recurring payments, https://docs.adyen.com/payment-methods/amazon-pay) I would expect the Adyen Magento 2 plugin to also support Amazon Pay.

Is there already a timeline / roadmap when Amazon Pay will be supported by the Magento 2 module?

**Comment by msilvagarcia** [comment]
Hey @fahu !

It's definitely in our roadmap, but we don't have a timeline yet.

Cheers!
Marcos
Adyen
