### ISSUE TITLE
Paid orders intermittently stuck on 'Payment Review' status, as well as Total Due failed to update

### ISSUE THREAD

**Issue by roby0404** [Adyen/adyen-magento2#997]
Basically, as the title says, intermittently, notifications process cronjob failed to update order status as well as Total Due value, even though invoice was created correctly during the cronjob process, and order was paid successfully and was supposed to have its status updated to the status specified in the payment method configuration.

I've noticed that this was a general bug inside the module that several people reported, so it wasn't specific to different environments with different third-party modules installed which could possibly affect this somehow.

It was practically impossible to get anything useful out of any logs I placed regarding this issue, as even the logs that Adyen has inside the Cron.php class were indicating that data was about to be saved correctly, but in the end, it wasn't. I was suspecting that something else was interfering the process of saving the order entity.

In the end, since adyen_payment_process_notification cronjob is defined in a different cron group, which is supposed to use separate PHP process during its run, it was my main point of suspicion, hence I started checking the cron logs.

In the end, the pattern was always the same for all orders that had this issue:

1. adyen_payment_process_notification cronjob started 
2. sales_send_order_emails cronjob started 
3. adyen_payment_process_notification cronjob finished 
4. sales_send_order_emails cronjob finished

Which lead me to conclusion that this issue happened because those 2 cronjobs were overlapping in this way from time to time,  and both are supposed to save some data against order entity at some point of their execution.

Unfortunately, I can't explain in detail what can possibly happen in this situation for data set to order entity in adyen_payment_process_notification to fail to be saved, as I couldn't reproduce and debug this in my local environment, so I had to create this theory only due to the repeating scenario inside cron.log as specified above, and apply a fix on production to test my theory out.

So, when I moved adyen_payment_process_notification cronjob to default cron group to prevent them from overlapping, like so:

```
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:module:Magento_Cron:etc/crontab.xsd">
    <group id="default">
        <job name="adyen_payment_process_notification" instance="Adyen\Payment\Model\Cron" method="processNotification">
            <schedule>*/1 * * * *</schedule>
        </job>
    </group>
    <group id="adyen_payment">
<!--        <job name="adyen_payment_process_notification" instance="Adyen\Payment\Model\Cron" method="processNotification">-->
<!--            <schedule>*/1 * * * *</schedule>-->
<!--        </job>-->
        <job name="adyen_payment_server_address_caching" instance="Adyen\Payment\Cron\ServerIpAddress" method="execute">
            <schedule>*/1 * * * *</schedule>
        </job>
    </group>
</config>
```

This issue didn't re-appear since then (6 days so far), and it's worth noting that it happened intermittently on a few orders throughout one day.

I hope this will help you and others who have the same issue.

Best regards,

Rob

**Comment by acampos1916** [comment]
Hello @roby0404, glad to see that you were able to fix that issue by moving the Adyen cronjob to the default cron group. Is it possible that the Magento instance was only configured to run the default cron group? As you can see from the Magento documentation the recommendation is to run all cron groups https://devdocs.magento.com/guides/v2.4/config-guide/cli/config-cli-subcommands-cron.html

I'll close this issue now but if you have any recommendations let us know.
